import { UNIVERSAL_V1_UI_FIELD_MANIFEST } from "../../application/intake/lb51/UniversalV1UiFieldManifest";
import { SUPPLY_VERTICAL_FIELD_MANIFEST } from "../../application/intake/lb93/SupplyVerticalFieldManifest";

const FIELD_DEFS = JSON.stringify([
  ...UNIVERSAL_V1_UI_FIELD_MANIFEST,
  ...SUPPLY_VERTICAL_FIELD_MANIFEST,
].filter((item, index, all) => all.findIndex(other => other.fieldPath === item.fieldPath) === index));

export const SUPPLY_USER_JOURNEY_UI = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Contrata-IA · Contrato de suministro</title>
<style>
body{font-family:Arial,sans-serif;margin:0;background:#f4f6f7;color:#17202a}header{background:#fff;border-bottom:1px solid #ddd;padding:18px 24px}main{max-width:1160px;margin:20px auto;padding:0 16px}.card{background:#fff;border:1px solid #ddd;border-radius:8px;padding:18px;margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.stages{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.stage{padding:10px 6px;border-radius:5px;background:#e9ecef;text-align:center;font-size:13px}.stage.active{background:#d4edda;font-weight:bold}.stage.blocked{background:#f8d7da}.field{padding:12px 0;border-top:1px solid #eee}input,textarea,select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #bbb;border-radius:4px}textarea{min-height:90px}button{border:0;border-radius:5px;padding:10px 14px;background:#176b45;color:#fff;cursor:pointer}button.secondary{background:#566573}button:disabled{background:#aaa;cursor:not-allowed}.muted{color:#626567}.ok{background:#e9f7ef;padding:10px;border-radius:4px}.warning{background:#fff3cd;padding:10px;border-radius:4px}.bad{background:#fdecec;padding:10px;border-radius:4px}.state{font-weight:bold}.HUMAN_VALIDATED{color:#176b45}.SOURCE_CONFLICT{color:#a93226}.SOURCE_DECLARED{color:#b9770e}@media(max-width:850px){.grid{grid-template-columns:1fr}.stages{grid-template-columns:1fr 1fr}.toolbar button{width:100%}}
</style></head><body>
<header><strong>Contrata-IA</strong> · Contrato de suministro</header><main>
<div class="card"><h2>Expediente</h2><div class="grid"><div><label>Identificador</label><input id="caseId" placeholder="CONTR/2026/XXXXXX"></div><div><label>Credencial</label><input id="token" type="password" autocomplete="off"></div></div><div class="toolbar" style="margin-top:10px"><button id="open">Abrir expediente</button><button id="refresh" class="secondary">Actualizar progreso</button></div><p id="status" class="muted">Introduzca expediente y credencial.</p></div>
<div class="card"><h2>Recorrido</h2><div id="stages" class="stages"></div><div id="summary" class="muted" style="margin-top:12px"></div></div>
<div class="card"><h2 id="stageTitle">Datos del expediente</h2><p id="stageHelp" class="muted">Se muestran únicamente los datos aplicables a la etapa actual.</p><div id="fields" class="muted">Abra un expediente.</div><div class="toolbar"><button id="prev" class="secondary">Anterior</button><button id="next">Siguiente</button></div></div>
<div class="card"><h2>Revisión y documentos</h2><div id="review" class="muted">Complete las etapas anteriores.</div><div id="pcapStatus" class="muted" style="margin-top:10px">El PCAP oficial se habilitará solo cuando su ámbito y todas las decisiones del Anexo I estén acreditadas.</div><div class="toolbar" style="margin-top:10px"><button id="memory" disabled>Descargar Memoria</button><button id="ppt" disabled>Descargar PPT</button><button id="pcap" disabled class="secondary">PCAP oficial</button></div><p class="muted">La descarga no sustituye la revisión ni la aprobación humana.</p></div>
</main><script>
const defs=${FIELD_DEFS};let record={fields:{}};let journey=null;let pcapGate=null;let stageIndex=0;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const stageNames=['Necesidad y objeto','Economía y duración','Procedimiento','Prescripciones','Ejecución','Revisión final','Documentos'];
function headers(){const t=$('token').value.trim();return {'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})};}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers(),...(opt.headers||{})},credentials:'same-origin'});const text=await r.text();let d={};try{d=text?JSON.parse(text):{};}catch{d={error:text}}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d;}
function valueEditor(def,field){const v=field?.value??'';if(def.control==='BOOLEAN')return '<select data-value><option value="">Seleccione…</option><option value="true" '+(v===true?'selected':'')+'>Sí</option><option value="false" '+(v===false?'selected':'')+'>No</option></select>';if(def.control==='SELECT'&&def.options)return '<select data-value><option value="">Seleccione…</option>'+def.options.map(o=>'<option '+(String(v)===String(o)?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>';if(def.control==='TEXTAREA'||def.control==='TABLE')return '<textarea data-value>'+esc(typeof v==='string'?v:JSON.stringify(v,null,2))+'</textarea>';return '<input data-value value="'+esc(v)+'">';}
function parse(def,raw){if(def.fieldPath==='execution.plannedModificationRegime'){try{return JSON.parse(raw)}catch{throw new Error('El régimen de modificación debe conservar la estructura indicada; revise el formato antes de guardar.')}}if(def.control==='BOOLEAN'){if(raw==='')throw new Error('Seleccione Sí o No.');return raw==='true';}if(def.control==='INTEGER'||def.control==='MONEY_CENTS'){const n=Number(raw);if(!Number.isFinite(n)||n<0)throw new Error('Número inválido');return n;}if(def.control==='TABLE'){try{return JSON.parse(raw)}catch{return raw.split('\n').map(x=>x.trim()).filter(Boolean)}}const value=String(raw||'').trim();if(!value)throw new Error('El campo no puede quedar vacío.');return value;}
function currentStage(){return journey?.stages?.[stageIndex]||null;}
function renderStages(){const host=$('stages');host.innerHTML=stageNames.map((n,i)=>{const s=journey?.stages?.[i];const cls=i===stageIndex?'active':(s?.status==='BLOCKED'?'blocked':'');return '<div class="stage '+cls+'">'+(i+1)+'. '+esc(n)+'<br><small>'+esc(s?.status||'PENDING')+'</small></div>'}).join('');}
function visibleDefs(){const s=currentStage();if(!s)return[];const paths=new Set([...(s.requiredFields||[]),...(s.optionalFields||[])]);return defs.filter(d=>paths.has(d.fieldPath));}
function renderFields(){const host=$('fields');const list=visibleDefs();$('stageTitle').textContent=stageNames[stageIndex];if(!list.length){host.innerHTML='<p class="muted">Esta etapa no requiere más datos editables.</p>';return;}host.innerHTML=list.map(def=>{const f=record.fields?.[def.fieldPath];const extra=def.fieldPath==='execution.plannedModificationRegime'?'<div class="muted">Declare expresamente estabilidad, DA 33.ª y otras causas, con applicable, maximumPercent y límites. No se reutilizan decisiones de otros expedientes.</div>':'';return '<div class="field" data-path="'+esc(def.fieldPath)+'"><div><strong>'+esc(def.label)+'</strong> <span class="state '+esc(f?.status||'PENDING')+'">'+esc(f?.status||'PENDING')+'</span></div><div class="muted">'+esc(def.help||'')+'</div>'+extra+valueEditor(def,f)+'<div class="toolbar" style="margin-top:7px"><button data-save>Guardar</button><button data-validate class="secondary">Validar humanamente</button></div></div>'}).join('');}
function renderReview(){const blockers=journey?.blockers||[];const ready=Boolean(journey?.readyForDocuments);$('summary').innerHTML='<strong>Progreso: '+esc(journey?.progressPercent||0)+' %</strong> · Etapa actual: '+esc(journey?.currentStageLabel||stageNames[stageIndex])+(blockers.length?'<br>Bloqueos: '+blockers.map(esc).join(' · '):'');$('review').className=ready?'ok':(blockers.length?'warning':'muted');$('review').innerHTML=ready?'<strong>Expediente preparado para Memoria y PPT.</strong> La validación humana continúa siendo obligatoria.':(blockers.length?'<strong>Bloqueos pendientes:</strong><br>'+blockers.map(x=>'• '+esc(x)).join('<br>'):'Complete y valide los datos requeridos.');$('memory').disabled=!ready;$('ppt').disabled=!ready;const pg=pcapGate||{ready:false,blockers:['PCAP todavía no evaluado.']};$('pcapStatus').className=pg.ready?'ok':'warning';$('pcapStatus').innerHTML=pg.ready?'<strong>Ámbito del PCAP oficial acreditado.</strong> Pendiente únicamente del segundo pase general del Anexo I.':'<strong>PCAP oficial no preparado:</strong><br>'+((pg.blockers||[]).map(x=>'• '+esc(x)).join('<br>'));$('pcap').disabled=true;}
async function load(){const id=$('caseId').value.trim();if(!id)throw new Error('Indique expediente.');if(!$('token').value.trim())throw new Error('Introduzca la credencial.');$('status').textContent='Abriendo expediente…';record=await api('/api/universal/cases/'+encodeURIComponent(id)+'/evidence');const data=await api('/api/lb95/cases/'+encodeURIComponent(id)+'/journey');journey=data.journey;pcapGate=data.pcapParametrization||null;stageIndex=Math.max(0,Math.min(6,journey.currentStageIndex??0));renderStages();renderFields();renderReview();$('status').className='ok';$('status').textContent='Expediente abierto. Persistencia: '+(data.persistence||'desconocida')+'.';}
async function act(ev){const b=ev.target.closest('button');const row=ev.target.closest('.field');if(!b||!row)return;const path=row.dataset.path;const def=defs.find(d=>d.fieldPath===path);const id=$('caseId').value.trim();try{if(b.hasAttribute('data-save')){const raw=row.querySelector('[data-value]').value;await api('/api/universal/cases/'+encodeURIComponent(id)+'/evidence/'+encodeURIComponent(path),{method:'PUT',body:JSON.stringify({value:parse(def,raw)})});}else if(b.hasAttribute('data-validate'))await api('/api/universal/cases/'+encodeURIComponent(id)+'/evidence/'+encodeURIComponent(path)+'/validate',{method:'POST',body:'{}'});await load();}catch(e){$('status').className='warning';$('status').textContent=e.message||String(e);}}
async function download(kind){const id=$('caseId').value.trim();const r=await fetch('/api/lb94/cases/'+encodeURIComponent(id)+'/generate/'+kind,{method:'POST',headers:headers(),credentials:'same-origin'});if(!r.ok){const d=await r.json().catch(()=>({error:'Error de generación'}));throw new Error(d.error||'Error de generación');}const blob=await r.blob();const disp=r.headers.get('content-disposition')||'';const m=/filename="([^"]+)"/.exec(disp);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=m?.[1]||(id+'_'+kind+'.odt');document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);}
$('open').onclick=()=>load().catch(e=>{$('status').className='warning';$('status').textContent=e.message||String(e)});$('refresh').onclick=$('open').onclick;$('fields').addEventListener('click',act);$('prev').onclick=()=>{stageIndex=Math.max(0,stageIndex-1);renderStages();renderFields()};$('next').onclick=()=>{stageIndex=Math.min(6,stageIndex+1);renderStages();renderFields()};$('memory').onclick=()=>download('MEMORIA').catch(e=>alert(e.message));$('ppt').onclick=()=>download('PPT').catch(e=>alert(e.message));
</script></body></html>`;
