import http,{type ServerResponse}from"node:http";
import path from"node:path";
import { UniversalEvidenceWorkspace,type UniversalEvidenceRecord } from "../../application/intake/lb52/UniversalEvidenceWorkspace";
import { createHttpPersistedConcessionTemplateAssetStoreFromEnv } from "../../application/intake/lb98/ConcessionPersistedTemplateAssetStore";
import { createHttpPersistedWorksConcessionTemplateAssetStoreFromEnv } from "../../application/intake/lb98/WorksConcessionPersistedTemplateAssetStore";
import { generateConcessionDocumentPackage } from "../../application/intake/lb98/ConcessionUserDocumentPackageGenerator";
import { generateWorksConcessionDocumentPackage } from "../../application/intake/lb98/WorksConcessionUserDocumentPackageGenerator";
import { evaluateConcessionUserJourney } from "../../application/intake/lb98/ConcessionUserJourneyCoordinator";
import { evaluateConcessionRiskOperational,type ConcessionSubtype } from "../../application/intake/lb98/ConcessionRiskOperationalGate";
import { evaluateConcessionViabilityContent } from "../../application/intake/lb98/ConcessionViabilityContentGate";
import { evaluateWorksConcessionPreparation } from "../../application/intake/lb98/WorksConcessionPreparationGate";
import { DurableUniversalEvidenceWorkspace } from "../../application/universal/DurableUniversalEvidenceWorkspace";
import { createUniversalCaseMirrorFromEnv } from "../../application/universal/HttpUniversalCaseMirror";
import { UniversalDurableCaseStore } from "../../application/universal/UniversalDurableCaseStore";
import { createLB97RuntimeServer } from "../lb97/LB97RuntimeServer";
import { SecurityPolicy } from "../lb7/SecurityPolicy";
import { CONCESSION_USER_JOURNEY_UI } from "./ConcessionUserJourneyUi";
const DATA_ROOT=path.resolve(process.env.CONTRATA_IA_DATA_DIR??"var/contrata-ia");const EVIDENCE_ROOT=path.join(DATA_ROOT,"universal-evidence-v1");const security=new SecurityPolicy();const localEvidence=new UniversalEvidenceWorkspace(EVIDENCE_ROOT);const durableEvidence=new DurableUniversalEvidenceWorkspace(EVIDENCE_ROOT,localEvidence,new UniversalDurableCaseStore(1,createUniversalCaseMirrorFromEnv()??undefined));
function sendJson(r:ServerResponse,s:number,v:unknown){const b=Buffer.from(JSON.stringify(v));r.writeHead(s,{"content-type":"application/json; charset=utf-8","content-length":b.length,"cache-control":"no-store"});r.end(b);}function sendHtml(r:ServerResponse,h:string){const b=Buffer.from(h);r.writeHead(200,{"content-type":"text/html; charset=utf-8","content-length":b.length,"cache-control":"no-store"});r.end(b);}function sendBinary(r:ServerResponse,d:Uint8Array,n:string,m:string){const b=Buffer.from(d);r.writeHead(200,{"content-type":m,"content-length":b.length,"content-disposition":`attachment; filename="${n}"`,"cache-control":"no-store"});r.end(b);}function statusFor(e:Error){if(/autenticación|credencial|sesión segura/i.test(e.message))return 401;if(/permiso insuficiente/i.test(e.message))return 403;if(/no encontrad/i.test(e.message))return 404;return 400;}
function v(r:UniversalEvidenceRecord,p:string):unknown{return r.fields[p]?.value;}
function subtype(r:UniversalEvidenceRecord):ConcessionSubtype|null{const x=v(r,"concession.subtype");return x==="SERVICE_CONCESSION"||x==="WORKS_CONCESSION"?x:null;}
function boolOrNull(r:UniversalEvidenceRecord,p:string):boolean|null{const x=v(r,p);return typeof x==="boolean"?x:null;}
function numberOrNull(r:UniversalEvidenceRecord,p:string):number|null{const x=v(r,p);return typeof x==="number"&&Number.isFinite(x)?x:null;}
function stringOrNull(r:UniversalEvidenceRecord,p:string):string|null{const x=v(r,p);return typeof x==="string"&&x.trim()?x:null;}

function legalGates(record:UniversalEvidenceRecord){
  const currentSubtype=subtype(record);const conclusion=v(record,"concession.viabilityStudyConclusion");const stateAid=v(record,"concession.stateAidRelevant");
  const risk=evaluateConcessionRiskOperational({subtype:currentSubtype,viabilityStudyApproved:v(record,"concession.viabilityStudyApproved")===true,viabilityStudyConcludesViable:conclusion==="VIABLE"?true:conclusion==="NOT_VIABLE"?false:null,demandRiskTransferred:v(record,"concession.demandRiskTransferred")===true,supplyRiskTransferred:v(record,"concession.supplyRiskTransferred")===true,marketExposureReal:v(record,"concession.marketExposureReal")===true,recoveryOfInvestmentGuaranteed:boolOrNull(record,"concession.investmentRecoveryGuaranteed"),recoveryOfCostsGuaranteed:boolOrNull(record,"concession.costRecoveryGuaranteed"),estimatedPotentialLossMoreThanNominal:v(record,"concession.potentialLossMoreThanNominal")===true,concessionRevenueModelDefined:Boolean(v(record,"concession.revenueModel")),netPresentValueAnalysisAvailable:Boolean(v(record,"concession.npvAnalysis")),stateAidRelevant:typeof stateAid==="boolean"?stateAid:null,stateAidCompatibilityAddressed:stateAid===false||Boolean(v(record,"concession.stateAidCompatibility"))});
  const viability=evaluateConcessionViabilityContent({subtype:currentSubtype,concessionChoiceJustification:Boolean(v(record,"need")),demandForecast:Boolean(v(record,"concession.demandForecast")),investmentAndFinancingPlan:Boolean(v(record,"concession.investmentPlan")),operatingCostRevenueModel:Boolean(v(record,"concession.revenueModel")),netPresentValueAndDiscountRate:Boolean(v(record,"concession.npvAnalysis")),riskAllocationMatrix:Boolean(v(record,"concession.riskAllocation")),stateAidResolved:typeof stateAid==="boolean"&&(stateAid===false||Boolean(v(record,"concession.stateAidCompatibility")))});
  return{risk,viability};
}

function worksPreparation(record:UniversalEvidenceRecord,viabilityComplete:boolean){
  if(subtype(record)!=="WORKS_CONCESSION")return{ready:true,blockers:[] as readonly string[]};
  return evaluateWorksConcessionPreparation({viabilityStudyApproved:v(record,"concession.viabilityStudyApproved")===true,viabilityContentComplete:viabilityComplete,administrationFullyDefinesWorks:boolOrNull(record,"concession.works.administrationFullyDefinesWorks"),anteprojectRequired:boolOrNull(record,"concession.works.anteprojectRequired"),anteprojectAvailable:v(record,"concession.works.anteprojectAvailable")===true,anteprojectApproved:v(record,"concession.works.anteprojectApproved")===true,anteprojectPublicInformationCompleted:v(record,"concession.works.anteprojectPublicInformationCompleted")===true,projectAvailable:Boolean(v(record,"works.projectScope")),worksProjectContentResult:null,worksPreparationGateResult:null,financialEvaluationOfficeReportApplicable:boolOrNull(record,"concession.works.financialEvaluationReportApplicable"),financialEvaluationOfficeReportAvailable:v(record,"concession.works.financialEvaluationReportAvailable")===true});
}

async function physicalState(record:UniversalEvidenceRecord){const currentSubtype=subtype(record);if(!currentSubtype)return{currentSubtype:null,store:null,readiness:{ready:false,assets:[],blockers:["Debe declararse el subtipo de concesión."]}};const store=currentSubtype==="WORKS_CONCESSION"?createHttpPersistedWorksConcessionTemplateAssetStoreFromEnv():createHttpPersistedConcessionTemplateAssetStoreFromEnv();if(!store)return{currentSubtype,store:null,readiness:{ready:false,assets:[],blockers:["Persistencia externa Concession no configurada."]}};return{currentSubtype,store,readiness:await store.readiness()};}
export function createLB98RuntimeServer():http.Server{const base=createLB97RuntimeServer();return http.createServer(async(request,response)=>{security.applySecurityHeaders(response);try{const url=new URL(request.url??"/","http://localhost");const parts=url.pathname.split("/").filter(Boolean);if(request.method==="GET"&&(url.pathname==="/concession"||url.pathname==="/concession/")){sendHtml(response,CONCESSION_USER_JOURNEY_UI);return;}if(parts[0]==="api"&&parts[1]==="lb98"&&parts[2]==="cases"&&parts[3]){const caseId=decodeURIComponent(parts[3]);if(request.method==="GET"&&parts[4]==="journey"&&parts.length===5){const actor=security.authenticate(request);security.require(actor,"VIEWER");const restored=await durableEvidence.get(caseId);const gates=legalGates(restored.record);const works=worksPreparation(restored.record,gates.viability.complete);const physical=await physicalState(restored.record);const physicalReady=physical.readiness.ready&&physical.readiness.assets.length===4&&physical.readiness.assets.every((a:{available:boolean})=>a.available)&&works.ready;const journey=evaluateConcessionUserJourney(restored.record,physicalReady);sendJson(response,200,{journey,risk:gates.risk,viability:gates.viability,worksPreparation:works,concessionSubtype:physical.currentSubtype,templates:physical.readiness,productionReady:false,humanValidationRequired:true});return;}if(request.method==="POST"&&parts[4]==="generate-package"&&parts.length===5){const actor=security.authenticate(request);security.require(actor,"OPERATOR");const restored=await durableEvidence.get(caseId);const gates=legalGates(restored.record);const works=worksPreparation(restored.record,gates.viability.complete);const physical=await physicalState(restored.record);const blockers=[...gates.risk.blockers,...gates.viability.blockers,...works.blockers,...physical.readiness.blockers];if(!physical.currentSubtype||!physical.store||!gates.risk.ready||!gates.viability.complete||!works.ready||!physical.readiness.ready){sendJson(response,409,{ready:false,blockers:[...new Set(blockers)],productionReady:false});return;}const pkg=physical.currentSubtype==="WORKS_CONCESSION"?await generateWorksConcessionDocumentPackage({record:restored.record,templateStore:physical.store as never}):await generateConcessionDocumentPackage({record:restored.record,templateStore:physical.store as never});if(!pkg.ready||!pkg.bytes||!pkg.fileName){sendJson(response,409,pkg);return;}sendBinary(response,pkg.bytes,pkg.fileName,"application/zip");return;}}base.emit("request",request,response);}catch(error){const failure=error instanceof Error?error:new Error(String(error));if(!response.headersSent)sendJson(response,statusFor(failure),{error:failure.message});else response.end();}});}
