import { createHash } from "node:crypto";
import type { UniversalEditableTemplateBinaryStore } from "../lb23/UniversalOdtProductionRenderer";
import { readOdtZip } from "../lb23/OdtPackageCodec";
import type { UniversalEvidenceRecord } from "../lb52/UniversalEvidenceWorkspace";
import { generateSupplyGeneralEvidenceDocuments } from "../lb94/SupplyGeneralEvidenceDocumentGenerator";
import { assertAtomicDocumentPackage } from "../lb102/AtomicDocumentPackageGate";
import { renderSupplyAsaGeneralPcap, type SupplyAsaGeneralPcapResult } from "./SupplyAsaGeneralPcapRenderer";
import { zipStoredFiles } from "./StoredZipPackage";
import type { LB103PresentedGenerationSeals } from "../../universal/LB103AuthoritativeSupplyGeneration";
import { extractContractingAuthorityAnexoIText } from "../lb35/JuntaSupplyAsaAnexoIResidualAudit";

export type SupplyAsaPackageProfile="SUPPLY_ASA_AUTOFINANCED_LB95"|"SUPPLY_ASA_EU_FUNDS_LB95";
export interface SupplyUserDocumentPackage {ready:boolean;fileName:string|null;mediaType:"application/zip";bytes:Uint8Array|null;sha256:string|null;manifest:null|{caseId:string;profile:SupplyAsaPackageProfile;generatedAt:string;documents:readonly {kind:"PCAP"|"MEMORIA"|"PPT";fileName:string;sha256:string;provenance:string}[];crossDocumentAuditReady:boolean;blockers:readonly string[];humanAcceptanceRequired:true};blockers:readonly string[];}
export type SupplyPcapRenderer=(input:{record:UniversalEvidenceRecord;templateStore:UniversalEditableTemplateBinaryStore})=>Promise<SupplyAsaGeneralPcapResult>;
function sha256(bytes:Uint8Array):string{return createHash("sha256").update(bytes).digest("hex");}
function textOf(bytes:Uint8Array):string{const entry=readOdtZip(bytes).find(item=>item.name==="content.xml");if(!entry)return"";return Buffer.from(entry.bytes).toString("utf8").replace(/<[^>]+>/g," ").replace(/&quot;/g,"\"").replace(/&apos;/g,"'").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\s+/g," ").trim();}
function normalized(value:unknown):string{return String(value??"").replace(/\s+/g," ").trim();}
function euro(cents:unknown):string{if(typeof cents!=="number"||!Number.isSafeInteger(cents))return"";return new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}).format(cents/100);}
function crossAudit(record:UniversalEvidenceRecord,pcap:Uint8Array,memory:Uint8Array,ppt:Uint8Array,templateId:string):string[]{
 const blockers:string[]=[];const texts={PCAP:textOf(pcap),MEMORIA:textOf(memory),PPT:textOf(ppt)};const object=normalized(record.fields.object?.value),cpv=normalized(record.fields.cpvMain?.value);
 if(!object)blockers.push("Auditoría cruzada: falta objeto validado.");else for(const [kind,text] of Object.entries(texts))if(!text.includes(object))blockers.push(`${kind}: el objeto validado no aparece materializado.`);
 if(cpv){if(!texts.PCAP.includes(cpv))blockers.push("PCAP: el CPV validado no aparece materializado.");if(!texts.MEMORIA.includes(cpv))blockers.push("MEMORIA: el CPV validado no aparece materializado.");}
 for(const [path,label] of [["baseTenderBudgetCents","PBL"],["economic.legalEstimatedValueCents","VE"]] as const){const formatted=euro(record.fields[path]?.value);if(!formatted){blockers.push(`Auditoría cruzada: falta ${label} numérico validado.`);continue;}if(!texts.PCAP.includes(formatted))blockers.push(`PCAP: no contiene ${label} ${formatted}.`);if(!texts.MEMORIA.includes(formatted))blockers.push(`MEMORIA: no contiene ${label} ${formatted}.`);}
 const funding=String(record.fields["economic.fundingSource"]?.value??"");const expectedEu=funding==="EU_FUNDS";if(templateId.includes("EU_FUNDS")!==expectedEu)blockers.push("PCAP: el modelo oficial no coincide con la financiación validada.");
 for(const [kind,text] of Object.entries(texts)){for(const marker of ["Modo ejemplo","se presupone aportada","provisionalmente","debe comprobar y validar"]){if(text.toLocaleLowerCase("es-ES").includes(marker.toLocaleLowerCase("es-ES")))blockers.push(`${kind}: contiene lenguaje interno o provisional no admisible: «${marker}».`);}}
 for(const token of ["AUTOFINANCED","EU_FUNDS","QUOTES_OR_CATALOGUES","ORDINARY_GLOBAL_PRICE","ABIERTO_SIMPLIFICADO_ABREVIADO"]){if(texts.MEMORIA.includes(token)||texts.PPT.includes(token))blockers.push(`Auditoría documental: el código interno ${token} debe transformarse a una denominación en español.`);}
 const memoryGeneric=["se regirán por el PCAP","son los validados en el expediente","se ajustarán a los datos validados","sujeta a revisión y validación humana","evaluableMedianteFormula","ponderacion:"];
 for(const marker of memoryGeneric)if(texts.MEMORIA.toLocaleLowerCase("es-ES").includes(marker.toLocaleLowerCase("es-ES")))blockers.push(`MEMORIA: contiene una remisión o expresión interna que debe sustituirse por la justificación material: «${marker}».`);
 const pptGeneric=["Ejecutar "+object+", conforme al alcance","conforme al expediente validado","formarán parte de las obligaciones de ejecución"];
 for(const marker of pptGeneric)if(marker&&texts.PPT.toLocaleLowerCase("es-ES").includes(marker.toLocaleLowerCase("es-ES")))blockers.push(`PPT: contiene una prescripción genérica insuficiente: «${marker}».`);
 try{const content=readOdtZip(pcap).find(item=>item.name==="content.xml");if(!content)throw new Error("falta content.xml");const annex=extractContractingAuthorityAnexoIText(Buffer.from(content.bytes).toString("utf8"));if(/_{3,}|Sí\s*\/\s*No/i.test(annex))blockers.push("PCAP: el Anexo I conserva campos del órgano de contratación sin cumplimentar.");for(const marker of ["El órgano de contratación competente","El plazo validado en el expediente","Según la relación de unidades","Los indicados por el órgano de contratación","Las previstas en el PCAP","Penalidades proporcionales por incumplimiento"])if(annex.toLocaleLowerCase("es-ES").includes(marker.toLocaleLowerCase("es-ES")))blockers.push(`PCAP: el Anexo I conserva una respuesta genérica no apta para el expediente: «${marker}».`);}catch(error){blockers.push(`PCAP: no ha podido auditarse materialmente el Anexo I (${error instanceof Error?error.message:String(error)}).`);}
 const base=euro(record.fields.baseTenderBudgetCents?.value),total=euro(record.fields["economic.initialPblVatIncludedCents"]?.value);if(base&&total&&base!==total&&new RegExp(base.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+".{0,40}IVA incluido","i").test(texts.PCAP))blockers.push(`PCAP: el importe ${base} corresponde al PBL sin IVA y no puede identificarse como IVA incluido.`);
 return [...new Set(blockers)];
}

export async function generateSupplyUserDocumentPackage(input:{record:UniversalEvidenceRecord;templateStore:UniversalEditableTemplateBinaryStore;pcapRenderer?:SupplyPcapRenderer;authoritativeSeals?:LB103PresentedGenerationSeals;}):Promise<SupplyUserDocumentPackage>{
 const blockers:string[]=[];const renderer=input.pcapRenderer??renderSupplyAsaGeneralPcap;const pcap=await renderer({record:input.record,templateStore:input.templateStore});if(!pcap.ready||!pcap.document)blockers.push(...pcap.blockers.map(item=>`PCAP: ${item}`));const general=await generateSupplyGeneralEvidenceDocuments({record:input.record,templateStore:input.templateStore});if(!general.ready)blockers.push(...general.blockers);if(blockers.length||!pcap.document||general.documents.length!==2)return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,manifest:null,blockers};
 const memory=general.documents.find(item=>item.kind==="MEMORY"),ppt=general.documents.find(item=>item.kind==="PPT");if(!memory||!ppt)return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,manifest:null,blockers:["No se han producido Memoria y PPT generales."]};
 const funding=String(input.record.fields["economic.fundingSource"]?.value??"");const profile:SupplyAsaPackageProfile=funding==="EU_FUNDS"?"SUPPLY_ASA_EU_FUNDS_LB95":"SUPPLY_ASA_AUTOFINANCED_LB95";const packageVersion=`${profile}_ATOMIC_V1`;const crossBlockers=crossAudit(input.record,pcap.document.bytes,memory.bytes,ppt.bytes,pcap.document.templateId);const safeId=input.record.caseId.replaceAll("/","-");const documents=[{kind:"PCAP" as const,fileName:pcap.document.fileName,bytes:pcap.document.bytes,sha256:pcap.document.sha256,provenance:`OFFICIAL_MODEL:${pcap.document.templateId}`},{kind:"MEMORIA" as const,fileName:`Memoria_${safeId}.odt`,bytes:memory.bytes,sha256:sha256(memory.bytes),provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE"},{kind:"PPT" as const,fileName:`PPT_${safeId}.odt`,bytes:ppt.bytes,sha256:sha256(ppt.bytes),provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE"}];
 let atomic;try{atomic=assertAtomicDocumentPackage({caseId:input.record.caseId,packageVersion,canonicalSnapshot:input.record,documents,crossDocumentBlockers:crossBlockers});}catch(error){return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,manifest:null,blockers:[error instanceof Error?error.message:String(error)]};}
 const generatedAt=input.record.updatedAt;const manifest={caseId:input.record.caseId,profile,generatedAt,...atomic,...(input.authoritativeSeals?{authoritativeSeals:{...input.authoritativeSeals}}:{}),documents:documents.map(({kind,fileName,sha256:hash,provenance})=>({kind,fileName,sha256:hash,provenance,snapshotHash:atomic.snapshotHash,generationId:atomic.generationId})),crossDocumentAuditReady:true,blockers:[] as string[],humanAcceptanceRequired:true as const};const zip=zipStoredFiles([...documents.map(item=>({name:item.fileName,bytes:item.bytes})),{name:"manifest.json",bytes:Buffer.from(JSON.stringify(manifest,null,2),"utf8")}]);return{ready:true,fileName:`Contrata-IA_${safeId}_PCAP-Memoria-PPT.zip`,mediaType:"application/zip",bytes:zip,sha256:sha256(zip),manifest,blockers:[]};
}
