import http,{type ServerResponse}from"node:http";
import path from"node:path";
import { UniversalEvidenceWorkspace } from "../../application/intake/lb52/UniversalEvidenceWorkspace";
import { createHttpPersistedMixedSupplyServiceTemplateAssetStoreFromEnv } from "../../application/intake/lb99/MixedSupplyServicePersistedTemplateAssetStore";
import type { MixedSupplyServiceProfile } from "../../application/intake/lb99/MixedSupplyServiceTemplateManifest";
import { generateMixedSupplyServiceDocumentPackage } from "../../application/intake/lb99/MixedSupplyServiceUserDocumentPackageGenerator";
import { evaluateMixedUserJourney } from "../../application/intake/lb99/MixedUserJourneyCoordinator";
import { DurableUniversalEvidenceWorkspace } from "../../application/universal/DurableUniversalEvidenceWorkspace";
import { createUniversalCaseMirrorFromEnv } from "../../application/universal/HttpUniversalCaseMirror";
import { UniversalDurableCaseStore } from "../../application/universal/UniversalDurableCaseStore";
import { createLB98RuntimeServer } from "../lb98/LB98RuntimeServer";
import { SecurityPolicy } from "../lb7/SecurityPolicy";
import { MIXED_USER_JOURNEY_UI } from "./MixedUserJourneyUi";
const DATA_ROOT=path.resolve(process.env.CONTRATA_IA_DATA_DIR??"var/contrata-ia");const EVIDENCE_ROOT=path.join(DATA_ROOT,"universal-evidence-v1");const security=new SecurityPolicy();const localEvidence=new UniversalEvidenceWorkspace(EVIDENCE_ROOT);const durableEvidence=new DurableUniversalEvidenceWorkspace(EVIDENCE_ROOT,localEvidence,new UniversalDurableCaseStore(1,createUniversalCaseMirrorFromEnv()??undefined));
function sendJson(r:ServerResponse,s:number,v:unknown){const b=Buffer.from(JSON.stringify(v));r.writeHead(s,{"content-type":"application/json; charset=utf-8","content-length":b.length,"cache-control":"no-store"});r.end(b);}function sendHtml(r:ServerResponse,h:string){const b=Buffer.from(h);r.writeHead(200,{"content-type":"text/html; charset=utf-8","content-length":b.length,"cache-control":"no-store"});r.end(b);}function sendBinary(r:ServerResponse,d:Uint8Array,n:string,m:string){const b=Buffer.from(d);r.writeHead(200,{"content-type":m,"content-length":b.length,"content-disposition":`attachment; filename="${n}"`,"cache-control":"no-store"});r.end(b);}function statusFor(e:Error){if(/autenticación|credencial|sesión segura/i.test(e.message))return 401;if(/permiso insuficiente/i.test(e.message))return 403;if(/no encontrad/i.test(e.message))return 404;return 400;}
function supplyServiceProfile(journey:ReturnType<typeof evaluateMixedUserJourney>):MixedSupplyServiceProfile|null{const families=new Set(journey.composition.componentFamilies);if(families.size!==2||!families.has("SUPPLY")||!families.has("SERVICE"))return null;if(journey.qualification.governingAwardRegime==="SUPPLY")return"SUPPLY_PRINCIPAL";if(journey.qualification.governingAwardRegime==="SERVICE")return"SERVICE_PRINCIPAL";return null;}
async function physicalState(record:Parameters<typeof evaluateMixedUserJourney>[0]){const initial=evaluateMixedUserJourney(record,false);const profile=supplyServiceProfile(initial);if(!profile)return{profile:null,store:null,readiness:{ready:false,assets:[] as Array<{kind:string;available:boolean}>,blockers:["La composición física LB99 acreditada solo cubre exactamente SUPPLY + SERVICE."]},journey:initial};const store=createHttpPersistedMixedSupplyServiceTemplateAssetStoreFromEnv(profile);if(!store)return{profile,store:null,readiness:{ready:false,assets:[] as Array<{kind:string;available:boolean}>,blockers:["Persistencia externa Mixed Supply-Service no configurada."]},journey:initial};const readiness=await store.readiness();const physicalReady=readiness.ready&&readiness.assets.length===3&&readiness.assets.every(a=>a.available);return{profile,store,readiness,journey:evaluateMixedUserJourney(record,physicalReady)};}
/** LB99 habilita solo los perfiles físicos especializados Supply+Service; Works/Concession mixtos permanecen bloqueados hasta compositor específico. */
export function createLB99RuntimeServer():http.Server{const base=createLB98RuntimeServer();return http.createServer(async(request,response)=>{security.applySecurityHeaders(response);try{const url=new URL(request.url??"/","http://localhost");const parts=url.pathname.split("/").filter(Boolean);if(request.method==="GET"&&(url.pathname==="/mixed"||url.pathname==="/mixed/")){sendHtml(response,MIXED_USER_JOURNEY_UI);return;}if(parts[0]==="api"&&parts[1]==="lb99"&&parts[2]==="cases"&&parts[3]){const caseId=decodeURIComponent(parts[3]);if(request.method==="GET"&&parts[4]==="journey"&&parts.length===5){const actor=security.authenticate(request);security.require(actor,"VIEWER");const restored=await durableEvidence.get(caseId);const state=await physicalState(restored.record);sendJson(response,200,{journey:state.journey,mixedProfile:state.profile,mixedTemplates:state.readiness,physicalCompositionReady:state.journey.readyForDocuments,genericMixedTemplateAllowed:false,sourceAuthority:"LCSP arts. 18, 34.2 y 122.2 + expedientes reales Junta suministro/servicio",humanValidationRequired:true,productionReady:false});return;}if(request.method==="POST"&&parts[4]==="generate-package"&&parts.length===5){const actor=security.authenticate(request);security.require(actor,"OPERATOR");const restored=await durableEvidence.get(caseId);const state=await physicalState(restored.record);if(!state.profile||!state.store){sendJson(response,409,{ready:false,blockers:[...new Set([...state.journey.blockers,...state.readiness.blockers,"LB99 no compone todavía contratos Mixed con Works o Concession; no existe fallback a una plantilla mixta genérica."])],journey:state.journey,genericMixedTemplateAllowed:false,productionReady:false});return;}if(!state.journey.readyForDocuments){sendJson(response,409,{ready:false,blockers:[...new Set([...state.journey.blockers,...state.readiness.blockers])],journey:state.journey,mixedProfile:state.profile,genericMixedTemplateAllowed:false,productionReady:false});return;}const pkg=await generateMixedSupplyServiceDocumentPackage({record:restored.record,templateStore:state.store});if(!pkg.ready||!pkg.bytes||!pkg.fileName){sendJson(response,409,pkg);return;}sendBinary(response,pkg.bytes,pkg.fileName,pkg.mediaType);return;}}base.emit("request",request,response);}catch(error){const failure=error instanceof Error?error:new Error(String(error));if(!response.headersSent)sendJson(response,statusFor(failure),{error:failure.message});else response.end();}});}
