import http,{type ServerResponse}from"node:http";
import path from"node:path";
import { UniversalEvidenceWorkspace } from "../../application/intake/lb52/UniversalEvidenceWorkspace";
import { evaluateMixedUserJourney } from "../../application/intake/lb99/MixedUserJourneyCoordinator";
import { DurableUniversalEvidenceWorkspace } from "../../application/universal/DurableUniversalEvidenceWorkspace";
import { createUniversalCaseMirrorFromEnv } from "../../application/universal/HttpUniversalCaseMirror";
import { UniversalDurableCaseStore } from "../../application/universal/UniversalDurableCaseStore";
import { createLB98RuntimeServer } from "../lb98/LB98RuntimeServer";
import { SecurityPolicy } from "../lb7/SecurityPolicy";
import { MIXED_USER_JOURNEY_UI } from "./MixedUserJourneyUi";

const DATA_ROOT=path.resolve(process.env.CONTRATA_IA_DATA_DIR??"var/contrata-ia");const EVIDENCE_ROOT=path.join(DATA_ROOT,"universal-evidence-v1");const security=new SecurityPolicy();const localEvidence=new UniversalEvidenceWorkspace(EVIDENCE_ROOT);const durableEvidence=new DurableUniversalEvidenceWorkspace(EVIDENCE_ROOT,localEvidence,new UniversalDurableCaseStore(1,createUniversalCaseMirrorFromEnv()??undefined));
function sendJson(r:ServerResponse,s:number,v:unknown){const b=Buffer.from(JSON.stringify(v));r.writeHead(s,{"content-type":"application/json; charset=utf-8","content-length":b.length,"cache-control":"no-store"});r.end(b);}function sendHtml(r:ServerResponse,h:string){const b=Buffer.from(h);r.writeHead(200,{"content-type":"text/html; charset=utf-8","content-length":b.length,"cache-control":"no-store"});r.end(b);}function statusFor(e:Error){if(/autenticación|credencial|sesión segura/i.test(e.message))return 401;if(/permiso insuficiente/i.test(e.message))return 403;if(/no encontrad/i.test(e.message))return 404;return 400;}

/** LB99 expone calificación/composición Mixed; la descarga permanece cerrada hasta acreditar compositor físico sin plantilla genérica falsa. */
export function createLB99RuntimeServer():http.Server{const base=createLB98RuntimeServer();return http.createServer(async(request,response)=>{security.applySecurityHeaders(response);try{const url=new URL(request.url??"/","http://localhost");const parts=url.pathname.split("/").filter(Boolean);if(request.method==="GET"&&(url.pathname==="/mixed"||url.pathname==="/mixed/")){sendHtml(response,MIXED_USER_JOURNEY_UI);return;}if(parts[0]==="api"&&parts[1]==="lb99"&&parts[2]==="cases"&&parts[3]){const caseId=decodeURIComponent(parts[3]);if(request.method==="GET"&&parts[4]==="journey"&&parts.length===5){const actor=security.authenticate(request);security.require(actor,"VIEWER");const restored=await durableEvidence.get(caseId);const journey=evaluateMixedUserJourney(restored.record,false);sendJson(response,200,{journey,physicalCompositionReady:false,genericMixedTemplateAllowed:false,sourceAuthority:"LCSP arts. 18, 34.2 y 122.2 + expedientes reales Junta suministro/servicio",humanValidationRequired:true,productionReady:false});return;}if(request.method==="POST"&&parts[4]==="generate-package"&&parts.length===5){const actor=security.authenticate(request);security.require(actor,"OPERATOR");const restored=await durableEvidence.get(caseId);const journey=evaluateMixedUserJourney(restored.record,false);sendJson(response,409,{ready:false,blockers:[...new Set([...journey.blockers,"LB99 no habilita descarga hasta acreditar un compositor físico que preserve la familia administrativa gobernante y todos los overlays de las prestaciones."])],journey,genericMixedTemplateAllowed:false,productionReady:false});return;}}base.emit("request",request,response);}catch(error){const failure=error instanceof Error?error:new Error(String(error));if(!response.headersSent)sendJson(response,statusFor(failure),{error:failure.message});else response.end();}});}
