export type ServiceVariant = "CLEANING" | "TRAINING" | "MAINTENANCE" | "OTHER_SERVICE";

export const SERVICE_VERTICAL_FIELD_MANIFEST = [
  {
    fieldPath: "service.variant",
    label: "Subfamilia técnica del servicio",
    control: "SELECT" as const,
    section: "TECHNICAL" as const,
    requiredForWorkflowReview: true,
    humanValidationRequired: true as const,
    options: ["CLEANING", "TRAINING", "MAINTENANCE", "OTHER_SERVICE"] as readonly ServiceVariant[],
    help: "La subfamilia se declara expresamente; no se deduce automáticamente del CPV ni de un expediente de referencia.",
  },
  {
    fieldPath: "service.insufficiencyOfOwnMeansJustification",
    label: "Justificación de insuficiencia de medios propios",
    control: "TEXTAREA" as const,
    section: "NEED_OBJECT" as const,
    requiredForWorkflowReview: true,
    humanValidationRequired: true as const,
    help: "En contratos de servicios debe justificarse la insuficiencia de medios cuando proceda conforme al art. 116.4.f LCSP.",
  },
  {
    fieldPath: "service.personnelRequirements",
    label: "Personal y medios personales exigidos",
    control: "TEXTAREA" as const,
    section: "TECHNICAL" as const,
    requiredForWorkflowReview: true,
    humanValidationRequired: true as const,
  },
  {
    fieldPath: "service.subrogationRequired",
    label: "Existe obligación de subrogación de personal",
    control: "BOOLEAN" as const,
    section: "EXECUTION" as const,
    requiredForWorkflowReview: true,
    humanValidationRequired: true as const,
    help: "No se presume por tratarse de limpieza u otra subfamilia; debe acreditarse por norma, convenio o acuerdo aplicable.",
  },
  {
    fieldPath: "service.subrogationInformation",
    label: "Información de las personas trabajadoras a subrogar",
    control: "TEXTAREA" as const,
    section: "EXECUTION" as const,
    requiredForWorkflowReview: false,
    humanValidationRequired: true as const,
    help: "Solo aplicable si existe obligación de subrogación; art. 130 LCSP.",
  },
  {
    fieldPath: "service.performanceControlRegime",
    label: "Control, seguimiento y niveles de calidad del servicio",
    control: "TEXTAREA" as const,
    section: "EXECUTION" as const,
    requiredForWorkflowReview: true,
    humanValidationRequired: true as const,
  },
  {
    fieldPath: "service.materialsOrEquipmentRegime",
    label: "Materiales, equipos o suministros accesorios incluidos",
    control: "TEXTAREA" as const,
    section: "TECHNICAL" as const,
    requiredForWorkflowReview: false,
    humanValidationRequired: true as const,
    help: "Los suministros accesorios no recalifican por sí solos el contrato de servicio.",
  },
  {
    fieldPath: "service.technicalManagementSystem",
    label: "Sistema técnico de gestión o seguimiento exigido",
    control: "TEXTAREA" as const,
    section: "TECHNICAL" as const,
    requiredForWorkflowReview: false,
    humanValidationRequired: true as const,
    help: "Aplicable, por ejemplo, a GMAO en servicios de mantenimiento cuando la fuente lo exija.",
  },
] as const;
