/**
 * ============================================================
 * CONTRATA-IA
 * ------------------------------------------------------------
 * DocumentDefinition
 * ------------------------------------------------------------
 * Define completamente un documento administrativo.
 *
 * Un documento NO contiene texto.
 *
 * Contiene únicamente:
 *
 * • identidad
 * • capítulos
 * • dependencias
 * • obligatoriedad
 * • reutilización
 *
 * ============================================================
 */

import { DocumentType } from "./DocumentType";

import { SectionDefinition } from "./SectionDefinition";

export interface DocumentDefinition {

    /**
     * Identificador único.
     */

    id: string;

    /**
     * Tipo documental.
     */

    type: DocumentType;

    /**
     * Nombre administrativo.
     */

    title: string;

    /**
     * Descripción.
     */

    description: string;

    /**
     * ¿Documento obligatorio?
     */

    mandatory: boolean;

    /**
     * Orden dentro del expediente.
     */

    order: number;

    /**
     * Capítulos del documento.
     */

    sections: SectionDefinition[];

    /**
     * Documentos de los que depende.
     */

    dependsOn: DocumentType[];

    /**
     * Documentos incompatibles.
     */

    excludes: DocumentType[];

    /**
     * ¿Puede generarse automáticamente?
     */

    autoGenerated: boolean;

    /**
     * ¿Puede editarse?
     */

    editable: boolean;

    /**
     * ¿Debe firmarse?
     */

    requiresSignature: boolean;

    /**
     * ¿Forma parte del expediente?
     */

    includedInExpediente: boolean;

}
