/** Synthetic inputs only. Never a source of administrative decisions. */
export const NEW_SUPPLY_VALUES: Record<string, unknown> = {
  contractType: "SUPPLY", object: "Suministro de material de oficina para prueba técnica", cpvMain: "30192000-1",
  need: "PRUEBA SINTÉTICA: comprobar el recorrido completo de un expediente nuevo.",
  "administrative.contractingAuthority": "Órgano ficticio de prueba técnica",
  "administrative.pcapAnnexIResidualDecisions": {
    objectSpecification: "Cien unidades de material de oficina según las prescripciones técnicas de la prueba.",
    totalUnits: "100",
    totalAmount: "1.000,00",
    lotsDescription: "No procede",
    lot1: "No procede",
    lot2: "No procede",
    maxOfferableLots: "No procede",
    maxAwardableLots: "No procede",
    integrativeOffer: "No",
    reservedScope: "No procede",
    priceRevisionComponents: "No procede",
    priceVariation: "No",
    partialDeadlines: "No procede",
    contractingAuthority: "Órgano ficticio de prueba técnica",
    bindingClarifications: "No",
    procurementBoard: "No",
    withdrawalCompensation: "100,00",
    desistanceCompensation: "100,00",
    article129Bodies: "No procede",
    professionalAuthorization: "No",
    professionalAuthorizationDetail: "No procede",
    ensRequirements: "No procede",
    organizationRequirementsDetail: "No procede",
    specialConditionPenalties: "No",
    specialConditionPenaltiesDetail: "No procede",
    criticalPartsDetail: "No procede",
    subcontractDocumentationPenalty: "No procede",
    delayPenalty: "No",
    delayPenaltyDetail: "No procede",
    defectivePerformancePenalty: "No",
    defectivePerformanceDetail: "No procede",
    partialPerformancePenalty: "No",
    partialPerformanceDetail: "No procede",
    environmentalSocialPenalty: "No",
    environmentalSocialDetail: "No procede",
    warrantyTerm: "12 meses",
    workProgramme: "No",
    confidentialInformation: "No se declara información confidencial en la prueba técnica.",
    confidentialityTerm: "5 años",
    insuranceRequired: "No",
    insuranceTerms: "No procede",
    assignmentAllowed: "No",
    suspensionSpecialRules: "No",
    suspensionSpecialRulesDetail: "No procede",
    personalDataTreatment: "No",
  },
  "lots.divisionIntoLots": false, "lots.noDivisionJustification": "Motivación sintética para verificar el campo, sin validez administrativa.",
  "administrative.reservedContractDa4": false,
  procedure: "ABIERTO_SIMPLIFICADO_ABREVIADO", "processing.processingType": "ORDINARIA",
  "economic.fundingSource": "AUTOFINANCED", "economic.needsBasedContractDa33": false,
  baseTenderBudgetCents: 100000, "economic.initialVatAmountCents": 21000, "economic.initialPblVatIncludedCents": 121000,
  "economic.legalEstimatedValueCents": 100000, "economic.budgetCoversEntireContractLife": true,
  "economic.priceDeterminationRegime": "Precio global de prueba.",
  "economic.estimatedValueCalculationMethod": "Importe inicial sin IVA; sin prórrogas ni incrementos en este supuesto sintético.",
  "economic.priceRevisionRegime": "No procede",
  "economic.annualityBudgetRows": [{year: 2026, amountCents: 121000, vatIncluded: true, budgetApplication: "APLICACIÓN FICTICIA DE PRUEBA"}],
  durationMonths: 12, extensionMonths: 0,
  "execution.extensionStructure": "Sin prórrogas.", "execution.extensionNoticeMonths": 0,
  "execution.plannedModificationRegime": {
    budgetStability: {applicable: true, maximumPercent: 0},
    needsDa33: {applicable: false, maximumPercent: 0, limits: []},
    other: {applicable: false, maximumPercent: 0, description: "No procede.", limits: []},
  },
  "criteria.awardCriteria": [{nombre: "Precio", ponderacion: 100, evaluableMedianteFormula: true}],
  "criteria.singleCriterionMotivation": "Motivación de prueba del criterio único; requiere revisión en cualquier expediente real.",
  "technical.supplyVariant": "ORDINARY_GLOBAL_PRICE", "technical.technicalRequirements": "Requisitos sintéticos: cien unidades de material de oficina, entregadas en embalaje íntegro.",
  "technical.executionLocations": ["Centro ficticio de pruebas"],
  "execution.specialExecutionConditions": ["Condición sintética: recogida de embalajes tras la entrega."],
  "execution.receiptAndAcceptanceRegime": "Comprobación de unidades y conformidad en el supuesto de prueba.",
};
