/** Synthetic inputs only. Never a source of administrative decisions. */
export const NEW_SUPPLY_VALUES: Record<string, unknown> = {
  contractType: "SUPPLY", object: "Suministro de material de oficina para prueba técnica", cpvMain: "30192000-1",
  need: "PRUEBA SINTÉTICA: comprobar el recorrido completo de un expediente nuevo.",
  "administrative.contractingAuthority": "Órgano ficticio de prueba técnica",
  "lots.divisionIntoLots": false, "lots.noDivisionJustification": "Motivación sintética para verificar el campo, sin validez administrativa.",
  "administrative.reservedContractDa4": false,
  procedure: "ABIERTO_SIMPLIFICADO_ABREVIADO", "processing.processingType": "ORDINARIA",
  "economic.fundingSource": "AUTOFINANCED", "economic.needsBasedContractDa33": false,
  baseTenderBudgetCents: 100000, "economic.initialVatAmountCents": 21000, "economic.initialPblVatIncludedCents": 121000,
  "economic.legalEstimatedValueCents": 100000, "economic.budgetCoversEntireContractLife": true,
  "economic.priceDeterminationRegime": "Precio global de prueba.",
  "economic.estimatedValueCalculationMethod": "Importe inicial sin IVA; sin prórrogas ni incrementos en este supuesto sintético.",
  "economic.priceRevisionRegime": "Sin revisión en este supuesto sintético.",
  "economic.annualityBudgetRows": [{year: 2026, amountCents: 121000, vatIncluded: true, budgetApplication: "APLICACIÓN FICTICIA DE PRUEBA"}],
  durationMonths: 12, extensionMonths: 0,
  "execution.extensionStructure": "Sin prórrogas.", "execution.extensionNoticeMonths": 0,
  "execution.plannedModificationRegime": {
    budgetStability: {applicable: true, maximumPercent: 0},
    needsDa33: {applicable: false, maximumPercent: 0, limits: []},
    other: {applicable: false, maximumPercent: 0, description: "No procede.", limits: []},
  },
  "criteria.awardCriteria": [{nombre: "Precio", ponderacion: 100, evaluableMedianteFormula: true}],
  "criteria.singleCriterionMotivation": "Motivación de prueba del criterio único; requiere revisión en cualquier expediente real.",
  "technical.supplyVariant": "ORDINARY_GLOBAL_PRICE", "technical.technicalRequirements": "Requisitos sintéticos: cien unidades de material de oficina, entregadas en embalaje íntegro.",
  "technical.executionLocations": ["Centro ficticio de pruebas"],
  "execution.specialExecutionConditions": ["Condición sintética: recogida de embalajes tras la entrega."],
  "execution.receiptAndAcceptanceRegime": "Comprobación de unidades y conformidad en el supuesto de prueba.",
};
