export const LB118_TECHNICAL_SPECIFICATIONS_VERSION="LB118-TECHNICAL-SPECIFICATIONS-V1" as const;
const LCSP="https://www.boe.es/buscar/act.php?id=BOE-A-2017-12902";
interface Basis{id:string;article:string;paragraph:string;relevantOfficialExcerpt:string;officialUrl:string}
export interface TechnicalRequirementInput {id:string;category:string;requirement:string;verificationMethod:string;justification:string;brandOrOriginReference:string;brandReferenceJustification:string;equivalentAcceptanceCriteria:string}
export interface TechnicalSpecificationsInput {contractType:"SUPPLY"|"SERVICE";technicalPurpose:string;requirements:readonly TechnicalRequirementInput[];usedByNaturalPersons:boolean;accessibilityRegime:"APPLIES"|"NOT_APPLICABLE";accessibilityRequirements:string;accessibilityNotApplicableJustification:string;environmentAffected:boolean;environmentalRequirements:string;specificVariant:string;specialRequirements:string}
export interface TechnicalSpecificationsResult {version:typeof LB118_TECHNICAL_SPECIFICATIONS_VERSION;technicalPurpose:string;technicalRequirements:readonly string[];verificationMethods:readonly string[];accessibilityRegime:string;environmentalTechnicalRegime:string;equivalenceRegime:string;specialRequirements:string;documentaryStatements:readonly {element:string;status:"APPLIES"|"NOT_APPLICABLE";text:string;destinations:readonly ("MEMORY"|"PPT"|"PCAP")[]}[];legalBasis:readonly Basis[];warnings:readonly string[];humanValidationRequired:true;generationBlocked:true;productionReady:false}
const basis=(id:string,article:string,paragraph:string,text:string):Basis=>({id,article,paragraph,relevantOfficialExcerpt:text,officialUrl:`${LCSP}#a${article}`});
const LEGAL=[basis("LCSP-124","124","único","El órgano de contratación aprobará antes de la licitación los documentos que contengan las prescripciones técnicas particulares."),basis("LCSP-125.1","125","1","Las prescripciones técnicas definen las características exigidas a una obra, servicio o suministro."),basis("LCSP-126.1","126","1","Las prescripciones proporcionarán acceso en igualdad y no crearán obstáculos injustificados a la competencia."),basis("LCSP-126.2","126","2","Los requisitos sobre procesos o ciclo de vida deben vincularse al objeto y ser proporcionales a su valor y objetivos."),basis("LCSP-126.3","126","3","Las prestaciones destinadas a personas tendrán en cuenta la accesibilidad universal, salvo justificación suficiente."),basis("LCSP-126.4","126","4","Cuando el objeto afecte al medio ambiente, las prescripciones aplicarán criterios de sostenibilidad y protección ambiental."),basis("LCSP-126.5","126","5","Las prescripciones se formularán por rendimiento o exigencias funcionales, por referencia técnica o combinando ambas vías."),basis("LCSP-126.6","126","6","No se referirán a marcas, procedencias, patentes o tipos para favorecer o descartar empresas; la excepción se justificará y se acompañará de «o equivalente»."),basis("LCSP-128.1","128","1","El órgano podrá exigir medios de prueba para acreditar la conformidad con las prescripciones técnicas.")];
const clean=(v:string,label:string)=>{const x=String(v||"").trim();if(!x||/pendiente|por determinar|no lo s[eé]/i.test(x))throw new Error(`Falta concretar ${label}.`);return x;};
export function evaluateTechnicalSpecifications(i:TechnicalSpecificationsInput):TechnicalSpecificationsResult{
 const purpose=clean(i.technicalPurpose,"la finalidad técnica");if(!i.requirements?.length)throw new Error("Debe existir al menos una prescripción técnica mínima.");
 const seen=new Set<string>(),equivalences:string[]=[];const requirements=i.requirements.map((x,n)=>{const id=clean(x.id,`el identificador del requisito ${n+1}`),category=clean(x.category,`la categoría del requisito ${id}`),requirement=clean(x.requirement,`el contenido del requisito ${id}`),verification=clean(x.verificationMethod,`el método de comprobación del requisito ${id}`),justification=clean(x.justification,`la necesidad y proporcionalidad del requisito ${id}`);if(seen.has(id.toLowerCase()))throw new Error(`Requisito duplicado: ${id}.`);seen.add(id.toLowerCase());if(/adecuad[oa]|suficiente|alta calidad|primera calidad|a satisfacci[oó]n|similar/i.test(requirement)&&requirement.length<120)throw new Error(`El requisito ${id} contiene una expresión indeterminada sin suficiente especificación medible.`);const brand=String(x.brandOrOriginReference||"").trim();if(brand){const reason=clean(x.brandReferenceJustification,`la justificación excepcional de la referencia ${brand}`),equivalent=clean(x.equivalentAcceptanceCriteria,`los criterios de equivalencia de la referencia ${brand}`);equivalences.push(`${brand}: referencia excepcional motivada (${reason}); se admitirán equivalentes que acrediten ${equivalent}.`);}return{id,text:`${id} · ${category}: ${requirement}. Verificación: ${verification}. Justificación: ${justification}.`,verification:`${id}: ${verification}`};});
 const accessibility=i.accessibilityRegime==="APPLIES"?`Se aplican requisitos de accesibilidad universal: ${clean(i.accessibilityRequirements,"los requisitos de accesibilidad")}.`:`No procede incorporar requisitos específicos de accesibilidad. Motivación: ${clean(i.accessibilityNotApplicableJustification,"la motivación de no aplicar accesibilidad")}.`;
 if(i.usedByNaturalPersons&&i.accessibilityRegime==="NOT_APPLICABLE"&&i.accessibilityNotApplicableJustification.trim().length<30)throw new Error("La exclusión de accesibilidad en una prestación destinada a personas requiere motivación suficiente.");
 const environmental=i.environmentAffected?`Se aplican requisitos ambientales vinculados al objeto: ${clean(i.environmentalRequirements,"los requisitos ambientales")}.`:`No se han identificado efectos ambientales específicos que requieran prescripciones adicionales; se mantiene el cumplimiento de la normativa ambiental aplicable.`;
 const equivalence=equivalences.length?equivalences.join(" "):"No se incorporan referencias a marca, procedencia, patente, tipo u origen determinados.";
 const special=String(i.specialRequirements||"").trim();if(i.specificVariant&&i.specificVariant!=="GENERAL"&&!special)throw new Error("La subfamilia técnica declarada requiere concretar sus prescripciones especiales.");const specialText=special||"No proceden prescripciones especiales adicionales para la subfamilia declarada.";
 return{version:LB118_TECHNICAL_SPECIFICATIONS_VERSION,technicalPurpose:purpose,technicalRequirements:requirements.map(x=>x.text),verificationMethods:requirements.map(x=>x.verification),accessibilityRegime:accessibility,environmentalTechnicalRegime:environmental,equivalenceRegime:equivalence,specialRequirements:specialText,documentaryStatements:[{element:"TECHNICAL_PURPOSE",status:"APPLIES",text:purpose,destinations:["MEMORY","PPT"]},{element:"MINIMUM_REQUIREMENTS",status:"APPLIES",text:requirements.map(x=>x.text).join("\n"),destinations:["PPT"]},{element:"VERIFICATION",status:"APPLIES",text:requirements.map(x=>x.verification).join("\n"),destinations:["PPT"]},{element:"ACCESSIBILITY",status:i.accessibilityRegime==="APPLIES"?"APPLIES":"NOT_APPLICABLE",text:accessibility,destinations:["MEMORY","PPT"]},{element:"ENVIRONMENT",status:i.environmentAffected?"APPLIES":"NOT_APPLICABLE",text:environmental,destinations:["MEMORY","PPT"]},{element:"BRANDS_EQUIVALENCE",status:equivalences.length?"APPLIES":"NOT_APPLICABLE",text:equivalence,destinations:["PPT"]},{element:"SPECIAL_OVERLAY",status:special?"APPLIES":"NOT_APPLICABLE",text:specialText,destinations:["PPT"]}],legalBasis:LEGAL,warnings:["Los precedentes sirven para detectar cuestiones, no para copiar requisitos al expediente nuevo.","Cada requisito se incorporará solo tras validar su necesidad, proporcionalidad y método de comprobación.","El PCAP oficial no se reescribe: solo se cumplimentarán las remisiones o destinos técnicos que el modelo autorice."],humanValidationRequired:true,generationBlocked:true,productionReady:false};
}
