export const WORKS_VERTICAL_FIELD_MANIFEST = [
  { fieldPath: "works.projectExists", label: "Existe proyecto de obras", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectApproval", label: "Proyecto aprobado por órgano competente", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.affectsStabilitySafetyOrWatertightness", label: "Afecta a estabilidad, seguridad o estanqueidad", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.supervisionReportAvailable", label: "Informe de supervisión disponible cuando resulte preceptivo", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.replanteoCompleted", label: "Replanteo del proyecto realizado", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.terrainAvailabilityAccredited", label: "Disponibilidad de terrenos acreditada o excepción motivada", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectAndWorksJointAward", label: "Adjudicación conjunta de proyecto y obra", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectScope", label: "Alcance técnico del proyecto", control: "TEXTAREA", section: "TECHNICAL", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.workCategory", label: "Clasificación material de la obra", control: "SELECT", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectMemoryAvailable", label: "Memoria del proyecto disponible", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectPlansAvailable", label: "Planos de conjunto y detalle disponibles", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectTechnicalSpecificationsAvailable", label: "PPT del proyecto disponible", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectBudgetMeasurementsAvailable", label: "Presupuesto, mediciones y precios del proyecto disponibles", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectProgrammeAvailable", label: "Programa de trabajos del proyecto disponible", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectReplanteoReferencesAvailable", label: "Referencias de replanteo disponibles", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectHealthSafetyStudyAvailable", label: "Estudio/estudio básico de seguridad y salud disponible", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.projectOtherLegalDocumentsComplete", label: "Documentación adicional legal/reglamentaria completa", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.simplifiedProjectExpresslyMotivated", label: "Simplificación del proyecto expresamente motivada", control: "BOOLEAN", section: "PREPARATION", requiredForWorkflowReview: false, humanValidationRequired: true },
  { fieldPath: "works.contractorClassificationSummary", label: "Clasificación empresarial exigida o régimen de solvencia", control: "TEXTAREA", section: "PROCEDURE", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "guarantees.provisionalGuaranteeRequired", label: "Garantía provisional", control: "BOOLEAN", section: "PROCEDURE", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "guarantees.definitiveGuaranteePercent", label: "Porcentaje de garantía definitiva", control: "INTEGER", section: "PROCEDURE", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "guarantees.complementaryGuaranteePercent", label: "Porcentaje de garantía complementaria", control: "INTEGER", section: "PROCEDURE", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.executionDirection", label: "Dirección facultativa y régimen de instrucciones", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.materialsAndQualityControl", label: "Materiales, ensayos y control de calidad", control: "TEXTAREA", section: "TECHNICAL", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.healthAndSafetyCoordination", label: "Seguridad y salud / coordinación aplicable", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.certificationRegime", label: "Medición, certificaciones y abonos a cuenta", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.receptionAndGuaranteeRegime", label: "Recepción, garantía, liquidación y vicios ocultos", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "execution.subcontractingRegime", label: "Régimen de subcontratación", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "execution.specificPenalties", label: "Penalidades específicas", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "execution.paymentRegime", label: "Régimen de pago", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
  { fieldPath: "works.dataProtectionRegime", label: "Régimen de protección de datos aplicable", control: "TEXTAREA", section: "EXECUTION", requiredForWorkflowReview: true, humanValidationRequired: true },
] as const;
