import { createHash } from "node:crypto";
import type { UniversalEditableTemplateBinaryStore } from "../lb23/UniversalOdtProductionRenderer";
import { readOdtZip } from "../lb23/OdtPackageCodec";
import type { UniversalEvidenceRecord } from "../lb52/UniversalEvidenceWorkspace";
import { zipStoredFiles } from "../lb95/StoredZipPackage";
import { getWorksGeneralTemplate } from "./WorksGeneralTemplateManifest";
import { renderWorksGeneralTemplate } from "./WorksGeneralEditableTemplateRenderer";

export interface WorksUserDocumentPackage {
  ready:boolean; fileName:string|null; mediaType:"application/zip"; bytes:Uint8Array|null; sha256:string|null; blockers:readonly string[];
  manifest:null|{caseId:string;profile:"WORKS_GENERAL_LB97";generatedAt:string;documents:readonly {kind:"PCAP"|"MEMORIA"|"PPT";fileName:string;sha256:string;provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE";officialModel:false}[];crossDocumentAuditReady:true;projectPreparationAudited:true;humanAcceptanceRequired:true};
}
function hash(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
function raw(record:UniversalEvidenceRecord,path:string){return record.fields[path]?.value;}
function text(record:UniversalEvidenceRecord,path:string):string|null{const v=raw(record,path);if(v===null||v===undefined||v==="")return null;if(Array.isArray(v))return v.map(String).join("; ");return String(v);}
function bool(record:UniversalEvidenceRecord,path:string):string|null{const v=raw(record,path);return typeof v==="boolean"?(v?"Sí":"No"):null;}
function euro(record:UniversalEvidenceRecord,path:string):string|null{const v=raw(record,path);return typeof v==="number"&&Number.isSafeInteger(v)?`${new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v/100)} €`:null;}
function join(...parts:(string|null|undefined)[]){const p=parts.filter((x):x is string=>Boolean(x));return p.length?p.join(" · "):null;}
function requireValue(blockers:string[],slot:string,value:string|null):string{if(value===null){blockers.push(`Falta valor validado para ${slot}.`);return "";}return value;}
function xmlText(bytes:Uint8Array){const e=readOdtZip(bytes).find(x=>x.name==="content.xml");return e?Buffer.from(e.bytes).toString("utf8").replace(/<[^>]+>/g," ").replace(/\s+/g," "):"";}
function lots(record:UniversalEvidenceRecord):string|null{const divided=raw(record,"lots.divisionIntoLots");if(divided===true)return join("División en lotes: sí",text(record,"lots.lots"));if(divided===false)return join("División en lotes: no",text(record,"lots.noDivisionJustification"));return null;}
function economy(record:UniversalEvidenceRecord){return{pbl:euro(record,"baseTenderBudgetCents"),vat:euro(record,"economic.initialVatAmountCents"),total:euro(record,"economic.initialPblVatIncludedCents"),ve:euro(record,"economic.legalEstimatedValueCents")};}

function buildValues(record:UniversalEvidenceRecord){
  const blockers:string[]=[];const e=economy(record);const object=text(record,"object");const cpv=text(record,"cpvMain");const project=text(record,"works.projectScope");
  const preparation=join(`Proyecto existente: ${bool(record,"works.projectExists")??""}`,`Aprobado: ${bool(record,"works.projectApproval")??""}`,`Supervisión: ${bool(record,"works.supervisionReportAvailable")??""}`,`Replanteo: ${bool(record,"works.replanteoCompleted")??""}`,`Terrenos: ${bool(record,"works.terrainAvailabilityAccredited")??""}`);
  const economic=join(e.pbl&&`PBL: ${e.pbl}`,e.vat&&`IVA: ${e.vat}`,e.total&&`Total: ${e.total}`,e.ve&&`VE: ${e.ve}`);
  const solvency=join(text(record,"works.contractorClassificationSummary"),text(record,"criteria.economicSolvency"),text(record,"criteria.technicalSolvency"));
  const guarantees=join(`Provisional: ${bool(record,"guarantees.provisionalGuaranteeRequired")??""}`,text(record,"guarantees.definitiveGuaranteePercent")&&`Definitiva: ${text(record,"guarantees.definitiveGuaranteePercent")}%`,text(record,"guarantees.complementaryGuaranteePercent")&&`Complementaria: ${text(record,"guarantees.complementaryGuaranteePercent")}%`);
  const duration=join(text(record,"durationMonths")&&`${text(record,"durationMonths")} meses`,text(record,"extensionMonths")&&`prórrogas: ${text(record,"extensionMonths")} meses`);
  const pcap:Record<string,string|number|boolean>={caseId:record.caseId,title:requireValue(blockers,"title",object),projectSummary:requireValue(blockers,"projectSummary",project),projectApprovalSummary:requireValue(blockers,"projectApprovalSummary",bool(record,"works.projectApproval")),supervisionSummary:requireValue(blockers,"supervisionSummary",bool(record,"works.supervisionReportAvailable")),replanteoSummary:requireValue(blockers,"replanteoSummary",join(bool(record,"works.replanteoCompleted"),bool(record,"works.terrainAvailabilityAccredited"))),objectSummary:requireValue(blockers,"objectSummary",object),cpvSummary:requireValue(blockers,"cpvSummary",cpv),lotsSummary:requireValue(blockers,"lotsSummary",lots(record)),economicSummary:requireValue(blockers,"economicSummary",economic),budgetSummary:requireValue(blockers,"budgetSummary",join(e.pbl,e.vat,e.total,text(record,"economic.annualityBudgetRows"))),estimatedValueSummary:requireValue(blockers,"estimatedValueSummary",join(e.ve,text(record,"economic.estimatedValueCalculationMethod"))),durationSummary:requireValue(blockers,"durationSummary",duration),classificationSolvencySummary:requireValue(blockers,"classificationSolvencySummary",solvency),procedureSummary:requireValue(blockers,"procedureSummary",text(record,"procedure")),guaranteesSummary:requireValue(blockers,"guaranteesSummary",guarantees),awardCriteriaSummary:requireValue(blockers,"awardCriteriaSummary",text(record,"criteria.awardCriteria")),executionDirectionSummary:requireValue(blockers,"executionDirectionSummary",text(record,"works.executionDirection")),specialExecutionConditionsSummary:requireValue(blockers,"specialExecutionConditionsSummary",text(record,"execution.specialExecutionConditions")),subcontractingSummary:requireValue(blockers,"subcontractingSummary",text(record,"execution.subcontractingRegime")),penaltiesSummary:requireValue(blockers,"penaltiesSummary",text(record,"execution.specificPenalties")),certificationPaymentSummary:requireValue(blockers,"certificationPaymentSummary",join(text(record,"works.certificationRegime"),text(record,"execution.paymentRegime"))),modificationSummary:requireValue(blockers,"modificationSummary",text(record,"execution.plannedModificationRegime")),receptionGuaranteeSummary:requireValue(blockers,"receptionGuaranteeSummary",text(record,"works.receptionAndGuaranteeRegime")),dataProtectionSummary:requireValue(blockers,"dataProtectionSummary",text(record,"works.dataProtectionRegime"))};
  const memory:Record<string,string|number|boolean>={caseId:record.caseId,needSummary:requireValue(blockers,"needSummary",text(record,"need")),objectSummary:requireValue(blockers,"memory.objectSummary",object),projectSummary:requireValue(blockers,"memory.projectSummary",join(project,preparation)),economicSummary:requireValue(blockers,"memory.economicSummary",economic),durationSummary:requireValue(blockers,"memory.durationSummary",duration),procedureSummary:requireValue(blockers,"memory.procedureSummary",text(record,"procedure")),classificationSolvencySummary:requireValue(blockers,"memory.classificationSolvencySummary",solvency),awardCriteriaSummary:requireValue(blockers,"memory.awardCriteriaSummary",text(record,"criteria.awardCriteria")),preparationActsSummary:requireValue(blockers,"preparationActsSummary",preparation),executionSummary:requireValue(blockers,"memory.executionSummary",join(text(record,"works.executionDirection"),text(record,"works.certificationRegime"),text(record,"works.receptionAndGuaranteeRegime")))};
  const ppt:Record<string,string|number|boolean>={caseId:record.caseId,objectSummary:requireValue(blockers,"ppt.objectSummary",object),projectScopeSummary:requireValue(blockers,"projectScopeSummary",project),technicalRequirementsSummary:requireValue(blockers,"technicalRequirementsSummary",text(record,"technical.technicalRequirements")),executionDirectionSummary:requireValue(blockers,"ppt.executionDirectionSummary",text(record,"works.executionDirection")),materialsAndQualitySummary:requireValue(blockers,"materialsAndQualitySummary",text(record,"works.materialsAndQualityControl")),healthSafetyCoordinationSummary:requireValue(blockers,"healthSafetyCoordinationSummary",text(record,"works.healthAndSafetyCoordination")),siteConditionsSummary:requireValue(blockers,"siteConditionsSummary",join(text(record,"technical.executionLocations"),bool(record,"works.terrainAvailabilityAccredited"))),certificationControlSummary:requireValue(blockers,"certificationControlSummary",text(record,"works.certificationRegime"))};
  return{blockers:[...new Set(blockers)],pcap,memory,ppt,common:{object,cpv,pbl:e.pbl,ve:e.ve}};
}

export async function generateWorksUserDocumentPackage(input:{record:UniversalEvidenceRecord;templateStore:UniversalEditableTemplateBinaryStore}):Promise<WorksUserDocumentPackage>{
  const built=buildValues(input.record);if(built.blockers.length)return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,blockers:built.blockers,manifest:null};
  try{
    const configs=[{kind:"PCAP" as const,values:built.pcap,label:"PCAP"},{kind:"MEMORY" as const,values:built.memory,label:"Memoria"},{kind:"PPT" as const,values:built.ppt,label:"PPT"}];
    const docs=[] as Array<{kind:"PCAP"|"MEMORIA"|"PPT";fileName:string;bytes:Uint8Array;sha256:string}>;
    for(const cfg of configs){const manifest=getWorksGeneralTemplate(cfg.kind);const source=await input.templateStore.get(manifest.templateId);if(!source)throw new Error(`No está persistida la plantilla Works ${cfg.kind}.`);const rendered=renderWorksGeneralTemplate({manifest,templateBytes:source.bytes,values:cfg.values});docs.push({kind:cfg.kind==="MEMORY"?"MEMORIA":cfg.kind,fileName:`${cfg.label}_${input.record.caseId.replaceAll("/","-")}.odt`,bytes:rendered.bytes,sha256:rendered.sha256});}
    const texts=docs.map(d=>xmlText(d.bytes));const audit:string[]=[];for(const required of [built.common.object,built.common.cpv,built.common.pbl,built.common.ve].filter((x):x is string=>Boolean(x))){if(!texts.some(t=>t.includes(required)))audit.push(`Auditoría cruzada Works: no se materializa ${required}.`);}if(audit.length)return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,blockers:audit,manifest:null};
    const manifest={caseId:input.record.caseId,profile:"WORKS_GENERAL_LB97" as const,generatedAt:new Date().toISOString(),documents:docs.map(d=>({kind:d.kind,fileName:d.fileName,sha256:d.sha256,provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE" as const,officialModel:false as const})),crossDocumentAuditReady:true as const,projectPreparationAudited:true as const,humanAcceptanceRequired:true as const};const zip=zipStoredFiles([...docs.map(d=>({name:d.fileName,bytes:d.bytes})),{name:"manifest.json",bytes:Buffer.from(JSON.stringify(manifest,null,2),"utf8")}]);return{ready:true,fileName:`Contrata-IA_${input.record.caseId.replaceAll("/","-")}_Works_PCAP-Memoria-PPT.zip`,mediaType:"application/zip",bytes:zip,sha256:hash(zip),blockers:[],manifest};
  }catch(error){return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,blockers:[error instanceof Error?error.message:String(error)],manifest:null};}
}
