export const SERVICE_REGRESSION_CASE_005_CARL_FINE = {
  id: "REG-SERVICE-005",
  step: "11.8.2",
  expediente: "ADM-2024-0004 (CONTR/2024/636510)",
  status: "FINE_SOURCE_EXTRACTION_PENDING_HUMAN_VALIDATION",
  facts: {
    legalCharacterization: "CONTRATO_MIXTO_SERVICIOS_SUMINISTROS_CON_PRESTACION_PRINCIPAL_SERVICIOS",
    serviceSharePercent: 90,
    supplySharePercent: 10,
    lots: false,
    noLotsReason: "Único edificio y prestaciones de limpieza interrelacionadas que requieren coordinación por una única contratista.",
    procedure: "ABIERTO_SIMPLIFICADO",
    ordinaryProcessing: true,
    sara: false,
    initialDurationMonths: 12,
    extensionMonths: 12,
    pblExVat: 44170.33,
    vatRatePercent: 21,
    vatAmount: 9275.77,
    pblIncVat: 53446.10,
    estimatedValueExVat: 106008.80,
    plannedModification: true,
    plannedModificationPercent: 20,
    awardCriteriaMode: "MULTIPLES_SOLO_FORMULAS",
    awardCriteriaTotalPoints: 100,
    economicOfferPoints: 80,
    paymentMode: "MENSUALIDADES_NATURALES_VENCIDAS",
    subrogation: true,
    laborCostReference2025: 24697.91,
    directCosts: 36161.30,
    indirectCosts: 8009.03,
  },
  sourceBoundaries: {
    verified: [
      "contrato mixto de servicios y suministros con prestación principal de servicios",
      "90 % servicios y 10 % suministro accesorio",
      "no división en lotes y su justificación técnica",
      "procedimiento abierto simplificado y tramitación ordinaria",
      "no sujeto a regulación armonizada",
      "duración inicial 12 meses y prórroga máxima 12 meses",
      "PBL 44.170,33 € sin IVA; IVA 9.275,77 €; total 53.446,10 €",
      "valor estimado 106.008,80 € sin IVA, incluyendo prórroga y modificación prevista del 20 %",
      "criterios exclusivamente cuantificables mediante fórmulas, 100 puntos; oferta económica hasta 80 puntos",
      "pago por mensualidades naturales vencidas",
      "coste laboral de referencia 2025 de 24.697,91 €",
      "costes directos 36.161,30 € y costes indirectos 8.009,03 €",
    ],
    deliberatelyPending: [
      "detalle exacto de los 20 puntos restantes de criterios de adjudicación",
      "fórmula exacta de la oferta económica y del resto de criterios",
      "sistema de determinación del precio en la literalidad del Anexo I",
      "solvencia económica y técnica exacta",
      "garantía definitiva y complementaria",
      "condiciones especiales de ejecución completas",
      "penalidades completas del PCAP",
      "causa y redacción exacta de la modificación prevista del 20 %",
      "detalle nominal y económico completo de la subrogación",
      "aplicación o no de DA 33.ª, que no se congela sin evidencia expresa del Anexo I",
    ],
  },
  correctionToStep118: {
    previousSimplification: "SERVICIO",
    correctedSourceCharacterization: "CONTRATO_MIXTO_CON_PRESTACION_PRINCIPAL_SERVICIOS",
    note: "La fuente no trata los suministros accesorios como mera presencia irrelevante: la Memoria califica expresamente el expediente como contrato mixto, cuantificando 90 % servicios y 10 % suministros. La prestación principal sigue siendo el servicio.",
  },
  humanValidationRequired: true,
} as const;

export type ServiceRegressionCase005CarlFineExtraction = typeof SERVICE_REGRESSION_CASE_005_CARL_FINE;
