export const SERVICE_REGRESSION_CASE_005_CARL_CLEANING = {
  id: "REG-SERVICE-005",
  expediente: "ADM-2024-0004 (CONTR/2024/636510)",
  shortName: "Limpieza sede Consejo Andaluz de Relaciones Laborales",
  status: "SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",
  sourceDocuments: ["MEMORIA", "PCAP", "PPT"] as const,
  sourceEvidence: {
    memory: "Memoria justificativa: objeto de limpieza e insuficiencia de medios propios.",
    pcap: "PCAP de servicios mediante procedimiento abierto simplificado ordinario; CPV principal 90919200-4 y CPV accesorios de productos y máquinas de limpieza.",
    ppt: "PPT específico del servicio de limpieza; apartado propio de subrogación de personal.",
  },
  facts: {
    contractType: "SERVICIO",
    serviceCategory: "LIMPIEZA",
    procedure: "ABIERTO_SIMPLIFICADO",
    ordinarySimplified: true,
    mainCpv: "90919200-4",
    accessoryCpvs: ["39830000-9", "42995000-7"] as const,
    insufficientOwnMeans: true,
    personnelSubrogation: true,
    accessoryCleaningMaterialsAndMachineryIncluded: true,
  },
  contrastWithSupplyCases: {
    different: [
      "SERVICIO_EN_LUGAR_DE_SUMINISTRO",
      "INSUFICIENCIA_DE_MEDIOS_PROPIOS",
      "SUBROGACION_DE_PERSONAL",
      "PRESTACION_PRINCIPAL_DE_LIMPIEZA",
      "SUMINISTROS_ACCESORIOS_NO_RECALIFICAN_EL_OBJETO",
    ],
    criticalBoundary: "La inclusión de material diverso, productos, maquinaria y uniformes necesarios para la limpieza no permite por sí sola recalificar el contrato como suministro.",
  },
  regressionGuards: {
    forbiddenSupplyInheritance: [
      "RECLASSIFY_AS_SUPPLY_DUE_TO_ACCESSORY_MATERIALS",
      "FORCE_SUPPLY_DELIVERY_LOGIC",
      "FERRETERIA_CATALOGUE_98_REFERENCES",
      "FORCE_SUPPLY_UNIT_PRICE_MODEL",
      "FORCE_DA33_WITHOUT_SERVICE_SOURCE_EVIDENCE",
      "DROP_PERSONNEL_SUBROGATION",
      "DROP_INSUFFICIENCY_OF_OWN_MEANS",
    ],
    requiredCaseRules: [
      "SERVICE_CONTRACT",
      "CLEANING_SERVICE",
      "OPEN_SIMPLIFIED_ORDINARY_PROCEDURE",
      "MAIN_CPV_90919200_4",
      "INSUFFICIENT_OWN_MEANS",
      "PERSONNEL_SUBROGATION",
      "ACCESSORY_CLEANING_INPUTS_DO_NOT_RECLASSIFY_CONTRACT",
    ],
  },
  extractionScope: {
    verifiedForStep118: [
      "tipo de contrato: servicios",
      "objeto principal: limpieza de la sede del CARL",
      "procedimiento abierto simplificado ordinario",
      "CPV principal 90919200-4",
      "CPV accesorios 39830000-9 y 42995000-7",
      "insuficiencia de medios propios",
      "existencia de subrogación de personal",
      "materiales, maquinaria y uniformes como elementos instrumentales de la prestación de limpieza",
    ],
    deliberatelyNotFrozenYet: [
      "división o no en lotes y su justificación",
      "aplicación o no de DA 33.ª",
      "sistema económico exacto y forma de determinación del precio",
      "PBL, IVA y valor estimado exactos",
      "duración exacta y detalle de prórrogas",
      "porcentaje y causa concreta de modificación prevista",
      "número, ponderación y fórmula exacta de los criterios de adjudicación",
      "solvencia, clasificación y habilitación",
      "garantías",
      "condiciones especiales de ejecución y penalidades",
      "detalle nominal/económico de la información de subrogación",
    ],
  },
  humanValidationRequired: true,
} as const;

export type ServiceRegressionCase005CarlCleaning = typeof SERVICE_REGRESSION_CASE_005_CARL_CLEANING;
