export const SERVICE_REGRESSION_CASE_007_MAINTENANCE_SEVILLE = {
  id: "REG-SERVICE-007",
  step: "11.9",
  expediente: "CONTR 2026 38892",
  shortName: "Mantenimiento integral SAE Sevilla",
  status: "SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",
  sourceDocuments: ["MEMORIA", "PCAP", "PPT"] as const,
  facts: {
    contractType: "SERVICIO",
    object: "Mantenimiento integral y gestión técnica de las instalaciones de los edificios de la Red de Oficinas y Centros del SAE de Sevilla",
    procedure: "ABIERTO",
    sara: true,
    lots: true,
    lotCount: 4,
    lotNames: [
      "Servicios de reparación y mantenimiento de equipos de climatización",
      "Servicios de reparación y mantenimiento de instalaciones contra incendios",
      "Servicios de reparación y mantenimiento de electricidad y equipos electromecánicos",
      "Servicios de reparación y mantenimiento de fontanería, albañilería, pintura y saneamiento",
    ] as const,
    mainAndRelatedCpvs: [
      "50700000-2",
      "50413200-5",
      "50710000-5",
      "45262500-6",
      "45330000-9",
      "45442110-1",
    ] as const,
    insufficientOwnMeansJustified: true,
    gmaoRequiredAsTechnicalMeans: true,
    electronicTendering: true,
  },
  sourceInconsistencies: [
    {
      id: "LOT-PRESENTATION-LIMIT-AMBIGUITY",
      severity: "BLOCKING_FOR_FREEZE",
      source: "PCAP_ANEXO_I",
      statementA: "Limitación de presentación de lotes: No existe limitación.",
      statementB: "Número máximo de lotes para los que una misma persona licitadora puede presentar oferta: Dos lotes.",
      treatment: "No congelar la regla de limitación de lotes hasta revisión humana del documento original o aclaración del órgano de contratación.",
    },
  ] as const,
  contrastWithCarl: {
    different: [
      "SERVICIO_MANTENIMIENTO_TECNICO_EN_LUGAR_DE_LIMPIEZA",
      "CUATRO_LOTES_EN_LUGAR_DE_LOTE_UNICO",
      "ABIERTO_SARA_EN_LUGAR_DE_SIMPLIFICADO_NO_SARA",
      "MULTIPLES_CPV_TECNICOS",
      "GMAO_COMO_MEDIO_TECNICO_EXIGIDO",
      "SIN_CONGELAR_SUBROGACION_COMO_REGLA_PROPIA",
    ],
    purpose: "Probar que el motor generaliza a servicios técnicos multilote y SARA sin heredar la estructura laboral y económica específica del CARL.",
  },
  deliberatelyNotFrozenYet: [
    "PBL, IVA y valor estimado exactos",
    "duración exacta y prórrogas",
    "sistema de determinación del precio",
    "DA 33.ª",
    "modificación prevista",
    "criterios de adjudicación y ponderaciones",
    "existencia y alcance de juicio de valor",
    "garantías",
    "solvencia económica exacta",
    "subrogación de personal",
    "condiciones especiales y penalidades",
    "regla definitiva sobre máximo de lotes ofertables por licitador",
  ] as const,
  humanValidationRequired: true,
} as const;

export type ServiceRegressionCase007MaintenanceSeville = typeof SERVICE_REGRESSION_CASE_007_MAINTENANCE_SEVILLE;
