export const SUPPLY_REGRESSION_CASE_004_SAS_470 = {
  id: "REG-SUPPLY-004",
  expediente: "470/2025",
  shortName: "SAS - nebulización y oxigenoterapia",
  status: "SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",
  sourceDocuments: ["MEMORIA", "PCAP", "PPT", "ANEXOS"] as const,
  facts: {
    contractType: "SUMINISTRO",
    procurementInstrument: "ACUERDO_MARCO",
    procedure: "ABIERTO",
    lots: true,
    successiveSupply: true,
    economicMode: "PRECIOS_UNITARIOS",
    awardMode: "CRITERIOS_MULTIPLES",
    judgmentValueCriteria: true,
    automaticCriteria: true,
    plannedModification: true,
  },
  contrastWithGolden: {
    same: ["SUMINISTRO", "PRECIOS_UNITARIOS", "MODIFICACION_PREVISTA"],
    different: [
      "ACUERDO_MARCO_EN_LUGAR_DE_CONTRATO_ORDINARIO",
      "VARIOS_LOTES_EN_LUGAR_DE_LOTE_UNICO",
      "PROCEDIMIENTO_ABIERTO_EN_LUGAR_DE_SIMPLIFICADO_ABREVIADO",
      "TRACTO_SUCESIVO",
      "CRITERIOS_MULTIPLES",
      "JUICIO_DE_VALOR_MAS_CRITERIOS_AUTOMATICOS",
    ],
  },
  regressionGuards: {
    forbiddenInheritedGoldenRules: [
      "FORCE_SINGLE_LOT",
      "FORCE_ABIERTO_SIMPLIFICADO_ABREVIADO",
      "FORCE_PRICE_ONLY_100",
      "FERRETERIA_CATALOGUE_98_REFERENCES",
      "FORCE_GOLDEN_ECONOMIC_AMOUNTS",
      "TREAT_AS_SINGLE_SUPPLY_CONTRACT_WITHOUT_FRAMEWORK",
    ],
    requiredCaseRules: [
      "FRAMEWORK_AGREEMENT",
      "OPEN_PROCEDURE",
      "MULTIPLE_LOTS",
      "SUCCESSIVE_SUPPLY",
      "UNIT_PRICES",
      "MULTIPLE_AWARD_CRITERIA",
      "JUDGMENT_VALUE_CRITERIA",
      "AUTOMATIC_CRITERIA",
    ],
  },
  extractionScope: {
    verifiedForStep1176: [
      "tipo de contrato: suministro",
      "instrumento: acuerdo marco",
      "procedimiento abierto",
      "existencia de lotes",
      "suministro de tracto sucesivo",
      "precios unitarios",
      "pluralidad de criterios",
      "coexistencia de juicio de valor y criterios automáticos",
      "existencia de modificación prevista",
    ],
    deliberatelyNotFrozenYet: [
      "número exacto y descripción de cada lote",
      "importes económicos por lote y globales",
      "CPV por lote",
      "duración y prórrogas exactas",
      "porcentaje y causa concreta de modificación",
      "ponderación exacta de cada criterio",
      "fórmulas de valoración",
      "número máximo de adjudicatarios por lote",
      "condiciones de los contratos basados",
      "garantías y condiciones especiales de ejecución",
    ],
  },
  humanValidationRequired: true,
} as const;

export type SupplyRegressionCase004Sas470 = typeof SUPPLY_REGRESSION_CASE_004_SAS_470;
