export const SUPPLY_REGRESSION_CASE_002_PANDA = {
  id: "REG-SUPPLY-002",
  expediente: "CONTR 2025 466864 (2025/001003)",
  shortName: "Panda Antivirus - AVRA",
  status: "SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",
  sourceDocuments: ["MEMORIA", "PCAP", "PPT"] as const,
  facts: {
    contractType: "SUMINISTRO",
    object: "Suscripción de productos software de protección corporativa de equipos de AVRA, con soporte técnico asociado.",
    cpv: "48760000-3",
    procedure: "ABIERTO_SIMPLIFICADO",
    lots: false,
    needsBasedDA33: false,
    initialDurationMonths: 36,
    extensions: false,
    pblExVat: 61192.25,
    vatExVat: 12850.37,
    pblVatIncluded: 74042.62,
    estimatedValueExVat: 61192.25,
    economicMode: "PRECIOS_UNITARIOS",
    priceRevision: false,
    unitIncreaseUpTo10PercentArt301_2: false,
    awardMode: "PRECIO_UNICO",
    awardPoints: 100,
    guaranteeDefinitive: true,
    guaranteeDefinitivePercentOnPbl: 5,
    specialExecutionCondition: "TRANSPARENCIA_FISCAL",
    paymentMode: "PAGOS_PARCIALES_CERTIFICACION_ANUAL",
    dataProcessingByContractor: false,
    plannedModification: true,
    plannedModificationPercent: 20,
    plannedModificationReason: "REDUCCION_FINANCIACION_MEDIDAS_ESTABILIDAD_PRESUPUESTARIA",
    plannedModificationIsDA33NeedsIncrease: false,
  },
  contrastWithGolden: {
    same: ["SUMINISTRO", "LOTE_UNICO", "PRECIO_100", "PRECIOS_UNITARIOS"],
    different: [
      "SIN_DA33",
      "ABIERTO_SIMPLIFICADO_ORDINARIO",
      "SIN_PRORROGA",
      "VE_IGUAL_PBL",
      "MODIFICACION_20_POR_REDUCCION_FINANCIACION_NO_POR_MAYORES_NECESIDADES",
      "GARANTIA_DEFINITIVA_5_POR_CIENTO",
      "CONDICION_ESPECIAL_TRANSPARENCIA_FISCAL",
    ],
  },
  regressionGuards: {
    forbiddenInheritedGoldenRules: [
      "DA33_ACTIVE",
      "DA33_MAXIMUM_BUDGET",
      "DA33_NEEDS_INCREASE_MODIFICATION",
      "EXTENSIONS_12_12",
      "FERRETERIA_CATALOGUE_98_REFERENCES",
      "PACKAGING_WASTE_SPECIAL_EXECUTION_CONDITION",
    ],
    requiredCaseRules: [
      "DA33_DISABLED",
      "NO_EXTENSIONS",
      "UNIT_PRICES",
      "PRICE_ONLY_100",
      "PLANNED_MODIFICATION_REDUCTION_FINANCING_20_PERCENT",
      "DEFINITIVE_GUARANTEE_5_PERCENT_PBL",
    ],
  },
  humanValidationRequired: true,
} as const;

export type SupplyRegressionCase002Panda = typeof SUPPLY_REGRESSION_CASE_002_PANDA;
