export const SUPPLY_REGRESSION_CASE_003_AULAS_DIGITALES = {
  id: "REG-SUPPLY-003",
  expediente: "CONTR 2025 0000489703",
  shortName: "Equipamiento para aulas digitales",
  status: "SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",
  sourceDocuments: ["MEMORIA", "MEMORIA_COMPLEMENTARIA", "PCAP", "PPT"] as const,
  facts: {
    contractType: "SUMINISTRO",
    procedure: "ABIERTO",
    sara: true,
    lots: true,
    lotCount: 9,
    needsBasedDA33: true,
    europeanFunds: true,
    economicMode: "PRECIOS_UNITARIOS",
    awardMode: "CRITERIOS_MULTIPLES",
    plannedModification: true,
    extensions: true,
  },
  contrastWithGolden: {
    same: ["SUMINISTRO", "DA33_ACTIVA", "PRECIOS_UNITARIOS", "PRORROGA", "MODIFICACION_PREVISTA"],
    different: [
      "NUEVE_LOTES_EN_LUGAR_DE_LOTE_UNICO",
      "PROCEDIMIENTO_ABIERTO_EN_LUGAR_DE_SIMPLIFICADO_ABREVIADO",
      "SARA",
      "FONDOS_EUROPEOS",
      "CRITERIOS_MULTIPLES_EN_LUGAR_DE_PRECIO_UNICO",
    ],
  },
  regressionGuards: {
    forbiddenInheritedGoldenRules: [
      "FORCE_SINGLE_LOT",
      "FORCE_ABIERTO_SIMPLIFICADO_ABREVIADO",
      "FORCE_PRICE_ONLY_100",
      "FORCE_AUTOFINANCING",
      "FERRETERIA_CATALOGUE_98_REFERENCES",
      "FORCE_GOLDEN_ECONOMIC_AMOUNTS",
    ],
    requiredCaseRules: [
      "DA33_ENABLED",
      "NINE_LOTS",
      "OPEN_PROCEDURE",
      "SARA_ENABLED",
      "EUROPEAN_FUNDS_ENABLED",
      "UNIT_PRICES",
      "MULTIPLE_AWARD_CRITERIA",
    ],
  },
  extractionScope: {
    verifiedForStep1174: [
      "tipo de contrato",
      "procedimiento abierto",
      "sujeción SARA",
      "9 lotes",
      "DA 33.ª activa",
      "financiación europea",
      "precios unitarios",
      "pluralidad de criterios",
      "existencia de prórroga",
      "existencia de modificación prevista",
    ],
    deliberatelyNotFrozenYet: [
      "importes económicos detallados",
      "porcentajes o causas concretas de modificación",
      "duración exacta y detalle de prórrogas",
      "ponderación y fórmula de cada criterio de adjudicación",
      "CPV por lote",
      "descripción individual de cada uno de los 9 lotes",
      "condiciones especiales y garantías por lote",
    ],
  },
  humanValidationRequired: true,
} as const;

export type SupplyRegressionCase003AulasDigitales = typeof SUPPLY_REGRESSION_CASE_003_AULAS_DIGITALES;
