export const SUPPLY_REGRESSION_CASE_005_TABLETS_PLATFORM = {
  id: "REG-SUPPLY-005",
  expediente: "CONTR 2024 0001239412",
  shortName: "Tablets y plataforma de gestión",
  status: "SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",
  sourceDocuments: ["MEMORIA", "PCAP", "PPT"] as const,
  facts: {
    contractType: "SUMINISTRO",
    complexSupplyWithPlatformComponent: true,
    procedure: "ABIERTO",
    lots: false,
    needsBasedDA33: true,
    economicMode: "PRECIOS_UNITARIOS",
    awardMode: "CRITERIOS_MULTIPLES",
    formulaEvaluatedCriteria: true,
    plannedModification: true,
    extensions: true,
  },
  contrastWithGolden: {
    same: [
      "SUMINISTRO",
      "LOTE_UNICO",
      "DA33_ACTIVA",
      "PRECIOS_UNITARIOS",
      "PRORROGA",
      "MODIFICACION_PREVISTA",
    ],
    different: [
      "SUMINISTRO_COMPLEJO_CON_COMPONENTE_PLATAFORMA",
      "PROCEDIMIENTO_ABIERTO_EN_LUGAR_DE_SIMPLIFICADO_ABREVIADO",
      "CRITERIOS_MULTIPLES_EVALUABLES_MEDIANTE_FORMULAS_EN_LUGAR_DE_PRECIO_UNICO",
    ],
  },
  regressionGuards: {
    forbiddenInheritedGoldenRules: [
      "FORCE_ABIERTO_SIMPLIFICADO_ABREVIADO",
      "FORCE_PRICE_ONLY_100",
      "FERRETERIA_CATALOGUE_98_REFERENCES",
      "FORCE_GOLDEN_ECONOMIC_AMOUNTS",
      "DROP_PLATFORM_COMPONENT",
      "RECLASSIFY_AS_SERVICE_WITHOUT_SOURCE_VALIDATION",
      "RECLASSIFY_AS_MIXED_CONTRACT_WITHOUT_SOURCE_VALIDATION",
    ],
    requiredCaseRules: [
      "SUPPLY_CONTRACT",
      "COMPLEX_SUPPLY_WITH_PLATFORM_COMPONENT",
      "OPEN_PROCEDURE",
      "SINGLE_LOT",
      "DA33_ENABLED",
      "UNIT_PRICES",
      "MULTIPLE_AWARD_CRITERIA",
      "FORMULA_EVALUATED_CRITERIA",
    ],
  },
  extractionScope: {
    verifiedForStep1178: [
      "tipo de contrato: suministro",
      "existencia de componente de plataforma de gestión dentro del objeto",
      "procedimiento abierto",
      "lote único",
      "DA 33.ª activa",
      "precios unitarios",
      "pluralidad de criterios evaluables mediante fórmulas",
      "existencia de prórroga",
      "existencia de modificación prevista",
    ],
    deliberatelyNotFrozenYet: [
      "calificación jurídica detallada del componente de plataforma y su peso económico",
      "eventual régimen de prestaciones accesorias",
      "importes económicos detallados",
      "CPV principal y CPV complementarios",
      "duración exacta y detalle de prórrogas",
      "porcentaje y causa concreta de modificación",
      "número, denominación, ponderación y fórmula exacta de cada criterio",
      "presupuesto máximo DA 33.ª y método concreto de cálculo del valor estimado",
      "garantías y condiciones especiales de ejecución",
      "protección de datos, seguridad y niveles de servicio de la plataforma",
    ],
  },
  humanValidationRequired: true,
} as const;

export type SupplyRegressionCase005TabletsPlatform = typeof SUPPLY_REGRESSION_CASE_005_TABLETS_PLATFORM;
