export const SUPPLY_REGRESSION_CASE_006_VEIASA_WINDOWS = {
  id: "REG-SUPPLY-006",
  expediente: "CF050-21-058",
  shortName: "VEIASA - licencias Windows Server",
  status: "SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",
  sourceDocuments: ["MEMORIA", "PCAP", "PPT", "INFORME"] as const,
  facts: {
    contractType: "SUMINISTRO",
    procedure: "ABIERTO_SIMPLIFICADO",
    lots: false,
    needsBasedDA33: false,
    economicMode: "PRECIO_GLOBAL",
    awardMode: "PRECIO_UNICO",
    extensions: false,
    plannedModification: false,
  },
  contrastWithGolden: {
    same: ["SUMINISTRO", "LOTE_UNICO", "PRECIO_UNICO"],
    different: [
      "SIN_DA33",
      "ABIERTO_SIMPLIFICADO_ORDINARIO",
      "PRECIO_GLOBAL_EN_LUGAR_DE_PRECIOS_UNITARIOS",
      "SIN_PRORROGA",
      "SIN_MODIFICACION_PREVISTA",
    ],
  },
  regressionGuards: {
    forbiddenInheritedGoldenRules: [
      "DA33_ACTIVE",
      "DA33_MAXIMUM_BUDGET",
      "UNIT_PRICES",
      "EXTENSIONS_12_12",
      "DA33_NEEDS_INCREASE_MODIFICATION",
      "FERRETERIA_CATALOGUE_98_REFERENCES",
      "FORCE_GOLDEN_ECONOMIC_AMOUNTS",
    ],
    requiredCaseRules: [
      "SUPPLY_CONTRACT",
      "OPEN_SIMPLIFIED_PROCEDURE",
      "SINGLE_LOT",
      "DA33_DISABLED",
      "GLOBAL_PRICE",
      "PRICE_ONLY",
      "NO_EXTENSIONS",
      "NO_PLANNED_MODIFICATION",
    ],
  },
  extractionScope: {
    verifiedForStep11710: [
      "tipo de contrato: suministro",
      "procedimiento abierto simplificado",
      "lote único",
      "DA 33.ª no aplicable",
      "precio global",
      "criterio único económico",
      "sin prórroga",
      "sin modificación prevista",
    ],
    deliberatelyNotFrozenYet: [
      "importe exacto del PBL y del valor estimado",
      "CPV exacto",
      "duración exacta",
      "plazo de entrega o implantación",
      "garantía definitiva",
      "solvencia y habilitación",
      "fórmula exacta de valoración económica",
      "condiciones especiales de ejecución",
      "obligaciones técnicas y niveles de soporte",
    ],
  },
  humanValidationRequired: true,
} as const;

export type SupplyRegressionCase006VeiasaWindows = typeof SUPPLY_REGRESSION_CASE_006_VEIASA_WINDOWS;
