import fs from "node:fs";
import {describe,expect,it} from "vitest";
import {LB102_PILOT_PACKAGE_CATALOG,pilotPackageDescriptor} from "../src/application/operations/lb102/LB102PilotPackageCatalog";
import {LB102_SUPPLY_FERRETERIA,LB102_SUPPLY_PANDA} from "../src/application/operations/lb102/RealSupplyPilotSnapshots";

describe("LB102 catálogo de paquetes reales del piloto",()=>{
 it("publica exactamente dos Supply y dos Service sin duplicados",()=>{expect(LB102_PILOT_PACKAGE_CATALOG).toHaveLength(4);expect(new Set(LB102_PILOT_PACKAGE_CATALOG.map(x=>x.id)).size).toBe(4);expect(LB102_PILOT_PACKAGE_CATALOG.filter(x=>x.family==="SUPPLY")).toHaveLength(2);expect(LB102_PILOT_PACKAGE_CATALOG.filter(x=>x.family==="SERVICE")).toHaveLength(2);});
 it("protege las cuatro identidades reales",()=>{expect(LB102_PILOT_PACKAGE_CATALOG.map(x=>x.caseId)).toEqual(["CONTR/2026/240267","CONTR 2025 466864","CONTR 2025 0000468715","CONTR 2026 38892"]);expect(pilotPackageDescriptor("inventado")).toBeNull();});
 it("congela ferretería y Panda como snapshots de caso, no defaults generales",()=>{expect(LB102_SUPPLY_FERRETERIA.fields.cpvMain?.value).toBe("44316400-2");expect(LB102_SUPPLY_FERRETERIA.fields["economic.legalEstimatedValueCents"]?.value).toBe(2532586);expect(LB102_SUPPLY_FERRETERIA.fields["economic.needsBasedContractDa33"]?.value).toBe(true);expect(LB102_SUPPLY_FERRETERIA.fields["economic.annualityBudgetRows"]?.value).toEqual([{year:2026,amountCents:159606,budgetApplication:"1439010000 G/32L/22000/00 01",vatIncluded:true},{year:2027,amountCents:638423,budgetApplication:"1439010000 G/32L/22000/00 01",vatIncluded:true},{year:2028,amountCents:478816,budgetApplication:"1439010000 G/32L/22000/00 01",vatIncluded:true}]);expect(LB102_SUPPLY_PANDA.fields.cpvMain?.value).toBe("48760000-3");expect(LB102_SUPPLY_PANDA.fields["lots.divisionIntoLots"]?.value).toBe(false);});
 it("el paquete Ferretería usa manifest atómico determinista post-Intervención",()=>{const source=fs.readFileSync("src/application/operations/lb102/FerreteriaPilotPackageGenerator.ts","utf8");expect(source).not.toContain("generatedAt: new Date");expect(source).toContain("schemaVersion:3");expect(source).toContain("snapshotHash");expect(source).toContain("generationId");expect(source).toContain("interventionRegressionApplied:true");expect(source).toContain("estimatedValueCents:2532586");expect(source).toContain("annuality2026VatIncludedCents:159606");});
 it("todos los pilotos se publican como tríadas atómicas",()=>{for(const item of LB102_PILOT_PACKAGE_CATALOG)expect(item.atomicDocumentSet).toEqual(["PCAP","MEMORIA","PPT"]);});
 it("la UI no permite introducir SHA manual y usa revisión ligada al paquete",()=>{const ui=fs.readFileSync("src/interfaces/lb102/LB102PilotAcceptanceUi.ts","utf8");expect(ui).not.toContain('id="sha"');expect(ui).toContain("/api/lb102/pilot-packages/");const runtime=fs.readFileSync("src/interfaces/lb102/LB102RuntimeServer.ts","utf8");expect(runtime).toContain("La revisión manual por SHA está deshabilitada");expect(runtime).toContain("packageSha256:pkg.sha256");});
});
