import fs from "node:fs";
import {describe,expect,it} from "vitest";
import {ferreteriaInterventionConsistencyAudit} from "../src/application/operations/lb102/FerreteriaPilotPackageGenerator";

const pcapOk=`Sus anexos han sido informados por la Asesoría Jurídica del Servicio Andaluz de Empleo el día 29 de julio de 2026 (nº de informe: AJ-SAE 2026/16). Material defectuoso: sustitución en un plazo máximo de tres (3) días hábiles. En cualquier caso, se considerará desproporcionada la baja superior a 25 unidades porcentuales respecto al presupuesto base de licitación. Cuando concurran cuatro o más licitadores se aplicará el artículo 85 RGLCAP. Garantía para bienes duraderos; quedan exceptuados los productos de carácter fungible o consumible.`;
const memoryOk=`Método de cálculo del valor estimado: presupuesto base y modificación prevista por aumento del consumo estimado sobre las referencias incluidas. No se incorporan artículos nuevos.`;
const pptOk=`La empresa adjudicataria deberá sustituir el material defectuoso en un plazo máximo de tres (3) días hábiles. El precio unitario establecido en la adjudicación del contrato será el único concepto de facturación. Se establece un plazo de garantía general de tres (3) años para bienes de naturaleza duradera. Quedan exceptuados los productos de carácter fungible o consumible.`;

describe("LB102 Ferretería post-Intervención: gate semántico de fuente",()=>{
 it("acepta las seis correcciones cuando están realmente materializadas",()=>{expect(ferreteriaInterventionConsistencyAudit(pcapOk,memoryOk,pptOk)).toEqual([]);});
 it("detecta residuos visibles equivalentes a los encontrados en la tríada subida",()=>{const badMemory=`${memoryOk} Incorporación al contrato de otros artículos no contemplados en el listado de material de ferretería.`;const badPpt=`La empresa adjudicataria deberá sustituir el material defectuoso en un plazo máximo de cinco (5) tres (3) días hábiles. El precio unitario establecido en la adjudicación del contrato acuerdo marco será el único concepto de facturación. Se fija un plazo de garantía de tres (3) años para los suministros realizados. Quedarán exceptuados los productos de carácter fungible.`;const blockers=ferreteriaInterventionConsistencyAudit(pcapOk,badMemory,badPpt);expect(blockers.some(x=>x.includes("artículos no contemplados"))).toBe(true);expect(blockers.some(x=>x.includes("5 días hábiles"))).toBe(true);expect(blockers.some(x=>x.includes("acuerdo marco"))).toBe(true);expect(blockers.some(x=>x.includes("garantía genérica"))).toBe(true);});
 it("no confunde otros plazos de cinco días del expediente con el plazo de material defectuoso",()=>{const ppt=`${pptOk} Trámite de audiencia por un plazo de cinco (5) días hábiles.`;expect(ferreteriaInterventionConsistencyAudit(pcapOk,memoryOk,ppt)).toEqual([]);});
 it("elimina del gate las magnitudes económicas históricas que ya no pueden imponerse sobre una fuente posterior",()=>{const source=fs.readFileSync("src/application/operations/lb102/FerreteriaPilotPackageGenerator.ts","utf8");expect(source).not.toContain('for(const required of ["21.793,15","18.160,96"]');expect(source).not.toContain('persiste el valor estimado histórico descartado 25.325,86');});
});
