import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {evaluateLB102PilotAcceptance} from "../src/application/operations/lb102/LB102PilotAcceptanceGate";
import {LB102_REQUIRED_PILOT_CASES} from "../src/application/operations/lb102/LB102PilotAcceptancePolicy";
import {LB102PilotAcceptanceStore} from "../src/application/operations/lb102/LB102PilotAcceptanceStore";
const roots:string[]=[];function store(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"lb102-acceptance-"));roots.push(root);return new LB102PilotAcceptanceStore(path.join(root,"acceptance.json"));}
afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
function status(s:LB102PilotAcceptanceStore){const e=s.evidence();return evaluateLB102PilotAcceptance({lb99PilotScopeClosed:true,sourceGovernanceReady:true,freeGenerationPathVerified:true,lb101SecurityReady:true,supplyRealCaseRuns:2,serviceRealCaseRuns:2,negativeRegressionConflictPassed:true,negativeRegressionMissingValidationPassed:true,negativeRegressionTemplateIntegrityPassed:true,userAcceptanceSessions:e.userAcceptanceSessions,distinctPilotUsers:e.distinctPilotUsers,criticalDefectsOpen:e.criticalDefectsOpen,generatedPackagesHumanReviewed:e.generatedPackagesHumanReviewed,acceptanceDecisionRecorded:e.acceptanceDecisionRecorded});}
function reviewAll(s:LB102PilotAcceptanceStore){LB102_REQUIRED_PILOT_CASES.forEach((c,i)=>s.recordReview({caseId:c.caseId,family:c.family,packageSha256:(i+1).toString(16).repeat(64),accepted:true,criticalDefectsOpen:0},i<2?"revisor.a":"admin.b"));}
describe("LB102 evidencia humana del piloto",()=>{
 it("solo alcanza viabilidad con dos usuarios, los cuatro casos canónicos sin críticos y aceptación posterior motivada",()=>{const s=store();s.recordSession("revisor.a");s.recordSession("admin.b");reviewAll(s);s.recordDecision({accepted:true,rationale:"Los cuatro paquetes canónicos han sido revisados y no presentan defectos críticos abiertos."},"admin.b");const x=status(s);expect(x.technicalPrePilotReady).toBe(true);expect(x.appViableForPilot).toBe(true);expect(x.productionReady).toBe(false);});
 it("rechaza expedientes ajenos y familias incompatibles",()=>{const s=store();expect(()=>s.recordReview({caseId:"CASE-AJENO",family:"SUPPLY",packageSha256:"a".repeat(64),accepted:true,criticalDefectsOpen:0},"revisor.a")).toThrow(/cuatro casos canónicos/);const ferreteria=LB102_REQUIRED_PILOT_CASES[0]!;expect(()=>s.recordReview({caseId:ferreteria.caseId,family:"SERVICE",packageSha256:"b".repeat(64),accepted:true,criticalDefectsOpen:0},"revisor.a")).toThrow(/familia declarada/);});
 it("exige identidad nominativa del revisor",()=>{const s=store();const c=LB102_REQUIRED_PILOT_CASES[0]!;expect(()=>s.recordReview({caseId:c.caseId,family:c.family,packageSha256:"a".repeat(64),accepted:true,criticalDefectsOpen:0},"   ")).toThrow(/identidad nominativa del revisor/);});
 it("no cuenta dos veces el mismo paquete",()=>{const s=store();const c=LB102_REQUIRED_PILOT_CASES[0]!;const review={caseId:c.caseId,family:c.family,packageSha256:"a".repeat(64),accepted:true,criticalDefectsOpen:0};s.recordReview(review,"revisor.a");expect(()=>s.recordReview(review,"admin.b")).toThrow(/ya tiene revisión/);});
 it("dos versiones del mismo expediente cuentan como un caso y la última revisión define los críticos abiertos",()=>{const s=store();const c=LB102_REQUIRED_PILOT_CASES[0]!;s.recordReview({caseId:c.caseId,family:c.family,packageSha256:"a".repeat(64),accepted:false,criticalDefectsOpen:2},"revisor.a");s.recordReview({caseId:c.caseId,family:c.family,packageSha256:"b".repeat(64),accepted:true,criticalDefectsOpen:0},"admin.b");const e=s.evidence();expect(e.totalPackageReviews).toBe(2);expect(e.generatedPackagesHumanReviewed).toBe(1);expect(e.distinctCasesHumanReviewed).toBe(1);expect(e.criticalDefectsOpen).toBe(0);});
 it("impide registrar aceptación afirmativa antes de completar la evidencia",()=>{const s=store();expect(()=>s.recordDecision({accepted:true,rationale:"Aceptación prematura."},"admin.b")).toThrow(/antes de completar la evidencia UAT/);expect(s.evidence().acceptanceDecisionRecorded).toBe(false);});
 it("permite registrar rechazo aun con evidencia incompleta",()=>{const s=store();s.recordDecision({accepted:false,rationale:"Se detectan incidencias pendientes."},"admin.b");expect(s.evidence().acceptanceDecisionRecorded).toBe(false);expect(status(s).appViableForPilot).toBe(false);});
 it("una nueva revisión posterior invalida la aceptación previa hasta una nueva decisión explícita",()=>{const s=store();s.recordSession("revisor.a");s.recordSession("admin.b");reviewAll(s);s.recordDecision({accepted:true,rationale:"Primera aceptación completa."},"admin.b");expect(s.evidence().acceptanceDecisionRecorded).toBe(true);const c=LB102_REQUIRED_PILOT_CASES[0]!;s.recordReview({caseId:c.caseId,family:c.family,packageSha256:"e".repeat(64),accepted:true,criticalDefectsOpen:0},"revisor.a");expect(s.evidence().acceptanceDecisionRecorded).toBe(false);expect(status(s).appViableForPilot).toBe(false);s.recordDecision({accepted:true,rationale:"Aceptación renovada tras revisar la nueva versión del paquete."},"admin.b");expect(s.evidence().acceptanceDecisionRecorded).toBe(true);expect(status(s).appViableForPilot).toBe(true);});
});
