import {describe,expect,it} from "vitest";
import {evaluateGuarantees} from "../src/application/intake/lb112/GuaranteesEngine";
const base={procedure:"ABIERTO_SIMPLIFICADO_ABREVIADO" as const,contractType:"SUPPLY" as const,provisionalRequired:false,definitiveRegime:"EXEMPT" as const,unitPriceContract:true,complementaryRequired:false,warrantyPeriodMonths:12};
describe("LB112 · garantías",()=>{
 it("expresa todas las decisiones del ASA y separa el plazo",()=>{const r=evaluateGuarantees(base);expect(r.documentaryStatements).toHaveLength(5);expect(r.definitivePercent).toBe(0);expect(r.documentaryStatements.find(x=>x.element==="DEFINITIVE")?.text).toContain("159.6.f");expect(r.documentaryStatements.find(x=>x.element==="WARRANTY_PERIOD")).toMatchObject({status:"APPLIES"});});
 it("valida los máximos y las motivaciones excepcionales",()=>{expect(()=>evaluateGuarantees({...base,procedure:"ABIERTO",provisionalRequired:true,provisionalPercent:4,provisionalPublicInterestReason:"Riesgo"})).toThrow(/3 %/);expect(()=>evaluateGuarantees({...base,procedure:"ABIERTO",provisionalRequired:true,provisionalPercent:3,provisionalPublicInterestReason:""})).toThrow(/interés público/);expect(()=>evaluateGuarantees({...base,procedure:"ABIERTO",definitiveRegime:"ORDINARY_5",complementaryRequired:true,complementaryPercent:6,complementaryRiskReason:"Riesgo"})).toThrow(/5 %/);});
 it("usa PBL sin IVA como base en precios unitarios",()=>{const r=evaluateGuarantees({...base,procedure:"ABIERTO",definitiveRegime:"ORDINARY_5"});expect(r.documentaryStatements.find(x=>x.element==="DEFINITIVE_BASE")?.text).toContain("presupuesto base de licitación, IVA excluido");});
 it("exige motivar una exención y un plazo cero",()=>{expect(()=>evaluateGuarantees({...base,procedure:"ABIERTO",definitiveRegime:"EXEMPT"})).toThrow(/exención/);expect(()=>evaluateGuarantees({...base,warrantyPeriodMonths:0})).toThrow(/ausencia de plazo/);const r=evaluateGuarantees({...base,warrantyPeriodMonths:0,warrantyNotRequiredReason:"Prestación instantánea comprobable íntegramente en la recepción."});expect(r.documentaryStatements.find(x=>x.element==="WARRANTY_PERIOD")).toMatchObject({status:"NOT_APPLICABLE"});});
});
