import {describe,expect,it} from "vitest";
import {evaluateExecutionReceiptPayment} from "../src/application/intake/lb117/ExecutionReceiptPaymentEngine";
const base={contractType:"SUPPLY" as const,contractManager:"Jefatura del Servicio de Contratación",contractManagerFunctions:"Supervisar, comprobar y dictar instrucciones dentro de las facultades atribuidas.",executionLocations:["Almacén central"],executionMonitoringRegime:"Acta de cada entrega y comprobación cuantitativa y cualitativa.",deliveryOrPerformanceRegime:"Entregas parciales conforme a pedidos emitidos durante la vigencia.",receiptAndAcceptanceRegime:"Acta formal firmada tras la comprobación de cada entrega.",receiptDeadlineDays:30,extendedReceiptDeadlineJustification:"",defectCorrectionRegime:"Los defectos constarán en acta y deberán subsanarse o sustituirse.",paymentMode:"SUCCESSIVE" as const,invoiceSubmissionRegime:"Factura electrónica tras cada entrega, dirigida a las unidades y códigos declarados por la Administración.",paymentRegime:"Pago de cada entrega efectivamente recibida de conformidad."};
describe("LB117 · responsable, ejecución, recepción y pago",()=>{
 it("estructura la secuencia y sus destinos sin confundir conformidad y pago",()=>{const r=evaluateExecutionReceiptPayment(base);expect(r.documentaryStatements.map(x=>x.element)).toEqual(["CONTRACT_MANAGER","EXECUTION","RECEIPT_CONFORMITY","INVOICING","PAYMENT"]);expect(r.paymentRegime).toContain("treinta días");expect(r.warnings.join(" ")).toMatch(/no equivale.*pago/i);expect(r.legalBasis.map(x=>x.id)).toContain("LCSP-301.1");});
 it("exige identidad organizativa, lugar y controles concretos",()=>{expect(()=>evaluateExecutionReceiptPayment({...base,contractManager:"Por determinar"})).toThrow(/responsable/i);expect(()=>evaluateExecutionReceiptPayment({...base,executionLocations:[]})).toThrow(/lugar/i);expect(()=>evaluateExecutionReceiptPayment({...base,receiptAndAcceptanceRegime:"No lo sé"})).toThrow(/recepción/i);});
 it("motiva un plazo de recepción superior al mes",()=>{expect(()=>evaluateExecutionReceiptPayment({...base,receiptDeadlineDays:45})).toThrow(/justificación/i);const r=evaluateExecutionReceiptPayment({...base,receiptDeadlineDays:45,extendedReceiptDeadlineJustification:"La pluralidad de sedes exige comprobaciones funcionales coordinadas."});expect(r.warnings.join(" ")).toMatch(/superior a un mes/i);});
 it("aplica la especialidad de servicios",()=>{const r=evaluateExecutionReceiptPayment({...base,contractType:"SERVICE",deliveryOrPerformanceRegime:"Prestación mensual con informe de actividad."});expect(r.executionRegime).toContain("Prestación");expect(r.legalBasis.map(x=>x.id)).toContain("LCSP-311.3");});
});
