import {describe,expect,it} from "vitest";
import {evaluateSubcontractingAssignment} from "../src/application/intake/lb114/SubcontractingAssignmentEngine";
const base={contractType:"SUPPLY" as const,supplyIncludesInstallationOrServices:false,secretOrSecurityContract:false,requireOfferDisclosure:false,criticalTasks:[],estimatedValueCents:4_000_000,expectedSubcontractingPercent:0,contractorQualitiesDecisive:false,assignmentWouldRestrictCompetition:false};
describe("LB114 · subcontratación y cesión",()=>{
 it("expresa separadamente lo aplicable y lo no aplicable",()=>{const r=evaluateSubcontractingAssignment(base);expect(r.documentaryStatements).toHaveLength(6);expect(r.documentaryStatements.find(x=>x.element==="CRITICAL_TASKS")?.status).toBe("NOT_APPLICABLE");expect(r.assignmentRegime).toContain("Se admite");expect(r.legalBasis.map(x=>x.article)).toContain("214");});
 it("solo admite tareas críticas en prestaciones legalmente cubiertas",()=>{expect(()=>evaluateSubcontractingAssignment({...base,criticalTasks:[{task:"Instalación",reason:"Seguridad"}]})).toThrow(/suministro puro/);const r=evaluateSubcontractingAssignment({...base,supplyIncludesInstallationOrServices:true,criticalTasks:[{task:"Puesta en servicio",reason:"Asegura la responsabilidad integral"}]});expect(r.criticalTasksRegime).toContain("Puesta en servicio");});
 it("detecta el control de pagos obligatorio del artículo 217.2",()=>{const r=evaluateSubcontractingAssignment({...base,contractType:"SERVICE",estimatedValueCents:500_000_001,expectedSubcontractingPercent:30});expect(r.documentaryStatements.find(x=>x.element==="PAYMENT_CONTROL")?.status).toBe("APPLIES");expect(r.paymentControlRegime).toContain("obligatoriamente");});
 it("excluye la cesión por cualidades determinantes y valida porcentajes",()=>{expect(evaluateSubcontractingAssignment({...base,contractorQualitiesDecisive:true}).assignmentRegime).toContain("No se admite");expect(()=>evaluateSubcontractingAssignment({...base,expectedSubcontractingPercent:101})).toThrow(/entre 0 y 100/);});
});
