import {describe,expect,it} from "vitest";
import {evaluatePlannedModification} from "../src/application/intake/lb115/PlannedModificationEngine";
const base={contractType:"SUPPLY" as const,needsBasedContractDa33:false,planned:false,planningBaseExVatCents:1_000_000,maximumAggregatePercent:0,declaredEstimatedValueExVatCents:1_000_000,causes:[],procedure:"",altersGlobalNature:false,introducesNewUnitPrices:false};
describe("LB115 · modificaciones previstas",()=>{
 it("documenta expresamente que no se prevén modificaciones",()=>{const r=evaluatePlannedModification(base);expect(r.documentaryStatements.find(x=>x.element==="PLANNED_MODIFICATION")).toMatchObject({status:"NOT_APPLICABLE"});expect(r.structuredRegime.other.description).toBe("No procede.");expect(r.modificationPercent).toBe(0);});
 it("exige cláusula completa, clara y dentro del veinte por ciento",()=>{expect(()=>evaluatePlannedModification({...base,planned:true,maximumAggregatePercent:21,causes:[{kind:"OTHER",description:"Cambio",scope:"Unidades",objectiveTrigger:"Hecho medible",limits:["Mismo objeto"]}],procedure:"Acuerdo previo"})).toThrow(/entre 0 y 20/);expect(()=>evaluatePlannedModification({...base,planned:true,maximumAggregatePercent:10,causes:[],procedure:"Acuerdo"})).toThrow(/al menos una causa/);});
 it("bloquea cambio de naturaleza y precios unitarios nuevos",()=>{expect(()=>evaluatePlannedModification({...base,altersGlobalNature:true})).toThrow(/naturaleza global/);expect(()=>evaluatePlannedModification({...base,introducesNewUnitPrices:true})).toThrow(/precios unitarios/);});
 it("reserva DA33 para suministros por necesidades y computa el alza en VE",()=>{const cause={kind:"DA33_NEEDS_UP" as const,description:"Mayores necesidades reales",scope:"Más unidades de referencias existentes",objectiveTrigger:"Consumo validado superior a estimación",limits:["Sin artículos nuevos","Mismos precios unitarios"]};expect(()=>evaluatePlannedModification({...base,planned:true,maximumAggregatePercent:20,causes:[cause],procedure:"Acuerdo antes de agotar presupuesto"})).toThrow(/DA 33/);expect(()=>evaluatePlannedModification({...base,needsBasedContractDa33:true,planned:true,maximumAggregatePercent:20,causes:[cause],procedure:"Acuerdo previo",declaredEstimatedValueExVatCents:1_100_000})).toThrow(/valor estimado/);const r=evaluatePlannedModification({...base,needsBasedContractDa33:true,planned:true,maximumAggregatePercent:20,causes:[cause],procedure:"Acuerdo previo",declaredEstimatedValueExVatCents:1_200_000});expect(r.modificationAmountExVatCents).toBe(200_000);expect(r.structuredRegime.needsDa33.applicable).toBe(true);});
});
