import { describe, expect, it } from "vitest";
import { UniversalAdaptiveQuestionEngine } from "../src/application/intake/lb14/UniversalAdaptiveQuestionEngine";
import { CanonicalExpedienteState } from "../src/domain/expediente/CanonicalExpedienteState";
import { EstadoExpediente } from "../src/domain/expediente/EstadoExpediente";
import { createPendingEvidenceField, EvidenceField } from "../src/domain/expediente/EvidenceField";
import { createUniversalExpedienteFromCanonical } from "../src/domain/expediente/UniversalExpedienteV13";

function validated<T>(key:string,value:T):EvidenceField<T>{return{key,value,status:"HUMAN_VALIDATED",sources:[{kind:"USER_INPUT",sourceId:"lb14-test"}],humanValidationRequired:true,humanValidated:true};}
function baseState(type:"SERVICE"|"SUPPLY"="SERVICE"):CanonicalExpedienteState{return{id:"LB14-001",lifecycleState:EstadoExpediente.OBJETO_VALIDADO,blockers:[],warnings:[],fields:{contractType:validated("contractType",type),object:validated("object",type==="SUPPLY"?"Suministro sucesivo de material de ferretería":"Servicio de mantenimiento de instalaciones"),cpvMain:validated("cpvMain",type==="SUPPLY"?"44316400-2":"50000000-5"),lots:validated("lots",["Lote único"]),estimatedValueCents:validated("estimatedValueCents",12000000),baseTenderBudgetCents:validated("baseTenderBudgetCents",6000000),procedure:createPendingEvidenceField("procedure"),durationMonths:validated("durationMonths",12),extensionMonths:validated("extensionMonths",12),modificationPercent:validated("modificationPercent",0),awardCriteria:validated("awardCriteria",[]),solvency:validated("solvency",[]),publicity:validated("publicity","PENDING_PROCEDURE")}};}

const engine=new UniversalAdaptiveQuestionEngine();

describe("Bloque 14.1 - preguntas adaptativas gobernadas por expediente universal",()=>{
  it("empieza preguntando la necesidad en lenguaje natural, no el tipo jurídico",()=>{const state=baseState();state.fields.object=createPendingEvidenceField("object");state.fields.contractType=createPendingEvidenceField("contractType");state.fields.cpvMain=createPendingEvidenceField("cpvMain");const action=engine.next(createUniversalExpedienteFromCanonical(state));expect(action.kind).toBe("ASK_USER");expect(action.id).toBe("ask:contract-need");expect(action.question?.toLocaleLowerCase("es-ES")).toContain("qué necesita contratar");});
  it("propone clasificar la naturaleza antes de preguntar al usuario por la calificación jurídica",()=>{const state=baseState();state.fields.contractType=createPendingEvidenceField("contractType");state.fields.cpvMain=createPendingEvidenceField("cpvMain");const action=engine.next(createUniversalExpedienteFromCanonical(state));expect(action.kind).toBe("RUN_ENGINE");expect(action.engine).toBe("CONTRACT_NATURE_CLASSIFIER");expect(action.fieldKey).toBe("contractType");});
  it("ejecuta CPVEngine en lugar de pedir un código CPV al usuario",()=>{const state=baseState();state.fields.cpvMain=createPendingEvidenceField("cpvMain");const action=engine.next(createUniversalExpedienteFromCanonical(state));expect(action.kind).toBe("RUN_ENGINE");expect(action.engine).toBe("CPVEngine");});
  it("si ya hay propuesta CPV pendiente de validación, pide validarla y no vuelve a preguntar",()=>{const state=baseState();state.fields.cpvMain={key:"cpvMain",value:"50000000-5",status:"SYSTEM_PROPOSAL",sources:[{kind:"SYSTEM_PROPOSAL",sourceId:"CPVEngine"}],humanValidationRequired:true,humanValidated:false};const action=engine.next(createUniversalExpedienteFromCanonical(state));expect(action.kind).toBe("VALIDATE_HUMAN");expect(action.fieldKey).toBe("cpvMain");});
  it("prioriza una contradicción de fuente sobre cualquier nueva pregunta",()=>{const universal=createUniversalExpedienteFromCanonical(baseState());universal.guarantees.definitiveGuaranteePercent={key:"guarantees.definitiveGuaranteePercent",value:null,status:"SOURCE_CONFLICT",sources:[{kind:"PRIMARY_DOCUMENT",sourceId:"PCAP-A"},{kind:"PRIMARY_DOCUMENT",sourceId:"PCAP-B"}],humanValidationRequired:true,humanValidated:false,conflict:{statements:["5 %","No exigida"],treatment:"DO_NOT_AUTO_RESOLVE"}};const action=engine.next(universal);expect(action.kind).toBe("RESOLVE_SOURCE_CONFLICT");expect(action.fieldKey).toBe("guarantees.definitiveGuaranteePercent");});
  it("en suministros pregunta por presupuesto máximo sin confundirlo con PBL, consumo o VE",()=>{const universal=createUniversalExpedienteFromCanonical(baseState("SUPPLY"));const action=engine.next(universal);expect(action.kind).toBe("ASK_USER");expect(action.id).toBe("ask:supply-maximum-budget");expect(action.fieldKey).toBe("economic.maximumApprovedBudgetCents");expect(action.help).toContain("No se confundirá con el consumo estimado ni con el valor estimado jurídico");});
  it("con tipo y VE disponibles pide primero los criterios necesarios para decidir el procedimiento",()=>{const universal=createUniversalExpedienteFromCanonical(baseState("SERVICE"));const action=engine.next(universal);expect(action.kind).toBe("ASK_USER");expect(action.id).toBe("ask:award-criteria-for-procedure");expect(action.fieldKey).toBe("criteria.awardCriteria");});
  it("después de criterios pide el umbral aplicable para servicios antes de ejecutar ProcedimientoEngine",()=>{const universal=createUniversalExpedienteFromCanonical(baseState("SERVICE"));universal.criteria.awardCriteria=validated("criteria.awardCriteria",[]);const action=engine.next(universal);expect(action.kind).toBe("ASK_USER");expect(action.id).toBe("ask:threshold-for-procedure");expect(action.fieldKey).toBe("regulation.threshold");});
  it("ejecuta ProcedimientoEngine cuando tipo, VE, criterios y umbral ya son promocionables",()=>{const universal=createUniversalExpedienteFromCanonical(baseState("SERVICE"));universal.criteria.awardCriteria=validated("criteria.awardCriteria",[]);universal.regulation.threshold=validated("regulation.threshold",216000);const action=engine.next(universal);expect(action.kind).toBe("RUN_ENGINE");expect(action.engine).toBe("ProcedimientoEngine");expect(action.fieldKey).toBe("procedure");});
});
