import { describe, expect, it } from "vitest";
import type { UniversalEditableTemplateBinaryStore } from "../src/application/intake/lb23/UniversalOdtProductionRenderer";
import type { UniversalEvidenceRecord } from "../src/application/intake/lb52/UniversalEvidenceWorkspace";
import { generateWorksUserDocumentPackage } from "../src/application/intake/lb97/WorksUserDocumentPackageGenerator";
import { WORKS_GENERAL_TEMPLATE_MANIFEST } from "../src/application/intake/lb97/WorksGeneralTemplateManifest";

const BINARIES: Record<string,string> = {
  "contrata-ia:works:memory:general:LB97-WORKS-GENERAL-ODT-V1": "UEsDBBQAAAAAAAAAIQBexjIMJwAAACcAAAAIAAAAbWltZXR5cGVhcHBsaWNhdGlvbi92bmQub2FzaXMub3BlbmRvY3VtZW50LnRleHRQSwMEFAAAAAgAAAAhAObJe26FAQAAzQYAAAsAAABjb250ZW50LnhtbJ2V0W6CMBSG7/cUDfeMebcQwHROE5Y4FsXd13JcukBLaHEa43Ptfk82bDcHRk3ZDYWe/zv/4dCWYLgpcrSGSjLBQ2dwe+cg4FRkjL+FziKduPfOMLoJxGrFKPiZoHUBXLlUcNWMqKG59E00dOqK+4JIJn1OCpC+or4ogf9Sflvtay8zo2CjbOmDts1Ktc2trbVY03/vRGolCqIYdXVURoFR6Ssy94ecofMycLwo8C5yP4GlyLbHh0O5UaCLLpEetNo9Zoym42kyizF6WszTeBKPcBq/YvT1iUbJczrDaYIexyh5mOF5axK7MQ48k/Z6ekokxJmddrcz6v3eTs8BsnldFKTa2hq0EFsXsXwHqnr6dCBbp7IS/7DqUrZe0GwhUTDa0+wEs3XL6qpZqoL3dDvBevSRQsNC/052OFs/mhMpWbPfTLEiXzdn2Lan+dUktpWQD1Jlo4opqBjpWcA51r7jUBLzrTBVsnffz9HWK3kDtP7H4jrl2n5e5/j0Oierd+FnFH0DUEsDBBQAAAAIAAAAIQAioArPkAAAABgBAAAKAAAAc3R5bGVzLnhtbI2PQQoCMQxFr1KyH6s7CW1n5wXUA5Q2I4WZVCYd0durLYqICzch5Of9/Jj+Oo3qQrOkzBY2qzUo4pBj4pOF42HXbaF3Jg9DCoQxh2UiLp2U20iiHiwLNtHCMjNmL0mQ/USCJWA+E78g/NzGeqlNqtm/eF2u9DtVC+NMk2pVrX8aWdgXz9HPEbQz+ovRvz9zd1BLAwQUAAAACAAAACEAr9I4lGUAAACBAAAADAAAAHNldHRpbmdzLnhtbE2NSQqAMAwAv1Jyd7tJsHrzBfoAqVEKNhFTxeeriOB5ZpiqOcNiDtrUC1so0hwMsZPR82yh79qkhKauZJq8IxzF7YE4Jkox3oaau2bFF1vYN0YZ1CvyEEgxOpSV+Mvwb+PzyuoLUEsDBBQAAAAIAAAAIQCFMOk2sQAAAKcBAAAVAAAATUVUQS1JTkYvbWFuaWZlc3QueG1slVDNDoIwDH4V0jtMb2ZhcPMJ9AGWUXTJ1i2sEHh7wUTBGBO8tV+/v7SsR++yAbtkAyk4FgfIkExoLN0UXC/n/AR1VXpNtsXE8jVks4zSe1XQdySDTjZJ0h6TZCNDRGqC6T0Sy0++XII2tq11mM+0bspWrHcuj5rvCgSssMfG6pyniAp0jM4azXN3MVBTPAsU29yCcWQQ+6NMIF50c98foYujWM5/uCaeHKadpuLr29UDUEsBAhQDFAAAAAAAAAAhAF7GMgwnAAAAJwAAAAgAAAAAAAAAAAAAAIABAAAAAG1pbWV0eXBlUEsBAhQDFAAAAAgAAAAhAObJe26FAQAAzQYAAAsAAAAAAAAAAAAAAIABTQAAAGNvbnRlbnQueG1sUEsBAhQDFAAAAAgAAAAhACKgCs+QAAAAGAEAAAoAAAAAAAAAAAAAAIAB+wEAAHN0eWxlcy54bWxQSwECFAMUAAAACAAAACEAr9I4lGUAAACBAAAADAAAAAAAAAAAAAAAgAGzAgAAc2V0dGluZ3MueG1sUEsBAhQDFAAAAAgAAAAhAIUw6TaxAAAApwEAABUAAAAAAAAAAAAAAIABQgMAAE1FVEEtSU5GL21hbmlmZXN0LnhtbFBLBQYAAAAABQAFACQBAAAmBAAAAAA=",
  "contrata-ia:works:pcap:general:LB97-WORKS-GENERAL-ODT-V1": "UEsDBBQAAAAAAAAAIQBexjIMJwAAACcAAAAIAAAAbWltZXR5cGVhcHBsaWNhdGlvbi92bmQub2FzaXMub3BlbmRvY3VtZW50LnRleHRQSwMEFAAAAAgAAAAhAIrPuZxbAgAAZA0AAAsAAABjb250ZW50LnhtbJ2XwXLaMBCG730Kje/Uza3jMc6omHboEPAAyaE3IW8YdWzLI8kUJpPn6r1PVskuBBxIV7kgCe23v2RrV+v4dlcWZAtKC1kNg5uPnwICFZe5qDbD4H71dfA5uE0+xPLxUXCIcsmbEioz4LIytiWWrnTUzQ6DRlWRZFroqGIl6MjwSNZQHajo1Dpqtbp/DOwMlna2p6w2+wIt3Rq39MueWGNkyYzgg3ZWJ3Fn1f6Sru98DoPsJgiTOLzK/ZtYy3x/HLjlJnG76Jq0TWs9OHpMshHNyPzLgi7Jn99kNJ+tFnRFBxPqhtmUzlaT6ZSSdLyYPNCUEjv9w7WU3M3T8XS+JIvxaH43nqU0tYPvKY3DTu9tXc40THKc7dNTZ/38jLM3whSAdd0aYz3XSv4EbpZNWTK1x0qcU55atLadLSvep9mjsdq6qUFthQtLT93XJFZTQV0wG9fSU7HPYfXk+h2v8gzCKvF66ynzQmA1Cmm0p8gJglUBm3llKbinUg/Dqq2bfAO+b+gMQu9LG2GzKeQPrGjAd3eXYKxy3iibxb3DrIehT2LBtBb2auhgWWztdbv3PZxvOfHIbhzsLnwfdp/D6m0aplyWAN8oeQViFdkvpvKREgaUYJ6il1j0Wd4Bb9ybSYWyucr/bF11gL49auCCFeODn5GscuE6vs/+v47w99na1YyK2e1UG+8r7QKMPudQscII72PX59ARDsocYzNje1d++sb3dRfYVZS2hD8mCD/1Cyi+guBQO+7bIWa9S4krDtDZnBmWKWneFXcX4VPl8KyqD88K/vDKN1LyF1BLAwQUAAAACAAAACEAIqAKz5AAAAAYAQAACgAAAHN0eWxlcy54bWyNj0EKAjEMRa9Ssh+rOwltZ+cF1AOUNiOFmVQmHdHbqy2KiAs3IeTn/fyY/jqN6kKzpMwWNqs1KOKQY+KTheNh122hdyYPQwqEMYdlIi6dlNtIoh4sCzbRwjIzZi9JkP1EgiVgPhO/IPzcxnqpTarZv3hdrvQ7VQvjTJNqVa1/GlnYF8/RzxG0M/qL0b8/c3dQSwMEFAAAAAgAAAAhAK/SOJRlAAAAgQAAAAwAAABzZXR0aW5ncy54bWxNjUkKgDAMAL9Scne7SbB68wX6AKlRCjYRU8Xnq4jgeWaYqjnDYg7a1AtbKNIcDLGT0fNsoe/apISmrmSavCMcxe2BOCZKMd6GmrtmxRdb2DdGGdQr8hBIMTqUlfjL8G/j88rqC1BLAwQUAAAACAAAACEAhTDpNrEAAACnAQAAFQAAAE1FVEEtSU5GL21hbmlmZXN0LnhtbJVQzQ6CMAx+FdI7TG9mYXDzCfQBllF0ydYtrBB4e8FEwRgTvLVfv7+0rEfvsgG7ZAMpOBYHyJBMaCzdFFwv5/wEdVV6TbbFxPI1ZLOM0ntV0Hckg042SdIek2QjQ0Rqguk9EstPvlyCNratdZjPtG7KVqx3Lo+a7woErLDHxuqcp4gKdIzOGs1zdzFQUzwLFNvcgnFkEPujTCBedHPfH6GLo1jOf7gmnhymnabi69vVA1BLAQIUAxQAAAAAAAAAIQBexjIMJwAAACcAAAAIAAAAAAAAAAAAAACAAQAAAABtaW1ldHlwZVBLAQIUAxQAAAAIAAAAIQCKz7mcWwIAAGQNAAALAAAAAAAAAAAAAACAAU0AAABjb250ZW50LnhtbFBLAQIUAxQAAAAIAAAAIQAioArPkAAAABgBAAAKAAAAAAAAAAAAAACAAdECAABzdHlsZXMueG1sUEsBAhQDFAAAAAgAAAAhAK/SOJRlAAAAgQAAAAwAAAAAAAAAAAAAAIABiQMAAHNldHRpbmdzLnhtbFBLAQIUAxQAAAAIAAAAIQCFMOk2sQAAAKcBAAAVAAAAAAAAAAAAAACAARgEAABNRVRBLUlORi9tYW5pZmVzdC54bWxQSwUGAAAAAAUABQAkAQAA/AQAAAAA",
  "contrata-ia:works:ppt:general:LB97-WORKS-GENERAL-ODT-V1": "UEsDBBQAAAAAAAAAIQBexjIMJwAAACcAAAAIAAAAbWltZXR5cGVhcHBsaWNhdGlvbi92bmQub2FzaXMub3BlbmRvY3VtZW50LnRleHRQSwMEFAAAAAgAAAAhAAuxD5qeAQAAWgYAAAsAAABjb250ZW50LnhtbJ1VTY6bMBTe9xQWe4bOrkKEiJJUYtGQgfQAjnlpXIGdsR+joCgH6Im6n7lYjelME2lITTfY+H1/gP2I5semJk+gNJdi5t3fffQICCYrLr7PvG+bL/4nbx5/iORuxxmElWRtAwJ9JgWakRi20OFQnXmtEqGkmutQ0AZ0iCyUBxCvrPASHVqvYQXhiK7sHnvJ1djVztYWbNl/n4m2KBuKnPm2quNoQNkrGea95sxb33tBHAWjvD+Fray6t5s+bhzZ0AdiB4v23xTjdbEs0yJbp1m+WpZk8/IzXWVpUpKAfE2KNH9dycliSfLPRUKef5E0X22KZJP4WRIFg/ptF0Y1ZJUb9nQa0OezG15ufwDDsm0aqjpXiyuSq9NBScti5ttO9HuH6uqKwPaCM1oX8NhyBf2G0hPtb2m45oAjsBbNQV0YAdZPJoYYFXBNYPY7KE5rnYjqoaU1x25ihHEF1wx7oDXuS7oD7FIplWlV9D/exT9kXNNojpBKUfGeO3VTvEt2dWagkJseY1MbFVSynuh/Q+IyRXDVy4KrNheM/Bni31BLAwQUAAAACAAAACEAIqAKz5AAAAAYAQAACgAAAHN0eWxlcy54bWyNj0EKAjEMRa9Ssh+rOwltZ+cF1AOUNiOFmVQmHdHbqy2KiAs3IeTn/fyY/jqN6kKzpMwWNqs1KOKQY+KTheNh122hdyYPQwqEMYdlIi6dlNtIoh4sCzbRwjIzZi9JkP1EgiVgPhO/IPzcxnqpTarZv3hdrvQ7VQvjTJNqVa1/GlnYF8/RzxG0M/qL0b8/c3dQSwMEFAAAAAgAAAAhAK/SOJRlAAAAgQAAAAwAAABzZXR0aW5ncy54bWxNjUkKgDAMAL9Scne7SbB68wX6AKlRCjYRU8Xnq4jgeWaYqjnDYg7a1AtbKNIcDLGT0fNsoe/apISmrmSavCMcxe2BOCZKMd6GmrtmxRdb2DdGGdQr8hBIMTqUlfjL8G/j88rqC1BLAwQUAAAACAAAACEAhTDpNrEAAACnAQAAFQAAAE1FVEEtSU5GL21hbmlmZXN0LnhtbJVQzQ6CMAx+FdI7TG9mYXDzCfQBllF0ydYtrBB4e8FEwRgTvLVfv7+0rEfvsgG7ZAMpOBYHyJBMaCzdFFwv5/wEdVV6TbbFxPI1ZLOM0ntV0Hckg042SdIek2QjQ0Rqguk9EstPvlyCNratdZjPtG7KVqx3Lo+a7woErLDHxuqcp4gKdIzOGs1zdzFQUzwLFNvcgnFkEPujTCBedHPfH6GLo1jOf7gmnhymnabi69vVA1BLAQIUAxQAAAAAAAAAIQBexjIMJwAAACcAAAAIAAAAAAAAAAAAAACAAQAAAABtaW1ldHlwZVBLAQIUAxQAAAAIAAAAIQALsQ+angEAAFoGAAALAAAAAAAAAAAAAACAAU0AAABjb250ZW50LnhtbFBLAQIUAxQAAAAIAAAAIQAioArPkAAAABgBAAAKAAAAAAAAAAAAAACAARQCAABzdHlsZXMueG1sUEsBAhQDFAAAAAgAAAAhAK/SOJRlAAAAgQAAAAwAAAAAAAAAAAAAAIABzAIAAHNldHRpbmdzLnhtbFBLAQIUAxQAAAAIAAAAIQCFMOk2sQAAAKcBAAAVAAAAAAAAAAAAAACAAVsDAABNRVRBLUlORi9tYW5pZmVzdC54bWxQSwUGAAAAAAUABQAkAQAAPwQAAAAA"
};

const field = (value: unknown) => ({ value, status: "HUMAN_VALIDATED", humanValidated: true, humanValidationRequired: true, sources: [] });

function completeRecord(): UniversalEvidenceRecord {
  const values: Record<string, unknown> = {
    contractType: "WORKS", need: "Rehabilitación necesaria para recuperar la funcionalidad del inmueble público.", object: "Rehabilitación integral del edificio administrativo de prueba", cpvMain: "45210000-2",
    "administrative.contractingAuthority": "Órgano de contratación de prueba", "lots.divisionIntoLots": false, "lots.noDivisionJustification": "Unidad funcional y responsabilidad técnica única.",
    baseTenderBudgetCents: 25_000_000, "economic.initialVatAmountCents": 5_250_000, "economic.initialPblVatIncludedCents": 30_250_000, "economic.legalEstimatedValueCents": 25_000_000,
    "economic.estimatedValueCalculationMethod": "Importe total estimado de la obra sin IVA.", "economic.annualityBudgetRows": ["2027: 250.000,00 €"], durationMonths: 10, extensionMonths: 0,
    procedure: "ABIERTO_SIMPLIFICADO_ORDINARIO", "criteria.awardCriteria": ["Precio 60 puntos", "Calidad técnica 40 puntos"], "criteria.economicSolvency": "Volumen anual de negocios conforme al PCAP.", "criteria.technicalSolvency": "Relación de obras ejecutadas conforme al PCAP.",
    "technical.technicalRequirements": "Ejecución conforme al proyecto aprobado, normativa técnica y prescripciones del PPT.", "technical.executionLocations": ["Sevilla"],
    "execution.specialExecutionConditions": ["Gestión selectiva de residuos de construcción"], "execution.subcontractingRegime": "Subcontratación conforme a los límites y obligaciones de la LCSP.", "execution.specificPenalties": "Penalidades por demora e incumplimiento conforme al PCAP.", "execution.paymentRegime": "Pago mediante certificaciones mensuales aprobadas.", "execution.plannedModificationRegime": "No se prevén modificaciones contractuales.",
    "guarantees.provisionalGuaranteeRequired": false, "guarantees.definitiveGuaranteePercent": 5, "guarantees.complementaryGuaranteePercent": 0,
    "works.projectExists": true, "works.projectApproval": true, "works.affectsStabilitySafetyOrWatertightness": false, "works.supervisionReportAvailable": false, "works.replanteoCompleted": true, "works.terrainAvailabilityAccredited": true, "works.projectAndWorksJointAward": false,
    "works.projectScope": "Rehabilitación de envolvente, instalaciones y acabados conforme al proyecto aprobado.", "works.projectMemoryAvailable": true, "works.projectPlansAvailable": true, "works.projectTechnicalSpecificationsAvailable": true, "works.projectBudgetMeasurementsAvailable": true, "works.projectProgrammeAvailable": true, "works.projectReplanteoReferencesAvailable": true, "works.projectHealthSafetyStudyAvailable": true, "works.projectSimplificationApplied": false,
    "works.executionDirection": "Dirección facultativa designada; instrucciones documentadas en libro de órdenes.", "works.materialsAndQualityControl": "Control documental, ensayos y recepción de materiales según proyecto.", "works.healthAndSafetyCoordination": "Coordinación de seguridad y salud durante toda la ejecución.", "works.certificationRegime": "Medición contradictoria y certificación mensual de obra ejecutada.", "works.receptionAndGuaranteeRegime": "Recepción formal, certificación final, plazo de garantía y liquidación conforme a LCSP.", "works.contractorClassificationSummary": "Clasificación o solvencia equivalente que resulte exigible conforme al valor y objeto.", "works.dataProtectionRegime": "Sin acceso ordinario a datos personales; cualquier acceso incidental se someterá a RGPD y LOPDGDD."
  };
  return { caseId: "REG-WORKS-LB97-E2E-001", updatedAt: new Date(0).toISOString(), fields: Object.fromEntries(Object.entries(values).map(([key,value]) => [key, field(value)])) as UniversalEvidenceRecord["fields"] };
}

const store: UniversalEditableTemplateBinaryStore = {
  async get(templateId) {
    const b64 = BINARIES[templateId];
    return b64 ? { templateId, sourceId: templateId, bytes: Buffer.from(b64, "base64") } : null;
  }
};

describe("LB97 E2E positivo del paquete Works", () => {
  it("genera PCAP, Memoria y PPT editables con auditoría cruzada y aceptación humana obligatoria", async () => {
    expect(Object.keys(BINARIES).sort()).toEqual(WORKS_GENERAL_TEMPLATE_MANIFEST.map(x => x.templateId).sort());
    const result = await generateWorksUserDocumentPackage({ record: completeRecord(), templateStore: store });
    expect(result.ready, result.blockers.join(" | ")).toBe(true);
    expect(result.bytes?.byteLength).toBeGreaterThan(0);
    expect(result.sha256).toMatch(/^[a-f0-9]{64}$/);
    expect(result.fileName).toContain("Works_PCAP-Memoria-PPT.zip");
    expect(result.manifest?.documents.map(x => x.kind).sort()).toEqual(["MEMORIA", "PCAP", "PPT"]);
    expect(result.manifest?.crossDocumentAuditReady).toBe(true);
    expect(result.manifest?.projectPreparationAudited).toBe(true);
    expect(result.manifest?.humanAcceptanceRequired).toBe(true);
    expect(result.manifest?.documents.every(x => x.officialModel === false)).toBe(true);
  });
});
