import { describe,expect,it } from "vitest";
import type { UniversalEditableTemplateBinaryStore } from "../src/application/intake/lb23/UniversalOdtProductionRenderer";
import type { UniversalEvidenceRecord } from "../src/application/intake/lb52/UniversalEvidenceWorkspace";
import { MIXED_SUPPLY_SERVICE_TEMPLATE_MANIFEST,type MixedSupplyServiceProfile } from "../src/application/intake/lb99/MixedSupplyServiceTemplateManifest";
import { evaluateMixedSupplyServiceTemplateBytes } from "../src/application/intake/lb99/MixedSupplyServiceTemplatePhysicalGate";
import { generateMixedSupplyServiceDocumentPackage } from "../src/application/intake/lb99/MixedSupplyServiceUserDocumentPackageGenerator";
import { LB99_MIXED_SUPPLY_SERVICE_BINARIES } from "./fixtures/lb99-mixed-supply-service-binaries";
function field(key:string,value:unknown){return{key,value,status:"HUMAN_VALIDATED" as const,sources:[{kind:"USER_INPUT" as const,sourceId:"lb99-e2e"}],humanValidationRequired:true,humanValidated:true};}
function record(profile:MixedSupplyServiceProfile):UniversalEvidenceRecord{const supply=profile==="SUPPLY_PRINCIPAL"?8_000_000:2_000_000,service=profile==="SERVICE_PRINCIPAL"?8_000_000:2_000_000;const values:Record<string,unknown>={contractType:"MIXED",need:"Necesidad conjunta de equipamiento y servicio asociado",object:"Suministro de equipamiento con servicio de implantación y soporte",cpvMain:"30200000-1",procedure:"ABIERTO","lots.divisionIntoLots":false,"criteria.economicSolvency":["Volumen anual"],"criteria.technicalSolvency":["Experiencia"],"criteria.awardCriteria":["Precio","Calidad técnica"],"execution.plannedModificationRegime":"Solo modificaciones previstas y legalmente procedentes","mixed.components":[{id:"supply",contractType:"SUPPLY",estimatedValueExVatCents:supply,functionallyLinked:true,complementaryRelationship:true},{id:"service",contractType:"SERVICE",estimatedValueExVatCents:service,functionallyLinked:true,complementaryRelationship:true}],"mixed.principalContractType":profile==="SUPPLY_PRINCIPAL"?"SUPPLY":"SERVICE","mixed.effectsRegimeSeparatedByComponent":true,"mixed.supplyRequirements":"Equipos, licencias y accesorios definidos técnicamente","mixed.serviceRequirements":"Implantación, configuración, formación y soporte","mixed.integrationRequirements":"Integración funcional obligatoria entre suministro y servicio","mixed.acceptanceControl":"Recepción del suministro y conformidad diferenciada del servicio","mixed.executionLocations":"Centros administrativos designados","mixed.dataProtectionRegime":"RGPD y LOPDGDD según los tratamientos asociados"};return{caseId:`REG-MIXED-${profile}`,updatedAt:new Date(0).toISOString(),fields:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,field(k,v)]))};}
class Store implements UniversalEditableTemplateBinaryStore{public constructor(private readonly profile:MixedSupplyServiceProfile){}async get(templateId:string){const m=MIXED_SUPPLY_SERVICE_TEMPLATE_MANIFEST.find(x=>x.profile===this.profile&&x.templateId===templateId);if(!m)return null;const b64=LB99_MIXED_SUPPLY_SERVICE_BINARIES[`${m.profile}:${m.kind}` as keyof typeof LB99_MIXED_SUPPLY_SERVICE_BINARIES];return{templateId,sourceId:templateId,bytes:Buffer.from(b64,"base64")};}}
describe("LB99 paquete físico Mixed Supply-Service",()=>{
  it("verifica SHA, estilo y slots exactos de los seis activos",()=>{for(const m of MIXED_SUPPLY_SERVICE_TEMPLATE_MANIFEST){const b64=LB99_MIXED_SUPPLY_SERVICE_BINARIES[`${m.profile}:${m.kind}` as keyof typeof LB99_MIXED_SUPPLY_SERVICE_BINARIES];const gate=evaluateMixedSupplyServiceTemplateBytes(m,Buffer.from(b64,"base64"));expect(gate.ready).toBe(true);expect(gate.actualSha256).toBe(m.expectedSha256);expect(gate.actualStyleFingerprint).toBe(m.expectedStyleFingerprint);expect(gate.officialModel).toBe(false);}});
  it.each(["SUPPLY_PRINCIPAL","SERVICE_PRINCIPAL"] as const)("genera tres ODT y manifest para %s sin plantilla Mixed genérica",async profile=>{const pkg=await generateMixedSupplyServiceDocumentPackage({record:record(profile),templateStore:new Store(profile)});expect(pkg.ready).toBe(true);expect(pkg.bytes?.byteLength).toBeGreaterThan(1000);expect(pkg.manifest?.documents.map(x=>x.kind).sort()).toEqual(["MEMORIA","PCAP","PPT"]);expect(pkg.manifest?.genericMixedTemplate).toBe(false);expect(pkg.manifest?.administrativeBaseFamily).toBe(profile==="SUPPLY_PRINCIPAL"?"SUPPLY":"SERVICE");expect(pkg.manifest?.componentValuesAudited).toBe(true);expect(pkg.manifest?.technicalOverlaysAudited).toBe(true);expect(pkg.manifest?.effectsRegimeByComponentAudited).toBe(true);expect(pkg.manifest?.humanAcceptanceRequired).toBe(true);});
  it("rechaza una combinación que incluya Works en este generador especializado",async()=>{const r=record("SUPPLY_PRINCIPAL");const fields={...r.fields,"mixed.components":field("mixed.components",[{id:"supply",contractType:"SUPPLY",estimatedValueExVatCents:8_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"works",contractType:"WORKS",estimatedValueExVatCents:2_000_000,functionallyLinked:true,complementaryRelationship:true}])};const pkg=await generateMixedSupplyServiceDocumentPackage({record:{...r,fields},templateStore:new Store("SUPPLY_PRINCIPAL")});expect(pkg.ready).toBe(false);expect(pkg.blockers.join(" ")).toContain("solo acepta prestaciones SUPPLY y SERVICE");});
  it("detecta mutación de un binario y no lo promociona",()=>{const m=MIXED_SUPPLY_SERVICE_TEMPLATE_MANIFEST[0]!;const b64=LB99_MIXED_SUPPLY_SERVICE_BINARIES[`${m.profile}:${m.kind}` as keyof typeof LB99_MIXED_SUPPLY_SERVICE_BINARIES];const bytes=Buffer.from(b64,"base64");bytes[bytes.length-1]^=1;expect(evaluateMixedSupplyServiceTemplateBytes(m,bytes).ready).toBe(false);});
});
