import { describe,expect,it } from "vitest";
import { evaluateMixedQualification,type MixedQualificationInput } from "../src/application/intake/lb99/MixedQualificationGate";

function base(overrides:Partial<MixedQualificationInput>={}):MixedQualificationInput{return{components:[{id:"supply",contractType:"SUPPLY",estimatedValueExVatCents:9_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"service",contractType:"SERVICE",estimatedValueExVatCents:1_000_000,functionallyLinked:true,complementaryRelationship:true}],declaredPrincipalContractType:null,objectivelySeparable:null,singleContractChosen:null,nonConcessionThresholdExceeded:null,effectsRegimeSeparatedByComponent:true,worksElementValueCents:null,worksProjectAvailable:false,concessionViabilityStudyAvailable:false,concessionAnteprojectResolved:null,...overrides};}

describe("LB99 calificación y régimen del contrato mixto",()=>{
  it("determina suministro como principal cuando su VE es superior al servicio",()=>{const r=evaluateMixedQualification(base());expect(r.ready).toBe(true);expect(r.principalContractType).toBe("SUPPLY");expect(r.governingAwardRegime).toBe("SUPPLY");});
  it("determina servicio como principal cuando su VE es superior al suministro",()=>{const r=evaluateMixedQualification(base({components:[{id:"supply",contractType:"SUPPLY",estimatedValueExVatCents:1_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"service",contractType:"SERVICE",estimatedValueExVatCents:9_000_000,functionallyLinked:true,complementaryRelationship:true}]}));expect(r.ready).toBe(true);expect(r.principalContractType).toBe("SERVICE");});
  it("no rompe un empate suministro-servicio inventando prestación principal",()=>{const r=evaluateMixedQualification(base({components:[{id:"supply",contractType:"SUPPLY",estimatedValueExVatCents:5_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"service",contractType:"SERVICE",estimatedValueExVatCents:5_000_000,functionallyLinked:true,complementaryRelationship:true}]}));expect(r.ready).toBe(false);expect(r.principalContractType).toBeNull();expect(r.blockers.join(" ")).toContain("iguales");});
  it("rechaza prestaciones que no estén vinculadas y sean complementarias",()=>{const r=evaluateMixedQualification(base({components:[{id:"supply",contractType:"SUPPLY",estimatedValueExVatCents:9_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"service",contractType:"SERVICE",estimatedValueExVatCents:1_000_000,functionallyLinked:false,complementaryRelationship:true}]}));expect(r.ready).toBe(false);expect(r.mixedNatureReady).toBe(false);expect(r.blockers.join(" ")).toContain("art. 34.2");});
  it("no deriva por valor la prestación principal de una combinación obra-servicio",()=>{const r=evaluateMixedQualification(base({components:[{id:"works",contractType:"WORKS",estimatedValueExVatCents:20_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"service",contractType:"SERVICE",estimatedValueExVatCents:1_000_000,functionallyLinked:true,complementaryRelationship:true}],worksElementValueCents:20_000_000,worksProjectAvailable:true}));expect(r.ready).toBe(false);expect(r.blockers.join(" ")).toContain("carácter de la prestación principal");});
  it("exige proyecto cuando el elemento de obra supera 50.000 euros",()=>{const r=evaluateMixedQualification(base({components:[{id:"works",contractType:"WORKS",estimatedValueExVatCents:6_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"service",contractType:"SERVICE",estimatedValueExVatCents:1_000_000,functionallyLinked:true,complementaryRelationship:true}],declaredPrincipalContractType:"WORKS",worksElementValueCents:5_000_001,worksProjectAvailable:false}));expect(r.projectRequired).toBe(true);expect(r.ready).toBe(false);expect(r.blockers.join(" ")).toContain("50.000");});
  it("en mixto con concesión separable y contrato único no inventa el resultado de los umbrales",()=>{const r=evaluateMixedQualification(base({components:[{id:"service",contractType:"SERVICE",estimatedValueExVatCents:3_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"concession",contractType:"CONCESSION",estimatedValueExVatCents:30_000_000,functionallyLinked:true,complementaryRelationship:true}],declaredPrincipalContractType:"CONCESSION",objectivelySeparable:true,singleContractChosen:true,nonConcessionThresholdExceeded:null,concessionViabilityStudyAvailable:true,concessionAnteprojectResolved:false}));expect(r.ready).toBe(false);expect(r.blockers.join(" ")).toContain("umbrales");});
  it("aplica régimen concesional cuando la parte separable no concesional no supera umbral y existe contrato único",()=>{const r=evaluateMixedQualification(base({components:[{id:"service",contractType:"SERVICE",estimatedValueExVatCents:3_000_000,functionallyLinked:true,complementaryRelationship:true},{id:"concession",contractType:"CONCESSION",estimatedValueExVatCents:30_000_000,functionallyLinked:true,complementaryRelationship:true}],declaredPrincipalContractType:"CONCESSION",objectivelySeparable:true,singleContractChosen:true,nonConcessionThresholdExceeded:false,concessionViabilityStudyAvailable:true,concessionAnteprojectResolved:false}));expect(r.ready).toBe(true);expect(r.governingAwardRegime).toBe("CONCESSION");});
  it("obliga a separar en PCAP efectos, cumplimiento y extinción por prestación",()=>{const r=evaluateMixedQualification(base({effectsRegimeSeparatedByComponent:false}));expect(r.ready).toBe(false);expect(r.blockers.join(" ")).toContain("122.2");});
});
