export const LB113_SPECIAL_EXECUTION_VERSION="LB113-SPECIAL-EXECUTION-V1" as const;
const LCSP="https://www.boe.es/buscar/act.php?id=BOE-A-2017-12902";
export type ConditionCategory="ENVIRONMENTAL"|"SOCIAL_EMPLOYMENT"|"ETHICAL"|"DATA_PROTECTION"|"FOOD_WASTE"|"OTHER";
export type BreachConsequence="PENALTY"|"ESSENTIAL_OBLIGATION"|"SERIOUS_INFRINGEMENT";
export interface SpecialConditionInput { title:string; category:ConditionCategory; obligation:string; objectLinkReason:string; verificationMethod:string; evidenceRequired:string; consequence:BreachConsequence; consequenceDetail:string }
export interface SpecialExecutionInput { contractType:"SUPPLY"|"SERVICE"; transfersPublicData:boolean; publicInstitutionFoodService:boolean; conditions:readonly SpecialConditionInput[] }
export interface ExecutionLegalBasis {id:string;article:string;paragraph:string;relevantOfficialExcerpt:string;officialUrl:string}
export interface SpecialExecutionResult {version:typeof LB113_SPECIAL_EXECUTION_VERSION;normalizedConditions:readonly SpecialConditionInput[];documentaryStatements:readonly {element:string;status:"APPLIES"|"NOT_APPLICABLE";text:string;destinations:readonly ("MEMORY"|"PCAP"|"PPT"|"NOTICE")[]}[];warnings:readonly string[];legalBasis:readonly ExecutionLegalBasis[];humanValidationRequired:true;generationBlocked:true;productionReady:false}
const basis=(id:string,article:string,paragraph:string,excerpt:string):ExecutionLegalBasis=>({id,article,paragraph,relevantOfficialExcerpt:excerpt,officialUrl:`${LCSP}#a${article}`});
const LEGAL={general:basis("LCSP-202.1","202","1","Debe establecerse al menos una condición especial vinculada al objeto, no discriminatoria, compatible con el Derecho de la Unión e indicada en anuncio y pliegos."),data:basis("LCSP-202.1-DATA","202","1, párrafo tercero","Si se ceden datos públicos al contratista, es obligatoria una condición de sometimiento a la normativa de protección de datos con carácter de obligación esencial."),food:basis("LCSP-202.1-FOOD","202","1, párrafo cuarto","En servicios de alimentación de instituciones públicas deben incorporarse prácticas adecuadas de prevención de pérdidas y desperdicio alimentario."),types:basis("LCSP-202.2","202","2","Las condiciones pueden ser económicas, de innovación, medioambientales, sociales o relativas al empleo."),effects:basis("LCSP-202.3","202","3","El pliego puede establecer penalidades, atribuir carácter esencial o considerar el incumplimiento infracción grave."),subs:basis("LCSP-202.4","202","4","Todas las condiciones especiales serán exigidas igualmente a los subcontratistas participantes."),penalty:basis("LCSP-192.1","192","1","Las penalidades deben ser proporcionales y cada una no puede superar el 10 % del precio ni el total el 50 %."),essential:basis("LCSP-211.1.f","211","1.f","Una obligación esencial debe enumerarse en el pliego de forma precisa, clara e inequívoca.")};
const clean=(v:string,msg:string)=>{const x=v?.trim();if(!x)throw new Error(msg);return x;};
export function evaluateSpecialExecutionConditions(input:SpecialExecutionInput):SpecialExecutionResult{
 if(!Array.isArray(input.conditions)||input.conditions.length===0)throw new Error("El PCAP debe establecer al menos una condición especial de ejecución.");
 const seen=new Set<string>();
 const normalized=input.conditions.map((c,i)=>{const p=`Condición ${i+1}`;const x={...c,title:clean(c.title,`${p}: falta el título.`),obligation:clean(c.obligation,`${p}: falta una obligación concreta.`),objectLinkReason:clean(c.objectLinkReason,`${p}: falta justificar la vinculación con el objeto.`),verificationMethod:clean(c.verificationMethod,`${p}: falta el método de verificación.`),evidenceRequired:clean(c.evidenceRequired,`${p}: falta identificar la evidencia exigible.`),consequenceDetail:clean(c.consequenceDetail,`${p}: falta concretar la consecuencia del incumplimiento.`)};if(seen.has(x.title.toLowerCase()))throw new Error(`Condición duplicada: ${x.title}.`);seen.add(x.title.toLowerCase());if(!["ENVIRONMENTAL","SOCIAL_EMPLOYMENT","ETHICAL","DATA_PROTECTION","FOOD_WASTE","OTHER"].includes(x.category))throw new Error(`${p}: categoría no admitida.`);if(!["PENALTY","ESSENTIAL_OBLIGATION","SERIOUS_INFRINGEMENT"].includes(x.consequence))throw new Error(`${p}: consecuencia no admitida.`);return x;});
 const data=normalized.find(c=>c.category==="DATA_PROTECTION");if(input.transfersPublicData&&!data)throw new Error("La cesión de datos públicos exige una condición especial de protección de datos.");if(input.transfersPublicData&&data?.consequence!=="ESSENTIAL_OBLIGATION")throw new Error("La condición obligatoria de protección de datos debe calificarse como obligación contractual esencial.");
 if(input.publicInstitutionFoodService&&!normalized.some(c=>c.category==="FOOD_WASTE"))throw new Error("El servicio de alimentación en una institución pública exige una condición sobre prevención del desperdicio alimentario.");
 const rows=normalized.map(c=>`${c.title}. Obligación: ${c.obligation} Vinculación: ${c.objectLinkReason} Verificación: ${c.verificationMethod} Evidencia: ${c.evidenceRequired} Consecuencia: ${c.consequenceDetail}`);
 return {version:LB113_SPECIAL_EXECUTION_VERSION,normalizedConditions:normalized,documentaryStatements:[
  {element:"SPECIAL_EXECUTION_CONDITIONS",status:"APPLIES",text:rows.join(" "),destinations:["MEMORY","PCAP","PPT","NOTICE"]},
  {element:"SUBCONTRACTORS",status:"APPLIES",text:"Todas las condiciones especiales de ejecución serán exigibles igualmente a los subcontratistas que participen en la ejecución.",destinations:["PCAP"]},
  {element:"DATA_TRANSFER_CONDITION",status:data?"APPLIES":"NOT_APPLICABLE",text:data?`La ejecución implica cesión de datos públicos: ${data.obligation} Se califica como obligación contractual esencial.`:"No se incorpora la condición obligatoria específica de cesión de datos porque se ha declarado que la ejecución no implica cesión de datos públicos al contratista.",destinations:["MEMORY","PCAP"]},
  {element:"FOOD_WASTE_CONDITION",status:normalized.some(c=>c.category==="FOOD_WASTE")?"APPLIES":"NOT_APPLICABLE",text:normalized.some(c=>c.category==="FOOD_WASTE")?"Se incorpora la condición obligatoria aplicable de prevención de pérdidas y desperdicio alimentario.":"No procede la condición específica de desperdicio alimentario porque no se ha declarado un servicio de alimentación en una institución pública.",destinations:["MEMORY","PCAP","PPT"]},
 ],warnings:["La condición debe describir una obligación durante la ejecución, no un requisito de solvencia ni un criterio de adjudicación encubierto.","La propuesta no se incorpora hasta su validación humana y debe publicarse también en el anuncio de licitación."],legalBasis:[LEGAL.general,LEGAL.types,LEGAL.effects,LEGAL.subs,LEGAL.penalty,LEGAL.essential,...(input.transfersPublicData?[LEGAL.data]:[]),...(input.publicInstitutionFoodService?[LEGAL.food]:[])],humanValidationRequired:true,generationBlocked:true,productionReady:false};
}
