export const LB119_DATA_PROTECTION_SECURITY_VERSION="LB119-DATA-PROTECTION-SECURITY-V1" as const;
export type DataScenario="NO_ACCESS"|"INCIDENTAL_ACCESS"|"PROCESSOR";
export interface DataProtectionSecurityInput {dataScenario:DataScenario;scenarioJustification:string;processingPurpose:string;personalDataCategories:string;dataSubjectCategories:string;processingOperations:string;specialCategoryOrCriminalData:boolean;processorAgreementIncluded:boolean;confidentialityRegime:string;returnOrDeletionRegime:string;serversOrAssociatedServices:boolean;serverLocationRegime:string;subprocessorsForeseen:boolean;subprocessorRegime:string;internationalTransfers:boolean;internationalTransferRegime:string;systemsSupportPublicService:boolean;ensApplicable:boolean;ensCategory:""|"BASIC"|"MEDIUM"|"HIGH";ensConformityEvidence:string;securityMeasuresRegime:string;incidentAndContinuityRegime:string;securityContactRegime:string}
interface Basis{id:string;norm:string;article:string;relevantOfficialExcerpt:string;officialUrl:string;checkedAt:string}
interface Statement{element:string;status:"APPLIES"|"NOT_APPLICABLE";text:string;destinations:readonly ("MEMORY"|"PPT"|"PCAP")[]}
export interface DataProtectionSecurityResult {version:typeof LB119_DATA_PROTECTION_SECURITY_VERSION;processingScenario:string;personalDataRegime:string;processorAgreementRegime:string;serverLocationAndSubprocessingRegime:string;internationalTransferRegime:string;informationSecurityRegime:string;ensRegime:string;incidentContinuityRegime:string;documentaryStatements:readonly Statement[];legalBasis:readonly Basis[];warnings:readonly string[];humanValidationRequired:true;generationBlocked:true;productionReady:false}
const LCSP="https://www.boe.es/buscar/act.php?id=BOE-A-2017-12902",GDPR="https://eur-lex.europa.eu/legal-content/ES/TXT/?uri=CELEX:32016R0679",LOPDGDD="https://www.boe.es/buscar/act.php?id=BOE-A-2018-16673",ENS="https://www.boe.es/buscar/act.php?id=BOE-A-2022-7191";
const legal=(id:string,norm:string,article:string,text:string,url:string,checkedAt:string):Basis=>({id,norm,article,relevantOfficialExcerpt:text,officialUrl:url,checkedAt});
const LEGAL:readonly Basis[]=[legal("LCSP-122.2-DATA","LCSP","122.2","Los pliegos mencionarán expresamente la obligación de respetar la normativa vigente en materia de protección de datos.",`${LCSP}#a122`,"2026-04-09"),legal("LCSP-122.2-PROCESSOR","LCSP","122.2 a-e","Cuando exista tratamiento por cuenta del responsable, el pliego debe concretar finalidad, normativa, ubicación de servidores y subcontratación de servicios asociados.",`${LCSP}#a122`,"2026-04-09"),legal("LCSP-202.1-DATA","LCSP","202.1","La cesión de datos exige una condición especial de ejecución relativa al cumplimiento de la normativa de protección de datos, con carácter de obligación esencial.",`${LCSP}#a202`,"2026-04-09"),legal("RGPD-28","RGPD","28","El tratamiento por cuenta del responsable requiere garantías suficientes y un contrato que determine objeto, duración, naturaleza, finalidad, datos, interesados, instrucciones y obligaciones.",GDPR,"2026-09-15"),legal("RGPD-32","RGPD","32","Responsable y encargado aplicarán medidas técnicas y organizativas apropiadas al riesgo.",GDPR,"2026-09-15"),legal("LOPDGDD-33","LOPDGDD","33","El acceso a datos necesario para prestar un servicio al responsable se rige por el régimen del encargado del tratamiento.",`${LOPDGDD}#a33`,"2026-09-15"),legal("ENS-2.3","Real Decreto 311/2022 (ENS)","2.3","Los pliegos incluirán requisitos para asegurar la conformidad ENS de los sistemas que sustenten servicios prestados por contratistas.",`${ENS}#a2`,"2026-09-15"),legal("ENS-3.2","Real Decreto 311/2022 (ENS)","3.2","Los sistemas con datos personales aplicarán además RGPD y LOPDGDD, con análisis de riesgos y, cuando proceda, evaluación de impacto.",`${ENS}#a3`,"2026-09-15")];
const clean=(v:string,label:string)=>{const x=String(v||"").trim();if(!x||/pendiente|por determinar|no lo s[eé]/i.test(x))throw new Error(`Falta concretar ${label}.`);return x;};
export function evaluateDataProtectionSecurity(i:DataProtectionSecurityInput):DataProtectionSecurityResult{
 const reason=clean(i.scenarioJustification,"la justificación del escenario de datos"),confidentiality=clean(i.confidentialityRegime,"el régimen de confidencialidad"),security=clean(i.securityMeasuresRegime,"las medidas de seguridad proporcionales"),incident=clean(i.incidentAndContinuityRegime,"la gestión de incidentes y continuidad"),contact=clean(i.securityContactRegime,"la interlocución de seguridad");
 if(i.dataScenario!=="PROCESSOR"&&(i.processorAgreementIncluded||i.processingPurpose.trim()||i.personalDataCategories.trim()||i.dataSubjectCategories.trim()||i.processingOperations.trim()))throw new Error("El encargo de tratamiento y sus elementos solo proceden cuando existe tratamiento por cuenta de la Administración.");
 let personal:string,agreement:string;
 if(i.dataScenario==="NO_ACCESS"){personal=`No se prevé acceso ni tratamiento de datos personales. Motivación: ${reason}. Se mantiene la obligación general de cumplimiento y ${confidentiality}.`;agreement="No procede contrato de encargo porque no existe tratamiento por cuenta de la Administración.";}
 else if(i.dataScenario==="INCIDENTAL_ACCESS"){personal=`Puede producirse acceso meramente incidental, no necesario para tratar datos. Motivación: ${reason}. Se prohíbe usarlos y se aplicará ${confidentiality}.`;agreement="No procede encargo mientras el acceso sea exclusivamente incidental; cualquier cambio obliga a revisar este bloque.";}
 else {if(!i.processorAgreementIncluded)throw new Error("El tratamiento por cuenta de la Administración exige incorporar un anexo de encargo conforme al artículo 28 RGPD.");const purpose=clean(i.processingPurpose,"la finalidad"),data=clean(i.personalDataCategories,"las categorías de datos"),subjects=clean(i.dataSubjectCategories,"las categorías de interesados"),operations=clean(i.processingOperations,"las operaciones"),end=clean(i.returnOrDeletionRegime,"la devolución o supresión");personal=`Tratamiento por cuenta de la Administración para ${purpose}. Datos: ${data}. Interesados: ${subjects}. Operaciones: ${operations}. ${i.specialCategoryOrCriminalData?"Se declaran categorías especiales o datos penales; deberán reforzarse las medidas según el riesgo.":"No se declaran categorías especiales ni datos penales."}`;agreement=`Se incorporará el anexo del artículo 28 RGPD: instrucciones, confidencialidad, seguridad, asistencia, auditoría, subencargados y ${end}.`;}
 let servers:string;if(i.serversOrAssociatedServices){servers=clean(i.serverLocationRegime,"la ubicación y actualización de servidores");servers+=i.subprocessorsForeseen?` Subencargados previstos: ${clean(i.subprocessorRegime,"su identidad o perfil y autorización")}.`:" No se prevén subencargados; incorporarlos exigirá autorización y actualización.";}else {if(i.subprocessorsForeseen)throw new Error("No puede declararse subcontratación de servidores o servicios asociados sin declarar su existencia.");servers="No existen servidores ni servicios asociados sujetos a declaración de ubicación; cualquier cambio reabrirá la decisión.";}
 const transfers=i.internationalTransfers?`Transferencias internacionales previstas bajo: ${clean(i.internationalTransferRegime,"su base y garantías")}.`:"No se prevén transferencias internacionales; cualquier cambio requerirá nueva valoración.";
 if(i.systemsSupportPublicService&&!i.ensApplicable)throw new Error("Si sistemas del contratista sustentan el servicio público no puede descartarse el ENS sin análisis documentado.");
 const ens=i.ensApplicable?`ENS aplicable. Categoría declarada por el órgano competente: ${clean(i.ensCategory,"la categoría ENS")}. Evidencia: ${clean(i.ensConformityEvidence,"la conformidad ENS")}. La categoría no ha sido inferida por el asistente.`:`No se activa conformidad ENS porque no se declaran sistemas del contratista que sustenten el servicio público. Motivación: ${reason}.`;
 const info=`Medidas técnicas y organizativas adecuadas al riesgo: ${security}. Interlocución: ${contact}.`;
 const documentaryStatements:Statement[]=[{element:"PROCESSING_SCENARIO",status:"APPLIES",text:personal,destinations:["MEMORY","PPT","PCAP"]},{element:"PROCESSOR_AGREEMENT",status:i.dataScenario==="PROCESSOR"?"APPLIES":"NOT_APPLICABLE",text:agreement,destinations:["MEMORY","PCAP"]},{element:"SERVERS_AND_SUBPROCESSORS",status:i.serversOrAssociatedServices?"APPLIES":"NOT_APPLICABLE",text:servers,destinations:["PPT","PCAP"]},{element:"INTERNATIONAL_TRANSFERS",status:i.internationalTransfers?"APPLIES":"NOT_APPLICABLE",text:transfers,destinations:["MEMORY","PPT","PCAP"]},{element:"INFORMATION_SECURITY",status:"APPLIES",text:info,destinations:["MEMORY","PPT"]},{element:"ENS",status:i.ensApplicable?"APPLIES":"NOT_APPLICABLE",text:ens,destinations:["MEMORY","PPT"]},{element:"INCIDENTS_AND_CONTINUITY",status:"APPLIES",text:incident,destinations:["PPT"]}];
 return{version:LB119_DATA_PROTECTION_SECURITY_VERSION,processingScenario:personal,personalDataRegime:personal,processorAgreementRegime:agreement,serverLocationAndSubprocessingRegime:servers,internationalTransferRegime:transfers,informationSecurityRegime:info,ensRegime:ens,incidentContinuityRegime:incident,documentaryStatements,legalBasis:LEGAL,warnings:["El escenario se decide por hechos del expediente, no por CPV o precedentes.","Consulte al DPD y al responsable de seguridad cuando el riesgo lo requiera.","El PCAP oficial permanece inalterado: solo se rellenan destinos autorizados."],humanValidationRequired:true,generationBlocked:true,productionReady:false};
}
