export { getCanonicalArchitecture, getCanonicalComponent } from "./CanonicalArchitecture";
export { EnvironmentConfiguration } from "./runtime/EnvironmentConfiguration";
export type {
  AICompletionRequest,
  AICompletionResult,
  AIServicePort,
  ApplicationConfiguration,
  CanonicalArchitectureSnapshot,
  CanonicalComponentDescriptor,
  CanonicalComponentId,
  CPVEnginePort,
  CPVProposal,
  DocumentExporterPort,
  DocumentGeneratorPort,
  DomainEvent,
  DomainEventHandler,
  EventBusPort,
  ExportedDocument,
  GeneratedDocument,
  InferenceEnginePort,
  InferenceRequest,
  InferenceResult,
  KnowledgeEnginePort,
  KnowledgeEvidence,
  KnowledgeQuery,
  LegalReasonerPort,
  LegalReasoningRequest,
  LegalReasoningResult,
  ProcedureProposal,
  ProcedureResolverPort,
  RuleEnginePort,
  RuleEvaluationRequest,
  RuleEvaluationResult
} from "./contracts";
