import {createHash} from "node:crypto";
import {computeOdtStyleFingerprint} from "../lb23/UniversalOdtProductionRenderer";
import {readOdtZip} from "../lb23/OdtPackageCodec";
import {HttpPersistedTemplateAssetStore,type PersistedTemplateAssetDescriptor} from "../lb94/HttpPersistedTemplateAssetStore";
import {LB102_FERRETERIA_SOURCE_ASSETS,LB102_PANDA_ASSETS,LB102_SERVICE_SOURCEBACKED_ASSETS} from "./LB102PersistedPilotTemplateStores";

export type LB102ProtectedSourceGroup="ferreteria"|"panda"|"service-huelva"|"service-sevilla";
export type LB102ProtectedSourceKind="PCAP"|"MEMORIA"|"PPT";
interface SourceGroupPolicy{readonly family:"SUPPLY"|"SERVICE";readonly caseId:string;readonly sourceAuthority:string;readonly assets:readonly PersistedTemplateAssetDescriptor[];readonly neverGeneralModel:boolean;readonly supersededReason?:string;}
const SERVICE_HUELVA_PREFIX="case:CONTR-2025-468715:";const SERVICE_SEVILLA_PREFIX="case:CONTR-2026-38892:";export const LB102_BINARY_CHUNK_BYTES=192*1024;
export const LB102_PROTECTED_SOURCE_GROUPS:Readonly<Record<LB102ProtectedSourceGroup,SourceGroupPolicy>>={
 ferreteria:{family:"SUPPLY",caseId:"CONTR/2026/240267",sourceAuthority:"VALIDATED_REAL_EXPEDIENTE",assets:LB102_FERRETERIA_SOURCE_ASSETS,neverGeneralModel:true,supersededReason:"La tríada post-Intervención recibida el 02/09/2026 no supera todavía el gate físico: la Memoria mantiene la incorporación de artículos no contemplados; el PPT conserva simultáneamente 5 y 3 días para material defectuoso, la referencia residual a acuerdo marco y una garantía genérica de tres años junto a la diferenciada. Además existe diferencia declarada de 0,01 € en la anualidad 2026 entre PCAP y Memoria. Debe mantenerse SOURCE_CONFLICT y no acreditarse Ferretería hasta disponer de una tríada corregida/validada."},
 panda:{family:"SUPPLY",caseId:"CONTR 2025 466864",sourceAuthority:"VALIDATED_REAL_EXPEDIENTE_DERIVED_EDITABLE_RECONSTRUCTION",assets:LB102_PANDA_ASSETS,neverGeneralModel:true},
 "service-huelva":{family:"SERVICE",caseId:"CONTR 2025 468715",sourceAuthority:"VALIDATED_REAL_EXPEDIENTE_DERIVED_EDITABLE_RECONSTRUCTION",assets:LB102_SERVICE_SOURCEBACKED_ASSETS.filter(asset=>asset.templateId.startsWith(SERVICE_HUELVA_PREFIX)),neverGeneralModel:true},
 "service-sevilla":{family:"SERVICE",caseId:"CONTR 2026 38892",sourceAuthority:"VALIDATED_REAL_EXPEDIENTE_DERIVED_EDITABLE_RECONSTRUCTION",assets:LB102_SERVICE_SOURCEBACKED_ASSETS.filter(asset=>asset.templateId.startsWith(SERVICE_SEVILLA_PREFIX)),neverGeneralModel:true},
} as const;
function sha256(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
function persistenceConfig(){const endpoint=(process.env.CONTRATA_IA_PERSISTENCE_URL??"").trim().replace(/\/+$/,"");const token=(process.env.CONTRATA_IA_PERSISTENCE_TOKEN??"").trim();if(!endpoint.startsWith("https://")||token.length<16)throw new Error("Persistencia autenticada no configurada.");return{endpoint,token};}
function policy(group:LB102ProtectedSourceGroup){const value=LB102_PROTECTED_SOURCE_GROUPS[group];if(!value)throw new Error("Grupo de fuentes LB102 desconocido.");if(value.assets.length===0)throw new Error(`${group}: allowlist física vacía; ingreso bloqueado.`);return value;}
function descriptorFor(group:LB102ProtectedSourceGroup,kind:LB102ProtectedSourceKind){const value=policy(group);if(value.supersededReason)throw new Error(`${group}: ${value.supersededReason}`);const matches=value.assets.filter(asset=>asset.kind===kind);if(matches.length!==1)throw new Error(`${group}/${kind}: la allowlist debe resolver exactamente un activo.`);return{groupPolicy:value,descriptor:matches[0]!};}
function provenanceFor(groupPolicy:SourceGroupPolicy,descriptor:PersistedTemplateAssetDescriptor){return{role:descriptor.provenanceRole,family:groupPolicy.family,caseId:groupPolicy.caseId,sourceAuthority:groupPolicy.sourceAuthority,officialModelClaimed:false,neverGeneralModel:groupPolicy.neverGeneralModel,humanValidationRequired:true};}
async function responseJson(response:Response){const text=await response.text();let payload:unknown={raw:text};try{payload=JSON.parse(text);}catch{}return payload;}
async function persistChunked(endpoint:string,token:string,group:string,kind:string,descriptor:PersistedTemplateAssetDescriptor,groupPolicy:SourceGroupPolicy,bytes:Uint8Array){const expectedChunks=Math.ceil(bytes.byteLength/LB102_BINARY_CHUNK_BYTES);const start=await fetch(`${endpoint}/template-ingest/start`,{method:"POST",headers:{"x-contrata-ia-persistence-token":token,"content-type":"application/json"},body:JSON.stringify({templateId:descriptor.templateId,kind:descriptor.kind,mediaType:"application/vnd.oasis.opendocument.text",sha256:descriptor.sha256,styleFingerprint:descriptor.styleFingerprint,provenance:provenanceFor(groupPolicy,descriptor),byteLength:bytes.byteLength,expectedChunks})});const startPayload=await responseJson(start) as Record<string,unknown>;if(!start.ok||typeof startPayload.sessionId!=="string")throw new Error(`${group}/${kind}: no se pudo iniciar transporte binario (HTTP ${start.status}).`);const sessionId=startPayload.sessionId;try{for(let index=0;index<expectedChunks;index+=1){const from=index*LB102_BINARY_CHUNK_BYTES,to=Math.min(bytes.byteLength,from+LB102_BINARY_CHUNK_BYTES),chunk=bytes.slice(from,to);const response=await fetch(`${endpoint}/template-ingest/${encodeURIComponent(sessionId)}/chunks/${index}`,{method:"PUT",headers:{"x-contrata-ia-persistence-token":token,"content-type":"application/octet-stream","content-length":String(chunk.byteLength)},body:chunk});if(!response.ok)throw new Error(`${group}/${kind}: fallo en fragmento ${index+1}/${expectedChunks} (HTTP ${response.status}).`);}const finalize=await fetch(`${endpoint}/template-ingest/${encodeURIComponent(sessionId)}/finalize`,{method:"POST",headers:{"x-contrata-ia-persistence-token":token}});const payload=await responseJson(finalize) as Record<string,unknown>;if(!finalize.ok||payload.sha256!==descriptor.sha256||Number(payload.byteLength)!==bytes.byteLength)throw new Error(`${group}/${kind}: promoción atómica rechazada o identidad final incorrecta (HTTP ${finalize.status}).`);return payload;}catch(error){try{await fetch(`${endpoint}/template-ingest/${encodeURIComponent(sessionId)}`,{method:"DELETE",headers:{"x-contrata-ia-persistence-token":token}});}catch{}throw error;}}
export async function persistLB102ProtectedSource(group:LB102ProtectedSourceGroup,kind:LB102ProtectedSourceKind,bytes:Uint8Array){const {groupPolicy,descriptor}=descriptorFor(group,kind);if(sha256(bytes)!==descriptor.sha256)throw new Error(`${group}/${kind}: SHA-256 no coincide con el binario permitido.`);let style:string;try{style=computeOdtStyleFingerprint(readOdtZip(bytes));}catch{throw new Error(`${group}/${kind}: el archivo no es un ODT válido.`);}if(style!==descriptor.styleFingerprint)throw new Error(`${group}/${kind}: huella de estilo no coincide con el activo permitido.`);const {endpoint,token}=persistenceConfig(),payload=await persistChunked(endpoint,token,group,kind,descriptor,groupPolicy,bytes);const recovered=await new HttpPersistedTemplateAssetStore(endpoint,token,[descriptor]).get(descriptor.templateId);if(!recovered||recovered.bytes.byteLength!==bytes.byteLength||sha256(recovered.bytes)!==descriptor.sha256)throw new Error(`${group}/${kind}: la recuperación posterior no acredita identidad binaria completa.`);return{descriptor,payload,byteLength:bytes.byteLength,sha256:descriptor.sha256,styleFingerprint:descriptor.styleFingerprint,chunks:Math.ceil(bytes.byteLength/LB102_BINARY_CHUNK_BYTES)};}
export async function lb102ProtectedSourceStatus(group:LB102ProtectedSourceGroup){const groupPolicy=policy(group);if(groupPolicy.supersededReason)return{group,family:groupPolicy.family,caseId:groupPolicy.caseId,ready:false,assets:groupPolicy.assets.map(asset=>({templateId:asset.templateId,kind:asset.kind,available:false,error:"SUPERSEDED_BY_INTERVENTION_REVIEW"})),blockers:[groupPolicy.supersededReason]};const {endpoint,token}=persistenceConfig(),readiness=await new HttpPersistedTemplateAssetStore(endpoint,token,groupPolicy.assets).readiness();return{group,family:groupPolicy.family,caseId:groupPolicy.caseId,ready:readiness.ready,assets:readiness.assets,blockers:readiness.blockers};}
export function parseLB102ProtectedSourceGroup(value:string):LB102ProtectedSourceGroup|null{return value==="ferreteria"||value==="panda"||value==="service-huelva"||value==="service-sevilla"?value:null;}
export function parseLB102ProtectedSourceKind(value:string):LB102ProtectedSourceKind|null{const normalized=value.toUpperCase();return normalized==="PCAP"||normalized==="MEMORIA"||normalized==="PPT"?normalized:null;}
