import {createHash} from "node:crypto";
import type {UniversalEditableTemplateBinaryStore} from "../lb23/UniversalOdtProductionRenderer";
import {computeOdtStyleFingerprint} from "../lb23/UniversalOdtProductionRenderer";
import {readOdtZip,writeOdtZip} from "../lb23/OdtPackageCodec";
import type {UniversalEvidenceRecord} from "../lb52/UniversalEvidenceWorkspace";
import {assertNoOdtSignatureResidue,sanitizeOdtSignatureResidue} from "./OdtSignatureResidueSanitizer";
import {extractPandaSourceLines,reflowPandaSourceLines} from "./PandaInstitutionalEvidenceFormatter";
import {LB102_PANDA_ASSETS,PANDA_OFFICIAL_ASO_PCAP_SOURCE_URL,PANDA_OFFICIAL_ASO_PCAP_TEMPLATE_ID} from "./LB102PersistedPilotTemplateStores";

function sha256(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
function esc(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");}
function decodeXml(value:string){return value.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'");}
function plain(xml:string){return decodeXml(xml.replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
function compact(xml:string){return plain(xml).replace(/[^A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9]/g,"").toLocaleLowerCase("es");}
function text(bytes:Uint8Array){const content=readOdtZip(bytes).find(entry=>entry.name==="content.xml");return content?plain(Buffer.from(content.bytes).toString("utf8")):"";}
function field(record:UniversalEvidenceRecord,key:string){const f=record.fields[key];if(!f||f.status!=="HUMAN_VALIDATED"||!f.humanValidated)throw new Error(`Panda V11: falta evidencia humana validada para ${key}.`);return f.value;}
function str(record:UniversalEvidenceRecord,key:string){const value=field(record,key);if(typeof value!=="string"||!value.trim())throw new Error(`Panda V11: ${key} debe ser texto validado.`);return value.trim();}
function replaceUniqueLiteral(xml:string,from:string,to:string,label:string){const count=xml.split(from).length-1;if(count!==1)throw new Error(`PCAP oficial ASO: anclaje ${label} aparece ${count} veces; se exige identidad física exacta.`);return xml.replace(from,to);}

function fillFrontPage(xml:string,record:UniversalEvidenceRecord){
 const title=str(record,"administrative.title"),locality=str(record,"administrative.locality"),nuts=str(record,"administrative.nuts"),cpv=str(record,"cpvMain");
 xml=replaceUniqueLiteral(xml,'<text:p text:style-name="P113">Expediente:</text:p><text:p text:style-name="P113"/>',`<text:p text:style-name="P113">Expediente:</text:p><text:p text:style-name="P113">${esc(record.caseId)}</text:p>`,"portada.expediente");
 xml=replaceUniqueLiteral(xml,'<text:p text:style-name="P113">Titulo:</text:p><text:p text:style-name="P113"/>',`<text:p text:style-name="P113">Titulo:</text:p><text:p text:style-name="P113">${esc(title)}</text:p>`,"portada.titulo");
 xml=replaceUniqueLiteral(xml,'<text:p text:style-name="P113">Localidad <text:span text:style-name="T1023">de entrega</text:span>:</text:p><text:p text:style-name="P113"/>',`<text:p text:style-name="P113">Localidad <text:span text:style-name="T1023">de entrega</text:span>:</text:p><text:p text:style-name="P113">${esc(locality)}</text:p>`,"portada.localidad");
 xml=replaceUniqueLiteral(xml,'<text:p text:style-name="P113">Código NUTS del lugar principal de ejecución:</text:p><text:p text:style-name="P113"/>',`<text:p text:style-name="P113">Código NUTS del lugar principal de ejecución:</text:p><text:p text:style-name="P113">${esc(nuts)}</text:p>`,"portada.nuts");
 const start=xml.indexOf('<text:p text:style-name="P113">Código CPV: ');if(start<0)throw new Error("PCAP oficial ASO: no se localiza portada.cpv.");const close=xml.indexOf('</text:note></text:p>',start);if(close<0)throw new Error("PCAP oficial ASO: estructura de nota CPV inesperada.");const anchor='</text:note></text:p>';xml=xml.slice(0,close)+`</text:note><text:span text:style-name="T1023"> ${esc(cpv)}</text:span></text:p>`+xml.slice(close+anchor.length);return xml;
}

function paragraphRanges(xml:string){const out:{start:number;end:number;text:string;compact:string}[]=[];for(const match of xml.matchAll(/<text:p\b[^>]*>[\s\S]*?<\/text:p>/g)){if(match.index===undefined)continue;out.push({start:match.index,end:match.index+match[0].length,text:plain(match[0]),compact:compact(match[0])});}return out;}
function findOfficialAnnexRange(xml:string){const pars=paragraphRanges(xml);const start=pars.find(item=>item.compact==="anexoi"&&item.start>xml.length/2);if(!start)throw new Error("PCAP oficial ASO: no se localiza el inicio material del Anexo I.");const end=pars.find(item=>item.start>start.start&&item.compact==="anexoii");if(!end)throw new Error("PCAP oficial ASO: no se localiza el inicio material del Anexo II.");return{start:start.start,end:end.start};}
function sourcePcapDescriptor(){const asset=LB102_PANDA_ASSETS.find(item=>item.kind==="PCAP");if(!asset)throw new Error("Panda V11: falta PCAP real de evidencia para materializar el Anexo I.");return asset;}
async function loadSourceAnnexLines(store:UniversalEditableTemplateBinaryStore){const asset=sourcePcapDescriptor(),source=await store.get(asset.templateId);if(!source)throw new Error("Panda V11: no se recupera el PCAP real de evidencia.");if(sha256(source.bytes)!==asset.sha256)throw new Error("Panda V11: SHA del PCAP real de evidencia incorrecto.");if(computeOdtStyleFingerprint(readOdtZip(source.bytes))!==asset.styleFingerprint)throw new Error("Panda V11: huella de estilo del PCAP real de evidencia incorrecta.");const sanitized=sanitizeOdtSignatureResidue(source.bytes);assertNoOdtSignatureResidue(sanitized,"PCAP Panda de evidencia");const lines=extractPandaSourceLines(sanitized);const starts=lines.map((line,index)=>({line,index})).filter(item=>/^ANEXO\s+I$/i.test(item.line));if(!starts.length)throw new Error("Panda V11: el PCAP real no contiene Anexo I identificable.");const start=starts[starts.length-1]!.index;const end=lines.findIndex((line,index)=>index>start&&/^ANEXO\s+II$/i.test(line));if(end<0)throw new Error("Panda V11: el PCAP real no contiene cierre del Anexo I.");const annex=reflowPandaSourceLines(lines.slice(start,end));if(annex.length<120)throw new Error(`Panda V11: Anexo I de evidencia insuficiente (${annex.length} párrafos).`);return annex;}
function annexStyle(line:string,index:number){if(index<2||/^\d+(?:\.\d+)*\.?\s+[A-ZÁÉÍÓÚÑ]/.test(line)||(/^[A-ZÁÉÍÓÚÜÑ0-9 .()ª-]+$/.test(line)&&line.length<140))return"P20";if(/^(?:Expediente|Localidad|T[íi]tulo|Objeto|C[óo]digo CPV|Divisi[óo]n|Importe|Valor estimado|M[ée]todo de c[áa]lculo|Tramitaci[óo]n|Plazo|Duraci[óo]n)/i.test(line))return"P134";return"P134";}
function materializedAnnexFragment(lines:readonly string[]){return lines.map((line,index)=>`<text:p text:style-name="${annexStyle(line,index)}">${esc(line)}</text:p>`).join("");}
function assertMaterializedPcap(xml:string,record:UniversalEvidenceRecord){const rendered=plain(xml);const mandatory=[record.caseId,str(record,"administrative.title"),str(record,"object"),str(record,"cpvMain"),"61.192,25","74.042,62","36 meses","División en lotes: No"];for(const value of mandatory)if(!rendered.toLocaleLowerCase("es").includes(value.toLocaleLowerCase("es")))throw new Error(`PCAP Panda V11: no se materializó el dato obligatorio ${value}.`);const critical=[/Objeto del contrato:\s*_+/i,/Importe total \(IVA excluido\):\s*_+/i,/Valor estimado del contrato:\s*_+/i,/Divisi[óo]n en lotes:\s*S[íi]\s*\/\s*No/i,/Tramitaci[óo]n del gasto:\s*Ordinaria\s*\/\s*Anticipada/i];for(const pattern of critical)if(pattern.test(rendered))throw new Error(`PCAP Panda V11: persiste un hueco crítico sin materializar (${pattern.source}).`);}

/** Gate físico del PCAP Panda V11. */
export async function loadPandaOfficialAsoPcapForCalibration(store:UniversalEditableTemplateBinaryStore){const source=await store.get(PANDA_OFFICIAL_ASO_PCAP_TEMPLATE_ID);if(!source)throw new Error(`Panda V11 bloqueado: falta el modelo oficial PCAP Suministro, procedimiento abierto simplificado ordinario, autofinanciado (17/12/2025). Fuente: ${PANDA_OFFICIAL_ASO_PCAP_SOURCE_URL}`);assertNoOdtSignatureResidue(source.bytes,"PCAP oficial ASO");const body=text(source.bytes);const required=["Suministro","Abierto Simplificado ordinario","ELEMENTOS DEL CONTRATO","ANEXO I","CARACTERÍSTICAS DEL CONTRATO"];for(const marker of required)if(!body.toLowerCase().includes(marker.toLowerCase()))throw new Error(`PCAP oficial ASO: falta marcador estructural ${marker}.`);return source;}

export interface PandaOfficialAsoPcapRenderResult{bytes:Uint8Array;sha256:string;fileName:string;officialModel:true;humanValidationRequired:true;}
/** V11 conserva íntegramente el cuerpo normativo del modelo oficial diciembre-2025 y sustituye únicamente su Anexo I en blanco por el Anexo I materializado del expediente Panda, saneado de firma y refluido sobre estilos del modelo oficial. */
export async function renderPandaOfficialAsoPcap(input:{templateStore:UniversalEditableTemplateBinaryStore;caseId:string;record:UniversalEvidenceRecord}):Promise<PandaOfficialAsoPcapRenderResult>{if(input.caseId!==input.record.caseId)throw new Error("Panda V11: caseId y snapshot no coinciden.");const source=await loadPandaOfficialAsoPcapForCalibration(input.templateStore);const annexLines=await loadSourceAnnexLines(input.templateStore);let entries=readOdtZip(source.bytes);const beforeStyle=computeOdtStyleFingerprint(entries),content=entries.find(entry=>entry.name==="content.xml");if(!content)throw new Error("PCAP oficial ASO: falta content.xml.");let xml=Buffer.from(content.bytes).toString("utf8");xml=fillFrontPage(xml,input.record);const range=findOfficialAnnexRange(xml);xml=xml.slice(0,range.start)+materializedAnnexFragment(annexLines)+xml.slice(range.end);assertMaterializedPcap(xml,input.record);entries=entries.map(entry=>entry.name==="content.xml"?{...entry,bytes:Buffer.from(xml,"utf8")}:entry);const afterStyle=computeOdtStyleFingerprint(entries);if(afterStyle!==beforeStyle)throw new Error("Panda V11: el render alteró la huella de estilo del modelo oficial.");const bytes=writeOdtZip(entries);assertNoOdtSignatureResidue(bytes,"PCAP Panda V11");return{bytes,sha256:sha256(bytes),fileName:`PCAP_${input.caseId.replaceAll("/","-").replaceAll(" ","-")}_JDA_ASO_Official_Materialized_V11.odt`,officialModel:true,humanValidationRequired:true};}
