import {createHash} from "node:crypto";
import type {UniversalEditableTemplateBinaryStore} from "../lb23/UniversalOdtProductionRenderer";
import {computeOdtStyleFingerprint} from "../lb23/UniversalOdtProductionRenderer";
import {readOdtZip,writeOdtZip} from "../lb23/OdtPackageCodec";
import {extractPandaSourceLines,reflowPandaSourceLines} from "./PandaInstitutionalEvidenceFormatter";
import {assertLb102GeneratedDocumentQuality} from "./LB102UniversalDocumentQualityGate";
import {SERVICE_OFFICIAL_OPEN_PCAP_TEMPLATE_ID} from "./LB102PersistedPilotTemplateStores";

function sha(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
function esc(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;");}
function decodeXml(value:string){return value.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'\"').replace(/&apos;/g,"'");}
function plain(xml:string){return decodeXml(xml.replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
function norm(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim().toLocaleLowerCase("es");}
const NON_SELF_CLOSING_TEXT_P=/<text:p\b(?![^>]*\/>)([^>]*)>[\s\S]*?<\/text:p>/g;
function paragraphs(xml:string){const out:{start:number;end:number;text:string;style:string|null;xml:string}[]=[];for(const match of xml.matchAll(NON_SELF_CLOSING_TEXT_P)){if(match.index===undefined)continue;const attrs=match[1]??"";const sm=/text:style-name="([^"]+)"/.exec(attrs);out.push({start:match.index,end:match.index+match[0].length,text:plain(match[0]),style:sm?.[1]??null,xml:match[0]});}return out;}
function annexRoman(line:string){const normalized=line.replace(/\s+/g," ").trim();const match=/^ANEXO\s+(?:(?:N(?:Ú|U)M(?:ERO)?\.?|N\.?[º°]\.?|NÚMERO)\s*)?([IVXLCDM]+)(?:\b|[.ªº°:-])/i.exec(normalized);return match?.[1]?.toUpperCase()??null;}
function annexCandidateScore(lines:readonly string[]){const joined=norm(lines.join("\n"));const markers=["expediente","objeto","codigo cpv","cpv","valor estimado","presupuesto","importe total","division en lotes","tramitacion","duracion","plazo"];return markers.reduce((sum,m)=>sum+(joined.includes(norm(m))?1:0),0);}
function hasAdministrativeCore(lines:readonly string[]){const joined=norm(lines.join("\n"));return joined.includes("expediente")&&joined.includes("cpv")&&(joined.includes("objeto")||joined.includes("presupuesto")||joined.includes("valor estimado")||joined.includes("importe total"));}
function annexRange(xml:string,label:string){const pars=paragraphs(xml);const starts=pars.filter(item=>annexRoman(item.text)==="I");const candidates=starts.map(start=>{const end=pars.find(item=>item.start>start.start&&annexRoman(item.text)!==null&&annexRoman(item.text)!=="I");if(!end)return null;const inside=pars.filter(item=>item.start>=start.start&&item.start<end.start);const lead=inside.slice(0,80).map(item=>item.text);return{start,end,inside,score:annexCandidateScore(lead),core:hasAdministrativeCore(lead)};}).filter((x):x is {start:(typeof pars)[number];end:(typeof pars)[number];inside:(typeof pars);score:number;core:boolean}=>x!==null&&x.core&&x.score>=4);candidates.sort((a,b)=>b.score-a.score||a.inside.length-b.inside.length||a.start.start-b.start.start);const best=candidates[0];if(!best)throw new Error(`${label}: no se localiza un Anexo I administrativo real.`);const style=best.inside.find(item=>item.start>best.start.start&&item.style)?.style??best.start.style??"Standard";return{start:best.start.start,end:best.end.start,headingStyle:style,bodyStyle:"Text_20_body"};}
export function selectServiceOfficialAnnexRangeForRegression(xml:string){const range=annexRange(xml,"PCAP oficial Service");return{start:range.start,end:range.end};}
function isResidualGuide(line:string){const v=line.replace(/\s+/g," ").trim();return /_{4,}/.test(v)||/^\(?\s*(?:indicar|señalar|marcar|cumplimentar)\b/i.test(v)||/^DOCUMENTO A CUMPLIMENTAR/i.test(v);}
export function selectServiceSourceAnnexLinesForRegression(lines:readonly string[]){const starts=lines.map((line,index)=>({index,roman:annexRoman(line)})).filter(item=>item.roman==="I");if(!starts.length)throw new Error("PCAP Service de evidencia: no se identifica Anexo I.");const candidates=starts.map(({index:start})=>{const end=lines.findIndex((line,index)=>index>start&&annexRoman(line)!==null&&annexRoman(line)!=="I");if(end<0)return null;const annex=reflowPandaSourceLines(lines.slice(start,end)).filter(line=>!isResidualGuide(line));const lead=annex.slice(0,80);return{annex,score:annexCandidateScore(lead),core:hasAdministrativeCore(lead)};}).filter((x):x is {annex:string[];score:number;core:boolean}=>x!==null&&x.core&&x.score>=4);candidates.sort((a,b)=>b.score-a.score||a.annex.length-b.annex.length);const best=candidates[0];if(!best)throw new Error("PCAP Service de evidencia: ningún Anexo I contiene suficiente evidencia administrativa en su cabecera material.");if(best.annex.length<20)throw new Error(`PCAP Service de evidencia: Anexo I insuficiente (${best.annex.length} párrafos).`);return best.annex;}
function sourceAnnexLines(sourceBytes:Uint8Array){return selectServiceSourceAnnexLinesForRegression(extractPandaSourceLines(sourceBytes));}
function replaceFollowingEmptyParagraph(xml:string,label:string,value:string){const escaped=label.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const re=new RegExp(`(<text:p\\b[^>]*>\\s*${escaped}\\s*</text:p>)\\s*<text:p\\b([^>]*)/>`,`i`);let done=false;const out=xml.replace(re,(_m,first,attrs)=>{done=true;return `${first}<text:p${attrs}>${esc(value)}</text:p>`;});return{xml:out,done};}
function fillFrontPage(xml:string,input:{caseId:string;mainCpv:string;objectValue:string}){let out=xml;for(const [label,value] of [["Expediente:",input.caseId],["Titulo:",input.objectValue]] as const){const r=replaceFollowingEmptyParagraph(out,label,value);out=r.xml;}const cover=out.indexOf("ANEXO I -");if(cover>=0){const pStart=out.indexOf("<text:p",cover);const cpvStart=out.indexOf("Código CPV:",pStart);if(cpvStart>=0){const close=out.indexOf("</text:p>",cpvStart);if(close>cpvStart&&!plain(out.slice(cpvStart,close)).includes(input.mainCpv)){out=out.slice(0,close)+` <text:span>${esc(input.mainCpv)}</text:span>`+out.slice(close);}}}return out;}
function materializeField(xml:string,value:string,label:RegExp,replacement:string,errorLabel:string){const hadValue=norm(plain(xml)).includes(norm(value.trim()));let replaced=0;const out=xml.replace(NON_SELF_CLOSING_TEXT_P,whole=>{const text=plain(whole);if(!label.test(text))return whole;const open=/^<text:p\b(?![^>]*\/>)[^>]*>/.exec(whole)?.[0];if(!open)return whole;replaced++;return `${open}${esc(replacement)}</text:p>`;});if(replaced>0)return out;if(hadValue)return xml;throw new Error(`PCAP oficial Service: no se localiza ${errorLabel} para materializarlo.`);}
function replaceOptionalPlaceholderParagraph(xml:string,label:RegExp,replacement:string){return xml.replace(NON_SELF_CLOSING_TEXT_P,whole=>{const text=plain(whole);if(!label.test(text))return whole;const open=/^<text:p\b(?![^>]*\/>)[^>]*>/.exec(whole)?.[0];if(!open)return whole;return `${open}${esc(replacement)}</text:p>`;});}
function materializeCriticalFields(xml:string,input:{caseId:string;mainCpv:string;objectValue:string;pblExVat:string;estimatedValue:string;divisionIntoLots:"Sí"|"No";expenseProcessing:"Ordinaria"|"Anticipada"}){if(!input.caseId.trim()||!input.mainCpv.trim()||!input.objectValue.trim()||!input.pblExVat.trim()||!input.estimatedValue.trim())throw new Error("PCAP oficial Service: datos críticos acreditados incompletos.");let out=materializeField(xml,input.caseId,/EXPEDIENTE\s*:\s*_{3,}/i,`EXPEDIENTE: ${input.caseId.trim()}`,"el expediente");out=materializeField(out,input.mainCpv,/C[oó]digo\s+CPV\s*(?:\d+)?\s*:\s*_{3,}/i,`Código CPV: ${input.mainCpv.trim()}`,"el código CPV");out=materializeField(out,input.objectValue,/Objeto del contrato\s*:\s*_{3,}/i,`Objeto del contrato: ${input.objectValue.trim()}`,"el campo genérico de objeto");out=materializeField(out,input.pblExVat,/Importe total\s*\(IVA excluido\)\s*:\s*_{3,}/i,`Importe total (IVA excluido): ${input.pblExVat.trim()} €`,"el importe total sin IVA");out=materializeField(out,input.estimatedValue,/Valor estimado del contrato\s*:\s*_{3,}/i,`Valor estimado del contrato: ${input.estimatedValue.trim()} €`,"el valor estimado");out=replaceOptionalPlaceholderParagraph(out,/Divisi[oó]n en lotes\s*:\s*S[ií]\s*\/\s*No/i,`División en lotes: ${input.divisionIntoLots}`);out=replaceOptionalPlaceholderParagraph(out,/Tramitaci[oó]n(?: del gasto)?\s*:\s*Ordinaria\s*\/\s*Anticipada/i,`Tramitación del gasto: ${input.expenseProcessing}.`);return out;}
export function materializeServiceOfficialPcapCriticalFieldsForRegression(xml:string,input:{caseId:string;mainCpv:string;objectValue:string;pblExVat:string;estimatedValue:string;divisionIntoLots:"Sí"|"No";expenseProcessing:"Ordinaria"|"Anticipada"}){return materializeCriticalFields(xml,input);}
function ensureAdministrativeEvidenceLines(lines:readonly string[],input:{caseId:string;mainCpv:string;objectValue:string;pblExVat:string;estimatedValue:string;divisionIntoLots:"Sí"|"No";expenseProcessing:"Ordinaria"|"Anticipada"}){const out=[...lines];const joined=()=>norm(out.join("\n"));const required=[{value:input.caseId,line:`EXPEDIENTE: ${input.caseId}`},{value:input.mainCpv,line:`Código CPV: ${input.mainCpv}`},{value:input.objectValue,line:`Objeto del contrato: ${input.objectValue}`},{value:input.pblExVat,line:`Importe total (IVA excluido): ${input.pblExVat} €`},{value:input.estimatedValue,line:`Valor estimado del contrato: ${input.estimatedValue} €`},{value:`División en lotes: ${input.divisionIntoLots}`,line:`División en lotes: ${input.divisionIntoLots}`},{value:`Tramitación del gasto: ${input.expenseProcessing}`,line:`Tramitación del gasto: ${input.expenseProcessing}`}];for(const item of required)if(!joined().includes(norm(item.value)))out.push(item.line);return out;}
function rowOne(value:string,style:string,bookmark=false){const mark=bookmark?`<text:bookmark-start text:name="CI_ANEXO_I"/>`:"";const end=bookmark?`<text:bookmark-end text:name="CI_ANEXO_I"/>`:"";return `<table:table-row><table:table-cell table:number-columns-spanned="2" office:value-type="string"><text:p text:style-name="${esc(style)}">${mark}${esc(value)}${end}</text:p></table:table-cell><table:covered-table-cell/></table:table-row>`;}
function rowTwo(left:string,right:string,labelStyle:string,bodyStyle:string){return `<table:table-row><table:table-cell office:value-type="string"><text:p text:style-name="${esc(labelStyle)}">${esc(left)}</text:p></table:table-cell><table:table-cell office:value-type="string"><text:p text:style-name="${esc(bodyStyle)}">${esc(right)}</text:p></table:table-cell></table:table-row>`;}
function administrativeAnnexFragment(lines:readonly string[],headingStyle:string,bodyStyle:string){const normalized=lines.filter((line,index)=>!(index===0&&annexRoman(line)==="I"));const rows=[rowOne("ANEXO I - CARACTERÍSTICAS DEL CONTRATO",headingStyle,true),...normalized.map(line=>{if(/^\d+(?:\.\d+)*\.?\s+[A-ZÁÉÍÓÚÑ]/.test(line)||/^[A-ZÁÉÍÓÚÜÑ0-9 .()ª-]{6,100}$/.test(line))return rowOne(line,headingStyle);const colon=line.indexOf(":");if(colon>0&&colon<100){const left=line.slice(0,colon+1).trim(),right=line.slice(colon+1).trim();if(right)return rowTwo(left,right,headingStyle,bodyStyle);}return rowOne(line,bodyStyle);})].join("");return `<table:table table:name="CI_Anexo_I"><table:table-column/><table:table-column/>${rows}</table:table>`;}
function addIndexLink(xml:string,style:string){if(xml.includes('xlink:href="#CI_ANEXO_I"'))return xml;const needle="DOCUMENTO A CUMPLIMENTAR POR EL ÓRGANO DE CONTRATACIÓN:";const p=paragraphs(xml).find(item=>norm(item.text)===norm(needle));if(!p)return xml;const link=`<text:p text:style-name="${esc(style)}"><text:a xlink:type="simple" xlink:href="#CI_ANEXO_I">ANEXO I: CARACTERÍSTICAS DEL CONTRATO</text:a></text:p>`;return xml.slice(0,p.end)+link+xml.slice(p.end);}
export interface ServiceOfficialOpenPcapRenderResult{bytes:Uint8Array;sha256:string;officialModel:true;}
export async function renderServiceOfficialOpenPcap(input:{templateStore:UniversalEditableTemplateBinaryStore;sourcePcapBytes:Uint8Array;caseId:string;mainCpv:string;objectValue:string;pblExVat:string;estimatedValue:string;divisionIntoLots:"Sí"|"No";expenseProcessing:"Ordinaria"|"Anticipada";label:string;exactValues:readonly string[];semanticConceptGroups:readonly (readonly string[])[]}):Promise<ServiceOfficialOpenPcapRenderResult>{const official=await input.templateStore.get(SERVICE_OFFICIAL_OPEN_PCAP_TEMPLATE_ID);if(!official)throw new Error(`${input.label}: falta modelo oficial Junta de Servicios abierto autofinanciado.`);let entries=readOdtZip(official.bytes);const before=computeOdtStyleFingerprint(entries);const content=entries.find(entry=>entry.name==="content.xml");if(!content)throw new Error(`${input.label}: modelo oficial sin content.xml.`);let xml=Buffer.from(content.bytes).toString("utf8");xml=fillFrontPage(xml,input);const range=annexRange(xml,"PCAP oficial Service");const sourceLines=sourceAnnexLines(input.sourcePcapBytes);const lines=ensureAdministrativeEvidenceLines(sourceLines,input);const fragment=administrativeAnnexFragment(lines,range.headingStyle,range.bodyStyle);xml=xml.slice(0,range.start)+fragment+xml.slice(range.end);xml=addIndexLink(xml,range.headingStyle);xml=materializeCriticalFields(xml,input);entries=entries.map(entry=>entry.name==="content.xml"?{...entry,bytes:Buffer.from(xml,"utf8")}:entry);const after=computeOdtStyleFingerprint(entries);if(after!==before)throw new Error(`${input.label}: el render alteró la huella de estilo del modelo oficial.`);const bytes=writeOdtZip(entries);assertLb102GeneratedDocumentQuality({bytes,kind:"PCAP",label:input.label,exactValues:input.exactValues,semanticConceptGroups:input.semanticConceptGroups});return{bytes,sha256:sha(bytes),officialModel:true};}
