import {createHash} from "node:crypto";
import type {UniversalEditableTemplateBinaryStore} from "../lb23/UniversalOdtProductionRenderer";
import {computeOdtStyleFingerprint} from "../lb23/UniversalOdtProductionRenderer";
import {readOdtZip,writeOdtZip} from "../lb23/OdtPackageCodec";
import {extractPandaSourceLines,reflowPandaSourceLines} from "./PandaInstitutionalEvidenceFormatter";
import {assertLb102GeneratedDocumentQuality} from "./LB102UniversalDocumentQualityGate";
import {SERVICE_OFFICIAL_OPEN_PCAP_TEMPLATE_ID} from "./LB102PersistedPilotTemplateStores";

function sha(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
function esc(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");}
function decodeXml(value:string){return value.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'");}
function plain(xml:string){return decodeXml(xml.replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
function paragraphs(xml:string){const out:{start:number;end:number;text:string;style:string|null}[]=[];for(const match of xml.matchAll(/<text:p\b([^>]*)>[\s\S]*?<\/text:p>/g)){if(match.index===undefined)continue;const attrs=match[1]??"";const sm=/text:style-name="([^"]+)"/.exec(attrs);out.push({start:match.index,end:match.index+match[0].length,text:plain(match[0]),style:sm?.[1]??null});}return out;}
function annexRoman(line:string){const normalized=line.replace(/\s+/g," ").trim();const match=/^ANEXO\s+(?:(?:N(?:Ú|U)M(?:ERO)?\.?|N\.?[º°]\.?|NÚMERO)\s*)?([IVXLCDM]+)(?:\b|[.ªº°:-])/i.exec(normalized);return match?.[1]?.toUpperCase()??null;}
function annexRange(xml:string,label:string){const pars=paragraphs(xml);const starts=pars.filter(item=>annexRoman(item.text)==="I");const start=starts[starts.length-1];if(!start)throw new Error(`${label}: no se localiza el Anexo I.`);const end=pars.find(item=>item.start>start.start&&annexRoman(item.text)!==null&&annexRoman(item.text)!=="I");if(!end)throw new Error(`${label}: no se localiza un anexo posterior que cierre el Anexo I.`);const style=pars.find(item=>item.start>start.start&&item.start<end.start&&item.style)?.style??start.style??"Standard";return{start:start.start,end:end.start,style};}
function sourceAnnexLines(sourceBytes:Uint8Array){const lines=extractPandaSourceLines(sourceBytes);const starts=lines.map((line,index)=>({line,index,roman:annexRoman(line)})).filter(item=>item.roman==="I");if(!starts.length)throw new Error("PCAP Service de evidencia: no se identifica Anexo I.");const start=starts[starts.length-1]!.index;const end=lines.findIndex((line,index)=>index>start&&annexRoman(line)!==null&&annexRoman(line)!=="I");if(end<0)throw new Error("PCAP Service de evidencia: no se identifica un anexo posterior que cierre el Anexo I.");const annex=reflowPandaSourceLines(lines.slice(start,end));if(annex.length<20)throw new Error(`PCAP Service de evidencia: Anexo I insuficiente (${annex.length} párrafos).`);return annex;}
function replacePlaceholderParagraph(xml:string,label:RegExp,replacement:string,errorLabel:string){let replaced=0;const out=xml.replace(/<text:p\b([^>]*)>[\s\S]*?<\/text:p>/g,whole=>{const text=plain(whole);if(!label.test(text))return whole;const open=/^<text:p\b[^>]*>/.exec(whole)?.[0]??"<text:p>";replaced++;return `${open}${esc(replacement)}</text:p>`;});if(replaced===0)throw new Error(`PCAP oficial Service: no se localiza ${errorLabel} para materializarlo.`);return out;}
function materializeCriticalFields(xml:string,input:{objectValue:string;pblExVat:string;estimatedValue:string}){if(!input.objectValue.trim()||!input.pblExVat.trim()||!input.estimatedValue.trim())throw new Error("PCAP oficial Service: datos críticos acreditados incompletos.");let out=replacePlaceholderParagraph(xml,/Objeto del contrato\s*:\s*_{3,}/i,`Objeto del contrato: ${input.objectValue.trim()}`,"el campo genérico de objeto");out=replacePlaceholderParagraph(out,/Importe total\s*\(IVA excluido\)\s*:\s*_{3,}/i,`Importe total (IVA excluido): ${input.pblExVat.trim()} €`,"el importe total sin IVA");out=replacePlaceholderParagraph(out,/Valor estimado del contrato\s*:\s*_{3,}/i,`Valor estimado del contrato: ${input.estimatedValue.trim()} €`,"el valor estimado");return out;}
function rowOne(value:string,style:string){return `<table:table-row><table:table-cell table:number-columns-spanned="2" office:value-type="string"><text:p text:style-name="${esc(style)}">${esc(value)}</text:p></table:table-cell><table:covered-table-cell/></table:table-row>`;}
function rowTwo(left:string,right:string,style:string){return `<table:table-row><table:table-cell office:value-type="string"><text:p text:style-name="${esc(style)}">${esc(left)}</text:p></table:table-cell><table:table-cell office:value-type="string"><text:p text:style-name="${esc(style)}">${esc(right)}</text:p></table:table-cell></table:table-row>`;}
function administrativeAnnexFragment(lines:readonly string[],style:string){const rows=lines.map((line,index)=>{if(index===0||/^\d+(?:\.\d+)*\.?\s+[A-ZÁÉÍÓÚÑ]/.test(line)||/^[A-ZÁÉÍÓÚÜÑ0-9 .()ª-]{6,140}$/.test(line))return rowOne(line,style);const colon=line.indexOf(":");if(colon>0&&colon<100){const left=line.slice(0,colon+1).trim(),right=line.slice(colon+1).trim();if(right)return rowTwo(left,right,style);}return rowOne(line,style);}).join("");return `<table:table table:name="CI_Anexo_I"><table:table-column/><table:table-column/>${rows}</table:table>`;}
export interface ServiceOfficialOpenPcapRenderResult{bytes:Uint8Array;sha256:string;officialModel:true;}
export async function renderServiceOfficialOpenPcap(input:{templateStore:UniversalEditableTemplateBinaryStore;sourcePcapBytes:Uint8Array;objectValue:string;pblExVat:string;estimatedValue:string;label:string;exactValues:readonly string[];semanticConceptGroups:readonly (readonly string[])[]}):Promise<ServiceOfficialOpenPcapRenderResult>{const official=await input.templateStore.get(SERVICE_OFFICIAL_OPEN_PCAP_TEMPLATE_ID);if(!official)throw new Error(`${input.label}: falta modelo oficial Junta de Servicios abierto autofinanciado.`);let entries=readOdtZip(official.bytes);const before=computeOdtStyleFingerprint(entries);const content=entries.find(entry=>entry.name==="content.xml");if(!content)throw new Error(`${input.label}: modelo oficial sin content.xml.`);let xml=Buffer.from(content.bytes).toString("utf8");const range=annexRange(xml,"PCAP oficial Service");const lines=sourceAnnexLines(input.sourcePcapBytes);const fragment=administrativeAnnexFragment(lines,range.style);xml=xml.slice(0,range.start)+fragment+xml.slice(range.end);xml=materializeCriticalFields(xml,input);entries=entries.map(entry=>entry.name==="content.xml"?{...entry,bytes:Buffer.from(xml,"utf8")}:entry);const after=computeOdtStyleFingerprint(entries);if(after!==before)throw new Error(`${input.label}: el render alteró la huella de estilo del modelo oficial.`);const bytes=writeOdtZip(entries);assertLb102GeneratedDocumentQuality({bytes,kind:"PCAP",label:input.label,exactValues:input.exactValues,semanticConceptGroups:input.semanticConceptGroups});return{bytes,sha256:sha(bytes),officialModel:true};}
