export const LB117_EXECUTION_RECEIPT_PAYMENT_VERSION="LB117-EXECUTION-RECEIPT-PAYMENT-V1" as const;
const LCSP="https://www.boe.es/buscar/act.php?id=BOE-A-2017-12902";
interface Basis{id:string;article:string;paragraph:string;relevantOfficialExcerpt:string;officialUrl:string}
export interface ExecutionReceiptPaymentInput {contractType:"SUPPLY"|"SERVICE";contractManager:string;contractManagerFunctions:string;executionLocations:readonly string[];executionMonitoringRegime:string;deliveryOrPerformanceRegime:string;receiptAndAcceptanceRegime:string;receiptDeadlineDays:number;extendedReceiptDeadlineJustification:string;defectCorrectionRegime:string;paymentMode:"SINGLE"|"SUCCESSIVE";invoiceSubmissionRegime:string;paymentRegime:string}
export interface ExecutionReceiptPaymentResult {version:typeof LB117_EXECUTION_RECEIPT_PAYMENT_VERSION;contractManager:string;contractManagerFunctions:string;executionRegime:string;receiptAndAcceptanceRegime:string;invoiceSubmissionRegime:string;paymentRegime:string;documentaryStatements:readonly {element:string;status:"APPLIES";text:string;destinations:readonly ("MEMORY"|"PCAP"|"PPT")[]}[];legalBasis:readonly Basis[];warnings:readonly string[];humanValidationRequired:true;generationBlocked:true;productionReady:false}
const basis=(id:string,article:string,paragraph:string,text:string):Basis=>({id,article,paragraph,relevantOfficialExcerpt:text,officialUrl:`${LCSP}#a${article}`});
const LEGAL=[basis("LCSP-62.1","62","1","El órgano de contratación designará un responsable del contrato para supervisar su ejecución y dictar las instrucciones necesarias dentro de las facultades atribuidas."),basis("LCSP-197","197","único","La ejecución del contrato se realizará a riesgo y ventura del contratista."),basis("LCSP-198.2","198","2","El pago podrá hacerse de manera total o parcial, mediante abonos a cuenta o, en contratos de tracto sucesivo, por vencimientos estipulados."),basis("LCSP-198.4","198","4","La Administración abonará el precio dentro de los treinta días siguientes a la aprobación de los documentos de conformidad."),basis("LCSP-210.2","210","2","La constatación del cumplimiento exige un acto formal y positivo de recepción o conformidad dentro del plazo legal o del fijado motivadamente en el PCAP."),basis("LCSP-210.4","210","4","Cuando proceda, la liquidación se acordará dentro de los treinta días desde el acta de recepción o conformidad."),basis("LCSP-300.1","300","1","En suministros, los bienes se entregarán en el tiempo y lugar fijados y conforme a los pliegos."),basis("LCSP-301.1","301","1","El suministro se abona por los bienes efectivamente entregados y formalmente recibidos."),basis("LCSP-304.2","304","2","Los defectos de los bienes se harán constar en el acta y darán lugar a instrucciones de subsanación o nuevo suministro."),basis("LCSP-311.1","311","1","En servicios, la ejecución se sujeta al contrato, a los pliegos y a las instrucciones del responsable."),basis("LCSP-311.3","311","3","La Administración comprobará la adecuación de la prestación y exigirá la subsanación de los defectos observados.")];
const clean=(v:string,label:string)=>{const x=String(v||"").trim();if(!x||/pendiente|por determinar|no lo s[eé]/i.test(x))throw new Error(`Falta concretar ${label}.`);return x;};
export function evaluateExecutionReceiptPayment(i:ExecutionReceiptPaymentInput):ExecutionReceiptPaymentResult{
 const manager=clean(i.contractManager,"la persona o unidad responsable del contrato"),functions=clean(i.contractManagerFunctions,"sus facultades e instrucciones"),monitoring=clean(i.executionMonitoringRegime,"el seguimiento verificable de la ejecución"),delivery=clean(i.deliveryOrPerformanceRegime,"el régimen de entregas o prestaciones");
 const locations=[...new Set((i.executionLocations||[]).map(x=>String(x).trim()).filter(Boolean))];if(!locations.length)throw new Error("Debe declararse al menos un lugar o ámbito de ejecución o entrega.");
 if(!Number.isInteger(i.receiptDeadlineDays)||i.receiptDeadlineDays<=0)throw new Error("El plazo de recepción o conformidad debe expresarse en días enteros positivos.");
 const extended=i.receiptDeadlineDays>30,extendedReason=extended?clean(i.extendedReceiptDeadlineJustification,"la justificación del plazo de recepción superior a un mes"):"No procede: el plazo no supera un mes.";
 const receipt=clean(i.receiptAndAcceptanceRegime,"el acto formal de recepción o conformidad"),defects=clean(i.defectCorrectionRegime,"la comprobación y subsanación de defectos"),invoice=clean(i.invoiceSubmissionRegime,"la presentación de la factura"),payment=clean(i.paymentRegime,"el régimen de pago");
 const execution=`Responsable: ${manager}. Facultades: ${functions}. Seguimiento: ${monitoring}. ${i.contractType==="SUPPLY"?"Entrega":"Prestación"}: ${delivery}. Lugar o ámbito: ${locations.join("; ")}. Ejecución a riesgo y ventura del contratista y con sujeción a los pliegos e instrucciones válidamente dictadas.`;
 const receiptText=`Recepción o conformidad formal y positiva en ${i.receiptDeadlineDays} días desde la entrega o realización. Procedimiento: ${receipt}. Comprobación y defectos: ${defects}. ${extendedReason}`;
 const invoiceText=`Factura electrónica: ${invoice}. Debe vincularse a la entrega o prestación efectivamente realizada y al documento de conformidad.`;
 const paymentText=`Pago ${i.paymentMode==="SINGLE"?"único":"sucesivo"}: ${payment}. El abono se tramitará dentro de los treinta días siguientes a la aprobación del documento de conformidad, sin convertir este plazo legal en una fecha de pago inventada.`;
 return{version:LB117_EXECUTION_RECEIPT_PAYMENT_VERSION,contractManager:manager,contractManagerFunctions:functions,executionRegime:execution,receiptAndAcceptanceRegime:receiptText,invoiceSubmissionRegime:invoiceText,paymentRegime:paymentText,documentaryStatements:[{element:"CONTRACT_MANAGER",status:"APPLIES",text:`${manager}. ${functions}`,destinations:["MEMORY","PCAP","PPT"]},{element:"EXECUTION",status:"APPLIES",text:execution,destinations:["MEMORY","PCAP","PPT"]},{element:"RECEIPT_CONFORMITY",status:"APPLIES",text:receiptText,destinations:["MEMORY","PCAP","PPT"]},{element:"INVOICING",status:"APPLIES",text:invoiceText,destinations:["MEMORY","PCAP"]},{element:"PAYMENT",status:"APPLIES",text:paymentText,destinations:["MEMORY","PCAP"]}],legalBasis:LEGAL,warnings:["La identidad del responsable, las unidades contables y los códigos de facturación proceden de la Administración y nunca se infieren del objeto.","La conformidad acredita la prestación; no equivale por sí sola a ordenar ni efectuar el pago.",...(extended?["El plazo superior a un mes requiere motivación específica por las características del contrato y constancia en el PCAP."]:[])],humanValidationRequired:true,generationBlocked:true,productionReady:false};
}
