import { FerreteriaCatalogItem, validateFerreteriaCanonicalCatalog } from "../lb39/FerreteriaCanonicalCatalog";

/**
 * LB43 — catálogo canónico source-backed del caso CONTR/2026/240267.
 *
 * Fuente: PPT Feretería SSCC SAE V6, punto 4. Se preservan los importes por fila
 * tal como figuran en la fuente, incluido el redondeo del IVA por artículo.
 * El total agregado declarado (IVA 2.216,01 €; total con IVA 12.768,45 €) no
 * coincide exactamente con la suma de los IVA redondeados fila a fila
 * (2.215,99 €) y se conserva como magnitud agregada declarada independiente.
 */
export const FERRETERIA_CANONICAL_CATALOG_98: readonly FerreteriaCatalogItem[] = [
  { sequence: 1, description: "ABRAZADERAS MANGUERA", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 130, totalPriceCentsExVat: 520, vatCents: 109, totalPriceCentsVatIncluded: 629 },
  { sequence: 2, description: "ACEITE MULTIUSO WD-40 400ML O EQUIVALENTE", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 999, totalPriceCentsExVat: 3996, vatCents: 839, totalPriceCentsVatIncluded: 4835 },
  { sequence: 3, description: "ADHESIVO DE MONTAJE EXPRESS CARTUCHO", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 668, totalPriceCentsExVat: 1336, vatCents: 281, totalPriceCentsVatIncluded: 1617 },
  { sequence: 4, description: "ALARGADERA 1,5 MTS 4 BASES CON INTERRUPTOR DE CORTE", estimatedAnnualConsumption: 50, totalContractUnits24Months: 100, unitPriceCentsExVat: 1150, totalPriceCentsExVat: 115000, vatCents: 24150, totalPriceCentsVatIncluded: 139150 },
  { sequence: 5, description: "ALARGADERA 3 MTS 4 BASES CON INTERRUPTOR DE CORTE", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 1380, totalPriceCentsExVat: 11040, vatCents: 2318, totalPriceCentsVatIncluded: 13358 },
  { sequence: 6, description: "ALARGADERA 3 MTS 6 BASES CON INTERRUPTOR DE CORTE", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 1650, totalPriceCentsExVat: 13200, vatCents: 2772, totalPriceCentsVatIncluded: 15972 },
  { sequence: 7, description: "ALARGADERA 5 MTS 4 BASES CON INTERRUPTOR DE CORTE", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 1851, totalPriceCentsExVat: 14808, vatCents: 3110, totalPriceCentsVatIncluded: 17918 },
  { sequence: 8, description: "ALARGADERA 5 MTS 6 BASES CON INTERRUPTOR DE CORTE", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 2100, totalPriceCentsExVat: 16800, vatCents: 3528, totalPriceCentsVatIncluded: 20328 },
  { sequence: 9, description: "ARMARIO PLAN DE EMERGENCIA TERMOPLÁSTICO PARA EXTERIOR", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 4767, totalPriceCentsExVat: 9534, vatCents: 2002, totalPriceCentsVatIncluded: 11536 },
  { sequence: 10, description: "ASIENTO INODORO UNIVERSAL EXTRA", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 1960, totalPriceCentsExVat: 3920, vatCents: 823, totalPriceCentsVatIncluded: 4743 },
  { sequence: 11, description: "BALIZAS GEOLOCALIZADAS HOMOLOGADAS DGT", estimatedAnnualConsumption: 3, totalContractUnits24Months: 6, unitPriceCentsExVat: 5224, totalPriceCentsExVat: 31344, vatCents: 6582, totalPriceCentsVatIncluded: 37926 },
  { sequence: 12, description: "BANDEJA PINTURA 360X285X75 NEGRA", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 345, totalPriceCentsExVat: 690, vatCents: 145, totalPriceCentsVatIncluded: 835 },
  { sequence: 13, description: "BARRA REPARADORA MULTIUSO", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 680, totalPriceCentsExVat: 1360, vatCents: 286, totalPriceCentsVatIncluded: 1646 },
  { sequence: 14, description: "BATERÍA LITIO 20V 4.0 A 7,5X11,7X6,3", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 5999, totalPriceCentsExVat: 23996, vatCents: 5039, totalPriceCentsVatIncluded: 29035 },
  { sequence: 15, description: "BOMBILLA LED DE BAJO CONSUMO Y ALTA EFICIENCIA E27 – 5W – 470LM – 5000K", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 525, totalPriceCentsExVat: 4200, vatCents: 882, totalPriceCentsVatIncluded: 5082 },
  { sequence: 16, description: "BOTIQUÍN DE PRIMEROS AUXILIOS TIPO MALETÍN (NORMATIVA RD 486/1997)", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 3062, totalPriceCentsExVat: 12248, vatCents: 2572, totalPriceCentsVatIncluded: 14820 },
  { sequence: 17, description: "BROCA MADERA 5MM", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 164, totalPriceCentsExVat: 656, vatCents: 138, totalPriceCentsVatIncluded: 794 },
  { sequence: 18, description: "BROCA PORCELANICO 6 MM EXTREME", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 940, totalPriceCentsExVat: 3760, vatCents: 790, totalPriceCentsVatIncluded: 4550 },
  { sequence: 19, description: "BROCA PORCELANICO 8 MM EXTREME", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1109, totalPriceCentsExVat: 4436, vatCents: 932, totalPriceCentsVatIncluded: 5368 },
  { sequence: 20, description: "BTV CERRADURA BUZÓN IMPERIO C/TUERCA", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 690, totalPriceCentsExVat: 2760, vatCents: 580, totalPriceCentsVatIncluded: 3340 },
  { sequence: 21, description: "CABLE HDMI MACHO/MACHO 4K 3MTS", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1177, totalPriceCentsExVat: 4708, vatCents: 989, totalPriceCentsVatIncluded: 5697 },
  { sequence: 22, description: "CABLE TIPO C M/H 2MTS", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 590, totalPriceCentsExVat: 4720, vatCents: 991, totalPriceCentsVatIncluded: 5711 },
  { sequence: 23, description: "CANAL 16X32MMX2M BLANCO CON CINTA AUTOADHESIVA", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 305, totalPriceCentsExVat: 18300, vatCents: 3843, totalPriceCentsVatIncluded: 22143 },
  { sequence: 24, description: "CANALETA DE SUELO SALVACABLES TRANSITABLE PARA INTERIOR Y EXTERIOR 2 CANALES, 970", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 3450, totalPriceCentsExVat: 27600, vatCents: 5796, totalPriceCentsVatIncluded: 33396 },
  { sequence: 25, description: "CANALETA SUELO SALVACABLES 18X75MMX2M", estimatedAnnualConsumption: 10, totalContractUnits24Months: 20, unitPriceCentsExVat: 1540, totalPriceCentsExVat: 30800, vatCents: 6468, totalPriceCentsVatIncluded: 37268 },
  { sequence: 26, description: "CANDADO TF20 O EQUIVALENTE", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 462, totalPriceCentsExVat: 3696, vatCents: 776, totalPriceCentsVatIncluded: 4472 },
  { sequence: 27, description: "CANDADO TF25 O EQUIVALENTE", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 581, totalPriceCentsExVat: 4648, vatCents: 976, totalPriceCentsVatIncluded: 5624 },
  { sequence: 28, description: "CARGADOR BATERÍA 60W", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 2999, totalPriceCentsExVat: 11996, vatCents: 2519, totalPriceCentsVatIncluded: 14515 },
  { sequence: 29, description: "CERROJO PASADOR CON LLAVE", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1977, totalPriceCentsExVat: 7908, vatCents: 1661, totalPriceCentsVatIncluded: 9569 },
  { sequence: 30, description: "CHALECO REFLECTANTE DE ALTA VISIBILIDAD HOMOLOGADO (CLASE 2, COLOR NARANJA/AMARIL)", estimatedAnnualConsumption: 20, totalContractUnits24Months: 40, unitPriceCentsExVat: 437, totalPriceCentsExVat: 17480, vatCents: 3671, totalPriceCentsVatIncluded: 21151 },
  { sequence: 31, description: "CIERRAPUERTA TESA S/MANETA O EQUIVALENTE", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 7185, totalPriceCentsExVat: 14370, vatCents: 3018, totalPriceCentsVatIncluded: 17388 },
  { sequence: 32, description: "CILINDRO CON LLAVE DE SEGURIDAD", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 2443, totalPriceCentsExVat: 4886, vatCents: 1026, totalPriceCentsVatIncluded: 5912 },
  { sequence: 33, description: "CILINDRO CON LLAVE DE SERRETA", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1291, totalPriceCentsExVat: 5164, vatCents: 1084, totalPriceCentsVatIncluded: 6248 },
  { sequence: 34, description: "CINTA ANTIDESLIZANTE 25MMX18M", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1233, totalPriceCentsExVat: 4932, vatCents: 1036, totalPriceCentsVatIncluded: 5968 },
  { sequence: 35, description: "CINTA ANTIDESLIZANTE 50MMX18M", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 2045, totalPriceCentsExVat: 8180, vatCents: 1718, totalPriceCentsVatIncluded: 9898 },
  { sequence: 36, description: "CINTA CARROCERO 36MMX45M", estimatedAnnualConsumption: 10, totalContractUnits24Months: 20, unitPriceCentsExVat: 226, totalPriceCentsExVat: 4520, vatCents: 949, totalPriceCentsVatIncluded: 5469 },
  { sequence: 37, description: "CINTA DE BALIZAMIENTO 50MMX50M", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 522, totalPriceCentsExVat: 1044, vatCents: 219, totalPriceCentsVatIncluded: 1263 },
  { sequence: 38, description: "CINTA DOBLE CARA 50MMX10M", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 780, totalPriceCentsExVat: 6240, vatCents: 1310, totalPriceCentsVatIncluded: 7550 },
  { sequence: 39, description: "CINTA DOBLE CARA DE ALTA RESISTENCIA (EXTRAFUERTE) TIPO (3M VHB 5952, TESA PRO MOUNT) O EQUIVALENTE", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 1931, totalPriceCentsExVat: 15448, vatCents: 3244, totalPriceCentsVatIncluded: 18692 },
  { sequence: 40, description: "CINTA VULCANIZABLE 19MMX10M", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 589, totalPriceCentsExVat: 2356, vatCents: 495, totalPriceCentsVatIncluded: 2851 },
  { sequence: 41, description: "COMPRESOR AIRE 20V", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 9287, totalPriceCentsExVat: 37148, vatCents: 7801, totalPriceCentsVatIncluded: 44949 },
  { sequence: 42, description: "DECAPANTE LACO FLUX 125GR O EQUIVALENTE", estimatedAnnualConsumption: 5, totalContractUnits24Months: 10, unitPriceCentsExVat: 784, totalPriceCentsExVat: 7840, vatCents: 1646, totalPriceCentsVatIncluded: 9486 },
  { sequence: 43, description: "DESATASCADOR PROFESIONAL 1L", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 532, totalPriceCentsExVat: 31920, vatCents: 6703, totalPriceCentsVatIncluded: 38623 },
  { sequence: 44, description: "DESINCRUSTANTE 5L", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 1590, totalPriceCentsExVat: 3180, vatCents: 668, totalPriceCentsVatIncluded: 3848 },
  { sequence: 45, description: "DISOLVENTE UNIVERSAL 1L", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 405, totalPriceCentsExVat: 810, vatCents: 170, totalPriceCentsVatIncluded: 980 },
  { sequence: 46, description: "ESCALERA 2 PELDAÑOS ANCHOS", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 3053, totalPriceCentsExVat: 6106, vatCents: 1282, totalPriceCentsVatIncluded: 7388 },
  { sequence: 47, description: "ESCALERA 5 PELDAÑOS ANCHOS", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 6036, totalPriceCentsExVat: 12072, vatCents: 2535, totalPriceCentsVatIncluded: 14607 },
  { sequence: 48, description: "ESCALERA 7 PELDAÑOS ANCHOS", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 8713, totalPriceCentsExVat: 17426, vatCents: 3659, totalPriceCentsVatIncluded: 21085 },
  { sequence: 49, description: "ESCUADRA METAL 25/25", estimatedAnnualConsumption: 8, totalContractUnits24Months: 16, unitPriceCentsExVat: 115, totalPriceCentsExVat: 1840, vatCents: 386, totalPriceCentsVatIncluded: 2226 },
  { sequence: 50, description: "FLEXOMETRO 5 MTS", estimatedAnnualConsumption: 3, totalContractUnits24Months: 6, unitPriceCentsExVat: 450, totalPriceCentsExVat: 2700, vatCents: 567, totalPriceCentsVatIncluded: 3267 },
  { sequence: 51, description: "GRIFOS MONOMANDOS LAVABO", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 4159, totalPriceCentsExVat: 16636, vatCents: 3494, totalPriceCentsVatIncluded: 20130 },
  { sequence: 52, description: "GUANTES DE LATEX (CAJA 100 UDS)", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 899, totalPriceCentsExVat: 3596, vatCents: 755, totalPriceCentsVatIncluded: 4351 },
  { sequence: 53, description: "HUMIDIFICADOR DE ULTRASONIDO 4,5L", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 3675, totalPriceCentsExVat: 7350, vatCents: 1544, totalPriceCentsVatIncluded: 8894 },
  { sequence: 54, description: "JUEGO MANIVELA CUADRADA 170X170 85MM", estimatedAnnualConsumption: 3, totalContractUnits24Months: 6, unitPriceCentsExVat: 1767, totalPriceCentsExVat: 10602, vatCents: 2226, totalPriceCentsVatIncluded: 12828 },
  { sequence: 55, description: "KIT LIMPIEZA GAFAS VR UNIVERSAL 30ML", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 1249, totalPriceCentsExVat: 9992, vatCents: 2098, totalPriceCentsVatIncluded: 12090 },
  { sequence: 56, description: "LA CAJA DE LLAVES DE EMERGENCIA HMF 1021-03", estimatedAnnualConsumption: 12, totalContractUnits24Months: 24, unitPriceCentsExVat: 1760, totalPriceCentsExVat: 42240, vatCents: 8870, totalPriceCentsVatIncluded: 51110 },
  { sequence: 57, description: "LLAVE DE SEGURIDAD (T10, AMG 10D LIN19D, T60 INTHER LATON) O EQUIVALENTE", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 561, totalPriceCentsExVat: 2244, vatCents: 471, totalPriceCentsVatIncluded: 2715 },
  { sequence: 58, description: "LLAVE SERRETA (CAY1D, JIS1D, LIN25D, TE28, U5D) O EQUIVALENTE", estimatedAnnualConsumption: 20, totalContractUnits24Months: 40, unitPriceCentsExVat: 237, totalPriceCentsExVat: 9480, vatCents: 1991, totalPriceCentsVatIncluded: 11471 },
  { sequence: 59, description: "LLAVERO PLÁSTICO", estimatedAnnualConsumption: 8, totalContractUnits24Months: 16, unitPriceCentsExVat: 27, totalPriceCentsExVat: 432, vatCents: 91, totalPriceCentsVatIncluded: 523 },
  { sequence: 60, description: "MANETA DE PUERTA", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1473, totalPriceCentsExVat: 5892, vatCents: 1237, totalPriceCentsVatIncluded: 7129 },
  { sequence: 61, description: "MANGUITOS CONEXIÓN H/H", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 192, totalPriceCentsExVat: 1536, vatCents: 323, totalPriceCentsVatIncluded: 1859 },
  { sequence: 62, description: "METROS DE MANGUERA AGUA ½", estimatedAnnualConsumption: 10, totalContractUnits24Months: 20, unitPriceCentsExVat: 126, totalPriceCentsExVat: 2520, vatCents: 529, totalPriceCentsVatIncluded: 3049 },
  { sequence: 63, description: "NIVELADOR REGULACIÓN INTERIOR M10X70MM", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 223, totalPriceCentsExVat: 13380, vatCents: 2810, totalPriceCentsVatIncluded: 16190 },
  { sequence: 64, description: "NIVELADOR REGULACIÓN INTERIOR M12X70MM", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 262, totalPriceCentsExVat: 15720, vatCents: 3301, totalPriceCentsVatIncluded: 19021 },
  { sequence: 65, description: "NIVELADOR REGULACIÓN INTERIOR M8X70MM", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 209, totalPriceCentsExVat: 12540, vatCents: 2633, totalPriceCentsVatIncluded: 15173 },
  { sequence: 66, description: "PASADOR (PUERTAS Y VENTANAS) 100MM", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 449, totalPriceCentsExVat: 1796, vatCents: 377, totalPriceCentsVatIncluded: 2173 },
  { sequence: 67, description: "PASADOR (PUERTAS Y VENTANAS) 50MM", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 303, totalPriceCentsExVat: 2424, vatCents: 509, totalPriceCentsVatIncluded: 2933 },
  { sequence: 68, description: "PATA NIVELADORA M10 (LONGITUD DEL TORNILLO A DETERMINAR ENTRE 27 Y 70 MM)", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 324, totalPriceCentsExVat: 19440, vatCents: 4082, totalPriceCentsVatIncluded: 23522 },
  { sequence: 69, description: "PATA NIVELADORA M12 (LONGITUD DEL TORNILLO A DETERMINAR ENTRE 27 Y 70 MM)", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 370, totalPriceCentsExVat: 22200, vatCents: 4662, totalPriceCentsVatIncluded: 26862 },
  { sequence: 70, description: "PATA NIVELADORA M6 (LONGITUD DEL TORNILLO A DETERMINAR ENTRE 27 Y 70 MM)", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 254, totalPriceCentsExVat: 15240, vatCents: 3200, totalPriceCentsVatIncluded: 18440 },
  { sequence: 71, description: "PATA NIVELADORA M8 (LONGITUD DEL TORNILLO A DETERMINAR ENTRE 27 Y 70 MM)", estimatedAnnualConsumption: 30, totalContractUnits24Months: 60, unitPriceCentsExVat: 296, totalPriceCentsExVat: 17760, vatCents: 3730, totalPriceCentsVatIncluded: 21490 },
  { sequence: 72, description: "PELÍCULA PROTECTORA 20M2", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 674, totalPriceCentsExVat: 2696, vatCents: 566, totalPriceCentsVatIncluded: 3262 },
  { sequence: 73, description: "PILAS TIPO LR44 (CAJA 10X2)", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 454, totalPriceCentsExVat: 908, vatCents: 191, totalPriceCentsVatIncluded: 1099 },
  { sequence: 74, description: "PILAS TIPO MN21 (CAJA 10X2)", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 638, totalPriceCentsExVat: 1276, vatCents: 268, totalPriceCentsVatIncluded: 1544 },
  { sequence: 75, description: "PINTURA - CUBO CON REJILLA PINTURA 16L", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 873, totalPriceCentsExVat: 1746, vatCents: 367, totalPriceCentsVatIncluded: 2113 },
  { sequence: 76, description: "PINTURA - PALETINA TRIPLE 40MM ESPECIAL", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 312, totalPriceCentsExVat: 2496, vatCents: 524, totalPriceCentsVatIncluded: 3020 },
  { sequence: 77, description: "PINTURA - RODILLO POLIAMIDA 180MM", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 517, totalPriceCentsExVat: 2068, vatCents: 434, totalPriceCentsVatIncluded: 2502 },
  { sequence: 78, description: "PINTURA - PÉRTIGA 2M", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 824, totalPriceCentsExVat: 1648, vatCents: 346, totalPriceCentsVatIncluded: 1994 },
  { sequence: 79, description: "PINTURA PLÁSTICA BLANCA MATE 15L", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 4291, totalPriceCentsExVat: 17164, vatCents: 3604, totalPriceCentsVatIncluded: 20768 },
  { sequence: 80, description: "PORTAETIQUETAS PLÁSTICO", estimatedAnnualConsumption: 3, totalContractUnits24Months: 6, unitPriceCentsExVat: 42, totalPriceCentsExVat: 252, vatCents: 53, totalPriceCentsVatIncluded: 305 },
  { sequence: 81, description: "PULSADOR ESTANCO", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 644, totalPriceCentsExVat: 2576, vatCents: 541, totalPriceCentsVatIncluded: 3117 },
  { sequence: 82, description: "PULSADOR UNIVERSAL DOBLE DESCARGA POR CABLE O EQUIVALENTE", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1564, totalPriceCentsExVat: 6256, vatCents: 1314, totalPriceCentsVatIncluded: 7570 },
  { sequence: 83, description: "REJILLA DESAG URIN MURAL", estimatedAnnualConsumption: 15, totalContractUnits24Months: 30, unitPriceCentsExVat: 1141, totalPriceCentsExVat: 34230, vatCents: 7188, totalPriceCentsVatIncluded: 41418 },
  { sequence: 84, description: "RUEDA PJP 125X32 (R00010)", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 1766, totalPriceCentsExVat: 14128, vatCents: 2967, totalPriceCentsVatIncluded: 17095 },
  { sequence: 85, description: "SEÑAL DE EVACUACIÓN/EMERGENCIA CUADRADA FOTOLUMINISCENTE CLASE B - 210X210 MM", estimatedAnnualConsumption: 10, totalContractUnits24Months: 20, unitPriceCentsExVat: 406, totalPriceCentsExVat: 8120, vatCents: 1705, totalPriceCentsVatIncluded: 9825 },
  { sequence: 86, description: "SEÑAL DE EVACUACIÓN/EMERGENCIA CUADRADA FOTOLUMINISCENTE CLASE B - 420X420 MM", estimatedAnnualConsumption: 6, totalContractUnits24Months: 12, unitPriceCentsExVat: 813, totalPriceCentsExVat: 9756, vatCents: 2049, totalPriceCentsVatIncluded: 11805 },
  { sequence: 87, description: "SEÑAL DE EVACUACIÓN/EMERGENCIA RECTANGULAR FOTOLUMINISCENTE CLASE B - 640X320 MM", estimatedAnnualConsumption: 6, totalContractUnits24Months: 12, unitPriceCentsExVat: 1350, totalPriceCentsExVat: 16200, vatCents: 3402, totalPriceCentsVatIncluded: 19602 },
  { sequence: 88, description: "SEÑAL DE EVACUACIÓN/EMERGENCIA RECTANGULAR FOTOLUMINISCENTE CLASE B - 320X160 MM", estimatedAnnualConsumption: 10, totalContractUnits24Months: 20, unitPriceCentsExVat: 484, totalPriceCentsExVat: 9680, vatCents: 2033, totalPriceCentsVatIncluded: 11713 },
  { sequence: 89, description: "SEPIOLITA 1530 (SACO 20 KG)", estimatedAnnualConsumption: 5, totalContractUnits24Months: 10, unitPriceCentsExVat: 1201, totalPriceCentsExVat: 12010, vatCents: 2522, totalPriceCentsVatIncluded: 14532 },
  { sequence: 90, description: "SILICONA ADHESIVO 290ML BLANCO O TRANSPARENTE", estimatedAnnualConsumption: 6, totalContractUnits24Months: 12, unitPriceCentsExVat: 550, totalPriceCentsExVat: 6600, vatCents: 1386, totalPriceCentsVatIncluded: 7986 },
  { sequence: 91, description: "SOPORTE TV FIJO 19\"- 40\" 25KG", estimatedAnnualConsumption: 2, totalContractUnits24Months: 4, unitPriceCentsExVat: 1942, totalPriceCentsExVat: 7768, vatCents: 1631, totalPriceCentsVatIncluded: 9399 },
  { sequence: 92, description: "TACO GRIS NYLON 6X30 MM FISCHER DUOPOWER (100 UDS) O EQUIVALENTE", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 620, totalPriceCentsExVat: 1240, vatCents: 260, totalPriceCentsVatIncluded: 1500 },
  { sequence: 93, description: "TACO GRIS NYLON 8X40 MM FISCHER DUOPOWER (120 UDS) O EQUIVALENTE", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 895, totalPriceCentsExVat: 1790, vatCents: 376, totalPriceCentsVatIncluded: 2166 },
  { sequence: 94, description: "TALADRO PERCUTOR 2 BATERIAS 18V", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 14177, totalPriceCentsExVat: 28354, vatCents: 5954, totalPriceCentsVatIncluded: 34308 },
  { sequence: 95, description: "TIERRA MANTILLO ORGÁNICO (SACO 50 L)", estimatedAnnualConsumption: 5, totalContractUnits24Months: 10, unitPriceCentsExVat: 677, totalPriceCentsExVat: 6770, vatCents: 1422, totalPriceCentsVatIncluded: 8192 },
  { sequence: 96, description: "TOPE RETENEDOR GIRAT. ADH/TOR INV/BLCO", estimatedAnnualConsumption: 1, totalContractUnits24Months: 2, unitPriceCentsExVat: 369, totalPriceCentsExVat: 738, vatCents: 155, totalPriceCentsVatIncluded: 893 },
  { sequence: 97, description: "TUBO ADHESIVO SELLADOR MULTIUSOS BLANCO O GRIS", estimatedAnnualConsumption: 4, totalContractUnits24Months: 8, unitPriceCentsExVat: 614, totalPriceCentsExVat: 4912, vatCents: 1032, totalPriceCentsVatIncluded: 5944 },
  { sequence: 98, description: "ZOTAL DESINFECTANTE LATA 870 ML", estimatedAnnualConsumption: 12, totalContractUnits24Months: 24, unitPriceCentsExVat: 1050, totalPriceCentsExVat: 25200, vatCents: 5292, totalPriceCentsVatIncluded: 30492 },
] as const;

export const FERRETERIA_SOURCE_DECLARED_CATALOG_TOTALS = {
  pblExVatCents: 1_055_244,
  vatCents: 221_601,
  pblVatIncludedCents: 1_276_845,
  sumOfRoundedRowVatCents: FERRETERIA_CANONICAL_CATALOG_98.reduce((sum, item) => sum + item.vatCents, 0),
  sumOfRoundedRowVatIncludedCents: FERRETERIA_CANONICAL_CATALOG_98.reduce((sum, item) => sum + item.totalPriceCentsVatIncluded, 0),
} as const;

export function evaluateFerreteriaCanonicalCatalogSourceData() {
  const structural = validateFerreteriaCanonicalCatalog(FERRETERIA_CANONICAL_CATALOG_98);
  const blockers = [...structural.blockers];
  if (FERRETERIA_SOURCE_DECLARED_CATALOG_TOTALS.pblExVatCents !== structural.totalExVatCents) blockers.push("El PBL sin IVA no coincide con la suma de las 98 filas.");
  return {
    ready: blockers.length === 0,
    blockers,
    itemCount: structural.itemCount,
    totalExVatCents: structural.totalExVatCents,
    declaredAggregateVatCents: FERRETERIA_SOURCE_DECLARED_CATALOG_TOTALS.vatCents,
    rowRoundedVatCents: FERRETERIA_SOURCE_DECLARED_CATALOG_TOTALS.sumOfRoundedRowVatCents,
    preservedAggregateRoundingDifferenceCents: FERRETERIA_SOURCE_DECLARED_CATALOG_TOTALS.vatCents - FERRETERIA_SOURCE_DECLARED_CATALOG_TOTALS.sumOfRoundedRowVatCents,
  } as const;
}
