export const UNIVERSAL_V1_JOURNEY_UI = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Contrata-IA · Expediente universal V1</title>
<style>body{font-family:Arial,sans-serif;margin:0;background:#f4f6f7;color:#17202a}header{background:#fff;border-bottom:1px solid #ddd;padding:18px}main{max-width:1120px;margin:22px auto;padding:0 16px}.card{background:#fff;border:1px solid #ddd;border-radius:8px;padding:18px;margin-bottom:14px}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}button{border:0;border-radius:5px;padding:10px 14px;background:#176b45;color:#fff;cursor:pointer}button.secondary{background:#566573}input,textarea,select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #bbb;border-radius:4px}textarea{min-height:90px}.field{border-top:1px solid #eee;padding:12px 0}.state{font-weight:bold}.SOURCE_CONFLICT{color:#a93226}.HUMAN_VALIDATED{color:#176b45}.SOURCE_DECLARED{color:#b9770e}.muted{color:#626567}.warning{background:#fff3cd;padding:10px;border-radius:4px}.ok{background:#e9f7ef;padding:10px;border-radius:4px}@media(max-width:760px){.grid{grid-template-columns:1fr}.toolbar button{width:100%}}</style></head>
<body><header><strong>Contrata-IA</strong> · Expediente universal V1</header><main>
<div class="card"><h2>Expediente</h2><div class="grid"><div><label>Identificador</label><input id="caseId" placeholder="CONTR/2026/240267"></div><div><label>Credencial</label><input id="token" type="password" autocomplete="off"></div></div><div class="toolbar" style="margin-top:10px"><button id="load">Abrir evidencia</button><button id="readiness" class="secondary">Comprobar preparación</button><button id="generate" class="secondary">Generar paquete universal</button></div><p id="status" class="muted">El sistema mostrará valores, procedencia y estado de validación; un conflicto nunca se resuelve automáticamente.</p></div>
<div class="card"><h2>Datos, fuentes y validación</h2><div id="fields" class="muted">Abra un expediente.</div></div>
<div class="card"><h2>Puerta de producción</h2><pre id="gate" style="white-space:pre-wrap">Sin comprobar.</pre></div>
</main><script>
const manifest=${JSON.stringify([])};
let definitions=[];
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const headers=()=>{const t=document.getElementById('token').value.trim();return {'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})};};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});const data=await r.json().catch(()=>({error:'Respuesta no JSON'}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));return data;}
function editor(def,field){const value=field?.value??''; if(def.control==='BOOLEAN')return '<select data-value><option value="true" '+(value===true?'selected':'')+'>Sí</option><option value="false" '+(value===false?'selected':'')+'>No</option></select>'; if(def.control==='TEXTAREA'||def.control==='TABLE')return '<textarea data-value>'+esc(typeof value==='string'?value:JSON.stringify(value,null,2))+'</textarea>'; return '<input data-value value="'+esc(value)+'">';}
function parse(def,raw){if(def.control==='BOOLEAN')return raw==='true';if(def.control==='INTEGER'||def.control==='MONEY_CENTS'){const n=Number(raw);if(!Number.isFinite(n))throw new Error('Número inválido');return n;}if(def.control==='TABLE'){try{return JSON.parse(raw)}catch{return raw.split('\n').map(x=>x.trim()).filter(Boolean)}}return raw;}
async function load(){const id=document.getElementById('caseId').value.trim();if(!id)throw new Error('Indique expediente.');const data=await api('/api/universal/manifest');definitions=data.fields;const record=await api('/api/universal/cases/'+encodeURIComponent(id)+'/evidence');const box=document.getElementById('fields');box.innerHTML='';for(const def of definitions){const f=record.fields?.[def.fieldPath];const div=document.createElement('div');div.className='field';div.dataset.path=def.fieldPath;div.innerHTML='<div><strong>'+esc(def.label)+'</strong> <span class="state '+esc(f?.status||'PENDING')+'">'+esc(f?.status||'PENDING')+'</span></div><div class="muted">'+esc(def.fieldPath)+(def.help?' · '+esc(def.help):'')+'</div>'+editor(def,f)+'<div class="toolbar" style="margin-top:7px"><button data-save>Guardar declaración</button><button data-validate class="secondary">Validar humanamente</button></div><div class="muted">Fuentes: '+esc((f?.sources||[]).map(s=>s.sourceId).join(', ')||'sin fuente registrada')+'</div>';box.appendChild(div);}document.getElementById('status').textContent='Expediente abierto. Los cambios se guardan como SOURCE_DECLARED hasta revisión.';}
document.getElementById('fields').addEventListener('click',async e=>{const btn=e.target.closest('button');if(!btn)return;const row=btn.closest('.field');const path=row.dataset.path;const def=definitions.find(x=>x.fieldPath===path);const id=document.getElementById('caseId').value.trim();try{if(btn.hasAttribute('data-save')){const raw=row.querySelector('[data-value]').value;await api('/api/universal/cases/'+encodeURIComponent(id)+'/evidence/'+encodeURIComponent(path),{method:'PUT',body:JSON.stringify({value:parse(def,raw)})});}else if(btn.hasAttribute('data-validate')){await api('/api/universal/cases/'+encodeURIComponent(id)+'/evidence/'+encodeURIComponent(path)+'/validate',{method:'POST',body:'{}'});}await load();}catch(err){alert(err.message);}});
document.getElementById('load').onclick=()=>load().catch(e=>alert(e.message));
document.getElementById('readiness').onclick=async()=>{try{const id=document.getElementById('caseId').value.trim();const r=await api('/api/universal/cases/'+encodeURIComponent(id)+'/production-readiness');document.getElementById('gate').textContent=JSON.stringify(r,null,2);document.getElementById('gate').className=r.ready?'ok':'warning';}catch(e){alert(e.message)}};
document.getElementById('generate').onclick=async()=>{try{const id=document.getElementById('caseId').value.trim();const r=await api('/api/universal/cases/'+encodeURIComponent(id)+'/generate',{method:'POST',body:'{}'});document.getElementById('gate').textContent=JSON.stringify(r,null,2);}catch(e){alert(e.message)}};
</script></body></html>`;
