import { UNIVERSAL_V1_JOURNEY_SCRIPT } from "./UniversalV1JourneyScript";

export const UNIVERSAL_V1_JOURNEY_UI = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Contrata-IA · Tramitación de expediente</title>
<style>body{font-family:Arial,sans-serif;margin:0;background:#f4f6f7;color:#17202a}header{background:#fff;border-bottom:1px solid #ddd;padding:18px}main{max-width:1120px;margin:22px auto;padding:0 16px}.card{background:#fff;border:1px solid #ddd;border-radius:8px;padding:18px;margin-bottom:14px}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}button{border:0;border-radius:5px;padding:10px 14px;background:#176b45;color:#fff;cursor:pointer}button.secondary{background:#566573}input,textarea,select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #bbb;border-radius:4px}textarea{min-height:90px}.field{border-top:1px solid #eee;padding:12px 0}.state{font-weight:bold}.SOURCE_CONFLICT{color:#a93226}.HUMAN_VALIDATED{color:#176b45}.SOURCE_DECLARED{color:#b9770e}.muted{color:#626567}.warning{background:#fff3cd;padding:10px;border-radius:4px}.ok{background:#e9f7ef;padding:10px;border-radius:4px}@media(max-width:760px){.grid{grid-template-columns:1fr}.toolbar button{width:100%}}</style></head>
<body><header><strong>Contrata-IA</strong> · Tramitación y revisión del expediente</header><main>
<div class="card"><h2>Expediente</h2><div class="grid"><div><label>Identificador</label><input id="caseId" placeholder="CONTR/2026/240267"></div><div><label>Credencial</label><input id="token" type="password" autocomplete="off"></div></div><div class="toolbar" style="margin-top:10px"><button id="load" type="button">Abrir expediente</button><button id="readiness" type="button" class="secondary">Comprobar preparación documental</button><button id="generate" type="button" class="secondary">Generar y descargar PCAP + Memoria + PPT</button></div><p id="status" class="muted">Cargando interfaz…</p></div>
<div class="card"><h2>Progreso del contrato de suministro</h2><div id="supplyProgress" class="muted">Abra un expediente para evaluar su progreso.</div></div>
<div class="card"><h2>Datos, fuentes y validación</h2><p class="muted">Cada dato se conserva con su procedencia y estado. Un conflicto requiere decisión humana y nunca se resuelve automáticamente.</p><div id="fields" class="muted">Abra un expediente.</div></div>
<div class="card"><h2>Preparación documental</h2><pre id="gate" style="white-space:pre-wrap">Sin comprobar. La generación solo se habilita cuando existan activos editables acreditados para el paquete correspondiente.</pre></div>
</main><script>${UNIVERSAL_V1_JOURNEY_SCRIPT}</script></body></html>`;
