export const LB103_AUTHORITATIVE_GENERATION_SCRIPT = `"use strict";
(function(){
var CASE_KEY="contrataIaAdaptiveCaseId";
var panelId="lb103AuthoritativeGenerationPanel";
var lastPreflight=null;
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function caseId(){return localStorage.getItem(CASE_KEY)||"";}
async function json(url,options){var response=await fetch(url,Object.assign({credentials:"same-origin",headers:{"content-type":"application/json"}},options||{}));var data=await response.json().catch(function(){return {};});if(!response.ok)throw new Error(data.error||"No se pudo completar la operación.");return data;}
async function preflight(){var id=caseId();if(!id)return null;return json("/api/adaptive/cases/"+encodeURIComponent(id)+"/lb103-preflight",{method:"GET"});}
function ensurePanel(){var main=document.querySelector("main");if(!main)return null;var panel=document.getElementById(panelId);if(!panel){panel=document.createElement("div");panel.id=panelId;main.appendChild(panel);}return panel;}
function euros(raw){var text=String(raw).trim();if(!/^(?:\\d{1,3}(?:\\.\\d{3})+|\\d+)(?:,\\d{1,2})?$/.test(text))throw new Error("Use euros en formato español, por ejemplo 1.234,56.");var pieces=text.replaceAll(".","").split(",");var cents=Number(pieces[0])*100+Number((pieces[1]||"").padEnd(2,"0"));if(!Number.isSafeInteger(cents))throw new Error("Importe fuera de rango.");return cents;}
function amount(v){return typeof v==="number"?(v/100).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}):"";}
var tableColumns={
 "criteria.awardCriteria":[["nombre","Criterio","text"],["ponderacion","Ponderación (%)","number"],["evaluableMedianteFormula","Evaluable mediante fórmula","boolean"]],
 "economic.annualityBudgetRows":[["year","Año","number"],["amountCents","Importe con IVA (€)","money"],["budgetApplication","Aplicación presupuestaria","text"]],
 "lots.lots":[["id","Número de lote","text"],["description","Descripción","text"]],
 "economic.unitPrices":[["reference","Referencia","text"],["description","Descripción","text"],["unitPriceCents","Precio unitario (€)","money"]]
};
function control(type,value,key){if(type==="boolean")return '<select data-key="'+esc(key)+'"><option value="">Seleccione</option><option value="true" '+(value===true?'selected':'')+'>Sí</option><option value="false" '+(value===false?'selected':'')+'>No</option></select>';return '<input data-key="'+esc(key)+'" value="'+esc(type==="money"?amount(value):(value==null?"":value))+'"'+(type==="number"?' type="number" min="0"':'')+'>';}
function rowHtml(cols,value){return '<div data-row class="grid">'+cols.map(function(c){return '<label>'+esc(c[1])+control(c[2],value&&value[c[0]],c[0])+'</label>';}).join("")+'<button type="button" data-remove>Eliminar fila</button></div>';}
function editor(f){var v=f.value;if(f.fieldPath==="execution.plannedModificationRegime"){return [ ["budgetStability","Estabilidad presupuestaria"],["needsDa33","Mayores necesidades"],["other","Otras causas"] ].map(function(pair){var x=v&&typeof v==="object"?v[pair[0]]||{}:{};return '<fieldset data-cause="'+pair[0]+'"><legend>'+pair[1]+'</legend><label>¿Se prevé esta causa?'+control("boolean",x.applicable,"applicable")+'</label><label>Porcentaje máximo'+control("number",x.maximumPercent,"maximumPercent")+'</label>'+(pair[0]!=="budgetStability"?'<label>Límites (uno por línea)<textarea data-key="limits">'+esc((x.limits||[]).join(String.fromCharCode(10)))+'</textarea></label>':'')+(pair[0]==="other"?'<label>Descripción<textarea data-key="description">'+esc(x.description||"")+'</textarea></label>':'')+'</fieldset>';}).join("");}
if(f.control==="TABLE"){var cols=tableColumns[f.fieldPath];if(cols)return '<div data-rows>'+((Array.isArray(v)&&v.length)?v:[{}]).map(function(row){return rowHtml(cols,row);}).join("")+'</div><button type="button" id="lb103AddRow">Añadir fila</button>';return '<label>Una entrada por línea<textarea id="lb103DocumentValue">'+esc(Array.isArray(v)?v.join(String.fromCharCode(10)):v||"")+'</textarea></label>';}
if(f.control==="BOOLEAN")return control("boolean",v,"value");if(f.options)return '<select id="lb103DocumentValue"><option value="">Seleccione</option>'+f.options.map(function(o){return '<option '+(v===o?'selected':'')+'>'+esc(o)+'</option>';}).join("")+'</select>';return '<textarea id="lb103DocumentValue">'+esc(f.control==="MONEY_CENTS"?amount(v):v==null?"":v)+'</textarea>'+(f.control==="MONEY_CENTS"?'<p>Importe en euros, con coma decimal.</p>':'');}
function parsed(type,raw){if(type==="boolean"){if(raw!=="true"&&raw!=="false")throw new Error("Seleccione Sí o No.");return raw==="true";}if(type==="money")return euros(raw);if(type==="number"){if(!String(raw).trim()||!Number.isSafeInteger(Number(raw))||Number(raw)<0)throw new Error("Introduzca un entero no negativo.");return Number(raw);}if(!String(raw).trim())throw new Error("Complete el texto.");return String(raw).trim();}
function readDocument(f,panel){if(f.fieldPath==="execution.plannedModificationRegime"){var result={};panel.querySelectorAll("[data-cause]").forEach(function(group){var active=parsed("boolean",group.querySelector('[data-key="applicable"]').value);var max=active?parsed("number",group.querySelector('[data-key="maximumPercent"]').value):0;if(max>20)throw new Error("El porcentaje excede el máximo admitido por este modelo.");var item={applicable:active,maximumPercent:max};if(group.dataset.cause!=="budgetStability"){var raw=group.querySelector('[data-key="limits"]').value;item.limits=raw.split(String.fromCharCode(10)).map(function(x){return x.trim();}).filter(Boolean);if(active&&!item.limits.length)throw new Error("Indique los límites de la modificación.");}if(group.dataset.cause==="other")item.description=group.querySelector('[data-key="description"]').value.trim();result[group.dataset.cause]=item;});return result;}
var cols=tableColumns[f.fieldPath];if(cols){return Array.from(panel.querySelectorAll("[data-row]")).map(function(row){var obj={};cols.forEach(function(c){obj[c[0]]=parsed(c[2],row.querySelector('[data-key="'+c[0]+'"]').value);});if(f.fieldPath==="economic.annualityBudgetRows")obj.vatIncluded=true;return obj;});}
var el=panel.querySelector('#lb103DocumentValue')||panel.querySelector('[data-key="value"]');if(f.control==="TABLE")return el.value.split(String.fromCharCode(10)).map(function(x){return x.trim();}).filter(Boolean);return parsed(f.control==="MONEY_CENTS"?"money":f.control==="INTEGER"?"number":f.control==="BOOLEAN"?"boolean":"text",el.value);}
function render(result){var panel=ensurePanel();if(!panel)return;lastPreflight=result;if(!result||!result.snapshotReady||!result.snapshot||!result.documentarySelection||!result.packageReady){panel.innerHTML="";return;}
var completion=result.completion;var pending=completion&&completion.fields.filter(function(f){return !f.ready;});if(pending&&pending.length){var f=pending[0];if(f.status==="SOURCE_CONFLICT"){panel.innerHTML='<div class="card warning"><h2>Conflicto pendiente</h2><p>'+esc(f.label)+': revise y resuelva la discrepancia de fuentes antes de continuar.</p></div>';return;}panel.innerHTML='<div class="card"><h2>Completar documentos</h2><p>Decisiones iniciales registradas. Quedan '+pending.length+' datos documentales por completar o validar.</p><h3>'+esc(f.label)+'</h3><p>'+esc(f.help||"")+'</p>'+editor(f)+'<button id="lb103SaveDocument" type="button">Guardar y validar esta respuesta</button><p id="lb103GenerationStatus" role="status"></p></div>';var add=document.getElementById("lb103AddRow");if(add)add.onclick=function(){panel.querySelector('[data-rows]').insertAdjacentHTML('beforeend',rowHtml(tableColumns[f.fieldPath],{}));};panel.onclick=function(event){if(event.target.hasAttribute('data-remove'))event.target.closest('[data-row]').remove();};document.getElementById("lb103SaveDocument").onclick=async function(){var button=this;var status=document.getElementById("lb103GenerationStatus");button.disabled=true;try{var value=readDocument(f,panel);var root="/api/adaptive/cases/"+encodeURIComponent(caseId())+"/universal-evidence";await json(root,{method:"PUT",body:JSON.stringify({fieldPath:f.fieldPath,value:value})});await json(root+"/validate",{method:"POST",body:JSON.stringify({fieldPath:f.fieldPath})});await refresh();}catch(error){status.textContent=error.message;button.disabled=false;}};return;}
panel.innerHTML='<div class="card"><h2>Generación documental</h2><p>Los datos documentales están completos y validados. Revise las decisiones antes de descargar.</p><button id="lb103GeneratePackage" type="button">Generar Memoria + PCAP + PPT</button><p id="lb103GenerationStatus" class="muted">La aceptación humana final seguirá siendo obligatoria.</p></div>';var button=document.getElementById("lb103GeneratePackage");if(button)button.onclick=generate;}
async function refresh(){try{render(await preflight());}catch(error){var panel=ensurePanel();if(panel)panel.innerHTML='<div class="card warning"><strong>Generación no disponible.</strong> '+esc(error.message)+'</div>';}}
async function generate(){var id=caseId();var status=document.getElementById("lb103GenerationStatus");try{if(!id||!lastPreflight||!lastPreflight.snapshot||!lastPreflight.documentarySelection)throw new Error("Vuelva a ejecutar el preflight antes de generar.");if(status)status.textContent="Reconstruyendo y comprobando los sellos en el servidor...";var response=await fetch("/api/adaptive/cases/"+encodeURIComponent(id)+"/lb103-generate",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify({snapshotSha256:lastPreflight.snapshot.sha256,documentarySelectionSha256:lastPreflight.documentarySelection.sha256})});if(!response.ok){var data=await response.json().catch(function(){return {};});throw new Error(data.error||(Array.isArray(data.blockers)?data.blockers.join(" "):"La generación ha sido rechazada por el servidor."));}var blob=await response.blob();var disposition=response.headers.get("content-disposition")||"";var match=/filename=\"([^\"]+)\"/.exec(disposition);var fileName=match&&match[1]?match[1]:"Contrata-IA_PCAP-Memoria-PPT.zip";var url=URL.createObjectURL(blob);var link=document.createElement("a");link.href=url;link.download=fileName;document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);if(status)status.textContent="Paquete generado. Continúa pendiente de aceptación humana final.";await refresh();}catch(error){if(status){status.className="warning";status.textContent=error.message;}else alert(error.message);}}
document.addEventListener("DOMContentLoaded",function(){setTimeout(refresh,250);});
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(refresh,100);});
})();`;
