export const LB103_AUTHORITATIVE_GENERATION_SCRIPT = `"use strict";
(function(){
var CASE_KEY="contrataIaAdaptiveCaseId";
var panelId="lb103AuthoritativeGenerationPanel";
var lastPreflight=null;
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function caseId(){return localStorage.getItem(CASE_KEY)||"";}
async function json(url,options){var response=await fetch(url,Object.assign({credentials:"same-origin",headers:{"content-type":"application/json"}},options||{}));var data=await response.json().catch(function(){return {};});if(!response.ok)throw new Error(data.error||"No se pudo completar la operación.");return data;}
async function preflight(){var id=caseId();if(!id)return null;return json("/api/adaptive/cases/"+encodeURIComponent(id)+"/lb103-preflight",{method:"GET"});}
function ensurePanel(){var main=document.querySelector("main");if(!main)return null;var panel=document.getElementById(panelId);if(!panel){panel=document.createElement("div");panel.id=panelId;main.appendChild(panel);}return panel;}
function render(result){var panel=ensurePanel();if(!panel)return;lastPreflight=result;if(!result||!result.snapshotReady||!result.snapshot||!result.documentarySelection||!result.packageReady){panel.innerHTML="";return;}var snapshot=result.snapshot.sha256;var selection=result.documentarySelection.sha256;panel.innerHTML='<div class="card"><h2>Generación documental</h2><p>El servidor ha validado el expediente y la terna documental compatible. La generación utilizará exclusivamente este estado sellado.</p><div class="info"><strong>Sello del expediente</strong><br><code>'+esc(snapshot)+'</code><br><strong>Sello de la selección documental</strong><br><code>'+esc(selection)+'</code></div><button id="lb103GeneratePackage" type="button">Generar Memoria + PCAP + PPT</button><p id="lb103GenerationStatus" class="muted">La aceptación humana final seguirá siendo obligatoria.</p></div>';var button=document.getElementById("lb103GeneratePackage");if(button)button.onclick=generate;}
async function refresh(){try{render(await preflight());}catch(error){var panel=ensurePanel();if(panel)panel.innerHTML='<div class="card warning"><strong>Generación no disponible.</strong> '+esc(error.message)+'</div>';}}
async function generate(){var id=caseId();var status=document.getElementById("lb103GenerationStatus");try{if(!id||!lastPreflight||!lastPreflight.snapshot||!lastPreflight.documentarySelection)throw new Error("Vuelva a ejecutar el preflight antes de generar.");if(status)status.textContent="Reconstruyendo y comprobando los sellos en el servidor...";var response=await fetch("/api/adaptive/cases/"+encodeURIComponent(id)+"/lb103-generate",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify({snapshotSha256:lastPreflight.snapshot.sha256,documentarySelectionSha256:lastPreflight.documentarySelection.sha256})});if(!response.ok){var data=await response.json().catch(function(){return {};});throw new Error(data.error||(Array.isArray(data.blockers)?data.blockers.join(" "):"La generación ha sido rechazada por el servidor."));}var blob=await response.blob();var disposition=response.headers.get("content-disposition")||"";var match=/filename=\"([^\"]+)\"/.exec(disposition);var fileName=match&&match[1]?match[1]:"Contrata-IA_PCAP-Memoria-PPT.zip";var url=URL.createObjectURL(blob);var link=document.createElement("a");link.href=url;link.download=fileName;document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);if(status)status.textContent="Paquete generado. Continúa pendiente de aceptación humana final.";await refresh();}catch(error){if(status){status.className="warning";status.textContent=error.message;}else alert(error.message);}}
document.addEventListener("DOMContentLoaded",function(){setTimeout(refresh,250);});
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(refresh,100);});
})();`;
