export const LB120_DOCUMENT_CONCLUSION_SCRIPT = String.raw`(function(){
var KEY="contrataIaAdaptiveAnswers",CASE_KEY="contrataIaAdaptiveCaseId",FIELD="closure.finalConsentRecord",preview=null;
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function read(){try{return JSON.parse(sessionStorage.getItem(KEY)||localStorage.getItem(KEY)||"{}");}catch(e){return {};}}
function save(a,k){sessionStorage.setItem(KEY,JSON.stringify(a));localStorage.setItem(KEY,JSON.stringify(a));document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:k}}));}
function cid(){return localStorage.getItem(CASE_KEY)||"";}
async function json(u,o){var r=await fetch(u,Object.assign({credentials:"same-origin",headers:{"content-type":"application/json"}},o||{})),b=await r.json().catch(function(){return {};});if(!r.ok)throw new Error((b.error||"No se pudo completar la operación.")+(Array.isArray(b.blockers)&&b.blockers.length?": "+b.blockers.join(" · "):""));return b;}
function gate(open){var g=document.getElementById("lb103AuthoritativeGenerationPanel");if(g)g.style.display=open?"":"none";}
async function validate(id,value){var root="/api/adaptive/cases/"+encodeURIComponent(id)+"/universal-evidence";await json(root,{method:"PUT",body:JSON.stringify({fieldPath:FIELD,value:value,sourceId:"ui:lb120:final-human-consent",note:"Consentimiento final ligado a las huellas del expediente y de los tres documentos"})});await json(root+"/validate",{method:"POST",body:JSON.stringify({fieldPath:FIELD})});}
function checks(){return["factsAndDecisionsConfirmed","legalGroundsConfirmed","crossDocumentConsistencyConfirmed","officialPcapIntegrityConfirmed","memoryAndPptStructureConfirmed","noCriticalBlockersConfirmed"].reduce(function(o,k){o[k]=document.getElementById(k).checked;return o;},{});}
function unique(xs){return xs.filter(function(x,i){return x&&xs.indexOf(x)===i;});}
function documentName(value){var map={MEMORY:"Memoria justificativa",PCAP:"Pliego de cláusulas administrativas particulares",PPT:"Pliego de prescripciones técnicas"};return map[String(value)]||String(value||"Documento").replaceAll("_"," ");}
function documentState(value){return value==="GENERAL_EDITABLE_SELECTED"?"Modelo compatible verificado":"Modelo pendiente de verificar";}
function blockersOf(p){return unique([].concat(Array.isArray(p.blockers)?p.blockers:[],p.completion&&Array.isArray(p.completion.blockers)?p.completion.blockers:[]));}
function preflightMessage(p){var blockers=blockersOf(p),detail=blockers.length?"\n• "+blockers.join("\n• "):"";if(!p.snapshotReady)return"Faltan decisiones o datos obligatorios por validar antes de preparar los documentos."+detail;if(!p.packageReady)return"Las decisiones del expediente están completas y validadas. La preparación documental permanece pendiente hasta que se verifique un modelo compatible para cada documento."+detail;return"Las decisiones y los modelos están disponibles, pero todavía existen comprobaciones documentales pendientes."+detail;}
function availabilityHtml(p){var decisionClass=p.snapshotReady?"info":"warning",decisionText=p.snapshotReady?"Decisiones del expediente completas y validadas":"Decisiones del expediente pendientes",rows=(p.documents||[]).map(function(d){return '<li><strong>'+esc(documentName(d.documentType))+':</strong> '+esc(documentState(d.status))+(Array.isArray(d.blockers)&&d.blockers.length?'<ul>'+d.blockers.map(function(b){return'<li>'+esc(b)+'</li>';}).join("")+'</ul>':"")+'</li>';}).join("");return '<div class="'+decisionClass+'"><strong>'+decisionText+'</strong><p>'+esc(preflightMessage(p)).replaceAll("\n","<br>")+'</p></div><h3>Estado de los documentos</h3><ul class="lb120-document-status">'+rows+'</ul>'+(p.snapshotReady?'<p class="muted">La falta de un modelo no modifica el estado de los pasos 1 a 7.</p>':"");}
async function preflight(){return json("/api/adaptive/cases/"+encodeURIComponent(cid())+"/lb103-preflight",{method:"GET"});}
function legalCard(d){if(!d)return"";return '<details><summary>Fundamento jurídico del cierre</summary>'+(d.legalBases||[]).map(function(b){return '<div class="info"><strong>'+esc(b.norm)+' · artículo '+esc(b.article)+', apartado '+esc(b.paragraph)+'</strong><br><q>'+esc(b.relevantOfficialExcerpt)+'</q><br><a href="'+esc(b.officialUrl)+'" target="_blank" rel="noopener noreferrer">Consultar texto oficial</a></div>';}).join("")+'</details>';}
async function mount(){var m=document.querySelector("main"),q=document.getElementById("lb106VirginPilot")||document.getElementById("work");if(!m||!q||document.getElementById("lb120Block"))return;var p=document.createElement("section");p.id="lb120Block";m.insertBefore(p,q);var observer=new MutationObserver(function(){gate(read().__lb120&&read().__lb120.status==="HUMAN_VALIDATED");});var gen=document.getElementById("lb103AuthoritativeGenerationPanel");if(gen)observer.observe(gen,{childList:true,subtree:true});await render(p);}
async function render(p){var a=read(),prior=a.__lb119||{},s=a.__lb120||{},id=cid();if(!id||prior.status!=="HUMAN_VALIDATED"){p.innerHTML="";gate(false);return;}if(s.status==="HUMAN_VALIDATED"){gate(true);p.innerHTML='<div class="card info"><h2>Cierre documental validado</h2><p>El consentimiento nominativo está ligado al paquete <code>'+esc(s.record.packageSha256)+'</code>.</p><p>Cualquier cambio en el expediente o en los documentos impedirá la descarga hasta repetir este cierre.</p><button id="lb120Review" class="secondary">Revisar de nuevo</button></div>';document.getElementById("lb120Review").onclick=function(){s.status="REVIEW";a.__lb120=s;save(a,"lb120-review");render(p);};return;}gate(false);p.innerHTML='<div class="card"><h2>Comprobación final y preparación de documentos</h2><div class="info"><strong>Decisiones del expediente completas</strong><p>Los pasos 1 a 7 están revisados. Esta comprobación no volverá a marcarlos como pendientes.</p></div><p>Ahora el sistema comprobará por separado la disponibilidad de la Memoria, el PCAP y el PPT adecuados al tipo de contrato, al procedimiento y a la financiación.</p><p class="muted">No se sustituirá el modelo oficial por otro distinto ni se generará un documento incompleto.</p><button id="lb120Preview">Comprobar los modelos y preparar la vista previa</button><div id="lb120Status" class="muted" style="white-space:normal">'+(s.preflight?availabilityHtml(s.preflight):"")+'</div></div>';document.getElementById("lb120Preview").onclick=async function(){var st=document.getElementById("lb120Status");try{st.innerHTML='<p class="muted">Comprobando decisiones, modelos y documentos…</p>';var pf=await preflight();a=read();s=a.__lb120||s;s.status=pf.documentState==="MODELOS_PENDIENTES"?"MODEL_PENDING":"REVIEW";s.decisionStatus=pf.decisionState;s.documentStatus=(pf.documents||[]).map(function(d){return{documentType:d.documentType,status:d.status,blockers:d.blockers||[]};});s.preflight=pf;a.__lb120=s;save(a,"lb120-preflight");if(!pf.generationReady||!pf.snapshot||!pf.documentarySelection){st.innerHTML=availabilityHtml(pf);return;}var x={snapshotSha256:pf.snapshot.sha256,documentarySelectionSha256:pf.documentarySelection.sha256};preview=await json("/api/adaptive/cases/"+encodeURIComponent(id)+"/lb120-preview",{method:"POST",body:JSON.stringify(x)});var matrix=await json("/api/lb106/decision-matrix",{method:"GET"});s.legal=(matrix.decisions||[]).find(function(d){return d.id==="D20_DOCUMENT_APPROVAL";});a.__lb120=s;save(a,"lb120-preview");showConsent(p,a,s,id);}catch(e){st.textContent=e.message;st.className="warning";}};}
function showConsent(p,a,s,id){p.innerHTML='<div class="card"><h2>Vista previa y propuesta de cierre</h2><p><strong>Paquete documental:</strong> <code>'+esc(preview.packageSha256)+'</code></p>'+preview.documents.map(function(d){return '<div class="info"><strong>'+esc(documentName(d.kind))+'</strong><br>'+esc(d.fileName)+'<br><code>'+esc(d.sha256)+'</code><br><small>'+esc(d.provenance)+'</small></div>';}).join("")+legalCard(s.legal)+[["factsAndDecisionsConfirmed","He revisado los hechos y decisiones validados."],["legalGroundsConfirmed","He revisado sus fundamentos jurídicos y alternativas."],["crossDocumentConsistencyConfirmed","Confirmo la coherencia entre Memoria, PCAP y PPT."],["officialPcapIntegrityConfirmed","Confirmo que el PCAP conserva el modelo oficial y solo se han cumplimentado sus huecos."],["memoryAndPptStructureConfirmed","Confirmo los epígrafes aplicables de Memoria y PPT."],["noCriticalBlockersConfirmed","No quedan bloqueos críticos conocidos."]].map(function(x){return '<label><input type="checkbox" id="'+x[0]+'" style="width:auto"> '+x[1]+'</label>';}).join("")+'<label>Conclusión y motivación de la persona responsable</label><textarea id="lb120Statement" rows="4"></textarea><button id="lb120Consent">Prestar y registrar consentimiento final</button> <button id="lb120Cancel" class="secondary">Rehacer vista previa</button><p id="lb120Status" class="muted"></p></div>';document.getElementById("lb120Cancel").onclick=function(){preview=null;render(p);};document.getElementById("lb120Consent").onclick=async function(){var st=document.getElementById("lb120Status");try{var input=Object.assign({snapshotSha256:preview.snapshotSha256,documentarySelectionSha256:preview.documentarySelectionSha256,packageSha256:preview.packageSha256,finalStatement:document.getElementById("lb120Statement").value},checks());var out=await json("/api/adaptive/cases/"+encodeURIComponent(id)+"/lb120-consent",{method:"POST",body:JSON.stringify(input)});await validate(id,out.record);a=read();s=a.__lb120||s;s.status="HUMAN_VALIDATED";s.record=out.record;s.humanValidatedAt=new Date().toISOString();a.__lb120=s;save(a,"lb120-human-validation");render(p);}catch(e){st.textContent=e.message;st.className="warning";}};}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();
document.addEventListener("contrata-ia:adaptive-saved",function(e){if(e.detail&&String(e.detail.kind||"").indexOf("lb120")===0)return;setTimeout(function(){var p=document.getElementById("lb120Block");if(p)render(p);},0);});
})();`;
