import type {StrictServicePilotSnapshot} from "../../intake/lb102/StrictServicePilotPackageGenerator";

const HUELVA_OBJECT="Servicios de limpieza para las oficinas/centros de empleo de Ayamonte, Lepe, Isla Cristina y Puebla de Guzmán dependientes de la Dirección Provincial del SAE de Huelva";
export const LB102_SERVICE_HUELVA:StrictServicePilotSnapshot={
 caseId:"CONTR 2025 0000468715",sourceAuthority:"JDA_SAE_HUELVA_MEMORIA_PCAP_PPT",sourceConfirmed:true,sourceConflict:false,
 sourceReferences:["Memoria justificativa CONTR 2025 0000468715","PCAP CONTR 2025 0000468715","PPT CONTR 2025 0000468715"],
 auditTerms:{object:"limpieza",cpv:"90911200",pbl:"174.582,58",estimatedValue:"296.790,39"},
 values:{
  PCAP:{caseId:"CONTR 2025 0000468715",title:HUELVA_OBJECT,locationSummary:"Ayamonte, Lepe, Isla Cristina y Puebla de Guzmán (Huelva).",cpvSummary:"90911200-8 limpieza de edificios; 90919200-4 limpieza de oficinas; 90922000-6 control de plagas; 90923000-3 desratización.",objectSummary:HUELVA_OBJECT,lotsSummary:"Sin división en lotes; la fuente justifica la unidad de coordinación técnica de los cuatro centros.",reservedContractSummary:"No consta reserva singular en el snapshot de piloto; se aplica exclusivamente el régimen acreditado por el PCAP fuente.",needsBasedContractSummary:"No es un contrato de suministros en función de necesidades ni se aplica DA 33.ª.",specificLegalRegimeSummary:"Contrato administrativo de servicios sujeto a LCSP y al PCAP específico del expediente.",economicSummary:"PBL 174.582,58 € sin IVA; IVA 36.662,34 €; total 211.244,93 €; valor estimado 296.790,39 €.",budgetSummary:"Presupuesto base de licitación: 174.582,58 € sin IVA; 211.244,93 € IVA incluido.",estimatedValueSummary:"Valor estimado declarado por la fuente: 296.790,39 € sin IVA.",priceSummary:"Sistema de precio y desglose conforme a Memoria y PCAP primarios del expediente, sin inferencia adicional.",durationSummary:"Duración y, en su caso, prórroga conforme al PCAP primario; el snapshot no sustituye la literalidad de la fuente.",solvencySummary:"Solvencia exigida conforme al apartado específico del PCAP primario, sin generalizar umbrales a otros expedientes.",buyerProfileSummary:"Perfil de contratante de la Dirección Provincial del Servicio Andaluz de Empleo de Huelva.",procedureSummary:"Procedimiento abierto; tramitación conforme a la publicación y PCAP del expediente.",guaranteesSummary:"Régimen de garantías conforme al PCAP primario del expediente.",awardCriteriaSummary:"Criterios de adjudicación conforme al PCAP primario del expediente; no se heredan criterios de otros casos.",specialExecutionConditionsSummary:"Condiciones especiales de ejecución conforme al PCAP primario.",subcontractingSummary:"Régimen de subcontratación conforme al PCAP primario y LCSP.",penaltiesSummary:"Penalidades conforme al PCAP primario del expediente.",paymentSummary:"Pago y facturación conforme al PCAP primario y a la ejecución efectivamente conformada.",executionSummary:"Prestación integral de limpieza y control de plagas en los cuatro centros objeto del contrato.",suspensionSummary:"Suspensión conforme a LCSP y PCAP primario.",modificationSummary:"Modificación únicamente en los supuestos y límites expresamente previstos en PCAP/LCSP; no se infiere porcentaje distinto del acreditado.",dataProtectionSummary:"Protección de datos conforme al régimen aplicable del PCAP y a los tratamientos que efectivamente implique la prestación.",subrogationSummary:"La subrogación solo se materializa si está expresamente acreditada por la documentación laboral/contractual del expediente."},
  MEMORY:{caseId:"CONTR 2025 0000468715",needAndOwnMeans:"La Dirección Provincial necesita garantizar la limpieza de cuatro oficinas/centros y la fuente justifica insuficiencia de medios materiales propios.",object:HUELVA_OBJECT,cpvMain:"90911200-8",lotsRegime:"No dividido en lotes por razones de coordinación técnica acreditadas en la fuente.",economicSummary:"PBL 174.582,58 € sin IVA; IVA 36.662,34 €; total 211.244,93 €; VE 296.790,39 €.",durationSummary:"Duración según documentación primaria del expediente; cualquier prórroga exige previsión expresa.",procedureAndSolvencySummary:"Procedimiento abierto; solvencia según PCAP primario.",awardCriteriaSummary:"Criterios según PCAP primario, sin extrapolación a otros expedientes.",personnelAndExecutionSummary:"Personal, medios y frecuencias conforme al PPT; ejecución en Ayamonte, Lepe, Isla Cristina y Puebla de Guzmán.",modificationSummary:"Solo modificaciones expresamente previstas o legalmente habilitadas."},
  PPT:{caseId:"CONTR 2025 0000468715",object:HUELVA_OBJECT,contractManagement:"Dirección Provincial del SAE de Huelva y persona responsable del contrato.",durationSummary:"Plazo conforme a PCAP/PPT primarios.",executionLocations:"Oficinas/centros de empleo de Ayamonte, Lepe, Isla Cristina y Puebla de Guzmán.",technicalRequirements:"Limpieza integral de edificios/oficinas y actuaciones de control de plagas definidas por el PPT.",serviceVariantRequirements:"Servicio de limpieza; CPV complementarios de limpieza de oficinas, control de plagas y desratización.",personnelAndMeansRequirements:"Personal, productos, maquinaria y medios exigidos por el PPT primario.",serviceControlAndExecutionConditions:"Control de calidad, frecuencias, incidencias y conformidad según PPT y responsable del contrato."}
 }
};

const G5_OBJECT="Impartición de acciones formativas específicas de Formación Profesional para el Empleo sobre soluciones y aplicaciones relacionadas con tecnologías a desplegar sobre entornos 5G";
export const LB102_SERVICE_5G:StrictServicePilotSnapshot={
 caseId:"CONTR/2023/957915",sourceAuthority:"JDA_CEETA_5G_MEMORIA_PCAP_PPT",sourceConfirmed:true,sourceConflict:false,
 sourceReferences:["Memoria/Resolución de inicio CONTR/2023/957915","PCAP CONTR/2023/957915","PPT CONTR/2023/957915"],
 auditTerms:{object:"acciones formativas",cpv:"80530000",pbl:"5.613.300,00",estimatedValue:"5.613.300,00"},
 values:{
  PCAP:{caseId:"CONTR/2023/957915",title:G5_OBJECT,locationSummary:"Almería, Cádiz, Córdoba, Granada, Huelva, Jaén, Málaga y Sevilla.",cpvSummary:"80530000-8 Servicios de formación profesional.",objectSummary:"Ejecución de 84 ediciones de acciones formativas sobre competencias digitales y tecnologías relacionadas con 5G.",lotsSummary:"Sin división en lotes; la documentación fuente motiva la unidad del proyecto formativo y la calidad/solvencia de la ejecución.",reservedContractSummary:"Sin reserva singular acreditada en el snapshot de piloto.",needsBasedContractSummary:"No aplica DA 33.ª de suministros.",specificLegalRegimeSummary:"Contrato administrativo de servicios; formación exenta de IVA conforme al art. 20.Uno.9º de la Ley 37/1992 según la fuente.",economicSummary:"PBL 5.613.300,00 €; IVA exento; VE 5.613.300,00 €.",budgetSummary:"Presupuesto base de licitación: 5.613.300,00 €, IVA exento.",estimatedValueSummary:"Valor estimado: 5.613.300,00 €; sin prórrogas ni modificaciones según la resolución de inicio.",priceSummary:"Precio determinado mediante precios unitarios conforme al art. 102 LCSP y detalle del PCAP.",durationSummary:"Sin prórrogas acreditadas; ejecución conforme al calendario y plazo de la documentación contractual.",solvencySummary:"Solvencia conforme al PCAP del procedimiento abierto SARA; no se extrapolan umbrales.",buyerProfileSummary:"Perfil de contratante de la Consejería competente en empleo de la Junta de Andalucía.",procedureSummary:"Procedimiento abierto, tramitación ordinaria, sujeto a regulación armonizada según la fuente.",guaranteesSummary:"Garantías conforme al PCAP primario del expediente.",awardCriteriaSummary:"Criterios de adjudicación establecidos en el PCAP del expediente 5G.",specialExecutionConditionsSummary:"Condiciones especiales conforme al PCAP y vinculadas a la correcta ejecución formativa.",subcontractingSummary:"Subcontratación conforme al PCAP y LCSP.",penaltiesSummary:"Penalidades por incumplimiento conforme al PCAP.",paymentSummary:"Pago asociado a la ejecución y conformidad de las acciones formativas conforme al PCAP.",executionSummary:"84 ediciones formativas, con ejecución territorial en las ocho provincias andaluzas.",suspensionSummary:"Suspensión conforme a LCSP y PCAP.",modificationSummary:"La fuente declara que el cálculo del VE no incorpora modificaciones ni prórrogas.",dataProtectionSummary:"Protección de datos aplicable a participantes y gestión de la formación conforme al PCAP y normativa aplicable.",subrogationSummary:"No se presume obligación de subrogación por tratarse de formación; solo sería aplicable con evidencia expresa."},
  MEMORY:{caseId:"CONTR/2023/957915",needAndOwnMeans:"Necesidad de impartir formación profesional para el empleo en competencias digitales vinculadas a tecnologías 5G.",object:"Ejecución de 84 ediciones de acciones formativas en entornos 5G.",cpvMain:"80530000-8",lotsRegime:"No dividido en lotes por la unidad del proyecto formativo y razones de calidad/solvencia acreditadas.",economicSummary:"PBL y VE: 5.613.300,00 €; operación exenta de IVA según la fuente.",durationSummary:"Sin prórrogas ni modificaciones computadas en el VE.",procedureAndSolvencySummary:"Procedimiento abierto ordinario, SARA; solvencia según PCAP.",awardCriteriaSummary:"Criterios conforme al PCAP específico del expediente.",personnelAndExecutionSummary:"Equipos docentes y medios técnicos conforme al PPT; ámbito de ejecución en las ocho provincias andaluzas.",modificationSummary:"No se computan modificaciones previstas en el valor estimado declarado."},
  PPT:{caseId:"CONTR/2023/957915",object:G5_OBJECT,contractManagement:"Unidad promotora de la Consejería competente en empleo y responsable del contrato.",durationSummary:"Calendario y plazo conforme al PPT/PCAP; sin prórroga prevista en el cálculo del VE.",executionLocations:"Ocho provincias andaluzas: Almería, Cádiz, Córdoba, Granada, Huelva, Jaén, Málaga y Sevilla.",technicalRequirements:"84 ediciones de acciones formativas; contenidos y requisitos técnicos sobre soluciones y aplicaciones relacionadas con entornos 5G.",serviceVariantRequirements:"Formación profesional para el empleo; CPV 80530000-8.",personnelAndMeansRequirements:"Personal docente, medios y recursos formativos conforme a los requisitos del PPT.",serviceControlAndExecutionConditions:"Seguimiento, acreditación de ejecución, asistencia, calidad y conformidad conforme al PPT y al órgano responsable."}
 }
};
