import {UniversalPriceRevisionEngine} from "../../../engines/UniversalPriceRevisionEngine";
export const LB116_PRICE_REVISION_VERSION="LB116-PRICE-REVISION-V1" as const;
const LCSP="https://www.boe.es/buscar/act.php?id=BOE-A-2017-12902";
export interface PriceRevisionDecisionInput {contractType:"SUPPLY"|"SERVICE";provisionalPrice:boolean;manufacturingArmamentOrPublicEquipmentSupply:boolean;energySupply:boolean;investmentRecoveryPeriodYears:number|null;rawMaterialsIntermediateGoodsAndEnergySharePercent:number|null;selectedRegime:"NO_REVISION"|"PERIODIC_PREDETERMINED";justification:string;formula:string;officialIndices:readonly {component:string;weightPercent:number;officialIndex:string}[]}
interface Basis{id:string;article:string;paragraph:string;relevantOfficialExcerpt:string;officialUrl:string}
export interface PriceRevisionDecisionResult {version:typeof LB116_PRICE_REVISION_VERSION;eligibility:"ELIGIBLE_IN_PRINCIPLE"|"NOT_ELIGIBLE"|"PENDING_FACTS";recommendedRegime:"NO_REVISION"|"REQUIRES_HUMAN_ASSESSMENT";priceRevisionRegime:string;justification:string;formula:string;costStructure:string;indices:string;accrualLimits:string;physicalProfileSupported:boolean;documentaryStatements:readonly {element:string;status:"APPLIES"|"NOT_APPLICABLE"|"PENDING";text:string;destinations:readonly ("MEMORY"|"PCAP")[]}[];legalBasis:readonly Basis[];warnings:readonly string[];humanValidationRequired:true;generationBlocked:true;productionReady:false}
const basis=(id:string,article:string,paragraph:string,text:string):Basis=>({id,article,paragraph,relevantOfficialExcerpt:text,officialUrl:`${LCSP}#a${article}`});
const LEGAL=[basis("LCSP-102.7","102","7","En los contratos celebrados con precios provisionales no cabrá la revisión de precios."),basis("LCSP-103.1","103","1","Los precios solo podrán ser objeto de revisión periódica y predeterminada en los términos legalmente establecidos."),basis("LCSP-103.2","103","2","La revisión exige justificación previa y solo procede en los tipos de contrato y condiciones expresamente establecidos."),basis("LCSP-103.2-MATERIALES","103","2, párrafos cuarto y quinto","Con recuperación inferior a cinco años, la participación de materias primas, bienes intermedios y energía debe superar el veinte por ciento y solo esa fracción puede revisarse."),basis("LCSP-103.3","103","3","El órgano de contratación podrá establecer el derecho a revisión y fijará la fórmula atendiendo a la naturaleza y estructura de costes."),basis("LCSP-103.4","103","4","El PCAP detallará una fórmula de revisión que será invariable durante la vigencia del contrato."),basis("LCSP-103.5","103","5","Salvo suministro de energía, deben haberse ejecutado al menos el veinte por ciento y haber transcurrido un año desde la formalización.")];
const clean=(v:string,label:string)=>{const x=String(v||"").trim();if(!x)throw new Error(`Falta ${label}.`);return x;};
export function evaluatePriceRevisionDecision(i:PriceRevisionDecisionInput):PriceRevisionDecisionResult{
 if(i.contractType!=="SUPPLY"&&(i.manufacturingArmamentOrPublicEquipmentSupply||i.energySupply))throw new Error("Las categorías especiales de fabricación de armamento/equipamiento y energía solo pueden declararse en contratos de suministro.");
 const base=new UniversalPriceRevisionEngine().evaluate({contractType:i.contractType,provisionalPrice:i.provisionalPrice,manufacturingArmamentOrPublicEquipmentSupply:i.manufacturingArmamentOrPublicEquipmentSupply,energySupply:i.energySupply,investmentRecoveryPeriodYears:i.investmentRecoveryPeriodYears===null?undefined:i.investmentRecoveryPeriodYears,rawMaterialsIntermediateGoodsAndEnergySharePercent:i.rawMaterialsIntermediateGoodsAndEnergySharePercent===null?undefined:i.rawMaterialsIntermediateGoodsAndEnergySharePercent});
 if(base.eligibility==="PENDING_FACTS")throw new Error("Faltan hechos para decidir la procedencia: periodo de recuperación y participación de materias primas, bienes intermedios y energía.");
 if(i.selectedRegime==="PERIODIC_PREDETERMINED"&&base.eligibility!=="ELIGIBLE_IN_PRINCIPLE")throw new Error("La revisión seleccionada no está habilitada por los hechos declarados.");
 const applying=i.selectedRegime==="PERIODIC_PREDETERMINED";
 const justification=applying?clean(i.justification,"la justificación económica y jurídica de la revisión"):clean(i.justification,"la motivación de que no procede la revisión");
 if(!applying&&i.officialIndices.length)throw new Error("No deben declararse índices si la revisión no procede.");
 const formula=applying?clean(i.formula,"la fórmula periódica y predeterminada"):"No procede.";
 const seen=new Set<string>();const indices=i.officialIndices.map((x,n)=>{const component=clean(x.component,`el componente ${n+1}`),officialIndex=clean(x.officialIndex,`el índice oficial ${n+1}`);if(seen.has(component.toLowerCase()))throw new Error(`Componente duplicado: ${component}.`);seen.add(component.toLowerCase());if(!Number.isFinite(x.weightPercent)||x.weightPercent<=0||x.weightPercent>100)throw new Error(`Peso inválido del componente ${component}.`);return{component,officialIndex,weightPercent:x.weightPercent};});
 if(applying&&!indices.length)throw new Error("La revisión requiere componentes, pesos e índices oficiales validados.");
 const share=i.rawMaterialsIntermediateGoodsAndEnergySharePercent;if(applying&&share!==null&&i.investmentRecoveryPeriodYears!==null&&i.investmentRecoveryPeriodYears<5){for(const x of indices)if(x.weightPercent<=1)throw new Error("En el supuesto de recuperación inferior a cinco años solo se identifican componentes con participación superior al uno por ciento.");const total=indices.reduce((a,x)=>a+x.weightPercent,0);if(total>share+0.0001)throw new Error("Los pesos revisables superan la fracción declarada de materias primas, bienes intermedios y energía.");}
 const costStructure=applying?indices.map(x=>`${x.component}: ${x.weightPercent} %`).join("; "):"No procede.";const indexText=applying?indices.map(x=>`${x.component}: ${x.officialIndex}`).join("; "):"No procede.";
 const accrual=applying?(i.energySupply?"Se aplicará el régimen temporal específico del suministro de energía.":"La revisión solo se devengará después de ejecutar al menos el 20 % y transcurrir un año desde la formalización; quedan excluidos el primer 20 % y el primer año."):"No procede al no establecerse revisión de precios.";
 const regime=applying?`Sí procede revisión periódica y predeterminada. Fórmula invariable: ${formula}`:`No procede la revisión de precios. ${justification}`;
 const physical=!applying;
 return{version:LB116_PRICE_REVISION_VERSION,eligibility:base.eligibility,recommendedRegime:base.eligibility==="NOT_ELIGIBLE"?"NO_REVISION":"REQUIRES_HUMAN_ASSESSMENT",priceRevisionRegime:regime,justification,formula,costStructure,indices:indexText,accrualLimits:accrual,physicalProfileSupported:physical,documentaryStatements:[{element:"PRICE_REVISION",status:applying?"APPLIES":"NOT_APPLICABLE",text:regime,destinations:["MEMORY","PCAP"]},{element:"FORMULA",status:applying?"APPLIES":"NOT_APPLICABLE",text:formula,destinations:["PCAP"]},{element:"COST_STRUCTURE",status:applying?"APPLIES":"NOT_APPLICABLE",text:costStructure,destinations:["MEMORY","PCAP"]},{element:"OFFICIAL_INDICES",status:applying?"APPLIES":"NOT_APPLICABLE",text:indexText,destinations:["PCAP"]},{element:"ACCRUAL_LIMITS",status:applying?"APPLIES":"NOT_APPLICABLE",text:accrual,destinations:["MEMORY","PCAP"]},{element:"PHYSICAL_PROFILE",status:physical?"APPLIES":"PENDING",text:physical?"El perfil físico activo acredita el supuesto sin revisión.":"La decisión afirmativa no puede generarse con el perfil físico actual; debe seleccionarse y acreditarse un modelo compatible.",destinations:["PCAP"]}],legalBasis:LEGAL,warnings:["No se utiliza el IPC general ni se seleccionan índices por semejanza con otros expedientes.","La fórmula y cada índice oficial requieren comprobación y validación humana antes de generar.",...(physical?[]:["Generación bloqueada: falta cobertura física acreditada para revisión afirmativa."])],humanValidationRequired:true,generationBlocked:true,productionReady:false};
}
