export const UNIVERSAL_EVIDENCE_SCRIPT = String.raw`(function(){
  const state={manifest:[],evidence:{},caseId:""};
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  async function request(url,options){const response=await fetch(url,{credentials:"same-origin",headers:{"content-type":"application/json",...(options&&options.headers||{})},...options});const text=await response.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={error:text}}if(!response.ok)throw new Error(body.error||("HTTP "+response.status));return body;}
  function fieldStatus(field){if(!field)return {text:"SIN DECLARAR",cls:"pending"};if(field.status==="HUMAN_VALIDATED")return{text:"VALIDADO",cls:"validated"};if(field.status==="SOURCE_CONFLICT")return{text:"CONFLICTO",cls:"conflict"};return{text:field.status||"PENDIENTE",cls:"pending"};}
  function boolValue(field){return field&&field.value===true?"true":field&&field.value===false?"false":"";}
  function lines(value){return Array.isArray(value)?value.join("\n"):"";}
  function tableText(path,value){if(!Array.isArray(value))return"";if(path==="economic.annualityBudgetRows")return value.map(r=>[r.year,r.amountCents,r.budgetApplication,r.vatIncluded?"Sí":"No"].join("; ")).join("\n");if(path==="economic.unitPrices")return value.map(r=>[r.concept,r.unit,r.unitPriceCents].join("; ")).join("\n");if(path==="criteria.awardCriteria")return value.map(r=>[r.nombre,r.ponderacion,r.evaluableMedianteFormula?"Sí":"No"].join("; ")).join("\n");return lines(value);}
  function inputFor(def,field){const value=field?field.value:null;const id="u-"+def.fieldPath.replace(/[^A-Za-z0-9]/g,"-");if(def.control==="BOOLEAN")return '<select id="'+id+'"><option value="">Seleccione…</option><option value="true" '+(boolValue(field)==="true"?"selected":"")+'>Sí</option><option value="false" '+(boolValue(field)==="false"?"selected":"")+'>No</option></select>';if(def.control==="MONEY_CENTS"||def.control==="INTEGER")return '<input id="'+id+'" type="number" min="0" step="1" value="'+esc(value??"")+'">';if(def.control==="SELECT"&&def.fieldPath==="contractType")return '<select id="'+id+'"><option value="">Seleccione…</option>'+["SUPPLY","SERVICE","WORKS","CONCESSION","MIXED","OTHER"].map(v=>'<option value="'+v+'" '+(value===v?"selected":"")+'>'+v+'</option>').join("")+'</select>';if(def.control==="TABLE"){let help="Una línea por elemento.";if(def.fieldPath==="economic.annualityBudgetRows")help="Formato por línea: año; importe en céntimos; aplicación presupuestaria; Sí/No IVA incluido.";else if(def.fieldPath==="economic.unitPrices")help="Formato por línea: concepto; unidad; precio unitario en céntimos.";else if(def.fieldPath==="criteria.awardCriteria")help="Formato por línea: nombre; ponderación; Sí/No evaluable mediante fórmula.";return '<textarea id="'+id+'">'+esc(tableText(def.fieldPath,value))+'</textarea><div class="help">'+esc(help)+'</div>';}if(def.control==="TEXTAREA")return '<textarea id="'+id+'">'+esc(value??"")+'</textarea>';return '<input id="'+id+'" value="'+esc(value??"")+'">';}
  function parseBool(v){if(v==="true")return true;if(v==="false")return false;throw new Error("Seleccione Sí o No.");}
  function yes(v){return /^(s[ií]|true|1)$/i.test(String(v).trim());}
  function parseTable(path,raw){const rows=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(path==="technical.executionLocations"||path==="execution.specialExecutionConditions")return rows;if(path==="economic.annualityBudgetRows")return rows.map((line,index)=>{const p=line.split(";").map(x=>x.trim());if(p.length<4)throw new Error("Fila "+(index+1)+": faltan columnas de anualidad.");const year=Number(p[0]),amountCents=Number(p[1]);if(!Number.isInteger(year)||!Number.isInteger(amountCents)||amountCents<0)throw new Error("Fila "+(index+1)+": año/importe no válido.");return{year,amountCents,budgetApplication:p[2],vatIncluded:yes(p[3])};});if(path==="economic.unitPrices")return rows.map((line,index)=>{const p=line.split(";").map(x=>x.trim());if(p.length<3)throw new Error("Fila "+(index+1)+": faltan columnas de precio unitario.");const unitPriceCents=Number(p[2]);if(!p[0]||!p[1]||!Number.isInteger(unitPriceCents)||unitPriceCents<0)throw new Error("Fila "+(index+1)+": precio unitario no válido.");return{concept:p[0],unit:p[1],unitPriceCents};});if(path==="criteria.awardCriteria")return rows.map((line,index)=>{const p=line.split(";").map(x=>x.trim());if(p.length<3)throw new Error("Fila "+(index+1)+": faltan columnas del criterio.");const ponderacion=Number(p[1]);if(!p[0]||!Number.isFinite(ponderacion)||ponderacion<=0||ponderacion>100)throw new Error("Fila "+(index+1)+": ponderación no válida.");return{nombre:p[0],ponderacion,evaluableMedianteFormula:yes(p[2])};});return rows;}
  function readValue(def){const id="u-"+def.fieldPath.replace(/[^A-Za-z0-9]/g,"-");const el=$(id);if(!el)throw new Error("Control no encontrado.");if(def.control==="BOOLEAN")return parseBool(el.value);if(def.control==="MONEY_CENTS"||def.control==="INTEGER"){const n=Number(el.value);if(!Number.isInteger(n)||n<0)throw new Error("Introduzca un número entero no negativo.");return n;}if(def.control==="TABLE")return parseTable(def.fieldPath,el.value);const value=String(el.value||"").trim();if(!value)throw new Error("El campo no puede quedar vacío.");return value;}
  function render(){const host=$("universalFields");if(!host)return;host.innerHTML=state.manifest.map(def=>{const field=state.evidence[def.fieldPath];const status=fieldStatus(field);return '<div class="field"><div class="row"><div><strong>'+esc(def.label)+'</strong> <span class="status '+status.cls+'">'+esc(status.text)+'</span>'+(def.help?'<div class="help">'+esc(def.help)+'</div>':'')+inputFor(def,field)+'</div><div class="toolbar"><button type="button" data-save="'+esc(def.fieldPath)+'">Guardar declaración</button><button type="button" class="review" data-validate="'+esc(def.fieldPath)+'" '+(!field||field.status==="SOURCE_CONFLICT"?'disabled':'')+'>Validar</button></div></div>'+(field&&field.sources?'<div class="help">Fuente(s): '+esc(field.sources.map(s=>s.sourceId).join(", "))+'</div>':'')+'</div>';}).join("");}
  async function loadManifest(){const body=await request('/api/universal-ui-manifest');state.manifest=body.fields||[];render();}
  async function loadCase(){const id=String($("universalCaseId").value||"").trim();if(!id)throw new Error("Indique el ID del expediente.");state.caseId=id;const body=await request('/api/adaptive/cases/'+encodeURIComponent(id)+'/universal-evidence');state.evidence=body.evidence||{};sessionStorage.setItem('contrataIaUniversalCaseId',id);render();$("universalStatus").className="ok";$("universalStatus").textContent='Expediente '+id+' · '+Object.keys(state.evidence).length+' campos con evidencia.';}
  async function save(path){if(!state.caseId)throw new Error("Abra primero un expediente.");const def=state.manifest.find(x=>x.fieldPath===path);if(!def)throw new Error("Campo no reconocido.");const value=readValue(def);const body=await request('/api/adaptive/cases/'+encodeURIComponent(state.caseId)+'/universal-evidence',{method:'PUT',body:JSON.stringify({fieldPath:path,value,sourceId:'ui:operator'})});state.evidence[path]=body.field;render();$("universalStatus").className="warning";$("universalStatus").textContent='Declaración guardada. Pendiente de validación humana: '+def.label;}
  async function validate(path){if(!state.caseId)throw new Error("Abra primero un expediente.");const body=await request('/api/adaptive/cases/'+encodeURIComponent(state.caseId)+'/universal-evidence/validate',{method:'POST',body:JSON.stringify({fieldPath:path})});state.evidence[path]=body.field;render();$("universalStatus").className="ok";$("universalStatus").textContent='Validación humana registrada: '+path;}
  document.addEventListener('DOMContentLoaded',async()=>{try{await loadManifest();const remembered=sessionStorage.getItem('contrataIaUniversalCaseId')||sessionStorage.getItem('contrataIaAdaptiveCaseId');if(remembered){$("universalCaseId").value=remembered;try{await loadCase();}catch{}}}catch(error){$("universalStatus").className="warning";$("universalStatus").textContent=error.message;}$("loadUniversalCase").addEventListener('click',()=>loadCase().catch(e=>alert(e.message)));$("universalFields").addEventListener('click',event=>{const target=event.target;if(!(target instanceof HTMLElement))return;const savePath=target.getAttribute('data-save');const validatePath=target.getAttribute('data-validate');if(savePath)save(savePath).catch(e=>alert(e.message));if(validatePath)validate(validatePath).catch(e=>alert(e.message));});});
})();`;
