export const ADAPTIVE_FLOW_UI = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Contrata-IA · Diálogo jurídico</title><style>body{font-family:Arial,sans-serif;margin:0;background:#f4f6f7;color:#17202a}header{background:#fff;border-bottom:1px solid #ddd;padding:18px}main{max-width:980px;margin:24px auto;padding:0 18px}.card{background:#fff;border:1px solid #ddd;border-radius:8px;padding:20px;margin-bottom:16px}button{padding:11px 14px;border:0;border-radius:5px;background:#176b45;color:#fff;cursor:pointer;min-height:44px}button.secondary{background:#566573}input,textarea,select{box-sizing:border-box;width:100%;padding:11px;margin:7px 0 12px;border:1px solid #bbb;border-radius:4px;font-size:16px}textarea{min-height:110px}.muted{color:#626567}.info{background:#eaf2f8;padding:12px;border-radius:5px;margin:8px 0}.warning{background:#fff3cd;padding:12px;border-radius:5px;margin:8px 0}.grid{display:grid;grid-template-columns:220px 1fr;gap:6px 14px}.grid>div{padding:5px 0;border-bottom:1px solid #eee}.toolbar{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:760px){.grid{grid-template-columns:1fr}.toolbar{display:block}button{width:100%;margin:4px 0}}</style></head><body><header><strong>Contrata-IA</strong> · Diálogo jurídico adaptativo</header><main><div class="card"><h2>Acceso</h2><input id="token" type="password" placeholder="Credencial de acceso"><div class="toolbar"><button id="applyToken">Aplicar credencial</button><button id="resetFlow" class="secondary">Reiniciar diálogo</button><button id="backClassic" class="secondary">Volver al piloto clásico</button></div><p id="tokenStatus" class="muted"></p></div><div id="work"></div></main><script>
(function(){
var token=sessionStorage.getItem("contrataIaToken")||"";
var rawAnswers=sessionStorage.getItem("contrataIaAdaptiveAnswers")||"{}";
var answers={};
try{answers=JSON.parse(rawAnswers);}catch(e){answers={};sessionStorage.removeItem("contrataIaAdaptiveAnswers");}
var tokenInput=document.getElementById("token");
var tokenStatus=document.getElementById("tokenStatus");
var work=document.getElementById("work");
tokenInput.value=token;
function setStatus(){tokenStatus.textContent=token?"Credencial activa en esta sesión.":"Sin credencial aplicada.";}
function esc(value){return String(value==null?"":value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function money(value){return typeof value==="number"?value.toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €":"Pendiente";}
function humanNature(value){if(value==="SERVICES")return "Servicios";if(value==="SUPPLIES")return "Suministros";return "Pendiente de clasificar";}
function humanLots(value){if(value==="SINGLE_LOT")return "Lote único propuesto";if(value==="MULTIPLE_LOTS")return "Varios lotes propuestos";return "Pendiente de análisis";}
function humanProcedure(value){if(value==="OPEN_SIMPLIFIED_ABBREVIATED_CANDIDATE")return "Abierto simplificado abreviado — propuesta";if(value==="OPEN_SIMPLIFIED_CANDIDATE")return "Abierto simplificado — propuesta";if(value==="OPEN_PROCEDURE_REVIEW_REQUIRED")return "Procedimiento a revisar según cuantía y régimen aplicable";return "Pendiente";}
function option(value,label){return "<option value=\""+esc(value)+"\">"+esc(label)+"</option>";}
function inputFor(q){
if(q.id==="contentResponsibility")return "<select id=\"ans\"><option value=\"\">Seleccione</option>"+option("ADMIN_SUPPLIES_CONTRACTOR_ADAPTS","La Administración aporta la información y la empresa la adapta/publica")+option("CONTRACTOR_CREATES","La empresa también crea contenido sustantivo")+option("NOT_APPLICABLE","No procede")+"</select>";
if(q.id==="technicalContinuity")return "<select id=\"ans\"><option value=\"\">Seleccione</option>"+option("SAME_CONTRACTOR_PREFERRED","Es preferible una misma empresa por continuidad/coordinación técnica")+option("SEPARABLE","Pueden ejecutarse separadamente sin problemas relevantes")+option("UNKNOWN","No lo sé")+"</select>";
if(q.id==="dominantComponent")return "<select id=\"ans\"><option value=\"\">Seleccione</option>"+option("INITIAL_DEVELOPMENT","Predomina la prestación inicial/desarrollo")+option("RECURRENT_SERVICE","Predomina el servicio recurrente")+option("GOODS","Predomina la adquisición de bienes")+option("BALANCED","Peso parecido")+option("UNKNOWN","No lo sé")+"</select>";
if(q.id==="requiresNonFormulaQualityAssessment")return "<select id=\"ans\"><option value=\"\">Seleccione</option><option value=\"false\">No</option><option value=\"true\">Sí</option></select>";
if(q.id==="extensionMonths")return "<input id=\"ans\" placeholder=\"Ej.: 12, 12\">";
if(["initialBudgetExVat","initialDurationMonths","initialOneOffCostExVat","recurringAnnualCostExVat"].includes(q.id))return "<input id=\"ans\" inputmode=\"decimal\" placeholder=\"Indique una cifra\">";
return "<textarea id=\"ans\" placeholder=\"Responda con lenguaje natural\"></textarea>";
}
function parseValue(id,raw){if(id==="requiresNonFormulaQualityAssessment")return raw==="true";if(id==="extensionMonths")return raw.split(",").map(function(x){return Number(x.trim());}).filter(function(x){return Number.isFinite(x)&&x>=0;});if(["initialBudgetExVat","initialDurationMonths","initialOneOffCostExVat","recurringAnnualCostExVat"].includes(id)){var normalized=raw.replaceAll(".","").replace(",",".");var n=Number(normalized);if(!Number.isFinite(n))throw new Error("Indique una cifra válida.");return n;}return raw;}
async function callAnalyze(){var response=await fetch("/api/adaptive/analyze",{method:"POST",headers:Object.assign({"content-type":"application/json"},token?{authorization:"Bearer "+token}:{}),body:JSON.stringify({answers:answers})});if(!response.ok){var message="Error";try{var data=await response.json();message=data.error||message;}catch(e){}throw new Error(message);}return response.json();}
function renderDecision(d){var html="<div class=\"card\"><h2>Interpretación acumulada</h2><div class=\"grid\"><div><strong>Naturaleza contractual</strong></div><div>"+esc(humanNature(d.contractNature))+"<br><span class=\"muted\">"+esc(d.contractNatureReason)+"</span></div><div><strong>Lotes</strong></div><div>"+esc(humanLots(d.lotProposal))+"<br><span class=\"muted\">"+esc(d.lotReason)+"</span></div><div><strong>Valor estimado provisional</strong></div><div>"+esc(money(d.economics.estimatedValueExVat))+"<br><span class=\"muted\">"+esc(d.economics.note)+"</span></div><div><strong>Procedimiento</strong></div><div>"+esc(humanProcedure(d.procedure))+"<br><span class=\"muted\">"+esc(d.procedureReason)+"</span></div></div>";
if(d.cpv&&d.cpv.length){html+="<h3>CPV propuestos</h3><ul>"+d.cpv.map(function(x){return "<li><strong>"+esc(x.code)+"</strong> · "+esc(x.label)+" ("+(x.role==="PRIMARY"?"principal":"complementario")+")</li>";}).join("")+"</ul>";}
if(d.economics.annualProjection&&d.economics.annualProjection.length){html+="<h3>Proyección económica</h3><ul>"+d.economics.annualProjection.map(function(x){return "<li>"+esc(x.period)+": <strong>"+esc(money(x.amountExVat))+"</strong></li>";}).join("")+"</ul>";}
if(d.proposals&&d.proposals.length)html+="<h3>Propuestas del sistema</h3><ul>"+d.proposals.map(function(x){return "<li>"+esc(x)+"</li>";}).join("")+"</ul>";
if(d.warnings&&d.warnings.length)html+=d.warnings.map(function(x){return "<div class=\"warning\">"+esc(x)+"</div>";}).join("");
html+="<div class=\"info\"><strong>Criterios de adjudicación:</strong> "+esc(d.awardCriteriaConstraint)+"</div><details><summary>Ver fundamento jurídico</summary>"+d.legalGrounds.map(function(x){return "<p><strong>"+esc(x.article)+"</strong><br>"+esc(x.rule)+"<br><span class=\"muted\">Verificación de normativa vigente obligatoria antes de cerrar el expediente.</span></p>";}).join("")+"</details></div>";return html;}
async function analyze(){if(!token){work.innerHTML="<div class=\"card warning\">Aplique primero una credencial.</div>";return;}try{var d=await callAnalyze();var html=renderDecision(d);if(d.nextQuestion){html+="<div class=\"card\"><h2>Siguiente pregunta</h2><h3>"+esc(d.nextQuestion.label)+"</h3><p>"+esc(d.nextQuestion.help)+"</p>"+inputFor(d.nextQuestion)+"<button id=\"saveAnswer\">Guardar y continuar</button><p class=\"muted\">Las respuestas alimentan propuestas jurídicas y requieren validación humana antes de cerrar el expediente.</p></div>";}else{html+="<div class=\"card info\"><h2>Espina dorsal completada</h2><p>Ya pueden abrirse las ramas específicas que correspondan.</p></div>";}work.innerHTML=html;if(d.nextQuestion){var save=document.getElementById("saveAnswer");save.addEventListener("click",async function(){var el=document.getElementById("ans");if(!el||!el.value.trim()){alert("Indique una respuesta.");return;}try{answers[d.nextQuestion.id]=parseValue(d.nextQuestion.id,el.value.trim());sessionStorage.setItem("contrataIaAdaptiveAnswers",JSON.stringify(answers));await analyze();}catch(e){alert(e.message);}});}}catch(e){work.innerHTML="<div class=\"card warning\">"+esc(e.message)+"</div>";}}
document.getElementById("applyToken").addEventListener("click",function(){token=tokenInput.value.trim();if(token)sessionStorage.setItem("contrataIaToken",token);else sessionStorage.removeItem("contrataIaToken");setStatus();analyze();});
document.getElementById("resetFlow").addEventListener("click",function(){answers={};sessionStorage.removeItem("contrataIaAdaptiveAnswers");analyze();});
document.getElementById("backClassic").addEventListener("click",function(){location.href="/";});
setStatus();analyze();
})();
</script></body></html>`;
