import { SERVICE_REGRESSION_CASE_007_MAINTENANCE_SEVILLE_ECONOMICS } from "../../regression/ServiceRegressionCase007MaintenanceSevilleEconomics";
import { SERVICE_REGRESSION_MAINTENANCE_007_ECONOMICS_GUARD_SCRIPT } from "./ServiceRegressionMaintenance007EconomicsGuardScript";

const CASE_JSON = JSON.stringify(SERVICE_REGRESSION_CASE_007_MAINTENANCE_SEVILLE_ECONOMICS);

const MAINTENANCE_007_ECONOMICS_CORE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var VERSION="REG-SERVICE-007-MAINTENANCE-ECONOMICS-11.9.3-v1";
var CASE=${CASE_JSON};
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"maintenance-economics-evidence-11.9.3"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function money(c){return (Number(c||0)/100).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function manifest(validated){return {version:VERSION,id:CASE.id,step:CASE.step,expediente:CASE.expediente,status:validated?"ECONOMIC_SOURCE_EVIDENCE_HUMAN_VALIDATED_WITH_ROUNDING_DIAGNOSTICS":CASE.status,sourceDocuments:CASE.sourceDocuments,sourceSection:CASE.sourceSection,sourceValuePolicy:CASE.sourceValuePolicy,estimatedValue:CASE.estimatedValue,annualitiesVatIncluded:CASE.annualitiesVatIncluded,resolvedEvidenceAtThisStep:CASE.resolvedEvidenceAtThisStep,deliberatelyStillOpen:CASE.deliberatelyStillOpen,humanValidated:validated===true,validatedAt:validated?new Date().toISOString():null};}
function downloadJson(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrata-IA_REG-SERVICE-007_Mantenimiento-Sevilla_Economics_11-9-3.json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function lotRows(){return CASE.estimatedValue.lots.map(function(l){return '<tr><td>Lote '+l.lot+'</td><td>'+money(l.tenderAmountExVatCents)+'</td><td>'+money(l.modificationCents)+'</td><td>'+money(l.extensionCents)+'</td><td>'+money(l.declaredEstimatedValueCents)+'</td><td>'+(l.declaredMinusArithmeticCents===0?'0,00 €':money(l.declaredMinusArithmeticCents))+'</td></tr>';}).join('');}
function card(){var a=readAnswers();if(a.serviceRegressionMaintenance007AutomaticGuardRegistered!==true)return "";var validated=a.serviceRegressionMaintenance007EconomicsValidated===true;var d=CASE.estimatedValue.declaredTotals;var diag=CASE.estimatedValue.diagnostic;var html='<div id="serviceRegressionMaintenance007EconomicsCard" class="card" style="margin-top:14px"><h3>11.9.3 Evidencia económica · Mantenimiento SAE Sevilla</h3>';
html+='<div class="info"><strong>Valores declarados por la fuente.</strong> Este paso conserva literalmente los importes del Anexo I del PCAP. Las comprobaciones aritméticas son diagnósticas y no sustituyen los valores declarados.</div>';
html+='<table style="width:100%;border-collapse:collapse"><thead><tr><th>Lote</th><th>Licitación sin IVA</th><th>Modificación</th><th>Prórroga</th><th>VE declarado</th><th>Diferencia</th></tr></thead><tbody>'+lotRows()+'</tbody></table>';
html+='<div class="grid" style="margin-top:12px"><div><strong>Total licitación sin IVA</strong></div><div>'+money(d.tenderAmountExVatCents)+'</div><div><strong>Modificación art. 204 LCSP</strong></div><div>'+money(d.modificationCents)+' · 20 %</div><div><strong>Prórroga</strong></div><div>'+money(d.extensionCents)+' · 24 meses</div><div><strong>VE global declarado</strong></div><div>'+money(d.estimatedValueCents)+'</div><div><strong>Anualidades IVA incluido</strong></div><div>'+money(CASE.annualitiesVatIncluded.declaredTotalCents)+'</div><div><strong>Aplicación presupuestaria</strong></div><div>'+esc(CASE.annualitiesVatIncluded.budgetApplication)+'</div></div>';
html+='<div class="warning"><strong>Diferencias de fuente que no se corrigen.</strong> Lotes 2 y 4: +0,01 € respecto del cálculo aritmético. Suma de VE declarados por lotes: '+money(diag.sumDeclaredLotEstimatedValuesCents)+'; VE global declarado: '+money(diag.declaredGlobalEstimatedValueCents)+'; diferencia: '+money(diag.lotSumMinusDeclaredGlobalCents)+'. Tratamiento: preservar declaraciones de la fuente.</div>';
html+='<div class="warning"><strong>Campos que siguen abiertos:</strong><ul>'+CASE.deliberatelyStillOpen.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul></div>';
if(!validated){html+='<p><strong>Estado:</strong> evidencia económica pendiente de validación humana.</p><button id="validateMaintenance007Economics" type="button">Validar evidencia económica 11.9.3</button>';}else{html+='<div class="info"><strong>11.9.3 validado.</strong> Se confirman únicamente los valores económicos declarados y sus diagnósticos de redondeo; los campos jurídicos abiertos permanecen sin resolver.</div><button id="downloadMaintenance007Economics" type="button" class="secondary">Descargar evidencia 11.9.3 JSON</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("serviceRegressionMaintenance007EconomicsCard");if(old)old.remove();var anchor=document.getElementById("serviceRegressionMaintenance007GuardCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="validateMaintenance007Economics"){var a=readAnswers();if(a.serviceRegressionMaintenance007AutomaticGuardRegistered!==true){alert("Primero debe registrarse la regresión automática 11.9.2.");return;}var m=manifest(true);a.serviceRegressionMaintenance007EconomicsValidated=true;a.serviceRegressionMaintenance007EconomicsVersion=VERSION;a.serviceRegressionMaintenance007EconomicsManifest=m;a.serviceRegressionMaintenance007EconomicsStatus="ECONOMIC_SOURCE_EVIDENCE_HUMAN_VALIDATED_WITH_ROUNDING_DIAGNOSTICS";a.serviceRegressionNextRecommendedStep="11.9.4";save(a);downloadJson(m);ensure();alert("Evidencia económica 11.9.3 validada. Los redondeos declarados se preservan y los campos jurídicos abiertos no se han completado por inferencia.");return;}if(e.target.id==="downloadMaintenance007Economics"){var a2=readAnswers();downloadJson(a2.serviceRegressionMaintenance007EconomicsManifest||manifest(true));return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;

export const SERVICE_REGRESSION_MAINTENANCE_007_ECONOMICS_SCRIPT = MAINTENANCE_007_ECONOMICS_CORE_SCRIPT + "\n" + SERVICE_REGRESSION_MAINTENANCE_007_ECONOMICS_GUARD_SCRIPT;
