import { CARL_SERVICE_REGRESSION_MANIFEST, CARL_SERVICE_REGRESSION_VERSION } from "../../regression/ServiceRegressionCase005CarlCleaningGuard";

const BASELINE_JSON = JSON.stringify(CARL_SERVICE_REGRESSION_MANIFEST);

export const SERVICE_REGRESSION_CARL_005_GUARD_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var VERSION=${JSON.stringify(CARL_SERVICE_REGRESSION_VERSION)};
var BASELINE=${BASELINE_JSON};
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"carl-service-regression-11.8.1"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function manifest(){return {version:VERSION,caseId:BASELINE.caseId,status:BASELINE.passed?"AUTOMATIC_REGRESSION_ACTIVE":"AUTOMATIC_REGRESSION_BLOCKED",passed:BASELINE.passed,blockers:BASELINE.blockers,checks:BASELINE.checks,protectedScope:BASELINE.protectedScope,deliberatelyNotFrozenYet:BASELINE.deliberatelyNotFrozenYet,forbiddenSupplyInheritance:BASELINE.forbiddenSupplyInheritance,requiresSourceExtractionHumanValidation:true,sourceExtractionHumanValidated:true,acceptanceRule:"La regresión protege únicamente el alcance validado en 11.8: contrato de servicios de limpieza, abierto simplificado ordinario, CPV principal 90919200-4, insuficiencia de medios propios, subrogación de personal y carácter instrumental de materiales/maquinaria. No congela todavía lotes, DA 33.ª, sistema económico, PBL/VE, duración, modificación, criterios, solvencia, garantías, condiciones especiales ni detalle económico de la subrogación.",registeredAt:new Date().toISOString()};}
function downloadJson(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrata-IA_REG-SERVICE-005_CARL_Regression_11-8-1.json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function rows(){return BASELINE.checks.map(function(c){return '<tr><td>'+esc(c.id)+'</td><td>'+(c.ok?'✓ Pasa':'✗ Bloquea')+'</td><td>'+esc(c.purpose)+'</td></tr>';}).join("");}
function card(){var a=readAnswers();if(a.serviceRegressionCarl005ExtractionValidated!==true)return "";var registered=a.serviceRegressionCarl005AutomaticGuardRegistered===true;var html='<div id="serviceRegressionCarl005GuardCard" class="card" style="margin-top:14px"><h3>11.8.1 Regresión automática servicios CARL</h3>';
if(BASELINE.passed){html+='<div class="info"><strong>Protección automática activa.</strong> La línea base supera '+BASELINE.checks.length+' comprobaciones con 0 bloqueantes. Se protege la naturaleza de servicio, la prestación principal de limpieza, el abierto simplificado ordinario, CPV principal, insuficiencia de medios, subrogación y el carácter instrumental de materiales/maquinaria.</div>';}else{html+='<div class="warning"><strong>Regresión bloqueada.</strong> Existen '+BASELINE.blockers.length+' incoherencias y no puede registrarse.</div>';}
html+='<div class="warning"><strong>Guardas frente a herencia de suministros.</strong> El expediente no puede recalificarse como suministro por incluir productos, maquinaria o uniformes; tampoco puede heredar lógica de entrega, catálogo de 98 referencias, precios unitarios de suministro ni DA 33.ª sin evidencia documental propia.</div><div class="warning"><strong>Alcance limitado deliberadamente.</strong> No se congelan todavía lotes, DA 33.ª, sistema económico, PBL/VE, duración/prórrogas, modificación, criterios/ponderaciones, solvencia, garantías, condiciones especiales, penalidades ni detalle económico de la subrogación.</div><table style="width:100%;border-collapse:collapse"><thead><tr><th>Check</th><th>Resultado</th><th>Qué protege</th></tr></thead><tbody>'+rows()+'</tbody></table>';
if(!registered&&BASELINE.passed){html+='<button id="registerCarl005AutomaticGuard" type="button">Registrar regresión automática 11.8.1</button>';}else if(registered){html+='<div class="info"><strong>11.8.1 registrado.</strong> Versión '+esc(VERSION)+'. REG-SERVICE-005 queda protegido como caso de regresión de servicios, pero no como golden case.</div><button id="downloadCarl005AutomaticGuard" type="button" class="secondary">Descargar manifiesto 11.8.1 JSON</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("serviceRegressionCarl005GuardCard");if(old)old.remove();var anchor=document.getElementById("serviceRegressionCarl005ExtractionCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="registerCarl005AutomaticGuard"){var a=readAnswers();if(a.serviceRegressionCarl005ExtractionValidated!==true){alert("Primero debe validarse la extracción documental 11.8.");return;}if(!BASELINE.passed){alert("La regresión presenta bloqueantes y no puede registrarse.");return;}var m=manifest();a.serviceRegressionCarl005AutomaticGuardRegistered=true;a.serviceRegressionCarl005AutomaticGuardVersion=VERSION;a.serviceRegressionCarl005AutomaticGuardManifest=m;a.serviceRegressionCarl005Status="AUTOMATIC_REGRESSION_ACTIVE";a.serviceRegressionNextRecommendedStep="11.8.2";save(a);downloadJson(m);ensure();alert("Regresión automática CARL 11.8.1 registrada. REG-SERVICE-005 queda protegido sin convertirse en golden case.");return;}if(e.target.id==="downloadCarl005AutomaticGuard"){var a2=readAnswers();downloadJson(a2.serviceRegressionCarl005AutomaticGuardManifest||manifest());return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;
