import { MAINTENANCE_007_REGRESSION_RESULT, MAINTENANCE_007_REGRESSION_VERSION } from "../../regression/ServiceRegressionCase007MaintenanceSevilleGuard";
import { SERVICE_REGRESSION_MAINTENANCE_007_ECONOMICS_SCRIPT } from "./ServiceRegressionMaintenance007EconomicsScript";

const BASELINE_JSON = JSON.stringify(MAINTENANCE_007_REGRESSION_RESULT);

const MAINTENANCE_007_GUARD_CORE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var VERSION=${JSON.stringify(MAINTENANCE_007_REGRESSION_VERSION)};
var BASELINE=${BASELINE_JSON};
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"maintenance-service-regression-11.9.2"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function manifest(){return {version:VERSION,caseId:BASELINE.caseId,step:BASELINE.step,status:BASELINE.passed?"AUTOMATIC_REGRESSION_ACTIVE_WITH_SOURCE_CONFLICT_GUARD":"AUTOMATIC_REGRESSION_BLOCKED",passed:BASELINE.passed,blockers:BASELINE.blockers,checks:BASELINE.checks,protectedScope:BASELINE.protectedScope,blockingSourceInconsistency:BASELINE.blockingSourceInconsistency,forbiddenInheritance:BASELINE.forbiddenInheritance,deliberatelyNotFrozenYet:BASELINE.deliberatelyNotFrozenYet,requiresFineExtractionHumanValidation:true,fineExtractionHumanValidated:true,registeredAt:new Date().toISOString()};}
function downloadJson(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrata-IA_REG-SERVICE-007_Mantenimiento-Sevilla_Regression_11-9-2.json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function rows(){return BASELINE.checks.map(function(c){return '<tr><td>'+esc(c.id)+'</td><td>'+(c.ok?'✓ Pasa':'✗ Bloquea')+'</td><td>'+esc(c.purpose)+'</td></tr>';}).join("");}
function card(){var a=readAnswers();if(a.serviceRegressionMaintenance007FineExtractionValidated!==true)return "";var registered=a.serviceRegressionMaintenance007AutomaticGuardRegistered===true;var inc=BASELINE.blockingSourceInconsistency;var html='<div id="serviceRegressionMaintenance007GuardCard" class="card" style="margin-top:14px"><h3>11.9.2 Regresión automática · Mantenimiento SAE Sevilla</h3>';
if(BASELINE.passed){html+='<div class="info"><strong>Perímetro acreditado protegido.</strong> La línea base supera '+BASELINE.checks.length+' comprobaciones con 0 bloqueantes internos. Se protegen servicio, abierto SARA, 4 lotes, CPV técnicos, insuficiencia de medios y GMAO.</div>';}else{html+='<div class="warning"><strong>Regresión bloqueada.</strong> Existen '+BASELINE.blockers.length+' incoherencias internas y no puede registrarse.</div>';}
html+='<div class="warning"><strong>Conflicto de fuente preservado como guarda.</strong> '+esc(inc.statementA)+' / '+esc(inc.statementB)+' La regresión no resuelve esta contradicción: fallará si el motor convierte cualquiera de las dos frases en regla definitiva sin nueva evidencia primaria y validación humana.</div><div class="warning"><strong>Campos fuera de esta regresión.</strong><ul>'+BASELINE.deliberatelyNotFrozenYet.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul></div><table style="width:100%;border-collapse:collapse"><thead><tr><th>Check</th><th>Resultado</th><th>Qué protege</th></tr></thead><tbody>'+rows()+'</tbody></table>';
if(!registered&&BASELINE.passed){html+='<button id="registerMaintenance007AutomaticGuard" type="button">Registrar regresión automática 11.9.2</button>';}else if(registered){html+='<div class="info"><strong>11.9.2 registrado.</strong> Versión '+esc(VERSION)+'. REG-SERVICE-007 queda protegido como caso de regresión con contradicción de fuente abierta; no es golden case ni línea base documental completa.</div><button id="downloadMaintenance007AutomaticGuard" type="button" class="secondary">Descargar manifiesto 11.9.2 JSON</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("serviceRegressionMaintenance007GuardCard");if(old)old.remove();var anchor=document.getElementById("serviceRegressionMaintenance007FineExtractionCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="registerMaintenance007AutomaticGuard"){var a=readAnswers();if(a.serviceRegressionMaintenance007FineExtractionValidated!==true){alert("Primero debe validarse la extracción documental fina 11.9.1.");return;}if(!BASELINE.passed){alert("La regresión presenta bloqueantes internos y no puede registrarse.");return;}var m=manifest();a.serviceRegressionMaintenance007AutomaticGuardRegistered=true;a.serviceRegressionMaintenance007AutomaticGuardVersion=VERSION;a.serviceRegressionMaintenance007AutomaticGuardManifest=m;a.serviceRegressionMaintenance007Status="AUTOMATIC_REGRESSION_ACTIVE_WITH_SOURCE_CONFLICT_GUARD";a.serviceRegressionNextRecommendedStep="11.9.3";save(a);downloadJson(m);ensure();alert("Regresión automática 11.9.2 registrada. La contradicción sobre límite de lotes permanece abierta y protegida frente a resolución automática.");return;}if(e.target.id==="downloadMaintenance007AutomaticGuard"){var a2=readAnswers();downloadJson(a2.serviceRegressionMaintenance007AutomaticGuardManifest||manifest());return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;

export const SERVICE_REGRESSION_MAINTENANCE_007_GUARD_SCRIPT = MAINTENANCE_007_GUARD_CORE_SCRIPT + "\n" + SERVICE_REGRESSION_MAINTENANCE_007_ECONOMICS_SCRIPT;
