import { CARL_FINE_REGRESSION_BASELINE, CARL_FINE_REGRESSION_VERSION } from "../../regression/ServiceRegressionCase005CarlFineGuard";

const BASELINE_JSON = JSON.stringify(CARL_FINE_REGRESSION_BASELINE);

export const SERVICE_REGRESSION_CARL_005_FINE_GUARD_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var VERSION=${JSON.stringify(CARL_FINE_REGRESSION_VERSION)};
var BASELINE=${BASELINE_JSON};
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"carl-fine-regression-11.8.3"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function manifest(){return {version:VERSION,caseId:BASELINE.caseId,status:BASELINE.passed?"SECOND_LEVEL_AUTOMATIC_REGRESSION_ACTIVE":"SECOND_LEVEL_AUTOMATIC_REGRESSION_BLOCKED",passed:BASELINE.passed,blockers:BASELINE.blockers,checks:BASELINE.checks,protectedScope:BASELINE.protectedScope,deliberatelyNotFrozenYet:BASELINE.deliberatelyNotFrozenYet,sourceValueGuard:BASELINE.sourceValueGuard,classificationGuard:BASELINE.classificationGuard,requiresFineExtractionHumanValidation:true,fineExtractionHumanValidated:true,acceptanceRule:"La regresión protege exclusivamente los hechos validados en 11.8.2. El VE de 106.008,80 € queda congelado como dato declarado por la fuente y no como fórmula jurídica generalizable. Los extremos no extraídos del Anexo I siguen fuera de la línea base.",registeredAt:new Date().toISOString()};}
function downloadJson(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrata-IA_REG-SERVICE-005_CARL_SecondLevel_11-8-3.json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function rows(){return BASELINE.checks.map(function(c){return '<tr><td>'+esc(c.id)+'</td><td>'+(c.ok?'✓ Pasa':'✗ Bloquea')+'</td><td>'+esc(c.purpose)+'</td></tr>';}).join("");}
function card(){var a=readAnswers();if(a.serviceRegressionCarl005FineExtractionValidated!==true)return "";var registered=a.serviceRegressionCarl005FineGuardRegistered===true;var html='<div id="serviceRegressionCarl005FineGuardCard" class="card" style="margin-top:14px"><h3>11.8.3 Regresión documental de segundo nivel · CARL</h3>';
if(BASELINE.passed){html+='<div class="info"><strong>Protección de segundo nivel activa.</strong> La línea base supera '+BASELINE.checks.length+' comprobaciones con 0 bloqueantes. Se protegen calificación mixta 90/10, prestación principal de servicios, no lotes, no SARA, duración 12+12, PBL/IVA/VE, modificación prevista del 20 %, criterios mediante fórmulas, pago y estructura de costes.</div>';}else{html+='<div class="warning"><strong>Regresión bloqueada.</strong> Existen '+BASELINE.blockers.length+' incoherencias y no puede registrarse.</div>';}
html+='<div class="warning"><strong>Guarda del valor estimado.</strong> '+esc(BASELINE.sourceValueGuard.explanation)+'</div><div class="warning"><strong>Guarda de calificación.</strong> '+esc(BASELINE.classificationGuard)+'</div><div class="warning"><strong>Fuera de esta línea base.</strong> Permanecen pendientes los 20 puntos restantes, fórmulas exactas, literalidad del sistema de precio, solvencia, garantías, condiciones especiales, penalidades, causa exacta de la modificación, detalle completo de subrogación y DA 33.ª.</div><table style="width:100%;border-collapse:collapse"><thead><tr><th>Check</th><th>Resultado</th><th>Qué protege</th></tr></thead><tbody>'+rows()+'</tbody></table>';
if(!registered&&BASELINE.passed){html+='<button id="registerCarl005FineGuard" type="button">Registrar regresión documental 11.8.3</button>';}else if(registered){html+='<div class="info"><strong>11.8.3 registrado.</strong> Versión '+esc(VERSION)+'. CARL queda protegido con regresión documental de segundo nivel, sin convertirse en golden case.</div><button id="downloadCarl005FineGuard" type="button" class="secondary">Descargar manifiesto 11.8.3 JSON</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("serviceRegressionCarl005FineGuardCard");if(old)old.remove();var anchor=document.getElementById("serviceRegressionCarl005FineExtractionCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="registerCarl005FineGuard"){var a=readAnswers();if(a.serviceRegressionCarl005FineExtractionValidated!==true){alert("Primero debe validarse la extracción fina 11.8.2.");return;}if(!BASELINE.passed){alert("La regresión presenta bloqueantes y no puede registrarse.");return;}var m=manifest();a.serviceRegressionCarl005FineGuardRegistered=true;a.serviceRegressionCarl005FineGuardVersion=VERSION;a.serviceRegressionCarl005FineGuardManifest=m;a.serviceRegressionCarl005FineStatus="SECOND_LEVEL_AUTOMATIC_REGRESSION_ACTIVE";a.serviceRegressionNextRecommendedStep="11.8.4";save(a);downloadJson(m);ensure();alert("Regresión documental CARL 11.8.3 registrada. El caso queda protegido en segundo nivel sin convertirse en golden case.");return;}if(e.target.id==="downloadCarl005FineGuard"){var a2=readAnswers();downloadJson(a2.serviceRegressionCarl005FineGuardManifest||manifest());return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;
