export const SPECIALIZED_WORKFLOW_UI = `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#176b45">
<title>Contrata-IA · Revisión especializada</title>
<style>
body{font-family:Arial,sans-serif;margin:0;background:#f4f6f7;color:#17202a}header{background:#fff;border-bottom:1px solid #ddd;padding:18px;position:sticky;top:0;z-index:5}main{max-width:1050px;margin:24px auto;padding:0 16px}.card{background:#fff;border:1px solid #ddd;border-radius:8px;padding:20px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}label{font-weight:600}input,textarea,select{box-sizing:border-box;width:100%;padding:10px;margin:5px 0 12px;border:1px solid #bbb;border-radius:4px;font-size:16px}textarea{min-height:76px}.check{display:flex;gap:8px;align-items:center;font-weight:400}.check input{width:auto;margin:0}button{padding:11px 14px;border:0;border-radius:5px;background:#176b45;color:#fff;cursor:pointer;margin:4px;min-height:44px}.secondary{background:#566573}.warning{background:#fff3cd;padding:10px;border-radius:5px;margin:8px 0}.ok{background:#e8f5e9;padding:10px;border-radius:5px;margin:8px 0}.info{background:#eaf2f8;padding:10px;border-radius:5px;margin:8px 0}.muted{color:#626567}.status{font-weight:700}.toolbar{display:flex;gap:8px;flex-wrap:wrap}.scope{border-left:4px solid #d68910}.scope strong{display:block;margin-bottom:4px}@media(max-width:720px){.grid,.checks{grid-template-columns:1fr}.toolbar{display:block}button{width:100%;margin:4px 0}}
</style>
</head>
<body>
<header><strong>Contrata-IA</strong> · Configuración especializada y revisión preventiva</header>
<main>
<div class="card"><h2>Expediente</h2><div class="grid"><div><label>Identificador del expediente</label><input id="caseId" placeholder="Ej.: CONTR-2026-..." /></div><div><label>Credencial de acceso</label><input id="token" type="password" autocomplete="off" placeholder="Bearer token del piloto" /></div></div><div class="toolbar"><button onclick="loadCase()">Cargar expediente</button><button class="secondary" onclick="backMain()">Volver al expediente principal</button></div><div id="current" class="muted"></div></div>
<div class="card scope"><strong>Alcance de esta pantalla</strong><span>EVENT_SERVICES se utiliza aquí como perfil documental y técnico especializado. El motor normativo validado en LB-4 no se amplía automáticamente a contratos de eventos. La revisión preventiva identifica alertas para comprobación humana; no emite dictamen jurídico.</span></div>
<div class="card"><h2>1. Perfil documental EVENT_SERVICES</h2><p class="muted">Active únicamente las prestaciones que formen parte del contrato. Los datos activados que no se cumplimenten quedan pendientes; Contrata-IA no inventa esos hechos.</p><div class="checks" id="features"></div><div id="eventFields" class="grid"></div><div class="toolbar"><button onclick="saveEvent()">Guardar perfil documental</button><button class="secondary" onclick="clearEventForm()">Limpiar formulario visible</button></div></div>
<div class="card"><h2>2. Revisión jurídica preventiva</h2><p class="muted">Contrasta configuraciones de riesgo calibradas con casos jurídicos reales. El resultado sirve para preparar el expediente antes de su remisión a Asesoría Jurídica y exige comprobación de normativa vigente.</p><div class="grid">
<div><label>Tipo de contrato</label><select id="contractType"><option value="SERVICES">Servicios</option><option value="SUPPLIES">Suministros</option></select></div>
<div><label>¿Parte del modelo oficial recomendado de PCAP?</label><select id="officialModel"><option value="true">Sí</option><option value="false">No</option></select></div>
<div><label>¿Contrato en función de necesidades / DA 33.ª?</label><select id="needsBased"><option value="false">No</option><option value="true">Sí</option></select></div>
<div><label>Meses de prórroga previstos</label><input id="extensionMonths" type="number" min="0" value="0" /></div>
<div><label>¿La prórroga añade o repone presupuesto?</label><select id="extensionAddsBudget"><option value="false">No</option><option value="true">Sí</option></select></div>
<div><label>¿El VEC vuelve a sumar el presupuesto de prórroga?</label><select id="vecAddsExtension"><option value="false">No</option><option value="true">Sí</option></select></div>
<div><label>¿Se propone un único criterio de adjudicación?</label><select id="singleCriterion"><option value="false">No</option><option value="true">Sí</option></select></div>
<div><label>¿El plazo de entrega o ejecución es variable?</label><select id="deliveryVariable"><option value="false">No</option><option value="true">Sí</option></select></div>
<div><label>¿Existe modificación contractual prevista?</label><select id="plannedModification"><option value="false">No</option><option value="true">Sí</option></select></div>
<div><label>¿La modificación admite elementos nuevos sin precio unitario?</label><select id="newUnpriced"><option value="false">No</option><option value="true">Sí</option></select></div>
<div><label>¿El catálogo o prestación queda abierto a elementos no definidos?</label><select id="openCatalogue"><option value="false">No</option><option value="true">Sí</option></select></div>
</div><button onclick="savePreLegal()">Ejecutar y guardar revisión preventiva</button></div>
<div id="result"></div>
</main>
<script>
const featureOptions=[['MULTI_EVENT','Varios eventos'],['MULTI_LOT','Varios lotes'],['MULTI_PROVINCE','Varias provincias/localidades'],['VENUE','Sede/espacio'],['AUDIOVISUAL','Audiovisual'],['STREAMING','Streaming'],['PEOPLE','Personal/ponentes/actuaciones'],['ACCESSIBILITY','Accesibilidad'],['CATERING','Catering'],['RESERVED_CATERING_LOT','Lote reservado de catering'],['TRAVEL','Viajes/alojamiento'],['AWARDS','Premios/estatuillas'],['PERSONAL_DATA','Datos personales'],['INTELLECTUAL_PROPERTY','Propiedad intelectual']];
const baseFields=[['eventOfficialNames','Denominación oficial del evento o eventos'],['eventCount','Número de eventos'],['publicPurposeAndNeed','Finalidad pública y necesidad'],['datesOrTimeWindow','Fechas o ventana temporal'],['locationsAndNuts','Localidades y NUTS'],['lots','Lotes y prestaciones'],['cpvByLotOrPrestacion','CPV por lote o prestación'],['creativeConcept','Concepto creativo'],['productionPlan','Plan de producción'],['runOfShow','Escaleta o secuencia técnica'],['montageDismantling','Montaje, desmontaje y logística'],['licensesAuthorizations','Licencias y autorizaciones'],['insurance','Seguros exigidos'],['finalReportAndMetrics','Informe final, indicadores y entregables']];
const conditional={VENUE:[['venue','Espacio o sede'],['expectedAttendance','Asistencia o aforo previsto']],AUDIOVISUAL:[['soundLightingProjection','Sonido, iluminación y proyección'],['photoVideoRequirements','Fotografía y vídeo']],STREAMING:[['streamingRequirements','Streaming o retransmisión']],PEOPLE:[['presenterSpeakersPerformers','Presentación, ponentes o actuaciones'],['supportStaff','Equipo de producción y auxiliares']],ACCESSIBILITY:[['signLanguageAccessibility','Lengua de signos y accesibilidad']],CATERING:[['catering','Alcance del catering'],['expectedCovers','Servicios o cubiertos previstos']],RESERVED_CATERING_LOT:[['reservedCateringLot','Configuración del lote reservado']],TRAVEL:[['travel','Traslados'],['accommodation','Alojamiento']],AWARDS:[['awardsStatuettesGifts','Estatuillas, premios u obsequios']],PERSONAL_DATA:[['personalDataProcessing','Tratamiento de datos personales']],INTELLECTUAL_PROPERTY:[['intellectualProperty','Propiedad intelectual e imagen']]};
let loadedCase=null;
const incoming=new URLSearchParams(location.search).get('caseId');const storedToken=sessionStorage.getItem('contrataIaToken')||'';if(incoming){document.getElementById('caseId').value=incoming;sessionStorage.setItem('contrataIaCaseId',incoming);}else{document.getElementById('caseId').value=sessionStorage.getItem('contrataIaCaseId')||'';}document.getElementById('token').value=storedToken;
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function headers(){const token=document.getElementById('token').value.trim();if(token)sessionStorage.setItem('contrataIaToken',token);return {'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})};}
function id(){const value=document.getElementById('caseId').value.trim();if(!value)throw new Error('Indique el identificador del expediente.');sessionStorage.setItem('contrataIaCaseId',value);return value;}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...headers()};const r=await fetch(url,opt);if(!r.ok){let e;try{e=await r.json()}catch{e={error:await r.text()}}throw new Error(e.error||'Error');}return r.json();}
function bool(id){return document.getElementById(id).value==='true';}
function selectedFeatures(){return featureOptions.filter(([key])=>document.getElementById('f_'+key).checked).map(([key])=>key);}
function renderFeatures(){document.getElementById('features').innerHTML=featureOptions.map(([key,label])=>'<label class="check"><input type="checkbox" id="f_'+key+'" onchange="renderEventFields()"> '+label+'</label>').join('');renderEventFields();}
function fieldHtml([key,label]){return '<div><label>'+label+'</label><textarea id="e_'+key+'"></textarea></div>';}
function renderEventFields(){const old={};document.querySelectorAll('[id^="e_"]').forEach(el=>old[el.id]=el.value);let fields=[...baseFields];for(const f of selectedFeatures())if(conditional[f])fields.push(...conditional[f]);const seen=new Set();fields=fields.filter(([key])=>!seen.has(key)&&seen.add(key));document.getElementById('eventFields').innerHTML=fields.map(fieldHtml).join('');for(const [key,value] of Object.entries(old)){const el=document.getElementById(key);if(el)el.value=value;}}
function collectEventAnswers(){const answers={};document.querySelectorAll('[id^="e_"]').forEach(el=>{const value=el.value.trim();if(value)answers[el.id.slice(2)]=value;});return answers;}
function clearEventForm(){for(const [,key] of featureOptions){void key;}document.querySelectorAll('#features input').forEach(el=>el.checked=false);renderEventFields();}
function fillEvent(config){if(!config)return;document.querySelectorAll('#features input').forEach(el=>el.checked=false);for(const f of config.features||[]){const el=document.getElementById('f_'+f);if(el)el.checked=true;}renderEventFields();for(const [key,value] of Object.entries(config.answers||{})){const el=document.getElementById('e_'+key);if(el)el.value=Array.isArray(value)?value.join('\n'):String(value);}}
function setSelect(id,value){const el=document.getElementById(id);if(el&&value!==undefined)el.value=String(value);}
function fillPreLegal(input){if(!input)return;setSelect('contractType',input.contractType);setSelect('officialModel',input.usesOfficialRecommendedPcapModel);setSelect('needsBased',input.needsBasedUnderDa33);setSelect('extensionMonths',input.extensionMonths??0);setSelect('extensionAddsBudget',input.extensionAddsBudget);setSelect('vecAddsExtension',input.estimatedValueIncludesExtensionBudgetAgain);setSelect('singleCriterion',input.singleAwardCriterion);setSelect('deliveryVariable',input.deliveryTimeVariable);setSelect('plannedModification',input.plannedModification);setSelect('newUnpriced',input.modificationAllowsNewUnpricedItems);setSelect('openCatalogue',input.catalogueOpenEnded);}
async function loadCase(){try{const out=await api('/api/cases/'+encodeURIComponent(id()),{method:'GET'});loadedCase=out.caseValue;fillEvent(loadedCase.lb7&&loadedCase.lb7.eventServices);fillPreLegal(loadedCase.lb7&&loadedCase.lb7.preLegalReviewInput);document.getElementById('current').textContent='Expediente cargado: '+id()+' · revisión r'+loadedCase.revision;try{const review=await api('/api/cases/'+encodeURIComponent(id())+'/review',{method:'GET'});show(review);}catch(e){showMessage('El expediente existe, pero todavía no puede obtenerse la revisión conjunta: '+e.message,'info');}}catch(e){showMessage(e.message,'warning');}}
async function saveEvent(){try{const out=await api('/api/cases/'+encodeURIComponent(id())+'/event-services',{method:'POST',body:JSON.stringify({features:selectedFeatures(),answers:collectEventAnswers()})});loadedCase=out.caseValue;if(out.review)show(out.review);else showMessage('Perfil EVENT_SERVICES guardado. Complete primero los datos generales obligatorios para obtener la revisión conjunta.','ok');}catch(e){showMessage(e.message,'warning');}}
async function savePreLegal(){try{const input={contractType:document.getElementById('contractType').value,usesOfficialRecommendedPcapModel:bool('officialModel'),needsBasedUnderDa33:bool('needsBased'),extensionMonths:Number(document.getElementById('extensionMonths').value||0),extensionAddsBudget:bool('extensionAddsBudget'),estimatedValueIncludesExtensionBudgetAgain:bool('vecAddsExtension'),singleAwardCriterion:bool('singleCriterion'),deliveryTimeVariable:bool('deliveryVariable'),plannedModification:bool('plannedModification'),modificationAllowsNewUnpricedItems:bool('newUnpriced'),catalogueOpenEnded:bool('openCatalogue')};const out=await api('/api/cases/'+encodeURIComponent(id())+'/pre-legal-review',{method:'POST',body:JSON.stringify(input)});loadedCase=out.caseValue;if(out.review)show(out.review);else showMessage('Revisión preventiva guardada. Complete primero los datos generales obligatorios para obtener el estado conjunto.','ok');}catch(e){showMessage(e.message,'warning');}}
function backMain(){location.href='/';}
function showMessage(message,kind){document.getElementById('result').innerHTML='<div class="card '+kind+'">'+esc(message)+'</div>';}
function statusLabel(status){if(status==='READY_FOR_HUMAN_LEGAL_REFERRAL')return 'Sin alertas preventivas detectadas';if(status==='REVIEW_REQUIRED')return 'Requiere revisión antes de remisión jurídica';return 'Revisión preventiva no ejecutada';}
function show(review){const lb7=review.lb7||{};const status=lb7.legalReferralStatus||'NOT_RUN';let html='<div class="card"><h2>Resultado de la revisión especializada</h2><div class="'+(status==='READY_FOR_HUMAN_LEGAL_REFERRAL'?'ok':status==='REVIEW_REQUIRED'?'warning':'info')+'"><strong>Estado:</strong> '+esc(statusLabel(status))+'<br><span class="muted">Este estado no equivale a conformidad jurídica ni sustituye al informe del Letrado.</span></div>';if(lb7.eventServices){html+='<h3>Perfil documental de eventos</h3>';if(lb7.eventServices.warnings.length)html+=lb7.eventServices.warnings.map(w=>'<div class="warning">'+esc(w)+'</div>').join('');else html+='<div class="ok">No faltan hechos técnicos activados para componer el borrador documental especializado.</div>';}if(lb7.preLegalReview){html+='<h3>Alertas preventivas</h3>';if(lb7.preLegalReview.findings.length)html+=lb7.preLegalReview.findings.map(f=>'<div class="warning"><strong>'+esc(f.topic)+'</strong><br>'+esc(f.message)+'<br><em>Antes de remitir: '+esc(f.actionBeforeLegalReferral)+'</em></div>').join('');else html+='<div class="ok">No se han detectado alertas calibradas con los casos jurídicos incorporados. Debe mantenerse la comprobación de normativa vigente y la revisión humana.</div>';}html+='<div class="toolbar"><button onclick="loadCase()">Actualizar estado</button><button class="secondary" onclick="backMain()">Volver y continuar expediente</button></div></div>';document.getElementById('result').innerHTML=html;document.getElementById('current').textContent='Estado actualizado para '+id();}
renderFeatures();if(document.getElementById('caseId').value)loadCase();
</script>
</body></html>`;
