import { REGRESSION_SOURCE_CASES } from "../../regression/RegressionCoverageMatrix";
import { SUPPLY_REGRESSION_CASE_002_PANDA } from "../../regression/SupplyRegressionCase002Panda";

const SOURCE_CASES_JSON = JSON.stringify(REGRESSION_SOURCE_CASES);
const PANDA_CASE_JSON = JSON.stringify(SUPPLY_REGRESSION_CASE_002_PANDA);

export const SUPPLY_REGRESSION_SOURCES_REGISTRY_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var VERSION="REGRESSION-SOURCE-CASES-11.7.1-v1";
var PANDA_VERSION="REG-SUPPLY-002-EXTRACTION-11.7.2-v1";
var CASES=${SOURCE_CASES_JSON};
var PANDA=${PANDA_CASE_JSON};
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-regression-sources-registry"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function docs(c){return c.source&&Array.isArray(c.source.documents)?c.source.documents.join(" + "):"";}
function manifest(){return {version:VERSION,status:"SOURCE_DOCUMENTS_AVAILABLE",legalValidation:"PENDING",caseCount:CASES.length,cases:CASES.map(function(c){return {id:c.id,label:c.label,expediente:c.source?c.source.expediente:"",shortName:c.source?c.source.shortName:"",documents:c.source?c.source.documents:[],status:c.status,sourceBasis:c.sourceBasis,legalValidation:c.source?c.source.legalValidation:"PENDING",purpose:c.purpose,tags:c.tags||[]};}),acceptanceRule:"El registro 11.7.1 acredita disponibilidad y clasificación documental, no validación jurídica. Cada caso deberá superar contraste, auditoría sin bloqueantes y validación humana propia.",nextCase:"REG-SUPPLY-002",registeredAt:new Date().toISOString()};}
function pandaManifest(validated){return {version:PANDA_VERSION,id:PANDA.id,expediente:PANDA.expediente,status:validated?"SOURCE_EXTRACTION_HUMAN_VALIDATED":"SOURCE_EXTRACTED_PENDING_HUMAN_VALIDATION",facts:PANDA.facts,contrastWithGolden:PANDA.contrastWithGolden,regressionGuards:PANDA.regressionGuards,sourceDocuments:PANDA.sourceDocuments,humanValidationRequired:true,humanValidated:validated===true,validatedAt:validated?new Date().toISOString():null};}
function downloadJson(data,name){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function rows(){return CASES.map(function(c){return '<tr><td>'+esc(c.id)+'</td><td>'+esc(c.source?c.source.expediente:"")+'</td><td>'+esc(c.source?c.source.shortName:c.label)+'</td><td>'+esc(docs(c))+'</td><td>Documentación disponible · validación jurídica pendiente</td></tr>';}).join("");}
function sourceCard(){var a=readAnswers();if(a.supplyGoldenCaseRegistered!==true)return "";var registered=a.supplyRegressionSourceCasesRegistered===true;var html='<div id="supplyRegressionSourcesRegistryCard" class="card" style="margin-top:14px"><h3>11.7.1 Incorporación de expedientes reales de contraste</h3><div class="info"><strong>'+CASES.length+' expedientes con documentación primaria disponible.</strong> Se incorporan como fuentes de contraste de la matriz. Ninguno adquiere por este acto condición de caso dorado ni de doctrina jurídica validada.</div><div class="warning"><strong>Estado jurídico: pendiente.</strong> PCAP, PPT, Memoria y anexos disponibles permiten iniciar la regresión, pero las decisiones extraídas deben auditarse expediente por expediente y recibir validación humana antes de fijarse como referencia.</div><table style="width:100%;border-collapse:collapse"><thead><tr><th>ID</th><th>Expediente</th><th>Caso</th><th>Documentos</th><th>Estado</th></tr></thead><tbody>'+rows()+'</tbody></table><p><strong>Primer contraste:</strong> REG-SUPPLY-002 · Panda Antivirus AVRA.</p>';
if(!registered){html+='<button id="registerRegressionSourceCases" type="button">Registrar fuentes reales 11.7.1</button>';}else{html+='<div class="info"><strong>11.7.1 registrado.</strong> Versión '+VERSION+'.</div><button id="downloadRegressionSourceCases" type="button" class="secondary">Descargar manifiesto 11.7.1 JSON</button>';}
html+='</div>';return html;}
function factRow(label,value,contrast){return '<tr><td>'+esc(label)+'</td><td>'+esc(value)+'</td><td>'+esc(contrast)+'</td></tr>';}
function pandaCard(){var a=readAnswers();if(a.supplyRegressionSourceCasesRegistered!==true)return "";var f=PANDA.facts,validated=a.supplyRegressionPanda002ExtractionValidated===true;var html='<div id="supplyRegressionPanda002Card" class="card" style="margin-top:14px"><h3>11.7.2 REG-SUPPLY-002 · Panda Antivirus AVRA</h3><div class="info"><strong>Extracción estructurada desde Memoria + PCAP + PPT.</strong> Este paso compara hechos del expediente con el golden case; no convierte Panda en golden case.</div><table style="width:100%;border-collapse:collapse"><thead><tr><th>Dato</th><th>Panda AVRA</th><th>Contraste golden</th></tr></thead><tbody>';
html+=factRow("DA 33.ª",f.needsBasedDA33?"Sí":"No","DIFERENTE · debe desactivarse la lógica de contrato por necesidades");
html+=factRow("Procedimiento","Abierto simplificado ordinario","DIFERENTE · golden: simplificado abreviado");
html+=factRow("Lotes",f.lots?"Sí":"No","IGUAL · lote único");
html+=factRow("Duración",f.initialDurationMonths+" meses; prórroga: "+(f.extensions?"Sí":"No"),"DIFERENTE · sin prórrogas 12+12");
html+=factRow("PBL sin IVA",f.pblExVat.toFixed(2)+" €","DIFERENTE");
html+=factRow("VE sin IVA",f.estimatedValueExVat.toFixed(2)+" €","DIFERENTE · VE=PBL");
html+=factRow("Precio","Precios unitarios","IGUAL en modalidad, pero sin presupuesto máximo DA 33.ª");
html+=factRow("Adjudicación",f.awardPoints+" puntos · precio único","IGUAL en resultado");
html+=factRow("Modificación prevista",f.plannedModificationPercent+" % · reducción de financiación","DIFERENTE · no es modificación por mayores necesidades DA 33.ª");
html+=factRow("Garantía definitiva",f.guaranteeDefinitivePercentOnPbl+" % del PBL","DIFERENTE");
html+=factRow("Condición especial","Transparencia fiscal","DIFERENTE");
html+='</tbody></table><div class="warning"><strong>Guardas de regresión:</strong> Panda no puede heredar DA 33.ª, presupuesto máximo por necesidades, catálogo de 98 referencias, prórrogas 12+12 ni la modificación por mayores necesidades del caso ferretería. Sí debe conservar precios unitarios, precio 100 puntos y su modificación propia por reducción de financiación hasta el 20 %.</div>';
if(!validated){html+='<p><strong>Estado:</strong> extracción documental pendiente de validación humana.</p><button id="validatePanda002Extraction" type="button">Validar extracción documental 11.7.2</button>';}else{html+='<div class="info"><strong>11.7.2 validado por la persona usuaria.</strong> La extracción queda disponible como base para construir la regresión automática específica, pero todavía no es golden case.</div><button id="downloadPanda002Extraction" type="button" class="secondary">Descargar extracción 11.7.2 JSON</button>';}
html+='</div>';return html;}
function ensure(){["supplyRegressionSourcesRegistryCard","supplyRegressionPanda002Card"].forEach(function(id){var old=document.getElementById(id);if(old)old.remove();});var anchor=document.getElementById("supplyRegressionCoverageMatrixCard")||document.getElementById("supplyGoldenCaseRegressionCard");if(anchor){var h1=sourceCard();if(h1)anchor.insertAdjacentHTML("afterend",h1);var a1=document.getElementById("supplyRegressionSourcesRegistryCard");if(a1){var h2=pandaCard();if(h2)a1.insertAdjacentHTML("afterend",h2);}}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="registerRegressionSourceCases"){var a=readAnswers(),m=manifest();if(a.supplyGoldenCaseRegistered!==true){alert("Debe existir primero un caso dorado registrado.");return;}a.supplyRegressionSourceCasesRegistered=true;a.supplyRegressionSourceCasesVersion=VERSION;a.supplyRegressionSourceCasesManifest=m;a.supplyRegressionNextRecommendedCase="REG-SUPPLY-002";a.supplyRegressionNextRecommendedStatus="SOURCE_DOCUMENTS_AVAILABLE";save(a);downloadJson(m,"Contrata-IA_Regression_Source_Cases_11-7-1.json");ensure();alert("Fuentes reales 11.7.1 registradas. La validación jurídica de cada expediente sigue pendiente.");return;}if(e.target.id==="downloadRegressionSourceCases"){var a2=readAnswers();downloadJson(a2.supplyRegressionSourceCasesManifest||manifest(),"Contrata-IA_Regression_Source_Cases_11-7-1.json");return;}if(e.target.id==="validatePanda002Extraction"){var a3=readAnswers(),pm=pandaManifest(true);a3.supplyRegressionPanda002ExtractionValidated=true;a3.supplyRegressionPanda002ExtractionVersion=PANDA_VERSION;a3.supplyRegressionPanda002ExtractionManifest=pm;a3.supplyRegressionPanda002Status="SOURCE_EXTRACTION_HUMAN_VALIDATED";save(a3);downloadJson(pm,"Contrata-IA_REG-SUPPLY-002_Panda_11-7-2.json");ensure();alert("Extracción documental 11.7.2 validada. El siguiente paso será construir y ejecutar la regresión automática específica de Panda.");return;}if(e.target.id==="downloadPanda002Extraction"){var a4=readAnswers();downloadJson(a4.supplyRegressionPanda002ExtractionManifest||pandaManifest(true),"Contrata-IA_REG-SUPPLY-002_Panda_11-7-2.json");return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;
