export const SUPPLY_AWARD_CRITERIA_VISIBILITY_HOTFIX_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var SHORT_DELIVERY_DAYS=5;
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-award-criteria-hotfix"}}));}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function hasModification(a){return a.supplyNeedsModificationForeseen===true||Number(a.supplyNeedsModificationMaximumIncreasePercent||0)>0||Number(a.supplyNeedsModificationMaximumIncreaseExVat||0)>0;}
function shortDeadline(a){var d=Number(a.supplyDeliveryDeadlineDays||0);return d>0&&d<=SHORT_DELIVERY_DAYS;}
function economicClosed(a){return Number(a.supplyMaximumApprovedBudgetExVat||0)>0&&a.supplyNeedsModificationValidated===true&&a.supplyEstimatedValueValidated===true&&Number(a.supplyEstimatedValueExVat||0)>0;}
function closureSummary(a){var budget=Number(a.supplyMaximumApprovedBudgetExVat||0),pct=Number(a.supplyNeedsModificationMaximumIncreasePercent||0),inc=Number(a.supplyNeedsModificationMaximumIncreaseExVat||budget*pct/100),ve=Number(a.supplyEstimatedValueExVat||0);var mod=a.supplyNeedsModificationForeseen===true?'<div class="info"><strong>Modificación prevista:</strong> '+pct.toLocaleString("es-ES",{maximumFractionDigits:2})+' % del precio inicial, equivalente a '+money(inc)+' sin IVA.</div>':'<div class="info"><strong>Modificación prevista:</strong> no se ha previsto modificación al alza por mayores necesidades.</div>';return '<div id="supplyLegalClosureCard" class="card" style="margin-top:12px"><h4>5.1 Cierre jurídico-económico previo a la validación del mapeo</h4><div class="info"><strong>Presupuesto máximo registrado:</strong> '+money(budget)+' sin IVA para toda la vigencia.</div>'+mod+'<div class="info"><strong>Valor estimado validado:</strong> '+money(ve)+' sin IVA.</div><div class="info"><strong>Cierre jurídico-económico completado.</strong> Presupuesto máximo, modificación prevista y valor estimado están cerrados. Los criterios de adjudicación se controlan separadamente en el apartado 5.2.</div></div>';}
function ensureClosure(a,map){var closure=document.getElementById("supplyLegalClosureCard");if(closure)return closure;if(!economicClosed(a))return null;var h3=map.querySelector("h3");if(h3)h3.insertAdjacentHTML("afterend",closureSummary(a));else map.insertAdjacentHTML("afterbegin",closureSummary(a));return document.getElementById("supplyLegalClosureCard");}
function restoreShortDeadlineCase(a){var legacy=a.supplyAwardCriteriaMode==="MULTIPLE_FORMULA"&&a.supplyAwardCriteriaLegalReviewStatus==="RECONFIGURATION_REQUIRED"&&shortDeadline(a)&&hasModification(a);if(!legacy)return false;a.supplyAwardCriteriaMode="PRICE_ONLY";delete a.supplyAwardCriteriaStructure;a.supplyAwardCriteriaStructureValidated=false;a.supplyAwardCriteriaLegalReviewValidated=false;a.supplyAwardCriteriaLegalReviewStatus="PRICE_ONLY_SHORT_DEADLINE_SPECIFIC_REVIEW";a.supplyPriceOnlyMotivationValidated=false;a.supplyPriceOnlyMotivationStatus="CASE_SPECIFIC_REVIEW_REQUIRED";a.supplyDocumentGenerationBlockedByAwardCriteria=true;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="READY_FOR_PRICE_ONLY_SPECIFIC_REVIEW";saveAnswers(a,"restore-price-only-short-deadline");return true;}
function priceOnlyPending(a){return a.supplyAwardCriteriaMode==="PRICE_ONLY"&&hasModification(a)&&a.supplyAwardCriteriaLegalReviewValidated!==true;}
function priceOnlyValidated(a){return a.supplyAwardCriteriaMode==="PRICE_ONLY"&&a.supplyAwardCriteriaLegalReviewValidated===true&&a.supplyPriceOnlyMotivationValidated===true;}
function card(a){if(priceOnlyPending(a)&&shortDeadline(a))return '<div id="supplyAwardCriteriaVisibilityHotfixCard" class="warning" style="margin:12px 0;padding:12px"><h4>5.2 Control jurídico de los criterios de adjudicación — precio como criterio único</h4><p><strong>Plazo de partida muy reducido:</strong> '+Number(a.supplyDeliveryDeadlineDays)+' días. En este expediente no se considera adecuado convertir una reducción adicional del plazo en criterio de valoración, porque podría incentivar compromisos difíciles de cumplir de forma continuada por disponibilidad o stock.</p><p>Los artículos están técnicamente definidos y la calidad mínima se fija en el PPT. La modificación prevista responde exclusivamente al régimen excepcional de mayores necesidades de la disposición adicional 33.ª, tramitada conforme al artículo 204 LCSP, manteniendo el mismo objeto y los precios unitarios previstos.</p><p><strong>Control jurídico:</strong> el artículo 145.3.f LCSP contiene una exigencia estricta sobre modificaciones, por lo que esta solución no se aplica como regla automática general. Se mantiene por la motivación específica de este expediente y requiere validación humana expresa.</p><div class="toolbar"><button id="validateShortDeadlinePriceOnly" type="button">Validar motivación específica y mantener solo precio</button><button id="sendPriceOnlyToLegalReview" type="button" class="secondary">Remitir criterios a revisión jurídica</button></div></div>';
if(priceOnlyPending(a)&&!shortDeadline(a))return '<div id="supplyAwardCriteriaVisibilityHotfixCard" class="warning" style="margin:12px 0;padding:12px"><h4>5.2 Control jurídico de los criterios de adjudicación</h4><p>El plazo máximo de entrega es de '+Number(a.supplyDeliveryDeadlineDays||0)+' días. Al no ser un plazo de partida especialmente reducido, puede existir margen para valorar objetivamente una mejora del plazo u otro criterio vinculado al objeto, siempre que sea útil, realista y cuantificable mediante fórmula.</p><p>No se impondrá automáticamente la pluralidad: debe decidirse si existe realmente un segundo criterio adecuado.</p><div class="toolbar"><button id="reviewMultipleCriteriaOption" type="button">Revisar posible pluralidad de criterios</button><button id="sendPriceOnlyToLegalReview" type="button" class="secondary">Mantener solo precio y remitir a revisión jurídica</button></div></div>';
if(priceOnlyValidated(a))return '<div id="supplyAwardCriteriaVisibilityHotfixCard" class="info" style="margin:12px 0;padding:12px"><h4>5.2 Criterios de adjudicación cerrados</h4><p><strong>Precio como único criterio validado para este expediente.</strong> Se conserva la motivación específica: productos perfectamente definidos, calidad mínima cerrada en el PPT y plazo de entrega de '+Number(a.supplyDeliveryDeadlineDays)+' días ya suficientemente reducido, cuya disminución adicional no se considera una mejora útil y estable por el riesgo de incumplimientos ligados a stock o disponibilidad.</p><p>La modificación por mayores necesidades de la DA 33.ª se mantiene como previsión excepcional y separada, conforme al régimen del artículo 204 LCSP. La decisión queda identificada como validación específica del caso, no como regla automática general.</p></div>';
return '';}
function patchMappingText(a,map){Array.from(map.querySelectorAll("li")).forEach(function(li){var t=(li.textContent||"").trim();if(!(t.startsWith("Criterios:")||t.startsWith("Criterios de adjudicación:")))return;var label=t.startsWith("Criterios:")?'Criterios:':'Criterios de adjudicación:';if(priceOnlyValidated(a))li.innerHTML='<strong>'+label+'</strong> Precio como criterio único, con motivación específica validada para este expediente por tratarse de artículos perfectamente definidos y existir un plazo máximo de entrega ya muy reducido ('+Number(a.supplyDeliveryDeadlineDays)+' días), sin una mejora adicional útil y sostenible mediante oferta.';else if(priceOnlyPending(a))li.innerHTML='<strong>'+label+'</strong> Precio como criterio único pendiente de validación específica en el apartado 5.2.';});Array.from(map.querySelectorAll(".info,.warning")).forEach(function(x){var t=x.textContent||"";if(!t.includes("Precio como criterio único:"))return;if(priceOnlyValidated(a)){x.className="info";x.innerHTML='<strong>Precio como criterio único: motivación específica validada.</strong> Se conserva la justificación del expediente y el descarte de una reducción adicional del plazo de '+Number(a.supplyDeliveryDeadlineDays)+' días por riesgo de compromisos poco realistas vinculados a stock o disponibilidad.';}else if(priceOnlyPending(a)){x.className="warning";x.innerHTML='<strong>Precio como criterio único: validación específica pendiente.</strong> Resuelva el apartado 5.2 antes de generar documentación.';}});}
function render(){var a=readAnswers();if(restoreShortDeadlineCase(a)){location.reload();return;}a=readAnswers();var map=document.getElementById("supplyDocumentMappingCard");if(!map)return;var closure=ensureClosure(a,map);var old=document.getElementById("supplyAwardCriteriaVisibilityHotfixCard");if(old)old.remove();var oldLegacy=document.getElementById("supplyAwardCriteriaConflictCard");if(oldLegacy)oldLegacy.remove();var html=card(a);if(html){if(closure)closure.insertAdjacentHTML("afterend",html);else{var h3=map.querySelector("h3");if(h3)h3.insertAdjacentHTML("afterend",html);else map.insertAdjacentHTML("afterbegin",html);}}patchMappingText(a,map);var btn=document.getElementById("validateSupplyDocumentMapping");if(btn){var blocked=priceOnlyPending(a)||a.supplyDocumentGenerationBlockedByAwardCriteria===true;btn.disabled=blocked;btn.style.opacity=blocked?"0.55":"1";btn.title=blocked?"Debe resolverse primero el control jurídico de los criterios de adjudicación.":"";}}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==="validateShortDeadlinePriceOnly"){a.supplyAwardCriteriaMode="PRICE_ONLY";a.supplyPriceOnlyMotivationValidated=true;a.supplyPriceOnlyMotivationStatus="CASE_SPECIFIC_SHORT_DEADLINE_VALIDATED";a.supplyAwardCriteriaLegalReviewValidated=true;a.supplyAwardCriteriaLegalReviewStatus="PRICE_ONLY_SHORT_DEADLINE_CASE_SPECIFIC_VALIDATED";a.supplyAwardCriteriaLegalGrounds=["LCSP art. 145.1","LCSP art. 145.3.f","LCSP art. 146.1","LCSP DA 33","LCSP art. 204"];a.supplyAwardCriteriaLegalReason="Precio como único criterio validado específicamente para este expediente: artículos perfectamente definidos, calidad mínima cerrada y plazo máximo de entrega ya muy reducido, cuya reducción adicional no se considera una mejora útil y estable por el riesgo de compromisos difíciles de cumplir por disponibilidad o stock. La modificación por mayores necesidades se mantiene como previsión excepcional de la DA 33.ª y se tramita conforme al artículo 204 LCSP.";a.supplyDocumentGenerationBlockedByAwardCriteria=false;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="READY_FOR_REVALIDATION_AFTER_PRICE_ONLY_REVIEW";saveAnswers(a,"validate-price-only-short-deadline");location.reload();}
if(t.id==="sendPriceOnlyToLegalReview"){a.supplyAwardCriteriaLegalReviewValidated=false;a.supplyAwardCriteriaLegalReviewStatus="REFERRED_TO_LEGAL_REVIEW";a.supplyDocumentGenerationBlockedByAwardCriteria=true;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="LEGAL_REVIEW_REQUIRED";saveAnswers(a,"refer-price-only-legal-review");render();}
if(t.id==="reviewMultipleCriteriaOption"){a.supplyAwardCriteriaLegalReviewStatus="MULTIPLE_CRITERIA_OPTION_REVIEW";a.supplyDocumentGenerationBlockedByAwardCriteria=true;saveAnswers(a,"review-multiple-criteria-option");alert("Revise si existe un criterio adicional realmente útil, objetivo, vinculado al objeto y cuantificable mediante fórmula. No se añadirá automáticamente.");}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(render,0);setTimeout(render,80);});
setTimeout(render,0);setTimeout(render,120);
})();`;
