export const SUPPLY_PCAP_GLOBAL_CLOSURE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-pcap-global-closure"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function eligible(a){var b=Array.isArray(a.supplyAnnexIComprehensiveAuditBlockers)?a.supplyAnnexIComprehensiveAuditBlockers:[];return a.supplyPblBreakdownClosureValidated===true&&b.length===0;}
var LEGAL_AGENCY="Asesoría Jurídica del Servicio Andaluz de Empleo";
var LEGAL_DATE="29 de julio de 2026";
var LEGAL_REPORT="AJ-SAE 2026/16";
var SUBCONTRACT_PERCENT=20;
var LEGAL_BASIS="Artículo 215.3 LCSP: la infracción de las condiciones de subcontratación puede dar lugar, cuando así se prevea en el pliego, a una penalidad de hasta el 50 % del importe del subcontrato o, en los supuestos legalmente exigidos, a la resolución. Para este expediente se propone el 20 %, coincidente con la versión administrativa anterior del PCAP de ferretería.";
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function paragraphs(doc){var a=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));a.sort(function(x,y){if(x===y)return 0;return x.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1;});return a;}
function find(ps,needle,from){var q=norm(needle);for(var i=from||0;i<ps.length;i++)if(norm(ps[i].textContent).indexOf(q)>=0)return i;return -1;}
function setContains(ps,needle,value,from){var i=find(ps,needle,from||0);if(i>=0){ps[i].textContent=value;return i;}return -1;}
function patch(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");var ps=paragraphs(doc);
var header=setContains(ps,"Sus anexos han sido informados por la Asesoría Jurídica de","Sus anexos han sido informados por la "+LEGAL_AGENCY+" el día "+LEGAL_DATE+" (nº de informe: "+LEGAL_REPORT+").",0);if(header<0)throw new Error("No se ha localizado la línea de informe jurídico de la cabecera.");
var sub=find(ps,"SUBCONTRATACIÓN",0);if(sub<0)throw new Error("No se ha localizado el apartado 9 de subcontratación.");
var p=setContains(ps,"Penalidad del _______ % del importe del subcontrato","Penalidad del "+SUBCONTRACT_PERCENT+" % del importe del subcontrato (consecuencia seleccionada conforme al artículo 215.3 LCSP).",sub);if(p<0)p=setContains(ps,"Penalidad del ___ % del importe del subcontrato","Penalidad del "+SUBCONTRACT_PERCENT+" % del importe del subcontrato (consecuencia seleccionada conforme al artículo 215.3 LCSP).",sub);if(p<0)throw new Error("No se ha localizado el porcentaje pendiente de subcontratación.");
setContains(ps,"Resolución del contrato, siempre que suponga","Resolución del contrato: no se selecciona como consecuencia ordinaria; únicamente procederá en los supuestos y con los requisitos legalmente exigibles.",sub);
setContains(ps,"En caso afirmativo, indicar dichas partes o trabajos:","En caso afirmativo, indicar dichas partes o trabajos: No procede.",sub);
setContains(ps,"a) Régimen de abono del precio:","a) Régimen de abono del precio: No procede (no se prevén pagos directos a subcontratistas).",sub);
setContains(ps,"b) Periodicidad del pago:","b) Periodicidad del pago: No procede.",sub);
setContains(ps,"c) Registro para presentación de facturas:","c) Registro para presentación de facturas: No procede.",sub);
setContains(ps,"En caso afirmativo, especificar las penalidades en caso de que el contratista no remita","En caso afirmativo, especificar las penalidades: No procede, al haberse validado que no se establece comprobación específica adicional del artículo 217.1 LCSP.",sub);
setContains(ps,"Porcentaje reservado:","Porcentaje reservado: No procede.",sub);
setContains(ps,"Mecanismos de control:","Mecanismos de control: No procede, al no establecerse reserva de ejecución en programas de empleo protegido.",sub);
var body=norm(ps.map(function(x){return x.textContent;}).join(" "));if(body.indexOf(norm(LEGAL_REPORT))<0||body.indexOf("PENALIDAD DEL 20 % DEL IMPORTE DEL SUBCONTRATO")<0)throw new Error("La inserción no supera la comprobación final.");return new XMLSerializer().serializeToString(doc);}
async function process(bytes){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");content.data=new TextEncoder().encode(patch(new TextDecoder("utf-8").decode(content.data)));var output=writeStoredZip(entries);await readZip(output);return output;}
function download(bytes){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="CONTR-2026-240267_PCAP_Oficial_Cierre_Global_11-3_Contrata-IA.odt";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function card(){var a=readAnswers();if(!eligible(a))return "";var html='<div id="supplyPcapGlobalClosureCard" class="card" style="margin-top:14px"><h3>11.3 Auditoría y cierre global del PCAP</h3><div class="info"><strong>Anexo I cerrado.</strong> La siguiente comprobación ya afecta al PCAP completo y no vuelve a abrir decisiones cerradas del Anexo I salvo contradicción documental.</div><div class="warning"><strong>Pendientes reales detectados:</strong><ul><li>Cabecera: incorporar '+esc(LEGAL_AGENCY)+', '+esc(LEGAL_DATE)+', informe '+esc(LEGAL_REPORT)+'.</li><li>Subcontratación: fijar la consecuencia del artículo 215.3 LCSP. Propuesta: penalidad del '+SUBCONTRACT_PERCENT+' % del importe del subcontrato.</li><li>Limpiar campos subordinados que ya son No procede por decisiones previamente validadas.</li></ul><p><strong>Fundamento de la propuesta de subcontratación:</strong> '+esc(LEGAL_BASIS)+'</p></div>';
if(a.supplyPcapGlobalProposalValidated!==true){html+='<button id="validateSupplyPcapGlobalProposal" type="button">Validar propuestas del cierre global</button><button id="rejectSupplyPcapGlobalProposal" type="button" class="secondary">Revisar antes de aplicar</button>';}else if(a.supplyPcapGlobalClosureValidated!==true){html+='<div class="info"><strong>Propuestas validadas.</strong> Seleccione el último ODT con el Anexo I cerrado para incorporar la cabecera jurídica, la penalidad de subcontratación del 20 % y la limpieza de campos subordinados.</div><input id="pcapGlobalClosureFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runSupplyPcapGlobalClosure" type="button">Aplicar cierre global y generar ODT</button>';}else{html+='<div class="info"><strong>Cierre global aplicado.</strong> El siguiente paso será la auditoría de coherencia PCAP ↔ PPT ↔ memoria justificativa antes de declarar el expediente documentalmente cerrado.</div>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyPcapGlobalClosureCard");if(old)old.remove();var anchor=document.getElementById("supplyPblBreakdownProposalCard")||document.getElementById("supplyAnnexIComprehensiveAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target)return;if(e.target.id==="validateSupplyPcapGlobalProposal"){var a=readAnswers();a.supplyPcapGlobalProposalValidated=true;a.supplyLegalReportAgency=LEGAL_AGENCY;a.supplyLegalReportDate=LEGAL_DATE;a.supplyLegalReportNumber=LEGAL_REPORT;a.supplySubcontractPenaltyPercent=SUBCONTRACT_PERCENT;a.supplySubcontractConsequence="PENALTY";a.supplyPcapGlobalProposalValidatedAt=new Date().toISOString();save(a);ensure();return;}if(e.target.id==="rejectSupplyPcapGlobalProposal"){var a2=readAnswers();a2.supplyPcapGlobalProposalRejected=true;save(a2);alert("El cierre global queda pendiente de revisión. No se modificará el ODT.");return;}if(e.target.id==="runSupplyPcapGlobalClosure"){var input=document.getElementById("pcapGlobalClosureFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione el último ODT con el Anexo I cerrado.");return;}try{var output=await process(new Uint8Array(await file.arrayBuffer())),a3=readAnswers();a3.supplyPcapGlobalClosureValidated=true;a3.supplyPcapGlobalClosureAt=new Date().toISOString();save(a3);download(output);alert("Cierre global del PCAP aplicado. Se ha generado un ODT para auditoría cruzada final.");ensure();}catch(err){alert("No se ha podido aplicar el cierre global del PCAP: "+err.message);}return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;