export const SUPPLY_OFFICIAL_PCAP_ANNEX_I_COMPLETION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var OFFICIAL_MODEL_URL="https://www.juntadeandalucia.es/sites/default/files/inline-files/2026/02/2025_12_17_pcap_suministro_abierto_simplificado_abreviado_autofinanciada.odt";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0",TABLE_NS="urn:oasis:names:tc:opendocument:xmlns:table:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-annex-i-completion"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un paquete ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function patchContent(xml,a){
 var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");
 var all=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));all.sort(function(x,y){return x.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1;});
 function getAnnexIRange(){for(var i=0;i<all.length;i++){if(norm(all[i].textContent)!=="ANEXO I")continue;var ok=false;for(var j=i+1;j<Math.min(i+18,all.length);j++)if(norm(all[j].textContent).indexOf("CARACTERÍSTICAS DEL CONTRATO")>=0)ok=true;if(!ok)continue;var end=all.length;for(var k=i+1;k<all.length;k++){var et=norm(all[k].textContent);if(et==="ANEXO II"||et.indexOf("ANEXO II DECLARACIÓN RESPONSABLE")===0){end=k;break;}}return {start:i,end:end};}throw new Error("No se ha localizado el Anexo I real del modelo oficial.");}
 var bounds=getAnnexIRange(),nodes=all.slice(bounds.start,bounds.end),changes=[];
 function find(prefixes,startAt,endAt){for(var i=startAt||0;i<(endAt==null?nodes.length:endAt);i++){var t=norm(nodes[i].textContent);for(var j=0;j<prefixes.length;j++)if(t.indexOf(norm(prefixes[j]))===0)return {el:nodes[i],index:i};}return null;}
 function contains(parts,startAt,endAt){for(var i=startAt||0;i<(endAt==null?nodes.length:endAt);i++){var t=norm(nodes[i].textContent);for(var j=0;j<parts.length;j++)if(t.indexOf(norm(parts[j]))>=0)return {el:nodes[i],index:i};}return null;}
 function set(prefixes,value,key,startAt,endAt){var h=find(prefixes,startAt,endAt);if(!h)return false;h.el.textContent=value;changes.push(key);return true;}
 function setContains(parts,value,key,startAt,endAt){var h=contains(parts,startAt,endAt);if(!h)return false;h.el.textContent=value;changes.push(key);return true;}
 function addAfter(prefixes,value,key){var h=find(prefixes);if(!h||!h.el.parentNode)return false;var p=doc.createElementNS(TEXT_NS,"text:p"),style=h.el.getAttributeNS(TEXT_NS,"style-name")||h.el.getAttribute("text:style-name");if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);p.textContent=value;h.el.parentNode.insertBefore(p,h.el.nextSibling);changes.push(key);return true;}
 function section(startPrefix,endPrefix){var s=find([startPrefix]);if(!s)return null;var e=endPrefix?find([endPrefix],s.index+1):null;return {start:s.index,end:e?e.index:nodes.length};}
 function followingTable(anchor){if(!anchor)return null;var cur=anchor.el;for(var n=0;n<220&&cur;n++){if(cur.nextSibling)cur=cur.nextSibling;else{while(cur&&cur!==doc.documentElement&&!cur.nextSibling)cur=cur.parentNode;if(!cur||cur===doc.documentElement)return null;cur=cur.nextSibling;}if(cur&&cur.nodeType===1){if(cur.namespaceURI===TABLE_NS&&cur.localName==="table")return cur;var nested=cur.getElementsByTagNameNS?cur.getElementsByTagNameNS(TABLE_NS,"table"):[];if(nested.length)return nested[0];}}return null;}
 function cellSet(cell,value){while(cell.firstChild)cell.removeChild(cell.firstChild);var p=doc.createElementNS(TEXT_NS,"text:p");p.textContent=value;cell.appendChild(p);}
 function fillAnnualities(){var vals=Array.isArray(a.supplyCurrentBudgetAnnualities)?a.supplyCurrentBudgetAnnualities:[],anchor=find(["Anualidades (IVA incluido)"]),table=followingTable(anchor);if(!table||vals.length<3)return false;var rows=Array.from(table.getElementsByTagNameNS(TABLE_NS,"table-row")),data=[];rows.forEach(function(r){var c=Array.from(r.getElementsByTagNameNS(TABLE_NS,"table-cell"));if(c.length>=3&&norm(r.textContent).indexOf("AÑO")<0)data.push(c);});if(data.length<3)return false;for(var i=0;i<3;i++){cellSet(data[i][0],String(vals[i].year));cellSet(data[i][1],money(vals[i].amount));cellSet(data[i][2],String(a.supplyCurrentBudgetApplication||"1439010000 G/32L/22000/00 01"));}changes.push("A2-anualidades");return true;}
 function fillDir3(){var anchor=contains(["Datos a incluir en la factura electrónica"]),table=followingTable(anchor);if(!table)return false;var rows=Array.from(table.getElementsByTagNameNS(TABLE_NS,"table-row")),done=0;rows.forEach(function(r){var cells=Array.from(r.getElementsByTagNameNS(TABLE_NS,"table-cell"));if(cells.length<2)return;var t=norm(r.textContent);if(t.indexOf("ÓRGANO GESTOR")>=0||t.indexOf("DE CONTRATACIÓN")>=0){if(cells.length>=3){cellSet(cells[cells.length-2],"Servicio Andaluz de Empleo");cellSet(cells[cells.length-1],"A01004615");}done++;}else if(t.indexOf("UNIDAD TRAMITADORA")>=0||t.indexOf("DE DESTINO")>=0){if(cells.length>=3){cellSet(cells[cells.length-2],"Servicio Andaluz de Empleo");cellSet(cells[cells.length-1],"A01004615");}done++;}else if(t.indexOf("OFICINA CONTABLE")>=0||t.indexOf("CENTRO CONTABLE")>=0){if(cells.length>=3){cellSet(cells[cells.length-2],"Intervención General");cellSet(cells[cells.length-1],"A01004456");}done++;}});if(done){changes.push("A11-DIR3");return true;}return false;}
 var pbl=Number(a.supplyCurrentTenderBudgetExVat||10552.44),pblInc=Number(a.supplyCurrentTenderBudgetInclVat||12768.45),vat=pblInc-pbl,ve=Number(a.supplyEstimatedValueExVat||21793.15),max=Number(a.supplyMaximumApprovedBudgetExVat||18160.96),modPct=Number(a.supplyNeedsModificationMaximumIncreasePercent||20);
 set(["TÍTULO DEL CONTRATO:"],"TÍTULO DEL CONTRATO: "+String(a.contractTitle||"SUMINISTRO DE MATERIALES DE FERRETERÍA PARA LAS INSTALACIONES LOS EDIFICIOS DONDE SE UBICAN LOS SERVICIOS CENTRALES DEL SERVICIO ANDALUZ DE EMPLEO Y SUS OFICINAS ANEXAS"),"A0-titulo");
 set(["EXPEDIENTE:"],"EXPEDIENTE: "+String(a.administrativeFileNumber||"CONTR/2026/240267"),"A0-expediente");
 set(["LOCALIDAD:"],"LOCALIDAD: "+String(a.supplyMainDeliveryLocality||"SEVILLA"),"A0-localidad");
 set(["Objeto del contrato:"],"Objeto del contrato: Suministro de materiales y artículos de ferretería para pequeñas reparaciones y reposiciones en los edificios del Servicio Andaluz de Empleo.","A1-objeto");
 set(["Código CPV"],"Código CPV: 44316400-2 (Artículos de ferretería).","A1-cpv");
 set(["Lugar de entrega del suministro:"],"Lugar de entrega del suministro: instalaciones de los Servicios Centrales del Servicio Andaluz de Empleo y sus oficinas anexas en Sevilla, conforme al PPT.","A1-entrega");
 set(["División en lotes:"],"División en lotes: No.","A1-lotes");set(["Descripción de los lotes:"],"Descripción de los lotes: No procede.","A1-lotes-desc");set(["Justificación de la no división del contrato en lotes:"],"Justificación de la no división del contrato en lotes: la gestión unificada evita dificultades de coordinación y control, mantiene homogénea la calidad del suministro y permite aprovechar economías de escala en gestión, logística y transporte.","A1-lotes-just");
 set(["Limitación de presentación de lotes."],"Limitación de presentación de lotes: No procede.","A1-lim-pres");set(["Limitación de adjudicación de lotes."],"Limitación de adjudicación de lotes: No procede.","A1-lim-adj");set(["Criterios objetivos o sistemas para determinar la adjudicación de los lotes"],"Criterios objetivos o sistemas para determinar la adjudicación de los lotes: No procede.","A1-lim-crit");set(["Oferta integradora:"],"Oferta integradora: No.","A1-integr");set(["Contrato reservado DA 4ª LCSP"],"Contrato reservado DA 4.ª LCSP: No.","A1-reserva");set(["En caso afirmativo, indicar el ámbito de la reserva:"],"En caso afirmativo, indicar el ámbito de la reserva: No procede.","A1-reserva-amb");
 set(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES (DA 33.ª LCSP): Sí.","A1-da33");addAfter(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"Las cantidades de las referencias son estimativas y podrán variar según las necesidades reales, sin obligación de alcanzar las cantidades estimadas y sin superar el presupuesto máximo aprobado para toda la vigencia de "+money(max)+" sin IVA.","A1-da33-text");
 set(["1.D. RÉGIMEN JURÍDICO ESPECÍFICO"],"1.D. RÉGIMEN JURÍDICO ESPECÍFICO POR RAZÓN DEL OBJETO DEL CONTRATO: No procede.","A1-regimen");
 set(["Importe total (IVA excluido):"],"Importe total (IVA excluido): "+money(pbl),"A2-pbl");set(["Importe del IVA:"],"Importe del IVA: "+money(vat),"A2-iva");set(["Importe total (IVA incluido):"],"Importe total (IVA incluido): "+money(pblInc),"A2-total");set(["Importe desglosado:"],"Importe desglosado: determinado a partir de las cantidades estimadas y precios unitarios de las referencias del catálogo validado incorporado al PPT.","A2-desglose");fillAnnualities();set(["Tramitación del gasto:"],"Tramitación del gasto: Ordinaria.","A2-tram");
 set(["Valor estimado del contrato:"],"Valor estimado del contrato: "+money(ve)+" sin IVA.","A2-ve");set(["Método de cálculo:"],"Método de cálculo: presupuesto máximo DA 33.ª para toda la vigencia, "+money(max)+" sin IVA, más modificación prevista máxima del "+modPct.toLocaleString("es-ES")+" %, resultando "+money(ve)+" sin IVA.","A2-metodo");set(["Sistema de determinación del precio:"],"Sistema de determinación del precio: precios unitarios por referencia del catálogo validado.","A2-precio");
 set(["Revisión de precios en los contratos de suministro de fabricación"],"Revisión de precios en los contratos de suministro de fabricación, energía y demás supuestos previstos en el modelo: No.","A2-rev1");set(["Revisión de precios en los contratos en los que el período de recuperación"],"Revisión de precios cuando el período de recuperación de la inversión sea inferior a cinco años: No.","A2-rev2");set(["Variación de precios en función del cumplimiento"],"Variación de precios en función del cumplimiento o incumplimiento de objetivos: No.","A2-var");set(["Supuestos y reglas para su determinación:"],"Supuestos y reglas para su determinación: No procede.","A2-var-reglas");set(["Entrega de otros bienes de la misma clase como pago"],"Entrega de otros bienes de la misma clase como pago de parte del precio: No.","A2-bienes");set(["Posibilidad de incremento del número de unidades a suministrar de hasta el 10%"],"Posibilidad de incremento del número de unidades a suministrar de hasta el 10 % del precio del contrato: No.","A2-10");
 set(["Plazo total (en meses):"],"Plazo total (en meses): 24 meses.","A3-plazo");set(["Plazos parciales (en meses):"],"Plazos parciales: No procede como hitos temporales; cada pedido deberá entregarse en un máximo de 5 días hábiles conforme al PPT.","A3-parcial");set(["Posibilidad de prórroga:"],"Posibilidad de prórroga: Sí.","A3-prorroga");set(["Duración de la prórroga:"],"Duración de la prórroga: hasta dos prórrogas de 12 meses cada una, máximo acumulado 24 meses.","A3-dur");set(["Plazo de preaviso de la prórroga:"],"Plazo de preaviso de la prórroga: 2 meses.","A3-preaviso");
 set(["Órgano de contratación:"],"Órgano de contratación: Dirección Gerencia del Servicio Andaluz de Empleo.","A4-organo");set(["Respuestas vinculantes sobre la aclaración de los pliegos:"],"Respuestas vinculantes sobre la aclaración de los pliegos: No.","A4-vinc");set(["Procedimiento de adjudicación:"],"Procedimiento de adjudicación: Abierto simplificado abreviado.","A5-proc");set(["Tramitación del expediente:"],"Tramitación del expediente: Ordinaria.","A5-tram");set(["Constitución de mesa de contratación:"],"Constitución de mesa de contratación: Sí.","A5-mesa");set(["Posibilidad de variantes"],"Posibilidad de variantes: No.","A5-variantes");set(["En caso de renuncia:"],"En caso de renuncia: 100 euros, previa justificación de los gastos ocasionados.","A5-renuncia");set(["En caso de desistimiento:"],"En caso de desistimiento: 100 euros, previa justificación de los gastos ocasionados.","A5-desist");set(["Organismos de los que las personas licitadoras pueden obtener"],"Organismos de los que las personas licitadoras pueden obtener información sobre las obligaciones del artículo 129.1 LCSP: No procede.","A5-129");
 set(["Se exige habilitación empresarial o profesional:"],"Se exige habilitación empresarial o profesional: No.","A6-hab");set(["a. En caso de que la ejecución del contrato requiera el empleo de sistemas de información"],"a. Exigencias ENS por empleo de sistemas de información: No procede.","A6-ens");set(["b. En caso de contratos reservados, se exige habilitación como:"],"b. Habilitación para contratos reservados: No procede.","A6-res");set(["Requisitos relativos a la organización, destino de sus beneficios"],"Requisitos relativos a la organización, destino de sus beneficios, sistemas de financiación u otros: No procede.","A6-org");
 set(["Único criterio de adjudicación relacionado con los costes:"],"Único criterio de adjudicación relacionado con los costes: Sí.","A7-unico");set(["1. Proposición económica:"],"1. Proposición económica: precio, 100 puntos.","A7-precio");set(["7.B. PARÁMETROS OBJETIVOS"],"7.B. PARÁMETROS OBJETIVOS PARA CONSIDERAR UNA OFERTA ANORMALMENTE BAJA: se aplicarán los parámetros del artículo 85 RGLCAP, conforme al artículo 149.2 LCSP.","A7-baja");set(["7.C. CRITERIOS DE DESEMPATE"],"7.C. CRITERIOS DE DESEMPATE: se mantienen los criterios específicos previstos por el modelo oficial y, si persiste el empate, se aplicará el artículo 147.2 LCSP.","A7-desemp");
 set(["Condición especial de ejecución de tipo ambiental o social"],"Condición especial de ejecución de tipo ambiental o social (obligatoria): 1) las comunicaciones escritas que no estén sujetas a formalidades de la Ley 39/2015 se realizarán preferentemente por correo electrónico, evitando papel; 2) la contratista recogerá, retirará y gestionará correctamente todos los residuos generados por las entregas, incluidos embalajes, cajas, palets, flejes y recipientes de productos químicos, retirándolos en el momento de la descarga.","A8-condiciones");set(["Si la ejecución del contrato implica el acceso por la persona contratista a datos personales"],"Si la ejecución del contrato implica el acceso por la persona contratista a datos personales en poder del órgano de contratación: No procede.","A8-datos");set(["Condiciones especiales de ejecución a las que se les atribuye el carácter de obligación contractual esencial"],"Condiciones especiales de ejecución a las que se les atribuye el carácter de obligación contractual esencial a efectos del artículo 211.1.f LCSP: No.","A8-esencial");set(["Condiciones especiales de ejecución que se tipifican como infracción grave"],"Condiciones especiales de ejecución que se tipifican como infracción grave a efectos del artículo 71.2.c LCSP: Sí; el incumplimiento reiterado de la obligación de gestión de residuos tendrá esta consideración cuando se opte por la continuidad del contrato.","A8-grave");set(["Penalidades por incumplimiento de las condiciones especiales de ejecución del contrato:"],"Penalidades por incumplimiento de las condiciones especiales de ejecución del contrato: Sí. Abandono de embalajes: 300,00 € por pedido afectado. Falta de acreditación de reciclaje de envases peligrosos o componentes químicos en 10 días: 5 % del importe neto del pedido afectado. Se impondrán por acuerdo del órgano de contratación, a propuesta de la persona responsable y previa audiencia de 5 días hábiles; se deducirán de las facturas. Ninguna penalidad individual superará el 10 % del precio del contrato ni el acumulado el 50 % del presupuesto máximo. En pedidos inferiores a 200 € netos podrá moderarse la penalidad fija hasta un 50 %, motivadamente y sin reiteración.","A8-penal");
 set(["Determinadas tareas críticas"],"Determinadas tareas críticas que deban ejecutarse directamente por la contratista: No.","A9-crit");set(["La persona licitadora debe indicar en la oferta"],"La persona licitadora debe indicar en la oferta la parte prevista para subcontratar: No.","A9-ind");set(["La persona contratista debe indicar si tiene previsto subcontratar los servidores"],"Subcontratación de servidores o servicios asociados con acceso a datos personales: No procede.","A9-serv");set(["La ejecución del contrato debe ir acompañada de medidas de seguridad especiales"],"La ejecución del contrato debe ir acompañada de medidas de seguridad especiales: No.","A9-seg");set(["Se prevén pagos directos a subcontratistas:"],"Se prevén pagos directos a subcontratistas: No.","A9-pagos");set(["Comprobación por el órgano de contratación del estricto cumplimiento"],"Comprobación específica del estricto cumplimiento de pagos a subcontratistas: No.","A9-control");set(["Reserva de un porcentaje mínimo de la ejecución de contratos"],"Reserva de un porcentaje mínimo de ejecución en programas de empleo protegido: No.","A9-reserva");
 set(["Penalidades por demora en la ejecución parcial o total"],"Penalidades por demora distintas de las del artículo 193.3 LCSP: Sí. Por cada pedido entregado fuera del plazo máximo de 5 días hábiles se impondrán 10,00 € sin IVA por cada día hábil de retraso; la penalidad acumulada por pedido no podrá superar el 50 % de su valor neto.","A10-demora");set(["Penalidades por cumplimiento defectuoso:"],"Penalidades por cumplimiento defectuoso: No.","A10-def");set(["Penalidades por incumplimiento parcial"],"Penalidades por incumplimiento parcial: No.","A10-parcial");set(["Penalidades por incumplimiento de las obligaciones en materia medioambiental"],"Penalidades por incumplimiento de obligaciones medioambientales, sociales o laborales: Sí. Se estará al régimen específico del apartado 8.B para la condición de gestión de residuos.","A10-ambiental");
 set(["Pago Único /Pagos parciales:","Pago Único / Pagos parciales:"],"Pago Único / Pagos parciales: Pagos parciales.","A11-pagos");set(["En caso de pagos parciales, periodicidad:"],"En caso de pagos parciales, periodicidad: según los pedidos realizados y conformados, al no estar predeterminada la cantidad ni el momento de cada pedido.","A11-period");set(["Plazo para aprobar los documentos que acrediten la conformidad"],"Plazo para aprobar los documentos que acrediten la conformidad: máximo 30 días naturales desde la entrega y recepción material del suministro.","A11-conf");set(["Registro para presentación de facturas:"],"Registro para presentación de facturas: Punto General de Entrada de Facturas Electrónicas de la Administración General del Estado (FACe).","A11-face");fillDir3();set(["Condiciones para el abono a cuenta de operaciones preparatorias:"],"Condiciones para el abono a cuenta de operaciones preparatorias: No procede.","A11-cuenta");
 set(["Plazo de garantía:"],"Plazo de garantía: 3 años para bienes de naturaleza duradera; para fungibles o consumibles, perfecto estado, ausencia de defectos ocultos y respeto de la caducidad del fabricante.","A12-garantia");set(["Programa de trabajo:"],"Programa de trabajo: No.","A12-programa");set(["Información a la que se le atribuye carácter confidencial:"],"Información a la que se atribuye carácter confidencial: no se prevé información específicamente confidencial por razón del objeto, sin perjuicio del deber legal de confidencialidad.","A12-conf");set(["Plazo durante el que la persona contratista deberá mantener"],"Plazo del deber de confidencialidad: 5 años, salvo plazo legal superior.","A12-plazo");set(["Obligación de tener suscrito seguro"],"Obligación de tener suscrito seguro específico: No.","A12-seguro");set(["Cesión del contrato:"],"Cesión del contrato: Sí, conforme a la cláusula 15 y a la LCSP.","A12-cesion");set(["En el supuesto de suspensión del contrato acordada"],"Reglas especiales de abono de daños y perjuicios en suspensión o demora de pago: No.","A13-susp");
 var s14=section("14. MODIFICACIONES","15. TRATAMIENTO DE DATOS PERSONALES");if(s14){set(["Posibilidad de modificación del contrato:"],"Posibilidad de modificación del contrato: Sí.","A14-si",s14.start,s14.end);var c1=contains(["Según lo dispuesto en el apartado 2 de la disposición adicional cuarta de la Ley 3/2012"],s14.start,s14.end);if(c1){c1.el.textContent="1. Reducción o supresión de prestaciones por medidas de estabilidad presupuestaria: No procede para la modificación prevista en este expediente.";changes.push("A14-causa1-no");}var c2=contains(["2. _______(Indicar causa de modificación).","2. _______ (Indicar causa de modificación)."],s14.start,s14.end);if(c2){c2.el.textContent="2. Mayores necesidades reales respecto de las estimadas inicialmente, en contrato de suministro en función de las necesidades conforme a la disposición adicional 33.ª LCSP.";changes.push("A14-da33");var next3=contains(["3. _______"],c2.index+1,s14.end),end2=next3?next3.index:s14.end;set(["Alcance y límites de la modificación:"],"Alcance y límites de la modificación: aumento exclusivamente de unidades de las referencias ya incluidas, manteniendo objeto y precios unitarios adjudicados; no podrán incorporarse nuevos artículos ni nuevos precios unitarios.","A14-alcance",c2.index,end2);setContains(["Porcentaje máximo del precio del contrato al que pueda afectar"],"Porcentaje máximo del precio del contrato al que puede afectar esta causa: "+modPct.toLocaleString("es-ES")+" %.","A14-pct",c2.index,end2);if(next3){next3.el.textContent="3. Otras causas de modificación previstas: No procede.";changes.push("A14-causa3-no");}}}
 set(["La ejecución del contrato requiere el tratamiento por la persona contratista de datos personales"],"La ejecución del contrato requiere el tratamiento por la persona contratista de datos personales por cuenta de la persona responsable del tratamiento: No.","A15-datos");
 var audit=[
  ["1.D. RÉGIMEN JURÍDICO ESPECÍFICO","régimen jurídico específico"],["Importe total (IVA excluido):","PBL"],["Valor estimado del contrato:","valor estimado"],["Método de cálculo:","método de cálculo"],["Sistema de determinación del precio:","sistema de precio"],["Plazo total (en meses):","duración"],["Posibilidad de prórroga:","prórroga"],["Órgano de contratación:","órgano de contratación"],["Procedimiento de adjudicación:","procedimiento"],["Tramitación del expediente:","tramitación"],["Se exige habilitación empresarial o profesional:","habilitación"],["Único criterio de adjudicación relacionado con los costes:","criterio único"],["Condición especial de ejecución de tipo ambiental o social","condición especial"],["Penalidades por incumplimiento de las condiciones especiales de ejecución del contrato:","penalidades 8.B"],["Penalidades por demora en la ejecución parcial o total","penalidad demora"],["Pago Único /Pagos parciales:","régimen de pago"],["Plazo de garantía:","garantía"],["Posibilidad de modificación del contrato:","modificación"],["La ejecución del contrato requiere el tratamiento por la persona contratista de datos personales","tratamiento de datos"]
 ],unresolved=[];
 audit.forEach(function(x){var h=find([x[0]]),t=h?norm(h.el.textContent):"";if(!h||t.indexOf("SÍ/NO")>=0||t.indexOf("_______")>=0||t.indexOf("___")>=0)unresolved.push(x[1]);});
 if(!changes.includes("A11-DIR3"))unresolved.push("datos DIR3 de facturación");
 unresolved.push("especificaciones del objeto: volcado estructural de las 98 referencias, cantidades e importes desde el catálogo validado");
 unresolved=unresolved.filter(function(x,i,arr){return arr.indexOf(x)===i;});
 return {xml:new XMLSerializer().serializeToString(doc),changes:changes,unresolved:unresolved};
}
async function parameterize(bytes,a){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");var patched=patchContent(new TextDecoder("utf-8").decode(content.data),a);content.data=new TextEncoder().encode(patched.xml);var output=writeStoredZip(entries);await readZip(output);return {bytes:output,changes:patched.changes,unresolved:patched.unresolved};}
function download(bytes,name){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
async function fromOfficial(){var r=await fetch(OFFICIAL_MODEL_URL,{mode:"cors",cache:"no-store"});if(!r.ok)throw new Error("No se ha podido descargar el ODT oficial.");return new Uint8Array(await r.arrayBuffer());}
function card(a){var html='<div id="supplyAnnexICompletionCard" class="card" style="margin-top:14px"><h3>11.2 Cierre integral y auditoría del Anexo I</h3>';if(a.supplyOfficialFullPcapInsertionMapValidated!==true){html+='<div class="warning">Paso no habilitado: valide primero el mapa de inserción oficial.</div></div>';return html;}html+='<div class="info"><strong>Auditoría condicional.</strong> Este paso trabaja únicamente dentro del Anexo I. Los campos subordinados a decisiones ya cerradas en No o No procede no se contabilizan como pendientes. Se recuperan del expediente los DIR3, condiciones 8.A/8.B y penalidades específicas documentadas.</div><div class="warning"><strong>Bloqueo real del catálogo.</strong> La tabla de especificaciones del objeto no se cerrará mediante una cifra resumida: debe volcarse desde las 98 referencias, cantidades e importes del catálogo validado.</div><button id="generateAnnexIComplete" type="button">Generar ODT oficial con Anexo I auditado</button><p class="muted">Si el portal oficial bloquea la descarga automática, seleccione manualmente el ODT oficial original o el ODT 11.1 generado.</p><input id="annexICompletionFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="generateAnnexICompleteFromFile" type="button" class="secondary">Completar ODT seleccionado</button>';if(Array.isArray(a.supplyAnnexIUnresolvedFields)){if(a.supplyAnnexIUnresolvedFields.length===0)html+='<div class="info"><strong>Auditoría del Anexo I superada.</strong> No quedan campos bloqueantes.</div>';else html+='<div class="warning"><strong>Bloqueantes reales pendientes:</strong><ul>'+a.supplyAnnexIUnresolvedFields.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul></div>';}html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyAnnexICompletionCard");if(old)old.remove();var anchor=document.getElementById("supplyOfficialPcapOdtGeneratorCard")||document.getElementById("supplyOfficialPcapInsertionControlCard");if(anchor)anchor.insertAdjacentHTML("afterend",card(readAnswers()));}
async function run(bytes){var a=readAnswers(),result=await parameterize(bytes,a),complete=result.unresolved.length===0;a.supplyAnnexICompletionGenerated=true;a.supplyAnnexICompletionChangedDestinations=result.changes;a.supplyAnnexIUnresolvedFields=result.unresolved;a.supplyAnnexICompletionStatus=complete?"COMPLETE":"PENDING_HUMAN_COMPLETION";saveAnswers(a);download(result.bytes,"CONTR-2026-240267_PCAP_Oficial_AnexoI_Cierre_11-2_Contrata-IA.odt");alert(complete?"Anexo I completado y auditoría superada.":"ODT generado como borrador. Quedan "+result.unresolved.length+" bloqueantes reales del Anexo I.");ensure();}
document.addEventListener("click",async function(e){if(!e.target)return;if(e.target.id==="generateAnnexIComplete"){try{await run(await fromOfficial());}catch(err){alert("No fue posible la descarga automática. Use el selector de archivo. Detalle: "+err.message);}}if(e.target.id==="generateAnnexICompleteFromFile"){var input=document.getElementById("annexICompletionFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione un ODT.");return;}try{await run(new Uint8Array(await file.arrayBuffer()));}catch(err){alert("No se ha podido completar el ODT: "+err.message);}}});
document.addEventListener("contrata-ia:adaptive-saved",ensure);ensure();
})();`;
