export const SUPPLY_CROSS_DOCUMENT_CORRECTION_PROPOSAL_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-cross-document-correction-proposal"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function eligible(a){return a.supplyCrossDocumentAuditRan===true;}
var SOURCES={
 memory:"Memoria Ferretería SSCC SAE V12 · letrado",
 pcap:"PCAP suministro abierto simplificado abreviado V7 · letrado",
 ppt:"PPT Ferretería SSCC SAE V6",
 legal:"Informe de atención a AJ-SAE 2026/16"
};
var PROPOSALS=[
 {id:"MEM-VE",document:"MEMORIA",title:"Sustituir el valor estimado y su método de cálculo",current:"La Memoria V12 mantiene 25.325,86 € sin IVA y suma de nuevo las prórrogas sobre el PBL inicial.",proposal:"Valor estimado: 21.793,15 € sin IVA. Método: presupuesto máximo DA 33.ª aprobado para toda la vigencia, 18.160,96 € sin IVA, más modificación prevista máxima del 20 %, 3.632,19 €, sin volver a adicionar las prórrogas porque el presupuesto máximo ya rige para toda la vigencia.",basis:"Art. 101 LCSP + configuración DA 33.ª validada del expediente + informe AJ-SAE 2026/16."},
 {id:"MEM-MOD",document:"MEMORIA",title:"Eliminar la incorporación de artículos nuevos como causa de modificación",current:"La Memoria V12 conserva como causa la incorporación de otros artículos no contemplados en el listado.",proposal:"La modificación prevista queda limitada a mayores necesidades reales respecto de las estimadas inicialmente, mediante aumento de unidades de las referencias ya incluidas, manteniendo objeto y precios unitarios adjudicados; no se incorporan nuevos artículos ni nuevos precios unitarios.",basis:"DA 33.ª y art. 204 LCSP, conforme al informe AJ-SAE 2026/16."},
 {id:"PPT-SCOPE",document:"PPT",title:"Cerrar jurídicamente el alcance del catálogo sin convertir las cantidades en rígidas",current:"El PPT V6 califica el listado y sus cantidades como meramente orientativo, no exhaustivo ni limitativo.",proposal:"Las cantidades estimadas son orientativas y podrán variar al alza o a la baja según las necesidades reales, sin obligación de alcanzar el volumen previsto y sin superar el presupuesto máximo. El catálogo de referencias y precios unitarios constituye el marco del suministro: las variaciones afectan a unidades de las referencias previstas y no habilitan la incorporación de nuevos artículos o nuevos precios unitarios.",basis:"DA 33.ª LCSP + art. 204 LCSP + cierre jurídico del expediente. Se mantiene la posibilidad técnica de productos equivalentes cuando la propia referencia lo admita."},
 {id:"PCAP-PBL",document:"PCAP",title:"Restituir el desglose económico cuantificado del modelo real V7",current:"El PCAP generado por Contrata-IA 11.3 utiliza una explicación genérica de costes integrados en precios unitarios.",proposal:"Trasladar al apartado 2.A el desglose coincidente de los modelos reales: costes directos 76,00 % = 8.019,85 €; costes indirectos 18,00 % = 1.899,44 €; beneficio industrial 6,00 % = 633,15 €; total 100,00 % = 10.552,44 € sin IVA.",basis:"Art. 100.2 LCSP y estructura económica efectivamente utilizada tanto en la Memoria V12 como en el PCAP V7 aportados como modelos reales finales."}
];
function table(){return '<table style="width:100%;border-collapse:collapse"><thead><tr><th>Documento</th><th>Corrección propuesta</th><th>Fundamento / fuente</th></tr></thead><tbody>'+PROPOSALS.map(function(p){return '<tr><td><strong>'+esc(p.document)+'</strong></td><td><strong>'+esc(p.title)+'</strong><br><span class="muted">Situación fuente:</span> '+esc(p.current)+'<br><strong>Propuesta Contrata-IA:</strong> '+esc(p.proposal)+'</td><td>'+esc(p.basis)+'</td></tr>';}).join('')+'</tbody></table>';}
function card(){var a=readAnswers();if(!eligible(a))return "";var html='<div id="supplyCrossDocumentCorrectionProposalCard" class="card" style="margin-top:14px"><h3>11.4.1 Propuesta motivada de corrección documental</h3><div class="info"><strong>Fuentes reales finales incorporadas al contraste.</strong><ul><li>'+esc(SOURCES.memory)+'</li><li>'+esc(SOURCES.pcap)+'</li><li>'+esc(SOURCES.ppt)+'</li><li>'+esc(SOURCES.legal)+'</li></ul><p>Estos modelos se utilizan como patrón real de estructura, formato y contenido del expediente. Cuando una versión anterior entra en contradicción con la revisión jurídica posterior, prevalece la corrección expresamente motivada y validada, no la copia automática del texto histórico.</p></div><div class="warning"><strong>Refinamiento del diagnóstico 11.4.</strong> Se mantienen cuatro correcciones, pero se precisa la cuarta: el desglose 76/18/6 no es un defecto de la Memoria; aparece también en el PCAP real V7. El documento que debe adaptarse en este punto es el PCAP generado por Contrata-IA, que deberá recuperar dicho desglose cuantificado.</div>'+table();
if(a.supplyCrossDocumentCorrectionProposalValidated!==true){html+='<div class="warning"><strong>Validación humana obligatoria.</strong> Este paso todavía no modifica ningún documento. La validación autoriza únicamente a preparar las versiones corregidas conservando la estructura de los modelos reales.</div><div class="toolbar"><button id="validateSupplyCrossDocumentCorrectionProposal" type="button">Validar las 4 correcciones propuestas</button><button id="rejectSupplyCrossDocumentCorrectionProposal" type="button" class="secondary">Revisar propuestas</button></div>';}else{html+='<div class="info"><strong>Propuestas 11.4.1 validadas.</strong> Queda autorizado el siguiente subpaso para generar de forma controlada las versiones corregidas de PCAP, PPT y Memoria, manteniendo la trazabilidad de cada sustitución.</div>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyCrossDocumentCorrectionProposalCard");if(old)old.remove();var anchor=document.getElementById("supplyCrossDocumentAuditCard")||document.getElementById("supplyPcapGlobalClosureCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="validateSupplyCrossDocumentCorrectionProposal"){var a=readAnswers();a.supplyCrossDocumentCorrectionProposalValidated=true;a.supplyCrossDocumentCorrectionProposalValidatedAt=new Date().toISOString();a.supplyCrossDocumentCorrectionSources=SOURCES;a.supplyCrossDocumentCorrectionIds=PROPOSALS.map(function(p){return p.id;});save(a);ensure();return;}if(e.target.id==="rejectSupplyCrossDocumentCorrectionProposal"){var a2=readAnswers();a2.supplyCrossDocumentCorrectionProposalRejected=true;a2.supplyCrossDocumentCorrectionProposalRejectedAt=new Date().toISOString();save(a2);alert("Las propuestas quedan pendientes de revisión. No se modificará ningún documento.");return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;