export const SUPPLY_CROSS_DOCUMENT_AUDIT_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-cross-document-audit"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function eligible(a){return a.supplyPcapGlobalClosureValidated===true;}
var SOURCE_MATRIX={
 pcap:"PCAP oficial · cierre global 11.3",
 ppt:"PPT Feretería SSCC SAE V6",
 memory:"Memoría Ferretería SSCC SAE V11",
 legal:"Informe de atención a AJ-SAE 2026/16"
};
var CANON={expediente:"CONTR/2026/240267",cpv:"44316400-2",pbl:"10.552,44",budget:"18.160,96",ve:"21.793,15",duration:"24 meses",delivery:"5 días hábiles",pricePoints:"100 puntos",modPercent:"20 %",legalReport:"AJ-SAE 2026/16",catalogueCount:98};
var SOURCE_BLOCKERS=[
 {id:"MEM-VE",severity:"CRÍTICA",title:"Valor estimado desactualizado en la Memoria V11",detail:"La Memoria V11 conserva 25.325,86 € sin IVA, calculado añadiendo prórrogas y una modificación del 20 %. La configuración validada del expediente fija 21.793,15 € sin IVA."},
 {id:"MEM-MOD",severity:"CRÍTICA",title:"La Memoria V11 conserva una causa de modificación ya descartada",detail:"La Memoria V11 permite incorporar artículos no contemplados. El informe de atención a AJ-SAE 2026/16 elimina esa posibilidad: la modificación DA 33.ª debe mantener el mismo objeto y los precios unitarios previstos, sin nuevos artículos ni nuevos precios."},
 {id:"CAT-SCOPE",severity:"CRÍTICA",title:"PPT V6 y Memoria V11 describen el catálogo como no exhaustivo ni limitativo",detail:"Esa redacción es incompatible con el cierre jurídico posterior del expediente. Las cantidades pueden variar, pero las referencias/precios unitarios deben permanecer dentro del catálogo validado; las nuevas necesidades no habilitan por sí mismas nuevos artículos."},
 {id:"PBL-BREAKDOWN",severity:"ALTA",title:"Desglose del PBL no idéntico entre PCAP y Memoria",detail:"La Memoria V11 contiene un desglose cuantificado: costes directos 76 % = 8.019,85 €; costes indirectos 18 % = 1.899,44 €; beneficio industrial 6 % = 633,15 €. El PCAP 11.3 utiliza una explicación genérica de costes integrados. Debe decidirse una única redacción económica y trasladarse de forma coherente."}
];
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readContentXml(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8");for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed);if(name==="content.xml"){var data=method===0?raw:await inflateRaw(raw);return dec.decode(data);}pos+=46+nameLen+extraLen+commentLen;}throw new Error("ODT sin content.xml.");}
function xmlText(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");return norm(doc.documentElement.textContent||"");}
function hasAny(body,vals){return vals.some(function(v){return body.indexOf(norm(v))>=0;});}
function physicalAudit(body){var checks=[
 {id:"PCAP-EXP",label:"Expediente",ok:body.indexOf(norm(CANON.expediente))>=0,expected:CANON.expediente},
 {id:"PCAP-CPV",label:"CPV",ok:body.indexOf(CANON.cpv)>=0,expected:CANON.cpv},
 {id:"PCAP-PBL",label:"PBL inicial",ok:hasAny(body,["10.552,44","10552,44"]),expected:"10.552,44 € sin IVA"},
 {id:"PCAP-BUDGET",label:"Presupuesto máximo DA 33.ª",ok:hasAny(body,["18.160,96","18160,96"]),expected:"18.160,96 € sin IVA"},
 {id:"PCAP-VE",label:"Valor estimado",ok:hasAny(body,["21.793,15","21793,15"]),expected:"21.793,15 € sin IVA"},
 {id:"PCAP-DURATION",label:"Duración",ok:body.indexOf("24 MESES")>=0,expected:"24 meses + prórrogas máximas conjuntas de 24 meses"},
 {id:"PCAP-PRICE",label:"Precio como criterio único",ok:body.indexOf("100 PUNTOS")>=0&&body.indexOf("ÚNICO CRITERIO")>=0,expected:"precio, 100 puntos"},
 {id:"PCAP-MOD",label:"Modificación DA 33.ª",ok:body.indexOf("DISPOSICIÓN ADICIONAL 33")>=0&&hasAny(body,["20 %","20%"]),expected:"máximo 20 %, mismo objeto/precios"},
 {id:"PCAP-AJ",label:"Informe jurídico",ok:body.indexOf(CANON.legalReport)>=0,expected:CANON.legalReport}
 ];return checks;}
function runAudit(body){var physical=physicalAudit(body),blockers=SOURCE_BLOCKERS.slice();physical.forEach(function(c){if(!c.ok)blockers.unshift({id:c.id,severity:"CRÍTICA",title:"PCAP 11.3 no contiene el dato físico esperado: "+c.label,detail:"Valor esperado: "+c.expected+"."});});return {physical:physical,blockers:blockers};}
function renderPhysical(checks){return '<table style="width:100%;border-collapse:collapse"><thead><tr><th>Control físico PCAP</th><th>Resultado</th><th>Valor esperado</th></tr></thead><tbody>'+checks.map(function(c){return '<tr><td>'+esc(c.label)+'</td><td>'+(c.ok?'✓ Coincide':'⚠ No coincide')+'</td><td>'+esc(c.expected)+'</td></tr>';}).join('')+'</tbody></table>';}
function renderBlockers(blockers){return blockers.length?'<div class="warning"><strong>Incoherencias documentales que impiden cerrar el expediente:</strong><ol>'+blockers.map(function(b){return '<li><strong>['+esc(b.severity)+'] '+esc(b.title)+'</strong><br>'+esc(b.detail)+'</li>';}).join('')+'</ol></div>':'<div class="info"><strong>Auditoría cruzada superada.</strong> No quedan incoherencias entre los documentos de referencia.</div>';}
function card(){var a=readAnswers();if(!eligible(a))return "";var html='<div id="supplyCrossDocumentAuditCard" class="card" style="margin-top:14px"><h3>11.4 Auditoría cruzada PCAP ↔ PPT ↔ Memoria ↔ informe jurídico</h3><div class="info"><strong>Fuentes de contraste del expediente.</strong><ul><li>'+esc(SOURCE_MATRIX.pcap)+'</li><li>'+esc(SOURCE_MATRIX.ppt)+'</li><li>'+esc(SOURCE_MATRIX.memory)+'</li><li>'+esc(SOURCE_MATRIX.legal)+'</li></ul><p>La aplicación comprueba físicamente el PCAP ODT y lo contrasta con una matriz de control extraída de las fuentes administrativas validadas del expediente. Los PDF fuente no se reescriben automáticamente en este paso.</p></div>';
if(a.supplyCrossDocumentAuditRan!==true){html+='<div class="warning"><strong>Puerta de coherencia documental.</strong> Seleccione el ODT generado en 11.3. La auditoría bloqueará el cierre si la Memoria/PPT conservan versiones anteriores incompatibles con las correcciones derivadas del informe AJ-SAE 2026/16.</div><input id="crossDocumentPcapFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runSupplyCrossDocumentAudit" type="button">Auditar coherencia documental 11.4</button>';}else{html+=renderPhysical(a.supplyCrossDocumentPhysicalChecks||[])+renderBlockers(a.supplyCrossDocumentAuditBlockers||[]);if(a.supplyCrossDocumentAuditBlockers&&a.supplyCrossDocumentAuditBlockers.length){if(a.supplyCrossDocumentDiagnosisValidated!==true){html+='<div class="toolbar"><button id="validateCrossDocumentDiagnosis" type="button">Validar diagnóstico y preparar correcciones</button><button id="rerunCrossDocumentAudit" type="button" class="secondary">Repetir auditoría</button></div>';}else{html+='<div class="info"><strong>Diagnóstico validado.</strong> El siguiente paso será corregir de forma controlada la Memoria, el PPT y, en su caso, el desglose económico del PCAP, sin alterar las decisiones jurídicas ya cerradas.</div>';}}else{html+='<div class="info"><strong>Expediente documental coherente.</strong> PCAP, PPT, Memoria e informe jurídico superan la matriz de consistencia.</div>';}}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyCrossDocumentAuditCard");if(old)old.remove();var anchor=document.getElementById("supplyPcapGlobalClosureCard")||document.getElementById("supplyPblBreakdownProposalCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target)return;if(e.target.id==="runSupplyCrossDocumentAudit"){var input=document.getElementById("crossDocumentPcapFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione el ODT generado en el Paso 11.3.");return;}try{var body=xmlText(await readContentXml(new Uint8Array(await file.arrayBuffer()))),result=runAudit(body),a=readAnswers();a.supplyCrossDocumentAuditRan=true;a.supplyCrossDocumentPhysicalChecks=result.physical;a.supplyCrossDocumentAuditBlockers=result.blockers;a.supplyCrossDocumentAuditSources=SOURCE_MATRIX;a.supplyCrossDocumentAuditAt=new Date().toISOString();save(a);ensure();alert("Auditoría cruzada completada. Se han detectado "+result.blockers.length+" incoherencias/bloqueantes documentales.");}catch(err){alert("No se ha podido ejecutar la auditoría cruzada: "+err.message);}return;}if(e.target.id==="validateCrossDocumentDiagnosis"){var a2=readAnswers();a2.supplyCrossDocumentDiagnosisValidated=true;a2.supplyCrossDocumentDiagnosisValidatedAt=new Date().toISOString();save(a2);ensure();return;}if(e.target.id==="rerunCrossDocumentAudit"){var a3=readAnswers();delete a3.supplyCrossDocumentAuditRan;delete a3.supplyCrossDocumentPhysicalChecks;delete a3.supplyCrossDocumentAuditBlockers;delete a3.supplyCrossDocumentDiagnosisValidated;save(a3);ensure();return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;