export const SUPPLY_CROSS_DOCUMENT_CORRECTION_GENERATOR_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-cross-document-correction-generator"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function eligible(a){return a.supplyCrossDocumentCorrectionProposalValidated===true;}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un paquete ODT/DOCX válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function parseXml(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar el XML del documento.");return doc;}
function odtParagraphs(doc){var a=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));a.sort(function(x,y){if(x===y)return 0;return x.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1;});return a;}
function findParagraph(ps,needle,from){var q=norm(needle);for(var i=from||0;i<ps.length;i++)if(norm(ps[i].textContent).indexOf(q)>=0)return i;return -1;}
function setText(node,text){while(node.firstChild)node.removeChild(node.firstChild);node.appendChild(node.ownerDocument.createTextNode(text));}
function patchPcapOdt(xml){var doc=parseXml(xml),ps=odtParagraphs(doc),start=findParagraph(ps,"2.A.PRESUPUESTO BASE DE LICITACIÓN",0);if(start<0)start=findParagraph(ps,"2.A. PRESUPUESTO BASE DE LICITACIÓN",0);var end=findParagraph(ps,"2.B.VALOR ESTIMADO DEL CONTRATO",start>=0?start:0);if(start<0||end<0||end<=start)throw new Error("No se ha delimitado de forma segura el apartado 2.A del PCAP.");var marker=findParagraph(ps,"Importe desglosado",start);if(marker<0||marker>=end)throw new Error("No se ha localizado el destino «Importe desglosado» del apartado 2.A.");var target=[];for(var i=marker+1;i<end;i++){var t=norm(ps[i].textContent);if(t.indexOf("DESGLOSE TÉCNICO-ECONÓMICO")>=0||t.indexOf("COSTES DIRECTOS")>=0||/_{3,}/.test(String(ps[i].textContent||"")))target.push(ps[i]);}
if(!target.length)throw new Error("El PCAP no contiene una zona de desglose reconocible; se cancela para no alterar contenido ajeno.");var lines=["Costes directos: 76,00 % = 8.019,85 €.","Costes indirectos: 18,00 % = 1.899,44 €.","Beneficio industrial: 6,00 % = 633,15 €.","TOTAL: 100,00 % = 10.552,44 € sin IVA."];
setText(target[0],lines.join(" "));for(var j=1;j<target.length;j++)setText(target[j],"");var body=norm(ps.slice(start,end).map(function(p){return p.textContent;}).join(" "));if(body.indexOf("8.019,85")<0||body.indexOf("1.899,44")<0||body.indexOf("633,15")<0||body.indexOf("10.552,44")<0)throw new Error("La corrección del desglose del PBL no supera la verificación física.");return new XMLSerializer().serializeToString(doc);}
function patchPptOdt(xml){var doc=parseXml(xml),ps=odtParagraphs(doc),idx=findParagraph(ps,"El listado de productos y sus cantidades estimadas tienen carácter meramente orientativo",0);if(idx<0)throw new Error("No se ha localizado de forma inequívoca el párrafo de alcance del catálogo del PPT V6.");var replacement="El listado de productos constituye el catálogo de referencias y precios unitarios del contrato. Las cantidades estimadas tienen carácter meramente orientativo y podrán variar al alza o a la baja en función de las necesidades reales de cada instalación, sin que el órgano de contratación esté obligado a alcanzar el volumen previsto y sin que pueda superarse el presupuesto máximo del contrato. Las variaciones de necesidad afectarán a unidades de las referencias ya incluidas y no habilitarán la incorporación de nuevos artículos ni de nuevos precios unitarios, sin perjuicio de la posibilidad de ofertar productos equivalentes cuando así se admita expresamente en la descripción técnica de la referencia.";setText(ps[idx],replacement);var body=norm(doc.documentElement.textContent||"");if(body.indexOf("NO HABILITARÁN LA INCORPORACIÓN DE NUEVOS ARTÍCULOS")<0||body.indexOf("PRESUPUESTO MÁXIMO")<0)throw new Error("La corrección del alcance del catálogo no supera la verificación física.");return new XMLSerializer().serializeToString(doc);}
function patchMemoryOdt(xml){var doc=parseXml(xml),ps=odtParagraphs(doc),start=findParagraph(ps,"Valor Estimado del Contrato",0),end=findParagraph(ps,"4.3. Distribución de Anualidades",start>=0?start:0);if(start<0||end<0||end<=start)throw new Error("No se ha podido delimitar de forma segura el bloque 4.2 de valor estimado de la Memoria editable.");var first=ps[start];var text="Valor Estimado del Contrato: A efectos del artículo 101 de la LCSP, el valor estimado se fija en 21.793,15 € sin IVA. Método de cálculo: presupuesto máximo aprobado para toda la vigencia del contrato conforme a la disposición adicional trigésima tercera, 18.160,96 € sin IVA, más la modificación prevista máxima del 20 %, equivalente a 3.632,19 €. Las prórrogas no se adicionan de nuevo al cálculo porque el presupuesto máximo aprobado ya se configura para toda la vigencia. La modificación prevista queda limitada a mayores necesidades reales respecto de las inicialmente estimadas, mediante aumento de unidades de las referencias ya incluidas, manteniendo el mismo objeto y los precios unitarios adjudicados; no se incorporarán nuevos artículos ni nuevos precios unitarios.";setText(first,text);for(var i=start+1;i<end;i++)setText(ps[i],"");var body=norm(doc.documentElement.textContent||"");if(body.indexOf("21.793,15")<0||body.indexOf("3.632,19")<0||body.indexOf("NO SE INCORPORARÁN NUEVOS ARTÍCULOS")<0)throw new Error("La corrección económica de la Memoria no supera la verificación física.");return new XMLSerializer().serializeToString(doc);}
async function patchPackage(file,kind){var bytes=new Uint8Array(await file.arrayBuffer()),entries=await readZip(bytes),entry=entries.find(function(e){return e.name==="content.xml";});if(!entry)throw new Error("Para conservar la estructura del modelo, este generador requiere un archivo ODT editable como origen.");var xml=new TextDecoder("utf-8").decode(entry.data),patched=kind==="pcap"?patchPcapOdt(xml):kind==="ppt"?patchPptOdt(xml):patchMemoryOdt(xml);entry.data=new TextEncoder().encode(patched);var out=writeStoredZip(entries);await readZip(out);return out;}
function download(bytes,name){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function status(a,key,label){return a[key]===true?' <span style="color:#176b45">✓ '+esc(label)+' generado y verificado</span>':'';}
function card(){var a=readAnswers();if(!eligible(a))return "";var html='<div id="supplyCrossDocumentCorrectionGeneratorCard" class="card" style="margin-top:14px"><h3>11.4.2 Generación controlada de documentos corregidos</h3><div class="info"><strong>Correcciones 11.4.1 validadas.</strong> Este paso modifica únicamente los destinos documentales expresamente aprobados y verifica físicamente el resultado antes de descargarlo.</div><div class="warning"><strong>Regla de conservación de formato.</strong> Para no reconstruir de forma aproximada los documentos, la corrección se aplica sobre archivos ODT editables. Los PDF aportados se mantienen como fuente de contraste, no se convierten silenciosamente en plantillas editables.</div>';
html+='<h4>PCAP corregido</h4><p>Use el último ODT del PCAP generado por Contrata-IA. Se sustituirá únicamente el desglose del apartado 2.A por el desglose real 76/18/6.</p><input id="crossCorrectionPcapFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="generateCorrectedPcap" type="button">Generar PCAP corregido</button>'+status(a,"supplyCrossCorrectionPcapGenerated","PCAP");
html+='<h4>PPT corregido</h4><p>Seleccione el PPT V6 editable. Se cerrará el alcance del catálogo manteniendo variables las cantidades estimadas.</p><input id="crossCorrectionPptFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="generateCorrectedPpt" type="button">Generar PPT corregido</button>'+status(a,"supplyCrossCorrectionPptGenerated","PPT");
html+='<h4>Memoria corregida</h4><p>Seleccione la versión editable ODT de la Memoria V12. El PDF aportado ya sirve como patrón y fuente probatoria, pero no debe remaquetarse automáticamente si queremos conservar fielmente su estructura administrativa.</p><input id="crossCorrectionMemoryFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="generateCorrectedMemory" type="button">Generar Memoria corregida</button>'+status(a,"supplyCrossCorrectionMemoryGenerated","Memoria");
if(a.supplyCrossCorrectionPcapGenerated===true&&a.supplyCrossCorrectionPptGenerated===true&&a.supplyCrossCorrectionMemoryGenerated===true){html+='<div class="info"><strong>Paquete de corrección 11.4.2 completado.</strong> Los tres documentos editables han sido generados y comprobados. El siguiente paso será repetir la auditoría cruzada sobre las versiones corregidas.</div>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyCrossDocumentCorrectionGeneratorCard");if(old)old.remove();var anchor=document.getElementById("supplyCrossDocumentCorrectionProposalCard")||document.getElementById("supplyCrossDocumentAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
async function run(inputId,kind,stateKey,name){var input=document.getElementById(inputId),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione primero el archivo ODT editable correspondiente.");return;}try{var out=await patchPackage(file,kind),a=readAnswers();a[stateKey]=true;a[stateKey+"At"]=new Date().toISOString();save(a);download(out,name);ensure();alert("Documento corregido y verificado: "+name);}catch(err){alert("No se ha generado el documento: "+err.message);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="generateCorrectedPcap"){run("crossCorrectionPcapFile","pcap","supplyCrossCorrectionPcapGenerated","CONTR-2026-240267_PCAP_Corregido_11-4-2_Contrata-IA.odt");return;}if(e.target.id==="generateCorrectedPpt"){run("crossCorrectionPptFile","ppt","supplyCrossCorrectionPptGenerated","CONTR-2026-240267_PPT_Corregido_11-4-2_Contrata-IA.odt");return;}if(e.target.id==="generateCorrectedMemory"){run("crossCorrectionMemoryFile","memory","supplyCrossCorrectionMemoryGenerated","CONTR-2026-240267_Memoria_Corregida_11-4-2_Contrata-IA.odt");return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;