export const SUPPLY_LEGAL_CLOSURE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-legal-closure"}}));}
function parseNumber(v){var s=String(v||"").trim().replaceAll("€","").replaceAll(" ","");if(!s)return NaN;var c=s.lastIndexOf(","),d=s.lastIndexOf(".");if(c>=0&&d>=0){if(c>d)s=s.replaceAll(".","").replace(",",".");else s=s.replaceAll(",","");}else if(c>=0)s=s.replace(",",".");else if(d>=0){var p=s.split(".");if(p.length>2||((p[p.length-1]||"").length===3&&p.length===2))s=p.join("");}return Number(s);}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function closureReady(a){var budget=Number(a.supplyMaximumApprovedBudgetExVat||0)>0&&a.supplyMaximumApprovedBudgetValidated===true;var mod=a.supplyNeedsModificationForeseen===false||(a.supplyNeedsModificationForeseen===true&&Number(a.supplyNeedsModificationMaximumIncreaseExVat||0)>=0&&a.supplyNeedsModificationValidated===true);var vec=Number(a.supplyEstimatedValueExVat||0)>0&&a.supplyEstimatedValueValidated===true;var price=a.supplyAwardCriteriaMode!=="PRICE_ONLY"||a.supplyPriceOnlyMotivationValidated===true;return budget&&mod&&vec&&price;}
function render(){var map=document.getElementById("supplyDocumentMappingCard");if(!map)return;var old=document.getElementById("supplyLegalClosureCard");if(old)old.remove();var a=readAnswers();var budget=Number(a.supplyMaximumApprovedBudgetExVat||0);var modKnown=a.supplyNeedsModificationForeseen===true||a.supplyNeedsModificationForeseen===false;var modIncrease=Number(a.supplyNeedsModificationMaximumIncreaseExVat||0);var vec=budget+(a.supplyNeedsModificationForeseen===true?modIncrease:0);var priceOnly=a.supplyAwardCriteriaMode==="PRICE_ONLY";var html='<div id="supplyLegalClosureCard" class="card" style="margin-top:12px"><h4>5.1 Cierre jurídico-económico previo al mapeo</h4>';
if(!(budget>0&&a.supplyMaximumApprovedBudgetValidated===true)){html+='<div class="warning"><strong>Presupuesto máximo de toda la vigencia pendiente.</strong><p>En este suministro por necesidades, indique el límite económico máximo aprobado para toda la vigencia contractual, incluidas las prórrogas. La prórroga no incrementa automáticamente este límite.</p><input id="supplyMaximumApprovedBudget" inputmode="decimal" placeholder="Importe máximo sin IVA"><button id="saveSupplyMaximumApprovedBudget" type="button">Guardar y validar presupuesto máximo</button></div>';}
else{html+='<div class="info"><strong>Presupuesto máximo validado:</strong> '+money(budget)+' sin IVA para toda la vigencia contractual.</div>';}
if(budget>0&&a.supplyMaximumApprovedBudgetValidated===true&&!modKnown){html+='<div class="warning"><strong>Modificación por mayores necesidades.</strong><p>¿Se prevé expresamente en los pliegos una modificación al alza si las necesidades reales superan las inicialmente estimadas, manteniendo el mismo objeto y los precios unitarios previstos?</p><select id="supplyNeedsModificationForeseen"><option value="">Seleccione</option><option value="true">Sí</option><option value="false">No</option></select><button id="saveSupplyNeedsModificationDecision" type="button">Guardar decisión</button></div>';}
if(a.supplyNeedsModificationForeseen===true&&a.supplyNeedsModificationValidated!==true){html+='<div class="warning"><strong>Importe máximo de la modificación prevista.</strong><p>Indique el incremento máximo sin IVA que podría alcanzar esa modificación. Este dato se incorpora al cálculo del valor estimado conforme al artículo 101.2.c LCSP.</p><input id="supplyNeedsModificationMaximumIncrease" inputmode="decimal" placeholder="Importe máximo adicional sin IVA"><button id="saveSupplyNeedsModificationMaximumIncrease" type="button">Guardar y calcular valor estimado</button></div>';}
if(a.supplyNeedsModificationForeseen===false&&a.supplyNeedsModificationValidated!==true){html+='<button id="validateNoSupplyNeedsModification" type="button">Confirmar que no se prevé modificación al alza</button>';}
if(budget>0&&a.supplyMaximumApprovedBudgetValidated===true&&a.supplyNeedsModificationValidated===true){html+='<div class="info"><strong>Valor estimado propuesto:</strong> '+money(vec)+' sin IVA. Se toma el importe máximo pagadero estimado y, cuando existe modificación prevista al alza, el máximo que puede alcanzar el contrato. La proyección de consumo queda separada y no se usa automáticamente como valor estimado.</div>';if(a.supplyEstimatedValueValidated!==true)html+='<button id="validateSupplyEstimatedValue" type="button">Validar valor estimado propuesto</button>';else html+='<div class="info"><strong>Valor estimado validado:</strong> '+money(a.supplyEstimatedValueExVat)+' sin IVA.</div>';}
if(priceOnly){if(a.supplyPriceOnlyMotivationValidated!==true){html+='<div class="warning"><strong>Validación específica del precio como único criterio.</strong><p>Para mantenerlo deben concurrir en este expediente las circunstancias de la motivación reforzada: artículos perfectamente definidos, calidad mínima cerrada en el PPT, plazo de entrega uniforme y no mejorable mediante oferta, y compatibilidad con el régimen de modificaciones previsto. El expediente de referencia fija además 5 días hábiles como condición homogénea de ejecución.</p><button id="validateSupplyPriceOnlyMotivation" type="button">Validar que concurren estas circunstancias</button><button id="rejectSupplyPriceOnlyMotivation" type="button" class="secondary">Revisar criterios de adjudicación</button></div>';}else html+='<div class="info"><strong>Motivación del precio único validada para este expediente.</strong> Se conservará su justificación específica para la Memoria y el PCAP, sujeta a verificación normativa final.</div>';}
if(closureReady(a))html+='<div class="info"><strong>Cierre previo completado.</strong> Ya puede validarse el mapeo documental.</div>';else html+='<div class="warning"><strong>Mapeo bloqueado.</strong> Complete los extremos anteriores antes de validarlo.</div>';
html+='</div>';
var toolbar=Array.from(map.querySelectorAll('.toolbar')).find(function(x){return x.querySelector('#validateSupplyDocumentMapping');});if(toolbar)toolbar.insertAdjacentHTML('beforebegin',html);else map.insertAdjacentHTML('beforeend',html);
var btn=document.getElementById('validateSupplyDocumentMapping');if(btn){btn.disabled=!closureReady(a);btn.style.opacity=closureReady(a)?'1':'0.55';btn.title=closureReady(a)?'':'Debe cerrar antes presupuesto máximo, valor estimado y, en su caso, la motivación del precio único.';}
}
work.addEventListener('click',function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==='saveSupplyMaximumApprovedBudget'){var el=document.getElementById('supplyMaximumApprovedBudget'),n=parseNumber(el?el.value:'');if(!Number.isFinite(n)||n<=0){alert('Indique un presupuesto máximo válido.');return;}a.supplyMaximumApprovedBudgetExVat=Number(n.toFixed(2));a.supplyMaximumApprovedBudgetValidated=true;a.supplyEstimatedValueValidated=false;saveAnswers(a,'supply-maximum-budget');render();}
if(t.id==='saveSupplyNeedsModificationDecision'){var el2=document.getElementById('supplyNeedsModificationForeseen');if(!el2||!el2.value){alert('Seleccione una opción.');return;}a.supplyNeedsModificationForeseen=el2.value==='true';a.supplyNeedsModificationValidated=false;a.supplyEstimatedValueValidated=false;if(!a.supplyNeedsModificationForeseen)delete a.supplyNeedsModificationMaximumIncreaseExVat;saveAnswers(a,'supply-modification-decision');render();}
if(t.id==='saveSupplyNeedsModificationMaximumIncrease'){var el3=document.getElementById('supplyNeedsModificationMaximumIncrease'),n2=parseNumber(el3?el3.value:'');if(!Number.isFinite(n2)||n2<0){alert('Indique un importe máximo adicional válido.');return;}a.supplyNeedsModificationMaximumIncreaseExVat=Number(n2.toFixed(2));a.supplyNeedsModificationValidated=true;a.supplyEstimatedValueValidated=false;saveAnswers(a,'supply-modification-maximum');render();}
if(t.id==='validateNoSupplyNeedsModification'){a.supplyNeedsModificationValidated=true;a.supplyNeedsModificationMaximumIncreaseExVat=0;a.supplyEstimatedValueValidated=false;saveAnswers(a,'supply-no-modification');render();}
if(t.id==='validateSupplyEstimatedValue'){var b=Number(a.supplyMaximumApprovedBudgetExVat||0),m=a.supplyNeedsModificationForeseen===true?Number(a.supplyNeedsModificationMaximumIncreaseExVat||0):0;if(!(b>0)||!a.supplyNeedsModificationValidated){alert('Faltan datos para cerrar el valor estimado.');return;}a.supplyEstimatedValueExVat=Number((b+m).toFixed(2));a.supplyEstimatedValueValidated=true;a.supplyEstimatedValueStatus='VALIDATED_ART_101';saveAnswers(a,'supply-estimated-value');render();}
if(t.id==='validateSupplyPriceOnlyMotivation'){a.supplyPriceOnlyMotivationValidated=true;a.supplyPriceOnlyMotivationStatus='CASE_SPECIFIC_VALIDATED_REQUIRES_FINAL_LEGAL_CHECK';saveAnswers(a,'supply-price-only-motivation');render();}
if(t.id==='rejectSupplyPriceOnlyMotivation'){a.supplyAwardCriteriaMode='MULTIPLE_FORMULA';a.supplyPriceOnlyMotivationValidated=false;a.supplyPriceOnlyMotivationStatus='REJECTED_REVIEW_CRITERIA';a.supplyDocumentMappingValidated=false;saveAnswers(a,'supply-price-only-rejected');location.reload();}
},true);
work.addEventListener('click',function(event){var t=event.target;if(!t||t.id!=='validateSupplyDocumentMapping')return;var a=readAnswers();if(!closureReady(a)){event.preventDefault();event.stopImmediatePropagation();alert('Antes de validar el mapeo debe cerrar el presupuesto máximo, el valor estimado y, en su caso, la motivación del precio único.');}},true);
document.addEventListener('contrata-ia:adaptive-saved',function(){setTimeout(render,0);});var obs=new MutationObserver(function(){render();});obs.observe(work,{childList:true,subtree:true});render();
})();`;
