export const SUPPLY_QUALIFICATION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");
if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-qualification"}}));}
function branchReady(){var txt=work.textContent||"";return txt.includes("Rama de suministro avanzada")||txt.includes("plazo de entrega y régimen básico de conformidad");}
function isAbbreviated(){return (work.textContent||"").includes("Abierto simplificado abreviado");}
function legalDraftText(){return "Solvencia. De conformidad con el artículo 159.6.b de la Ley 9/2017, de 8 de noviembre, de Contratos del Sector Público, en este procedimiento abierto simplificado abreviado los licitadores quedan exentos de acreditar la solvencia económica y financiera y la solvencia técnica o profesional. Esta exención se refiere a su acreditación en el procedimiento y no elimina las condiciones generales de aptitud para contratar. Aptitud para contratar. Se mantienen las condiciones generales de aptitud previstas en los artículos 65 y 71 de la LCSP: plena capacidad de obrar, ausencia de prohibiciones de contratar y, cuando resulte exigible por el objeto de la prestación, la habilitación empresarial o profesional correspondiente. Garantía provisional. No procede su constitución conforme al artículo 159.4.b de la LCSP. Garantía definitiva. De acuerdo con el artículo 159.6.f de la LCSP, no se requiere garantía definitiva en esta tramitación abreviada. Condición especial de ejecución. En cumplimiento del artículo 202.1 de la LCSP se incorpora una condición especial vinculada a la ejecución consistente en la correcta gestión y retirada de los embalajes y residuos generados directamente por las entregas, evitando embalajes innecesarios cuando sea compatible con la adecuada protección del producto. La redacción definitiva deberá comprobarse frente a la normativa vigente y al modelo de pliego aplicable antes de cerrar el expediente.";}
function legalGrounds(){return ["LCSP art. 159.6.b","LCSP art. 159.4.b","LCSP art. 159.6.f","LCSP arts. 65 y 71","LCSP art. 202.1"];}
function migrateValidatedDraft(){var a=readAnswers();if(a.supplyLegalBlockValidated!==true||a.supplyPcapLegalDraft)return false;a.supplySolvencyAccreditation=a.supplySolvencyAccreditation||"EXEMPT_ART_159_6_B";a.supplyProvisionalGuarantee=a.supplyProvisionalGuarantee||"NOT_REQUIRED_ART_159_4_B";a.supplyDefinitiveGuarantee=a.supplyDefinitiveGuarantee||"NOT_REQUIRED_ART_159_6_F";a.supplySpecialExecutionCondition=a.supplySpecialExecutionCondition||"DELIVERY_PACKAGING_WASTE_ART_202_1";a.supplyPcapLegalDraft=legalDraftText();a.supplyPcapLegalGrounds=legalGrounds();saveAnswers(a,"supply-legal-block-migrated");return true;}
function legalDraftHtml(){return '<div class="card" style="margin-top:12px"><h4>Redacción para incorporar al PCAP / documentación preparatoria</h4><p><strong>Solvencia.</strong> De conformidad con el <strong>artículo 159.6.b LCSP</strong>, en el procedimiento abierto simplificado abreviado los licitadores quedan exentos de <strong>acreditar</strong> la solvencia económica y financiera y la solvencia técnica o profesional. Esta exención afecta a la acreditación en el procedimiento y no elimina las condiciones generales de aptitud para contratar.</p><p><strong>Aptitud para contratar.</strong> Se mantienen las condiciones generales de los <strong>artículos 65 y 71 LCSP</strong>: plena capacidad de obrar, ausencia de prohibiciones de contratar y, cuando resulte exigible por el objeto, la habilitación empresarial o profesional correspondiente.</p><p><strong>Garantía provisional.</strong> No procede su constitución conforme al <strong>artículo 159.4.b LCSP</strong>.</p><p><strong>Garantía definitiva.</strong> De acuerdo con el <strong>artículo 159.6.f LCSP</strong>, no se requiere garantía definitiva en esta tramitación abreviada.</p><p><strong>Condición especial de ejecución.</strong> En cumplimiento del <strong>artículo 202.1 LCSP</strong>, se propone incorporar la correcta gestión y retirada de los embalajes y residuos generados directamente por las entregas, evitando embalajes innecesarios cuando sea compatible con la adecuada protección del producto.</p><p class="muted">Este texto queda marcado como contenido documental validado. Antes del cierre del expediente deberá comprobarse su adecuación al texto vigente de la LCSP y al modelo de pliego aplicable.</p></div>';}
function proposal(a){var abbreviated=isAbbreviated();var html='<div id="supplyQualificationCard" class="card"><h3>3. Aptitud, solvencia, garantías y condiciones de ejecución</h3>';
if(abbreviated){html+='<div class="info"><strong>Propuesta jurídica automática según el procedimiento seleccionado</strong><ul><li><strong>Solvencia:</strong> los licitadores quedan exentos de acreditar solvencia económica y financiera y técnica o profesional.</li><li><strong>Garantía provisional:</strong> no procede en el procedimiento abierto simplificado.</li><li><strong>Garantía definitiva:</strong> no se requiere en la tramitación abreviada.</li><li><strong>Aptitud para contratar:</strong> se mantienen las exigencias legales generales de capacidad, ausencia de prohibiciones de contratar y, cuando proceda, habilitación profesional.</li></ul><p class="muted">Fundamento: artículos 159.6.b, 159.4.b, 159.6.f, 65 y 71 LCSP. La configuración se somete a validación humana y verificación normativa vigente antes de cerrar los pliegos.</p></div>';}else{html+='<div class="warning"><strong>Régimen de solvencia y garantías pendiente de propuesta automática.</strong> El procedimiento mostrado no es el simplificado abreviado. Contrata-IA debe aplicar las reglas específicas del procedimiento y del tipo de contrato antes de trasladar requisitos al PCAP.</div>';}
html+='<div class="info"><strong>Condición especial de ejecución propuesta</strong><p>Para este suministro de artículos con entregas sucesivas, se propone como condición vinculada a la ejecución la correcta gestión y retirada de embalajes y residuos generados directamente por las entregas, evitando embalajes innecesarios cuando sea compatible con la protección del producto.</p><p class="muted">El artículo 202.1 LCSP obliga a establecer en el PCAP al menos una condición especial de ejecución entre las previstas legalmente, vinculada al objeto del contrato y respetando las restantes exigencias del precepto. Esta redacción debe validarse antes de incorporarse al PCAP.</p></div>';
if(a.supplyLegalBlockValidated===true){html+='<div class="info"><strong>Bloque 3 validado por la persona usuaria.</strong> La conclusión jurídica queda aceptada y su motivación legal se conserva como contenido para los pliegos.</div>';if(abbreviated)html+=legalDraftHtml();}else if(a.supplyLegalBlockCorrectionRequested===true){html+='<label><strong>Indique qué aspecto debe corregirse</strong></label><textarea id="supplyLegalCorrection" placeholder="Explique el cambio necesario en solvencia, garantías o condición especial de ejecución">'+esc(a.supplyLegalCorrection||"")+'</textarea><button id="saveSupplyLegalCorrection" type="button">Guardar corrección pendiente</button>';}else{html+='<div class="toolbar"><button id="validateSupplyLegalBlock" type="button">Validar propuesta y conservar redacción jurídica</button><button id="correctSupplyLegalBlock" type="button" class="secondary">Necesito corregirla</button></div>';}
html+='</div>';return html;}
function ensure(){if(migrateValidatedDraft())return;var existing=document.getElementById("supplyQualificationCard");if(!branchReady()){if(existing)existing.remove();return;}var economic=document.getElementById("supplyEconomicPeriodCard");if(existing){if(economic&&existing.previousElementSibling!==economic)economic.insertAdjacentElement("afterend",existing);return;}if(economic)economic.insertAdjacentHTML("afterend",proposal(readAnswers()));else{var catalogue=document.getElementById("supplyCatalogueCard");if(catalogue)catalogue.insertAdjacentHTML("afterend",proposal(readAnswers()));else work.insertAdjacentHTML("beforeend",proposal(readAnswers()));}}
function rerender(){var old=document.getElementById("supplyQualificationCard");if(old)old.remove();ensure();}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==="validateSupplyLegalBlock"){a.supplyLegalBlockValidated=true;a.supplySolvencyAccreditation="EXEMPT_ART_159_6_B";a.supplyProvisionalGuarantee="NOT_REQUIRED_ART_159_4_B";a.supplyDefinitiveGuarantee="NOT_REQUIRED_ART_159_6_F";a.supplySpecialExecutionCondition="DELIVERY_PACKAGING_WASTE_ART_202_1";a.supplyPcapLegalDraft=legalDraftText();a.supplyPcapLegalGrounds=legalGrounds();delete a.supplyLegalBlockCorrectionRequested;delete a.supplyLegalCorrection;saveAnswers(a,"supply-legal-block-validated");rerender();}if(t.id==="correctSupplyLegalBlock"){a.supplyLegalBlockCorrectionRequested=true;saveAnswers(a,"supply-legal-block-correction-requested");rerender();}if(t.id==="saveSupplyLegalCorrection"){var el=document.getElementById("supplyLegalCorrection");if(!el||!el.value.trim()){alert("Indique qué aspecto debe corregirse.");return;}a.supplyLegalCorrection=el.value.trim();a.supplyLegalBlockValidated=false;delete a.supplyPcapLegalDraft;delete a.supplyPcapLegalGrounds;saveAnswers(a,"supply-legal-block-correction");rerender();}});
var observer=new MutationObserver(function(){ensure();});observer.observe(work,{childList:true,subtree:true});ensure();
})();`;
