export const SUPPLY_CROSS_DOCUMENT_FINAL_AUDIT_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-cross-document-final-audit"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function eligible(a){return a.supplyCrossCorrectionPcapGenerated===true&&a.supplyCrossCorrectionPptGenerated===true&&a.supplyCrossCorrectionMemoryGenerated===true;}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readContentXml(file){var bytes=new Uint8Array(await file.arrayBuffer()),e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo «"+file.name+"» no es un ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8");for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido en «"+file.name+"».");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed);if(name==="content.xml"){var data=method===0?raw:await inflateRaw(raw);return dec.decode(data);}pos+=46+nameLen+extraLen+commentLen;}throw new Error("ODT sin content.xml: "+file.name);}
function textFromXml(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");return norm(doc.documentElement.textContent||"");}
function has(body,needle){return body.indexOf(norm(needle))>=0;}function hasAny(body,vals){return vals.some(function(v){return has(body,v);});}
function check(id,document,label,ok,expected,detail){return {id:id,document:document,label:label,ok:!!ok,expected:expected,detail:detail||""};}
function auditPcap(body){return [
check("PCAP-PBL","PCAP","PBL inicial",hasAny(body,["10.552,44","10552,44"]),"10.552,44 € sin IVA"),
check("PCAP-DIRECT","PCAP","Costes directos 76 %",has(body,"8.019,85")&&hasAny(body,["76,00 %","76 %"]),"8.019,85 € · 76 %"),
check("PCAP-INDIRECT","PCAP","Costes indirectos 18 %",has(body,"1.899,44")&&hasAny(body,["18,00 %","18 %"]),"1.899,44 € · 18 %"),
check("PCAP-PROFIT","PCAP","Beneficio industrial 6 %",has(body,"633,15")&&hasAny(body,["6,00 %","6 %"]),"633,15 € · 6 %"),
check("PCAP-BUDGET","PCAP","Presupuesto máximo DA 33.ª",hasAny(body,["18.160,96","18160,96"]),"18.160,96 € sin IVA"),
check("PCAP-VE","PCAP","Valor estimado",hasAny(body,["21.793,15","21793,15"]),"21.793,15 € sin IVA"),
check("PCAP-PRICE","PCAP","Precio como criterio único",has(body,"100 PUNTOS")&&has(body,"ÚNICO CRITERIO"),"Precio · 100 puntos"),
check("PCAP-DA33","PCAP","Modificación prevista",has(body,"DISPOSICIÓN ADICIONAL 33")&&hasAny(body,["20 %","20%"])&&has(body,"NUEVOS PRECIOS UNITARIOS"),"DA 33.ª · máximo 20 % · sin nuevos precios")
];}
function auditPpt(body){return [
check("PPT-IDENTITY","PPT","Identificación del expediente",hasAny(body,["CONTR/2026/240267","CONTR-2026-240267"]),"Expediente CONTR/2026/240267"),
check("PPT-DELIVERY","PPT","Plazo de entrega",hasAny(body,["CINCO (5) DÍAS HÁBILES","CINCO(5) DÍAS HÁBILES","5 DÍAS HÁBILES"]),"cinco (5) días hábiles"),
check("PPT-CATALOGUE-CLOSED","PPT","Catálogo cerrado",has(body,"NO HABILITARÁN LA INCORPORACIÓN DE NUEVOS ARTÍCULOS")&&has(body,"NUEVOS PRECIOS UNITARIOS"),"Cantidades variables; sin nuevas referencias/precios"),
check("PPT-OLD-SCOPE","PPT","Eliminación de redacción obsoleta",!has(body,"NO EXHAUSTIVO NI LIMITATIVO"),"No debe figurar «no exhaustivo ni limitativo»"),
check("PPT-BUDGET","PPT","Límite por presupuesto máximo",has(body,"PRESUPUESTO MÁXIMO"),"Variación de cantidades sin superar presupuesto máximo")
];}
function auditMemory(body){return [
check("MEM-PBL","MEMORIA","PBL inicial",hasAny(body,["10.552,44","10552,44"]),"10.552,44 € sin IVA"),
check("MEM-DIRECT","MEMORIA","Desglose 76/18/6",has(body,"8.019,85")&&has(body,"1.899,44")&&has(body,"633,15")&&hasAny(body,["76,00 %","76 %"])&&hasAny(body,["18,00 %","18 %"])&&hasAny(body,["6,00 %","6 %"]),"8.019,85 + 1.899,44 + 633,15 · 76/18/6"),
check("MEM-BUDGET","MEMORIA","Presupuesto máximo DA 33.ª",hasAny(body,["18.160,96","18160,96"]),"18.160,96 € sin IVA"),
check("MEM-VE","MEMORIA","Valor estimado corregido",hasAny(body,["21.793,15","21793,15"]),"21.793,15 € sin IVA"),
check("MEM-OLD-VE","MEMORIA","Eliminación de VE anterior",!hasAny(body,["25.325,86","25325,86"]),"No debe permanecer 25.325,86 €"),
check("MEM-MOD","MEMORIA","Modificación DA 33.ª cerrada",has(body,"MAYORES NECESIDADES REALES")&&has(body,"NO SE INCORPORARÁN NUEVOS ARTÍCULOS")&&has(body,"NUEVOS PRECIOS UNITARIOS"),"Más unidades de referencias existentes; sin artículos/precios nuevos"),
check("MEM-MOD-20","MEMORIA","Modificación máxima 20 %",hasAny(body,["20 %","20%"])&&hasAny(body,["3.632,19","3632,19"]),"20 % = 3.632,19 €")
];}
function commonChecks(pcap,ppt,memory){return [
check("X-CPV","CRUZADO","CPV coherente",has(pcap,"44316400-2")&&has(memory,"44316400-2"),"44316400-2 en PCAP y Memoria; el PPT se vincula por expediente"),
check("X-PPT-IDENTITY","CRUZADO","PPT vinculado al expediente",hasAny(ppt,["CONTR/2026/240267","CONTR-2026-240267"]),"PPT inequívocamente vinculado a CONTR/2026/240267"),
check("X-DURATION","CRUZADO","Duración coherente",has(pcap,"24 MESES")&&has(memory,"24 MESES"),"24 meses y prórrogas conforme a configuración validada"),
check("X-DA33","CRUZADO","Régimen DA 33.ª coherente",has(pcap,"DISPOSICIÓN ADICIONAL 33")&&has(memory,"DISPOSICIÓN ADICIONAL")&&has(ppt,"PRESUPUESTO MÁXIMO"),"Necesidades variables bajo presupuesto máximo"),
check("X-NO-NEW-ITEMS","CRUZADO","Sin artículos/precios nuevos",has(pcap,"NUEVOS PRECIOS UNITARIOS")&&has(ppt,"NUEVOS PRECIOS UNITARIOS")&&has(memory,"NUEVOS PRECIOS UNITARIOS"),"Prohibición coherente en PCAP, PPT y Memoria")
];}
function summarize(checks){var blockers=checks.filter(function(c){return !c.ok;}).map(function(c){return {id:c.id,severity:"BLOQUEANTE",document:c.document,title:c.label,detail:"Esperado: "+c.expected+(c.detail?" · "+c.detail:"")};});return {checks:checks,blockers:blockers};}
async function run(files){var px=await readContentXml(files.pcap),tx=await readContentXml(files.ppt),mx=await readContentXml(files.memory),pcap=textFromXml(px),ppt=textFromXml(tx),memory=textFromXml(mx),checks=auditPcap(pcap).concat(auditPpt(ppt)).concat(auditMemory(memory)).concat(commonChecks(pcap,ppt,memory));return summarize(checks);}
function checksTable(checks){return '<table style="width:100%;border-collapse:collapse"><thead><tr><th>Documento</th><th>Control</th><th>Resultado</th><th>Esperado</th></tr></thead><tbody>'+checks.map(function(c){return '<tr><td>'+esc(c.document)+'</td><td>'+esc(c.label)+'</td><td>'+(c.ok?'✓ Correcto':'⚠ Bloqueante')+'</td><td>'+esc(c.expected)+'</td></tr>';}).join('')+'</tbody></table>';}
function blockersBox(blockers){if(!blockers.length)return '<div class="info"><strong>Auditoría final 11.4.3 superada.</strong> PCAP, PPT y Memoria corregidos presentan 0 incoherencias documentales en la matriz del expediente.</div>';return '<div class="warning"><strong>Incoherencias que impiden cerrar el expediente:</strong><ol>'+blockers.map(function(b){return '<li><strong>['+esc(b.document)+'] '+esc(b.title)+'</strong><br>'+esc(b.detail)+'</li>';}).join('')+'</ol></div>';}
function card(){var a=readAnswers();if(!eligible(a))return "";var html='<div id="supplyCrossDocumentFinalAuditCard" class="card" style="margin-top:14px"><h3>11.4.3 Auditoría final de coherencia documental</h3><div class="info"><strong>Puerta final del expediente piloto.</strong> Seleccione PCAP y PPT corregidos de 11.4.2 y, tras la calibración, la Memoria 11.4.3A. La comprobación se realiza sobre el contenido físico de los archivos.</div><div class="warning"><strong>Criterio de aceptación:</strong> 0 incoherencias reales. La matriz está calibrada contra los modelos administrativos reales: el PPT se identifica por expediente y no se le exige un campo CPV inexistente en su modelo.</div>';
if(a.supplyCrossDocumentFinalAuditRan!==true){html+='<h4>PCAP corregido</h4><input id="finalAuditPcapFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><h4>PPT corregido</h4><input id="finalAuditPptFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><h4>Memoria corregida</h4><input id="finalAuditMemoryFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runSupplyCrossDocumentFinalAudit" type="button">Ejecutar auditoría final 11.4.3</button>';}else{html+=checksTable(a.supplyCrossDocumentFinalChecks||[])+blockersBox(a.supplyCrossDocumentFinalBlockers||[]);if((a.supplyCrossDocumentFinalBlockers||[]).length===0){if(a.supplyCrossDocumentFinalAuditValidated!==true){html+='<div class="warning"><strong>Validación humana final.</strong> El resultado automatizado es favorable. Confirme el cierre antes de registrar este expediente como caso de regresión.</div><button id="validateSupplyCrossDocumentFinalAudit" type="button">Validar cierre 11.4.3 y registrar caso de regresión</button>';}else{html+='<div class="info"><strong>Expediente documental cerrado.</strong> Caso de regresión registrado: CONTR-2026-240267-SUPPLY-DA33-GOLDEN-001.</div>';}}else{html+='<button id="rerunSupplyCrossDocumentFinalAudit" type="button" class="secondary">Repetir auditoría con documentos corregidos</button>';}}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyCrossDocumentFinalAuditCard");if(old)old.remove();var anchor=document.getElementById("supplyCrossDocumentCorrectionGeneratorCard")||document.getElementById("supplyCrossDocumentCorrectionProposalCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target)return;if(e.target.id==="runSupplyCrossDocumentFinalAudit"){var p=document.getElementById("finalAuditPcapFile"),t=document.getElementById("finalAuditPptFile"),m=document.getElementById("finalAuditMemoryFile"),pf=p&&p.files&&p.files[0],tf=t&&t.files&&t.files[0],mf=m&&m.files&&m.files[0];if(!pf||!tf||!mf){alert("Seleccione los tres ODT corregidos.");return;}try{var result=await run({pcap:pf,ppt:tf,memory:mf}),a=readAnswers();a.supplyCrossDocumentFinalAuditRan=true;a.supplyCrossDocumentFinalChecks=result.checks;a.supplyCrossDocumentFinalBlockers=result.blockers;a.supplyCrossDocumentFinalAuditAt=new Date().toISOString();save(a);ensure();alert("Auditoría final 11.4.3 completada. Incoherencias reales: "+result.blockers.length+".");}catch(err){alert("No se ha podido ejecutar la auditoría final: "+err.message);}return;}if(e.target.id==="rerunSupplyCrossDocumentFinalAudit"){var a2=readAnswers();delete a2.supplyCrossDocumentFinalAuditRan;delete a2.supplyCrossDocumentFinalChecks;delete a2.supplyCrossDocumentFinalBlockers;delete a2.supplyCrossDocumentFinalAuditValidated;save(a2);ensure();return;}if(e.target.id==="validateSupplyCrossDocumentFinalAudit"){var a3=readAnswers(),b=Array.isArray(a3.supplyCrossDocumentFinalBlockers)?a3.supplyCrossDocumentFinalBlockers:[];if(a3.supplyCrossDocumentFinalAuditRan!==true||b.length!==0){alert("No puede cerrarse el expediente mientras existan incoherencias documentales.");return;}a3.supplyCrossDocumentFinalAuditValidated=true;a3.supplyCrossDocumentFinalAuditValidatedAt=new Date().toISOString();a3.supplyGoldenRegressionCaseId="CONTR-2026-240267-SUPPLY-DA33-GOLDEN-001";a3.supplyGoldenRegressionCaseStatus="VALIDATED_DOCUMENTARY_GOLDEN_CASE";save(a3);ensure();return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;