export const SUPPLY_OFFICIAL_PCAP_ODT_GENERATOR_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var OFFICIAL_MODEL_URL="https://www.juntadeandalucia.es/sites/default/files/inline-files/2026/02/2025_12_17_pcap_suministro_abierto_simplificado_abreviado_autofinanciada.odt";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-official-pcap-odt"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function ready(a){return a.supplyOfficialFullPcapInsertionMapValidated===true&&a.supplyOfficialFullPcapInsertionPolicy==="COPY_OFFICIAL_ODT_AND_REPLACE_ONLY_ANNEX_I_VARIABLE_DESTINATIONS";}
function u16(bytes,pos){return bytes[pos]|(bytes[pos+1]<<8);}
function u32(bytes,pos){return (bytes[pos]|(bytes[pos+1]<<8)|(bytes[pos+2]<<16)|(bytes[pos+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}
function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;for(var i=0;i<parts.length;i++)n+=parts[i].length;var out=new Uint8Array(n),p=0;for(var j=0;j<parts.length;j++){out.set(parts[j],p);p+=parts[j].length;}return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){if(typeof DecompressionStream!=="function")throw new Error("Este navegador no permite descomprimir el ODT automáticamente.");var ds=new DecompressionStream("deflate-raw");var ab=await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer();return new Uint8Array(ab);}
async function readZip(bytes){var eocd=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){eocd=i;break;}}if(eocd<0)throw new Error("El archivo no es un paquete ODT/ZIP válido.");var count=u16(bytes,eocd+10),pos=u32(bytes,eocd+16),enc=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=enc.decode(bytes.slice(pos+46,pos+46+nameLen));if(u32(bytes,localOffset)!==0x04034b50)throw new Error("Entrada ODT inválida: "+name);var localName=u16(bytes,localOffset+26),localExtra=u16(bytes,localOffset+28),start=localOffset+30+localName+localExtra,raw=bytes.slice(start,start+compressed),data;if(method===0)data=raw;else if(method===8)data=await inflateRaw(raw);else throw new Error("Método ZIP no soportado en "+name+": "+method);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});for(var i=0;i<ordered.length;i++){var e=ordered[i],name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;}var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function norm(v){return String(v||"").replace(/\s+/g," ").trim().toUpperCase();}
function patchContent(xml,a){var parser=new DOMParser(),doc=parser.parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml del ODT.");var nodes=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h"))),changes=[];
function find(prefixes){for(var i=0;i<nodes.length;i++){var t=norm(nodes[i].textContent);for(var j=0;j<prefixes.length;j++)if(t.indexOf(norm(prefixes[j]))===0)return nodes[i];}return null;}
function set(prefixes,value,key){var el=find(prefixes);if(!el)return false;el.textContent=value;changes.push(key);return true;}
function addAfter(prefixes,value,key){var el=find(prefixes);if(!el||!el.parentNode)return false;var p=doc.createElementNS(TEXT_NS,"text:p");var style=el.getAttributeNS(TEXT_NS,"style-name")||el.getAttribute("text:style-name");if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);p.textContent=value;el.parentNode.insertBefore(p,el.nextSibling);changes.push(key);return true;}
var pbl=Number(a.supplyCurrentTenderBudgetExVat||0),pblInc=Number(a.supplyCurrentTenderBudgetInclVat||0),vat=pblInc-pbl,ve=Number(a.supplyEstimatedValueExVat||0),max=Number(a.supplyMaximumApprovedBudgetExVat||0),modPct=Number(a.supplyNeedsModificationMaximumIncreasePercent||20);
set(["Expediente:"],"Expediente: "+String(a.administrativeFileNumber||"CONTR/2026/240267"),"cabecera-expediente");
set(["Titulo:","Título:"],"Título: "+String(a.contractTitle||""),"cabecera-titulo");
set(["Localidad de entrega:"],"Localidad de entrega: "+String(a.supplyMainDeliveryLocality||"SEVILLA"),"cabecera-localidad");
set(["Código NUTS del lugar principal de ejecución:"],"Código NUTS del lugar principal de ejecución: "+String(a.supplyMainExecutionNuts||"ES618"),"cabecera-nuts");
set(["Código CPV:"],"Código CPV: 44316400-2 (Artículos de ferretería).","cabecera-cpv");
set(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES (DA 33ª LCSP): Sí","1c-da33");
addAfter(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"Presupuesto máximo aprobado para toda la vigencia, incluidas las prórrogas: "+money(max)+" sin IVA. Las cantidades son estimativas y las prórrogas no incrementan automáticamente este límite.","1c-maximo");
set(["Importe total (IVA excluido):"],"Importe total (IVA excluido): "+money(pbl),"2a-pbl-sin-iva");
set(["Importe del IVA:"],"Importe del IVA: "+money(vat),"2a-iva");
set(["Importe total (IVA incluido):"],"Importe total (IVA incluido): "+money(pblInc),"2a-pbl-iva");
addAfter(["Anualidades (IVA incluido)"],"Anualidades validadas: "+(Array.isArray(a.supplyCurrentBudgetAnnualities)?a.supplyCurrentBudgetAnnualities.map(function(x){return String(x.year)+" · "+String(a.supplyCurrentBudgetApplication||"")+" · "+money(x.amount);}).join(" | "):""),"2a-anualidades");
set(["Valor estimado del contrato:"],"Valor estimado del contrato: "+money(ve)+" sin IVA.","2b-valor-estimado");
addAfter(["2.B.VALOR ESTIMADO DEL CONTRATO","2.B. VALOR ESTIMADO DEL CONTRATO"],"Método de cálculo validado: presupuesto máximo DA 33.ª para toda la vigencia "+money(max)+" sin IVA, más modificación prevista máxima del "+modPct.toLocaleString("es-ES")+" %, resultando un valor estimado de "+money(ve)+" sin IVA.","2b-metodo");
set(["Sistema de determinación del precio"],"Sistema de determinación del precio: Precio unitario por referencia del catálogo validado de 98 artículos.","2c-precio");
addAfter(["3. DURACIÓN","3. PLAZO"],"Duración inicial: 24 meses. Prórroga 1: 12 meses. Prórroga 2: 12 meses. En contratos DA 33.ª no procede prorrogar si el presupuesto máximo se ha agotado antes, salvo regularización legal previa.","3-duracion");
addAfter(["7. CRITERIOS DE ADJUDICACIÓN"],"Precio como único criterio: 100 puntos. Parámetros de anormalidad conforme al artículo 149.2 LCSP y artículo 85 RGLCAP. Desempate: aplicación supletoria del artículo 147.2 LCSP.","7-criterios");
addAfter(["8. CONDICIÓN","8. CONDICIONES"],"Condición especial de ejecución validada: gestión y retirada de embalajes y residuos vinculados directamente a las entregas, conforme al artículo 202.1 LCSP.","8-condicion");
addAfter(["10. PENALIDADES"],"No se establecen penalidades específicas adicionales; resulta de aplicación el régimen legal correspondiente, incluida la demora conforme al artículo 193 LCSP.","10-penalidades");
set(["Posibilidad de modificación del contrato:"],"Posibilidad de modificación del contrato: Sí","14-si");
addAfter(["14. MODIFICACIONES DEL CONTRATO"],"Modificación prevista por mayores necesidades hasta un máximo del "+modPct.toLocaleString("es-ES")+" %, conforme a la disposición adicional 33.ª y al artículo 204 LCSP, manteniendo el mismo objeto y los precios unitarios previstos. No podrán introducirse artículos ni precios unitarios nuevos.","14-modificacion");
var required=["cabecera-expediente","cabecera-titulo","1c-da33","2a-pbl-sin-iva","2b-valor-estimado","14-si"],missing=required.filter(function(x){return changes.indexOf(x)<0;});if(missing.length)throw new Error("El ODT no coincide suficientemente con el modelo validado. Destinos no reconocidos: "+missing.join(", ")+".");return {xml:new XMLSerializer().serializeToString(doc),changes:changes};}
async function parameterize(bytes,a){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";}),mime=entries.find(function(e){return e.name==="mimetype";});if(!content||!mime)throw new Error("El archivo seleccionado no es un ODT válido.");var text=new TextDecoder("utf-8").decode(content.data),patched=patchContent(text,a);content.data=new TextEncoder().encode(patched.xml);return {bytes:writeStoredZip(entries),changes:patched.changes};}
function download(bytes,name){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
async function fromOfficial(){var response=await fetch(OFFICIAL_MODEL_URL,{mode:"cors",cache:"no-store"});if(!response.ok)throw new Error("No se ha podido descargar el ODT oficial (HTTP "+response.status+").");return new Uint8Array(await response.arrayBuffer());}
function card(a){var html='<div id="supplyOfficialPcapOdtGeneratorCard" class="card" style="margin-top:14px"><h3>11. Generación del DPCAF / PCAP oficial editable</h3>';if(!ready(a)){html+='<div class="warning"><strong>Paso todavía no habilitado.</strong> Debe validarse primero el mapa de inserción del Paso 10.</div></div>';return html;}html+='<div class="info"><strong>Plantilla oficial bloqueada.</strong> El generador trabaja sobre el ODT oficial de Suministro · abierto simplificado abreviado · autofinanciado, actualizado en diciembre de 2025. Solo se modifica content.xml y se conservan los restantes recursos del paquete.</div><div class="warning"><strong>Control de seguridad documental.</strong> Si el archivo no contiene los destinos esenciales del Anexo I, la generación se cancela. El resultado seguirá requiriendo revisión humana antes de aprobarse o firmarse.</div><button id="generateOfficialPcapOdt" type="button">Generar ODT oficial parametrizado</button><p class="muted">Si la descarga automática del portal de la Junta fuera bloqueada por el navegador, seleccione manualmente el mismo ODT oficial:</p><input id="officialPcapOdtFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="generateOfficialPcapOdtFromFile" type="button" class="secondary">Generar desde ODT oficial seleccionado</button><p><a href="'+OFFICIAL_MODEL_URL+'" target="_blank" rel="noopener">Abrir/descargar ODT oficial de la Junta de Andalucía</a></p>';if(a.supplyOfficialFullPcapOdtGenerated===true)html+='<div class="info"><strong>ODT oficial parametrizado generado.</strong> Destinos modificados en la última generación: '+esc((a.supplyOfficialFullPcapOdtChangedDestinations||[]).join(", "))+'.</div>';html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyOfficialPcapOdtGeneratorCard");if(old)old.remove();var a=readAnswers(),anchor=document.getElementById("supplyOfficialPcapInsertionControlCard");if(!anchor)return;anchor.insertAdjacentHTML("afterend",card(a));}
async function run(bytes){var a=readAnswers();if(!ready(a)){alert("Debe validarse primero el Paso 10.");return;}try{var result=await parameterize(bytes,a),name=String(a.administrativeFileNumber||"CONTR-2026-240267").replaceAll("/","-")+"_PCAP_Oficial_Parametrizado_Contrata-IA.odt";download(result.bytes,name);a.supplyOfficialFullPcapOdtGenerated=true;a.supplyOfficialFullPcapOdtGeneratedAt=new Date().toISOString();a.supplyOfficialFullPcapOdtChangedDestinations=result.changes;a.supplyOfficialFullPcapOdtSource=OFFICIAL_MODEL_URL;a.supplyOfficialFullPcapOdtStatus="OFFICIAL_ODT_PARAMETERIZED_PENDING_HUMAN_REVIEW";saveAnswers(a,"supply-official-pcap-odt-generated");ensure();}catch(error){alert("No se ha generado el ODT: "+(error&&error.message?error.message:String(error)));}}
work.addEventListener("click",async function(event){var t=event.target;if(!t)return;if(t.id==="generateOfficialPcapOdt"){t.disabled=true;try{await run(await fromOfficial());}catch(error){alert("La descarga automática del ODT oficial no ha sido posible. Use el selector de archivo inferior. Detalle: "+(error&&error.message?error.message:String(error)));}finally{t.disabled=false;}}if(t.id==="generateOfficialPcapOdtFromFile"){var input=document.getElementById("officialPcapOdtFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione primero el ODT oficial.");return;}t.disabled=true;try{await run(new Uint8Array(await file.arrayBuffer()));}finally{t.disabled=false;}}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,25);});setTimeout(ensure,100);setTimeout(ensure,500);setTimeout(ensure,1500);setTimeout(ensure,3000);
})();`;
