export const SUPPLY_OFFICIAL_TEMPLATE_PARAMETERIZATION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers",catalogueKey="contrataIaSupplyCatalogue";
var FERRETERIA_CASE={
  templateId:"JDA-PCAP-SUPPLY-OSA-SELF-2025-12",
  fileNumber:"CONTR/2026/240267",
  title:"SUMINISTRO DE MATERIALES DE FERRETERÍA PARA LAS INSTALACIONES LOS EDIFICIOS DONDE SE UBICAN LOS SERVICIOS CENTRALES DEL SERVICIO ANDALUZ DE EMPLEO Y SUS OFICINAS ANEXAS",
  locality:"SEVILLA",
  nuts:"ES618",
  cpv:"44316400-2",
  cpvLabel:"Artículos de ferretería"
};
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function readCatalogue(){var c=readJson(sessionStorage,catalogueKey);if(Array.isArray(c.items)&&c.items.length)return c;c=readJson(localStorage,catalogueKey);if(Array.isArray(c.items)&&c.items.length)sessionStorage.setItem(catalogueKey,JSON.stringify(c));return c;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-official-template-parameterization"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function ready(a){return a.supplyOfficialTemplateValidated===true&&a.supplyOfficialTemplateId===FERRETERIA_CASE.templateId;}
function lotLabel(c){return Array.isArray(c.lots)&&c.lots.length>1?String(c.lots.length)+" lotes":"Lote único";}
function row(dest,label,value,status,note){return '<tr><td><strong>'+esc(dest)+'</strong></td><td>'+esc(label)+'</td><td>'+esc(value)+'</td><td>'+(status==='OK'?'<span>✓ Preparado</span>':status==='HISTORICAL'?'<span>ℹ Antecedente</span>':'<span>⚠ Pendiente</span>')+(note?'<div class="muted">'+esc(note)+'</div>':'')+'</td></tr>';}
function isFerreteriaCase(a){return a.supplyOfficialTemplateId===FERRETERIA_CASE.templateId&&(a.supplyOfficialTemplateValidated===true||String(a.needAndPurpose||"").toLowerCase().includes("ferreter"));}
function migrateStableAdministrativeData(a){if(!isFerreteriaCase(a))return false;var changed=false;
if(!String(a.administrativeFileNumber||"").trim()){a.administrativeFileNumber=FERRETERIA_CASE.fileNumber;changed=true;}
if(!String(a.contractTitle||"").trim()){a.contractTitle=FERRETERIA_CASE.title;changed=true;}
if(!String(a.supplyMainDeliveryLocality||"").trim()){a.supplyMainDeliveryLocality=FERRETERIA_CASE.locality;changed=true;}
if(!String(a.supplyMainExecutionNuts||"").trim()){a.supplyMainExecutionNuts=FERRETERIA_CASE.nuts;changed=true;}
if(a.supplyAdministrativeDataSource!=="SOURCE_PCAP_CONTR_2026_240267"){a.supplyAdministrativeDataSource="SOURCE_PCAP_CONTR_2026_240267";changed=true;}
if(a.supplyPreviousEconomicConfigurationReusable!==false){a.supplyPreviousEconomicConfigurationReusable=false;changed=true;}
if(a.supplyPreviousEconomicConfigurationStatus!=="HISTORICAL_SUPERSEDED_BY_DA33_REVIEW"){a.supplyPreviousEconomicConfigurationStatus="HISTORICAL_SUPERSEDED_BY_DA33_REVIEW";changed=true;}
if(changed)saveAnswers(a,"supply-parameterization-source-data-migration");return changed;}
function build(a,c){var ext=Array.isArray(a.extensionMonths)?a.extensionMonths:[];var modPct=Number(a.supplyNeedsModificationMaximumIncreasePercent||0);var budget=Number(a.supplyMaximumApprovedBudgetExVat||0);var ve=Number(a.supplyEstimatedValueExVat||0);var delivery=Number(a.supplyDeliveryDeadlineDays||0);var objectText=(a.needAndPurpose||"")+(a.scopeDetail?' '+a.scopeDetail:'');var duration=Number(a.initialDurationMonths||0)+' meses'+(ext.length?' + '+ext.map(function(x,i){return 'prórroga '+(i+1)+' de '+Number(x)+' meses';}).join('; '):'');var criteria=a.supplyAwardCriteriaMode==='PRICE_ONLY'&&a.supplyPriceOnlyMotivationValidated===true?'Precio como único criterio, 100 puntos, con motivación específica validada':'Pendiente de cierre';var mod=a.supplyNeedsModificationForeseen===true?modPct.toLocaleString("es-ES",{maximumFractionDigits:2})+' % máximo por mayores necesidades, DA 33.ª / art. 204 LCSP; mismo objeto y precios unitarios':'No prevista';var annualities=Array.isArray(a.supplyBudgetAnnualities)&&a.supplyBudgetAnnualities.length>0;var budgetCode=String(a.supplyBudgetApplication||"").trim();var adminFile=String(a.administrativeFileNumber||a.contractFileNumber||"").trim();var title=String(a.contractTitle||"").trim();var locality=String(a.supplyMainDeliveryLocality||"").trim();var nuts=String(a.supplyMainExecutionNuts||"").trim();var currentPbl=Number(a.supplyCurrentTenderBudgetExVat||0);var pblValidated=a.supplyCurrentTenderBudgetValidated===true&&currentPbl>0;var rows='';
rows+=row('Cabecera del Anexo I','Expediente',adminFile||'Pendiente de número administrativo',adminFile?'OK':'PENDING',adminFile?'Recuperado de la cabecera del PCAP real del expediente.':'El identificador técnico local de Contrata-IA no sustituye al número administrativo del expediente.');
rows+=row('Cabecera del Anexo I','Título del contrato',title||objectText||'Pendiente',(title||objectText)?'OK':'PENDING',title?'Denominación administrativa recuperada del PCAP real; deberá mantenerse si no existe una versión posterior aprobada.':'Debe conservarse la denominación administrativa finalmente aprobada.');
rows+=row('Cabecera del Anexo I','Localidad / NUTS',locality&&nuts?locality+' · '+nuts:(locality||nuts||'Pendiente'),locality&&nuts?'OK':'PENDING',locality&&nuts?'Recuperado de la cabecera del PCAP real del expediente.':'El modelo oficial incluye localidad de entrega y código NUTS del lugar principal de ejecución.');
rows+=row('Anexo I · apartado 1','Objeto y CPV',objectText+' · CPV '+FERRETERIA_CASE.cpv+' ('+FERRETERIA_CASE.cpvLabel+')','OK','El modelo remite el objeto, lotes y carácter de contrato por necesidades a este apartado.');
rows+=row('Anexo I · apartado 1','Lotes y DA 33.ª',lotLabel(c)+' · suministro en función de las necesidades; presupuesto máximo para toda la vigencia: '+money(budget)+' sin IVA','OK','La prórroga no incrementa automáticamente el presupuesto máximo.');
rows+=row('Anexo I · apartado 2','Presupuesto máximo DA 33.ª para toda la vigencia',budget>0?money(budget)+' sin IVA':'Pendiente',budget>0?'OK':'PENDING','Magnitud contractual ya validada como límite económico para toda la vigencia, incluidas las prórrogas. No se confunde con la proyección de consumo ni con el valor estimado.');
rows+=row('Anexo I · apartado 2','PBL / presupuesto base de licitación vigente',pblValidated?money(currentPbl)+' sin IVA':'Pendiente de cierre específico conforme al modelo oficial y a la configuración DA 33.ª',pblValidated?'OK':'PENDING','No se reutiliza automáticamente el PBL de versiones anteriores ni se copia por identidad el presupuesto máximo. Debe quedar expresamente determinado y validado para la versión vigente del Anexo I.');
rows+=row('Anexo I · apartado 2','Configuración económica anterior del expediente','Existe una versión económica anterior del PCAP y de la documentación preparatoria','HISTORICAL','Se conserva únicamente como antecedente documental. Sus importes, anualidades y valor estimado no se trasladan automáticamente tras la revisión jurídico-económica DA 33.ª.');
rows+=row('Anexo I · apartado 2','Valor estimado',ve>0?money(ve)+' sin IVA':'Pendiente',ve>0?'OK':'PENDING','Valor validado separadamente de la proyección de consumo y del presupuesto máximo.');
rows+=row('Anexo I · apartado 2','Sistema de determinación del precio','Precios unitarios por referencia del catálogo validado','OK','Las 98 referencias y sus precios unitarios se conservan sin introducir precios nuevos.');
rows+=row('Anexo I · apartado 2','Anualidades / partida presupuestaria vigente',annualities&&budgetCode?'Anualidades vigentes definidas · '+budgetCode:'Pendiente de nueva validación presupuestaria',annualities&&budgetCode?'OK':'PENDING','Las anualidades y aplicaciones presupuestarias anteriores no se reutilizan automáticamente; deben corresponder a la configuración económica vigente.');
rows+=row('Anexo I · apartado 3','Duración y prórrogas',duration,'OK','En contratos DA 33.ª no procede prórroga si se agota antes el presupuesto máximo salvo regularización legal previa.');
rows+=row('Anexo I · apartado 7','Criterios de adjudicación',criteria,criteria.startsWith('Precio')?'OK':'PENDING','El modelo fija en este apartado orden, ponderación, anormalidad y desempate.');
rows+=row('Anexo I · apartado 7','Parámetros de oferta anormalmente baja / desempate','Pendiente de parametrización específica','PENDING','El modelo oficial exige su definición; no se inventarán parámetros ni criterios de desempate.');
rows+=row('Anexo I · apartado 8','Condición especial de ejecución','Gestión y retirada de embalajes/residuos vinculados a las entregas','OK','Redacción validada conforme al art. 202.1 LCSP.');
rows+=row('Anexo I · apartado 10','Penalidades específicas','Pendiente de comprobar si se añaden penalidades particulares','PENDING','Las penalidades específicas, si existen, deben quedar expresamente parametrizadas; no se crearán automáticamente.');
rows+=row('Anexo I · apartado 14','Modificación prevista',mod,a.supplyNeedsModificationValidated===true?'OK':'PENDING','No se incorporarán artículos ni precios unitarios nuevos.');
rows+=row('PPT / cláusula de entrega','Plazo de entrega',delivery>0?delivery+' días hábiles':'Pendiente',delivery>0?'OK':'PENDING','El plazo de 5 días permanece condición de ejecución, no criterio adicional de adjudicación.');
var pending=[];if(!adminFile)pending.push('número administrativo del expediente');if(!locality||!nuts)pending.push('localidad de entrega y código NUTS');if(!pblValidated)pending.push('PBL vigente del Anexo I, determinado expresamente para la configuración DA 33.ª actual');if(!annualities||!budgetCode)pending.push('anualidades y partida presupuestaria vigentes');pending.push('parámetros de ofertas anormalmente bajas y, en su caso, desempate');pending.push('decisión sobre penalidades específicas del Anexo I-apartado 10');
var html='<div id="supplyOfficialTemplateParameterizationCard" class="card" style="margin-top:14px"><h3>7. Parametrización del Anexo I del DPCAF / PCAP oficial</h3><div class="info"><strong>Modelo base bloqueado:</strong> '+esc(a.supplyOfficialTemplateId||'')+'. Contrata-IA no reescribe las cláusulas generales; únicamente prepara los valores y textos variables que corresponden a los destinos previstos en el modelo recomendado.</div><div class="info"><strong>Fuente administrativa recuperada:</strong> cabecera del PCAP real '+esc(FERRETERIA_CASE.fileNumber)+' para expediente, título, localidad y NUTS. <strong>Regla de seguridad:</strong> la configuración económica anterior se conserva como antecedente, pero no se reutiliza automáticamente después de la revisión DA 33.ª.</div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Destino oficial</th><th>Dato</th><th>Valor preparado</th><th>Estado</th></tr></thead><tbody>'+rows+'</tbody></table></div>';
if(pending.length){html+='<div class="warning"><strong>Datos indispensables todavía pendientes antes de generar el borrador editable:</strong><ul>'+pending.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul><p>Estos datos no se deducirán ni se copiarán de cifras históricas distintas. La parametrización completa se cerrará únicamente cuando estén expresamente validados.</p></div>';}else{html+='<div class="info"><strong>No quedan datos estructurales pendientes en este mapa.</strong> La generación seguirá condicionada a las restantes comprobaciones documentales y normativas.</div>';}
if(a.supplyOfficialTemplateParameterizationValidated===true){html+='<div class="info"><strong>Mapa estructural del Anexo I validado.</strong> Queda registrada la ubicación documental de los datos conocidos y la relación de pendientes. El siguiente paso será completar exclusivamente los campos pendientes antes de producir el primer borrador editable.</div>';}else{html+='<button id="validateSupplyOfficialTemplateParameterization" type="button">Validar mapa estructural del Anexo I</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyOfficialTemplateParameterizationCard");if(old)old.remove();var a=readAnswers();if(migrateStableAdministrativeData(a))a=readAnswers();var anchor=document.getElementById("supplyOfficialTemplateCard");if(!anchor||!ready(a))return;anchor.insertAdjacentHTML('afterend',build(a,readCatalogue()));}
work.addEventListener('click',function(event){var t=event.target;if(!t||t.id!=="validateSupplyOfficialTemplateParameterization")return;var a=readAnswers();if(!ready(a)){alert('Debe validarse primero el modelo oficial.');return;}a.supplyOfficialTemplateParameterizationValidated=true;a.supplyOfficialTemplateParameterizationStatus='STRUCTURAL_MAPPING_VALIDATED_PENDING_REQUIRED_FIELDS';a.supplyOfficialTemplateParameterizationModel=FERRETERIA_CASE.templateId;a.supplyOfficialTemplateParameterizationDestinations=['HEADER','ANNEX_I_1','ANNEX_I_2_DA33_BUDGET','ANNEX_I_2_PBL','ANNEX_I_2_ESTIMATED_VALUE','ANNEX_I_3','ANNEX_I_7','ANNEX_I_8','ANNEX_I_10','ANNEX_I_14','PPT_DELIVERY'];saveAnswers(a,'supply-official-template-parameterization-validated');ensure();},true);
document.addEventListener('contrata-ia:adaptive-saved',function(){setTimeout(ensure,0);});
setTimeout(ensure,0);setTimeout(ensure,180);
})();`;
