export const SUPPLY_OFFICIAL_PCAP_ODT_GENERATOR_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var OFFICIAL_MODEL_URL="https://www.juntadeandalucia.es/sites/default/files/inline-files/2026/02/2025_12_17_pcap_suministro_abierto_simplificado_abreviado_autofinanciada.odt";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
var TABLE_NS="urn:oasis:names:tc:opendocument:xmlns:table:1.0";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-official-pcap-odt"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function ready(a){return a.supplyOfficialFullPcapInsertionMapValidated===true&&a.supplyOfficialFullPcapInsertionPolicy==="COPY_OFFICIAL_ODT_AND_REPLACE_ONLY_ANNEX_I_VARIABLE_DESTINATIONS";}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){if(typeof DecompressionStream!=="function")throw new Error("Este navegador no permite descomprimir el ODT automáticamente.");var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un paquete ODT/ZIP válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen));if(u32(bytes,localOffset)!==0x04034b50)throw new Error("Entrada ODT inválida: "+name);var ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data;if(method===0)data=raw;else if(method===8)data=await inflateRaw(raw);else throw new Error("Método ZIP no soportado en "+name+": "+method);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function norm(v){return String(v||"").replace(/\s+/g," ").trim().toUpperCase();}
function patchContent(xml,a){var parser=new DOMParser(),doc=parser.parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml del ODT.");var nodes=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h"))),changes=[],pending=[];
function find(prefixes){for(var i=0;i<nodes.length;i++){var t=norm(nodes[i].textContent);for(var j=0;j<prefixes.length;j++)if(t.indexOf(norm(prefixes[j]))===0)return nodes[i];}return null;}
function findContains(parts){for(var i=0;i<nodes.length;i++){var t=norm(nodes[i].textContent);for(var j=0;j<parts.length;j++)if(t.indexOf(norm(parts[j]))>=0)return nodes[i];}return null;}
function set(prefixes,value,key,required){var el=find(prefixes);if(!el){if(required)pending.push(key);return false;}el.textContent=value;changes.push(key);return true;}
function setContains(parts,value,key,required){var el=findContains(parts);if(!el){if(required)pending.push(key);return false;}el.textContent=value;changes.push(key);return true;}
function addAfter(prefixes,value,key){var el=find(prefixes);if(!el||!el.parentNode){pending.push(key);return false;}var p=doc.createElementNS(TEXT_NS,"text:p"),style=el.getAttributeNS(TEXT_NS,"style-name")||el.getAttribute("text:style-name");if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);p.textContent=value;el.parentNode.insertBefore(p,el.nextSibling);changes.push(key);return true;}
function firstFollowingTable(anchor){if(!anchor)return null;var cur=anchor;for(var depth=0;depth<250&&cur;depth++){if(cur.nextSibling){cur=cur.nextSibling;}else{while(cur&&cur!==doc.documentElement&&!cur.nextSibling)cur=cur.parentNode;if(!cur||cur===doc.documentElement)return null;cur=cur.nextSibling;}if(cur&&cur.nodeType===1){if(cur.namespaceURI===TABLE_NS&&cur.localName==="table")return cur;var nested=cur.getElementsByTagNameNS?cur.getElementsByTagNameNS(TABLE_NS,"table"):[];if(nested&&nested.length)return nested[0];}}return null;}
function clearCellAndSet(cell,value){while(cell.firstChild)cell.removeChild(cell.firstChild);var p=doc.createElementNS(TEXT_NS,"text:p");p.textContent=value;cell.appendChild(p);}
function setTabbedParagraph(p,values){while(p.firstChild)p.removeChild(p.firstChild);for(var i=0;i<values.length;i++){if(i)p.appendChild(doc.createElementNS(TEXT_NS,"text:tab"));p.appendChild(doc.createTextNode(String(values[i])));}}
function cloneEmptyParagraph(ref){var p=doc.createElementNS(TEXT_NS,"text:p"),style=ref&&(ref.getAttributeNS(TEXT_NS,"style-name")||ref.getAttribute("text:style-name"));if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);return p;}
function fillAnnualitiesAsParagraphs(vals){var paras=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")),anchorIndex=-1,endIndex=-1,headerIndex=-1;for(var i=0;i<paras.length;i++){var t=norm(paras[i].textContent);if(anchorIndex<0&&t.indexOf("ANUALIDADES (IVA INCLUIDO)")>=0){anchorIndex=i;continue;}if(anchorIndex>=0&&endIndex<0&&t.indexOf("TRAMITACIÓN DEL GASTO")>=0){endIndex=i;break;}}if(anchorIndex<0||endIndex<0)return false;for(var h=anchorIndex+1;h<endIndex;h++){var ht=norm(paras[h].textContent);if(ht.indexOf("AÑO")>=0&&ht.indexOf("IMPORTE")>=0){headerIndex=h;break;}}if(headerIndex<0)return false;var rowParas=[];for(var r=headerIndex+1;r<endIndex;r++){var rt=norm(paras[r].textContent);if(!rt||rt.indexOf("AÑO")>=0||rt.indexOf("IMPORTE")>=0)continue;rowParas.push(paras[r]);if(rowParas.length===3)break;}var insertionRef=paras[endIndex],styleRef=rowParas[0]||paras[headerIndex];while(rowParas.length<3){var np=cloneEmptyParagraph(styleRef);insertionRef.parentNode.insertBefore(np,insertionRef);rowParas.push(np);}for(var k=0;k<3;k++)setTabbedParagraph(rowParas[k],[String(vals[k].year),money(vals[k].amount),String(a.supplyCurrentBudgetApplication||"")]);return true;}
function fillAnnualities(){var anchor=find(["Anualidades (IVA incluido)"]),target=firstFollowingTable(anchor),vals=Array.isArray(a.supplyCurrentBudgetAnnualities)?a.supplyCurrentBudgetAnnualities:[];if(vals.length<3){pending.push("2a-tabla-anualidades");return;}if(!target){var tables=Array.from(doc.getElementsByTagNameNS(TABLE_NS,"table"));for(var i=0;i<tables.length;i++){var txt=norm(tables[i].textContent);if(txt.indexOf("AÑO")>=0&&txt.indexOf("IMPORTE")>=0){target=tables[i];break;}}}var tableFilled=false;if(target){var rows=Array.from(target.getElementsByTagNameNS(TABLE_NS,"table-row")),dataRows=[];for(var r=0;r<rows.length;r++){var cells=Array.from(rows[r].getElementsByTagNameNS(TABLE_NS,"table-cell"));if(cells.length>=3){var txt=norm(rows[r].textContent);if(txt.indexOf("AÑO")>=0&&txt.indexOf("IMPORTE")>=0)continue;dataRows.push({row:rows[r],cells:cells});}}if(dataRows.length>=3){for(var k=0;k<3;k++){clearCellAndSet(dataRows[k].cells[0],String(vals[k].year));clearCellAndSet(dataRows[k].cells[1],money(vals[k].amount));clearCellAndSet(dataRows[k].cells[2],String(a.supplyCurrentBudgetApplication||""));}tableFilled=true;}}if(!tableFilled&&!fillAnnualitiesAsParagraphs(vals)){pending.push("2a-tabla-anualidades");return;}changes.push("2a-tabla-anualidades");}
var pbl=Number(a.supplyCurrentTenderBudgetExVat||0),pblInc=Number(a.supplyCurrentTenderBudgetInclVat||0),vat=pblInc-pbl,ve=Number(a.supplyEstimatedValueExVat||0),max=Number(a.supplyMaximumApprovedBudgetExVat||0),modPct=Number(a.supplyNeedsModificationMaximumIncreasePercent||20),annualities=Array.isArray(a.supplyCurrentBudgetAnnualities)?a.supplyCurrentBudgetAnnualities:[];
set(["Expediente:"],"Expediente: "+String(a.administrativeFileNumber||"CONTR/2026/240267"),"cabecera-expediente",true);
set(["Titulo:","Título:"],"Título: "+String(a.contractTitle||""),"cabecera-titulo",true);
set(["Localidad de entrega:"],"Localidad de entrega: "+String(a.supplyMainDeliveryLocality||"SEVILLA"),"cabecera-localidad");
set(["Código NUTS del lugar principal de ejecución:"],"Código NUTS del lugar principal de ejecución: "+String(a.supplyMainExecutionNuts||"ES618"),"cabecera-nuts");
set(["Código CPV:"],"Código CPV: 44316400-2 (Artículos de ferretería).","cabecera-cpv");
set(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES (DA 33ª LCSP): Sí","1c-da33",true);
addAfter(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"Presupuesto máximo aprobado para toda la vigencia, incluidas las prórrogas: "+money(max)+" sin IVA. Las cantidades son estimativas y las prórrogas no incrementan automáticamente este límite.","1c-maximo");
set(["Importe total (IVA excluido):"],"Importe total (IVA excluido): "+money(pbl),"2a-pbl-sin-iva",true);
set(["Importe del IVA:"],"Importe del IVA: "+money(vat),"2a-iva",true);
set(["Importe total (IVA incluido):"],"Importe total (IVA incluido): "+money(pblInc),"2a-pbl-iva",true);
fillAnnualities();
set(["Tramitación del gasto:"],"Tramitación del gasto: Ordinaria.","2a-tramitacion");
set(["Valor estimado del contrato:"],"Valor estimado del contrato: "+money(ve)+" sin IVA.","2b-valor-estimado",true);
set(["Método de cálculo:"],"Método de cálculo: presupuesto máximo DA 33.ª para toda la vigencia "+money(max)+" sin IVA, más modificación prevista máxima del "+modPct.toLocaleString("es-ES")+" %, resultando un valor estimado de "+money(ve)+" sin IVA.","2b-metodo",true);
set(["Sistema de determinación del precio"],"Sistema de determinación del precio: Precios unitarios por referencia del catálogo validado de 98 artículos.","2c-precio",true);
set(["Plazo total (en meses):"],"Plazo total (en meses): 24","3-plazo-total",true);
set(["Plazos parciales (en meses):"],"Plazos parciales (en meses): pedidos sucesivos según necesidades; plazo máximo de entrega: 5 días hábiles.","3-plazos-parciales");
set(["Posibilidad de prórroga:"],"Posibilidad de prórroga: Sí","3-prorroga-si",true);
set(["Duración de la prórroga:"],"Duración de la prórroga: dos prórrogas de 12 meses cada una.","3-prorroga-duracion",true);
set(["Plazo de preaviso de la prórroga:"],"Plazo de preaviso de la prórroga: 2 meses.","3-prorroga-preaviso");
set(["Único criterio de adjudicación relacionado con los costes:"],"Único criterio de adjudicación relacionado con los costes: Sí","7-unico-precio",true);
set(["1. Proposición económica."],"1. Proposición económica: precio, 100 puntos.","7a-precio");
set(["7.B. PARÁMETROS OBJETIVOS PARA CONSIDERAR UNA OFERTA ANORMALMENTE BAJA"],"7.B. PARÁMETROS OBJETIVOS PARA CONSIDERAR UNA OFERTA ANORMALMENTE BAJA: se aplicarán los parámetros objetivos del artículo 85 RGLCAP, de conformidad con el artículo 149.2 LCSP.","7b-anormalidad",true);
set(["7.C. CRITERIOS DE DESEMPATE"],"7.C. CRITERIOS DE DESEMPATE (Cláusula 10.3): se mantienen los criterios específicos previstos en el modelo y, si persiste el empate, se aplicará supletoriamente el artículo 147.2 LCSP.","7c-desempate",true);
set(["Condición especial de ejecución de tipo ambiental o social"],"Condición especial de ejecución de tipo ambiental o social (obligatoria): gestión y retirada de embalajes y residuos generados directamente por las entregas, evitando embalajes innecesarios cuando sea compatible con la adecuada protección del producto.","8a-condicion",true);
set(["Penalidades por incumplimiento de las condiciones especiales de ejecución del contrato:"],"Penalidades por incumplimiento de las condiciones especiales de ejecución del contrato: No. Se aplicará el régimen legal general cuando proceda.","8b-penalidades");
set(["Penalidades por demora en la ejecución parcial o total del plazo de ejecución"],"Penalidades por demora en la ejecución parcial o total del plazo de ejecución, distintas de las establecidas en el artículo 193.3 LCSP: No.","10-demora",true);
set(["Penalidades por cumplimiento defectuoso:"],"Penalidades por cumplimiento defectuoso: No.","10-defectuoso",true);
set(["Penalidades por incumplimiento parcial"],"Penalidades por incumplimiento parcial en la ejecución de las prestaciones: No.","10-parcial",true);
set(["Penalidades por incumplimiento de las obligaciones en materia medioambiental"],"Penalidades por incumplimiento de las obligaciones en materia medioambiental, social o laboral: No, sin perjuicio del régimen legal aplicable.","10-social",true);
set(["Posibilidad de modificación del contrato:"],"Posibilidad de modificación del contrato: Sí","14-si",true);
set(["2. _______(Indicar causa de modificación).","2. _______ (Indicar causa de modificación)."],"2. Mayores necesidades reales respecto de las estimadas inicialmente en contrato sujeto a la disposición adicional 33.ª LCSP.","14-causa-da33",true);
setContains(["Porcentaje máximo del precio del contrato al que pueda afectar"],"- Porcentaje máximo del precio del contrato al que pueda afectar: "+modPct.toLocaleString("es-ES")+" %.","14-porcentaje",true);
addAfter(["2. Mayores necesidades reales respecto de las estimadas inicialmente"],"Alcance y límites: aumento exclusivamente de unidades de los artículos ya incluidos, manteniendo el mismo objeto y los precios unitarios adjudicados; no podrán introducirse artículos ni precios unitarios nuevos. La modificación deberá tramitarse antes de agotar el presupuesto máximo.","14-alcance-da33");
var required=["cabecera-expediente","cabecera-titulo","1c-da33","2a-pbl-sin-iva","2a-iva","2a-pbl-iva","2a-tabla-anualidades","2b-valor-estimado","2b-metodo","2c-precio","3-plazo-total","3-prorroga-si","3-prorroga-duracion","7-unico-precio","7b-anormalidad","7c-desempate","8a-condicion","10-demora","10-defectuoso","10-parcial","14-si","14-causa-da33","14-porcentaje"],missing=required.filter(function(x){return changes.indexOf(x)<0;});if(missing.length)throw new Error("El ODT no coincide suficientemente con el modelo validado. Destinos estructurales no reconocidos: "+missing.join(", ")+".");return {xml:new XMLSerializer().serializeToString(doc),changes:changes,pending:pending};}
async function parameterize(bytes,a){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";}),mime=entries.find(function(e){return e.name==="mimetype";});if(!content||!mime)throw new Error("El archivo seleccionado no es un ODT válido.");var text=new TextDecoder("utf-8").decode(content.data),patched=patchContent(text,a);content.data=new TextEncoder().encode(patched.xml);var output=writeStoredZip(entries);await readZip(output);return {bytes:output,changes:patched.changes,pending:patched.pending};}
function download(bytes,name){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),lnk=document.createElement("a");lnk.href=url;lnk.download=name;document.body.appendChild(lnk);lnk.click();lnk.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
async function fromOfficial(){var response=await fetch(OFFICIAL_MODEL_URL,{mode:"cors",cache:"no-store"});if(!response.ok)throw new Error("No se ha podido descargar el ODT oficial (HTTP "+response.status+").");return new Uint8Array(await response.arrayBuffer());}
function card(a){var html='<div id="supplyOfficialPcapOdtGeneratorCard" class="card" style="margin-top:14px"><h3>11. Generación del DPCAF / PCAP oficial editable</h3>';if(!ready(a)){html+='<div class="warning"><strong>Paso todavía no habilitado.</strong> Debe validarse primero el mapa de inserción del Paso 10.</div></div>';return html;}html+='<div class="info"><strong>Paso 11.1 · parametrización estructural.</strong> Contrata-IA trabaja sobre el ODT oficial y cumplimenta los destinos reales del Anexo I. Ya no añade únicamente párrafos explicativos: rellena importes, estructura de anualidades, plazos, criterios, condición especial, penalidades y modificación en sus campos oficiales.</div><div class="warning"><strong>Control de seguridad documental.</strong> Si no se reconocen todos los destinos estructurales esenciales, la generación se cancela. Los apartados todavía no cerrados del Anexo I seguirán pendientes para la fase siguiente.</div><button id="generateOfficialPcapOdt" type="button">Generar ODT oficial parametrizado 11.1</button><p class="muted">Si la descarga automática del portal de la Junta fuera bloqueada por el navegador, seleccione manualmente el mismo ODT oficial:</p><input id="officialPcapOdtFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="generateOfficialPcapOdtFromFile" type="button" class="secondary">Generar desde ODT oficial seleccionado</button><p><a href="'+OFFICIAL_MODEL_URL+'" target="_blank" rel="noopener">Abrir/descargar ODT oficial de la Junta de Andalucía</a></p>';if(a.supplyOfficialFullPcapOdtGenerated===true)html+='<div class="info"><strong>Último ODT generado.</strong> Destinos estructurales modificados: '+esc((a.supplyOfficialFullPcapOdtChangedDestinations||[]).join(", "))+'.</div>';html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyOfficialPcapOdtGeneratorCard");if(old)old.remove();var a=readAnswers(),anchor=document.getElementById("supplyOfficialPcapInsertionControlCard");if(!anchor)return;anchor.insertAdjacentHTML("afterend",card(a));}
async function run(bytes){var a=readAnswers();if(!ready(a)){alert("Debe validarse primero el Paso 10.");return;}try{var result=await parameterize(bytes,a),name=String(a.administrativeFileNumber||"CONTR-2026-240267").replaceAll("/","-")+"_PCAP_Oficial_Parametrizado_11-1_Contrata-IA.odt";download(result.bytes,name);a.supplyOfficialFullPcapOdtGenerated=true;a.supplyOfficialFullPcapOdtGeneratedAt=new Date().toISOString();a.supplyOfficialFullPcapOdtChangedDestinations=result.changes;a.supplyOfficialFullPcapOdtPendingDestinations=result.pending;a.supplyOfficialFullPcapOdtSource=OFFICIAL_MODEL_URL;a.supplyOfficialFullPcapOdtStatus="OFFICIAL_ODT_STRUCTURALLY_PARAMETERIZED_PENDING_HUMAN_REVIEW";saveAnswers(a,"supply-official-pcap-odt-11-1-generated");ensure();}catch(error){alert("No se ha generado el ODT: "+(error&&error.message?error.message:String(error)));}}
work.addEventListener("click",async function(event){var t=event.target;if(!t)return;if(t.id==="generateOfficialPcapOdt"){t.disabled=true;try{await run(await fromOfficial());}catch(error){alert("La descarga automática del ODT oficial no ha sido posible. Use el selector de archivo inferior. Detalle: "+(error&&error.message?error.message:String(error)));}finally{t.disabled=false;}}if(t.id==="generateOfficialPcapOdtFromFile"){var input=document.getElementById("officialPcapOdtFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione primero el ODT oficial.");return;}t.disabled=true;try{await run(new Uint8Array(await file.arrayBuffer()));}finally{t.disabled=false;}}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,25);});setTimeout(ensure,100);setTimeout(ensure,500);setTimeout(ensure,1500);setTimeout(ensure,3000);
})();`;
