export const SUPPLY_OFFICIAL_PCAP_ANNEX_I_COMPLETION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var OFFICIAL_MODEL_URL="https://www.juntadeandalucia.es/sites/default/files/inline-files/2026/02/2025_12_17_pcap_suministro_abierto_simplificado_abreviado_autofinanciada.odt";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-annex-i-completion"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un paquete ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen));var ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function patchContent(xml,a){
 var parser=new DOMParser(),doc=parser.parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");
 var all=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));
 all.sort(function(x,y){return x.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1;});
 function getAnnexIRange(){for(var i=0;i<all.length;i++){if(norm(all[i].textContent)!=="ANEXO I")continue;var hasCharacteristics=false,hasTitle=false;for(var j=i+1;j<Math.min(i+18,all.length);j++){var t=norm(all[j].textContent);if(t.indexOf("CARACTERÍSTICAS DEL CONTRATO")>=0)hasCharacteristics=true;if(t.indexOf("TÍTULO DEL CONTRATO")===0)hasTitle=true;}if(hasCharacteristics&&hasTitle){var end=all.length;for(var k=i+1;k<all.length;k++){var et=norm(all[k].textContent);if(et==="ANEXO II"||et.indexOf("ANEXO II DECLARACIÓN RESPONSABLE")===0){end=k;break;}}return {start:i,end:end};}}throw new Error("No se ha localizado el Anexo I real del modelo oficial.");}
 var bounds=getAnnexIRange(),nodes=all.slice(bounds.start,bounds.end),changes=[];
 function find(prefixes){for(var i=0;i<nodes.length;i++){var t=norm(nodes[i].textContent);for(var j=0;j<prefixes.length;j++)if(t.indexOf(norm(prefixes[j]))===0)return nodes[i];}return null;}
 function findContains(parts,startAt){for(var i=startAt||0;i<nodes.length;i++){var t=norm(nodes[i].textContent);for(var j=0;j<parts.length;j++)if(t.indexOf(norm(parts[j]))>=0)return {el:nodes[i],index:i};}return null;}
 function set(prefixes,value,key){var el=find(prefixes);if(!el)return false;el.textContent=value;changes.push(key);return true;}
 function setContains(parts,value,key,startAt){var hit=findContains(parts,startAt);if(!hit)return false;hit.el.textContent=value;changes.push(key);return hit.index;}
 function addAfter(prefixes,value,key){var el=find(prefixes);if(!el||!el.parentNode)return false;var p=doc.createElementNS(TEXT_NS,"text:p"),style=el.getAttributeNS(TEXT_NS,"style-name")||el.getAttribute("text:style-name");if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);p.textContent=value;el.parentNode.insertBefore(p,el.nextSibling);changes.push(key);return true;}
 var pbl=Number(a.supplyCurrentTenderBudgetExVat||10552.44),pblInc=Number(a.supplyCurrentTenderBudgetInclVat||12768.45),vat=pblInc-pbl,ve=Number(a.supplyEstimatedValueExVat||21793.15),max=Number(a.supplyMaximumApprovedBudgetExVat||18160.96),modPct=Number(a.supplyNeedsModificationMaximumIncreasePercent||20);
 var title=String(a.contractTitle||"SUMINISTRO DE MATERIALES DE FERRETERÍA PARA LAS INSTALACIONES LOS EDIFICIOS DONDE SE UBICAN LOS SERVICIOS CENTRALES DEL SERVICIO ANDALUZ DE EMPLEO Y SUS OFICINAS ANEXAS");
 set(["TÍTULO DEL CONTRATO:"],"TÍTULO DEL CONTRATO: "+title,"A0-titulo");
 set(["EXPEDIENTE:"],"EXPEDIENTE: "+String(a.administrativeFileNumber||"CONTR/2026/240267"),"A0-expediente");
 set(["LOCALIDAD:"],"LOCALIDAD: "+String(a.supplyMainDeliveryLocality||"SEVILLA"),"A0-localidad");
 set(["Objeto del contrato:"],"Objeto del contrato: Suministro de materiales y artículos de ferretería para pequeñas reparaciones y reposiciones en los edificios del Servicio Andaluz de Empleo.","A1-objeto");
 set(["Código CPV"],"Código CPV: 44316400-2 (Artículos de ferretería).","A1-cpv");
 set(["Lugar de entrega del suministro:"],"Lugar de entrega del suministro: instalaciones de los Servicios Centrales del Servicio Andaluz de Empleo y sus oficinas anexas en Sevilla, conforme al PPT.","A1-entrega");
 set(["División en lotes:"],"División en lotes: No.","A1-lotes-no");
 set(["Descripción de los lotes:"],"Descripción de los lotes: No procede.","A1-lotes-desc");
 set(["Justificación de la no división del contrato en lotes:"],"Justificación de la no división del contrato en lotes: la gestión unificada evita dificultades de coordinación y control, mantiene homogénea la calidad del suministro y permite aprovechar economías de escala en gestión, logística y transporte, favoreciendo ofertas económicamente más competitivas.","A1-lotes-just");
 set(["Limitación de presentación de lotes."],"Limitación de presentación de lotes: No procede.","A1-lotes-pres");
 set(["Limitación de adjudicación de lotes."],"Limitación de adjudicación de lotes: No procede.","A1-lotes-adj");
 set(["Criterios objetivos o sistemas para determinar la adjudicación de los lotes"],"Criterios objetivos o sistemas para determinar la adjudicación de los lotes: No procede.","A1-lotes-criterios");
 set(["Oferta integradora:"],"Oferta integradora: No.","A1-oferta-integradora");
 set(["Contrato reservado DA 4ª LCSP"],"Contrato reservado DA 4.ª LCSP: No.","A1-reservado");
 set(["En caso afirmativo, indicar el ámbito de la reserva:"],"En caso afirmativo, indicar el ámbito de la reserva: No procede.","A1-reserva-ambito");
 set(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES (DA 33.ª LCSP): Sí.","A1-da33");
 addAfter(["1.C. CONTRATO EN FUNCIÓN DE LAS NECESIDADES"],"Las cantidades de las 98 referencias son estimativas. El presupuesto máximo aprobado para toda la vigencia, incluidas las prórrogas, es de "+money(max)+" sin IVA. Las prórrogas no incrementan por sí solas este límite.","A1-da33-max");
 set(["Importe total (IVA excluido):"],"Importe total (IVA excluido): "+money(pbl),"A2-pbl");
 set(["Importe del IVA:"],"Importe del IVA: "+money(vat),"A2-iva");
 set(["Importe total (IVA incluido):"],"Importe total (IVA incluido): "+money(pblInc),"A2-pbl-iva");
 set(["Importe desglosado:"],"Importe desglosado: conforme a las 98 referencias, cantidades estimadas y precios unitarios del catálogo validado incorporado al PPT/documentación técnica.","A2-desglose");
 set(["Tramitación del gasto:"],"Tramitación del gasto: Ordinaria.","A2-tramitacion");
 set(["Valor estimado del contrato:"],"Valor estimado del contrato: "+money(ve)+" sin IVA.","A2-ve");
 set(["Método de cálculo:"],"Método de cálculo: presupuesto máximo DA 33.ª para toda la vigencia, "+money(max)+" sin IVA, más modificación prevista máxima del "+modPct.toLocaleString("es-ES")+" %, resultando "+money(ve)+" sin IVA.","A2-metodo");
 set(["Sistema de determinación del precio:"],"Sistema de determinación del precio: precios unitarios por referencia del catálogo validado de 98 artículos.","A2-precio");
 set(["Revisión de precios en los contratos de suministro de fabricación"],"Revisión de precios en los contratos de suministro de fabricación de armamento y equipamiento, suministro de energía y demás supuestos del modelo: No.","A2-revision-1");
 set(["Revisión de precios en los contratos en los que el período de recuperación"],"Revisión de precios en los contratos en los que el período de recuperación de la inversión sea inferior a cinco años: No.","A2-revision-2");
 set(["Variación de precios en función del cumplimiento"],"Variación de precios en función del cumplimiento o incumplimiento de objetivos de plazos o rendimiento: No.","A2-variacion");
 set(["Supuestos y reglas para su determinación:"],"Supuestos y reglas para su determinación: No procede.","A2-variacion-reglas");
 set(["Entrega de otros bienes de la misma clase como pago"],"Entrega de otros bienes de la misma clase como pago de parte del precio: No.","A2-pago-bienes");
 set(["Posibilidad de incremento del número de unidades a suministrar de hasta el 10%"],"Posibilidad de incremento del número de unidades a suministrar de hasta el 10 % del precio del contrato: No.","A2-diez");
 set(["Plazo total (en meses):"],"Plazo total (en meses): 24 meses.","A3-plazo");
 set(["Plazos parciales (en meses):"],"Plazos parciales (en meses): No procede. Los pedidos tendrán un plazo máximo de entrega de 5 días hábiles conforme al PPT.","A3-parciales");
 set(["Posibilidad de prórroga:"],"Posibilidad de prórroga: Sí.","A3-prorroga");
 set(["Duración de la prórroga:"],"Duración de la prórroga: una o varias prórrogas por un período máximo acumulado de 24 meses.","A3-prorroga-duracion");
 set(["Plazo de preaviso de la prórroga:"],"Plazo de preaviso de la prórroga: 2 meses.","A3-preaviso");
 set(["Órgano de contratación:"],"Órgano de contratación: Dirección Gerencia del Servicio Andaluz de Empleo.","A4-organo");
 set(["Respuestas vinculantes sobre la aclaración de los pliegos:"],"Respuestas vinculantes sobre la aclaración de los pliegos: No.","A4-vinculantes");
 set(["Procedimiento de adjudicación:"],"Procedimiento de adjudicación: Abierto simplificado abreviado.","A5-procedimiento");
 set(["Tramitación del expediente:"],"Tramitación del expediente: Ordinaria.","A5-tramitacion");
 set(["Constitución de mesa de contratación:"],"Constitución de mesa de contratación: Sí.","A5-mesa");
 set(["Posibilidad de variantes"],"Posibilidad de variantes: No.","A5-variantes");
 set(["En caso de renuncia:"],"En caso de renuncia: 100 euros, previa justificación de los gastos ocasionados.","A5-renuncia");
 set(["En caso de desistimiento:"],"En caso de desistimiento: 100 euros, previa justificación de los gastos ocasionados.","A5-desistimiento");
 set(["Organismos de los que las personas licitadoras pueden obtener"],"Organismos de los que las personas licitadoras pueden obtener información sobre las obligaciones del artículo 129.1 LCSP: No procede.","A5-art129");
 set(["Se exige habilitación empresarial o profesional:"],"Se exige habilitación empresarial o profesional: No.","A6-habilitacion");
 set(["a. En caso de que la ejecución del contrato requiera el empleo de sistemas de información"],"a. Exigencias ENS por empleo de sistemas de información: No procede.","A6-ens");
 set(["b. En caso de contratos reservados, se exige habilitación como:"],"b. Habilitación para contratos reservados: No procede.","A6-reservados");
 set(["Requisitos relativos a la organización, destino de sus beneficios"],"Requisitos relativos a la organización, destino de sus beneficios, sistemas de financiación u otros: No procede.","A6-organizacion");
 set(["Único criterio de adjudicación relacionado con los costes:"],"Único criterio de adjudicación relacionado con los costes: Sí.","A7-unico");
 set(["1. Proposición económica:"],"1. Proposición económica: precio, 100 puntos.","A7-precio");
 set(["7.B. PARÁMETROS OBJETIVOS"],"7.B. PARÁMETROS OBJETIVOS PARA CONSIDERAR UNA OFERTA ANORMALMENTE BAJA: se aplicarán los parámetros del artículo 85 RGLCAP, de conformidad con el artículo 149.2 LCSP.","A7-anormalidad");
 set(["7.C. CRITERIOS DE DESEMPATE"],"7.C. CRITERIOS DE DESEMPATE (Cláusula 10.3): se mantienen los criterios específicos del modelo oficial y, si persiste el empate, se aplicará supletoriamente el artículo 147.2 LCSP.","A7-desempate");
 set(["Determinadas tareas críticas"],"Determinadas tareas críticas que deban ser ejecutadas directamente por la contratista: No.","A9-criticas");
 set(["La persona licitadora debe indicar en la oferta"],"La persona licitadora debe indicar en la oferta la parte del contrato que tenga previsto subcontratar: No.","A9-indicar");
 set(["La persona contratista debe indicar si tiene previsto subcontratar los servidores"],"Subcontratación de servidores o servicios asociados con acceso a datos personales: No procede.","A9-servidores");
 set(["La ejecución del contrato debe ir acompañada de medidas de seguridad especiales"],"La ejecución del contrato debe ir acompañada de medidas de seguridad especiales: No.","A9-seguridad");
 set(["Se prevén pagos directos a subcontratistas:"],"Se prevén pagos directos a subcontratistas: No.","A9-pagos-directos");
 set(["Comprobación por el órgano de contratación del estricto cumplimiento"],"Comprobación específica del estricto cumplimiento de pagos a subcontratistas: No.","A9-control-pagos");
 set(["Reserva de un porcentaje mínimo de la ejecución de contratos"],"Reserva de un porcentaje mínimo de la ejecución de contratos en programas de empleo protegido: No.","A9-reserva");
 set(["Penalidades por demora en la ejecución parcial o total"],"Penalidades por demora distintas de las previstas en el artículo 193.3 LCSP: No.","A10-demora");
 set(["Penalidades por cumplimiento defectuoso:"],"Penalidades por cumplimiento defectuoso: No.","A10-defectuoso");
 set(["Penalidades por incumplimiento parcial"],"Penalidades por incumplimiento parcial: No.","A10-parcial");
 set(["Penalidades por incumplimiento de las obligaciones en materia medioambiental"],"Penalidades específicas por incumplimiento de obligaciones medioambientales, sociales o laborales: No, sin perjuicio del régimen legal y de las consecuencias generales previstas en el PCAP.","A10-social");
 set(["Pago Único /Pagos parciales:","Pago Único / Pagos parciales:"],"Pago Único / Pagos parciales: Pagos parciales.","A11-pagos");
 set(["En caso de pagos parciales, periodicidad:"],"En caso de pagos parciales, periodicidad: según los pedidos efectivamente realizados y conformados.","A11-periodicidad");
 set(["Plazo para aprobar los documentos que acrediten la conformidad"],"Plazo para aprobar los documentos que acrediten la conformidad: máximo de 30 días naturales desde la entrega y recepción material del suministro.","A11-conformidad");
 set(["Condiciones para el abono a cuenta de operaciones preparatorias:"],"Condiciones para el abono a cuenta de operaciones preparatorias: No procede.","A11-preparatorias");
 set(["Plazo de garantía:"],"Plazo de garantía: 3 años para bienes de naturaleza duradera; para productos fungibles o consumibles, garantía de perfecto estado, ausencia de defectos ocultos en la entrega y respeto de la fecha de caducidad del fabricante.","A12-garantia");
 set(["Programa de trabajo:"],"Programa de trabajo: No.","A12-programa");
 set(["Información a la que se le atribuye carácter confidencial:"],"Información a la que se le atribuye carácter confidencial: por la naturaleza del contrato, no se prevé acceso a información específicamente confidencial, sin perjuicio del deber legal de confidencialidad.","A12-confidencial");
 set(["Plazo durante el que la persona contratista deberá mantener"],"Plazo durante el que la persona contratista deberá mantener el deber de confidencialidad: 5 años, salvo que legalmente proceda un plazo superior.","A12-conf-plazo");
 set(["Obligación de tener suscrito seguro"],"Obligación de tener suscrito seguro específico que cubra responsabilidades derivadas de la ejecución: No.","A12-seguro");
 set(["Cesión del contrato:"],"Cesión del contrato: Sí, conforme a la cláusula 15 del PCAP y a la LCSP.","A12-cesion");
 set(["En el supuesto de suspensión del contrato acordada"],"Reglas especiales para abono de daños y perjuicios en suspensión o demora de pago superior al plazo legal: No.","A13-suspension");
 set(["Posibilidad de modificación del contrato:"],"Posibilidad de modificación del contrato: Sí.","A14-si");
 var cause1=findContains(["Según lo dispuesto en el apartado 2 de la disposición adicional cuarta de la Ley 3/2012"]);if(cause1){var p1=setContains(["Porcentaje máximo del precio del contrato al que pueda afectar"],"- Porcentaje máximo del precio del contrato al que pueda afectar esta causa de reducción: 20 %.","A14-causa1-pct",cause1.index);}
 var cause2=findContains(["2. _______(Indicar causa de modificación).","2. _______ (Indicar causa de modificación)."]);if(cause2){cause2.el.textContent="2. Mayores necesidades reales respecto de las estimadas inicialmente, en contrato de suministro en función de las necesidades conforme a la disposición adicional 33.ª LCSP.";changes.push("A14-causa2");var alcance=findContains(["Alcance y límites de la modificación:"],cause2.index+1);if(alcance){alcance.el.textContent="Alcance y límites de la modificación: aumento exclusivamente de unidades de las referencias ya incluidas, manteniendo el mismo objeto y los precios unitarios adjudicados; no podrán incorporarse nuevos artículos ni establecerse nuevos precios unitarios. Importe máximo acumulado: "+modPct.toLocaleString("es-ES")+" % del precio inicial de referencia, conforme al artículo 204 LCSP. La modificación deberá tramitarse antes de agotar el presupuesto máximo.";changes.push("A14-causa2-alcance");}}
 set(["La ejecución del contrato requiere el tratamiento por la persona contratista de datos personales"],"La ejecución del contrato requiere el tratamiento por la persona contratista de datos personales por cuenta de la persona responsable del tratamiento: No.","A15-datos");
 function isConditionalNonBlocking(t){return t.indexOf("EN CASO AFIRMATIVO")>=0||t.indexOf("EN SU CASO")>=0||t.indexOf("LOTE 1.")===0||t.indexOf("LOTE 2.")===0||t.indexOf("FÓRMULA:")===0||t.indexOf("PORCENTAJE RESERVADO")===0||t.indexOf("MECANISMOS DE CONTROL")===0;}
 var unresolved=[];for(var q=0;q<nodes.length;q++){var tx=norm(nodes[q].textContent);if(!tx)continue;if((tx.indexOf("SÍ/NO")>=0||tx.indexOf("_______")>=0||tx.indexOf("___")>=0)&&!isConditionalNonBlocking(tx)){unresolved.push(nodes[q].textContent.replace(/\\s+/g," ").trim().slice(0,180));}}
 unresolved=unresolved.filter(function(x,i,arr){return arr.indexOf(x)===i;});
 return {xml:new XMLSerializer().serializeToString(doc),changes:changes,unresolved:unresolved.slice(0,40)};
}
async function parameterize(bytes,a){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");var xml=new TextDecoder("utf-8").decode(content.data),patched=patchContent(xml,a);content.data=new TextEncoder().encode(patched.xml);var output=writeStoredZip(entries);await readZip(output);return {bytes:output,changes:patched.changes,unresolved:patched.unresolved};}
function download(bytes,name){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
async function fromOfficial(){var r=await fetch(OFFICIAL_MODEL_URL,{mode:"cors",cache:"no-store"});if(!r.ok)throw new Error("No se ha podido descargar el ODT oficial.");return new Uint8Array(await r.arrayBuffer());}
function card(a){var html='<div id="supplyAnnexICompletionCard" class="card" style="margin-top:14px"><h3>11.2 Cierre integral y auditoría del Anexo I</h3>';if(a.supplyOfficialFullPcapInsertionMapValidated!==true){html+='<div class="warning">Paso no habilitado: valide primero el mapa de inserción oficial.</div></div>';return html;}html+='<div class="info"><strong>Corrección estructural.</strong> Este paso trabaja exclusivamente dentro del Anexo I real del ODT oficial. No modifica los Anexos II y siguientes, destinados a licitadores. Recupera los datos administrativos del expediente, aplica las decisiones ya validadas y corrige la modificación DA 33.ª por anclaje de causa, evitando la sustitución global errónea del porcentaje.</div><div class="warning"><strong>Control de completitud.</strong> Si quedan campos del órgano de contratación sin resolver, el archivo se genera como borrador pendiente y se muestra la relación de destinos. No se considerará PCAP cerrado mientras existan bloqueantes.</div><button id="generateAnnexIComplete" type="button">Generar ODT oficial con Anexo I completado</button><p class="muted">Si el portal oficial bloquea la descarga automática, seleccione manualmente el ODT oficial original o el ODT 11.1 generado.</p><input id="annexICompletionFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="generateAnnexICompleteFromFile" type="button" class="secondary">Completar ODT seleccionado</button>';if(Array.isArray(a.supplyAnnexIUnresolvedFields)){if(a.supplyAnnexIUnresolvedFields.length===0)html+='<div class="info"><strong>Auditoría del Anexo I superada.</strong> No quedan campos bloqueantes detectados del órgano de contratación.</div>';else html+='<div class="warning"><strong>Pendientes detectados:</strong><ul>'+a.supplyAnnexIUnresolvedFields.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul></div>';}html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyAnnexICompletionCard");if(old)old.remove();var anchor=document.getElementById("supplyOfficialPcapOdtGeneratorCard")||document.getElementById("supplyOfficialPcapInsertionControlCard");if(anchor)anchor.insertAdjacentHTML("afterend",card(readAnswers()));}
async function run(bytes){var a=readAnswers(),result=await parameterize(bytes,a),complete=result.unresolved.length===0;a.supplyAnnexICompletionGenerated=true;a.supplyAnnexICompletionChangedDestinations=result.changes;a.supplyAnnexIUnresolvedFields=result.unresolved;a.supplyAnnexICompletionStatus=complete?"COMPLETE":"PENDING_HUMAN_COMPLETION";saveAnswers(a);download(result.bytes,"CONTR-2026-240267_PCAP_Oficial_AnexoI_Cierre_11-2_Contrata-IA.odt");alert(complete?"Anexo I completado y auditoría estructural superada.":"ODT generado como borrador. Quedan "+result.unresolved.length+" campos del Anexo I que requieren cierre o validación.");ensure();}
document.addEventListener("click",async function(e){if(!e.target)return;if(e.target.id==="generateAnnexIComplete"){try{await run(await fromOfficial());}catch(err){alert("No fue posible la descarga automática. Use el selector de archivo. Detalle: "+err.message);}}if(e.target.id==="generateAnnexICompleteFromFile"){var input=document.getElementById("annexICompletionFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione un ODT.");return;}try{await run(new Uint8Array(await file.arrayBuffer()));}catch(err){alert("No se ha podido completar el ODT: "+err.message);}}});
document.addEventListener("contrata-ia:adaptive-saved",ensure);ensure();
})();`;
