import { REGRESSION_SOURCE_CASES } from "../../regression/RegressionCoverageMatrix";

const SOURCE_CASES_JSON = JSON.stringify(REGRESSION_SOURCE_CASES);

export const SUPPLY_REGRESSION_SOURCES_REGISTRY_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var VERSION="REGRESSION-SOURCE-CASES-11.7.1-v1";
var CASES=${SOURCE_CASES_JSON};
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-regression-sources-registry"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function docs(c){return c.source&&Array.isArray(c.source.documents)?c.source.documents.join(" + "):"";}
function manifest(){return {version:VERSION,status:"SOURCE_DOCUMENTS_AVAILABLE",legalValidation:"PENDING",caseCount:CASES.length,cases:CASES.map(function(c){return {id:c.id,label:c.label,expediente:c.source?c.source.expediente:"",shortName:c.source?c.source.shortName:"",documents:c.source?c.source.documents:[],status:c.status,sourceBasis:c.sourceBasis,legalValidation:c.source?c.source.legalValidation:"PENDING",purpose:c.purpose,tags:c.tags||[]};}),acceptanceRule:"El registro 11.7.1 acredita disponibilidad y clasificación documental, no validación jurídica. Cada caso deberá superar contraste, auditoría sin bloqueantes y validación humana propia.",nextCase:"REG-SUPPLY-002",registeredAt:new Date().toISOString()};}
function downloadJson(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrata-IA_Regression_Source_Cases_11-7-1.json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function rows(){return CASES.map(function(c){return '<tr><td>'+esc(c.id)+'</td><td>'+esc(c.source?c.source.expediente:"")+'</td><td>'+esc(c.source?c.source.shortName:c.label)+'</td><td>'+esc(docs(c))+'</td><td>Documentación disponible · validación jurídica pendiente</td></tr>';}).join("");}
function card(){var a=readAnswers();if(a.supplyGoldenCaseRegistered!==true)return "";var registered=a.supplyRegressionSourceCasesRegistered===true;var html='<div id="supplyRegressionSourcesRegistryCard" class="card" style="margin-top:14px"><h3>11.7.1 Incorporación de expedientes reales de contraste</h3><div class="info"><strong>'+CASES.length+' expedientes con documentación primaria disponible.</strong> Se incorporan como fuentes de contraste de la matriz. Ninguno adquiere por este acto condición de caso dorado ni de doctrina jurídica validada.</div><div class="warning"><strong>Estado jurídico: pendiente.</strong> PCAP, PPT, Memoria y anexos disponibles permiten iniciar la regresión, pero las decisiones extraídas deben auditarse expediente por expediente y recibir validación humana antes de fijarse como referencia.</div><table style="width:100%;border-collapse:collapse"><thead><tr><th>ID</th><th>Expediente</th><th>Caso</th><th>Documentos</th><th>Estado</th></tr></thead><tbody>'+rows()+'</tbody></table><p><strong>Primer contraste:</strong> REG-SUPPLY-002 · Panda Antivirus AVRA. Su función es verificar que las reglas específicas de DA 33.ª del golden case no se trasladan a un suministro ordinario.</p>';
if(!registered){html+='<button id="registerRegressionSourceCases" type="button">Registrar fuentes reales 11.7.1</button>';}else{html+='<div class="info"><strong>11.7.1 registrado.</strong> Versión '+VERSION+'. El siguiente trabajo es el contraste documental de REG-SUPPLY-002.</div><button id="downloadRegressionSourceCases" type="button" class="secondary">Descargar manifiesto 11.7.1 JSON</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyRegressionSourcesRegistryCard");if(old)old.remove();var anchor=document.getElementById("supplyRegressionCoverageMatrixCard")||document.getElementById("supplyGoldenCaseRegressionCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="registerRegressionSourceCases"){var a=readAnswers(),m=manifest();if(a.supplyGoldenCaseRegistered!==true){alert("Debe existir primero un caso dorado registrado.");return;}a.supplyRegressionSourceCasesRegistered=true;a.supplyRegressionSourceCasesVersion=VERSION;a.supplyRegressionSourceCasesManifest=m;a.supplyRegressionNextRecommendedCase="REG-SUPPLY-002";a.supplyRegressionNextRecommendedStatus="SOURCE_DOCUMENTS_AVAILABLE";save(a);downloadJson(m);ensure();alert("Fuentes reales 11.7.1 registradas. La validación jurídica de cada expediente sigue pendiente.");return;}if(e.target.id==="downloadRegressionSourceCases"){var a2=readAnswers();downloadJson(a2.supplyRegressionSourceCasesManifest||manifest());return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;
