export const SUPPLY_CROSS_DOCUMENT_FINAL_AUDIT_CALIBRATION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-cross-document-final-audit-calibration"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function parseXml(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");return doc;}
function paragraphs(doc){var a=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));a.sort(function(x,y){if(x===y)return 0;return x.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1;});return a;}
function find(ps,needle,from){var q=norm(needle);for(var i=from||0;i<ps.length;i++)if(norm(ps[i].textContent).indexOf(q)>=0)return i;return -1;}
function setText(node,text){while(node.firstChild)node.removeChild(node.firstChild);node.appendChild(node.ownerDocument.createTextNode(text));}
function insertBefore(doc,ref,text,styleSource){var p=doc.createElementNS(TEXT_NS,"text:p"),style=(styleSource||ref).getAttributeNS(TEXT_NS,"style-name")||(styleSource||ref).getAttribute("text:style-name");if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);p.textContent=text;ref.parentNode.insertBefore(p,ref);return p;}
async function readBody(file){var entries=await readZip(new Uint8Array(await file.arrayBuffer())),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");var doc=parseXml(new TextDecoder("utf-8").decode(content.data));return norm(doc.documentElement.textContent||"");}
function has(body,v){return body.indexOf(norm(v))>=0;}function hasAny(body,vals){return vals.some(function(v){return has(body,v);});}
function auditPptModel(body){return {identity:has(body,"CONTR/2026/240267")||has(body,"CONTR-2026-240267"),delivery:hasAny(body,["CINCO (5) DÍAS HÁBILES","CINCO(5) DÍAS HÁBILES","5 DÍAS HÁBILES"]),catalogue:has(body,"NO HABILITARÁN LA INCORPORACIÓN DE NUEVOS ARTÍCULOS")&&has(body,"NUEVOS PRECIOS UNITARIOS"),oldScope:!has(body,"NO EXHAUSTIVO NI LIMITATIVO")};}
function auditMemoryBreakdown(body){return has(body,"8.019,85")&&has(body,"1.899,44")&&has(body,"633,15")&&hasAny(body,["76,00 %","76 %"])&&hasAny(body,["18,00 %","18 %"])&&hasAny(body,["6,00 %","6 %"]);}
async function repairMemory(file){var entries=await readZip(new Uint8Array(await file.arrayBuffer())),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");var doc=parseXml(new TextDecoder("utf-8").decode(content.data)),ps=paragraphs(doc),s=find(ps,"4.2",0);if(s<0)s=find(ps,"PRESUPUESTO BASE DE LICITACIÓN Y VALOR ESTIMADO",0);var end=find(ps,"4.3",s>=0?s:0);if(s<0||end<0||end<=s)throw new Error("No se ha podido delimitar el apartado económico 4.2 de la Memoria.");var ref=ps[end],style=ps[s];for(var i=s+1;i<end;i++)setText(ps[i],"");var lines=[
"Presupuesto Base de Licitación: el PBL de la duración inicial del contrato, 24 meses, se fija en 10.552,44 € sin IVA; IVA 21 %: 2.216,01 €; total IVA incluido: 12.768,45 €.",
"Desglose del PBL conforme al artículo 100.2 LCSP: costes directos 76,00 % = 8.019,85 €; costes indirectos 18,00 % = 1.899,44 €; beneficio industrial 6,00 % = 633,15 €; total 100,00 % = 10.552,44 € sin IVA.",
"Presupuesto máximo aprobado para toda la vigencia conforme a la disposición adicional 33.ª LCSP: 18.160,96 € sin IVA. Las prórrogas no incrementan por sí solas este límite.",
"Valor estimado del contrato: 21.793,15 € sin IVA. Método de cálculo: presupuesto máximo aprobado para toda la vigencia, 18.160,96 €, más modificación prevista máxima del 20 %, equivalente a 3.632,19 €, sin volver a adicionar las prórrogas.",
"La modificación prevista queda limitada a mayores necesidades reales respecto de las inicialmente estimadas, mediante aumento de unidades de las referencias ya incluidas, manteniendo el mismo objeto y los precios unitarios adjudicados; no se incorporarán nuevos artículos ni nuevos precios unitarios."
];lines.forEach(function(line){insertBefore(doc,ref,line,style);});var body=norm(doc.documentElement.textContent||"");if(!auditMemoryBreakdown(body)||!has(body,"21.793,15")||has(body,"25.325,86"))throw new Error("La Memoria reparada no supera la verificación económica.");content.data=new TextEncoder().encode(new XMLSerializer().serializeToString(doc));var out=writeStoredZip(entries);await readZip(out);return out;}
function download(bytes){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="CONTR-2026-240267_Memoria_Corregida_11-4-3A_Contrata-IA.odt";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function eligible(a){return a.supplyCrossDocumentFinalAuditRan===true&&Array.isArray(a.supplyCrossDocumentFinalBlockers)&&a.supplyCrossDocumentFinalBlockers.length>0;}
function card(){var a=readAnswers();if(!eligible(a)&&a.supplyCrossDocumentFinalCalibrationDone!==true)return "";var html='<div id="supplyCrossDocumentFinalAuditCalibrationCard" class="card" style="margin-top:14px"><h3>11.4.3A Calibración final contra modelos reales</h3><div class="info"><strong>Diagnóstico confirmado.</strong> El PPT real no contiene CPV como campo propio, pero sí identifica inequívocamente el expediente. El plazo de entrega aparece como «cinco (5) días hábiles». El único defecto documental real detectado por 11.4.3 es la pérdida del desglose 76/18/6 en la Memoria durante la corrección 11.4.2.</div>';
if(a.supplyCrossDocumentFinalCalibrationDone!==true){html+='<h4>1. Verificar físicamente el PPT corregido</h4><input id="finalCalibrationPptFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><h4>2. Reparar y verificar únicamente la Memoria</h4><input id="finalCalibrationMemoryFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runFinalCalibrationRepair" type="button">Verificar PPT y reparar Memoria</button>';}else{html+='<div class="info"><strong>Calibración completada.</strong> PPT verificado conforme a su modelo real y Memoria económica reparada. Vuelva a ejecutar 11.4.3 utilizando el PCAP corregido anterior, el PPT corregido anterior y la nueva Memoria 11.4.3A.</div>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyCrossDocumentFinalAuditCalibrationCard");if(old)old.remove();var anchor=document.getElementById("supplyCrossDocumentFinalAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target||e.target.id!=="runFinalCalibrationRepair")return;var pi=document.getElementById("finalCalibrationPptFile"),mi=document.getElementById("finalCalibrationMemoryFile"),pf=pi&&pi.files&&pi.files[0],mf=mi&&mi.files&&mi.files[0];if(!pf||!mf){alert("Seleccione el PPT corregido y la Memoria corregida generados en 11.4.2.");return;}try{var pptBody=await readBody(pf),ppt=auditPptModel(pptBody);if(!ppt.identity)throw new Error("El PPT no se identifica con el expediente CONTR/2026/240267.");if(!ppt.delivery)throw new Error("No se localiza el plazo de entrega de cinco (5) días hábiles en el PPT.");if(!ppt.catalogue||!ppt.oldScope)throw new Error("El PPT no contiene todavía el cierre del catálogo validado.");var memOut=await repairMemory(mf),a=readAnswers();a.supplyCrossDocumentFinalCalibrationDone=true;a.supplyCrossDocumentFinalCalibrationAt=new Date().toISOString();a.supplyCrossDocumentFinalCalibrationPptVerified=true;a.supplyCrossDocumentFinalCalibrationMemoryRepaired=true;delete a.supplyCrossDocumentFinalAuditRan;delete a.supplyCrossDocumentFinalChecks;delete a.supplyCrossDocumentFinalBlockers;delete a.supplyCrossDocumentFinalAuditValidated;save(a);download(memOut);ensure();alert("PPT verificado y Memoria reparada. Repita ahora la auditoría 11.4.3 con la nueva Memoria descargada.");}catch(err){alert("No se ha completado la calibración: "+err.message);}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;