export const SUPPLY_STATE_CONSISTENCY_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var MIGRATION="2026-08-14-art1453f-da33";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-state-consistency"}}));}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function priceConflict(a){return a.supplyAwardCriteriaMode==="PRICE_ONLY"&&a.supplyNeedsModificationForeseen===true&&a.supplyNeedsModificationValidated===true;}
function criteriaDefinitionPending(a){return a.supplyAwardCriteriaMode==="MULTIPLE_FORMULA"&&a.supplyAwardCriteriaLegalReviewStatus==="RECONFIGURATION_REQUIRED"&&a.supplyAwardCriteriaStructureValidated!==true;}
function blocked(a){return priceConflict(a)||criteriaDefinitionPending(a);}
function migrate(a){if(!priceConflict(a)||a.supplyAwardCriteriaConflictMigrationVersion===MIGRATION)return false;a.supplyAwardCriteriaConflictMigrationVersion=MIGRATION;a.supplyAwardCriteriaLegalReviewValidated=false;a.supplyAwardCriteriaLegalReviewStatus="LEGAL_CONFLICT_ART_145_3_F_DA33";a.supplyPriceOnlyMotivationPreviouslyValidated=a.supplyPriceOnlyMotivationValidated===true;a.supplyPriceOnlyMotivationValidated=false;a.supplyPriceOnlyMotivationStatus="LEGAL_REVIEW_REQUIRED_ART_145_3_F_DA33";a.supplyDocumentGenerationBlockedByAwardCriteria=true;if(a.supplyDocumentMappingValidated===true){a.supplyDocumentMappingPreviouslyValidated=true;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="LEGAL_REVIEW_REQUIRED";}saveAnswers(a,"supply-art1453f-da33-migration");return true;}
function patchAccumulated(a){if(a.supplyEstimatedValueValidated!==true||!(Number(a.supplyEstimatedValueExVat)>0))return;var cards=Array.from(work.querySelectorAll(".card"));var card=cards.find(function(x){return (x.textContent||"").includes("Interpretación acumulada");});if(!card)return;var strongs=Array.from(card.querySelectorAll("strong"));var label=strongs.find(function(x){return (x.textContent||"").trim()==="Valor estimado provisional";});if(!label)return;label.textContent="Valor estimado validado";var labelCell=label.parentElement;var valueCell=labelCell&&labelCell.nextElementSibling;if(valueCell)valueCell.innerHTML=money(a.supplyEstimatedValueExVat)+'<br><span class="muted">Valor estimado cerrado separadamente de la proyección de consumo, incorporando la configuración validada de opciones y modificaciones.</span>';}
function patchEconomic(a){if(a.supplyEstimatedValueValidated!==true||!(Number(a.supplyEstimatedValueExVat)>0))return;var card=document.getElementById("supplyEconomicPeriodCard");if(!card)return;Array.from(card.querySelectorAll(".warning,.info")).forEach(function(x){if((x.textContent||"").includes("Valor estimado contractual:")){x.className="info";x.innerHTML='<strong>Valor estimado contractual validado:</strong> '+money(a.supplyEstimatedValueExVat)+' sin IVA. Se mantiene jurídicamente separado del consumo estimado de referencia, de la proyección de consumo y del presupuesto máximo aprobado.';}});}
function patchFinalization(a){var card=document.getElementById("supplyFinalizationCard");if(!card)return;Array.from(card.querySelectorAll(".info,.warning")).forEach(function(x){var t=x.textContent||"";if(t.includes("El cierre del valor estimado y de la motivación específica del criterio único")){x.innerHTML='<strong>Expediente estructuralmente preparado.</strong> El valor estimado ya está cerrado. La configuración de criterios de adjudicación debe superar el control jurídico específico antes de generar documentación definitiva.';}});var lis=Array.from(card.querySelectorAll("li"));var criteria=lis.find(function(x){return (x.textContent||"").startsWith("Criterios de adjudicación:");});if(criteria&&priceConflict(a))criteria.innerHTML='<strong>Criterios de adjudicación:</strong> ⚠ Revisión jurídica obligatoria: el precio único no puede darse por cerrado mientras exista una modificación prevista, por la condición expresa del artículo 145.3.f LCSP.';if(criteria&&a.supplyAwardCriteriaMode==="MULTIPLE_FORMULA"&&a.supplyAwardCriteriaStructureValidated===true)criteria.innerHTML='<strong>Criterios de adjudicación:</strong> ✓ Pluralidad de criterios objetivos cuantificables mediante fórmula definida por la persona usuaria; pendiente de verificación normativa final en el PCAP.';}
function patchMapping(a){var map=document.getElementById("supplyDocumentMappingCard");if(!map)return;Array.from(map.querySelectorAll(".info,.warning")).forEach(function(x){var t=x.textContent||"";if(t.includes("Precio como criterio único: motivación específica validada")||t.includes("Precio como criterio único: motivación reforzada disponible")){if(priceConflict(a)){x.className="warning";x.innerHTML='<strong>Precio como criterio único: revisión jurídica requerida.</strong> El artículo 145.3.f LCSP exige, para esta excepción en suministros, que no sea posible introducir modificaciones de ninguna clase. El expediente mantiene una modificación prevista por mayores necesidades al amparo de la DA 33.ª y del artículo 204 LCSP. La motivación material del informe se conserva, pero no basta para cerrar jurídicamente el criterio único.';}}if(t.includes("Mapeo documental validado")&&blocked(a)){x.className="warning";x.innerHTML='<strong>Mapeo reabierto por control jurídico.</strong> La validación anterior queda conservada como antecedente, pero no habilita la generación documental hasta resolver la configuración de criterios de adjudicación.';}});var btn=document.getElementById("validateSupplyDocumentMapping");if(btn){btn.disabled=blocked(a);btn.style.opacity=blocked(a)?"0.55":"1";btn.title=blocked(a)?"Debe resolverse primero el control jurídico de los criterios de adjudicación.":"";}}
function reviewCard(a){if(!blocked(a))return "";if(priceConflict(a))return '<div id="supplyAwardCriteriaConflictCard" class="card warning" style="margin-top:12px"><h4>5.2 Control jurídico de los criterios de adjudicación</h4><p><strong>Incompatibilidad a resolver antes de generar documentos.</strong> El artículo 145.3.f LCSP permite excepcionalmente que el precio sea el único factor determinante en suministros perfectamente definidos cuando, además, no pueda variarse el plazo de entrega ni introducirse modificaciones de ninguna clase.</p><p>Este expediente mantiene una modificación prevista por mayores necesidades conforme a la disposición adicional 33.ª y al artículo 204 LCSP. Por ello Contrata-IA no considera cerrada la excepción de precio único, aunque conserva la motivación aportada en el informe del expediente.</p><p><strong>No se inventará un criterio alternativo.</strong> Si se mantiene la modificación prevista, debe pasarse a pluralidad de criterios y concretar al menos un criterio adicional objetivo, vinculado al objeto y evaluable mediante fórmula.</p><button id="switchSupplyCriteriaToMultiple" type="button">Reconfigurar a pluralidad de criterios automáticos</button></div>';return '<div id="supplyAwardCriteriaConflictCard" class="card warning" style="margin-top:12px"><h4>5.2 Definición de la pluralidad de criterios</h4><p>Indique el criterio objetivo adicional que realmente sea adecuado para este suministro. Contrata-IA no propone automáticamente la reducción del plazo de entrega porque el informe del expediente razona que esa mejora puede generar compromisos poco realistas.</p><label><strong>Criterio objetivo adicional</strong></label><input id="supplyAdditionalCriterionName" placeholder="Descripción del criterio"><label><strong>Peso del precio (puntos)</strong></label><input id="supplyPriceWeight" type="number" min="1" max="99" step="1"><label><strong>Peso del criterio adicional (puntos)</strong></label><input id="supplyAdditionalWeight" type="number" min="1" max="99" step="1"><label><strong>Regla o fórmula de valoración objetiva</strong></label><textarea id="supplyAdditionalCriterionFormula" placeholder="Describa cómo se medirá y puntuará sin juicio de valor"></textarea><button id="saveSupplyMultipleCriteriaDefinition" type="button">Guardar definición y continuar</button><p class="muted">Los pesos deben sumar 100 puntos. La configuración seguirá sujeta a verificación normativa final antes de generar el PCAP.</p></div>';}
function ensureReview(a){var old=document.getElementById("supplyAwardCriteriaConflictCard");if(old)old.remove();if(!blocked(a))return;var anchor=document.getElementById("supplyLegalClosureCard")||document.getElementById("supplyDocumentMappingCard");if(anchor)anchor.insertAdjacentHTML("afterend",reviewCard(a));}
function patch(){var a=readAnswers();if(migrate(a))return;patchAccumulated(a);patchEconomic(a);patchFinalization(a);patchMapping(a);ensureReview(a);}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==="switchSupplyCriteriaToMultiple"){a.supplyAwardCriteriaMode="MULTIPLE_FORMULA";a.supplyAwardCriteriaLegalReviewStatus="RECONFIGURATION_REQUIRED";a.supplyAwardCriteriaLegalReviewValidated=false;a.supplyAwardCriteriaStructureValidated=false;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="LEGAL_REVIEW_REQUIRED";a.supplyDocumentGenerationBlockedByAwardCriteria=true;saveAnswers(a,"supply-criteria-reconfigure-multiple");setTimeout(patch,0);}
if(t.id==="saveSupplyMultipleCriteriaDefinition"){var n=document.getElementById("supplyAdditionalCriterionName"),p=document.getElementById("supplyPriceWeight"),w=document.getElementById("supplyAdditionalWeight"),f=document.getElementById("supplyAdditionalCriterionFormula");var pw=p?Number(p.value):NaN,aw=w?Number(w.value):NaN;if(!n||!n.value.trim()||!f||!f.value.trim()){alert("Debe identificar el criterio adicional y su regla objetiva de valoración.");return;}if(!Number.isFinite(pw)||!Number.isFinite(aw)||pw<=0||aw<=0||pw+aw!==100){alert("Los pesos deben ser positivos y sumar 100 puntos.");return;}a.supplyAwardCriteriaStructure=[{id:"PRICE",label:"Precio",weight:pw,formulaRequired:true},{id:"USER_OBJECTIVE_CRITERION",label:n.value.trim(),weight:aw,formulaRequired:true,formulaDescription:f.value.trim()}];a.supplyAwardCriteriaStructureValidated=true;a.supplyAwardCriteriaLegalReviewValidated=true;a.supplyAwardCriteriaLegalReviewStatus="MULTIPLE_FORMULA_USER_DEFINED_PENDING_FINAL_LEGAL_CHECK";a.supplyDocumentGenerationBlockedByAwardCriteria=false;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="READY_FOR_REVALIDATION_AFTER_CRITERIA_CHANGE";saveAnswers(a,"supply-multiple-criteria-defined");location.reload();}},true);
work.addEventListener("click",function(event){var t=event.target;if(!t||t.id!=="validateSupplyDocumentMapping")return;var a=readAnswers();if(blocked(a)){event.preventDefault();event.stopImmediatePropagation();alert("Antes de validar el mapeo debe resolverse el control jurídico de los criterios de adjudicación.");}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(patch,0);});
setTimeout(patch,0);
})();`;
