export const SUPPLY_ANNEX_I_COMPREHENSIVE_AUDIT_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;return readJson(localStorage,answersKey);}
function saveAnswers(a){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-annex-i-comprehensive-audit"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function paragraphs(doc){return Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));}
function findIndex(ps,needle,from){for(var i=from||0;i<ps.length;i++)if(norm(ps[i].textContent).indexOf(norm(needle))>=0)return i;return -1;}
function setText(el,text){if(el)el.textContent=text;}
function hasPlaceholder(text){return /_{3,}/.test(String(text||""));}
function insertAfterParagraph(doc,el,text){if(!el||!el.parentNode)return false;var p=doc.createElementNS(TEXT_NS,"text:p"),style=el.getAttributeNS(TEXT_NS,"style-name")||el.getAttribute("text:style-name");if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);p.textContent=text;el.parentNode.insertBefore(p,el.nextSibling);return true;}
function auditAndPatch(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");var ps=paragraphs(doc),start=findIndex(ps,"TÍTULO DEL CONTRATO:",0),end=findIndex(ps,"ANEXO II",start>0?start:0);if(start<0||end<0||end<=start)throw new Error("No se ha podido delimitar el Anexo I real del modelo oficial.");var fixed=[],ignored=[],blockers=[];
function idx(label){return findIndex(ps,label,start);}function txt(i){return i>=0&&i<ps.length?String(ps[i].textContent||""):"";}
function replaceConditional(label,value,key){var i=idx(label);if(i>=0&&hasPlaceholder(txt(i))){setText(ps[i],value);fixed.push(key);return true;}return false;}
var closedPatterns=["LOTE 1.","LOTE 2.","COMBINACIÓN O COMBINACIONES DE LOTES","LOTES RESERVADOS","FÓRMULA:","URGENTE, SEGÚN RESOLUCIÓN","EN CASO AFIRMATIVO, INDICAR","OTROS REQUISITOS NECESARIOS PARA ASEGURAR LA CONFORMIDAD","OTRAS:","DETERMINADAS TAREAS CRÍTICAS","PENALIDAD DEL _______ % DEL IMPORTE DEL SUBCONTRATO","RÉGIMEN DE ABONO DEL PRECIO:","PERIODICIDAD DEL PAGO:","REGISTRO PARA PRESENTACIÓN DE FACTURAS:","PORCENTAJE RESERVADO:","OPERACIONES PREPARATORIAS SUSCEPTIBLES","EXIGENCIA, EN SU CASO, DE UN PROGRAMA DE TRABAJO","CRITERIOS Y FORMA DE VALORACIÓN DE LAS OPERACIONES PREPARATORIAS","PLAN DE AMORTIZACIÓN DE LOS ABONOS A CUENTA","EN SU CASO, TÉRMINOS DEL SEGURO","REGLAS A APLICAR SERÁN LAS SIGUIENTES","EL TRATAMIENTO CONSISTIRÁ EN:","ESPECIFICAR DE ACUERDO CON EL ARTÍCULO 28.3","ESTAS OPERACIONES DE TRATAMIENTO","HAN SIDO ENCOMENDADAS A SU VEZ"];
for(var i=start;i<end;i++){var n=norm(txt(i));if(!hasPlaceholder(txt(i)))continue;for(var c=0;c<closedPatterns.length;c++){if(n.indexOf(closedPatterns[c])>=0){ignored.push(txt(i));break;}}}
var c2=idx("2. _______");if(c2>=0){setText(ps[c2],"2. No procede.");fixed.push("7A-documentacion-criterio-2");}var c3=findIndex(ps,"3. _______",c2>=0?c2+1:start);if(c3>=0&&c3<end){setText(ps[c3],"3. No procede.");fixed.push("7A-documentacion-criterio-3");}
var p8=idx("Penalidades por incumplimiento de las condiciones especiales de ejecución del contrato: Sí.");var p8detail=findIndex(ps,"En caso afirmativo, indicar las penalidades conforme al artículo 192",p8>=0?p8:start);if(p8>=0&&p8detail>=0&&hasPlaceholder(txt(p8detail))){setText(ps[p8detail],"En caso afirmativo, indicar las penalidades conforme al artículo 192 LCSP: abandono de embalajes, 300,00 € por pedido afectado; falta de acreditación de reciclaje de envases peligrosos o componentes químicos en 10 días, 5 % del importe neto del pedido afectado, con audiencia previa y límites legales aplicables.");fixed.push("8B-penalidades-detalle");}
var d=idx("Penalidades por demora distintas de las del artículo 193.3 LCSP: Sí.");var dd=findIndex(ps,"En caso afirmativo, especificar:",d>=0?d:start);if(d>=0&&dd>=0&&hasPlaceholder(txt(dd))){setText(ps[dd],"En caso afirmativo, especificar: 10,00 € sin IVA por cada día hábil de retraso en cada pedido, con límite acumulado por pedido del 50 % de su valor neto.");fixed.push("10-demora-detalle");}
var env=idx("Penalidades por incumplimiento de obligaciones medioambientales, sociales o laborales: Sí.");var envd=findIndex(ps,"En caso afirmativo, especificar:",env>=0?env:start);if(env>=0&&envd>=0&&hasPlaceholder(txt(envd))){setText(ps[envd],"En caso afirmativo, especificar: se aplica el régimen específico del apartado 8.B para la condición de gestión y retirada de residuos y embalajes.");fixed.push("10-medioambiental-detalle");}
// 14: anclaje estricto dentro del apartado 14 y de la causa 2 DA 33.ª.
var sec14=idx("14. MODIFICACIONES DEL CONTRATO");var cause1=sec14>=0?findIndex(ps,"1. Reducción o supresión de prestaciones por medidas de estabilidad presupuestaria",sec14):-1;var da=sec14>=0?findIndex(ps,"2. Mayores necesidades reales respecto de las estimadas inicialmente",sec14):-1;var cause3=da>=0?findIndex(ps,"3. Otras causas de modificación previstas",da+1):-1;var daEnd=cause3>=0?cause3:Math.min(da+12,end);
if(da>=0){var has20=false;for(var j=da;j<daEnd;j++){var nj=norm(txt(j));if(nj.indexOf("20 %")>=0||nj.indexOf("20%")>=0){has20=true;break;}}if(!has20){var target=-1;for(var k=da+1;k<daEnd;k++){if(hasPlaceholder(txt(k))){target=k;break;}}if(target>=0){setText(ps[target],"- Porcentaje máximo del precio inicial del contrato al que puede afectar esta modificación prevista: 20 %.");fixed.push("14-da33-porcentaje");has20=true;}else{var scope=findIndex(ps,"Alcance y límites de la modificación: aumento exclusivamente de unidades",da);if(scope>=da&&scope<daEnd&&insertAfterParagraph(doc,ps[scope],"- Porcentaje máximo del precio inicial del contrato al que puede afectar esta modificación prevista: 20 %.")){fixed.push("14-da33-porcentaje-insertado");has20=true;}}}if(!has20)blockers.push("14. Modificación DA 33.ª: falta incorporar el porcentaje máximo del 20 % dentro de la causa 2.");}else blockers.push("14. Modificación DA 33.ª: no se ha localizado la causa 2 dentro del apartado 14.");
if(cause1>=0&&da>cause1){for(var q=cause1;q<da;q++){if(norm(txt(q)).indexOf("PORCENTAJE MÁXIMO DEL PRECIO DEL CONTRATO")>=0&&hasPlaceholder(txt(q))){setText(ps[q],"- Porcentaje máximo del precio del contrato al que pueda afectar: No procede.");fixed.push("14-causa1-porcentaje-no-procede");}}}
var breakdown=idx("Importe desglosado:");if(breakdown>=0){var blankBreak=false;for(var b=breakdown+1;b<Math.min(breakdown+4,end);b++)if(hasPlaceholder(txt(b)))blankBreak=true;if(blankBreak)blockers.push("2.A. Desglose del PBL: deben cerrarse los campos de costes directos, indirectos y otros eventuales gastos o justificarse expresamente su configuración conforme al modelo; Contrata-IA no debe inventar esos importes.");}
var residual=[];for(var r=start;r<end;r++){var raw=txt(r),nr=norm(raw);if(!hasPlaceholder(raw))continue;var isIgnored=false;for(var z=0;z<closedPatterns.length;z++)if(nr.indexOf(closedPatterns[z])>=0){isIgnored=true;break;}if(nr==="- _______"||nr==="-_________"||nr==="_______")isIgnored=true;if(isIgnored)continue;if(nr.indexOf("IMPORTE DESGLOSADO")<0&&nr.indexOf("EN CASO AFIRMATIVO")<0)residual.push(raw);}
return {xml:new XMLSerializer().serializeToString(doc),fixed:fixed,ignoredCount:ignored.length,blockers:blockers,residual:residual.slice(0,30)};}
async function process(bytes){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");var result=auditAndPatch(new TextDecoder("utf-8").decode(content.data));content.data=new TextEncoder().encode(result.xml);var output=writeStoredZip(entries);await readZip(output);return {bytes:output,result:result};}
function download(bytes){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="CONTR-2026-240267_PCAP_Oficial_AnexoI_Auditoria_Integral_11-2-2_Contrata-IA.odt";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function card(){var a=readAnswers();if(a.supplyAnnexIFinalAuditValidated!==true)return "";var html='<div id="supplyAnnexIComprehensiveAuditCard" class="card" style="margin-top:14px"><h3>11.2.2 Auditoría integral de campos residuales del Anexo I</h3><div class="info"><strong>Control completo del Anexo I.</strong> Se revisan todos los guiones bajos y opciones residuales dentro del documento que corresponde cumplimentar al órgano de contratación. Los campos subordinados a decisiones ya cerradas en No o No procede no se tratan como bloqueantes.</div><div class="warning"><strong>No se auditan como pendientes los Anexos II y siguientes.</strong> Esos modelos contienen campos que debe cumplimentar posteriormente la persona licitadora o adjudicataria.</div><input id="annexIComprehensiveAuditFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runAnnexIComprehensiveAudit" type="button">Auditar integralmente el Anexo I</button>';
if(Array.isArray(a.supplyAnnexIComprehensiveAuditBlockers)){if(a.supplyAnnexIComprehensiveAuditBlockers.length===0)html+='<div class="info"><strong>Auditoría integral superada.</strong> No quedan campos reales del órgano de contratación sin resolver en el Anexo I.</div>';else html+='<div class="warning"><strong>Bloqueantes reales tras auditoría integral:</strong><ul>'+a.supplyAnnexIComprehensiveAuditBlockers.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul></div>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyAnnexIComprehensiveAuditCard");if(old)old.remove();var anchor=document.getElementById("supplyAnnexIFinalAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target||e.target.id!=="runAnnexIComprehensiveAudit")return;var input=document.getElementById("annexIComprehensiveAuditFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione el ODT que ha superado el Paso 11.2.1.");return;}try{var out=await process(new Uint8Array(await file.arrayBuffer())),a=readAnswers(),r=out.result;a.supplyAnnexIComprehensiveAuditBlockers=r.blockers;a.supplyAnnexIComprehensiveAuditFixed=r.fixed;a.supplyAnnexIComprehensiveAuditIgnoredConditionalCount=r.ignoredCount;a.supplyAnnexIComprehensiveAuditResidualSample=r.residual;a.supplyAnnexIComprehensiveAuditValidated=r.blockers.length===0;a.supplyAnnexIComprehensiveAuditStatus=r.blockers.length?"PENDING_TECHNICAL_ECONOMIC_VALIDATION":"COMPLETE";saveAnswers(a);download(out.bytes);alert(r.blockers.length?"Auditoría integral completada. Quedan "+r.blockers.length+" bloqueantes reales: "+r.blockers.join(" | "):"Auditoría integral del Anexo I superada. Bloqueantes reales: 0.");ensure();}catch(err){alert("No se ha podido completar la auditoría integral: "+err.message);}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;