export const SUPPLY_AWARD_CRITERIA_VISIBILITY_HOTFIX_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-award-criteria-hotfix"}}));}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function hasModification(a){return a.supplyNeedsModificationForeseen===true||Number(a.supplyNeedsModificationMaximumIncreasePercent||0)>0||Number(a.supplyNeedsModificationMaximumIncreaseExVat||0)>0;}
function priceConflict(a){return a.supplyAwardCriteriaMode==="PRICE_ONLY"&&hasModification(a);}
function pendingDefinition(a){return a.supplyAwardCriteriaMode==="MULTIPLE_FORMULA"&&a.supplyAwardCriteriaLegalReviewStatus==="RECONFIGURATION_REQUIRED"&&a.supplyAwardCriteriaStructureValidated!==true;}
function blocked(a){return priceConflict(a)||pendingDefinition(a);}
function economicClosed(a){return Number(a.supplyMaximumApprovedBudgetExVat||0)>0&&a.supplyNeedsModificationValidated===true&&a.supplyEstimatedValueValidated===true&&Number(a.supplyEstimatedValueExVat||0)>0;}
function closureSummary(a){var budget=Number(a.supplyMaximumApprovedBudgetExVat||0),pct=Number(a.supplyNeedsModificationMaximumIncreasePercent||0),inc=Number(a.supplyNeedsModificationMaximumIncreaseExVat||budget*pct/100),ve=Number(a.supplyEstimatedValueExVat||0);var mod=a.supplyNeedsModificationForeseen===true?'<div class="info"><strong>Modificación prevista:</strong> '+pct.toLocaleString("es-ES",{maximumFractionDigits:2})+' % del precio inicial, equivalente a '+money(inc)+' sin IVA.</div>':'<div class="info"><strong>Modificación prevista:</strong> no se ha previsto modificación al alza por mayores necesidades.</div>';return '<div id="supplyLegalClosureCard" class="card" style="margin-top:12px"><h4>5.1 Cierre jurídico-económico previo a la validación del mapeo</h4><div class="info"><strong>Presupuesto máximo registrado:</strong> '+money(budget)+' sin IVA para toda la vigencia.</div>'+mod+'<div class="info"><strong>Valor estimado validado:</strong> '+money(ve)+' sin IVA.</div><div class="info"><strong>Cierre jurídico-económico completado.</strong> Presupuesto máximo, modificación prevista y valor estimado están cerrados. Los criterios de adjudicación se controlan separadamente en el apartado 5.2.</div></div>';}
function ensureClosure(a,map){var closure=document.getElementById("supplyLegalClosureCard");if(closure)return closure;if(!economicClosed(a))return null;var h3=map.querySelector("h3");if(h3)h3.insertAdjacentHTML("afterend",closureSummary(a));else map.insertAdjacentHTML("afterbegin",closureSummary(a));return document.getElementById("supplyLegalClosureCard");}
function card(a){if(priceConflict(a))return '<div id="supplyAwardCriteriaVisibilityHotfixCard" class="warning" style="margin:12px 0;padding:12px"><h4>5.2 Control jurídico de los criterios de adjudicación</h4><p><strong>Debe resolverse antes de generar documentos.</strong> El expediente mantiene precio como criterio único y, al mismo tiempo, una modificación prevista por mayores necesidades. La excepción del artículo 145.3.f LCSP exige que no puedan introducirse modificaciones de ninguna clase.</p><p>La motivación previa queda conservada como antecedente, pero no permite cerrar este punto mientras se mantenga la modificación prevista.</p><button id="hotfixSwitchSupplyCriteriaToMultiple" type="button">Reconfigurar a pluralidad de criterios automáticos</button></div>';
if(pendingDefinition(a))return '<div id="supplyAwardCriteriaVisibilityHotfixCard" class="warning" style="margin:12px 0;padding:12px"><h4>5.2 Definición de la pluralidad de criterios</h4><p>Defina el criterio objetivo adicional que sea realmente adecuado para este suministro. No se propone automáticamente una reducción del plazo de entrega.</p><label><strong>Criterio objetivo adicional</strong></label><input id="hotfixAdditionalCriterionName" placeholder="Descripción del criterio"><label><strong>Peso del precio (puntos)</strong></label><input id="hotfixPriceWeight" type="number" min="1" max="99" step="1"><label><strong>Peso del criterio adicional (puntos)</strong></label><input id="hotfixAdditionalWeight" type="number" min="1" max="99" step="1"><label><strong>Regla o fórmula objetiva de valoración</strong></label><textarea id="hotfixAdditionalCriterionFormula" placeholder="Describa cómo se medirá y puntuará mediante fórmula"></textarea><button id="hotfixSaveSupplyMultipleCriteriaDefinition" type="button">Guardar definición y continuar</button><p class="muted">Los pesos deben sumar 100 puntos.</p></div>';
return '';}
function normalize(a){if(!priceConflict(a))return false;var changed=false;if(a.supplyAwardCriteriaLegalReviewStatus!=="LEGAL_CONFLICT_ART_145_3_F_DA33"){a.supplyAwardCriteriaLegalReviewStatus="LEGAL_CONFLICT_ART_145_3_F_DA33";changed=true;}if(a.supplyAwardCriteriaLegalReviewValidated!==false){a.supplyAwardCriteriaLegalReviewValidated=false;changed=true;}if(a.supplyPriceOnlyMotivationValidated===true){a.supplyPriceOnlyMotivationPreviouslyValidated=true;a.supplyPriceOnlyMotivationValidated=false;changed=true;}if(a.supplyDocumentGenerationBlockedByAwardCriteria!==true){a.supplyDocumentGenerationBlockedByAwardCriteria=true;changed=true;}if(a.supplyDocumentMappingValidated===true){a.supplyDocumentMappingPreviouslyValidated=true;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="LEGAL_REVIEW_REQUIRED";changed=true;}if(changed)saveAnswers(a,"supply-award-criteria-hotfix-normalize");return changed;}
function patchMappingText(a,map){if(!priceConflict(a))return;Array.from(map.querySelectorAll("li")).forEach(function(li){var t=(li.textContent||"").trim();if(t.startsWith("Criterios:")||t.startsWith("Criterios de adjudicación:")){li.innerHTML='<strong>'+(t.startsWith("Criterios:")?'Criterios:':'Criterios de adjudicación:')+'</strong> configuración reabierta por control jurídico. No se trasladará el precio como criterio único mientras se mantenga la modificación prevista; debe resolverse el apartado 5.2 antes de generar documentos.';}});Array.from(map.querySelectorAll(".info,.warning")).forEach(function(x){var t=x.textContent||"";if(t.includes("Precio como criterio único:")){x.className="warning";x.innerHTML='<strong>Precio como criterio único: revisión jurídica requerida.</strong> La motivación previa se conserva como antecedente, pero el criterio no está cerrado mientras conviva con una modificación prevista por mayores necesidades. Resuelva el apartado 5.2 antes de generar documentación.';}});}
function render(){var a=readAnswers();normalize(a);a=readAnswers();var map=document.getElementById("supplyDocumentMappingCard");if(!map)return;var closure=ensureClosure(a,map);patchMappingText(a,map);var old=document.getElementById("supplyAwardCriteriaVisibilityHotfixCard");if(old)old.remove();if(blocked(a)){var html=card(a);if(closure)closure.insertAdjacentHTML("afterend",html);else{var h3=map.querySelector("h3");if(h3)h3.insertAdjacentHTML("afterend",html);else map.insertAdjacentHTML("afterbegin",html);}}var btn=document.getElementById("validateSupplyDocumentMapping");if(btn&&blocked(a)){btn.disabled=true;btn.style.opacity="0.55";btn.title="Debe resolverse primero el control jurídico de los criterios de adjudicación.";}}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==="hotfixSwitchSupplyCriteriaToMultiple"){a.supplyAwardCriteriaMode="MULTIPLE_FORMULA";a.supplyAwardCriteriaLegalReviewStatus="RECONFIGURATION_REQUIRED";a.supplyAwardCriteriaLegalReviewValidated=false;a.supplyAwardCriteriaStructureValidated=false;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="LEGAL_REVIEW_REQUIRED";a.supplyDocumentGenerationBlockedByAwardCriteria=true;saveAnswers(a,"supply-criteria-reconfigure-multiple-hotfix");setTimeout(render,0);}
if(t.id==="hotfixSaveSupplyMultipleCriteriaDefinition"){var n=document.getElementById("hotfixAdditionalCriterionName"),p=document.getElementById("hotfixPriceWeight"),w=document.getElementById("hotfixAdditionalWeight"),f=document.getElementById("hotfixAdditionalCriterionFormula");var pw=p?Number(p.value):NaN,aw=w?Number(w.value):NaN;if(!n||!n.value.trim()||!f||!f.value.trim()){alert("Debe identificar el criterio adicional y su regla objetiva de valoración.");return;}if(!Number.isFinite(pw)||!Number.isFinite(aw)||pw<=0||aw<=0||pw+aw!==100){alert("Los pesos deben ser positivos y sumar 100 puntos.");return;}a.supplyAwardCriteriaStructure=[{id:"PRICE",label:"Precio",weight:pw,formulaRequired:true},{id:"USER_OBJECTIVE_CRITERION",label:n.value.trim(),weight:aw,formulaRequired:true,formulaDescription:f.value.trim()}];a.supplyAwardCriteriaStructureValidated=true;a.supplyAwardCriteriaLegalReviewValidated=true;a.supplyAwardCriteriaLegalReviewStatus="MULTIPLE_FORMULA_USER_DEFINED_PENDING_FINAL_LEGAL_CHECK";a.supplyDocumentGenerationBlockedByAwardCriteria=false;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="READY_FOR_REVALIDATION_AFTER_CRITERIA_CHANGE";saveAnswers(a,"supply-multiple-criteria-defined-hotfix");location.reload();}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(render,0);setTimeout(render,80);});
setTimeout(render,0);setTimeout(render,120);setTimeout(render,500);
})();`;
