export const SUPPLY_GOLDEN_CASE_REGISTRY_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var CASE_ID="CONTR-2026-240267-SUPPLY-DA33-GOLDEN-001";
var CASE_STATUS="VALIDATED_DOCUMENTARY_GOLDEN_CASE";
var REGRESSION_VERSION="SUPPLY-DA33-GOLDEN-001-v1";
var BASELINE_COMMIT="a2e937d2102d2b8bdf7db9a7ff4a14a3bf93deb7";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-golden-case-registry"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function eligible(a){var b=Array.isArray(a.supplyCrossDocumentFinalBlockers)?a.supplyCrossDocumentFinalBlockers:[];return a.supplyCrossDocumentFinalAuditRan===true&&b.length===0;}
function manifest(){return {
  id:CASE_ID,status:CASE_STATUS,regressionVersion:REGRESSION_VERSION,expediente:"CONTR/2026/240267",contractType:"SUMINISTRO",procedure:"ABIERTO_SIMPLIFICADO_ABREVIADO",financing:"AUTOFINANCIADO",cpv:"44316400-2",catalogueReferences:98,referenceEconomicBaseExVat:4540.24,initialPblExVat:10552.44,initialPblVatIncluded:12768.45,directCostsPercent:76,directCostsExVat:8019.85,indirectCostsPercent:18,indirectCostsExVat:1899.44,industrialProfitPercent:6,industrialProfitExVat:633.15,maximumBudgetAllTermExVat:18160.96,estimatedValueExVat:21793.15,plannedModificationPercent:20,plannedModificationMaximumExVat:3632.19,initialDurationMonths:24,extensionMonths:[12,12],deliveryBusinessDays:5,soleAwardCriterion:"PRECIO",awardPoints:100,noNewItems:true,noNewUnitPrices:true,legalBasis:["DA 33.ª LCSP","art. 204 LCSP"],legalReport:"AJ-SAE 2026/16",legalReportDate:"2026-07-29",finalAuditBlockers:0,humanValidated:true,baselineCommit:BASELINE_COMMIT,registeredAt:new Date().toISOString()
};}
function downloadJson(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=CASE_ID+".json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function card(){var a=readAnswers();if(!eligible(a)&&a.supplyGoldenCaseRegistered!==true)return "";var html='<div id="supplyGoldenCaseRegistryCard" class="card" style="margin-top:14px"><h3>11.5 Registro formal del caso dorado</h3>';
if(a.supplyGoldenCaseRegistered!==true){html+='<div class="info"><strong>Expediente apto para registro.</strong> La auditoría final 11.4.3 presenta 0 incoherencias reales. El registro congela las magnitudes, decisiones jurídicas y fuentes que constituyen la referencia aprobada del expediente piloto.</div><div class="warning"><strong>Validación humana.</strong> Al registrar el caso dorado se declara que estas decisiones son la línea base de regresión y que cualquier desviación futura deberá ser detectada y justificada.</div><button id="registerSupplyGoldenCase" type="button">Registrar caso dorado 11.5</button>';}else{var m=a.supplyGoldenCaseManifest||{};html+='<div class="info"><strong>Caso dorado registrado.</strong> '+esc(m.id||CASE_ID)+' · estado '+esc(m.status||CASE_STATUS)+' · versión '+esc(m.regressionVersion||REGRESSION_VERSION)+'.</div><button id="downloadSupplyGoldenManifest" type="button" class="secondary">Descargar manifiesto JSON del caso dorado</button>';}
html+='</div>';
if(a.supplyGoldenCaseRegistered===true){html+='<div id="supplyGoldenCaseRegressionCard" class="card" style="margin-top:14px"><h3>11.6 Regresión automática del caso dorado</h3><div class="info"><strong>Protección activa.</strong> El caso '+CASE_ID+' queda cubierto por una prueba de regresión en el repositorio. La prueba valida las magnitudes económicas, DA 33.ª, modificación del 20 %, catálogo cerrado, duración, precio único, plazo de entrega y ausencia de redacciones incompatibles.</div><div class="warning"><strong>Puerta CI.</strong> Los cambios futuros que alteren esta línea base deben hacer fallar la regresión hasta que la modificación haya sido revisada y, si procede, se versiona expresamente el golden case.</div><ul><li>Identificador: '+CASE_ID+'</li><li>Versión de regresión: '+REGRESSION_VERSION+'</li><li>Bloqueantes admitidos: 0</li><li>Validación humana: obligatoria</li></ul></div>';}
return html;}
function ensure(){var old=document.getElementById("supplyGoldenCaseRegistryCard");if(old)old.remove();var old2=document.getElementById("supplyGoldenCaseRegressionCard");if(old2)old2.remove();var anchor=document.getElementById("supplyCrossDocumentFinalAuditCalibrationCard")||document.getElementById("supplyCrossDocumentFinalAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="registerSupplyGoldenCase"){var a=readAnswers(),b=Array.isArray(a.supplyCrossDocumentFinalBlockers)?a.supplyCrossDocumentFinalBlockers:[];if(a.supplyCrossDocumentFinalAuditRan!==true||b.length!==0){alert("No puede registrarse el caso dorado sin una auditoría 11.4.3 con 0 incoherencias reales.");return;}var m=manifest();a.supplyCrossDocumentFinalAuditValidated=true;a.supplyCrossDocumentFinalAuditValidatedAt=new Date().toISOString();a.supplyGoldenCaseRegistered=true;a.supplyGoldenCaseRegisteredAt=m.registeredAt;a.supplyGoldenCaseManifest=m;a.supplyGoldenRegressionCaseId=CASE_ID;a.supplyGoldenRegressionCaseStatus=CASE_STATUS;a.supplyGoldenRegressionVersion=REGRESSION_VERSION;save(a);downloadJson(m);ensure();alert("Caso dorado registrado. La regresión 11.6 queda activa en el repositorio y en CI.");return;}if(e.target.id==="downloadSupplyGoldenManifest"){var a2=readAnswers();downloadJson(a2.supplyGoldenCaseManifest||manifest());return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;