import { SUPPLY_DOCUMENT_MAPPING_SCRIPT } from "./SupplyDocumentMappingScript";
import { SUPPLY_LEGAL_CLOSURE_SCRIPT } from "./SupplyLegalClosureScript";
import { SUPPLY_STATE_CONSISTENCY_SCRIPT } from "./SupplyStateConsistencyScript";

export const SUPPLY_FINALIZATION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");
if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var catalogueKey="contrataIaSupplyCatalogue";
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function readCatalogue(){var c=readJson(sessionStorage,catalogueKey);if(Array.isArray(c.items)&&c.items.length)return c;c=readJson(localStorage,catalogueKey);if(Array.isArray(c.items)&&c.items.length)sessionStorage.setItem(catalogueKey,JSON.stringify(c));return c;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-finalization"}}));}
function readyForBlock(){var a=readAnswers();return a.supplyLegalBlockValidated===true&&!!a.supplyPcapLegalDraft;}
function check(label,ok,detail){return '<li><strong>'+esc(label)+':</strong> '+(ok?'✓':'⚠')+' '+esc(detail)+'</li>';}
function buildCard(){var a=readAnswers(),c=readCatalogue();var catalogueOk=Array.isArray(c.items)&&c.items.length>0&&Number(c.total)>0;var temporalOk=a.supplyCataloguePeriodValidated===true&&Number(a.supplyCatalogueReferenceMonths)>0;var projectedOk=Number(a.supplyCatalogueProjectedTotalConsumptionExVat)>0||Number(a.supplyCatalogueProjectedEstimatedValueExVat)>0;var budgetOk=Number.isFinite(Number(a.supplyMaximumApprovedBudgetExVat))&&Number(a.supplyMaximumApprovedBudgetExVat)>0;var durationOk=Number.isFinite(Number(a.initialDurationMonths))&&Number(a.initialDurationMonths)>0;var extensionsOk=!Array.isArray(a.extensionMonths)||a.extensionMonths.every(function(v){return Number.isFinite(Number(v))&&Number(v)>0;});var criteriaOk=!!a.supplyAwardCriteriaMode;var deliveryOk=Number.isFinite(Number(a.supplyDeliveryDeadlineDays))&&Number(a.supplyDeliveryDeadlineDays)>0;var placesOk=a.supplyDeliveryPlacesDefined!==undefined;var replacementOk=a.supplyReplacementRequired!==undefined;var legalOk=a.supplyLegalBlockValidated===true&&!!a.supplyPcapLegalDraft;var allOk=catalogueOk&&temporalOk&&projectedOk&&budgetOk&&durationOk&&extensionsOk&&criteriaOk&&deliveryOk&&placesOk&&replacementOk&&legalOk;
var html='<div id="supplyFinalizationCard" class="card"><h3>4. Comprobaciones finales y preparación documental</h3><p>Contrata-IA comprueba automáticamente si dispone ya de los datos estructurales necesarios para preparar la documentación del expediente.</p><ul>';
html+=check('Objeto y naturaleza',true,'Suministro identificado y rama específica aplicada.');
html+=check('Catálogo por lote',catalogueOk,catalogueOk?String(c.items.length)+' artículos importados; base económica de la tabla '+Number(c.total).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' € sin IVA.':'Falta una relación válida de artículos.');
html+=check('Horizonte temporal del catálogo',temporalOk,temporalOk?'Las cantidades de la tabla representan '+Number(a.supplyCatalogueReferenceMonths)+' meses.':'Debe indicarse qué período representan las cantidades importadas.');
html+=check('Proyección de consumo',projectedOk,projectedOk?'La proyección temporal de consumo está validada como referencia y no se confunde con el presupuesto contractual.':'Falta validar la proyección de consumo.');
html+=check('Presupuesto máximo para toda la vigencia',budgetOk,budgetOk?Number(a.supplyMaximumApprovedBudgetExVat).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' € sin IVA como límite económico aprobado para la vigencia, incluidas las prórrogas.':'Falta introducir o validar el presupuesto máximo aprobado para toda la vigencia.');
html+=check('Duración y prórrogas',durationOk&&extensionsOk,durationOk&&extensionsOk?'Periodo inicial de '+Number(a.initialDurationMonths)+' meses; las prórrogas no incrementan automáticamente el presupuesto máximo.':'Falta duración o estructura de prórrogas.');
html+=check('Valor estimado',a.supplyEstimatedValueValidated===true,a.supplyEstimatedValueValidated===true?Number(a.supplyEstimatedValueExVat).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' € sin IVA, validado separadamente de la proyección de consumo.':'Pendiente de cierre jurídico conforme al artículo 101 LCSP y a las modificaciones previstas.');
html+=check('Criterios de adjudicación',criteriaOk,criteriaOk?(a.supplyAwardCriteriaMode==='PRICE_ONLY'?'Solo precio, con motivación reforzada y control jurídico final.':'Varios criterios objetivos cuantificables mediante fórmula.'):'Falta validar la estructura de criterios.');
html+=check('Condiciones técnicas de entrega',deliveryOk&&placesOk&&replacementOk,deliveryOk&&placesOk&&replacementOk?'Plazo de entrega, centros y régimen de sustitución definidos.':'Queda alguna condición básica de entrega pendiente.');
html+=check('Solvencia, garantías y condición especial',legalOk,legalOk?'Conclusión jurídica validada y motivación conservada para el PCAP.':'Falta validar el bloque jurídico.');
html+='</ul>';
if(allOk){if(a.supplyDocumentPreparationValidated===true){html+='<div class="info"><strong>Expediente preparado para documentación.</strong> La información está consolidada para alimentar la Memoria justificativa, el PCAP y el PPT. El cierre del valor estimado y de la motivación específica del criterio único, si procede, se realiza en el bloque 5.1 antes de validar definitivamente el mapeo.</div><div class="info"><strong>Importante:</strong> esta validación de integridad no sustituye la revisión jurídica ni la comprobación de la normativa vigente y del modelo de pliego aplicable.</div>';}else{html+='<div class="info"><strong>No se detectan datos estructurales esenciales pendientes para iniciar el mapeo documental.</strong> Los controles jurídicos finales se cerrarán en el bloque 5.1.</div><button id="validateSupplyDocumentPreparation" type="button">Validar expediente para preparación documental</button>';}}else{html+='<div class="warning"><strong>El expediente todavía no debe pasar a generación documental.</strong> Complete únicamente los elementos marcados con ⚠. No se volverán a preguntar decisiones ya deducidas o validadas.</div>';}
html+='</div>';return html;}
function ensure(){var existing=document.getElementById("supplyFinalizationCard");if(!readyForBlock()){if(existing)existing.remove();return;}if(existing)return;var q=document.getElementById("supplyQualificationCard");if(q)q.insertAdjacentHTML("afterend",buildCard());else work.insertAdjacentHTML("beforeend",buildCard());}
function rerender(){var old=document.getElementById("supplyFinalizationCard");if(old)old.remove();ensure();}
work.addEventListener("click",function(event){var t=event.target;if(!t||t.id!=="validateSupplyDocumentPreparation")return;var a=readAnswers();a.supplyDocumentPreparationValidated=true;a.supplyDocumentPreparationStatus="READY_FOR_TEMPLATE_MAPPING";saveAnswers(a,"supply-document-preparation-validated");rerender();});
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(rerender,0);});
var observer=new MutationObserver(function(){ensure();});observer.observe(work,{childList:true,subtree:true});ensure();
})();` + SUPPLY_DOCUMENT_MAPPING_SCRIPT + SUPPLY_LEGAL_CLOSURE_SCRIPT + SUPPLY_STATE_CONSISTENCY_SCRIPT;
