export const SUPPLY_OFFICIAL_ANNEX_DRAFT_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-official-annex-draft"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function ready(a){return a.supplyOfficialTemplatePendingFieldsValidated===true&&a.supplyCurrentTenderBudgetValidated===true&&a.supplyCurrentBudgetAllocationValidated===true&&a.supplyAbnormallyLowParametersValidated===true&&a.supplyTieBreakValidated===true&&a.supplySpecificPenaltiesDecisionValidated===true&&a.supplyCurrentTenderBudgetRelationship==="INITIAL_PBL_DISTINCT_FROM_DA33_MAXIMUM_BUDGET";}
function annualities(a){if(!Array.isArray(a.supplyCurrentBudgetAnnualities))return "";return a.supplyCurrentBudgetAnnualities.map(function(x){return String(x.year)+": "+money(x.amount);}).join(" · ");}
function extensionText(a){var ext=Array.isArray(a.extensionMonths)?a.extensionMonths:[];return ext.map(function(x,i){return "Prórroga "+(i+1)+": "+Number(x)+" meses";}).join("; ");}
function tieText(a){return a.supplyTieBreakMode==="LEGAL_ART_147_2"?"Se aplicará el régimen supletorio previsto en el artículo 147.2 LCSP.":String(a.supplyTieBreakSpecificText||"Criterios específicos de desempate validados.");}
function penaltyText(a){return a.supplySpecificPenaltiesMode==="NONE"?"No se establecen penalidades específicas adicionales; resulta de aplicación el régimen legal correspondiente, incluida la demora conforme al artículo 193 LCSP.":String(a.supplySpecificPenaltiesText||"Penalidades específicas validadas.");}
function cleanSentence(v){var s=String(v||"").trim();while(s.endsWith("."))s=s.slice(0,-1).trim();return s+".";}
function xmlEscape(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");}
function p(text,style){var s=style||"Normal";return '<w:p><w:pPr><w:pStyle w:val="'+s+'"/><w:spacing w:after="120"/><w:jc w:val="'+(s==="Title"?"center":"both")+'"/></w:pPr><w:r><w:t xml:space="preserve">'+xmlEscape(text)+'</w:t></w:r></w:p>';}
function crc32(bytes){var crc=0xffffffff;for(var i=0;i<bytes.length;i++){crc^=bytes[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function u16(v){var x=new Uint8Array(2);new DataView(x.buffer).setUint16(0,v&65535,true);return x;}
function u32(v){var x=new Uint8Array(4);new DataView(x.buffer).setUint32(0,v>>>0,true);return x;}
function concat(parts){var n=0;for(var i=0;i<parts.length;i++)n+=parts[i].length;var out=new Uint8Array(n),pos=0;for(var j=0;j<parts.length;j++){out.set(parts[j],pos);pos+=parts[j].length;}return out;}
function zip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0;for(var i=0;i<entries.length;i++){var name=enc.encode(entries[i].name),data=entries[i].data,crc=crc32(data);var local=concat([new Uint8Array([80,75,3,4]),u16(20),u16(2048),u16(0),u16(0),u16(0x5c21),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),u16(20),u16(20),u16(2048),u16(0),u16(0),u16(0x5c21),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length;}var central=concat(centrals);var end=concat([new Uint8Array([80,75,5,6]),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(central.length),u32(offset),u16(0)]);return concat(locals.concat([central,end]));}
function buildDocx(a){var enc=new TextEncoder(),body=[];body.push(p("BORRADOR PARAMETRIZADO DEL ANEXO I DEL DPCAF / PCAP","Title"));body.push(p("Expediente "+String(a.administrativeFileNumber||"CONTR/2026/240267")));body.push(p("Documento generado como borrador editable a partir del modelo oficial validado "+String(a.supplyOfficialTemplateId||"")+". No sustituye las cláusulas generales del modelo oficial ni su revisión jurídica final."));
body.push(p("CABECERA DEL ANEXO I","Heading1"));body.push(p("Título: "+String(a.contractTitle||"")));body.push(p("Localidad / NUTS: "+String(a.supplyMainDeliveryLocality||"")+" / "+String(a.supplyMainExecutionNuts||"")));
body.push(p("1. OBJETO, CPV, LOTES Y CONTRATO EN FUNCIÓN DE LAS NECESIDADES","Heading1"));body.push(p(String(a.needAndPurpose||"")+(a.scopeDetail?" "+String(a.scopeDetail):"")));body.push(p("CPV: 44316400-2 — Artículos de ferretería."));body.push(p("Lote único. Suministro en función de las necesidades conforme a la disposición adicional 33.ª LCSP. Presupuesto máximo aprobado para toda la vigencia: "+money(a.supplyMaximumApprovedBudgetExVat)+" sin IVA. Las prórrogas no incrementan por sí solas este límite."));
body.push(p("2. PRESUPUESTO BASE, VALOR ESTIMADO Y PRECIO","Heading1"));body.push(p("Presupuesto base de licitación correspondiente a la duración inicial: "+money(a.supplyCurrentTenderBudgetExVat)+" sin IVA; IVA "+Number(a.supplyCurrentTenderVatRate||0).toLocaleString("es-ES")+" %; total IVA incluido: "+money(a.supplyCurrentTenderBudgetInclVat)+"."));body.push(p("Presupuesto máximo DA 33.ª para toda la vigencia: "+money(a.supplyMaximumApprovedBudgetExVat)+" sin IVA."));body.push(p("Valor estimado: "+money(a.supplyEstimatedValueExVat)+" sin IVA."));body.push(p("Sistema de determinación del precio: precios unitarios por referencia del catálogo validado de 98 artículos."));body.push(p("Aplicación presupuestaria: "+String(a.supplyCurrentBudgetApplication||"")+". Anualidades IVA incluido: "+annualities(a)+"."));
body.push(p("3. DURACIÓN Y PRÓRROGAS","Heading1"));body.push(p("Duración inicial: "+Number(a.initialDurationMonths||0)+" meses. "+extensionText(a)+". El presupuesto máximo DA 33.ª rige para toda la vigencia y no aumenta automáticamente por las prórrogas."));
body.push(p("7. CRITERIOS DE ADJUDICACIÓN, ANORMALIDAD Y DESEMPATE","Heading1"));body.push(p("Precio como único criterio de adjudicación: 100 puntos, con motivación específica validada para este expediente."));body.push(p("Parámetros objetivos de oferta anormalmente baja: "+cleanSentence(a.supplyAbnormallyLowParametersText)));body.push(p("Desempate: "+tieText(a)));
body.push(p("8. CONDICIÓN ESPECIAL DE EJECUCIÓN","Heading1"));body.push(p("Gestión y retirada de embalajes y residuos vinculados directamente a las entregas, conforme a la redacción validada del artículo 202.1 LCSP."));body.push(p("10. PENALIDADES ESPECÍFICAS","Heading1"));body.push(p(penaltyText(a)));
body.push(p("14. MODIFICACIÓN PREVISTA","Heading1"));body.push(p("Modificación prevista por mayores necesidades hasta un máximo del "+Number(a.supplyNeedsModificationMaximumIncreasePercent||20).toLocaleString("es-ES")+" %, conforme a la disposición adicional 33.ª y al artículo 204 LCSP, manteniendo el mismo objeto y los precios unitarios previstos, sin incorporación de nuevos artículos ni nuevos precios unitarios."));
body.push(p("CONDICIÓN DE ENTREGA","Heading1"));body.push(p("Plazo máximo de entrega: "+Number(a.supplyDeliveryDeadlineDays||5)+" días hábiles. Se configura como condición de ejecución y no como criterio adicional de adjudicación."));body.push(p("ADVERTENCIA DE REVISIÓN","Heading1"));body.push(p("Este archivo constituye un borrador editable del Anexo I parametrizado. Antes de aprobar o firmar el PCAP deberá comprobarse su inserción fiel en el modelo oficial vigente, la coherencia con la Memoria justificativa y el PPT, y la normativa vigente aplicable."));body.push('<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr>');
var documentXml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+body.join("")+'</w:body></w:document>';var styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Source Sans Pro" w:hAnsi="Source Sans Pro"/><w:sz w:val="20"/><w:lang w:val="es-ES"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="24"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="21"/></w:rPr></w:style></w:styles>';
return zip([{name:"[Content_Types].xml",data:enc.encode('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>')},{name:"_rels/.rels",data:enc.encode('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>')},{name:"word/_rels/document.xml.rels",data:enc.encode('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>')},{name:"word/document.xml",data:enc.encode(documentXml)},{name:"word/styles.xml",data:enc.encode(styles)}]);}
function card(a){var html='<div id="supplyOfficialAnnexDraftCard" class="card" style="margin-top:14px"><h3>9. Primer borrador editable del Anexo I</h3>';if(!ready(a)){html+='<div class="warning"><strong>Paso todavía no habilitado.</strong> Debe quedar completado y validado el Paso 8 con PBL inicial y presupuesto máximo DA 33.ª diferenciados.</div></div>';return html;}html+='<div class="info"><strong>Preparado para generar.</strong> Contrata-IA utilizará exclusivamente los datos ya validados para crear un DOCX editable del Anexo I.</div><ul><li>Modelo oficial vinculado: '+esc(a.supplyOfficialTemplateId||'')+'</li><li>Expediente: '+esc(a.administrativeFileNumber||'')+'</li><li>PBL inicial: '+money(a.supplyCurrentTenderBudgetExVat)+' sin IVA · '+money(a.supplyCurrentTenderBudgetInclVat)+' IVA incluido.</li><li>Presupuesto máximo DA 33.ª: '+money(a.supplyMaximumApprovedBudgetExVat)+' sin IVA para toda la vigencia.</li><li>Valor estimado: '+money(a.supplyEstimatedValueExVat)+' sin IVA.</li></ul><div class="warning"><strong>Alcance del borrador.</strong> Se genera el Anexo I parametrizado para revisión. El Paso 10 contrastará cada dato con el destino exacto del modelo oficial antes de producir una versión completa.</div><button id="generateSupplyOfficialAnnexDraft" type="button">Generar borrador editable DOCX corregido</button>';if(a.supplyOfficialAnnexDraftGenerated===true)html+='<div class="info"><strong>Borrador corregido generado.</strong> Queda disponible para la comprobación documental previa al Paso 10.</div>';html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyOfficialAnnexDraftCard");if(old)old.remove();var a=readAnswers();var anchor=document.getElementById("supplyOfficialTemplatePendingFieldsCard");if(!anchor)return;anchor.insertAdjacentHTML("afterend",card(a));}
work.addEventListener("click",function(event){var t=event.target;if(!t||t.id!=="generateSupplyOfficialAnnexDraft")return;var a=readAnswers();if(!ready(a)){alert("Debe completarse primero el Paso 8 corregido.");return;}var bytes=buildDocx(a);var blob=new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"});var url=URL.createObjectURL(blob);var link=document.createElement("a");link.href=url;link.download=String(a.administrativeFileNumber||"CONTR-2026-240267").replaceAll("/","-")+"_Anexo_I_Borrador_Corregido_Contrata-IA.docx";document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);a.supplyOfficialAnnexDraftGenerated=true;a.supplyOfficialAnnexDraftGeneratedAt=new Date().toISOString();a.supplyOfficialAnnexDraftScope="ANNEX_I_PARAMETERIZED_DRAFT_CORRECTED_NOT_FULL_OFFICIAL_PCAP";saveAnswers(a,"supply-official-annex-draft-generated");ensure();},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);
})();`;
