export const SUPPLY_CATALOGUE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");
if(!work)return;
var storageKey="contrataIaSupplyCatalogue";
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function parseNumber(v){var s=String(v||"").trim().split(" ").join("").replaceAll("€","");if(!s)return NaN;var c=s.lastIndexOf(","),d=s.lastIndexOf(".");if(c>=0&&d>=0){if(c>d)s=s.replaceAll(".","").replace(",",".");else s=s.replaceAll(",","");}else if(c>=0)s=s.replace(",",".");else if(d>=0){var p=s.split(".");if(p.length>2||((p[p.length-1]||"").length===3&&p.length===2))s=p.join("");}return Number(s);}
function splitLine(line){var out=[],cur="",quoted=false;for(var i=0;i<line.length;i++){var ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(ch===';'&&!quoted){out.push(cur);cur="";}else cur+=ch;}out.push(cur);return out;}
function templateText(withSuggestions){var nl=String.fromCharCode(10);var rows=["Referencia;Denominación;Descripción técnica mínima;Unidad;Cantidad estimada;Precio unitario estimado sin IVA;Lote;CPV"];if(withSuggestions){rows.push(";Tornillería y elementos de fijación;;unidad;;;;");rows.push(";Cerrajería y herrajes;;unidad;;;;");rows.push(";Adhesivos y selladores;;unidad;;;;");rows.push(";Herramientas manuales;;unidad;;;;");rows.push(";Consumibles y pequeños repuestos;;unidad;;;;");}else{rows.push("ART-001;;;;;;;");}return "\uFEFF"+rows.join(nl);}
function download(text,name){var blob=new Blob([text],{type:"text/csv;charset=utf-8"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
function catalogueCard(){return '<div id="supplyCatalogueCard" class="card"><h2>Relación de artículos del suministro</h2><p>Para suministros con varias referencias, la vía principal es importar una tabla preparada en Excel. La plantilla utiliza formato CSV con separador punto y coma, compatible con Excel.</p><div class="toolbar"><button id="downloadSupplyTemplate" type="button">Descargar plantilla para Excel</button><button id="suggestSupplyCategories" type="button" class="secondary">Proponer categorías orientativas</button></div><p class="muted">La propuesta automática solo sirve como ayuda inicial. La unidad promotora debe validar los artículos, cantidades y especificaciones que responden a su necesidad real.</p><label><strong>Importar relación cumplimentada</strong></label><input id="supplyFile" type="file" accept=".csv,text/csv"><div id="supplyCatalogueSummary"></div></div>';}
function renderSummary(data){var box=document.getElementById("supplyCatalogueSummary");if(!box)return;if(!data||!Array.isArray(data.items)||data.items.length===0){box.innerHTML='<p class="muted">Todavía no se ha importado ninguna relación de artículos.</p>';return;}var issues=data.issues||[];var lots=data.lots||[];var html='<div class="info"><strong>'+data.items.length+' artículos importados</strong><br>Importe estimado de las filas válidas: <strong>'+Number(data.total||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' €</strong><br>'+(issues.length?issues.length+' incidencias requieren revisión.':'Sin incidencias básicas detectadas.')+(lots.length?'<br>Lotes indicados en la tabla: '+esc(lots.join(", ")):'')+'</div>';if(issues.length)html+='<ul>'+issues.slice(0,12).map(function(x){return '<li>'+esc(x)+'</li>';}).join("")+'</ul>';html+='<details><summary>Ver primeras referencias importadas</summary><table style="width:100%;border-collapse:collapse"><thead><tr><th>Ref.</th><th>Denominación</th><th>Cantidad</th><th>Precio</th><th>Lote</th></tr></thead><tbody>'+data.items.slice(0,10).map(function(x){return '<tr><td>'+esc(x.referencia)+'</td><td>'+esc(x.denominacion)+'</td><td>'+esc(x.cantidad)+'</td><td>'+esc(x.precio)+'</td><td>'+esc(x.lote)+'</td></tr>';}).join("")+'</tbody></table></details>';box.innerHTML=html;}
function parseCatalogue(text){var nl=String.fromCharCode(10);var lines=String(text||"").replaceAll(String.fromCharCode(13),"").split(nl).filter(function(x){return x.trim();});if(lines.length<2)throw new Error("La tabla no contiene artículos.");var items=[],issues=[],refs={},lots={};var total=0;for(var i=1;i<lines.length;i++){var c=splitLine(lines[i]);while(c.length<8)c.push("");var item={referencia:(c[0]||"").trim(),denominacion:(c[1]||"").trim(),descripcion:(c[2]||"").trim(),unidad:(c[3]||"").trim(),cantidad:(c[4]||"").trim(),precio:(c[5]||"").trim(),lote:(c[6]||"").trim(),cpv:(c[7]||"").trim()};if(!item.referencia&&!item.denominacion&&!item.cantidad&&!item.precio)continue;items.push(item);var row=i+1;if(!item.denominacion)issues.push("Fila "+row+": falta la denominación del artículo.");var q=parseNumber(item.cantidad),p=parseNumber(item.precio);if(!Number.isFinite(q)||q<=0)issues.push("Fila "+row+": cantidad estimada no válida.");if(!Number.isFinite(p)||p<0)issues.push("Fila "+row+": precio unitario no válido.");if(Number.isFinite(q)&&q>0&&Number.isFinite(p)&&p>=0)total+=q*p;if(item.referencia){var key=item.referencia.toLocaleLowerCase("es-ES");if(refs[key])issues.push("Fila "+row+": referencia duplicada "+item.referencia+".");refs[key]=true;}if(item.lote)lots[item.lote]=true;}return {items:items,issues:issues,total:total,lots:Object.keys(lots),importedAt:new Date().toISOString()};}
function isSupply(){var txt=work.textContent||"";return txt.includes("Suministros")||txt.includes("Naturaleza contractual propuesta: suministros");}
function ensureCard(){var current=document.getElementById("supplyCatalogueCard");if(!isSupply()){if(current)current.remove();return;}if(!current){work.insertAdjacentHTML("beforeend",catalogueCard());var saved={};try{saved=JSON.parse(sessionStorage.getItem(storageKey)||"{}");}catch(e){}renderSummary(saved);} }
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;if(t.id==="downloadSupplyTemplate"){download(templateText(false),"plantilla_articulos_suministro.csv");}if(t.id==="suggestSupplyCategories"){var a={};try{a=JSON.parse(sessionStorage.getItem("contrataIaAdaptiveAnswers")||"{}");}catch(e){}var text=String((a.needAndPurpose||"")+" "+(a.scopeDetail||"")).toLocaleLowerCase("es-ES");if(text.includes("ferreter")){download(templateText(true),"plantilla_suministro_ferreteria_orientativa.csv");}else{var box=document.getElementById("supplyCatalogueSummary");if(box)box.innerHTML='<div class="info">No hay todavía una taxonomía específica validada para este objeto. Descargue la plantilla general y complete las referencias reales de la necesidad.</div>';}}});
work.addEventListener("change",async function(event){var t=event.target;if(!t||t.id!=="supplyFile"||!t.files||!t.files[0])return;var box=document.getElementById("supplyCatalogueSummary");try{var data=parseCatalogue(await t.files[0].text());sessionStorage.setItem(storageKey,JSON.stringify(data));renderSummary(data);}catch(e){if(box)box.innerHTML='<div class="warning">'+esc(e.message)+'</div>';}});
var observer=new MutationObserver(function(){ensureCard();});observer.observe(work,{childList:true,subtree:false});ensureCard();
})();`;
