export const SUPPLY_QUALIFICATION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");
if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-qualification"}}));}
function branchReady(){var txt=work.textContent||"";return txt.includes("Rama de suministro avanzada")||txt.includes("plazo de entrega y régimen básico de conformidad");}
function isAbbreviated(){return (work.textContent||"").includes("Abierto simplificado abreviado");}
function proposal(a){var abbreviated=isAbbreviated();var html='<div id="supplyQualificationCard" class="card"><h3>3. Aptitud, solvencia, garantías y condiciones de ejecución</h3>';
if(abbreviated){html+='<div class="info"><strong>Propuesta jurídica automática según el procedimiento seleccionado</strong><ul><li><strong>Solvencia:</strong> no se exigirá a los licitadores la acreditación de solvencia económica y financiera ni técnica o profesional.</li><li><strong>Garantía provisional:</strong> no procede en el procedimiento abierto simplificado.</li><li><strong>Garantía definitiva:</strong> no se requerirá en la tramitación abreviada.</li><li><strong>Aptitud para contratar:</strong> se mantienen las exigencias legales generales de capacidad, ausencia de prohibiciones de contratar y, cuando proceda, habilitación profesional.</li></ul><p class="muted">Fundamento principal: artículo 159.6.b y 159.6.f LCSP, en relación con el régimen general del procedimiento abierto simplificado. La configuración se somete a validación humana y verificación normativa vigente antes de cerrar los pliegos.</p></div>';}else{html+='<div class="warning"><strong>Régimen de solvencia y garantías pendiente de propuesta automática.</strong> El procedimiento mostrado no es el simplificado abreviado. Contrata-IA debe aplicar las reglas específicas del procedimiento y del tipo de contrato antes de trasladar requisitos al PCAP.</div>';}
html+='<div class="info"><strong>Condición especial de ejecución propuesta</strong><p>Para este suministro de artículos con entregas sucesivas, se propone como condición vinculada a la ejecución la correcta gestión y retirada de embalajes y residuos generados directamente por las entregas, evitando embalajes innecesarios cuando sea compatible con la protección del producto.</p><p class="muted">La LCSP exige establecer al menos una condición especial de ejecución de carácter social, ético, medioambiental o de otro orden entre las previstas legalmente, siempre vinculada al objeto del contrato. Esta redacción es una propuesta que debe validarse antes de incorporarse al PCAP.</p></div>';
if(a.supplyLegalBlockValidated===true){html+='<div class="info"><strong>Bloque 3 validado por la persona usuaria.</strong> Solvencia, garantías y condición especial de ejecución quedan aceptadas como propuesta de trabajo para la preparación documental.</div>';}else if(a.supplyLegalBlockCorrectionRequested===true){html+='<label><strong>Indique qué aspecto debe corregirse</strong></label><textarea id="supplyLegalCorrection" placeholder="Explique el cambio necesario en solvencia, garantías o condición especial de ejecución">'+esc(a.supplyLegalCorrection||"")+'</textarea><button id="saveSupplyLegalCorrection" type="button">Guardar corrección pendiente</button>';}else{html+='<div class="toolbar"><button id="validateSupplyLegalBlock" type="button">Validar propuesta</button><button id="correctSupplyLegalBlock" type="button" class="secondary">Necesito corregirla</button></div>';}
html+='</div>';return html;}
function ensure(){var existing=document.getElementById("supplyQualificationCard");if(!branchReady()){if(existing)existing.remove();return;}if(existing)return;var catalogue=document.getElementById("supplyCatalogueCard");if(catalogue)catalogue.insertAdjacentHTML("afterend",proposal(readAnswers()));else work.insertAdjacentHTML("beforeend",proposal(readAnswers()));}
function rerender(){var old=document.getElementById("supplyQualificationCard");if(old)old.remove();ensure();}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==="validateSupplyLegalBlock"){a.supplyLegalBlockValidated=true;a.supplySolvencyAccreditation="EXEMPT_ART_159_6_B";a.supplyDefinitiveGuarantee="NOT_REQUIRED_ART_159_6_F";a.supplySpecialExecutionCondition="DELIVERY_PACKAGING_WASTE";delete a.supplyLegalBlockCorrectionRequested;delete a.supplyLegalCorrection;saveAnswers(a,"supply-legal-block-validated");rerender();}if(t.id==="correctSupplyLegalBlock"){a.supplyLegalBlockCorrectionRequested=true;saveAnswers(a,"supply-legal-block-correction-requested");rerender();}if(t.id==="saveSupplyLegalCorrection"){var el=document.getElementById("supplyLegalCorrection");if(!el||!el.value.trim()){alert("Indique qué aspecto debe corregirse.");return;}a.supplyLegalCorrection=el.value.trim();a.supplyLegalBlockValidated=false;saveAnswers(a,"supply-legal-block-correction");rerender();}});
var observer=new MutationObserver(function(){ensure();});observer.observe(work,{childList:true,subtree:true});ensure();
})();`;
