export const SUPPLY_AWARD_CRITERIA_LEGAL_REVIEW_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-award-criteria-legal-review"}}));}
function needsReview(){var a=readAnswers();return a.supplyDocumentPreparationValidated===true&&a.supplyAwardCriteriaMode==="PRICE_ONLY"&&a.supplyAwardCriteriaLegalReviewValidated!==true;}
function card(){return '<div id="supplyAwardCriteriaLegalReviewCard" class="card warning" style="margin-top:12px"><h4>Control jurídico del criterio único de precio</h4><p><strong>Propuesta de Contrata-IA:</strong> no cerrar todavía el PCAP con precio como único criterio. En suministros, el artículo 145.3.f LCSP solo permite esa excepción cuando los productos estén perfectamente definidos, no pueda variarse el plazo de entrega y no puedan introducirse modificaciones de ninguna clase.</p><p>En un suministro sucesivo por necesidades, el sistema debe comprobar expresamente esas tres condiciones. Como medida preventiva, se propone pasar a <strong>pluralidad de criterios automáticos</strong>, manteniendo la compatibilidad con el artículo 159.6.c LCSP.</p><div class="card" style="margin-top:10px"><strong>Propuesta técnica orientativa para validación humana</strong><p>Precio: <input id="supplyPriceWeight" type="number" min="1" max="99" value="85" style="width:90px"> puntos</p><p>Mejora objetiva del plazo de entrega: <input id="supplyDeliveryWeight" type="number" min="1" max="99" value="15" style="width:90px"> puntos</p><p class="muted">La ponderación es una propuesta técnica de trabajo, no un porcentaje impuesto por la LCSP. La suma debe ser 100 y ambos criterios se evaluarán mediante fórmula.</p></div><div class="toolbar"><button id="applySupplyMultipleCriteria" type="button">Aplicar propuesta y continuar</button><button id="keepSupplyPriceOnly" type="button" class="secondary">Mantener solo precio y justificar excepción</button></div><div id="supplyPriceOnlyExceptionBox"></div></div>';}
function ensure(){var mapping=document.getElementById("supplyDocumentMappingCard");var old=document.getElementById("supplyAwardCriteriaLegalReviewCard");if(!mapping||!needsReview()){if(old)old.remove();return;}if(old)return;var controls=Array.from(mapping.querySelectorAll("button"));controls.forEach(function(b){if(b.id==="validateSupplyDocumentMapping")b.style.display="none";});mapping.insertAdjacentHTML("beforeend",card());}
function rerender(){var old=document.getElementById("supplyAwardCriteriaLegalReviewCard");if(old)old.remove();ensure();}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==="applySupplyMultipleCriteria"){var p=document.getElementById("supplyPriceWeight"),d=document.getElementById("supplyDeliveryWeight");var pw=p?Number(p.value):NaN,dw=d?Number(d.value):NaN;if(!Number.isFinite(pw)||!Number.isFinite(dw)||pw<=0||dw<=0||pw+dw!==100){alert("La ponderación debe sumar 100 puntos.");return;}a.supplyAwardCriteriaMode="MULTIPLE_FORMULA";a.supplyAwardCriteriaLegalReviewValidated=true;a.supplyAwardCriteriaStructure=[{id:"PRICE",weight:pw,formulaRequired:true},{id:"DELIVERY_TIME_IMPROVEMENT",weight:dw,formulaRequired:true}];a.supplyAwardCriteriaLegalGrounds=["LCSP art. 145.3.f","LCSP art. 145.6","LCSP art. 159.6.c"];a.supplyAwardCriteriaLegalReason="Se adopta pluralidad de criterios automáticos porque no se ha acreditado de forma suficiente la excepción que permitiría utilizar el precio como único factor determinante en un suministro por necesidades.";saveAnswers(a,"supply-award-criteria-multiple-formula");location.reload();}
if(t.id==="keepSupplyPriceOnly"){var box=document.getElementById("supplyPriceOnlyExceptionBox");if(box)box.innerHTML='<div class="warning"><p>Para mantener solo precio deben quedar acreditadas las tres condiciones del artículo 145.3.f LCSP:</p><label><input id="priceOnlyProductsDefined" type="checkbox" style="width:auto"> Productos perfectamente definidos.</label><br><label><input id="priceOnlyDeliveryFixed" type="checkbox" style="width:auto"> El plazo de entrega no puede variar.</label><br><label><input id="priceOnlyNoMods" type="checkbox" style="width:auto"> No se prevén modificaciones de ninguna clase.</label><label><strong>Motivación concreta</strong></label><textarea id="priceOnlyReason" placeholder="Explique por qué el precio es el único factor determinante en este suministro"></textarea><button id="validateSupplyPriceOnlyException" type="button">Validar excepción motivada</button></div>';}
if(t.id==="validateSupplyPriceOnlyException"){var c1=document.getElementById("priceOnlyProductsDefined"),c2=document.getElementById("priceOnlyDeliveryFixed"),c3=document.getElementById("priceOnlyNoMods"),r=document.getElementById("priceOnlyReason");if(!c1||!c2||!c3||!c1.checked||!c2.checked||!c3.checked||!r||!r.value.trim()){alert("No puede mantenerse el criterio único de precio sin acreditar las tres condiciones y una motivación concreta.");return;}a.supplyAwardCriteriaLegalReviewValidated=true;a.supplyAwardCriteriaPriceOnlyExceptionValidated=true;a.supplyAwardCriteriaPriceOnlyReason=r.value.trim();a.supplyAwardCriteriaLegalGrounds=["LCSP art. 145.3.f","LCSP art. 159.6.c"];saveAnswers(a,"supply-award-criteria-price-only-exception");location.reload();}});
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(rerender,0);});
var observer=new MutationObserver(function(){ensure();});observer.observe(work,{childList:true,subtree:true});ensure();
})();`;
