export const SUPPLY_PBL_BREAKDOWN_PROPOSAL_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-pbl-breakdown-proposal"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
var LINE1="Desglose técnico-económico: el PBL de la duración inicial asciende a 10.552,44 € sin IVA y se determina por la suma de las cantidades estimadas de las referencias multiplicadas por sus precios unitarios de licitación.";
var LINE2="Los precios unitarios integran los costes necesarios para ejecutar el suministro, incluidos adquisición, transporte, distribución, entrega, estructura empresarial, margen y demás gastos inherentes cuando no hayan sido cuantificados separadamente por la Administración; no se adicionan importes distintos al PBL calculado.";
var PROPOSAL=LINE1+" "+LINE2;
var LEGAL="Fundamento: artículo 100.2 LCSP. En este suministro por precios unitarios no se asignan porcentajes ficticios de costes indirectos: se explica la formación del PBL y la integración en los precios unitarios de los costes necesarios no cuantificados separadamente por la Administración.";
function eligible(a){var b=Array.isArray(a.supplyAnnexIComprehensiveAuditBlockers)?a.supplyAnnexIComprehensiveAuditBlockers:[];var auditDone=Array.isArray(a.supplyAnnexIComprehensiveAuditBlockers);return a.supplyAnnexIFinalAuditValidated===true&&(b.some(function(x){return String(x).indexOf("2.A. Desglose del PBL")>=0;})||(auditDone&&a.supplyPblBreakdownClosureValidated!==true)||a.supplyPblBreakdownProposalValidated===true||a.supplyPblBreakdownClosureValidated===true);}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function paragraphs(doc){var a=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));a.sort(function(x,y){if(x===y)return 0;return x.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1;});return a;}
function find(ps,needle,from){var q=norm(needle);for(var i=from||0;i<ps.length;i++)if(norm(ps[i].textContent).indexOf(q)>=0)return i;return -1;}
function patch(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");var ps=paragraphs(doc),a2=find(ps,"2.A.PRESUPUESTO BASE DE LICITACIÓN",0);if(a2<0)a2=find(ps,"2.A. PRESUPUESTO BASE DE LICITACIÓN",0);var a2b=find(ps,"2.B.VALOR ESTIMADO DEL CONTRATO",a2>=0?a2:0);if(a2<0||a2b<0||a2b<=a2)throw new Error("No se ha podido delimitar el apartado 2.A del Anexo I.");var d=find(ps,"Importe desglosado:",a2);if(d<0||d>=a2b)throw new Error("No se ha localizado «Importe desglosado» dentro del apartado 2.A.");var blanks=[];for(var i=d+1;i<a2b&&i<d+8;i++){if(/_{3,}/.test(String(ps[i].textContent||"")))blanks.push(ps[i]);}
if(blanks.length<2){var body0=norm(ps.slice(d,a2b).map(function(p){return p.textContent;}).join(" "));if(body0.indexOf("DESGLOSE TÉCNICO-ECONÓMICO")>=0&&body0.indexOf("TRANSPORTE")>=0)return new XMLSerializer().serializeToString(doc);throw new Error("No se han localizado las dos líneas residuales del desglose del PBL; se cancela para no sobrescribir contenido no reconocido.");}
blanks[0].textContent="- "+LINE1;blanks[1].textContent="- "+LINE2;var body=norm(ps.slice(d,a2b).map(function(p){return p.textContent;}).join(" "));if(body.indexOf("10.552,44")<0||body.indexOf("PRECIOS UNITARIOS")<0||body.indexOf("TRANSPORTE")<0)throw new Error("La inserción del desglose no supera la comprobación documental.");return new XMLSerializer().serializeToString(doc);}
async function process(bytes){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");content.data=new TextEncoder().encode(patch(new TextDecoder("utf-8").decode(content.data)));var output=writeStoredZip(entries);await readZip(output);return output;}
function download(bytes){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="CONTR-2026-240267_PCAP_Oficial_AnexoI_PBL_Cerrado_Contrata-IA.odt";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function card(){var a=readAnswers();if(!eligible(a))return "";var html='<div id="supplyPblBreakdownProposalCard" class="card" style="margin-top:14px"><h3>11.2.3 Cierre técnico-económico del desglose del PBL</h3><div class="info"><strong>Control reforzado del documento real.</strong> Aunque 11.2.2 haya informado inicialmente de 0 bloqueantes, el cierre del PBL no se da por superado hasta comprobar e insertar físicamente el desglose del apartado 2.A en el ODT.</div><div class="info"><strong>Propuesta motivada, no decisión automática.</strong> Para este suministro por precios unitarios se propone cerrar el apartado 2.A sin inventar porcentajes de costes indirectos.</div><div class="warning"><strong>Redacción propuesta:</strong><p>'+esc(PROPOSAL)+'</p><p><strong>'+esc(LEGAL)+'</strong></p></div>';
if(a.supplyPblBreakdownProposalValidated!==true){html+='<button id="validateSupplyPblBreakdownProposal" type="button">Validar propuesta de desglose PBL</button><button id="rejectSupplyPblBreakdownProposal" type="button" class="secondary">Necesito otro desglose</button>';}else if(a.supplyPblBreakdownClosureValidated!==true){html+='<div class="info"><strong>Propuesta validada.</strong> Seleccione el ODT más reciente, con el apartado 14 ya corregido, para insertar el desglose únicamente en las dos líneas residuales del 2.A.</div><input id="pblBreakdownClosureFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runPblBreakdownClosure" type="button">Insertar desglose PBL y generar ODT</button>';}else{html+='<div class="info"><strong>Desglose PBL insertado y comprobado.</strong> Vuelva a ejecutar la auditoría integral 11.2.2 con el ODT descargado. Si no aparecen nuevos bloqueantes reales, el Anexo I queda cerrado.</div>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyPblBreakdownProposalCard");if(old)old.remove();var anchor=document.getElementById("supplySection14DeterministicRepairCard")||document.getElementById("supplyAnnexIComprehensiveAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target)return;if(e.target.id==="validateSupplyPblBreakdownProposal"){var a=readAnswers();a.supplyPblBreakdownProposalValidated=true;a.supplyPblBreakdownProposalText=PROPOSAL;a.supplyPblBreakdownProposalLegalBasis="art. 100.2 LCSP; formación del PBL mediante cantidades estimadas y precios unitarios";a.supplyPblBreakdownProposalValidatedAt=new Date().toISOString();save(a);ensure();return;}if(e.target.id==="rejectSupplyPblBreakdownProposal"){var a2=readAnswers();a2.supplyPblBreakdownProposalValidated=false;a2.supplyPblBreakdownProposalRejected=true;save(a2);alert("La propuesta no se ha validado. El desglose PBL seguirá bloqueado hasta que se defina una alternativa técnicamente motivada.");ensure();return;}if(e.target.id==="runPblBreakdownClosure"){var input=document.getElementById("pblBreakdownClosureFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione el ODT más reciente con el apartado 14 ya corregido.");return;}try{var output=await process(new Uint8Array(await file.arrayBuffer())),a3=readAnswers();a3.supplyPblBreakdownClosureValidated=true;a3.supplyPblBreakdownClosureAt=new Date().toISOString();var blockers=Array.isArray(a3.supplyAnnexIComprehensiveAuditBlockers)?a3.supplyAnnexIComprehensiveAuditBlockers:[];a3.supplyAnnexIComprehensiveAuditBlockers=blockers.filter(function(x){return String(x).indexOf("2.A. Desglose del PBL")<0;});save(a3);download(output);alert("Desglose del PBL insertado y comprobado. Vuelva a ejecutar 11.2.2 con el ODT descargado para confirmar el cierre integral del Anexo I.");ensure();}catch(err){alert("No se ha podido cerrar el desglose del PBL: "+err.message);}return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;