export const SUPPLY_AWARD_CRITERIA_VISIBILITY_HOTFIX_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-award-criteria-hotfix"}}));}
function hasModification(a){return a.supplyNeedsModificationForeseen===true||Number(a.supplyNeedsModificationMaximumIncreasePercent||0)>0||Number(a.supplyNeedsModificationMaximumIncreaseExVat||0)>0;}
function priceConflict(a){return a.supplyAwardCriteriaMode==="PRICE_ONLY"&&hasModification(a);}
function pendingDefinition(a){return a.supplyAwardCriteriaMode==="MULTIPLE_FORMULA"&&a.supplyAwardCriteriaLegalReviewStatus==="RECONFIGURATION_REQUIRED"&&a.supplyAwardCriteriaStructureValidated!==true;}
function blocked(a){return priceConflict(a)||pendingDefinition(a);}
function card(a){if(priceConflict(a))return '<div id="supplyAwardCriteriaVisibilityHotfixCard" class="warning" style="margin:12px 0;padding:12px"><h4>5.2 Control jurídico de los criterios de adjudicación</h4><p><strong>Debe resolverse antes de generar documentos.</strong> El expediente mantiene precio como criterio único y, al mismo tiempo, una modificación prevista por mayores necesidades. La excepción del artículo 145.3.f LCSP exige que no puedan introducirse modificaciones de ninguna clase.</p><p>La motivación previa queda conservada como antecedente, pero no permite cerrar este punto mientras se mantenga la modificación prevista.</p><button id="hotfixSwitchSupplyCriteriaToMultiple" type="button">Reconfigurar a pluralidad de criterios automáticos</button></div>';
if(pendingDefinition(a))return '<div id="supplyAwardCriteriaVisibilityHotfixCard" class="warning" style="margin:12px 0;padding:12px"><h4>5.2 Definición de la pluralidad de criterios</h4><p>Defina el criterio objetivo adicional que sea realmente adecuado para este suministro. No se propone automáticamente una reducción del plazo de entrega.</p><label><strong>Criterio objetivo adicional</strong></label><input id="hotfixAdditionalCriterionName" placeholder="Descripción del criterio"><label><strong>Peso del precio (puntos)</strong></label><input id="hotfixPriceWeight" type="number" min="1" max="99" step="1"><label><strong>Peso del criterio adicional (puntos)</strong></label><input id="hotfixAdditionalWeight" type="number" min="1" max="99" step="1"><label><strong>Regla o fórmula objetiva de valoración</strong></label><textarea id="hotfixAdditionalCriterionFormula" placeholder="Describa cómo se medirá y puntuará mediante fórmula"></textarea><button id="hotfixSaveSupplyMultipleCriteriaDefinition" type="button">Guardar definición y continuar</button><p class="muted">Los pesos deben sumar 100 puntos.</p></div>';
return '';}
function normalize(a){if(!priceConflict(a))return false;var changed=false;if(a.supplyAwardCriteriaLegalReviewStatus!=="LEGAL_CONFLICT_ART_145_3_F_DA33"){a.supplyAwardCriteriaLegalReviewStatus="LEGAL_CONFLICT_ART_145_3_F_DA33";changed=true;}if(a.supplyAwardCriteriaLegalReviewValidated!==false){a.supplyAwardCriteriaLegalReviewValidated=false;changed=true;}if(a.supplyPriceOnlyMotivationValidated===true){a.supplyPriceOnlyMotivationPreviouslyValidated=true;a.supplyPriceOnlyMotivationValidated=false;changed=true;}if(a.supplyDocumentGenerationBlockedByAwardCriteria!==true){a.supplyDocumentGenerationBlockedByAwardCriteria=true;changed=true;}if(a.supplyDocumentMappingValidated===true){a.supplyDocumentMappingPreviouslyValidated=true;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="LEGAL_REVIEW_REQUIRED";changed=true;}if(changed)saveAnswers(a,"supply-award-criteria-hotfix-normalize");return changed;}
function render(){var a=readAnswers();normalize(a);a=readAnswers();var old=document.getElementById("supplyAwardCriteriaVisibilityHotfixCard");if(old)old.remove();if(!blocked(a))return;var map=document.getElementById("supplyDocumentMappingCard");if(!map)return;var h3=map.querySelector("h3");if(h3)h3.insertAdjacentHTML("afterend",card(a));else map.insertAdjacentHTML("afterbegin",card(a));var btn=document.getElementById("validateSupplyDocumentMapping");if(btn){btn.disabled=true;btn.style.opacity="0.55";btn.title="Debe resolverse primero el control jurídico de los criterios de adjudicación.";}}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==="hotfixSwitchSupplyCriteriaToMultiple"){a.supplyAwardCriteriaMode="MULTIPLE_FORMULA";a.supplyAwardCriteriaLegalReviewStatus="RECONFIGURATION_REQUIRED";a.supplyAwardCriteriaLegalReviewValidated=false;a.supplyAwardCriteriaStructureValidated=false;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="LEGAL_REVIEW_REQUIRED";a.supplyDocumentGenerationBlockedByAwardCriteria=true;saveAnswers(a,"supply-criteria-reconfigure-multiple-hotfix");setTimeout(render,0);}
if(t.id==="hotfixSaveSupplyMultipleCriteriaDefinition"){var n=document.getElementById("hotfixAdditionalCriterionName"),p=document.getElementById("hotfixPriceWeight"),w=document.getElementById("hotfixAdditionalWeight"),f=document.getElementById("hotfixAdditionalCriterionFormula");var pw=p?Number(p.value):NaN,aw=w?Number(w.value):NaN;if(!n||!n.value.trim()||!f||!f.value.trim()){alert("Debe identificar el criterio adicional y su regla objetiva de valoración.");return;}if(!Number.isFinite(pw)||!Number.isFinite(aw)||pw<=0||aw<=0||pw+aw!==100){alert("Los pesos deben ser positivos y sumar 100 puntos.");return;}a.supplyAwardCriteriaStructure=[{id:"PRICE",label:"Precio",weight:pw,formulaRequired:true},{id:"USER_OBJECTIVE_CRITERION",label:n.value.trim(),weight:aw,formulaRequired:true,formulaDescription:f.value.trim()}];a.supplyAwardCriteriaStructureValidated=true;a.supplyAwardCriteriaLegalReviewValidated=true;a.supplyAwardCriteriaLegalReviewStatus="MULTIPLE_FORMULA_USER_DEFINED_PENDING_FINAL_LEGAL_CHECK";a.supplyDocumentGenerationBlockedByAwardCriteria=false;a.supplyDocumentMappingValidated=false;a.supplyDocumentMappingStatus="READY_FOR_REVALIDATION_AFTER_CRITERIA_CHANGE";saveAnswers(a,"supply-multiple-criteria-defined-hotfix");location.reload();}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(render,0);});
var observer=new MutationObserver(function(){setTimeout(render,0);});observer.observe(work,{childList:true,subtree:true});setTimeout(render,0);
})();`;
