export const SUPPLY_LEGAL_CLOSURE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-legal-closure"}}));}
function parsePercent(v){var s=String(v||"").trim().replace("%","").replace(",",".");if(!s)return NaN;return Number(s);}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function closureReady(a){var budget=Number(a.supplyMaximumApprovedBudgetExVat||0)>0;var mod=a.supplyNeedsModificationForeseen===false||(a.supplyNeedsModificationForeseen===true&&Number(a.supplyNeedsModificationMaximumIncreasePercent||0)>=0&&Number(a.supplyNeedsModificationMaximumIncreasePercent||0)<=20&&a.supplyNeedsModificationValidated===true);var ve=Number(a.supplyEstimatedValueExVat||0)>0&&a.supplyEstimatedValueValidated===true;var price=a.supplyAwardCriteriaMode!=="PRICE_ONLY"||a.supplyPriceOnlyMotivationValidated===true;return budget&&mod&&ve&&price;}
function render(){var map=document.getElementById("supplyDocumentMappingCard");if(!map)return;var old=document.getElementById("supplyLegalClosureCard");if(old)old.remove();var a=readAnswers();var budget=Number(a.supplyMaximumApprovedBudgetExVat||0);var modKnown=a.supplyNeedsModificationForeseen===true||a.supplyNeedsModificationForeseen===false;var modPercent=Number(a.supplyNeedsModificationMaximumIncreasePercent||0);var modIncrease=budget*modPercent/100;var ve=budget+(a.supplyNeedsModificationForeseen===true?modIncrease:0);var priceOnly=a.supplyAwardCriteriaMode==="PRICE_ONLY";var html='<div id="supplyLegalClosureCard" class="card" style="margin-top:12px"><h4>5.1 Cierre jurídico-económico previo a la validación del mapeo</h4>';
if(budget>0)html+='<div class="info"><strong>Presupuesto máximo registrado:</strong> '+money(budget)+' sin IVA para toda la vigencia.</div>';else html+='<div class="warning"><strong>Falta el presupuesto máximo aprobado para toda la vigencia.</strong></div>';
if(budget>0&&!modKnown)html+='<div class="warning"><strong>Modificación por mayores necesidades.</strong><p>La disposición adicional 33.ª LCSP exige que, si se quiere atender un incremento de necesidades reales, la posibilidad de modificación esté prevista en la documentación de la licitación en los términos del artículo 204 LCSP.</p><p>¿Se prevé expresamente esta modificación al alza, manteniendo el mismo objeto y los precios unitarios previstos?</p><select id="supplyNeedsModificationForeseen"><option value="">Seleccione</option><option value="true">Sí</option><option value="false">No</option></select><button id="saveSupplyNeedsModificationDecision" type="button">Guardar decisión</button></div>';
if(a.supplyNeedsModificationForeseen===true&&a.supplyNeedsModificationValidated!==true)html+='<div class="warning"><strong>Porcentaje máximo de la modificación prevista.</strong><p><strong>Límite legal: 20 % del precio inicial del contrato.</strong> El artículo 204.1 LCSP permite prever modificaciones durante la vigencia hasta un máximo del 20 %, siempre que la cláusula esté formulada de forma clara, precisa e inequívoca y detalle alcance, límites, condiciones y procedimiento. El artículo 204.1 también impide introducir nuevos precios unitarios no previstos. La DA 33.ª remite expresamente a este régimen para los suministros y servicios en función de las necesidades.</p><label><strong>Porcentaje máximo previsto</strong></label><input id="supplyNeedsModificationMaximumIncreasePercent" type="number" min="0" max="20" step="0.01" inputmode="decimal" placeholder="Ej.: 20"><span> %</span><div class="muted">Con el presupuesto registrado, el 20 % equivaldría a '+money(budget*0.20)+'.</div><button id="saveSupplyNeedsModificationMaximumIncrease" type="button">Guardar porcentaje</button></div>';
if(a.supplyNeedsModificationForeseen===false&&a.supplyNeedsModificationValidated!==true)html+='<button id="validateNoSupplyNeedsModification" type="button">Confirmar que no se prevé modificación al alza</button>';
if(a.supplyNeedsModificationForeseen===true&&a.supplyNeedsModificationValidated===true)html+='<div class="info"><strong>Modificación prevista:</strong> '+modPercent.toLocaleString("es-ES",{maximumFractionDigits:2})+' % del precio inicial, equivalente actualmente a '+money(modIncrease)+' sin IVA.</div>';
if(budget>0&&a.supplyNeedsModificationValidated===true){html+='<div class="info"><strong>Valor estimado propuesto:</strong> '+money(ve)+' sin IVA. Integra el presupuesto máximo y, cuando existe modificación prevista al alza, el importe máximo correspondiente al porcentaje validado. Se mantiene separado de la proyección de consumo.</div>';if(a.supplyEstimatedValueValidated!==true)html+='<button id="validateSupplyEstimatedValue" type="button">Validar valor estimado propuesto</button>';else html+='<div class="info"><strong>Valor estimado validado:</strong> '+money(a.supplyEstimatedValueExVat)+' sin IVA.</div>';}
if(priceOnly&&a.supplyPriceOnlyMotivationValidated!==true)html+='<div class="warning"><strong>Precio como criterio único.</strong><p>Confirme que en este expediente concurren las circunstancias ya motivadas: artículos perfectamente definidos, calidad mínima cerrada, plazo de entrega uniforme y compatibilidad con el régimen de modificaciones.</p><button id="validateSupplyPriceOnlyMotivation" type="button">Validar motivación específica</button><button id="rejectSupplyPriceOnlyMotivation" type="button" class="secondary">Revisar criterios</button></div>';
if(priceOnly&&a.supplyPriceOnlyMotivationValidated===true)html+='<div class="info"><strong>Motivación específica del precio único validada.</strong></div>';
html+=closureReady(a)?'<div class="info"><strong>Cierre completado.</strong> Ya puede validar el mapeo documental.</div>':'<div class="warning"><strong>Mapeo todavía bloqueado.</strong> Complete los controles anteriores.</div>';
html+='</div>';var toolbar=Array.from(map.querySelectorAll('.toolbar')).find(function(x){return x.querySelector('#validateSupplyDocumentMapping');});if(toolbar)toolbar.insertAdjacentHTML('beforebegin',html);else map.insertAdjacentHTML('beforeend',html);var btn=document.getElementById('validateSupplyDocumentMapping');if(btn){btn.disabled=!closureReady(a);btn.style.opacity=closureReady(a)?'1':'0.55';btn.title=closureReady(a)?'':'Debe cerrar valor estimado y, en su caso, motivación del precio único.';}}
work.addEventListener('click',function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();if(t.id==='saveSupplyNeedsModificationDecision'){var el=document.getElementById('supplyNeedsModificationForeseen');if(!el||!el.value){alert('Seleccione una opción.');return;}a.supplyNeedsModificationForeseen=el.value==='true';a.supplyNeedsModificationValidated=false;a.supplyEstimatedValueValidated=false;delete a.supplyNeedsModificationMaximumIncreaseExVat;if(!a.supplyNeedsModificationForeseen)delete a.supplyNeedsModificationMaximumIncreasePercent;saveAnswers(a,'supply-modification-decision');render();}
if(t.id==='saveSupplyNeedsModificationMaximumIncrease'){var el2=document.getElementById('supplyNeedsModificationMaximumIncreasePercent'),pct=parsePercent(el2?el2.value:'');if(!Number.isFinite(pct)||pct<0||pct>20){alert('Indique un porcentaje válido entre 0 % y 20 %, conforme al artículo 204.1 LCSP.');return;}a.supplyNeedsModificationMaximumIncreasePercent=Number(pct.toFixed(2));a.supplyNeedsModificationMaximumIncreaseExVat=Number((Number(a.supplyMaximumApprovedBudgetExVat||0)*pct/100).toFixed(2));a.supplyNeedsModificationValidated=true;a.supplyEstimatedValueValidated=false;saveAnswers(a,'supply-modification-maximum-percent');render();}
if(t.id==='validateNoSupplyNeedsModification'){a.supplyNeedsModificationValidated=true;a.supplyNeedsModificationMaximumIncreasePercent=0;a.supplyNeedsModificationMaximumIncreaseExVat=0;a.supplyEstimatedValueValidated=false;saveAnswers(a,'supply-no-modification');render();}
if(t.id==='validateSupplyEstimatedValue'){var b=Number(a.supplyMaximumApprovedBudgetExVat||0),pct=Number(a.supplyNeedsModificationMaximumIncreasePercent||0),m=a.supplyNeedsModificationForeseen===true?b*pct/100:0;if(!(b>0)||!a.supplyNeedsModificationValidated){alert('Faltan datos para cerrar el valor estimado.');return;}a.supplyEstimatedValueExVat=Number((b+m).toFixed(2));a.supplyEstimatedValueValidated=true;a.supplyEstimatedValueStatus='VALIDATED_ART_101';saveAnswers(a,'supply-estimated-value');render();}
if(t.id==='validateSupplyPriceOnlyMotivation'){a.supplyPriceOnlyMotivationValidated=true;a.supplyPriceOnlyMotivationStatus='CASE_SPECIFIC_VALIDATED_REQUIRES_FINAL_LEGAL_CHECK';saveAnswers(a,'supply-price-only-motivation');render();}
if(t.id==='rejectSupplyPriceOnlyMotivation'){a.supplyAwardCriteriaMode='MULTIPLE_FORMULA';a.supplyPriceOnlyMotivationValidated=false;a.supplyDocumentMappingValidated=false;saveAnswers(a,'supply-price-only-rejected');location.reload();}},true);
work.addEventListener('click',function(event){var t=event.target;if(!t||t.id!=='validateSupplyDocumentMapping')return;var a=readAnswers();if(!closureReady(a)){event.preventDefault();event.stopImmediatePropagation();alert('Antes de validar el mapeo debe cerrar el valor estimado y, en su caso, la motivación del precio único.');}},true);
document.addEventListener('contrata-ia:adaptive-saved',function(){setTimeout(render,0);});
render();
})();`;
