export const SUPPLY_ECONOMIC_PERIOD_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");
if(!work)return;
var answersKey="contrataIaAdaptiveAnswers",catalogueKey="contrataIaSupplyCatalogue";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function readCatalogue(){var c=readJson(sessionStorage,catalogueKey);if(Array.isArray(c.items)&&c.items.length)return c;c=readJson(localStorage,catalogueKey);if(Array.isArray(c.items)&&c.items.length){sessionStorage.setItem(catalogueKey,JSON.stringify(c));return c;}return {};}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-economic-period"}}));}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function legacyHide(){var summary=document.getElementById("supplyCatalogueSummary");if(!summary)return;Array.from(summary.querySelectorAll(".info,.warning")).forEach(function(x){var t=x.textContent||"";if(t.includes("Presupuesto conciliado")||t.includes("Debe conciliarse el presupuesto")||t.includes("Diferencia presupuestaria justificada"))x.style.display="none";});Array.from(summary.querySelectorAll(".card")).forEach(function(x){if((x.textContent||"").includes("1. Criterios de adjudicación"))x.style.display="none";});}
function projection(a,c){var base=Number(c.total||0),ref=Number(a.supplyCatalogueReferenceMonths||0),initial=Number(a.initialDurationMonths||0),ext=Array.isArray(a.extensionMonths)?a.extensionMonths.map(Number):[];if(!(base>0&&ref>0&&initial>0))return null;var initialValue=base*initial/ref;var extensionValues=ext.map(function(m){return base*m/ref;});return {base:base,ref:ref,initialMonths:initial,initialValue:initialValue,extensionMonths:ext,extensionValues:extensionValues,estimatedValue:initialValue+extensionValues.reduce(function(s,v){return s+v;},0)};}
function specificClauses(a){var html='<div style="margin-top:14px"><h3>2. Condiciones específicas del suministro</h3>';if(a.supplyDeliveryDeadlineDays===undefined)return html+'<p>¿Cuál es el plazo máximo ordinario de entrega desde cada pedido?</p><input id="econSupplyDeliveryDeadlineDays" type="number" min="1" step="1" inputmode="numeric" placeholder="Días naturales"><button id="econSaveDeliveryDeadline" type="button">Guardar y continuar</button></div>';if(a.supplyDeliveryPlacesDefined===undefined)return html+'<p>¿Están ya definidos los lugares o centros de entrega?</p><select id="econSupplyDeliveryPlacesDefined"><option value="">Seleccione</option><option value="true">Sí</option><option value="false">No, deben concretarse</option></select><button id="econSaveDeliveryPlaces" type="button">Guardar y continuar</button></div>';if(a.supplyReplacementRequired===undefined)return html+'<p>¿Debe exigirse sustitución de artículos defectuosos o no conformes sin coste adicional?</p><select id="econSupplyReplacementRequired"><option value="">Seleccione</option><option value="true">Sí</option><option value="false">No</option></select><button id="econSaveReplacement" type="button">Guardar y continuar</button></div>';return html+'<div class="info"><strong>Rama de suministro avanzada.</strong> Ya están definidos catálogo, horizonte temporal, presupuesto, criterios, plazo de entrega y régimen básico de conformidad.</div></div>';}
function continuation(a){var html='<div class="card" style="margin-top:14px"><h3>1. Criterios de adjudicación</h3>';if(!a.supplyAwardCriteriaMode){html+='<p>Seleccione la estructura inicial de criterios. Para un abierto simplificado abreviado, todos deben ser cuantificables mediante fórmulas.</p><select id="econSupplyCriteriaMode"><option value="">Seleccione</option><option value="PRICE_ONLY">Solo precio</option><option value="MULTIPLE_FORMULA">Varios criterios objetivos cuantificables mediante fórmula</option></select><button id="econSaveSupplyCriteriaMode" type="button">Guardar y continuar</button>';}else{html+='<div class="info"><strong>Configuración seleccionada:</strong> '+(a.supplyAwardCriteriaMode==="PRICE_ONLY"?'solo precio':'varios criterios objetivos mediante fórmula')+'.</div>';if(a.supplySpecificClausesStarted!==true)html+='<button id="econContinueSupplyClauses" type="button">Continuar con condiciones del suministro</button>';else html+=specificClauses(a);}return html+'</div>';}
function card(){var a=readAnswers(),c=readCatalogue();if(!Array.isArray(c.items)||!c.items.length)return '';var html='<div id="supplyEconomicPeriodCard" class="card"><h3>Horizonte temporal de la relación de artículos</h3>';if(!a.supplyCatalogueReferenceMonths){html+='<div class="warning"><strong>La suma de la tabla no puede compararse todavía con el presupuesto del contrato.</strong><p>Indique qué período representan las cantidades estimadas de la hoja importada.</p></div><select id="supplyCataloguePeriodChoice"><option value="">Seleccione</option><option value="1">Un mes</option><option value="12">Doce meses / un año</option><option value="INITIAL">Todo el período inicial del contrato</option><option value="OTHER">Otro período</option></select><div id="supplyCatalogueOtherPeriod"></div><button id="saveSupplyCataloguePeriod" type="button">Calcular proyección</button></div>';return html;}
var p=projection(a,c);if(!p){html+='<div class="warning">No se puede calcular la proyección porque falta la duración inicial o el período de referencia de la tabla.</div></div>';return html;}
html+='<div class="info"><strong>Base de consumo validable:</strong> la tabla representa '+p.ref+' meses y suma <strong>'+money(p.base)+'</strong>.</div><h4>Proyección económica propuesta</h4><ul><li>Periodo inicial ('+p.initialMonths+' meses): <strong>'+money(p.initialValue)+'</strong></li>'+p.extensionMonths.map(function(m,i){return '<li>Prórroga '+(i+1)+' ('+m+' meses): <strong>'+money(p.extensionValues[i])+'</strong></li>';}).join("")+'<li>Valor estimado provisional: <strong>'+money(p.estimatedValue)+'</strong></li></ul>';
if(a.supplyCataloguePeriodValidated!==true){html+='<p class="muted">La proyección se obtiene trasladando la misma base de consumo al número de meses de cada período. Valídela solo si esa hipótesis responde a la necesidad prevista; si una prórroga tendrá un importe distinto, podrá corregirse posteriormente.</p><div class="toolbar"><button id="validateSupplyCatalogueProjection" type="button">Validar esta proyección</button><button id="changeSupplyCataloguePeriod" type="button" class="secondary">Cambiar período de referencia</button></div></div>';return html;}
html+='<div class="info"><strong>Proyección temporal validada.</strong> El presupuesto inicial y los importes de prórroga se han actualizado con esta base temporal.</div>'+continuation(a)+'</div>';return html;}
function ensure(){legacyHide();var c=readCatalogue();var old=document.getElementById("supplyEconomicPeriodCard");if(!Array.isArray(c.items)||!c.items.length){if(old)old.remove();return;}if(old)return;var cat=document.getElementById("supplyCatalogueCard");if(cat)cat.insertAdjacentHTML("afterend",card());else work.insertAdjacentHTML("beforeend",card());}
function rerender(){var old=document.getElementById("supplyEconomicPeriodCard");if(old)old.remove();ensure();}
work.addEventListener("change",function(event){var t=event.target;if(!t||t.id!=="supplyCataloguePeriodChoice")return;var box=document.getElementById("supplyCatalogueOtherPeriod");if(box)box.innerHTML=t.value==="OTHER"?'<input id="supplyCatalogueCustomMonths" type="number" min="1" step="1" placeholder="Número de meses que representa la tabla">':'';});
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers(),c=readCatalogue();if(t.id==="saveSupplyCataloguePeriod"){var sel=document.getElementById("supplyCataloguePeriodChoice"),v=sel?sel.value:"";if(!v){alert("Seleccione el período que representan las cantidades de la tabla.");return;}var months;if(v==="INITIAL")months=Number(a.initialDurationMonths||0);else if(v==="OTHER"){var custom=document.getElementById("supplyCatalogueCustomMonths");months=custom?Number(custom.value):NaN;}else months=Number(v);if(!Number.isInteger(months)||months<=0){alert("Indique un período válido en meses.");return;}a.supplyCatalogueReferenceMonths=months;a.supplyCataloguePeriodValidated=false;saveAnswers(a,"supply-catalogue-period");rerender();}
if(t.id==="changeSupplyCataloguePeriod"){delete a.supplyCatalogueReferenceMonths;delete a.supplyCataloguePeriodValidated;saveAnswers(a,"supply-catalogue-period-change");rerender();}
if(t.id==="validateSupplyCatalogueProjection"){var p=projection(a,c);if(!p)return;a.initialBudgetExVat=Number(p.initialValue.toFixed(2));a.supplyExtensionBudgetsExVat=p.extensionValues.map(function(v){return Number(v.toFixed(2));});a.supplyCataloguePeriodValidated=true;a.supplyCatalogueProjectedInitialBudgetExVat=a.initialBudgetExVat;a.supplyCatalogueProjectedEstimatedValueExVat=Number(p.estimatedValue.toFixed(2));delete a.supplyBudgetDifferenceJustified;delete a.supplyBudgetDifferenceReason;saveAnswers(a,"supply-catalogue-projection-validated");location.reload();}
if(t.id==="econSaveSupplyCriteriaMode"){var mode=document.getElementById("econSupplyCriteriaMode");if(!mode||!mode.value){alert("Seleccione una opción.");return;}a.supplyAwardCriteriaMode=mode.value;saveAnswers(a,"supply-criteria");rerender();}
if(t.id==="econContinueSupplyClauses"){a.supplySpecificClausesStarted=true;saveAnswers(a,"supply-specific-clauses");rerender();}
if(t.id==="econSaveDeliveryDeadline"){var el=document.getElementById("econSupplyDeliveryDeadlineDays"),n=el?Number(el.value):NaN;if(!Number.isInteger(n)||n<=0){alert("Indique un número válido de días.");return;}a.supplyDeliveryDeadlineDays=n;saveAnswers(a,"supply-delivery-deadline");rerender();}
if(t.id==="econSaveDeliveryPlaces"){var el2=document.getElementById("econSupplyDeliveryPlacesDefined");if(!el2||!el2.value){alert("Seleccione una opción.");return;}a.supplyDeliveryPlacesDefined=el2.value==="true";saveAnswers(a,"supply-delivery-places");rerender();}
if(t.id==="econSaveReplacement"){var el3=document.getElementById("econSupplyReplacementRequired");if(!el3||!el3.value){alert("Seleccione una opción.");return;}a.supplyReplacementRequired=el3.value==="true";saveAnswers(a,"supply-replacement");rerender();}
});
document.addEventListener("contrata-ia:catalogue-saved",function(){setTimeout(rerender,0);});
var observer=new MutationObserver(function(){legacyHide();ensure();});observer.observe(work,{childList:true,subtree:true});ensure();
})();`;
