export const SUPPLY_PBL_BREAKDOWN_PROPOSAL_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-pbl-breakdown-proposal"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
var PROPOSAL="Coste directo de adquisición/suministro: 10.552,44 € sin IVA, determinado por la suma de las cantidades estimadas de las referencias durante la duración inicial multiplicadas por sus precios unitarios de licitación. Los costes de transporte, distribución, entrega, estructura empresarial, margen y demás gastos inherentes a la ejecución se consideran integrados en los precios unitarios cuando no han sido objeto de cuantificación separada por la Administración; no se adicionan importes distintos al PBL ya calculado.";
var LEGAL="Fundamento: artículo 100.2 LCSP, que exige adecuación a mercado y desglose de costes directos, indirectos y otros eventuales gastos; y doctrina administrativa sobre suministros a precios unitarios, que exige justificar la formación de dichos precios y, cuando proceda, explicar la integración en ellos de transporte, distribución o entrega.";
function eligible(a){var b=Array.isArray(a.supplyAnnexIComprehensiveAuditBlockers)?a.supplyAnnexIComprehensiveAuditBlockers:[];return a.supplyAnnexIFinalAuditValidated===true&&(b.some(function(x){return String(x).indexOf("2.A. Desglose del PBL")>=0;})||a.supplyPblBreakdownProposalValidated===true);}
function card(){var a=readAnswers();if(!eligible(a))return "";var html='<div id="supplyPblBreakdownProposalCard" class="card" style="margin-top:14px"><h3>11.2.3 Cierre técnico-económico del desglose del PBL</h3><div class="info"><strong>Propuesta motivada, no decisión automática.</strong> Para este suministro por precios unitarios se propone cerrar el apartado 2.A sin inventar porcentajes de costes indirectos.</div><div class="warning"><strong>Redacción propuesta:</strong><p>'+esc(PROPOSAL)+'</p><p><strong>'+esc(LEGAL)+'</strong></p></div>';
if(a.supplyPblBreakdownProposalValidated===true){html+='<div class="info"><strong>Propuesta validada por la persona usuaria.</strong> Queda preparada para su inserción en las dos líneas de desglose del apartado 2.A y para volver a ejecutar la auditoría integral.</div>';}else{html+='<button id="validateSupplyPblBreakdownProposal" type="button">Validar propuesta de desglose PBL</button><button id="rejectSupplyPblBreakdownProposal" type="button" class="secondary">Necesito otro desglose</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyPblBreakdownProposalCard");if(old)old.remove();var anchor=document.getElementById("supplyAnnexIComprehensiveAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="validateSupplyPblBreakdownProposal"){var a=readAnswers();a.supplyPblBreakdownProposalValidated=true;a.supplyPblBreakdownProposalText=PROPOSAL;a.supplyPblBreakdownProposalLegalBasis="art. 100.2 LCSP + doctrina administrativa sobre suministros a precios unitarios";a.supplyPblBreakdownProposalValidatedAt=new Date().toISOString();save(a);ensure();}if(e.target.id==="rejectSupplyPblBreakdownProposal"){var a2=readAnswers();a2.supplyPblBreakdownProposalValidated=false;a2.supplyPblBreakdownProposalRejected=true;save(a2);alert("La propuesta no se ha validado. El desglose PBL seguirá bloqueado hasta que se defina una alternativa técnicamente motivada.");ensure();}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;
