export const SUPPLY_CATALOGUE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");
if(!work)return;
var storageKey="contrataIaSupplyCatalogue";
var answersKey="contrataIaAdaptiveAnswers";
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("es-ES").replace(/[^a-z0-9]+/g," ").trim();}
function parseNumber(v){var s=String(v||"").trim().split(" ").join("").replaceAll("€","");if(!s)return NaN;var c=s.lastIndexOf(","),d=s.lastIndexOf(".");if(c>=0&&d>=0){if(c>d)s=s.replaceAll(".","").replace(",",".");else s=s.replaceAll(",","");}else if(c>=0)s=s.replace(",",".");else if(d>=0){var p=s.split(".");if(p.length>2||((p[p.length-1]||"").length===3&&p.length===2))s=p.join("");}return Number(s);}
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply"}}));}
function readCatalogue(){var c=readJson(sessionStorage,storageKey);if(Array.isArray(c.items)&&c.items.length)return c;c=readJson(localStorage,storageKey);if(Array.isArray(c.items)&&c.items.length){sessionStorage.setItem(storageKey,JSON.stringify(c));return c;}return {};}
function saveCatalogue(c){var raw=JSON.stringify(c);sessionStorage.setItem(storageKey,raw);localStorage.setItem(storageKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:catalogue-saved"));document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-catalogue"}}));}
function splitLine(line){var out=[],cur="",quoted=false;for(var i=0;i<line.length;i++){var ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(ch===';'&&!quoted){out.push(cur);cur="";}else cur+=ch;}out.push(cur);return out;}
function templateText(withSuggestions){var nl=String.fromCharCode(10);var rows=["Referencia;Denominación;Descripción técnica mínima;Unidad;Cantidad estimada;Precio unitario estimado sin IVA;Lote;CPV"];if(withSuggestions){rows.push(";Tornillería y elementos de fijación;;unidad;;;;");rows.push(";Cerrajería y herrajes;;unidad;;;;");rows.push(";Adhesivos y selladores;;unidad;;;;");rows.push(";Herramientas manuales;;unidad;;;;");rows.push(";Consumibles y pequeños repuestos;;unidad;;;;");}else rows.push("ART-001;;;;;;;");return "\\uFEFF"+rows.join(nl);}
function download(text,name){var blob=new Blob([text],{type:"text/csv;charset=utf-8"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
function catalogueCard(){return '<div id="supplyCatalogueCard" class="card"><h2>Rama específica · suministro</h2><h3>Relación de artículos del suministro</h3><p>Puede importar una relación preparada en Excel/LibreOffice. Se admiten CSV y ODS. Cada lote se muestra y calcula de forma independiente.</p><div class="toolbar"><button id="downloadSupplyTemplate" type="button">Descargar plantilla para Excel</button><button id="suggestSupplyCategories" type="button" class="secondary">Proponer categorías orientativas</button></div><p class="muted">La propuesta automática solo sirve como ayuda inicial. La unidad promotora debe validar los artículos, cantidades, especificaciones y asignación a lotes que responden a su necesidad real.</p><label><strong>Importar relación cumplimentada</strong></label><input id="supplyFile" type="file" accept=".csv,.ods,text/csv,application/vnd.oasis.opendocument.spreadsheet"><div id="supplyCatalogueSummary"></div></div>';}
function groupItems(data){var groups={};var named=(data.lots||[]).length>0;(data.items||[]).forEach(function(item){var key=String(item.lote||"").trim();if(!key)key=named?"Sin lote asignado":"Lote 1 — lote único";(groups[key]||(groups[key]=[])).push(item);});return groups;}
function itemAmount(item){var q=parseNumber(item.cantidad),p=parseNumber(item.precio);return Number.isFinite(q)&&q>0&&Number.isFinite(p)&&p>=0?q*p:0;}
function lotTable(name,items){var subtotal=items.reduce(function(sum,item){return sum+itemAmount(item);},0);return '<div class="card" style="margin-top:12px"><h3>'+esc(name)+'</h3><p><strong>'+items.length+' artículos</strong> · Importe estimado: <strong>'+subtotal.toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' €</strong></p><details><summary>Ver primeras referencias del lote</summary><table style="width:100%;border-collapse:collapse"><thead><tr><th>Ref.</th><th>Denominación</th><th>Cantidad</th><th>Precio</th></tr></thead><tbody>'+items.slice(0,10).map(function(x){return '<tr><td>'+esc(x.referencia)+'</td><td>'+esc(x.denominacion)+'</td><td>'+esc(x.cantidad)+'</td><td>'+esc(x.precio)+'</td></tr>';}).join("")+'</tbody></table></details></div>';}
function reconciliation(data){var a=readAnswers(),budget=Number(a.initialBudgetExVat),total=Number(data.total||0);if(!Number.isFinite(budget)||!Number.isFinite(total)||total<=0)return '';var diff=Math.abs(budget-total),tol=Math.max(1,total*0.01);if(diff<=tol)return '<div class="info" style="margin-top:12px"><strong>Presupuesto conciliado.</strong> La relación de artículos y el presupuesto inicial son coherentes.</div>';if(a.supplyBudgetDifferenceJustified===true)return '<div class="info" style="margin-top:12px"><strong>Diferencia presupuestaria justificada.</strong><br>'+esc(a.supplyBudgetDifferenceReason||"La unidad promotora ha decidido mantener el presupuesto declarado.")+'</div>';return '<div class="warning" style="margin-top:12px"><strong>Debe conciliarse el presupuesto antes de continuar.</strong><br>Presupuesto declarado: <strong>'+budget.toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' €</strong><br>Suma de la relación importada: <strong>'+total.toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' €</strong><p>Si la tabla recoge toda la necesidad del periodo inicial, utilice su importe. Si el presupuesto declarado incluye otros conceptos, manténgalo justificando la diferencia.</p><div class="toolbar"><button id="useCatalogueBudget" type="button">Usar importe de la tabla</button><button id="showBudgetReason" type="button" class="secondary">Mantener presupuesto declarado</button></div><div id="budgetReasonBox"></div></div>';}
function specificClauses(a){var html='<div style="margin-top:14px"><h3>2. Condiciones específicas del suministro</h3>';if(a.supplyDeliveryDeadlineDays===undefined)return html+'<p>¿Cuál es el plazo máximo ordinario de entrega desde cada pedido?</p><input id="supplyDeliveryDeadlineDays" type="number" min="1" step="1" inputmode="numeric" placeholder="Días naturales"><button id="saveDeliveryDeadline" type="button">Guardar y continuar</button></div>';if(a.supplyDeliveryPlacesDefined===undefined)return html+'<p>¿Están ya definidos los lugares o centros de entrega?</p><select id="supplyDeliveryPlacesDefined"><option value="">Seleccione</option><option value="true">Sí</option><option value="false">No, deben concretarse</option></select><button id="saveDeliveryPlaces" type="button">Guardar y continuar</button></div>';if(a.supplyReplacementRequired===undefined)return html+'<p>¿Debe exigirse sustitución de artículos defectuosos o no conformes sin coste adicional?</p><select id="supplyReplacementRequired"><option value="">Seleccione</option><option value="true">Sí</option><option value="false">No</option></select><button id="saveReplacement" type="button">Guardar y continuar</button></div>';return html+'<div class="info"><strong>Rama de suministro avanzada.</strong> Ya están definidos catálogo, presupuesto, criterios, plazo de entrega y régimen básico de conformidad. El siguiente bloque será solvencia, garantías y condiciones especiales antes de generar los pliegos.</div></div>';}
function criteria(data){var a=readAnswers(),budget=Number(a.initialBudgetExVat),total=Number(data.total||0);if(!Number.isFinite(budget)||!Number.isFinite(total)||total<=0)return '';var coherent=Math.abs(budget-total)<=Math.max(1,total*0.01)||a.supplyBudgetDifferenceJustified===true;if(!coherent)return '';var mode=a.supplyAwardCriteriaMode||"";var html='<div class="card" style="margin-top:14px"><h3>1. Criterios de adjudicación</h3>';if(!mode){html+='<p>Seleccione la estructura inicial de criterios. Para un abierto simplificado abreviado, todos deben ser cuantificables mediante fórmulas.</p><select id="supplyCriteriaMode"><option value="">Seleccione</option><option value="PRICE_ONLY">Solo precio</option><option value="MULTIPLE_FORMULA">Varios criterios objetivos cuantificables mediante fórmula</option></select><button id="saveSupplyCriteriaMode" type="button">Guardar y continuar</button>';}else{html+='<div class="info"><strong>Configuración seleccionada:</strong> '+(mode==="PRICE_ONLY"?'solo precio':'varios criterios objetivos mediante fórmula')+'.</div>';if(a.supplySpecificClausesStarted!==true)html+='<button id="continueSupplyClauses" type="button">Continuar con condiciones del suministro</button>';else html+=specificClauses(a);}return html+'</div>';}
function renderSummary(data){var box=document.getElementById("supplyCatalogueSummary");if(!box)return;if(!data||!Array.isArray(data.items)||data.items.length===0){box.innerHTML='<p class="muted">Todavía no se ha importado ninguna relación de artículos.</p>';return;}var issues=data.issues||[],groups=groupItems(data);var html='<div class="info"><strong>'+data.items.length+' artículos importados</strong><br>Importe estimado total: <strong>'+Number(data.total||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+' €</strong><br>'+(issues.length?issues.length+' incidencias requieren revisión.':'Sin incidencias básicas detectadas.')+((data.lots||[]).length?'<br>Lotes identificados: '+esc(data.lots.join(", ")):'<br>Configuración actual: lote único')+(data.sourceFormat?'<br>Formato leído: '+esc(data.sourceFormat):'')+'</div>';if(issues.length)html+='<ul>'+issues.slice(0,12).map(function(x){return '<li>'+esc(x)+'</li>';}).join("")+'</ul>';Object.keys(groups).forEach(function(name){html+=lotTable(name,groups[name]);});html+=reconciliation(data);html+=criteria(data);box.innerHTML=html;}
function validateItems(items,sourceFormat){var issues=[],refs={},lots={},total=0,blankLot=false;items.forEach(function(item,index){var row=index+2;if(!item.denominacion)issues.push("Fila "+row+": falta la denominación del artículo.");var q=parseNumber(item.cantidad),p=parseNumber(item.precio);if(!Number.isFinite(q)||q<=0)issues.push("Fila "+row+": cantidad estimada no válida.");if(!Number.isFinite(p)||p<0)issues.push("Fila "+row+": precio unitario no válido.");if(Number.isFinite(q)&&q>0&&Number.isFinite(p)&&p>=0)total+=q*p;if(item.referencia){var key=item.referencia.toLocaleLowerCase("es-ES");if(refs[key])issues.push("Fila "+row+": referencia duplicada "+item.referencia+".");refs[key]=true;}if(item.lote)lots[item.lote]=true;else blankLot=true;});var lotNames=Object.keys(lots);if(lotNames.length&&blankLot)issues.push("Hay artículos sin lote asignado. En un expediente con varios lotes cada artículo debe pertenecer a un lote concreto.");return {items:items,issues:issues,total:total,lots:lotNames,sourceFormat:sourceFormat,importedAt:new Date().toISOString()};}
function parseCsv(text){var nl=String.fromCharCode(10),lines=String(text||"").replaceAll(String.fromCharCode(13),"").split(nl).filter(function(x){return x.trim();});if(lines.length<2)throw new Error("La tabla no contiene artículos.");var items=[];for(var i=1;i<lines.length;i++){var c=splitLine(lines[i]);while(c.length<8)c.push("");var item={referencia:(c[0]||"").trim(),denominacion:(c[1]||"").trim(),descripcion:(c[2]||"").trim(),unidad:(c[3]||"").trim(),cantidad:(c[4]||"").trim(),precio:(c[5]||"").trim(),lote:(c[6]||"").trim(),cpv:(c[7]||"").trim()};if(!item.referencia&&!item.denominacion&&!item.cantidad&&!item.precio)continue;items.push(item);}return validateItems(items,"CSV");}
function u16(d,o){return d[o]|(d[o+1]<<8);}function u32(d,o){return (d[o]|(d[o+1]<<8)|(d[o+2]<<16)|(d[o+3]<<24))>>>0;}
async function inflateRaw(bytes){if(typeof DecompressionStream!=="function")throw new Error("Este navegador no permite abrir ODS directamente. Guarde temporalmente la hoja como CSV UTF-8.");var ds=new DecompressionStream("deflate-raw"),ab=await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer();return new Uint8Array(ab);}
async function odsContentXml(file){var d=new Uint8Array(await file.arrayBuffer());if(d.length<22||d[0]!==80||d[1]!==75)throw new Error("El archivo ODS no tiene una estructura válida.");var e=-1;for(var i=d.length-22;i>=Math.max(0,d.length-65557);i--){if(u32(d,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("No se pudo localizar el índice interno del ODS.");var count=u16(d,e+10),off=u32(d,e+16),p=off;for(var n=0;n<count;n++){if(u32(d,p)!==0x02014b50)break;var method=u16(d,p+10),cs=u32(d,p+20),fn=u16(d,p+28),ex=u16(d,p+30),co=u16(d,p+32),lo=u32(d,p+42),name=new TextDecoder().decode(d.slice(p+46,p+46+fn));if(name==="content.xml"){var lfn=u16(d,lo+26),lex=u16(d,lo+28),start=lo+30+lfn+lex,comp=d.slice(start,start+cs),raw=method===0?comp:method===8?await inflateRaw(comp):null;if(!raw)throw new Error("Compresión ODS no soportada.");return new TextDecoder("utf-8").decode(raw);}p+=46+fn+ex+co;}throw new Error("El ODS no contiene content.xml.");}
function cellText(cell){var ps=cell.getElementsByTagNameNS("urn:oasis:names:tc:opendocument:xmlns:text:1.0","p"),out=[];for(var i=0;i<ps.length;i++)out.push(ps[i].textContent||"");return out.join(" ").trim();}
function parseOdsXml(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se pudo interpretar el contenido XML del ODS.");var ns="urn:oasis:names:tc:opendocument:xmlns:table:1.0",rows=doc.getElementsByTagNameNS(ns,"table-row"),matrix=[];for(var r=0;r<rows.length;r++){var cells=rows[r].getElementsByTagNameNS(ns,"table-cell"),vals=[];for(var c=0;c<cells.length;c++){var rep=Number(cells[c].getAttributeNS(ns,"number-columns-repeated")||"1"),txt=cellText(cells[c]);for(var k=0;k<Math.min(rep,40);k++)vals.push(txt);}while(vals.length&&vals[vals.length-1]==="")vals.pop();if(vals.some(function(x){return x!=="";}))matrix.push(vals);}if(matrix.length<2)throw new Error("La hoja ODS no contiene filas de artículos.");var headers=matrix[0].map(norm);function idx(tokens){for(var i=0;i<headers.length;i++)if(tokens.every(function(t){return headers[i].includes(t);}))return i;return -1;}var desc=idx(["descripcion"]),qty=idx(["uds"]);if(qty<0)qty=idx(["cantidad"]);var price=idx(["precio","unitario","maximo"]);if(price<0)price=idx(["precio","unitario"]);var lot=idx(["lote"]),cpv=idx(["cpv"]);if(desc<0||qty<0||price<0)throw new Error("No se reconocen las columnas mínimas del ODS. Se necesitan descripción, unidades/cantidad y precio unitario.");var items=[];for(var j=1;j<matrix.length;j++){var row=matrix[j],den=(row[desc]||"").trim(),q=(row[qty]||"").trim(),pr=(row[price]||"").trim();if(!den&&!q&&!pr)continue;if(!den&&pr&&j===matrix.length-1)continue;items.push({referencia:"",denominacion:den,descripcion:den,unidad:"unidad",cantidad:q,precio:pr,lote:lot>=0?(row[lot]||"").trim():"",cpv:cpv>=0?(row[cpv]||"").trim():""});}return validateItems(items,"ODS");}
async function parseFile(file){var name=String(file.name||"").toLocaleLowerCase("es-ES");if(name.endsWith(".ods"))return parseOdsXml(await odsContentXml(file));if(name.endsWith(".csv")||file.type==="text/csv"||!file.type)return parseCsv(await file.text());throw new Error("Formato no admitido. Utilice CSV u ODS.");}
function isSupply(){var txt=work.textContent||"";return txt.includes("Suministros")||txt.includes("Naturaleza contractual propuesta: suministros");}
function hideGenericCompletion(){Array.from(work.querySelectorAll(".card.info")).forEach(function(card){if((card.textContent||"").includes("Espina dorsal completada")){var h=card.querySelector("h2");if(h)h.textContent="Espina dorsal común completada";var p=card.querySelector("p");if(p)p.textContent="Continúe a continuación con la rama específica del suministro.";}});}
function ensureCard(){if(!isSupply())return;hideGenericCompletion();var current=document.getElementById("supplyCatalogueCard");if(!current){work.insertAdjacentHTML("beforeend",catalogueCard());current=document.getElementById("supplyCatalogueCard");}renderSummary(readCatalogue());}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var data=readCatalogue(),a=readAnswers();if(t.id==="downloadSupplyTemplate")download(templateText(false),"plantilla_articulos_suministro.csv");if(t.id==="suggestSupplyCategories"){var text=String((a.needAndPurpose||"")+" "+(a.scopeDetail||"")).toLocaleLowerCase("es-ES");if(text.includes("ferreter"))download(templateText(true),"plantilla_suministro_ferreteria_orientativa.csv");}
if(t.id==="useCatalogueBudget"&&Number.isFinite(Number(data.total))){a.initialBudgetExVat=Number(data.total);delete a.supplyBudgetDifferenceJustified;delete a.supplyBudgetDifferenceReason;saveAnswers(a,"supply-budget-from-catalogue");renderSummary(data);}
if(t.id==="showBudgetReason"){var box=document.getElementById("budgetReasonBox");if(box)box.innerHTML='<label><strong>Justificación de la diferencia</strong></label><textarea id="budgetDifferenceReason" placeholder="Explique qué conceptos adicionales incorpora el presupuesto declarado"></textarea><button id="saveBudgetReason" type="button">Guardar justificación y continuar</button>';}
if(t.id==="saveBudgetReason"){var reason=document.getElementById("budgetDifferenceReason");if(!reason||!reason.value.trim()){alert("Indique la justificación de la diferencia presupuestaria.");return;}a.supplyBudgetDifferenceJustified=true;a.supplyBudgetDifferenceReason=reason.value.trim();saveAnswers(a,"supply-budget-justification");renderSummary(data);}
if(t.id==="saveSupplyCriteriaMode"){var mode=document.getElementById("supplyCriteriaMode");if(!mode||!mode.value){alert("Seleccione una opción.");return;}a.supplyAwardCriteriaMode=mode.value;saveAnswers(a,"supply-criteria");renderSummary(data);}
if(t.id==="continueSupplyClauses"){a.supplySpecificClausesStarted=true;saveAnswers(a,"supply-specific-clauses");renderSummary(data);}
if(t.id==="saveDeliveryDeadline"){var el=document.getElementById("supplyDeliveryDeadlineDays"),v=el?Number(el.value):NaN;if(!Number.isInteger(v)||v<=0){alert("Indique un número válido de días.");return;}a.supplyDeliveryDeadlineDays=v;saveAnswers(a,"supply-delivery-deadline");renderSummary(data);}
if(t.id==="saveDeliveryPlaces"){var el2=document.getElementById("supplyDeliveryPlacesDefined");if(!el2||!el2.value){alert("Seleccione una opción.");return;}a.supplyDeliveryPlacesDefined=el2.value==="true";saveAnswers(a,"supply-delivery-places");renderSummary(data);}
if(t.id==="saveReplacement"){var el3=document.getElementById("supplyReplacementRequired");if(!el3||!el3.value){alert("Seleccione una opción.");return;}a.supplyReplacementRequired=el3.value==="true";saveAnswers(a,"supply-replacement");renderSummary(data);}
});
work.addEventListener("change",async function(event){var t=event.target;if(!t||t.id!=="supplyFile"||!t.files||!t.files[0])return;var box=document.getElementById("supplyCatalogueSummary");try{if(box)box.innerHTML='<div class="info">Leyendo '+esc(t.files[0].name)+'…</div>';var data=await parseFile(t.files[0]);saveCatalogue(data);renderSummary(data);}catch(e){if(box)box.innerHTML='<div class="warning">'+esc(e.message)+'</div>';}});
var observer=new MutationObserver(function(){ensureCard();});observer.observe(work,{childList:true,subtree:false});ensureCard();
})();`;