export const SUPPLY_SECTION_14_DETERMINISTIC_REPAIR_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;return readJson(localStorage,answersKey);}
function saveAnswers(a){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-section-14-deterministic-repair"}}));}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function paragraphs(doc){var a=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));a.sort(function(x,y){if(x===y)return 0;return x.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1;});return a;}
function text(ps,i){return i>=0&&i<ps.length?norm(ps[i].textContent):"";}
function findContains(ps,parts,from,to){var stop=to==null?ps.length:to;for(var i=Math.max(0,from||0);i<stop;i++){var t=text(ps,i);for(var j=0;j<parts.length;j++)if(t.indexOf(norm(parts[j]))>=0)return i;}return -1;}
function locateBounds(ps){var annex=findContains(ps,["TÍTULO DEL CONTRATO:","CARACTERÍSTICAS DEL CONTRATO"],0);var endAnnex=findContains(ps,["ANEXO II"],annex>=0?annex:0);var limit=endAnnex>0?endAnnex:ps.length;var s14=findContains(ps,["MODIFICACIONES DEL CONTRATO","MODIFICACIONES CONTRACTUALES"],annex>=0?annex:0,limit);var s15=findContains(ps,["TRATAMIENTO DE DATOS PERSONALES"],s14>=0?s14+1:annex>=0?annex:0,limit);return {s14:s14,s15:s15,annex:annex,endAnnex:endAnnex};}
function insertBefore(doc,ref,v,styleSource){if(!ref||!ref.parentNode)return null;var p=doc.createElementNS(TEXT_NS,"text:p"),s=styleSource||ref,style=s.getAttributeNS(TEXT_NS,"style-name")||s.getAttribute("text:style-name");if(style)p.setAttributeNS(TEXT_NS,"text:style-name",style);p.textContent=v;ref.parentNode.insertBefore(p,ref);return p;}
var CANONICAL=[
"1. Reducción o supresión de prestaciones por medidas de estabilidad presupuestaria: No procede.",
"Alcance y límites de la modificación: No procede.",
"- Porcentaje máximo del precio del contrato al que pueda afectar esta causa: No procede.",
"2. Mayores necesidades reales respecto de las estimadas inicialmente, en contrato de suministro en función de las necesidades conforme a la disposición adicional 33.ª LCSP.",
"Alcance y límites de la modificación: aumento exclusivamente de unidades de las referencias ya incluidas, manteniendo el mismo objeto y los precios unitarios adjudicados; no podrán incorporarse nuevos artículos ni establecerse nuevos precios unitarios.",
"- Porcentaje máximo del precio inicial del contrato al que puede afectar esta modificación prevista: 20 %.",
"- La modificación deberá tramitarse antes de agotar el presupuesto máximo, manteniendo el mismo objeto y los precios unitarios adjudicados.",
"3. Otras causas de modificación previstas: No procede.",
"Alcance y límites de la modificación: No procede."
];
function rebuildSection14(doc){var ps=paragraphs(doc),b=locateBounds(ps);if(b.s14<0||b.s15<0||b.s15<=b.s14)throw new Error("No se han podido localizar los límites del apartado 14. Anclajes: modificaciones="+b.s14+", tratamientoDatos="+b.s15+".");var ref=ps[b.s15],style=ps[b.s14];for(var i=b.s14+1;i<b.s15;i++)ps[i].textContent="";CANONICAL.forEach(function(line){insertBefore(doc,ref,line,style);});return b;}
function audit(doc){var ps=paragraphs(doc),b=locateBounds(ps),err=[];if(b.s14<0||b.s15<0||b.s15<=b.s14){err.push("No se han podido delimitar los límites del apartado 14.");return {ok:false,errors:err,bounds:b};}var body=norm(ps.slice(b.s14+1,b.s15).map(function(p){return p.textContent;}).join(" "));var i1=body.indexOf("1. REDUCCIÓN O SUPRESIÓN");var i2=body.indexOf("2. MAYORES NECESIDADES REALES");var i3=body.indexOf("3. OTRAS CAUSAS DE MODIFICACIÓN");if(i1<0||i2<0||i3<0||!(i1<i2&&i2<i3))err.push("No se reconocen las tres causas canónicas en el orden esperado.");var c1=i1>=0&&i2>i1?body.slice(i1,i2):"";var c2=i2>=0&&i3>i2?body.slice(i2,i3):"";var c3=i3>=0?body.slice(i3):"";if(c1.indexOf("NO PROCEDE")<0)err.push("Causa 1 sin No procede.");if(c1.indexOf("20 %")>=0||c1.indexOf("20%")>=0)err.push("Causa 1 conserva el 20 %.");if(c2.indexOf("DISPOSICIÓN ADICIONAL 33")<0)err.push("Causa 2 sin DA 33.ª.");if(c2.indexOf("20 %")<0&&c2.indexOf("20%")<0)err.push("Causa 2 sin 20 %.");if(c2.indexOf("NUEVOS ARTÍCULOS")<0||c2.indexOf("NUEVOS PRECIOS UNITARIOS")<0)err.push("Causa 2 sin prohibición de nuevos artículos/precios.");if(c3.indexOf("NO PROCEDE")<0)err.push("Causa 3 sin No procede.");return {ok:err.length===0,errors:err,bounds:b,cause1:c1,cause2:c2,cause3:c3};}
function repair(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");rebuildSection14(doc);var a=audit(doc);if(!a.ok)throw new Error("La reconstrucción no supera la auditoría: "+a.errors.join(" "));return {xml:new XMLSerializer().serializeToString(doc),audit:a};}
async function process(bytes){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");var result=repair(new TextDecoder("utf-8").decode(content.data));content.data=new TextEncoder().encode(result.xml);var output=writeStoredZip(entries);await readZip(output);return {bytes:output,result:result};}
function download(bytes){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="CONTR-2026-240267_PCAP_Oficial_AnexoI_Apartado14_DA33_Corregido_Contrata-IA.odt";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function has14Blocker(a){var b=Array.isArray(a.supplyAnnexIComprehensiveAuditBlockers)?a.supplyAnnexIComprehensiveAuditBlockers:[];return b.some(function(x){return String(x).indexOf("14.")===0||String(x).indexOf("Modificación DA 33")>=0;});}
function card(){var a=readAnswers();if(a.supplyAnnexIFinalAuditValidated!==true||(!has14Blocker(a)&&a.supplySection14DeterministicRepairValidated!==true))return "";var html='<div id="supplySection14DeterministicRepairCard" class="card" style="margin-top:14px"><h3>11.2.2A Reconstrucción estructural del apartado 14</h3><div class="warning"><strong>Reconstrucción por límites de sección.</strong> El control localiza únicamente «Modificaciones del contrato» y «Tratamiento de datos personales» y reconstruye íntegramente el contenido intermedio. No depende de numeración automática, listas ni guiones bajos del ODT.</div>';if(a.supplySection14DeterministicRepairValidated===true){html+='<div class="info"><strong>Apartado 14 corregido y auditado.</strong> Causa 1 = No procede; causa 2 = DA 33.ª + 20 %; causa 3 = No procede. Vuelva a ejecutar 11.2.2 sobre el ODT descargado.</div>';}else{html+='<p>Seleccione el último ODT generado por el Paso 11.2.2.</p><input id="section14RepairFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runSection14DeterministicRepair" type="button">Reconstruir y auditar apartado 14</button>';}html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplySection14DeterministicRepairCard");if(old)old.remove();var anchor=document.getElementById("supplyAnnexIComprehensiveAuditCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target||e.target.id!=="runSection14DeterministicRepair")return;var input=document.getElementById("section14RepairFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione el último ODT generado por la auditoría integral 11.2.2.");return;}try{var out=await process(new Uint8Array(await file.arrayBuffer())),a=readAnswers(),existing=Array.isArray(a.supplyAnnexIComprehensiveAuditBlockers)?a.supplyAnnexIComprehensiveAuditBlockers:[];a.supplyAnnexIComprehensiveAuditBlockers=existing.filter(function(x){return !(String(x).indexOf("14.")===0||String(x).indexOf("Modificación DA 33")>=0);});a.supplySection14DeterministicRepairValidated=true;a.supplySection14DeterministicRepairStatus="CAUSE_1_NO_PROCEDE__CAUSE_2_DA33_20_PERCENT__CAUSE_3_NO_PROCEDE";a.supplySection14DeterministicRepairAudit=out.result.audit;a.supplySection14DeterministicRepairAt=new Date().toISOString();saveAnswers(a);download(out.bytes);alert("Apartado 14 reconstruido y auditado correctamente. Use el ODT descargado para volver a ejecutar el Paso 11.2.2.");ensure();}catch(err){alert("No se ha podido reconstruir el apartado 14: "+err.message);}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;