export const SUPPLY_ANNEX_I_AUDIT_FINAL_HOTFIX_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers",catalogueKey="contrataIaSupplyCatalogue";
var TEXT_NS="urn:oasis:names:tc:opendocument:xmlns:text:1.0";
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;return readJson(localStorage,answersKey);}
function readCatalogue(){var c=readJson(sessionStorage,catalogueKey);if(Array.isArray(c.items)&&c.items.length)return c;return readJson(localStorage,catalogueKey);}
function saveAnswers(a){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"supply-annex-i-final-audit"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function norm(v){return String(v||"").replace(/\\s+/g," ").trim().toUpperCase();}
function u16(b,p){return b[p]|(b[p+1]<<8);}function u32(b,p){return (b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))>>>0;}
function put16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function put32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
function concat(parts){var n=0;parts.forEach(function(x){n+=x.length;});var out=new Uint8Array(n),p=0;parts.forEach(function(x){out.set(x,p);p+=x.length;});return out;}
function crc32(data){var crc=0xffffffff;for(var i=0;i<data.length;i++){crc^=data[i];for(var b=0;b<8;b++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
async function inflateRaw(data){var ds=new DecompressionStream("deflate-raw");return new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer());}
async function readZip(bytes){var e=-1;for(var i=bytes.length-22;i>=0&&i>bytes.length-70000;i--){if(u32(bytes,i)===0x06054b50){e=i;break;}}if(e<0)throw new Error("El archivo no es un paquete ODT válido.");var count=u16(bytes,e+10),pos=u32(bytes,e+16),dec=new TextDecoder("utf-8"),entries=[];for(var n=0;n<count;n++){if(u32(bytes,pos)!==0x02014b50)throw new Error("Directorio ZIP ODT no reconocido.");var method=u16(bytes,pos+10),compressed=u32(bytes,pos+20),nameLen=u16(bytes,pos+28),extraLen=u16(bytes,pos+30),commentLen=u16(bytes,pos+32),localOffset=u32(bytes,pos+42),name=dec.decode(bytes.slice(pos+46,pos+46+nameLen)),ln=u16(bytes,localOffset+26),le=u16(bytes,localOffset+28),start=localOffset+30+ln+le,raw=bytes.slice(start,start+compressed),data=method===0?raw:await inflateRaw(raw);entries.push({name:name,data:data});pos+=46+nameLen+extraLen+commentLen;}return entries;}
function writeStoredZip(entries){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,ordered=entries.slice().sort(function(a,b){if(a.name==="mimetype")return -1;if(b.name==="mimetype")return 1;return 0;});ordered.forEach(function(e){var name=enc.encode(e.name),data=e.data,crc=crc32(data),local=concat([new Uint8Array([80,75,3,4]),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),name,data]);locals.push(local);centrals.push(concat([new Uint8Array([80,75,1,2]),put16(20),put16(20),put16(2048),put16(0),put16(0),put16(0x5c21),put32(crc),put32(data.length),put32(data.length),put16(name.length),put16(0),put16(0),put16(0),put16(0),put32(0),put32(offset),name]));offset+=local.length;});var central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),put16(0),put16(0),put16(ordered.length),put16(ordered.length),put32(central.length),put32(offset),put16(0)]);return concat(locals.concat([central,end]));}
function patchAndAudit(xml){var doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.getElementsByTagName("parsererror").length)throw new Error("No se ha podido interpretar content.xml.");var ps=Array.from(doc.getElementsByTagNameNS(TEXT_NS,"p")).concat(Array.from(doc.getElementsByTagNameNS(TEXT_NS,"h")));var priceChanged=false;for(var i=0;i<ps.length;i++){var t=norm(ps[i].textContent);if(t.indexOf("SISTEMA DE DETERMINACIÓN DEL PRECIO")>=0&&(t.indexOf("PRECIOS UNITARIOS POR REFERENCIA")<0||t.indexOf("_______")>=0)){ps[i].textContent="Sistema de determinación del precio: precios unitarios por referencia del catálogo validado.";priceChanged=true;break;}}
var serialized=new XMLSerializer().serializeToString(doc),txt=norm(doc.documentElement.textContent),catalogue=readCatalogue(),unresolved=[];
var priceOk=txt.indexOf("SISTEMA DE DETERMINACIÓN DEL PRECIO: PRECIOS UNITARIOS POR REFERENCIA DEL CATÁLOGO VALIDADO")>=0;
var penaltyOk=txt.indexOf("10,00 € SIN IVA POR CADA DÍA HÁBIL DE RETRASO")>=0||txt.indexOf("10,00 € SIN IVA POR CADA DIA HABIL DE RETRASO")>=0;
var paymentOk=txt.indexOf("PAGO ÚNICO / PAGOS PARCIALES: PAGOS PARCIALES")>=0||txt.indexOf("PAGO UNICO / PAGOS PARCIALES: PAGOS PARCIALES")>=0;
var catalogueStateOk=Array.isArray(catalogue.items)&&catalogue.items.length===98&&(!Array.isArray(catalogue.issues)||catalogue.issues.length===0);
var catalogueDocOk=txt.indexOf("TOTAL: 654 UNIDADES ESTIMADAS")>=0&&txt.indexOf("TOTAL: 4.540,24 €")>=0;
if(!priceOk)unresolved.push("sistema de determinación del precio");if(!penaltyOk)unresolved.push("penalidad demora");if(!paymentOk)unresolved.push("régimen de pago");if(!(catalogueStateOk&&catalogueDocOk))unresolved.push("especificaciones del objeto: volcado estructural del catálogo validado");
return {xml:serialized,unresolved:unresolved,priceChanged:priceChanged,checks:{price:priceOk,penalty:penaltyOk,payment:paymentOk,catalogue:catalogueStateOk&&catalogueDocOk}};}
async function process(bytes){var entries=await readZip(bytes),content=entries.find(function(e){return e.name==="content.xml";});if(!content)throw new Error("ODT sin content.xml.");var result=patchAndAudit(new TextDecoder("utf-8").decode(content.data));content.data=new TextEncoder().encode(result.xml);var output=writeStoredZip(entries);await readZip(output);return {bytes:output,result:result};}
function download(bytes){var blob=new Blob([bytes],{type:"application/vnd.oasis.opendocument.text"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="CONTR-2026-240267_PCAP_Oficial_AnexoI_Cierre_11-2_FINAL_Contrata-IA.odt";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function card(){var a=readAnswers();if(a.supplyAnnexICompletionGenerated!==true)return "";var html='<div id="supplyAnnexIFinalAuditCard" class="card" style="margin-top:14px"><h3>11.2.1 Cierre final de auditoría del Anexo I</h3><div class="info"><strong>Auditoría sobre el documento real.</strong> Este control corrige el anclaje del sistema de determinación del precio y vuelve a verificar penalidad por demora, régimen de pago y volcado de las 98 referencias directamente en el ODT.</div><div class="warning"><strong>Use el último ODT generado en el Paso 11.2.</strong> No se deducirá el cierre únicamente del estado de la interfaz.</div><input id="annexIFinalAuditFile" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="runAnnexIFinalAudit" type="button">Cerrar y auditar ODT 11.2</button>';
if(a.supplyAnnexIFinalAuditValidated===true){html+='<div class="info"><strong>Auditoría documental superada.</strong> Sistema de precio, penalidad de demora, régimen de pago y catálogo se han comprobado en el ODT final. Bloqueantes reales: 0.</div>';}html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyAnnexIFinalAuditCard");if(old)old.remove();var anchor=document.getElementById("supplyAnnexICompletionCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",async function(e){if(!e.target||e.target.id!=="runAnnexIFinalAudit")return;var input=document.getElementById("annexIFinalAuditFile"),file=input&&input.files&&input.files[0];if(!file){alert("Seleccione el último ODT generado por el Paso 11.2.");return;}try{var out=await process(new Uint8Array(await file.arrayBuffer())),a=readAnswers(),r=out.result;a.supplyAnnexIUnresolvedFields=r.unresolved;a.supplyAnnexICompletionStatus=r.unresolved.length?"PENDING_HUMAN_COMPLETION":"COMPLETE";a.supplyAnnexIFinalAuditChecks=r.checks;a.supplyAnnexIFinalAuditValidated=r.unresolved.length===0;a.supplyAnnexIFinalAuditPriceAnchorCorrected=r.priceChanged;saveAnswers(a);download(out.bytes);alert(r.unresolved.length?"ODT corregido, pero aún quedan "+r.unresolved.length+" bloqueantes reales: "+r.unresolved.join(", "):"Auditoría del Anexo I superada. Bloqueantes reales: 0.");ensure();}catch(err){alert("No se ha podido cerrar la auditoría del ODT: "+err.message);}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;