import { VEIASA_REGRESSION_BASELINE, VEIASA_REGRESSION_VERSION } from "../../regression/SupplyRegressionCase006VeiasaWindowsGuard";
import { SERVICE_REGRESSION_CARL_005_EXTRACTION_SCRIPT } from "./ServiceRegressionCarl005ExtractionScript";

const BASELINE_JSON = JSON.stringify(VEIASA_REGRESSION_BASELINE);

const VEIASA_GUARD_CORE_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var key="contrataIaAdaptiveAnswers";
var VERSION=${JSON.stringify(VEIASA_REGRESSION_VERSION)};
var BASELINE=${BASELINE_JSON};
function readJson(s,k){try{return JSON.parse(s.getItem(k)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,key);if(Object.keys(a).length)return a;return readJson(localStorage,key);}
function save(a){var raw=JSON.stringify(a);sessionStorage.setItem(key,raw);localStorage.setItem(key,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:"veiasa-regression-11.7.11"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function manifest(){return {version:VERSION,caseId:BASELINE.caseId,status:BASELINE.passed?"AUTOMATIC_REGRESSION_ACTIVE":"AUTOMATIC_REGRESSION_BLOCKED",passed:BASELINE.passed,blockers:BASELINE.blockers,checks:BASELINE.checks,protectedScope:BASELINE.protectedScope,deliberatelyNotFrozenYet:BASELINE.deliberatelyNotFrozenYet,forbiddenGoldenInheritance:BASELINE.forbiddenGoldenInheritance,requiresSourceExtractionHumanValidation:true,sourceExtractionHumanValidated:true,acceptanceRule:"La regresión protege únicamente el alcance validado en 11.7.10. VEIASA debe permanecer sin DA 33.ª, con precio global, sin prórroga y sin modificación prevista; no puede heredar presupuesto máximo por necesidades, precios unitarios, catálogo de 98 referencias ni lógica de mayores necesidades del golden case.",registeredAt:new Date().toISOString()};}
function downloadJson(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Contrata-IA_REG-SUPPLY-006_VEIASA_Regression_11-7-11.json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
function rows(){return BASELINE.checks.map(function(c){return '<tr><td>'+esc(c.id)+'</td><td>'+(c.ok?'✓ Pasa':'✗ Bloquea')+'</td><td>'+esc(c.purpose)+'</td></tr>';}).join("");}
function card(){var a=readAnswers();if(a.supplyRegressionVeiasa006ExtractionValidated!==true)return "";var registered=a.supplyRegressionVeiasa006AutomaticGuardRegistered===true;var html='<div id="supplyRegressionVeiasa006GuardCard" class="card" style="margin-top:14px"><h3>11.7.11 Regresión automática VEIASA Windows Server</h3>';
if(BASELINE.passed){html+='<div class="info"><strong>Protección automática activa.</strong> La línea base supera '+BASELINE.checks.length+' comprobaciones con 0 bloqueantes. Se protege suministro, abierto simplificado ordinario, lote único, DA 33.ª desactivada, precio global, criterio económico único, ausencia de prórroga y ausencia de modificación prevista.</div>';}else{html+='<div class="warning"><strong>Regresión bloqueada.</strong> Existen '+BASELINE.blockers.length+' incoherencias y no puede registrarse.</div>';}
html+='<div class="warning"><strong>Guardas críticas.</strong> VEIASA no puede heredar presupuesto máximo DA 33.ª, precios unitarios, prórrogas 12+12, modificación por mayores necesidades, catálogo de 98 referencias ni importes del golden case.</div><div class="warning"><strong>Alcance limitado deliberadamente.</strong> No se congelan todavía importes, CPV, duración exacta, entrega/implantación, garantía, solvencia, fórmula económica, condiciones especiales ni obligaciones técnicas de soporte.</div><table style="width:100%;border-collapse:collapse"><thead><tr><th>Check</th><th>Resultado</th><th>Qué protege</th></tr></thead><tbody>'+rows()+'</tbody></table>';
if(!registered&&BASELINE.passed){html+='<button id="registerVeiasa006AutomaticGuard" type="button">Registrar regresión automática 11.7.11</button>';}else if(registered){html+='<div class="info"><strong>11.7.11 registrado.</strong> Versión '+esc(VERSION)+'. VEIASA queda protegido como caso de regresión, pero no como golden case.</div><button id="downloadVeiasa006AutomaticGuard" type="button" class="secondary">Descargar manifiesto 11.7.11 JSON</button>';}
html+='</div>';return html;}
function ensure(){var old=document.getElementById("supplyRegressionVeiasa006GuardCard");if(old)old.remove();var anchor=document.getElementById("supplyRegressionVeiasa006ExtractionCard");if(anchor){var html=card();if(html)anchor.insertAdjacentHTML("afterend",html);}}
document.addEventListener("click",function(e){if(!e.target)return;if(e.target.id==="registerVeiasa006AutomaticGuard"){var a=readAnswers();if(a.supplyRegressionVeiasa006ExtractionValidated!==true){alert("Primero debe validarse la extracción documental 11.7.10.");return;}if(!BASELINE.passed){alert("La regresión presenta bloqueantes y no puede registrarse.");return;}var m=manifest();a.supplyRegressionVeiasa006AutomaticGuardRegistered=true;a.supplyRegressionVeiasa006AutomaticGuardVersion=VERSION;a.supplyRegressionVeiasa006AutomaticGuardManifest=m;a.supplyRegressionVeiasa006Status="AUTOMATIC_REGRESSION_ACTIVE";a.supplyRegressionNextRecommendedCase="REG-SERVICE-005";save(a);downloadJson(m);ensure();alert("Regresión automática VEIASA 11.7.11 registrada. REG-SUPPLY-006 queda protegido sin convertirse en golden case.");return;}if(e.target.id==="downloadVeiasa006AutomaticGuard"){var a2=readAnswers();downloadJson(a2.supplyRegressionVeiasa006AutomaticGuardManifest||manifest());return;}},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,500);
})();`;

export const SUPPLY_REGRESSION_VEIASA_006_GUARD_SCRIPT = VEIASA_GUARD_CORE_SCRIPT + "\n" + SERVICE_REGRESSION_CARL_005_EXTRACTION_SCRIPT;
