export const SUPPLY_QUALIFICATION_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");
if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-qualification"}}));}
function branchReady(){var txt=work.textContent||"";return txt.includes("Rama de suministro avanzada")||txt.includes("plazo de entrega y régimen básico de conformidad");}
function capabilityLabel(value){if(value==="ORDINARY_MARKET")return "Suministro ordinario de mercado";if(value==="SPECIFIC_CAPACITY")return "Se requiere experiencia o capacidad específica";if(value==="UNKNOWN")return "Pendiente de concretar";return "Pendiente";}
function guaranteeLabel(value){if(value==="NO_ADDITIONAL")return "Sin garantía adicional propuesta en esta fase";if(value==="REQUIRED")return "Se considera necesaria una garantía específica";if(value==="UNKNOWN")return "Pendiente de concretar";return "Pendiente";}
function specialConditionLabel(value){if(value==="ENVIRONMENTAL")return "Condición ambiental vinculada a la ejecución";if(value==="SOCIAL")return "Condición social vinculada a la ejecución";if(value==="DELIVERY_PACKAGING")return "Condición sobre entregas, embalajes o gestión de residuos";if(value==="NONE_IDENTIFIED")return "No se ha identificado todavía una condición específica";if(value==="UNKNOWN")return "Pendiente de concretar";return "Pendiente";}
function qualificationBranch(){var a=readAnswers();var html='<div id="supplyQualificationCard" class="card"><h3>3. Aptitud, solvencia, garantías y condiciones de ejecución</h3>';
if(a.supplyCapabilityNeed===undefined){html+='<p><strong>¿Para ejecutar correctamente este suministro necesita exigir a la empresa alguna capacidad o experiencia específica, aparte de dedicarse normalmente a la venta y suministro de este tipo de materiales?</strong></p><p class="muted">Responda desde la necesidad real. Contrata-IA propondrá después cómo trasladarlo a la solvencia del expediente.</p><select id="supplyCapabilityNeed"><option value="">Seleccione</option><option value="ORDINARY_MARKET">No, es un suministro ordinario de mercado</option><option value="SPECIFIC_CAPACITY">Sí, necesita experiencia o capacidad específica</option><option value="UNKNOWN">No lo sé todavía</option></select><button id="saveSupplyCapability" type="button">Guardar y continuar</button></div>';return html;}
html+='<div class="info"><strong>Necesidad de capacidad:</strong> '+esc(capabilityLabel(a.supplyCapabilityNeed))+'.</div>';
if(a.supplyCapabilityNeed==="SPECIFIC_CAPACITY"&&a.supplyCapabilityDetail===undefined){html+='<p><strong>¿Qué capacidad o experiencia concreta necesita?</strong></p><textarea id="supplyCapabilityDetail" placeholder="Describa el requisito técnico o de experiencia realmente necesario"></textarea><button id="saveSupplyCapabilityDetail" type="button">Guardar y continuar</button></div>';return html;}
if(a.supplyCapabilityNeed==="UNKNOWN"&&a.supplyCapabilityDetail===undefined){html+='<div class="warning">La solvencia queda provisionalmente pendiente. Debe concretarse antes de cerrar los pliegos.</div><button id="deferSupplyCapability" type="button">Continuar dejando esta comprobación pendiente</button></div>';return html;}
if(a.supplyGuaranteeNeed===undefined){html+='<p><strong>¿Existe algún riesgo de ejecución que aconseje exigir una garantía específica adicional?</strong></p><p class="muted">Por ejemplo, riesgo relevante de incumplimiento en entregas, reposición o conformidad. No es necesario conocer ahora el régimen jurídico de garantías.</p><select id="supplyGuaranteeNeed"><option value="">Seleccione</option><option value="NO_ADDITIONAL">No se aprecia un riesgo adicional relevante</option><option value="REQUIRED">Sí, conviene estudiar una garantía específica</option><option value="UNKNOWN">No lo sé todavía</option></select><button id="saveSupplyGuarantee" type="button">Guardar y continuar</button></div>';return html;}
html+='<div class="info"><strong>Garantía:</strong> '+esc(guaranteeLabel(a.supplyGuaranteeNeed))+'.</div>';
if(a.supplyGuaranteeNeed==="REQUIRED"&&a.supplyGuaranteeReason===undefined){html+='<p><strong>¿Qué riesgo concreto pretende cubrir?</strong></p><textarea id="supplyGuaranteeReason" placeholder="Describa el riesgo que justifica estudiar una garantía específica"></textarea><button id="saveSupplyGuaranteeReason" type="button">Guardar y continuar</button></div>';return html;}
if(a.supplySpecialExecutionCondition===undefined){html+='<p><strong>¿Qué tipo de condición especial de ejecución encaja mejor con este suministro?</strong></p><p class="muted">La propuesta debe guardar relación con la ejecución del contrato y será validada antes de trasladarse al PCAP.</p><select id="supplySpecialExecutionCondition"><option value="">Seleccione</option><option value="DELIVERY_PACKAGING">Entregas, reducción de embalajes o correcta gestión de residuos</option><option value="ENVIRONMENTAL">Otra condición ambiental vinculada al suministro</option><option value="SOCIAL">Condición social vinculada a la ejecución</option><option value="NONE_IDENTIFIED">No identifico ahora una condición específica</option><option value="UNKNOWN">No lo sé todavía</option></select><button id="saveSupplySpecialCondition" type="button">Guardar y continuar</button></div>';return html;}
html+='<div class="info"><strong>Condición especial de ejecución:</strong> '+esc(specialConditionLabel(a.supplySpecialExecutionCondition))+'.</div>';
html+='<div class="info"><strong>Bloque 3 completado.</strong> Ya pueden abrirse las comprobaciones finales de solvencia proporcional, régimen de garantías, condiciones especiales y preparación documental. Antes de generar los pliegos, las propuestas deberán someterse a validación humana y verificación normativa vigente.</div></div>';return html;}
function ensure(){var existing=document.getElementById("supplyQualificationCard");if(!branchReady()){if(existing)existing.remove();return;}if(existing)return;var catalogue=document.getElementById("supplyCatalogueCard");if(catalogue)catalogue.insertAdjacentHTML("afterend",qualificationBranch());else work.insertAdjacentHTML("beforeend",qualificationBranch());}
function rerender(){var old=document.getElementById("supplyQualificationCard");if(old)old.remove();ensure();}
work.addEventListener("click",function(event){var t=event.target;if(!t||!t.id)return;var a=readAnswers();
if(t.id==="saveSupplyCapability"){var el=document.getElementById("supplyCapabilityNeed");if(!el||!el.value){alert("Seleccione una opción.");return;}a.supplyCapabilityNeed=el.value;saveAnswers(a,"supply-capability");rerender();}
if(t.id==="saveSupplyCapabilityDetail"){var el2=document.getElementById("supplyCapabilityDetail");if(!el2||!el2.value.trim()){alert("Describa la capacidad o experiencia necesaria.");return;}a.supplyCapabilityDetail=el2.value.trim();saveAnswers(a,"supply-capability-detail");rerender();}
if(t.id==="deferSupplyCapability"){a.supplyCapabilityDetail="PENDING_VALIDATION";saveAnswers(a,"supply-capability-pending");rerender();}
if(t.id==="saveSupplyGuarantee"){var el3=document.getElementById("supplyGuaranteeNeed");if(!el3||!el3.value){alert("Seleccione una opción.");return;}a.supplyGuaranteeNeed=el3.value;saveAnswers(a,"supply-guarantee");rerender();}
if(t.id==="saveSupplyGuaranteeReason"){var el4=document.getElementById("supplyGuaranteeReason");if(!el4||!el4.value.trim()){alert("Describa el riesgo que se pretende cubrir.");return;}a.supplyGuaranteeReason=el4.value.trim();saveAnswers(a,"supply-guarantee-reason");rerender();}
if(t.id==="saveSupplySpecialCondition"){var el5=document.getElementById("supplySpecialExecutionCondition");if(!el5||!el5.value){alert("Seleccione una opción.");return;}a.supplySpecialExecutionCondition=el5.value;saveAnswers(a,"supply-special-condition");rerender();}
});
var observer=new MutationObserver(function(){ensure();});observer.observe(work,{childList:true,subtree:true});ensure();
})();`;
