export const SUPPLY_OFFICIAL_TEMPLATE_PENDING_FIELDS_SCRIPT = `"use strict";
(function(){
var work=document.getElementById("work");if(!work)return;
var answersKey="contrataIaAdaptiveAnswers";
function readJson(storage,key){try{return JSON.parse(storage.getItem(key)||"{}");}catch(e){return {};}}
function readAnswers(){var a=readJson(sessionStorage,answersKey);if(Object.keys(a).length)return a;a=readJson(localStorage,answersKey);if(Object.keys(a).length)sessionStorage.setItem(answersKey,JSON.stringify(a));return a;}
function saveAnswers(a,kind){var raw=JSON.stringify(a);sessionStorage.setItem(answersKey,raw);localStorage.setItem(answersKey,raw);document.dispatchEvent(new CustomEvent("contrata-ia:adaptive-saved",{detail:{kind:kind||"supply-official-template-pending-fields"}}));}
function esc(v){return String(v==null?"":v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function money(v){return Number(v||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2})+" €";}
function num(v){if(typeof v==="number")return v;var s=String(v==null?"":v).trim().replace(/\s/g,"");if(s.includes(",")&&s.includes("."))s=s.lastIndexOf(",")>s.lastIndexOf(".")?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"");else if(s.includes(","))s=s.replace(",",".");var n=Number(s);return Number.isFinite(n)?n:NaN;}
function ready(a){return a.supplyOfficialTemplateParameterizationValidated===true&&a.supplyOfficialTemplateParameterizationModel==="JDA-PCAP-SUPPLY-OSA-SELF-2025-12";}
function parseAnnualities(text){var lines=String(text||"").split(/\n+/).map(function(x){return x.trim();}).filter(Boolean);var out=[];for(var i=0;i<lines.length;i++){var m=lines[i].match(/^(20\d{2})\s*[:=;|]\s*(.+)$/);if(!m)return null;var amount=num(m[2]);if(!Number.isFinite(amount)||amount<0)return null;out.push({year:Number(m[1]),amount:Math.round(amount*100)/100});}return out.length?out:null;}
function annualitiesText(a){if(Array.isArray(a.supplyCurrentBudgetAnnualities)&&a.supplyCurrentBudgetAnnualities.length)return a.supplyCurrentBudgetAnnualities.map(function(x){return x.year+" = "+Number(x.amount).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2});}).join("\n");return "";}
function completed(a){return a.supplyCurrentTenderBudgetValidated===true&&a.supplyCurrentBudgetAllocationValidated===true&&a.supplyAbnormallyLowParametersValidated===true&&a.supplyTieBreakValidated===true&&a.supplySpecificPenaltiesDecisionValidated===true;}
function card(a){var budget=Number(a.supplyMaximumApprovedBudgetExVat||0),ve=Number(a.supplyEstimatedValueExVat||0);var pblEx=Number(a.supplyCurrentTenderBudgetExVat||0),vat=Number(a.supplyCurrentTenderVatRate||0),pblInc=Number(a.supplyCurrentTenderBudgetInclVat||0);var tie=a.supplyTieBreakMode||"";var pen=a.supplySpecificPenaltiesMode||"";var html='<div id="supplyOfficialTemplatePendingFieldsCard" class="card" style="margin-top:14px"><h3>8. Cierre de campos pendientes del Anexo I</h3><div class="info"><strong>Regla de consistencia económica.</strong> El presupuesto máximo DA 33.ª validado ('+money(budget)+' sin IVA), el PBL que finalmente se incorpore al Anexo I y el valor estimado ('+money(ve)+' sin IVA) se mantienen como magnitudes diferenciadas. Contrata-IA no copiará automáticamente una sobre otra.</div>';
if(completed(a)){html+='<div class="info"><strong>Campos pendientes cerrados.</strong> PBL vigente, anualidades/aplicación presupuestaria, oferta anormalmente baja/desempate y decisión sobre penalidades específicas han quedado validados. El expediente puede pasar a la preparación del primer borrador editable sobre el modelo oficial.</div><ul><li><strong>PBL validado:</strong> '+money(pblEx)+' sin IVA · '+money(pblInc)+' IVA incluido ('+vat.toLocaleString("es-ES",{maximumFractionDigits:2})+' %).</li><li><strong>Aplicación presupuestaria:</strong> '+esc(a.supplyCurrentBudgetApplication||'')+'.</li><li><strong>Desempate:</strong> '+esc(tie==="LEGAL_ART_147_2"?'Aplicación supletoria del artículo 147.2 LCSP':a.supplyTieBreakSpecificText||'Criterios específicos validados')+'.</li><li><strong>Penalidades específicas:</strong> '+esc(pen==="NONE"?'No se añaden penalidades particulares adicionales':a.supplySpecificPenaltiesText||'Penalidades particulares validadas')+'.</li></ul></div>';return html;}
html+='<div class="warning"><strong>Complete únicamente estos cuatro bloques.</strong> Los datos históricos del PCAP anterior se conservan como antecedente y no se reutilizan automáticamente.</div>';
html+='<h4>8.1 PBL vigente del Anexo I</h4><p class="muted">El artículo 100 LCSP define el PBL como límite máximo de gasto, incluido IVA. Introduzca la configuración vigente que deba constar en este expediente; no se propone automáticamente la cifra de versiones anteriores.</p><label><strong>PBL sin IVA (€)</strong></label><input id="pendingPblExVat" inputmode="decimal" value="'+esc(pblEx>0?pblEx:"")+'"><label><strong>Tipo de IVA (%)</strong></label><input id="pendingPblVatRate" inputmode="decimal" value="'+esc(vat>0?vat:"")+'"><div id="pendingPblPreview" class="muted">'+(pblInc>0?'PBL IVA incluido actualmente guardado: '+money(pblInc):'El total IVA incluido se calculará al guardar.')+'</div>';
html+='<h4>8.2 Anualidades y aplicación presupuestaria vigentes</h4><label><strong>Aplicación / partida presupuestaria</strong></label><input id="pendingBudgetApplication" value="'+esc(a.supplyCurrentBudgetApplication||"")+'" placeholder="Aplicación presupuestaria vigente"><label><strong>Anualidades</strong></label><textarea id="pendingBudgetAnnualities" placeholder="Una anualidad por línea. Ej.: 2026 = 1.000,00">'+esc(annualitiesText(a))+'</textarea><p class="muted">Introduzca los importes tal como deban constar presupuestariamente. Contrata-IA no reutiliza automáticamente las anualidades de la versión económica anterior.</p>';
html+='<h4>8.3 Oferta anormalmente baja y desempate</h4><label><strong>Parámetros objetivos para identificar ofertas anormalmente bajas</strong></label><textarea id="pendingAbnormallyLowParameters" placeholder="Redacción o regla objetiva que se incorporará al Anexo I">'+esc(a.supplyAbnormallyLowParametersText||"")+'</textarea><p class="muted">El parámetro debe quedar definido expresamente en el pliego conforme al artículo 149 LCSP.</p><label><strong>Desempate</strong></label><select id="pendingTieBreakMode"><option value="">Seleccione</option><option value="LEGAL_ART_147_2"'+(tie==="LEGAL_ART_147_2"?' selected':'')+'>No establecer criterios específicos: aplicar el orden legal del artículo 147.2 LCSP</option><option value="SPECIFIC"'+(tie==="SPECIFIC"?' selected':'')+'>Establecer criterios específicos vinculados al objeto</option></select><textarea id="pendingTieBreakSpecificText" placeholder="Solo si selecciona criterios específicos">'+esc(a.supplyTieBreakSpecificText||"")+'</textarea>';
html+='<h4>8.4 Penalidades específicas del apartado 10</h4><p class="muted">El artículo 192 LCSP permite prever penalidades particulares para cumplimiento defectuoso o incumplimientos definidos. No se crean automáticamente.</p><select id="pendingPenaltiesMode"><option value="">Seleccione</option><option value="NONE"'+(pen==="NONE"?' selected':'')+'>No añadir penalidades específicas adicionales</option><option value="SPECIFIC"'+(pen==="SPECIFIC"?' selected':'')+'>Añadir penalidades específicas</option></select><textarea id="pendingPenaltiesText" placeholder="Solo si se añaden penalidades específicas: supuesto, cuantía o regla y límite aplicable">'+esc(a.supplySpecificPenaltiesText||"")+'</textarea>';
html+='<button id="validateSupplyPendingAnnexFields" type="button">Guardar y validar campos pendientes</button></div>';return html;}
function ensure(){var old=document.getElementById("supplyOfficialTemplatePendingFieldsCard");if(old)old.remove();var a=readAnswers();var anchor=document.getElementById("supplyOfficialTemplateParameterizationCard");if(!anchor||!ready(a))return;anchor.insertAdjacentHTML("afterend",card(a));}
work.addEventListener("click",function(event){var t=event.target;if(!t||t.id!=="validateSupplyPendingAnnexFields")return;var a=readAnswers();if(!ready(a)){alert("Debe validarse primero el mapa estructural del Anexo I.");return;}var pblEl=document.getElementById("pendingPblExVat"),vatEl=document.getElementById("pendingPblVatRate"),appEl=document.getElementById("pendingBudgetApplication"),annEl=document.getElementById("pendingBudgetAnnualities"),abnEl=document.getElementById("pendingAbnormallyLowParameters"),tieEl=document.getElementById("pendingTieBreakMode"),tieTextEl=document.getElementById("pendingTieBreakSpecificText"),penEl=document.getElementById("pendingPenaltiesMode"),penTextEl=document.getElementById("pendingPenaltiesText");var pbl=num(pblEl?pblEl.value:""),vatRate=num(vatEl?vatEl.value:""),annualities=parseAnnualities(annEl?annEl.value:"");if(!Number.isFinite(pbl)||pbl<=0){alert("Debe indicar un PBL vigente sin IVA superior a cero.");return;}if(!Number.isFinite(vatRate)||vatRate<0||vatRate>100){alert("Debe indicar un tipo de IVA válido entre 0 y 100.");return;}if(!appEl||!appEl.value.trim()||!annualities){alert("Debe indicar la aplicación presupuestaria y al menos una anualidad válida (AAAA = importe).");return;}if(!abnEl||!abnEl.value.trim()){alert("Debe definir los parámetros objetivos de oferta anormalmente baja que se trasladarán al Anexo I.");return;}var tieMode=tieEl?tieEl.value:"";if(!tieMode){alert("Debe decidir el régimen de desempate.");return;}if(tieMode==="SPECIFIC"&&(!tieTextEl||!tieTextEl.value.trim())){alert("Si establece criterios específicos de desempate debe indicar su redacción.");return;}var penMode=penEl?penEl.value:"";if(!penMode){alert("Debe decidir si se incorporan penalidades específicas adicionales.");return;}if(penMode==="SPECIFIC"&&(!penTextEl||!penTextEl.value.trim())){alert("Si se añaden penalidades específicas debe indicar su redacción.");return;}var incl=Math.round((pbl*(1+vatRate/100))*100)/100;a.supplyCurrentTenderBudgetExVat=Math.round(pbl*100)/100;a.supplyCurrentTenderVatRate=vatRate;a.supplyCurrentTenderBudgetInclVat=incl;a.supplyCurrentTenderBudgetValidated=true;a.supplyCurrentBudgetApplication=appEl.value.trim();a.supplyCurrentBudgetAnnualities=annualities;a.supplyCurrentBudgetAllocationValidated=true;a.supplyAbnormallyLowParametersText=abnEl.value.trim();a.supplyAbnormallyLowParametersValidated=true;a.supplyTieBreakMode=tieMode;a.supplyTieBreakSpecificText=tieMode==="SPECIFIC"?tieTextEl.value.trim():"";a.supplyTieBreakValidated=true;a.supplySpecificPenaltiesMode=penMode;a.supplySpecificPenaltiesText=penMode==="SPECIFIC"?penTextEl.value.trim():"";a.supplySpecificPenaltiesDecisionValidated=true;a.supplyOfficialTemplatePendingFieldsValidated=true;a.supplyOfficialTemplatePendingFieldsStatus="ANNEX_I_REQUIRED_FIELDS_CLOSED_READY_FOR_EDITABLE_DRAFT";saveAnswers(a,"supply-annex-pending-fields-validated");ensure();},true);
document.addEventListener("contrata-ia:adaptive-saved",function(){setTimeout(ensure,0);});setTimeout(ensure,0);setTimeout(ensure,180);
})();`;
