/**
 * ============================================================
 * CONTRATA-IA
 * ------------------------------------------------------------
 * MemoryDefinition
 * ------------------------------------------------------------
 * Modelo documental oficial de la Memoria Justificativa.
 *
 * NO genera texto.
 *
 * Únicamente define:
 *
 * • estructura
 * • epígrafes
 * • orden
 * • obligatoriedad
 * • reutilización
 *
 * ============================================================
 */

import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";
import { SectionDefinition } from "../SectionDefinition";

export const MemoryDefinition: DocumentDefinition = {

    id: "MEMORIA",

    type: DocumentType.MEMORY,

    title: "Memoria Justificativa",

    description:
        "Documento principal del expediente de contratación.",

    mandatory: true,

    order: 10,

    autoGenerated: true,

    editable: true,

    requiresSignature: true,

    includedInExpediente: true,

    dependsOn: [],

    excludes: [],

    sections: [

        {

            id: "NEED",

            order: 1,

            title: "Necesidad del contrato",

            description:
                "Justificación de la necesidad.",

            mandatory: true,

            editable: true,

            reusable: true,

            reusableKey: "NEED",

            legalArticles: [

                "LCSP-28",

                "LCSP-116"

            ],

            dependsOn: [],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

        {

            id: "OBJECT",

            order: 2,

            title: "Objeto del contrato",

            description:
                "Definición del objeto contractual.",

            mandatory: true,

            editable: true,

            reusable: true,

            reusableKey: "OBJECT",

            legalArticles: [

                "LCSP-99"

            ],

            dependsOn: [],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

        {

            id: "INSUFFICIENCY",

            order: 3,

            title: "Insuficiencia de medios",

            description:
                "Justificación de insuficiencia de medios.",

            mandatory: true,

            editable: true,

            reusable: true,

            reusableKey: "MEANS",

            legalArticles: [

                "LCSP-28"

            ],

            dependsOn: [],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

              {
            id: "CPV",

            order: 4,

            title: "Clasificación CPV",

            description:
                "Códigos CPV aplicables al contrato.",

            mandatory: true,

            editable: false,

            reusable: true,

            reusableKey: "CPV",

            legalArticles: [

                "LCSP-99"

            ],

            dependsOn: [

                "OBJECT"

            ],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

        {
            id: "LOTS",

            order: 5,

            title: "División en lotes",

            description:
                "Justificación de la división o no división en lotes.",

            mandatory: true,

            editable: true,

            reusable: true,

            reusableKey: "LOTS",

            legalArticles: [

                "LCSP-99.3"

            ],

            dependsOn: [

                "OBJECT"

            ],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

        {

            id: "BUDGET",

            order: 6,

            title: "Presupuesto base de licitación",

            description:
                "Determinación del presupuesto del contrato.",

            mandatory: true,

            editable: false,

            reusable: true,

            reusableKey: "BUDGET",

            legalArticles: [

                "LCSP-100"

            ],

            dependsOn: [],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

        {

            id: "ESTIMATED_VALUE",

            order: 7,

            title: "Valor estimado",

            description:
                "Determinación del valor estimado del contrato.",

            mandatory: true,

            editable: false,

            reusable: true,

            reusableKey: "VALUE",

            legalArticles: [

                "LCSP-101"

            ],

            dependsOn: [

                "BUDGET"

            ],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

        {

            id: "PROCEDURE",

            order: 8,

            title: "Procedimiento de adjudicación",

            description:
                "Procedimiento aplicable conforme a la LCSP.",

            mandatory: true,

            editable: false,

            reusable: true,

            reusableKey: "PROCEDURE",

            legalArticles: [

                "LCSP-131"

            ],

            dependsOn: [

                "ESTIMATED_VALUE"

            ],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

        {

            id: "DURATION",

            order: 9,

            title: "Duración",

            description:
                "Duración prevista del contrato.",

            mandatory: true,

            editable: true,

            reusable: true,

            reusableKey: "DURATION",

            legalArticles: [

                "LCSP-29"

            ],

            dependsOn: [],

            excludes: [],

            priority: 1,

            isVisible: () => true,

            shouldRender: () => true

        },

              {

            id: "SOLVENCY",

            order: 10,

            title: "Solvencia",

            description:
                "Requisitos de solvencia económica, financiera y técnica.",

            mandatory: false,

            editable: false,

            reusable: true,

            reusableKey: "SOLVENCY",

            legalArticles: [

                "LCSP-74",

                "LCSP-75",

                "LCSP-86",

                "LCSP-87",

                "LCSP-90"

            ],

            dependsOn: [

                "PROCEDURE"

            ],

            excludes: [],

            priority: 2,

            isVisible: (ctx) =>

                ctx.solvency.required,

            shouldRender: (ctx) =>

                ctx.solvency.required

        },

        {

            id: "AWARD_CRITERIA",

            order: 11,

            title: "Criterios de adjudicación",

            description:
                "Determinación de los criterios de adjudicación.",

            mandatory: true,

            editable: false,

            reusable: true,

            reusableKey: "CRITERIA",

            legalArticles: [

                "LCSP-145",

                "LCSP-146"

            ],

            dependsOn: [

                "PROCEDURE"

            ],

            excludes: [],

            priority: 2,

            isVisible: () => true,

            shouldRender: () => true

        },

        {

            id: "SPECIAL_CONDITIONS",

            order: 12,

            title: "Condiciones especiales de ejecución",

            description:
                "Condiciones sociales, medioambientales o de innovación.",

            mandatory: false,

            editable: true,

            reusable: true,

            reusableKey: "SPECIAL_EXECUTION",

            legalArticles: [

                "LCSP-202"

            ],

            dependsOn: [],

            excludes: [],

            priority: 3,

            isVisible: (ctx) =>

                ctx.specialExecutionConditions.length > 0,

            shouldRender: (ctx) =>

                ctx.specialExecutionConditions.length > 0

        },

        {

            id: "CONCLUSIONS",

            order: 13,

            title: "Conclusiones",

            description:
                "Conclusión de la memoria justificativa.",

            mandatory: true,

            editable: true,

            reusable: false,

            legalArticles: [

                "LCSP-28",

                "LCSP-116"

            ],

            dependsOn: [],

            excludes: [],

            priority: 10,

            isVisible: () => true,

            shouldRender: () => true

        }

    ]

};
