import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";
import { canonicalSectionsAsDefinitions } from "../CanonicalMemoryPptStructure";

/**
 * Estructura lógica transversal de la Memoria. Las particularidades de familia
 * se añaden como overlays mediante CanonicalMemoryPptStructure y nunca cambian
 * la numeración de los epígrafes comunes.
 */
export const MemoryDefinition: DocumentDefinition = {
  id: "MEMORIA",
  type: DocumentType.MEMORY,
  title: "Memoria justificativa de la contratación",
  description: "Canon transversal de Contrata-IA para la justificación del expediente.",
  mandatory: true,
  order: 10,
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [],
  excludes: [],
  sections: canonicalSectionsAsDefinitions("MEMORY", "SUPPLY"),
};
