import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";

const visible = () => true;

export const ServicePcapDefinition: DocumentDefinition = {
  id: "PCAP_SERVICE_OPEN_ELECTRONIC_2025_12",
  type: DocumentType.PCAP,
  title: "Pliego de Cláusulas Administrativas Particulares - Servicios",
  description: "Estructura del modelo recomendado para contratos de servicios con presentación electrónica de ofertas.",
  mandatory: true,
  order: 20,
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  sections: [
    { id: "I_ELEMENTS", order: 1, title: "I. Elementos del contrato", description: "Régimen jurídico, objeto, presupuesto, crédito, plazo, capacidad, solvencia y perfil de contratante.", mandatory: true, editable: true, reusable: true, reusableKey: "CONTRACT_ELEMENTS", legalArticles: ["LCSP-28", "LCSP-99", "LCSP-100", "LCSP-101", "LCSP-116", "LCSP-122"], dependsOn: [], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "II_AWARD", order: 2, title: "II. Adjudicación del contrato", description: "Procedimiento, tramitación, presentación de proposiciones, mesa, valoración, clasificación, adjudicación y formalización.", mandatory: true, editable: true, reusable: true, reusableKey: "AWARD", legalArticles: ["LCSP-145", "LCSP-150", "LCSP-156"], dependsOn: ["I_ELEMENTS"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "III_EXECUTION", order: 3, title: "III. Ejecución del contrato", description: "Responsable, condiciones de ejecución, protección de datos, obligaciones, seguros, cesión, subcontratación, penalidades, recepción y pago.", mandatory: true, editable: true, reusable: true, reusableKey: "EXECUTION", legalArticles: ["LCSP-192", "LCSP-193", "LCSP-202", "LCSP-211"], dependsOn: ["II_AWARD"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "IV_PREROGATIVES", order: 4, title: "IV. Prerrogativas de la Administración", description: "Prerrogativas, suspensión, modificación y extinción.", mandatory: true, editable: true, reusable: true, reusableKey: "PREROGATIVES", legalArticles: ["LCSP-190", "LCSP-191", "LCSP-203"], dependsOn: ["III_EXECUTION"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "V_REMEDIES", order: 5, title: "V. Jurisdicción y recursos", description: "Recurso especial y demás recursos procedentes.", mandatory: true, editable: true, reusable: true, reusableKey: "REMEDIES", legalArticles: ["LCSP-44", "LCSP-50"], dependsOn: ["IV_PREROGATIVES"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "ANNEX_I", order: 6, title: "Anexo I. Características del contrato", description: "Datos parametrizables del expediente: objeto, CPV, lotes, presupuesto, valor estimado, duración, solvencia, criterios, garantías, modificación y demás características.", mandatory: true, editable: true, reusable: true, reusableKey: "PCAP_ANNEX_I", legalArticles: ["LCSP-99", "LCSP-100", "LCSP-101", "LCSP-122"], dependsOn: ["I_ELEMENTS"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "GENERAL_ANNEXES", order: 7, title: "Anexos generales", description: "DEUC/DRU, confidencialidad, UTE, proposición económica y declaraciones previas a la adjudicación y formalización.", mandatory: true, editable: true, reusable: false, legalArticles: ["LCSP-140", "LCSP-141", "LCSP-150"], dependsOn: ["ANNEX_I"], excludes: [], priority: 80, isVisible: visible, shouldRender: visible },
    { id: "SERVICE_ANNEXES", order: 8, title: "Anexos específicos de servicios", description: "Personal técnico y, cuando proceda, información sobre condiciones de subrogación.", mandatory: false, editable: true, reusable: false, legalArticles: ["LCSP-130", "LCSP-308"], dependsOn: ["ANNEX_I"], excludes: [], priority: 80, isVisible: visible, shouldRender: visible },
  ],
};
