import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";

const visible = () => true;

export const ServicePptDefinition: DocumentDefinition = {
  id: "PPT_SERVICE_CLEANING_STRUCTURAL",
  type: DocumentType.PPT,
  title: "Pliego de Prescripciones Técnicas - Servicios",
  description: "Estructura técnica contrastada con pliegos reales de servicios de limpieza del ámbito de Empleo de la Junta de Andalucía.",
  mandatory: true,
  order: 30,
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  sections: [
    { id: "OBJECT_SCOPE", order: 1, title: "Objeto y alcance técnico", description: "Objeto del PPT, centros o dependencias afectadas y alcance material de la prestación.", mandatory: true, editable: true, reusable: true, reusableKey: "TECHNICAL_OBJECT", legalArticles: ["LCSP-124", "LCSP-125"], dependsOn: [], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "SERVICE_REQUIREMENTS", order: 2, title: "Características y prestaciones del servicio", description: "Prestaciones mínimas, periodicidad, criterios de ejecución y tratamientos específicos.", mandatory: true, editable: true, reusable: true, reusableKey: "SERVICE_REQUIREMENTS", legalArticles: ["LCSP-124", "LCSP-126"], dependsOn: ["OBJECT_SCOPE"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "PERSONNEL_SCHEDULE", order: 3, title: "Personal, organización y horarios", description: "Medios personales, funciones, dedicación, organización y horarios de prestación.", mandatory: false, editable: true, reusable: true, reusableKey: "PERSONNEL", legalArticles: ["LCSP-124"], dependsOn: ["SERVICE_REQUIREMENTS"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "MATERIALS", order: 4, title: "Medios materiales y consumibles", description: "Productos, materiales, equipos y consumibles necesarios para la ejecución.", mandatory: false, editable: true, reusable: true, reusableKey: "MATERIALS", legalArticles: ["LCSP-124", "LCSP-126"], dependsOn: ["SERVICE_REQUIREMENTS"], excludes: [], priority: 80, isVisible: visible, shouldRender: visible },
    { id: "QUALITY_CONTROL", order: 5, title: "Control de calidad y seguimiento", description: "Mecanismos de comprobación de la correcta prestación y coordinación con la Administración.", mandatory: true, editable: true, reusable: true, reusableKey: "QUALITY_CONTROL", legalArticles: ["LCSP-62", "LCSP-311"], dependsOn: ["SERVICE_REQUIREMENTS"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "EXECUTION_METHOD", order: 6, title: "Forma de ejecución del servicio", description: "Reglas operativas de ejecución y coordinación técnica.", mandatory: true, editable: true, reusable: true, reusableKey: "EXECUTION_METHOD", legalArticles: ["LCSP-124"], dependsOn: ["SERVICE_REQUIREMENTS"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "SUBROGATION", order: 7, title: "Subrogación de personal", description: "Información técnica vinculada a subrogación cuando resulte exigible por norma, convenio o acuerdo de eficacia general.", mandatory: false, editable: true, reusable: true, reusableKey: "SUBROGATION", legalArticles: ["LCSP-130"], dependsOn: ["PERSONNEL_SCHEDULE"], excludes: [], priority: 80, isVisible: visible, shouldRender: visible },
    { id: "ANNEXES", order: 8, title: "Anexos técnicos", description: "Relación de centros, superficies, personal u otros datos técnicos del servicio.", mandatory: false, editable: true, reusable: false, legalArticles: ["LCSP-124"], dependsOn: ["OBJECT_SCOPE"], excludes: [], priority: 70, isVisible: visible, shouldRender: visible },
  ],
};
