import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";
import { canonicalSectionsAsDefinitions } from "../CanonicalMemoryPptStructure";

export const ServicePptDefinition: DocumentDefinition = {
  id: "PPT_SERVICE_CLEANING_STRUCTURAL",
  type: DocumentType.PPT,
  title: "Pliego de Prescripciones Técnicas - Servicios",
  description: "Estructura técnica contrastada con pliegos reales de servicios de limpieza del ámbito de Empleo de la Junta de Andalucía.",
  mandatory: true,
  order: 30,
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  sections: canonicalSectionsAsDefinitions("PPT","SERVICE"),
};
