import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";

const visible = () => true;

export const SupplyPcapFullModelDefinition: DocumentDefinition = {
  id: "PCAP_SUPPLY_ASA_JDA_2025_12_FULL",
  type: DocumentType.PCAP,
  title: "PCAP oficial de suministro - abierto simplificado abreviado",
  description: "Modelo completo recomendado por la Comisión Consultiva de Contratación Pública de la Junta de Andalucía, presentación electrónica y autofinanciación, actualización diciembre de 2025.",
  mandatory: true,
  order: 20,
  sections: [
    { id: "GENERAL_CLAUSES", order: 1, title: "Cláusulas generales", description: "Régimen jurídico, objeto, presupuesto, procedimiento, adjudicación, formalización, ejecución y extinción conforme al modelo oficial.", mandatory: true, editable: false, reusable: false, legalArticles: [], dependsOn: [], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "ANNEX_I", order: 2, title: "Anexo I. Características del contrato", description: "Parte parametrizable del modelo oficial con los datos validados del expediente.", mandatory: true, editable: true, reusable: true, reusableKey: "SUPPLY_ANNEX_I", legalArticles: ["LCSP-99", "LCSP-100", "LCSP-101", "LCSP-102", "LCSP-159.6"], dependsOn: ["GENERAL_CLAUSES"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "BIDDER_ANNEXES", order: 3, title: "Anexos de licitación y adjudicación", description: "Declaraciones, proposición, UTE, registros, incompatibilidades, igualdad, discapacidad, menores y restantes anexos del modelo oficial.", mandatory: true, editable: true, reusable: false, legalArticles: [], dependsOn: ["ANNEX_I"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "CONFIDENTIALITY_AND_DATA", order: 4, title: "Confidencialidad y protección de datos", description: "Anexos y cláusulas del modelo oficial aplicables a confidencialidad y tratamiento de datos.", mandatory: true, editable: true, reusable: false, legalArticles: [], dependsOn: ["GENERAL_CLAUSES"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
  ],
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
};
