import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";

const visible = () => true;

export const SupplyPptDefinition: DocumentDefinition = {
  id: "PPT_SUPPLY_NEEDS_HARDWARE_2026",
  type: DocumentType.PPT,
  title: "Pliego de Prescripciones Técnicas - Suministros",
  description: "Estructura técnica contrastada con el PPT de suministro sucesivo de materiales de ferretería del SAE.",
  mandatory: true,
  order: 30,
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  sections: [
    { id: "OBJECT", order: 1, title: "Objeto del pliego de prescripciones técnicas", description: "Objeto técnico del suministro y alcance de los bienes a entregar.", mandatory: true, editable: true, reusable: true, reusableKey: "TECHNICAL_OBJECT", legalArticles: ["LCSP-124", "LCSP-125"], dependsOn: [], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "MANAGING_UNIT", order: 2, title: "Unidad gestora y responsable del contrato", description: "Unidad gestora y dirección de la ejecución mediante la persona responsable del contrato.", mandatory: true, editable: true, reusable: true, reusableKey: "MANAGING_UNIT", legalArticles: ["LCSP-62"], dependsOn: [], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "TERM", order: 3, title: "Plazo de ejecución", description: "Duración, inicio y prórrogas vinculadas al régimen administrativo del expediente.", mandatory: true, editable: true, reusable: true, reusableKey: "DURATION", legalArticles: ["LCSP-29"], dependsOn: [], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "MATERIAL_DESCRIPTION", order: 4, title: "Descripción de los materiales objeto del contrato", description: "Relación de artículos, especificaciones, unidades y cantidades estimadas.", mandatory: true, editable: true, reusable: true, reusableKey: "SUPPLY_ITEMS", legalArticles: ["LCSP-124", "LCSP-126"], dependsOn: ["OBJECT"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "EQUIVALENCE_QUALITY", order: 5, title: "Equivalencias, calidad y documentación técnica", description: "Tratamiento de referencias a marcas/modelos, equivalencias, calidad mínima, fichas técnicas y de seguridad.", mandatory: true, editable: true, reusable: true, reusableKey: "QUALITY_EQUIVALENCE", legalArticles: ["LCSP-126"], dependsOn: ["MATERIAL_DESCRIPTION"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "ESTIMATED_CONSUMPTION", order: 6, title: "Consumo estimado y unidades", description: "Cantidades orientativas derivadas del consumo histórico, sin obligación de agotamiento y sujetas al presupuesto máximo cuando proceda.", mandatory: true, editable: true, reusable: true, reusableKey: "ESTIMATED_CONSUMPTION", legalArticles: ["LCSP-DA33"], dependsOn: ["MATERIAL_DESCRIPTION"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "DEFECTIVE_GOODS", order: 7, title: "Reposición de materiales defectuosos", description: "Obligación de reponer o sustituir mercancía defectuosa imputable a las características de los materiales entregados.", mandatory: true, editable: true, reusable: true, reusableKey: "DEFECTIVE_GOODS", legalArticles: ["LCSP-300"], dependsOn: ["MATERIAL_DESCRIPTION"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "DELIVERY", order: 8, title: "Condiciones de pedido y entrega", description: "Forma de pedido, lugares, plazos y condiciones técnicas de entrega.", mandatory: true, editable: true, reusable: true, reusableKey: "DELIVERY", legalArticles: ["LCSP-300"], dependsOn: ["MATERIAL_DESCRIPTION"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "ANNEX_ITEMS", order: 9, title: "Anexo técnico de artículos", description: "Tabla o catálogo de referencias, unidades, consumos estimados y especificaciones técnicas.", mandatory: true, editable: true, reusable: false, legalArticles: ["LCSP-124", "LCSP-126"], dependsOn: ["MATERIAL_DESCRIPTION"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
  ],
};
