import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";

const visible = () => true;

export const SupplyPcapAnnexDefinition: DocumentDefinition = {
  id: "PCAP_SUPPLY_ANNEX_I_JDA_2025_12",
  type: DocumentType.PCAP,
  title: "Anexo I del DPCAF / PCAP - Suministros",
  description: "Estructura acreditada del Anexo I parametrizable para suministros en función de las necesidades. No representa por sí sola el clausulado general completo.",
  mandatory: true,
  order: 20,
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  sections: [
    { id: "OBJECT_CPV_LOTS_NEEDS", order: 1, title: "Objeto, CPV, lotes y contrato en función de las necesidades", description: "Objeto, clasificación CPV, lotes y, cuando proceda, régimen de suministro por necesidades.", mandatory: true, editable: true, reusable: true, reusableKey: "OBJECT_CPV_LOTS", legalArticles: ["LCSP-99", "LCSP-DA33"], dependsOn: [], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "BUDGET_EV_PRICE", order: 2, title: "Presupuesto base, valor estimado y precio", description: "PBL, presupuesto máximo cuando proceda, IVA, valor estimado, sistema de determinación del precio, aplicación presupuestaria y anualidades.", mandatory: true, editable: true, reusable: true, reusableKey: "ECONOMICS", legalArticles: ["LCSP-100", "LCSP-101", "LCSP-102", "LCSP-DA33"], dependsOn: ["OBJECT_CPV_LOTS_NEEDS"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "DURATION_EXTENSIONS", order: 3, title: "Duración y prórrogas", description: "Duración inicial y prórrogas, preservando separadamente el presupuesto máximo aprobado cuando sea aplicable.", mandatory: true, editable: true, reusable: true, reusableKey: "DURATION", legalArticles: ["LCSP-29"], dependsOn: ["BUDGET_EV_PRICE"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "AWARD_CRITERIA", order: 4, title: "Criterios de adjudicación, anormalidad y desempate", description: "Criterios, fórmulas o parámetros, ofertas anormalmente bajas y reglas de desempate.", mandatory: true, editable: true, reusable: true, reusableKey: "AWARD_CRITERIA", legalArticles: ["LCSP-145", "LCSP-147", "LCSP-149"], dependsOn: ["OBJECT_CPV_LOTS_NEEDS"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "SPECIAL_EXECUTION", order: 5, title: "Condición especial de ejecución", description: "Condiciones especiales de ejecución vinculadas al objeto y verificables.", mandatory: true, editable: true, reusable: true, reusableKey: "SPECIAL_EXECUTION", legalArticles: ["LCSP-202"], dependsOn: [], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "PENALTIES", order: 6, title: "Penalidades específicas", description: "Penalidades específicas cuando procedan, sin sustituir el régimen legal general.", mandatory: false, editable: true, reusable: true, reusableKey: "PENALTIES", legalArticles: ["LCSP-192", "LCSP-193"], dependsOn: [], excludes: [], priority: 80, isVisible: visible, shouldRender: visible },
    { id: "PLANNED_MODIFICATION", order: 7, title: "Modificación prevista", description: "Régimen y límites de la modificación prevista cuando esté definida en el expediente.", mandatory: false, editable: true, reusable: true, reusableKey: "MODIFICATION", legalArticles: ["LCSP-204", "LCSP-DA33"], dependsOn: ["BUDGET_EV_PRICE"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "DELIVERY", order: 8, title: "Condiciones de entrega", description: "Plazos y condiciones operativas de entrega configuradas como ejecución cuando corresponda.", mandatory: true, editable: true, reusable: true, reusableKey: "DELIVERY", legalArticles: ["LCSP-300"], dependsOn: [], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
  ],
};
