import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";
import { canonicalSectionsAsDefinitions } from "../CanonicalMemoryPptStructure";

export const SupplyPptDefinition: DocumentDefinition = {
  id: "PPT_SUPPLY_NEEDS_HARDWARE_2026",
  type: DocumentType.PPT,
  title: "Pliego de Prescripciones Técnicas - Suministros",
  description: "Estructura técnica contrastada con el PPT de suministro sucesivo de materiales de ferretería del SAE.",
  mandatory: true,
  order: 30,
  autoGenerated: true,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  sections: canonicalSectionsAsDefinitions("PPT","SUPPLY",["SUCCESSIVE_NEEDS_CATALOGUE"]),
};
