import { DocumentDefinition } from "../DocumentDefinition";
import { DocumentType } from "../DocumentType";

const visible = () => true;

/**
 * Estructura de PCAP de obras contrastable con un modelo real recuperado.
 * No contiene cláusulas ni texto fuente y no habilita por sí sola generación física.
 */
export const WorksPcapDefinition: DocumentDefinition = {
  id: "PCAP_WORKS_OPEN_STRUCTURAL",
  type: DocumentType.PCAP,
  title: "Pliego de Cláusulas Administrativas Particulares - Obras",
  description: "Estructura administrativa de obras con guardas específicas de proyecto, replanteo, clasificación, ejecución, certificaciones y recepción.",
  mandatory: true,
  order: 20,
  autoGenerated: false,
  editable: true,
  requiresSignature: true,
  includedInExpediente: true,
  dependsOn: [DocumentType.MEMORY],
  excludes: [],
  sections: [
    { id: "I_WORKS_ELEMENTS", order: 1, title: "I. Elementos del contrato de obras", description: "Objeto, proyecto aprobado, CPV, lotes, PBL, VE, crédito, plazo, clasificación/solvencia y perfil.", mandatory: true, editable: true, reusable: true, reusableKey: "WORKS_CONTRACT_ELEMENTS", legalArticles: ["LCSP-13", "LCSP-99", "LCSP-100", "LCSP-101", "LCSP-116", "LCSP-122", "LCSP-231"], dependsOn: [], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "II_WORKS_AWARD", order: 2, title: "II. Adjudicación", description: "Procedimiento, presentación y evaluación de ofertas, clasificación, adjudicación y formalización.", mandatory: true, editable: true, reusable: true, reusableKey: "AWARD", legalArticles: ["LCSP-145", "LCSP-146", "LCSP-150", "LCSP-156", "LCSP-159"], dependsOn: ["I_WORKS_ELEMENTS"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "III_WORKS_EXECUTION", order: 3, title: "III. Ejecución de las obras", description: "Comprobación del replanteo, dirección facultativa, programa, certificaciones, obligaciones, condiciones especiales, penalidades y subcontratación.", mandatory: true, editable: true, reusable: true, reusableKey: "WORKS_EXECUTION", legalArticles: ["LCSP-192", "LCSP-202", "LCSP-237", "LCSP-238", "LCSP-240"], dependsOn: ["II_WORKS_AWARD"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "IV_WORKS_MODIFICATION", order: 4, title: "IV. Modificación, suspensión y prerrogativas", description: "Modificación del contrato y del proyecto, suspensión y prerrogativas administrativas.", mandatory: true, editable: true, reusable: true, reusableKey: "WORKS_MODIFICATION", legalArticles: ["LCSP-190", "LCSP-203", "LCSP-204", "LCSP-205", "LCSP-242"], dependsOn: ["III_WORKS_EXECUTION"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "V_WORKS_RECEIPT", order: 5, title: "V. Recepción, garantía y liquidación", description: "Recepción, medición general, certificación final, plazo de garantía, liquidación y vicios ocultos.", mandatory: true, editable: true, reusable: true, reusableKey: "WORKS_CLOSEOUT", legalArticles: ["LCSP-243", "LCSP-244"], dependsOn: ["IV_WORKS_MODIFICATION"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
    { id: "VI_WORKS_REMEDIES", order: 6, title: "VI. Jurisdicción y recursos", description: "Régimen de recursos procedente según valor, acto y naturaleza del poder adjudicador.", mandatory: true, editable: true, reusable: true, reusableKey: "REMEDIES", legalArticles: ["LCSP-44", "LCSP-50"], dependsOn: ["V_WORKS_RECEIPT"], excludes: [], priority: 90, isVisible: visible, shouldRender: visible },
    { id: "WORKS_ANNEX_I", order: 7, title: "Anexo I. Características del contrato", description: "Datos parametrizables del expediente de obras, incluido proyecto, presupuesto, clasificación, plazo, criterios, garantías y modificación.", mandatory: true, editable: true, reusable: true, reusableKey: "PCAP_ANNEX_I_WORKS", legalArticles: ["LCSP-13", "LCSP-99", "LCSP-100", "LCSP-101", "LCSP-122", "LCSP-231"], dependsOn: ["I_WORKS_ELEMENTS"], excludes: [], priority: 100, isVisible: visible, shouldRender: visible },
  ],
};
