export const LB102_PILOT_ACCEPTANCE_UI = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Contrata-IA · Piloto LB102</title>
<style>
body{font-family:Arial,sans-serif;max-width:1100px;margin:32px auto;padding:0 16px;color:#202124}h1{margin-bottom:6px}.muted{color:#666}.card{border:1px solid #ddd;border-radius:10px;padding:18px;margin:16px 0}.packages{display:grid;grid-template-columns:1fr 1fr;gap:16px}.pkg{border:1px solid #ddd;border-radius:10px;padding:15px}label{display:block;font-weight:600;margin:10px 0 4px}input,textarea,button{font:inherit;padding:10px;box-sizing:border-box}input,textarea{width:100%}textarea{min-height:70px}button{cursor:pointer;margin:8px 6px 0 0}.ok{color:#137333}.bad{color:#b3261e}pre{white-space:pre-wrap;background:#f7f7f7;padding:12px;border-radius:8px}.sha{font-family:monospace;word-break:break-all;font-size:12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.login-actions{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.hidden{display:none}@media(max-width:760px){.packages,.row{grid-template-columns:1fr}}
</style></head><body>
<h1>Contrata-IA · aceptación funcional LB102</h1><p class="muted">Prepiloto técnico acreditado. Cada revisión queda ligada al ZIP generado por el servidor. La aceptación del piloto no implica producción institucional.</p>
<section class="card"><h2>1. Acceso</h2><div class="row"><div><label for="username">Usuario</label><input id="username" autocomplete="username" placeholder="usuario-piloto-1"></div><div><label for="password">Contraseña</label><input id="password" type="password" autocomplete="current-password"></div></div><div class="login-actions"><button id="loginButton" type="button">Entrar</button><button id="logoutButton" type="button">Salir</button><span class="muted">La sesión se recuerda durante 7 días en este navegador.</span></div><p id="me" class="muted">No autenticado.</p></section>
<section class="card"><h2>2. Sesión de aceptación</h2><button id="sessionButton" type="button">Registrar esta sesión</button><button id="statusButton" type="button">Actualizar estado</button><pre id="status">Sin consultar.</pre></section>
<section class="card" id="sourcesCard"><h2>2.A. Fuentes físicas Ferretería</h2><p class="muted">Solo ADMIN. Carga única de los ODT fuente exactos del expediente CONTR/2026/240267. El servidor comprueba SHA-256 y huella de estilo antes de persistirlos.</p><div class="row"><div><label for="memorySource">Memoria V12 letrado (.odt)</label><input id="memorySource" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="uploadMemoryButton" type="button">Validar y guardar Memoria</button></div><div><label for="pptSource">PPT V6 (.odt)</label><input id="pptSource" type="file" accept=".odt,application/vnd.oasis.opendocument.text"><button id="uploadPptButton" type="button">Validar y guardar PPT</button></div></div><button id="sourceStatusButton" type="button">Comprobar fuentes Ferretería</button><pre id="sourceStatus">Sin comprobar.</pre></section>
<section class="card"><h2>3. Cuatro expedientes reales</h2><p class="muted">Descarga y abre cada ZIP. Revisa Memoria, PCAP y PPT. Solo después registra el resultado. El SHA lo calcula Contrata-IA.</p><div id="packages" class="packages"></div></section>
<section class="card" id="decisionCard"><h2>4. Decisión final</h2><p class="muted">Solo ADMIN. Deben existir 2 sesiones, 2 usuarios distintos, 4 paquetes revisados y 0 defectos críticos abiertos.</p><label for="rationale">Motivación</label><textarea id="rationale" placeholder="Motivación de la aceptación o rechazo funcional"></textarea><button id="acceptDecisionButton" type="button">Aceptar piloto</button><button id="rejectDecisionButton" type="button">Rechazar / mantener abierto</button><pre id="decisionResult"></pre></section>
<script>
async function requestJson(url,options){const c=options||{};const r=await fetch(url,{credentials:"same-origin",headers:{"content-type":"application/json",...(c.headers||{})},...c});const t=await r.text();let v;try{v=JSON.parse(t)}catch{v={raw:t}}if(!r.ok){const b=Array.isArray(v.blockers)?v.blockers.join(" · "):"";throw new Error(v.error||b||JSON.stringify(v))}return v}
function setText(id,text,cls){const e=document.getElementById(id);if(!e)return;e.textContent=text;if(cls)e.className=cls}
function applyRole(role){document.getElementById("sourcesCard").classList.toggle("hidden",role!=="ADMIN");document.getElementById("decisionCard").classList.toggle("hidden",role!=="ADMIN")}
function showActor(a){setText("me","Autenticado: "+(a.displayName||a.id)+" · "+a.role,"ok");applyRole(a.role)}
async function login(){try{const u=document.getElementById("username"),p=document.getElementById("password");const username=u.value.trim(),password=p.value;if(!username||!password)throw new Error("Introduce usuario y contraseña.");const envelope="LOGIN:"+encodeURIComponent(username)+":"+encodeURIComponent(password);const v=await requestJson("/api/lb102/session/login",{method:"POST",body:JSON.stringify({token:envelope})});p.value="";showActor(v.actor);await loadPackages();await refreshStatus();if(v.actor.role==="ADMIN")await refreshSourceStatus()}catch(e){setText("me","Error: "+e.message,"bad")}}
async function logout(){try{await requestJson("/api/lb102/session/logout",{method:"POST",body:"{}"});setText("me","No autenticado.","muted");document.getElementById("password").value="";document.getElementById("packages").replaceChildren();applyRole("VIEWER")}catch(e){setText("me","Error: "+e.message,"bad")}}
async function recordSession(){try{await requestJson("/api/lb102/acceptance/sessions",{method:"POST",body:"{}"});await refreshStatus()}catch(e){setText("status","Error: "+e.message,"bad")}}
async function refreshStatus(){try{const v=await requestJson("/api/lb102/acceptance/status");setText("status",JSON.stringify(v,null,2))}catch(e){setText("status","Error: "+e.message,"bad")}}
async function uploadSource(kind,inputId){const input=document.getElementById(inputId),file=input.files&&input.files[0];if(!file){setText("sourceStatus","Selecciona primero el archivo ODT.","bad");return}try{setText("sourceStatus","Validando "+file.name+"...","muted");const r=await fetch("/api/lb102/ferreteria-sources/"+kind,{method:"PUT",credentials:"same-origin",headers:{"content-type":"application/vnd.oasis.opendocument.text"},body:file});const t=await r.text();let v;try{v=JSON.parse(t)}catch{v={raw:t}}if(!r.ok)throw new Error(v.error||JSON.stringify(v));setText("sourceStatus","Guardado "+v.kind+" · SHA-256 "+v.sha256,"ok");input.value="";await refreshSourceStatus()}catch(e){setText("sourceStatus","Error: "+e.message,"bad")}}
async function refreshSourceStatus(){try{const v=await requestJson("/api/lb102/ferreteria-sources");const lines=v.assets.map(x=>(x.available?"OK ":"FALTA ")+x.kind+" · "+x.templateId+(x.sha256?" · "+x.sha256:""));setText("sourceStatus",(v.ready?"Fuentes protegidas listas.\\n":"Fuentes protegidas incompletas.\\n")+lines.join("\\n"),v.ready?"ok":"bad")}catch(e){setText("sourceStatus","Error: "+e.message,"bad")}}
function field(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
function createPackageCard(pkg){const a=document.createElement("article");a.className="pkg";a.id="pkg-"+pkg.id;a.appendChild(field("h3",pkg.label));a.appendChild(field("p","Expediente: "+pkg.caseId+" · Familia: "+pkg.family+" · Perfil: "+pkg.profile));const d=field("button","Generar y descargar ZIP");d.type="button";a.appendChild(d);const s=field("p","SHA pendiente de generación.");s.className="sha muted";a.appendChild(s);const al=document.createElement("label"),accepted=document.createElement("input");accepted.type="checkbox";accepted.checked=true;accepted.style.width="auto";al.appendChild(accepted);al.appendChild(document.createTextNode(" Documentación aceptable para piloto"));a.appendChild(al);a.appendChild(field("label","Defectos críticos abiertos"));const critical=document.createElement("input");critical.type="number";critical.min="0";critical.value="0";a.appendChild(critical);a.appendChild(field("label","Observaciones de revisión"));const notes=document.createElement("textarea");a.appendChild(notes);const review=field("button","Registrar revisión de este paquete");review.type="button";a.appendChild(review);const result=document.createElement("pre");a.appendChild(result);
d.addEventListener("click",async()=>{try{s.textContent="Generando paquete...";s.className="sha muted";const r=await fetch("/api/lb102/pilot-packages/"+encodeURIComponent(pkg.id)+"/download",{credentials:"same-origin"});if(!r.ok){const v=await r.json();throw new Error((v.blockers||[]).join(" · ")||v.error||"No se pudo generar el paquete")}const hash=r.headers.get("x-contrata-ia-package-sha256")||"SHA no disponible",blob=await r.blob(),disp=r.headers.get("content-disposition")||"",m=/filename="([^"]+)"/.exec(disp),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=m?m[1]:pkg.id+".zip";document.body.appendChild(link);link.click();const href=link.href;link.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);s.textContent="SHA-256 generado por servidor: "+hash;s.className="sha ok"}catch(e){s.textContent="Error: "+e.message;s.className="sha bad"}});
review.addEventListener("click",async()=>{try{const body={accepted:accepted.checked,criticalDefectsOpen:Number(critical.value||0),notes:notes.value},v=await requestJson("/api/lb102/pilot-packages/"+encodeURIComponent(pkg.id)+"/review",{method:"POST",body:JSON.stringify(body)});result.textContent="Revisión registrada. SHA servidor: "+v.package.sha256;result.className="ok";s.textContent="SHA-256 registrado: "+v.package.sha256;s.className="sha ok";await refreshStatus()}catch(e){result.textContent="Error: "+e.message;result.className="bad"}});return a}
async function loadPackages(){const c=document.getElementById("packages");c.replaceChildren();try{const v=await requestJson("/api/lb102/pilot-packages");for(const p of v.packages)c.appendChild(createPackageCard(p))}catch(e){const p=field("p","Error: "+e.message);p.className="bad";c.appendChild(p)}}
async function decision(accepted){try{const rationale=document.getElementById("rationale").value,v=await requestJson("/api/lb102/acceptance/decision",{method:"POST",body:JSON.stringify({accepted,rationale})});setText("decisionResult",JSON.stringify(v,null,2));await refreshStatus()}catch(e){setText("decisionResult","Error: "+e.message,"bad")}}
document.getElementById("loginButton").addEventListener("click",login);document.getElementById("password").addEventListener("keydown",e=>{if(e.key==="Enter")login()});document.getElementById("logoutButton").addEventListener("click",logout);document.getElementById("sessionButton").addEventListener("click",recordSession);document.getElementById("statusButton").addEventListener("click",refreshStatus);document.getElementById("uploadMemoryButton").addEventListener("click",()=>uploadSource("memoria","memorySource"));document.getElementById("uploadPptButton").addEventListener("click",()=>uploadSource("ppt","pptSource"));document.getElementById("sourceStatusButton").addEventListener("click",refreshSourceStatus);document.getElementById("acceptDecisionButton").addEventListener("click",()=>decision(true));document.getElementById("rejectDecisionButton").addEventListener("click",()=>decision(false));applyRole("VIEWER");(async()=>{try{const v=await requestJson("/api/lb102/session/me");showActor(v.actor);await loadPackages();await refreshStatus();if(v.actor.role==="ADMIN")await refreshSourceStatus()}catch{}})();
</script></body></html>`;
