export const LB102_PILOT_ACCEPTANCE_UI = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Contrata-IA · Piloto LB102</title>
<style>body{font-family:Arial,sans-serif;max-width:1100px;margin:32px auto;padding:0 16px;color:#202124}h1{margin-bottom:6px}.muted{color:#666}.card{border:1px solid #ddd;border-radius:10px;padding:18px;margin:16px 0}.packages{display:grid;grid-template-columns:1fr 1fr;gap:16px}.pkg{border:1px solid #ddd;border-radius:10px;padding:15px}label{display:block;font-weight:600;margin:10px 0 4px}input,textarea,button{font:inherit;padding:10px;box-sizing:border-box}input,textarea{width:100%}textarea{min-height:70px}button{cursor:pointer;margin:8px 6px 0 0}button:disabled{cursor:wait;opacity:.65}.ok{color:#137333}.bad{color:#b3261e}.info{color:#174ea6}.feedback{font-weight:600;margin:10px 0 0}pre{white-space:pre-wrap;background:#f7f7f7;padding:12px;border-radius:8px}.sha{font-family:monospace;word-break:break-all;font-size:12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.hidden{display:none}@media(max-width:760px){.packages,.row{grid-template-columns:1fr}}</style></head><body>
<h1>Contrata-IA · aceptación funcional LB102</h1><p class="muted">Prepiloto técnico. Cada expediente se genera como una tríada atómica PCAP + Memoria + PPT ligada a un único snapshot. La aceptación funcional no implica producción institucional.</p>
<section class="card"><h2>1. Acceso</h2><div class="row"><div><label for="username">Usuario</label><input id="username" autocomplete="username" placeholder="usuario-piloto-1"></div><div><label for="password">Contraseña</label><input id="password" type="password" autocomplete="current-password"></div></div><button id="loginButton">Entrar</button><button id="logoutButton">Salir</button><p id="me" class="muted">No autenticado.</p></section>
<section class="card"><h2>2. Preparación técnica</h2><p>La UAT solo debe comenzar cuando los cuatro grupos físicos estén disponibles. Ferretería usa exclusivamente la tríada post-Intervención validada: <strong>PCAP V8 + Memoria V14 + PPT V8</strong>, anualidad 2026 <strong>1.596,06 €</strong> y valor estimado <strong>25.325,86 €</strong>.</p><button id="sourceStatusButton">Comprobar cuatro grupos</button><a href="/lb102-source-ingress" style="margin-left:8px">Abrir ingreso protegido</a><p id="sourceFeedback" class="feedback muted"></p><pre id="sourceStatus">Sin comprobar.</pre></section>
<section class="card"><h2>3. Sesión de aceptación humana</h2><p class="muted">No registres esta sesión hasta terminar la fase técnica pre-UAT. Para la aceptación final se exigen dos sesiones reales de dos usuarios distintos.</p><button id="sessionButton">Registrar esta sesión</button><button id="statusButton">Actualizar estado</button><p id="sessionFeedback" class="feedback muted">Sin acciones pendientes.</p><pre id="status">Sin consultar.</pre></section>
<section class="card"><h2>4. Cuatro expedientes reales</h2><p class="muted">Generar y descargar ZIP produce en servidor un único paquete atómico por expediente. Revisa los tres ODT conjuntamente antes de registrar una revisión humana.</p><div id="packages" class="packages"></div></section>
<section class="card hidden" id="decisionCard"><h2>5. Decisión final</h2><p class="muted">Solo ADMIN. Requiere 2 sesiones, 2 usuarios distintos, 4 paquetes revisados y 0 defectos críticos abiertos.</p><label for="rationale">Motivación</label><textarea id="rationale"></textarea><button id="acceptDecisionButton">Aceptar piloto</button><button id="rejectDecisionButton">Rechazar / mantener abierto</button><pre id="decisionResult"></pre></section>
<script>
async function requestJson(url,options){const c=options||{};const r=await fetch(url,{credentials:"same-origin",headers:{"content-type":"application/json",...(c.headers||{})},...c});const t=await r.text();let v;try{v=JSON.parse(t)}catch{v={raw:t}}if(!r.ok){const b=Array.isArray(v.blockers)?v.blockers.join(" · "):"";throw new Error(v.error||b||JSON.stringify(v))}return v}
function setText(id,text,cls){const e=document.getElementById(id);if(!e)return;e.textContent=text;if(cls)e.className=cls}
function busy(id,value){const e=document.getElementById(id);if(e)e.disabled=value}
function applyRole(role){document.getElementById("decisionCard").classList.toggle("hidden",role!=="ADMIN")}
function showActor(a){setText("me","Autenticado: "+(a.displayName||a.id)+" · "+a.role,"ok");applyRole(a.role)}
async function login(){busy("loginButton",true);setText("me","Autenticando...","info");try{const u=document.getElementById("username");const p=document.getElementById("password");const username=u.value.trim();const password=p.value;if(!username||!password)throw new Error("Introduce usuario y contraseña.");const envelope="LOGIN:"+encodeURIComponent(username)+":"+encodeURIComponent(password);const v=await requestJson("/api/lb102/session/login",{method:"POST",body:JSON.stringify({token:envelope})});p.value="";showActor(v.actor);await refreshSourceStatus();await loadPackages();await refreshStatus(false)}catch(e){setText("me","Error: "+e.message,"bad")}finally{busy("loginButton",false)}}
async function logout(){try{await requestJson("/api/lb102/session/logout",{method:"POST",body:"{}"});setText("me","Sesión cerrada correctamente.","ok");document.getElementById("packages").replaceChildren();applyRole("VIEWER")}catch(e){setText("me","Error: "+e.message,"bad")}}
async function refreshSourceStatus(){busy("sourceStatusButton",true);setText("sourceFeedback","Comprobando fuentes físicas...","feedback info");try{const v=await requestJson("/api/lb102/source-assets");const lines=v.groups.map(function(g){return(g.ready?"OK ":"BLOQUEADO ")+g.group+" · "+g.assets.filter(function(a){return a.available}).length+"/"+g.assets.length+" activos"+(g.blockers.length?" · "+g.blockers.join(" · "):"")});const ready=v.groups.length===4&&v.groups.every(function(g){return g.ready});const nl=String.fromCharCode(10);setText("sourceStatus",(ready?"CUATRO GRUPOS FÍSICOS LISTOS.":"FUENTES FÍSICAS INCOMPLETAS.")+nl+lines.join(nl),ready?"ok":"bad");setText("sourceFeedback",ready?"Comprobación completada correctamente.":"Comprobación completada con bloqueos.",ready?"feedback ok":"feedback bad")}catch(e){setText("sourceStatus","Error: "+e.message,"bad");setText("sourceFeedback","No se pudo completar la comprobación.","feedback bad")}finally{busy("sourceStatusButton",false)}}
async function recordSession(){busy("sessionButton",true);busy("statusButton",true);setText("sessionFeedback","Registrando sesión humana...","feedback info");try{const v=await requestJson("/api/lb102/acceptance/sessions",{method:"POST",body:"{}"});setText("sessionFeedback","Sesión registrada correctamente · "+(v.id||"evidencia persistida"),"feedback ok");await refreshStatus(true)}catch(e){setText("sessionFeedback","Error al registrar la sesión: "+e.message,"feedback bad");setText("status","Error: "+e.message,"bad")}finally{busy("sessionButton",false);busy("statusButton",false)}}
async function refreshStatus(fromSession){busy("statusButton",true);if(!fromSession)setText("sessionFeedback","Actualizando estado LB102...","feedback info");try{const v=await requestJson("/api/lb102/acceptance/status");setText("status",JSON.stringify(v,null,2));if(!fromSession){const e=v.evidence||{};setText("sessionFeedback","Estado actualizado · sesiones: "+String(e.userAcceptanceSessions??0)+" · usuarios distintos: "+String(e.distinctPilotUsers??0)+" · expedientes revisados: "+String(e.generatedPackagesHumanReviewed??0),"feedback ok")}}catch(e){setText("status","Error: "+e.message,"bad");setText("sessionFeedback","Error al actualizar estado: "+e.message,"feedback bad")}finally{busy("statusButton",false)}}
function field(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
function createPackageCard(pkg){const a=document.createElement("article");a.className="pkg";a.appendChild(field("h3",pkg.label));a.appendChild(field("p","Expediente: "+pkg.caseId+" · "+pkg.family+" · "+pkg.profile));const d=field("button","Generar y descargar ZIP");const s=field("p","SHA pendiente de generación.");s.className="sha muted";a.appendChild(d);a.appendChild(s);const al=document.createElement("label");const accepted=document.createElement("input");accepted.type="checkbox";accepted.checked=true;accepted.style.width="auto";al.appendChild(accepted);al.appendChild(document.createTextNode(" Documentación aceptable para piloto"));a.appendChild(al);a.appendChild(field("label","Defectos críticos abiertos"));const critical=document.createElement("input");critical.type="number";critical.min="0";critical.value="0";a.appendChild(critical);a.appendChild(field("label","Observaciones de revisión"));const notes=document.createElement("textarea");a.appendChild(notes);const review=field("button","Registrar revisión de este paquete");const result=document.createElement("pre");a.appendChild(review);a.appendChild(result);d.onclick=async function(){d.disabled=true;try{s.textContent="Generando paquete...";s.className="sha info";const r=await fetch("/api/lb102/pilot-packages/"+encodeURIComponent(pkg.id)+"/download",{credentials:"same-origin"});if(!r.ok){const v=await r.json();throw new Error((v.blockers||[]).join(" · ")||v.error||"No se pudo generar el paquete")}const hash=r.headers.get("x-contrata-ia-package-sha256")||"SHA no disponible";const blob=await r.blob();const disp=r.headers.get("content-disposition")||"";const marker='filename="';const start=disp.indexOf(marker);let fileName=pkg.id+".zip";if(start>=0){const rest=disp.slice(start+marker.length);const end=rest.indexOf('"');if(end>=0)fileName=rest.slice(0,end)}const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=fileName;document.body.appendChild(link);link.click();link.remove();s.textContent="Paquete generado y descarga iniciada · SHA-256: "+hash;s.className="sha ok"}catch(e){s.textContent="Error: "+e.message;s.className="sha bad"}finally{d.disabled=false}};review.onclick=async function(){review.disabled=true;result.textContent="Registrando revisión humana...";result.className="info";try{const v=await requestJson("/api/lb102/pilot-packages/"+encodeURIComponent(pkg.id)+"/review",{method:"POST",body:JSON.stringify({accepted:accepted.checked,criticalDefectsOpen:Number(critical.value||0),notes:notes.value})});result.textContent="Revisión registrada correctamente. SHA servidor: "+v.package.sha256;result.className="ok";await refreshStatus(false)}catch(e){result.textContent="Error: "+e.message;result.className="bad"}finally{review.disabled=false}};return a}
async function loadPackages(){const c=document.getElementById("packages");c.replaceChildren();try{const v=await requestJson("/api/lb102/pilot-packages");for(const p of v.packages)c.appendChild(createPackageCard(p))}catch(e){const p=field("p","Error: "+e.message);p.className="bad";c.appendChild(p)}}
async function decision(accepted){try{const rationale=document.getElementById("rationale").value;setText("decisionResult",accepted?"Registrando aceptación final...":"Registrando decisión de rechazo...","info");const v=await requestJson("/api/lb102/acceptance/decision",{method:"POST",body:JSON.stringify({accepted:accepted,rationale:rationale})});const nl=String.fromCharCode(10);setText("decisionResult",(accepted?"Decisión de aceptación registrada correctamente.":"Decisión de rechazo registrada correctamente.")+nl+JSON.stringify(v,null,2),"ok");await refreshStatus(false)}catch(e){setText("decisionResult","Error: "+e.message,"bad")}}
document.getElementById("loginButton").onclick=login;document.getElementById("password").onkeydown=function(e){if(e.key==="Enter")login()};document.getElementById("logoutButton").onclick=logout;document.getElementById("sourceStatusButton").onclick=refreshSourceStatus;document.getElementById("sessionButton").onclick=recordSession;document.getElementById("statusButton").onclick=function(){refreshStatus(false)};document.getElementById("acceptDecisionButton").onclick=function(){decision(true)};document.getElementById("rejectDecisionButton").onclick=function(){decision(false)};applyRole("VIEWER");(async function(){try{const v=await requestJson("/api/lb102/session/me");showActor(v.actor);await refreshSourceStatus();await loadPackages();await refreshStatus(false)}catch{}})();
</script></body></html>`;
