export type ConcessionGeneralTemplateKind = "PCAP" | "MEMORY" | "PPT" | "VIABILITY";
export type ConcessionGeneralTemplateSubtype = "SERVICE_CONCESSION" | "WORKS_CONCESSION";

export interface ConcessionGeneralTemplateManifestRecord {
  templateId:string;kind:ConcessionGeneralTemplateKind;fileName:string;mediaType:"application/vnd.oasis.opendocument.text";expectedSha256:string;expectedStyleFingerprint:string;provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE";officialModel:false;sourceAuthority:"LCSP_CONCESSION_PLUS_JDA_REAL_CASES_PUERTO_REAL_CFA"|"LCSP_247_250_PLUS_JDA_MALAGA_WORKS_CONCESSION_2025";subtype:ConcessionGeneralTemplateSubtype;humanValidationRequired:true;slots:readonly string[];
}

/** Perfil físico SERVICE_CONCESSION V1. No es modelo oficial. */
export const CONCESSION_GENERAL_TEMPLATE_MANIFEST: readonly ConcessionGeneralTemplateManifestRecord[] = [
  { templateId:"contrata-ia:concession:pcap:service:LB98-CONCESSION-GENERAL-ODT-V1", kind:"PCAP", fileName:"LB98_PCAP_SERVICE_CONCESSION_GENERAL_V1.odt", mediaType:"application/vnd.oasis.opendocument.text", expectedSha256:"76d6a9999bf77064c8a655feaaf54f9178df3066eac2d4583188b1b56d3c7a8f", expectedStyleFingerprint:"sha256:77f8c655234bfb810e20f3d39dfd09e5e2cf7d1609648facc1d987b50c8b5763", provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE", officialModel:false, sourceAuthority:"LCSP_CONCESSION_PLUS_JDA_REAL_CASES_PUERTO_REAL_CFA", subtype:"SERVICE_CONCESSION", humanValidationRequired:true, slots:["caseId","title","subtypeSummary","objectSummary","cpvSummary","lotsSummary","viabilitySummary","operationalRiskSummary","riskAllocationSummary","economicSummary","revenueTariffSummary","durationSummary","procedureSummary","solvencySummary","guaranteesSummary","awardCriteriaSummary","executionSummary","equilibriumSummary","interventionRescueSummary","modificationSummary","dataProtectionSummary"] },
  { templateId:"contrata-ia:concession:memory:service:LB98-CONCESSION-GENERAL-ODT-V1", kind:"MEMORY", fileName:"LB98_MEMORY_SERVICE_CONCESSION_GENERAL_V1.odt", mediaType:"application/vnd.oasis.opendocument.text", expectedSha256:"d64b5e6923d23d5b5824bb527e1222ec31cbcac001e09c438dab019b5ab53b90", expectedStyleFingerprint:"sha256:77f8c655234bfb810e20f3d39dfd09e5e2cf7d1609648facc1d987b50c8b5763", provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE", officialModel:false, sourceAuthority:"LCSP_CONCESSION_PLUS_JDA_REAL_CASES_PUERTO_REAL_CFA", subtype:"SERVICE_CONCESSION", humanValidationRequired:true, slots:["caseId","needSummary","objectSummary","concessionChoiceSummary","viabilitySummary","operationalRiskSummary","economicSummary","durationSummary","procedureSummary","executionSummary"] },
  { templateId:"contrata-ia:concession:ppt:service:LB98-CONCESSION-GENERAL-ODT-V1", kind:"PPT", fileName:"LB98_PPT_SERVICE_CONCESSION_GENERAL_V1.odt", mediaType:"application/vnd.oasis.opendocument.text", expectedSha256:"2786a0d0d584dcb4e1349be679ac2c314e38cd02abe06814ef22cb727fbe0ce2", expectedStyleFingerprint:"sha256:77f8c655234bfb810e20f3d39dfd09e5e2cf7d1609648facc1d987b50c8b5763", provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE", officialModel:false, sourceAuthority:"LCSP_CONCESSION_PLUS_JDA_REAL_CASES_PUERTO_REAL_CFA", subtype:"SERVICE_CONCESSION", humanValidationRequired:true, slots:["caseId","objectSummary","serviceTechnicalSummary","qualityContinuitySummary","userAccessSummary","tariffSummary","controlPolicePowersSummary","executionSummary"] },
  { templateId:"contrata-ia:concession:viability:service:LB98-CONCESSION-GENERAL-ODT-V1", kind:"VIABILITY", fileName:"LB98_VIABILITY_SERVICE_CONCESSION_GENERAL_V1.odt", mediaType:"application/vnd.oasis.opendocument.text", expectedSha256:"60bccd4c427b6da3a8317a9b8fa4ef6eb9af2b0f8c3c0060f0dcba6a20f9b035", expectedStyleFingerprint:"sha256:77f8c655234bfb810e20f3d39dfd09e5e2cf7d1609648facc1d987b50c8b5763", provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE", officialModel:false, sourceAuthority:"LCSP_CONCESSION_PLUS_JDA_REAL_CASES_PUERTO_REAL_CFA", subtype:"SERVICE_CONCESSION", humanValidationRequired:true, slots:["caseId","purposeSummary","demandForecastSummary","investmentFinancingSummary","costRevenueSummary","npvDiscountSummary","riskMatrixSummary","operationalRiskConclusion","stateAidSummary","viabilityConclusion"] },
] as const;
export function getConcessionGeneralTemplate(kind:ConcessionGeneralTemplateKind):ConcessionGeneralTemplateManifestRecord{const record=CONCESSION_GENERAL_TEMPLATE_MANIFEST.find(item=>item.kind===kind);if(!record)throw new Error(`No existe plantilla Concession para ${kind}.`);return record;}
