export const CONCESSION_VERTICAL_FIELD_MANIFEST = [
  { fieldPath:"concession.subtype", label:"Tipo de concesión", control:"SELECT", section:"QUALIFICATION", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.viabilityStudyApproved", label:"Estudio de viabilidad aprobado", control:"BOOLEAN", section:"VIABILITY", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.viabilityStudyConclusion", label:"Conclusión del estudio de viabilidad", control:"SELECT", section:"VIABILITY", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.demandRiskTransferred", label:"Transferencia de riesgo de demanda", control:"BOOLEAN", section:"RISK", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.supplyRiskTransferred", label:"Transferencia de riesgo de suministro/oferta", control:"BOOLEAN", section:"RISK", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.marketExposureReal", label:"Exposición real a incertidumbres del mercado", control:"BOOLEAN", section:"RISK", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.investmentRecoveryGuaranteed", label:"Recuperación de inversión garantizada", control:"BOOLEAN", section:"RISK", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.costRecoveryGuaranteed", label:"Recuperación de costes garantizada", control:"BOOLEAN", section:"RISK", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.potentialLossMoreThanNominal", label:"Pérdida potencial real no nominal", control:"BOOLEAN", section:"RISK", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.revenueModel", label:"Modelo de ingresos, retribución y tarifas", control:"TEXTAREA", section:"ECONOMICS", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.npvAnalysis", label:"VAN de inversiones, costes e ingresos y tasa de descuento", control:"TEXTAREA", section:"ECONOMICS", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.investmentPlan", label:"Inversiones y financiación", control:"TEXTAREA", section:"ECONOMICS", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.demandForecast", label:"Previsión de demanda", control:"TEXTAREA", section:"ECONOMICS", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.riskAllocation", label:"Distribución de riesgos entre Administración y concesionario", control:"TEXTAREA", section:"RISK", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.stateAidRelevant", label:"Existen ayudas relevantes para la viabilidad", control:"BOOLEAN", section:"VIABILITY", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.stateAidCompatibility", label:"Análisis de compatibilidad de ayuda de Estado", control:"TEXTAREA", section:"VIABILITY", requiredForWorkflowReview:false, humanValidationRequired:true },
  { fieldPath:"concession.tariffRegime", label:"Régimen de tarifas y actualización", control:"TEXTAREA", section:"EXECUTION", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.economicEquilibriumRegime", label:"Régimen de equilibrio económico", control:"TEXTAREA", section:"EXECUTION", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.interventionRescueRegime", label:"Secuestro/intervención y rescate", control:"TEXTAREA", section:"EXECUTION", requiredForWorkflowReview:true, humanValidationRequired:true },
  { fieldPath:"concession.publicServicePolicePowers", label:"Poderes de policía del servicio público cuando proceda", control:"TEXTAREA", section:"EXECUTION", requiredForWorkflowReview:true, humanValidationRequired:true },
] as const;
