import type { UniversalEvidenceRecord } from "../lb52/UniversalEvidenceWorkspace";
import { evaluateConcessionRiskOperational } from "./ConcessionRiskOperationalGate";
import { evaluateConcessionViabilityContent } from "./ConcessionViabilityContentGate";

export type ConcessionJourneyStageId="IDENTIFICATION"|"QUALIFICATION_RISK"|"VIABILITY"|"ECONOMICS"|"PROCEDURE"|"TECHNICAL"|"EXECUTION"|"FINAL_REVIEW"|"DOCUMENTS";
export interface ConcessionJourneyStage{id:ConcessionJourneyStageId;label:string;status:"COMPLETE"|"IN_PROGRESS"|"BLOCKED";applicablePaths:readonly string[];blockers:readonly string[];}
export interface ConcessionUserJourney{caseId:string;family:"CONCESSION";stages:readonly ConcessionJourneyStage[];currentStage:ConcessionJourneyStageId;blockers:readonly string[];riskOperationalReady:boolean;viabilityReady:boolean;readyForDocuments:boolean;humanValidationRequired:true;}
function f(r:UniversalEvidenceRecord,p:string){return r.fields[p];}function v(r:UniversalEvidenceRecord,p:string){return f(r,p)?.value;}
function usable(r:UniversalEvidenceRecord,p:string){const x=f(r,p);return Boolean(x)&&!["PENDING","SOURCE_CONFLICT","SYSTEM_PROPOSAL"].includes(x!.status)&&(x!.status==="NOT_APPLICABLE"||x!.value!==undefined);}
function validated(r:UniversalEvidenceRecord,p:string){const x=f(r,p);return Boolean(x)&&(x!.status==="NOT_APPLICABLE"||(x!.status==="HUMAN_VALIDATED"&&x!.humanValidated===true));}
function conflicts(r:UniversalEvidenceRecord,paths:readonly string[]){return paths.filter(p=>f(r,p)?.status==="SOURCE_CONFLICT").map(p=>`${p}: conflicto de fuentes pendiente de decisión humana.`);}
function stage(r:UniversalEvidenceRecord,id:ConcessionJourneyStageId,label:string,paths:readonly string[],extra:readonly string[]=[]):ConcessionJourneyStage{const c=[...conflicts(r,paths),...extra];return{id,label,applicablePaths:paths,status:c.length?"BLOCKED":paths.every(p=>usable(r,p))?"COMPLETE":"IN_PROGRESS",blockers:c};}

export function evaluateConcessionUserJourney(record:UniversalEvidenceRecord,physicalPackageReady=false,subtypePreparationBlockers:readonly string[]=[]):ConcessionUserJourney{
  const subtype=v(record,"concession.subtype")==="SERVICE_CONCESSION"||v(record,"concession.subtype")==="WORKS_CONCESSION"?v(record,"concession.subtype") as "SERVICE_CONCESSION"|"WORKS_CONCESSION":null;
  const identification=["contractType","need","object","cpvMain","administrative.contractingAuthority","lots.divisionIntoLots","concession.subtype"];
  const riskPaths=["concession.demandRiskTransferred","concession.supplyRiskTransferred","concession.marketExposureReal","concession.investmentRecoveryGuaranteed","concession.costRecoveryGuaranteed","concession.potentialLossMoreThanNominal","concession.riskAllocation"];
  const viabilityPaths=["concession.viabilityStudyApproved","concession.viabilityStudyConclusion","concession.demandForecast","concession.investmentPlan","concession.revenueModel","concession.npvAnalysis","concession.stateAidRelevant"];
  if(v(record,"concession.stateAidRelevant")===true)viabilityPaths.push("concession.stateAidCompatibility");
  const economics=["economic.legalEstimatedValueCents","durationMonths","concession.revenueModel","concession.npvAnalysis","concession.tariffRegime"];
  const procedure=["procedure","criteria.awardCriteria","criteria.economicSolvency","criteria.technicalSolvency","guarantees.provisionalGuaranteeRequired","concession.definitiveGuaranteeRegime"];
  const technical=["technical.technicalRequirements","technical.executionLocations","concession.qualityContinuityRegime","concession.userAccessRegime"];
  const execution=["execution.specialExecutionConditions","execution.subcontractingRegime","execution.specificPenalties","execution.plannedModificationRegime","concession.economicEquilibriumRegime","concession.interventionRescueRegime","concession.publicServicePolicePowers","concession.dataProtectionRegime"];
  if(subtype==="WORKS_CONCESSION"){
    technical.push("concession.works.projectSolution","concession.works.administrationFullyDefinesWorks","concession.works.anteprojectRequired","concession.works.planningUrbanContext","concession.works.environmentalAnalysis");
    execution.push("concession.works.reversionRegime","concession.works.financialEvaluationOfficeReportApplicable");
    if(v(record,"concession.works.anteprojectRequired")===true)technical.push("concession.works.anteprojectAvailable","concession.works.anteprojectApproved","concession.works.anteprojectPublicInformationCompleted");
    if(v(record,"concession.works.financialEvaluationOfficeReportApplicable")===true)execution.push("concession.works.financialEvaluationOfficeReportAvailable");
    if(v(record,"concession.works.administrationFullyDefinesWorks")===true){
      technical.push("concession.works.projectAvailable","works.projectExists","works.projectApproval","works.affectsStabilitySafetyOrWatertightness","works.supervisionReportAvailable","works.replanteoCompleted","works.terrainAvailabilityAccredited","works.workCategory","works.projectMemoryAvailable","works.projectPlansAvailable","works.projectTechnicalSpecificationsAvailable","works.projectBudgetMeasurementsAvailable","works.projectProgrammeAvailable","works.projectReplanteoReferencesAvailable","works.projectHealthSafetyStudyAvailable","works.projectOtherLegalDocumentsComplete");
    }
  }
  const conclusion=v(record,"concession.viabilityStudyConclusion");const stateAid=v(record,"concession.stateAidRelevant");
  const risk=evaluateConcessionRiskOperational({subtype,viabilityStudyApproved:v(record,"concession.viabilityStudyApproved")===true,viabilityStudyConcludesViable:conclusion==="VIABLE"?true:conclusion==="NOT_VIABLE"?false:null,demandRiskTransferred:v(record,"concession.demandRiskTransferred")===true,supplyRiskTransferred:v(record,"concession.supplyRiskTransferred")===true,marketExposureReal:v(record,"concession.marketExposureReal")===true,recoveryOfInvestmentGuaranteed:typeof v(record,"concession.investmentRecoveryGuaranteed")==="boolean"?v(record,"concession.investmentRecoveryGuaranteed") as boolean:null,recoveryOfCostsGuaranteed:typeof v(record,"concession.costRecoveryGuaranteed")==="boolean"?v(record,"concession.costRecoveryGuaranteed") as boolean:null,estimatedPotentialLossMoreThanNominal:v(record,"concession.potentialLossMoreThanNominal")===true,concessionRevenueModelDefined:Boolean(v(record,"concession.revenueModel")),netPresentValueAnalysisAvailable:Boolean(v(record,"concession.npvAnalysis")),stateAidRelevant:typeof stateAid==="boolean"?stateAid as boolean:null,stateAidCompatibilityAddressed:stateAid===false||Boolean(v(record,"concession.stateAidCompatibility"))});
  const viability=evaluateConcessionViabilityContent({subtype,concessionChoiceJustification:Boolean(v(record,"need")),demandForecast:Boolean(v(record,"concession.demandForecast")),investmentAndFinancingPlan:Boolean(v(record,"concession.investmentPlan")),operatingCostRevenueModel:Boolean(v(record,"concession.revenueModel")),netPresentValueAndDiscountRate:Boolean(v(record,"concession.npvAnalysis")),riskAllocationMatrix:Boolean(v(record,"concession.riskAllocation")),stateAidResolved:typeof stateAid==="boolean"&&(stateAid===false||Boolean(v(record,"concession.stateAidCompatibility")))});
  const stages:ConcessionJourneyStage[]=[
    stage(record,"IDENTIFICATION","Necesidad, objeto y subtipo concesional",identification),
    stage(record,"QUALIFICATION_RISK","Calificación y riesgo operacional",riskPaths,risk.blockers.filter(b=>!/viabilidad|VAN|ingresos|ayuda/i.test(b))),
    stage(record,"VIABILITY","Estudio de viabilidad",viabilityPaths,[...viability.blockers,...risk.blockers.filter(b=>/viabilidad|VAN|ingresos|ayuda/i.test(b))]),
    stage(record,"ECONOMICS","Economía concesional",economics),
    stage(record,"PROCEDURE","Procedimiento, solvencia y garantías",procedure),
    stage(record,"TECHNICAL",subtype==="WORKS_CONCESSION"?"Anteproyecto/proyecto, obra y explotación":"Prescripciones y explotación",technical,subtype==="WORKS_CONCESSION"?subtypePreparationBlockers:[]),
    stage(record,"EXECUTION","Tarifas, equilibrio, intervención y control",execution),
  ];
  const family=v(record,"contractType");const allPaths=[...new Set(stages.flatMap(s=>s.applicablePaths))];const familyBlock=family&&family!=="CONCESSION"?[`El expediente está clasificado como ${String(family)} y no puede tramitarse como concesión.`]:[];const businessComplete=stages.every(s=>s.status==="COMPLETE");const allValidated=allPaths.length>0&&allPaths.every(p=>validated(record,p));const finalBlockers=[...familyBlock];if(!businessComplete)finalBlockers.push("Quedan etapas concesionales pendientes o bloqueadas.");if(businessComplete&&!allValidated)finalBlockers.push("Todos los datos concesionales aplicables deben quedar validados humanamente antes de generar documentos.");stages.push({id:"FINAL_REVIEW",label:"Revisión final",applicablePaths:allPaths,status:finalBlockers.length?"IN_PROGRESS":"COMPLETE",blockers:finalBlockers});
  const documentBlockers:string[]=[];if(finalBlockers.length)documentBlockers.push("La revisión final no está completada.");if(!physicalPackageReady)documentBlockers.push("El paquete físico Concession no está acreditado para este expediente.");stages.push({id:"DOCUMENTS",label:"Documentos",applicablePaths:[],status:documentBlockers.length?"IN_PROGRESS":"COMPLETE",blockers:documentBlockers});
  const blockers=[...new Set([...familyBlock,...stages.flatMap(s=>s.blockers)])];return{caseId:record.caseId,family:"CONCESSION",stages,currentStage:stages.find(s=>s.status!=="COMPLETE")?.id??"DOCUMENTS",blockers,riskOperationalReady:risk.concessionQualificationSupported,viabilityReady:viability.complete&&risk.viabilityReady,readyForDocuments:documentBlockers.length===0,humanValidationRequired:true};
}
