import { createHash } from "node:crypto";
import type { UniversalEditableTemplateBinaryStore } from "../lb23/UniversalOdtProductionRenderer";
import { readOdtZip } from "../lb23/OdtPackageCodec";
import type { UniversalEvidenceRecord } from "../lb52/UniversalEvidenceWorkspace";
import { zipStoredFiles } from "../lb95/StoredZipPackage";
import { getConcessionGeneralTemplate } from "./ConcessionGeneralTemplateManifest";
import { renderConcessionGeneralTemplate } from "./ConcessionGeneralEditableTemplateRenderer";

export interface ConcessionUserDocumentPackage {
  ready:boolean;fileName:string|null;mediaType:"application/zip";bytes:Uint8Array|null;sha256:string|null;blockers:readonly string[];
  manifest:null|{caseId:string;profile:"SERVICE_CONCESSION_GENERAL_LB98";generatedAt:string;documents:readonly {kind:"PCAP"|"MEMORIA"|"PPT"|"VIABILITY";fileName:string;sha256:string;provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE";officialModel:false}[];crossDocumentAuditReady:true;operationalRiskAudited:true;viabilityAudited:true;humanAcceptanceRequired:true};
}
function hash(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex");}
function raw(r:UniversalEvidenceRecord,p:string){return r.fields[p]?.value;}function text(r:UniversalEvidenceRecord,p:string):string|null{const v=raw(r,p);if(v===null||v===undefined||v==="")return null;if(Array.isArray(v))return v.map(String).join("; ");return String(v);}function bool(r:UniversalEvidenceRecord,p:string):string|null{const v=raw(r,p);return typeof v==="boolean"?(v?"Sí":"No"):null;}function euro(r:UniversalEvidenceRecord,p:string):string|null{const v=raw(r,p);return typeof v==="number"&&Number.isSafeInteger(v)?`${new Intl.NumberFormat("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v/100)} €`:null;}function join(...xs:(string|null|undefined)[]){const p=xs.filter((x):x is string=>Boolean(x));return p.length?p.join(" · "):null;}function req(b:string[],s:string,v:string|null){if(v===null){b.push(`Falta valor validado para ${s}.`);return "";}return v;}function xmlText(bytes:Uint8Array){const e=readOdtZip(bytes).find(x=>x.name==="content.xml");return e?Buffer.from(e.bytes).toString("utf8").replace(/<[^>]+>/g," ").replace(/\s+/g," "):"";}
function lots(r:UniversalEvidenceRecord){const d=raw(r,"lots.divisionIntoLots");if(d===true)return join("División en lotes: sí",text(r,"lots.lots"));if(d===false)return join("División en lotes: no",text(r,"lots.noDivisionJustification"));return null;}

function buildValues(r:UniversalEvidenceRecord){const b:string[]=[];const object=text(r,"object"),cpv=text(r,"cpvMain"),ve=euro(r,"economic.legalEstimatedValueCents");const subtype=text(r,"concession.subtype");if(subtype!=="SERVICE_CONCESSION")b.push("El paquete físico LB98 V1 solo está acreditado para concesión de servicios.");const risk=join(`Riesgo demanda: ${bool(r,"concession.demandRiskTransferred")??""}`,`Riesgo suministro: ${bool(r,"concession.supplyRiskTransferred")??""}`,`Exposición mercado: ${bool(r,"concession.marketExposureReal")??""}`,`Recuperación inversión garantizada: ${bool(r,"concession.investmentRecoveryGuaranteed")??""}`,`Recuperación costes garantizada: ${bool(r,"concession.costRecoveryGuaranteed")??""}`,`Pérdida no nominal: ${bool(r,"concession.potentialLossMoreThanNominal")??""}`);const econ=join(ve&&`VE: ${ve}`,text(r,"concession.investmentPlan"),text(r,"concession.revenueModel"),text(r,"concession.npvAnalysis"));const viability=join(`Estudio aprobado: ${bool(r,"concession.viabilityStudyApproved")??""}`,text(r,"concession.viabilityStudyConclusion"));const duration=text(r,"durationMonths")?`${text(r,"durationMonths")} meses`:null;const execution=join(text(r,"concession.qualityContinuityRegime"),text(r,"execution.specialExecutionConditions"),text(r,"concession.publicServicePolicePowers"));const stateAid=raw(r,"concession.stateAidRelevant")===false?"No se declaran ayudas de Estado relevantes.":join("Existen ayudas relevantes",text(r,"concession.stateAidCompatibility"));
  const pcap:Record<string,string|number|boolean>={caseId:r.caseId,title:req(b,"title",object),subtypeSummary:req(b,"subtypeSummary",subtype),objectSummary:req(b,"objectSummary",object),cpvSummary:req(b,"cpvSummary",cpv),lotsSummary:req(b,"lotsSummary",lots(r)),viabilitySummary:req(b,"viabilitySummary",viability),operationalRiskSummary:req(b,"operationalRiskSummary",risk),riskAllocationSummary:req(b,"riskAllocationSummary",text(r,"concession.riskAllocation")),economicSummary:req(b,"economicSummary",econ),revenueTariffSummary:req(b,"revenueTariffSummary",join(text(r,"concession.revenueModel"),text(r,"concession.tariffRegime"))),durationSummary:req(b,"durationSummary",duration),procedureSummary:req(b,"procedureSummary",text(r,"procedure")),solvencySummary:req(b,"solvencySummary",join(text(r,"criteria.economicSolvency"),text(r,"criteria.technicalSolvency"))),guaranteesSummary:req(b,"guaranteesSummary",text(r,"concession.definitiveGuaranteeRegime")),awardCriteriaSummary:req(b,"awardCriteriaSummary",text(r,"criteria.awardCriteria")),executionSummary:req(b,"executionSummary",execution),equilibriumSummary:req(b,"equilibriumSummary",text(r,"concession.economicEquilibriumRegime")),interventionRescueSummary:req(b,"interventionRescueSummary",text(r,"concession.interventionRescueRegime")),modificationSummary:req(b,"modificationSummary",text(r,"execution.plannedModificationRegime")),dataProtectionSummary:req(b,"dataProtectionSummary",text(r,"concession.dataProtectionRegime"))};
  const memory:Record<string,string|number|boolean>={caseId:r.caseId,needSummary:req(b,"needSummary",text(r,"need")),objectSummary:req(b,"memory.objectSummary",object),concessionChoiceSummary:req(b,"concessionChoiceSummary",text(r,"need")),viabilitySummary:req(b,"memory.viabilitySummary",viability),operationalRiskSummary:req(b,"memory.operationalRiskSummary",risk),economicSummary:req(b,"memory.economicSummary",econ),durationSummary:req(b,"memory.durationSummary",duration),procedureSummary:req(b,"memory.procedureSummary",text(r,"procedure")),executionSummary:req(b,"memory.executionSummary",execution)};
  const ppt:Record<string,string|number|boolean>={caseId:r.caseId,objectSummary:req(b,"ppt.objectSummary",object),serviceTechnicalSummary:req(b,"serviceTechnicalSummary",text(r,"technical.technicalRequirements")),qualityContinuitySummary:req(b,"qualityContinuitySummary",text(r,"concession.qualityContinuityRegime")),userAccessSummary:req(b,"userAccessSummary",text(r,"concession.userAccessRegime")),tariffSummary:req(b,"tariffSummary",text(r,"concession.tariffRegime")),controlPolicePowersSummary:req(b,"controlPolicePowersSummary",text(r,"concession.publicServicePolicePowers")),executionSummary:req(b,"ppt.executionSummary",execution)};
  const viab:Record<string,string|number|boolean>={caseId:r.caseId,purposeSummary:req(b,"purposeSummary",text(r,"need")),demandForecastSummary:req(b,"demandForecastSummary",text(r,"concession.demandForecast")),investmentFinancingSummary:req(b,"investmentFinancingSummary",text(r,"concession.investmentPlan")),costRevenueSummary:req(b,"costRevenueSummary",text(r,"concession.revenueModel")),npvDiscountSummary:req(b,"npvDiscountSummary",text(r,"concession.npvAnalysis")),riskMatrixSummary:req(b,"riskMatrixSummary",text(r,"concession.riskAllocation")),operationalRiskConclusion:req(b,"operationalRiskConclusion",risk),stateAidSummary:req(b,"stateAidSummary",stateAid),viabilityConclusion:req(b,"viabilityConclusion",text(r,"concession.viabilityStudyConclusion"))};return{blockers:[...new Set(b)],pcap,memory,ppt,viab,audit:{object,cpv,ve,riskAllocation:text(r,"concession.riskAllocation"),npv:text(r,"concession.npvAnalysis")}};}

export async function generateConcessionUserDocumentPackage(input:{record:UniversalEvidenceRecord;templateStore:UniversalEditableTemplateBinaryStore}):Promise<ConcessionUserDocumentPackage>{const built=buildValues(input.record);if(built.blockers.length)return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,blockers:built.blockers,manifest:null};try{const cfgs=[{kind:"PCAP" as const,values:built.pcap,label:"PCAP"},{kind:"MEMORY" as const,values:built.memory,label:"Memoria"},{kind:"PPT" as const,values:built.ppt,label:"PPT"},{kind:"VIABILITY" as const,values:built.viab,label:"Estudio_Viabilidad"}];const docs=[] as Array<{kind:"PCAP"|"MEMORIA"|"PPT"|"VIABILITY";fileName:string;bytes:Uint8Array;sha256:string}>;for(const c of cfgs){const m=getConcessionGeneralTemplate(c.kind);const source=await input.templateStore.get(m.templateId);if(!source)throw new Error(`No está persistida la plantilla Concession ${c.kind}.`);const rendered=renderConcessionGeneralTemplate({manifest:m,templateBytes:source.bytes,values:c.values});docs.push({kind:c.kind==="MEMORY"?"MEMORIA":c.kind,fileName:`${c.label}_${input.record.caseId.replaceAll("/","-")}.odt`,bytes:rendered.bytes,sha256:rendered.sha256});}const texts=docs.map(d=>xmlText(d.bytes));const audit:string[]=[];for(const required of [built.audit.object,built.audit.cpv,built.audit.ve,built.audit.riskAllocation,built.audit.npv].filter((x):x is string=>Boolean(x)))if(!texts.some(t=>t.includes(required)))audit.push(`Auditoría cruzada Concession: no se materializa ${required}.`);if(audit.length)return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,blockers:audit,manifest:null};const manifest={caseId:input.record.caseId,profile:"SERVICE_CONCESSION_GENERAL_LB98" as const,generatedAt:new Date().toISOString(),documents:docs.map(d=>({kind:d.kind,fileName:d.fileName,sha256:d.sha256,provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE" as const,officialModel:false as const})),crossDocumentAuditReady:true as const,operationalRiskAudited:true as const,viabilityAudited:true as const,humanAcceptanceRequired:true as const};const zip=zipStoredFiles([...docs.map(d=>({name:d.fileName,bytes:d.bytes})),{name:"manifest.json",bytes:Buffer.from(JSON.stringify(manifest,null,2),"utf8")}]);return{ready:true,fileName:`Contrata-IA_${input.record.caseId.replaceAll("/","-")}_ServiceConcession_PCAP-Memoria-PPT-Viabilidad.zip`,mediaType:"application/zip",bytes:zip,sha256:hash(zip),blockers:[],manifest};}catch(error){return{ready:false,fileName:null,mediaType:"application/zip",bytes:null,sha256:null,blockers:[error instanceof Error?error.message:String(error)],manifest:null};}}
