import type { ConcessionGeneralTemplateKind, ConcessionGeneralTemplateManifestRecord } from "./ConcessionGeneralTemplateManifest";

/** Perfil físico WORKS_CONCESSION derivado de Contrata-IA. No reutiliza PCAP Works ordinario ni Service Concession. */
export const WORKS_CONCESSION_GENERAL_TEMPLATE_MANIFEST: readonly ConcessionGeneralTemplateManifestRecord[] = [
  {templateId:"contrata-ia:concession:pcap:works:LB98-WORKS-CONCESSION-GENERAL-ODT-V1",kind:"PCAP",fileName:"LB98_PCAP_WORKS_CONCESSION_GENERAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"a5b1dbf2191e99ded1a06981fde4bdc720a0299b06de0fdf1b8f1a2cb151649a",expectedStyleFingerprint:"sha256:bfb143e937d9f80ac3a5c4dedede36c6d4e28bdc3677440db58ad4bf357294b9",provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_247_250_PLUS_JDA_MALAGA_WORKS_CONCESSION_2025",subtype:"WORKS_CONCESSION",humanValidationRequired:true,slots:["caseId","title","objectSummary","cpvSummary","viabilitySummary","anteprojectProjectSummary","operationalRiskSummary","riskAllocationSummary","economicSummary","revenueTariffSummary","durationSummary","procedureSummary","solvencySummary","guaranteesSummary","awardCriteriaSummary","constructionExecutionSummary","exploitationSummary","equilibriumSummary","interventionRescueSummary","modificationSummary","reversionSummary","dataProtectionSummary"]},
  {templateId:"contrata-ia:concession:memory:works:LB98-WORKS-CONCESSION-GENERAL-ODT-V1",kind:"MEMORY",fileName:"LB98_MEMORY_WORKS_CONCESSION_GENERAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"c66bb816bee9b224472911f72852a82fd3431ba388907cdf8cceb693694669e2",expectedStyleFingerprint:"sha256:bfb143e937d9f80ac3a5c4dedede36c6d4e28bdc3677440db58ad4bf357294b9",provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_247_250_PLUS_JDA_MALAGA_WORKS_CONCESSION_2025",subtype:"WORKS_CONCESSION",humanValidationRequired:true,slots:["caseId","needSummary","objectSummary","concessionChoiceSummary","viabilitySummary","anteprojectProjectSummary","operationalRiskSummary","economicSummary","durationSummary","executionSummary"]},
  {templateId:"contrata-ia:concession:ppt:works:LB98-WORKS-CONCESSION-GENERAL-ODT-V1",kind:"PPT",fileName:"LB98_PPT_WORKS_CONCESSION_GENERAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"370cf9c6a8a405e0dcd1e568f0b3325be1fd02fb28539fdca139bf9052102135",expectedStyleFingerprint:"sha256:bfb143e937d9f80ac3a5c4dedede36c6d4e28bdc3677440db58ad4bf357294b9",provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_247_250_PLUS_JDA_MALAGA_WORKS_CONCESSION_2025",subtype:"WORKS_CONCESSION",humanValidationRequired:true,slots:["caseId","objectSummary","projectTechnicalSummary","constructionQualitySummary","healthSafetySummary","exploitationTechnicalSummary","tariffSummary","controlPolicePowersSummary","reversionSummary"]},
  {templateId:"contrata-ia:concession:viability:works:LB98-WORKS-CONCESSION-GENERAL-ODT-V1",kind:"VIABILITY",fileName:"LB98_VIABILITY_WORKS_CONCESSION_GENERAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"b9855bc0150e636cd79ee0e274be537d9b78af634d56d25a54927a067912fdc5",expectedStyleFingerprint:"sha256:bfb143e937d9f80ac3a5c4dedede36c6d4e28bdc3677440db58ad4bf357294b9",provenance:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_247_250_PLUS_JDA_MALAGA_WORKS_CONCESSION_2025",subtype:"WORKS_CONCESSION",humanValidationRequired:true,slots:["caseId","purposeSummary","demandForecastSummary","planningUrbanSummary","environmentalSummary","projectSolutionSummary","investmentFinancingSummary","costRevenueSummary","npvDiscountSummary","riskMatrixSummary","operationalRiskConclusion","stateAidSummary","viabilityConclusion"]},
] as const;

export function getWorksConcessionGeneralTemplate(kind:ConcessionGeneralTemplateKind):ConcessionGeneralTemplateManifestRecord{const record=WORKS_CONCESSION_GENERAL_TEMPLATE_MANIFEST.find(item=>item.kind===kind);if(!record)throw new Error(`No existe plantilla Works Concession para ${kind}.`);return record;}
