import type {UniversalSupplyAsaPlannedModificationDecision} from "../../../domain/expediente/UniversalExpedienteDomains";
export const LB115_PLANNED_MODIFICATION_VERSION="LB115-PLANNED-MODIFICATION-V1" as const;
const LCSP="https://www.boe.es/buscar/act.php?id=BOE-A-2017-12902";
export type PlannedModificationCause="BUDGET_STABILITY_DOWN"|"DA33_NEEDS_UP"|"OTHER";
export interface ModificationCauseInput {kind:PlannedModificationCause;description:string;scope:string;objectiveTrigger:string;limits:readonly string[]}
export interface PlannedModificationInput {contractType:"SUPPLY"|"SERVICE";needsBasedContractDa33:boolean;planned:boolean;planningBaseExVatCents:number;maximumAggregatePercent:number;declaredEstimatedValueExVatCents:number;causes:readonly ModificationCauseInput[];procedure:string;altersGlobalNature:boolean;introducesNewUnitPrices:boolean}
interface Basis{id:string;article:string;paragraph:string;relevantOfficialExcerpt:string;officialUrl:string}
export interface PlannedModificationResult {version:typeof LB115_PLANNED_MODIFICATION_VERSION;modificationPercent:number;modificationAmountExVatCents:number;structuredRegime:UniversalSupplyAsaPlannedModificationDecision;justification:string;procedure:string;noNewUnitPrices:true;estimatedValueTreatment:string;documentaryStatements:readonly {element:string;status:"APPLIES"|"NOT_APPLICABLE";text:string;destinations:readonly ("MEMORY"|"PCAP")[]}[];legalBasis:readonly Basis[];warnings:readonly string[];humanValidationRequired:true;generationBlocked:true;productionReady:false}
const basis=(id:string,article:string,paragraph:string,text:string):Basis=>({id,article,paragraph,relevantOfficialExcerpt:text,officialUrl:`${LCSP}#a${article.replace(/\D/g,"")}`});
const LEGAL=[basis("LCSP-101.2.c","101","2.c","Cuando se prevea la posibilidad de modificar el contrato, el valor estimado tendrá en cuenta el importe máximo que pueda alcanzar con todas las modificaciones al alza previstas."),basis("LCSP-203.2","203","2","Los contratos solo podrán modificarse durante su vigencia cuando se haya previsto conforme al artículo 204 o, excepcionalmente, concurra el artículo 205."),basis("LCSP-204.1","204","1","La modificación prevista puede alcanzar como máximo el veinte por ciento del precio inicial si el pliego advierte expresamente esta posibilidad."),basis("LCSP-204.1.a","204","1.a","La cláusula de modificación debe estar formulada de forma clara, precisa e inequívoca."),basis("LCSP-204.1.b","204","1.b","La cláusula debe precisar alcance, límites, naturaleza, condiciones objetivamente verificables y procedimiento."),basis("LCSP-204.1-PRECIO","204","1, párrafo segundo","La modificación no podrá establecer nuevos precios unitarios no previstos en el contrato."),basis("LCSP-204.2","204","2","La modificación prevista no puede alterar la naturaleza global del contrato inicial.")];
const clean=(v:string,label:string)=>{const x=String(v||"").trim();if(!x)throw new Error(`Falta ${label}.`);return x;};
export function evaluatePlannedModification(i:PlannedModificationInput):PlannedModificationResult{
 if(i.planned&&(!Number.isInteger(i.planningBaseExVatCents)||i.planningBaseExVatCents<=0))throw new Error("La base de planificación sin IVA debe ser positiva y expresarse en céntimos.");
 if(i.planned&&(!Number.isInteger(i.declaredEstimatedValueExVatCents)||i.declaredEstimatedValueExVatCents<=0))throw new Error("El valor estimado declarado debe ser positivo y expresarse en céntimos.");
 if(!Number.isFinite(i.maximumAggregatePercent)||i.maximumAggregatePercent<0||i.maximumAggregatePercent>20)throw new Error("El porcentaje máximo acumulado debe estar entre 0 y 20.");
 if(i.altersGlobalNature)throw new Error("Una modificación prevista no puede alterar la naturaleza global del contrato.");
 if(i.introducesNewUnitPrices)throw new Error("Una modificación prevista no puede establecer nuevos precios unitarios.");
 if(!i.planned&&(i.maximumAggregatePercent!==0||i.causes.length))throw new Error("Si no se prevén modificaciones, el porcentaje y las causas deben quedar a cero.");
 if(i.planned&&(i.maximumAggregatePercent<=0||!i.causes.length))throw new Error("Una modificación prevista exige porcentaje positivo y al menos una causa completa.");
 const seen=new Set<PlannedModificationCause>();const causes=i.causes.map((c,n)=>{if(seen.has(c.kind))throw new Error(`Causa duplicada: ${c.kind}.`);seen.add(c.kind);const x={...c,description:clean(c.description,`la descripción de la causa ${n+1}`),scope:clean(c.scope,`el alcance de la causa ${n+1}`),objectiveTrigger:clean(c.objectiveTrigger,`la condición objetiva de la causa ${n+1}`),limits:c.limits.map((v,j)=>clean(v,`el límite ${j+1} de la causa ${n+1}`))};if(!x.limits.length)throw new Error(`La causa ${n+1} debe incluir al menos un límite.`);return x;});
 const da33=causes.find(c=>c.kind==="DA33_NEEDS_UP");if(da33&&(i.contractType!=="SUPPLY"||!i.needsBasedContractDa33))throw new Error("La causa DA 33.ª solo procede en un suministro por necesidades expresamente validado.");
 const procedure=i.planned?clean(i.procedure,"el procedimiento para tramitar la modificación"):"No procede al no preverse modificaciones conforme al artículo 204 LCSP.";
 const amount=i.planned?Math.round(i.planningBaseExVatCents*i.maximumAggregatePercent/100):0;
 const upward=causes.some(c=>c.kind!=="BUDGET_STABILITY_DOWN");const minimumVe=i.planningBaseExVatCents+(upward?amount:0);if(i.planned&&upward&&i.declaredEstimatedValueExVatCents<minimumVe)throw new Error("El valor estimado no incorpora el importe máximo de las modificaciones al alza previstas.");
 const by=(k:PlannedModificationCause)=>causes.find(c=>c.kind===k);const describe=(c:ModificationCauseInput)=>`${c.description} Alcance: ${c.scope}. Condición objetiva: ${c.objectiveTrigger}. Límites: ${c.limits.join("; ")}.`;
 const stability=by("BUDGET_STABILITY_DOWN"),needs=by("DA33_NEEDS_UP"),other=by("OTHER");
 const structuredRegime:UniversalSupplyAsaPlannedModificationDecision={budgetStability:{applicable:!!stability,maximumPercent:stability?i.maximumAggregatePercent:0},needsDa33:{applicable:!!needs,maximumPercent:needs?i.maximumAggregatePercent:0,limits:needs?[needs.scope,needs.objectiveTrigger,...needs.limits]:[]},other:{applicable:!!other,description:other?describe(other):"No procede.",maximumPercent:other?i.maximumAggregatePercent:0,limits:other?[other.scope,other.objectiveTrigger,...other.limits]:[]}};
 const justification=i.planned?causes.map(describe).join(" "):"No se prevén modificaciones al amparo del artículo 204 LCSP; cualquier necesidad futura no prevista solo podrá examinarse, sin garantía de procedencia, conforme al régimen excepcional del artículo 205.";
 const ve=i.planned&&upward?`El valor estimado declarado incorpora hasta ${amount} céntimos sin IVA por modificaciones al alza previstas.`:"No existe incremento del valor estimado por modificaciones previstas al alza.";
 return{version:LB115_PLANNED_MODIFICATION_VERSION,modificationPercent:i.maximumAggregatePercent,modificationAmountExVatCents:amount,structuredRegime,justification,procedure,noNewUnitPrices:true,estimatedValueTreatment:ve,documentaryStatements:[{element:"PLANNED_MODIFICATION",status:i.planned?"APPLIES":"NOT_APPLICABLE",text:justification,destinations:["MEMORY","PCAP"]},{element:"MAXIMUM_AGGREGATE",status:i.planned?"APPLIES":"NOT_APPLICABLE",text:i.planned?`Máximo acumulado: ${i.maximumAggregatePercent} % de la base de planificación, equivalente a ${amount} céntimos sin IVA.`:"Porcentaje máximo: 0 %.",destinations:["MEMORY","PCAP"]},{element:"PROCEDURE",status:i.planned?"APPLIES":"NOT_APPLICABLE",text:procedure,destinations:["PCAP"]},{element:"NEW_UNIT_PRICES",status:"NOT_APPLICABLE",text:"No podrán establecerse nuevos precios unitarios no previstos en el contrato.",destinations:["PCAP"]},{element:"GLOBAL_NATURE",status:"NOT_APPLICABLE",text:"La modificación no podrá alterar la naturaleza global del contrato.",destinations:["MEMORY","PCAP"]},{element:"ESTIMATED_VALUE",status:i.planned&&upward?"APPLIES":"NOT_APPLICABLE",text:ve,destinations:["MEMORY","PCAP"]}],legalBasis:LEGAL,warnings:["Las modificaciones no previstas del artículo 205 no se redactan como una autorización genérica anticipada.","El porcentaje es un máximo acumulado y no un derecho automático a modificar el contrato.","Las variaciones de unidades que la LCSP excluya del concepto de modificación deben analizarse separadamente."],humanValidationRequired:true,generationBlocked:true,productionReady:false};
}
