import { createHash } from "node:crypto";
import { LB94_SUPPLY_GENERAL_RUNTIME_ASSETS, type PersistedTemplateAssetDescriptor } from "./HttpPersistedTemplateAssetStore";

export interface TemplateProvisioningInput { templateId: string; contentBase64: string; }
export interface TemplateProvisioningResult { templateId: string; kind: "PCAP" | "MEMORIA" | "PPT"; sha256: string; byteLength: number; persisted: true; }
type SupplyPersistedTemplateAssetDescriptor = PersistedTemplateAssetDescriptor & { kind: "PCAP" | "MEMORIA" | "PPT" };

function endpoint(value: string): string { const normalized=value.trim().replace(/\/+$/,"");if(!normalized.startsWith("https://"))throw new Error("El provisionado LB94 exige endpoint HTTPS.");return normalized; }
function decode(value:string):Uint8Array{if(!/^[A-Za-z0-9+/]*={0,2}$/.test(value)||value.length%4!==0)throw new Error("El archivo recibido no contiene base64 válido.");return Buffer.from(value,"base64");}
function hash(bytes:Uint8Array):string{return createHash("sha256").update(bytes).digest("hex");}
function descriptor(templateId:string):SupplyPersistedTemplateAssetDescriptor{const found=LB94_SUPPLY_GENERAL_RUNTIME_ASSETS.find(item=>item.templateId===templateId);if(!found)throw new Error("El templateId no pertenece al inventario físico LB94 autorizado.");if(found.kind==="VIABILITY")throw new Error("Un activo VIABILITY no pertenece al inventario Supply LB94.");return found as SupplyPersistedTemplateAssetDescriptor;}
function provenance(item:SupplyPersistedTemplateAssetDescriptor):Record<string,unknown>{if(item.provenanceRole==="OFFICIAL_MODEL")return{role:"OFFICIAL_MODEL",sourceId:item.sourceId,officialModelClaimed:true,exactBinaryIdentityVerified:true};return{role:"CONTRATA_IA_DERIVED_GENERAL_TEMPLATE",sourceId:item.sourceId,derivationVersion:"LB94-SUPPLY-GENERAL-ODT-V2",officialModelClaimed:false,exactBinaryIdentityVerified:true,humanValidationRequired:true};}

/** Provisionador Supply deliberadamente cerrado a PCAP/MEMORIA/PPT aunque el store universal admita VIABILITY desde LB98. */
export async function provisionSupplyTemplateAsset(input:TemplateProvisioningInput,environment:NodeJS.ProcessEnv=process.env):Promise<TemplateProvisioningResult>{const item=descriptor(input.templateId);const persistenceUrl=environment.CONTRATA_IA_PERSISTENCE_URL?.trim();const token=environment.CONTRATA_IA_PERSISTENCE_TOKEN?.trim();if(!persistenceUrl||!token)throw new Error("Falta configuración de persistencia para provisionar activos LB94.");const bytes=decode(input.contentBase64);if(bytes.byteLength<100||bytes.byteLength>2_000_000)throw new Error("Tamaño de activo LB94 fuera del rango permitido.");const actual=hash(bytes);if(actual!==item.sha256)throw new Error(`SHA-256 incorrecto para ${item.kind}; el archivo no es el activo exacto acreditado.`);const response=await fetch(`${endpoint(persistenceUrl)}/templates/${encodeURIComponent(item.templateId)}`,{method:"PUT",headers:{"content-type":"application/json; charset=utf-8","x-contrata-ia-persistence-token":token,accept:"application/json"},body:JSON.stringify({kind:item.kind,mediaType:"application/vnd.oasis.opendocument.text",sha256:item.sha256,styleFingerprint:item.styleFingerprint,provenance:provenance(item),contentBase64:input.contentBase64})});if(!response.ok){const body=await response.text();throw new Error(`Persistencia LB94 rechazó ${item.kind}: HTTP ${response.status}${body?` · ${body.slice(0,300)}`:""}`);}return{templateId:item.templateId,kind:item.kind,sha256:item.sha256,byteLength:bytes.byteLength,persisted:true};}
