import type { MixedComponentContractType } from "./MixedQualificationGate";
export interface MixedRealCaseEvidence{id:string;title:string;sourceUrl:string;componentTypes:readonly MixedComponentContractType[];principalContractType:MixedComponentContractType;principalRule:"HIGHEST_ESTIMATED_VALUE_SUPPLY_SERVICE";generalizable:false;genericTemplateAuthority:false;}

/** Expedientes reales sirven para regresión de calificación; no son una plantilla Mixed general. */
export const LB99_MIXED_REAL_CASES:readonly MixedRealCaseEvidence[]=[
  {id:"JDA-MIXED-SERVICE-PRINCIPAL-DOC-149562",title:"Expediente mixto Junta con servicios y suministros, prestación principal servicio",sourceUrl:"https://www.juntadeandalucia.es/haciendayadministracionpublica/apl/pdc_sirec_documentacion/rest/descargar/documento/149562",componentTypes:["SERVICE","SUPPLY"],principalContractType:"SERVICE",principalRule:"HIGHEST_ESTIMATED_VALUE_SUPPLY_SERVICE",generalizable:false,genericTemplateAuthority:false},
  {id:"JDA-MIXED-SUPPLY-PRINCIPAL-O365-DOC-18649",title:"Despliegue de funcionalidades de trabajo colaborativo O365 con suministros y servicios",sourceUrl:"https://www.juntadeandalucia.es/haciendayadministracionpublica/apl/pdc_sirec_documentacion/rest/descargar/documento/18649",componentTypes:["SUPPLY","SERVICE"],principalContractType:"SUPPLY",principalRule:"HIGHEST_ESTIMATED_VALUE_SUPPLY_SERVICE",generalizable:false,genericTemplateAuthority:false},
  {id:"JDA-EMPLOYMENT-MIXED-RENTING-MAINTENANCE-DOC-212781",title:"Renting de vehículo con mantenimiento integral, contrato mixto suministro-servicio",sourceUrl:"https://www.juntadeandalucia.es/haciendayadministracionpublica/apl/pdc_sirec_documentacion/rest/descargar/documento/212781",componentTypes:["SUPPLY","SERVICE"],principalContractType:"SUPPLY",principalRule:"HIGHEST_ESTIMATED_VALUE_SUPPLY_SERVICE",generalizable:false,genericTemplateAuthority:false},
] as const;

export function evaluateMixedPhysicalBaseline(){return{block:"LB99" as const,objective:"MIXED_LEGAL_COMPOSITION_WITHOUT_FAKE_GENERIC_TEMPLATE" as const,realSourceCoverage:true,art18QualificationGateReady:true,documentCompositionPlanReady:true,genericMixedTemplateAllowed:false as const,physicalComposerReady:false,engineeringClosed:false,productionReady:false as const,humanValidationRequired:true as const,cases:LB99_MIXED_REAL_CASES,blockers:["No existe ni se autoriza una plantilla genérica MIXED que borre la prestación principal y los regímenes de cada componente.","Falta acreditar compositor físico que parta del perfil administrativo gobernante y preserve overlays técnicos, de preparación, viabilidad y ejecución por componente."]};}
