export type MixedSupplyServiceProfile="SUPPLY_PRINCIPAL"|"SERVICE_PRINCIPAL";
export type MixedSupplyServiceTemplateKind="PCAP"|"MEMORY"|"PPT";
export interface MixedSupplyServiceTemplateManifestRecord{profile:MixedSupplyServiceProfile;kind:MixedSupplyServiceTemplateKind;templateId:string;fileName:string;mediaType:"application/vnd.oasis.opendocument.text";expectedSha256:string;expectedStyleFingerprint:string;provenance:"CONTRATA_IA_DERIVED_MIXED_SPECIALIZED_TEMPLATE";officialModel:false;sourceAuthority:"LCSP_18_34_122_PLUS_JDA_MIXED_SUPPLY_SERVICE_REAL_CASES";humanValidationRequired:true;slots:readonly string[];}
const STYLE="sha256:2e4f03faa90fdd91c942b39ae064e8d273d0d217c44f639fe84c47b95e62491f";
const PCAP_SLOTS=["caseId","title","objectSummary","componentsSummary","principalRegimeSummary","cpvSummary","lotsSummary","economicBreakdownSummary","procedureSummary","solvencySummary","awardCriteriaSummary","technicalOverlaySummary","effectsRegimeSummary","executionSummary","modificationSummary","dataProtectionSummary"] as const;
const MEMORY_SLOTS=["caseId","needSummary","objectSummary","componentsSummary","principalJustification","economicBreakdownSummary","procedureSummary","technicalCompositionSummary","executionRegimeSummary"] as const;
const PPT_SUPPLY=["caseId","objectSummary","supplyRequirements","serviceRequirements","integrationRequirements","acceptanceControl","executionLocations"] as const;
const PPT_SERVICE=["caseId","objectSummary","serviceRequirements","supplyRequirements","integrationRequirements","acceptanceControl","executionLocations"] as const;
export const MIXED_SUPPLY_SERVICE_TEMPLATE_MANIFEST:readonly MixedSupplyServiceTemplateManifestRecord[]=[
{profile:"SUPPLY_PRINCIPAL",kind:"PCAP",templateId:"contrata-ia:mixed:supply-service:supply-principal:pcap:LB99-V1",fileName:"LB99_PCAP_SUPPLY_SERVICE_SUPPLY_PRINCIPAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"020bf76025a92289877acc988ba9492fd071f7d6af06eca010b480ff17b4ce96",expectedStyleFingerprint:STYLE,provenance:"CONTRATA_IA_DERIVED_MIXED_SPECIALIZED_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_18_34_122_PLUS_JDA_MIXED_SUPPLY_SERVICE_REAL_CASES",humanValidationRequired:true,slots:PCAP_SLOTS},
{profile:"SUPPLY_PRINCIPAL",kind:"MEMORY",templateId:"contrata-ia:mixed:supply-service:supply-principal:memory:LB99-V1",fileName:"LB99_MEMORY_SUPPLY_SERVICE_SUPPLY_PRINCIPAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"1266b6a30d9fa03986e1b40c447d183bd1193dfcbe0d98069add5556ba9ca409",expectedStyleFingerprint:STYLE,provenance:"CONTRATA_IA_DERIVED_MIXED_SPECIALIZED_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_18_34_122_PLUS_JDA_MIXED_SUPPLY_SERVICE_REAL_CASES",humanValidationRequired:true,slots:MEMORY_SLOTS},
{profile:"SUPPLY_PRINCIPAL",kind:"PPT",templateId:"contrata-ia:mixed:supply-service:supply-principal:ppt:LB99-V1",fileName:"LB99_PPT_SUPPLY_SERVICE_SUPPLY_PRINCIPAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"87af447879f8d94db29a1c885d8fa9b6450589c42a69f26b8ee093dd8a97c82e",expectedStyleFingerprint:STYLE,provenance:"CONTRATA_IA_DERIVED_MIXED_SPECIALIZED_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_18_34_122_PLUS_JDA_MIXED_SUPPLY_SERVICE_REAL_CASES",humanValidationRequired:true,slots:PPT_SUPPLY},
{profile:"SERVICE_PRINCIPAL",kind:"PCAP",templateId:"contrata-ia:mixed:supply-service:service-principal:pcap:LB99-V1",fileName:"LB99_PCAP_SUPPLY_SERVICE_SERVICE_PRINCIPAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"74730760d4ade757a2aed8f0de69df1449e83ab0fa1bfedb518a5b2d8fca4953",expectedStyleFingerprint:STYLE,provenance:"CONTRATA_IA_DERIVED_MIXED_SPECIALIZED_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_18_34_122_PLUS_JDA_MIXED_SUPPLY_SERVICE_REAL_CASES",humanValidationRequired:true,slots:PCAP_SLOTS},
{profile:"SERVICE_PRINCIPAL",kind:"MEMORY",templateId:"contrata-ia:mixed:supply-service:service-principal:memory:LB99-V1",fileName:"LB99_MEMORY_SUPPLY_SERVICE_SERVICE_PRINCIPAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"749b2180f181010651e5d8d5ef3f4fcd4fb18e60c5e829b78958d05d2a149918",expectedStyleFingerprint:STYLE,provenance:"CONTRATA_IA_DERIVED_MIXED_SPECIALIZED_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_18_34_122_PLUS_JDA_MIXED_SUPPLY_SERVICE_REAL_CASES",humanValidationRequired:true,slots:MEMORY_SLOTS},
{profile:"SERVICE_PRINCIPAL",kind:"PPT",templateId:"contrata-ia:mixed:supply-service:service-principal:ppt:LB99-V1",fileName:"LB99_PPT_SUPPLY_SERVICE_SERVICE_PRINCIPAL_V1.odt",mediaType:"application/vnd.oasis.opendocument.text",expectedSha256:"6055e1676b0b86b02d665daf2d7a66b0e1031e3e88779fb54ace568e8ea28f92",expectedStyleFingerprint:STYLE,provenance:"CONTRATA_IA_DERIVED_MIXED_SPECIALIZED_TEMPLATE",officialModel:false,sourceAuthority:"LCSP_18_34_122_PLUS_JDA_MIXED_SUPPLY_SERVICE_REAL_CASES",humanValidationRequired:true,slots:PPT_SERVICE},
] as const;
export function getMixedSupplyServiceTemplate(profile:MixedSupplyServiceProfile,kind:MixedSupplyServiceTemplateKind){const item=MIXED_SUPPLY_SERVICE_TEMPLATE_MANIFEST.find(x=>x.profile===profile&&x.kind===kind);if(!item)throw new Error(`No existe perfil físico Mixed ${profile}/${kind}.`);return item;}
