import type { UniversalEvidenceRecord } from "../lb52/UniversalEvidenceWorkspace";
import { buildMixedDocumentCompositionPlan,type MixedConcessionSubtype } from "./MixedDocumentCompositionPlan";
import { evaluateMixedQualification,type MixedQualificationComponent,type MixedComponentContractType } from "./MixedQualificationGate";

export type MixedJourneyStageId="IDENTIFICATION"|"COMPONENTS"|"QUALIFICATION"|"PREPARATION"|"EXECUTION"|"FINAL_REVIEW"|"DOCUMENTS";
export interface MixedJourneyStage{id:MixedJourneyStageId;label:string;status:"COMPLETE"|"IN_PROGRESS"|"BLOCKED";blockers:readonly string[];}
export interface MixedUserJourney{caseId:string;family:"MIXED";stages:readonly MixedJourneyStage[];currentStage:MixedJourneyStageId;qualification:ReturnType<typeof evaluateMixedQualification>;composition:ReturnType<typeof buildMixedDocumentCompositionPlan>;readyForDocuments:boolean;blockers:readonly string[];humanValidationRequired:true;}
function f(r:UniversalEvidenceRecord,p:string){return r.fields[p];}function v(r:UniversalEvidenceRecord,p:string){return f(r,p)?.value;}
function validated(r:UniversalEvidenceRecord,p:string){const x=f(r,p);return Boolean(x)&&(x!.status==="NOT_APPLICABLE"||(x!.status==="HUMAN_VALIDATED"&&x!.humanValidated===true));}
function boolOrNull(r:UniversalEvidenceRecord,p:string){const x=v(r,p);return typeof x==="boolean"?x:null;}
function moneyOrNull(r:UniversalEvidenceRecord,p:string){const x=v(r,p);return typeof x==="number"&&Number.isSafeInteger(x)&&x>=0?x:null;}
function typeOrNull(x:unknown):MixedComponentContractType|null{return x==="SUPPLY"||x==="SERVICE"||x==="WORKS"||x==="CONCESSION"?x:null;}
function parseComponents(value:unknown):{components:MixedQualificationComponent[];blockers:string[]}{const blockers:string[]=[];if(!Array.isArray(value))return{components:[],blockers:["mixed.components debe contener una lista de prestaciones diferenciadas."]};const components:MixedQualificationComponent[]=[];for(const [index,item] of value.entries()){if(!item||typeof item!=="object"||Array.isArray(item)){blockers.push(`Componente ${index+1}: estructura inválida.`);continue;}const r=item as Record<string,unknown>;const contractType=typeOrNull(r.contractType);const id=typeof r.id==="string"?r.id.trim():"";const ve=r.estimatedValueExVatCents===null?null:typeof r.estimatedValueExVatCents==="number"&&Number.isSafeInteger(r.estimatedValueExVatCents)&&r.estimatedValueExVatCents>=0?r.estimatedValueExVatCents:null;if(!contractType)blockers.push(`Componente ${index+1}: tipo contractual no válido.`);if(!id)blockers.push(`Componente ${index+1}: falta identificador.`);if(r.estimatedValueExVatCents!==null&&ve===null)blockers.push(`Componente ${index+1}: valor estimado inválido.`);if(contractType&&id)components.push({id,contractType,estimatedValueExVatCents:ve,functionallyLinked:r.functionallyLinked===true,complementaryRelationship:r.complementaryRelationship===true});}return{components,blockers};}

export function evaluateMixedUserJourney(record:UniversalEvidenceRecord,physicalCompositionReady=false):MixedUserJourney{
  const parsed=parseComponents(v(record,"mixed.components"));const declared=typeOrNull(v(record,"mixed.principalContractType"));const concessionSubtype=(v(record,"mixed.concessionSubtype")==="SERVICE_CONCESSION"||v(record,"mixed.concessionSubtype")==="WORKS_CONCESSION"?v(record,"mixed.concessionSubtype"):null) as MixedConcessionSubtype|null;
  const qualification=evaluateMixedQualification({components:parsed.components,declaredPrincipalContractType:declared,objectivelySeparable:boolOrNull(record,"mixed.objectivelySeparable"),singleContractChosen:boolOrNull(record,"mixed.singleContractChosen"),nonConcessionThresholdExceeded:boolOrNull(record,"mixed.nonConcessionThresholdExceeded"),effectsRegimeSeparatedByComponent:v(record,"mixed.effectsRegimeSeparatedByComponent")===true,worksElementValueCents:moneyOrNull(record,"mixed.worksElementValueCents"),worksProjectAvailable:v(record,"mixed.worksProjectAvailable")===true,concessionViabilityStudyAvailable:v(record,"mixed.concessionViabilityStudyAvailable")===true,concessionAnteprojectResolved:boolOrNull(record,"mixed.concessionAnteprojectResolved")});
  const composition=buildMixedDocumentCompositionPlan({qualification,components:parsed.components,concessionSubtype});const stages:MixedJourneyStage[]=[];
  const familyBlock=v(record,"contractType")&&v(record,"contractType")!=="MIXED"?[`El expediente está clasificado como ${String(v(record,"contractType"))} y no puede tramitarse por el vertical Mixed.`]:[];
  const identificationPaths=["contractType","need","object","cpvMain","administrative.contractingAuthority"];
  stages.push({id:"IDENTIFICATION",label:"Necesidad y objeto mixto",status:familyBlock.length?"BLOCKED":identificationPaths.every(p=>validated(record,p))?"COMPLETE":"IN_PROGRESS",blockers:familyBlock});
  stages.push({id:"COMPONENTS",label:"Prestaciones y valores separados",status:parsed.blockers.length?"BLOCKED":validated(record,"mixed.components")?"COMPLETE":"IN_PROGRESS",blockers:parsed.blockers});
  const qPaths=["mixed.effectsRegimeSeparatedByComponent"];if(parsed.components.some(c=>c.contractType==="CONCESSION")){qPaths.push("mixed.objectivelySeparable","mixed.concessionSubtype","mixed.concessionViabilityStudyAvailable","mixed.concessionAnteprojectResolved");if(v(record,"mixed.objectivelySeparable")===true)qPaths.push("mixed.singleContractChosen");if(v(record,"mixed.objectivelySeparable")===true&&v(record,"mixed.singleContractChosen")===true)qPaths.push("mixed.nonConcessionThresholdExceeded");}if(qualification.principalContractType&&!(parsed.components.length===2&&parsed.components.some(c=>c.contractType==="SUPPLY")&&parsed.components.some(c=>c.contractType==="SERVICE")))qPaths.push("mixed.principalContractType");
  stages.push({id:"QUALIFICATION",label:"Prestación principal y régimen de adjudicación",status:qualification.blockers.length?"BLOCKED":qPaths.every(p=>validated(record,p))?"COMPLETE":"IN_PROGRESS",blockers:qualification.blockers});
  const prepPaths:string[]=[];if(parsed.components.some(c=>c.contractType==="WORKS")){prepPaths.push("mixed.worksElementValueCents");if(qualification.projectRequired)prepPaths.push("mixed.worksProjectAvailable");}
  stages.push({id:"PREPARATION",label:"Proyecto y viabilidad por componente",status:prepPaths.length===0?"COMPLETE":prepPaths.every(p=>validated(record,p))?"COMPLETE":"IN_PROGRESS",blockers:[]});
  stages.push({id:"EXECUTION",label:"Régimen de efectos por prestación",status:validated(record,"mixed.effectsRegimeSeparatedByComponent")?"COMPLETE":"IN_PROGRESS",blockers:[]});
  const businessComplete=stages.every(s=>s.status==="COMPLETE");const finalBlockers:string[]=[];if(!businessComplete)finalBlockers.push("Quedan decisiones o validaciones del contrato mixto pendientes.");if(!composition.ready)finalBlockers.push(...composition.blockers);stages.push({id:"FINAL_REVIEW",label:"Revisión final de composición",status:finalBlockers.length?"IN_PROGRESS":"COMPLETE",blockers:[...new Set(finalBlockers)]});
  const documentBlockers:string[]=[];if(finalBlockers.length)documentBlockers.push("La revisión final Mixed no está completada.");if(!physicalCompositionReady)documentBlockers.push("El compositor físico Mixed todavía no está acreditado; no se genera una plantilla mixta genérica.");stages.push({id:"DOCUMENTS",label:"Documentos compuestos",status:documentBlockers.length?"IN_PROGRESS":"COMPLETE",blockers:documentBlockers});
  const blockers=[...new Set(stages.flatMap(s=>s.blockers))];return{caseId:record.caseId,family:"MIXED",stages,currentStage:stages.find(s=>s.status!=="COMPLETE")?.id??"DOCUMENTS",qualification,composition,readyForDocuments:documentBlockers.length===0,blockers,humanValidationRequired:true};
}
