import { UniversalCapability } from "./UniversalContractCoverage";

export type ReuseDisposition = "REUSE" | "REUSE_WITH_BOUNDARY" | "KNOWLEDGE_ONLY" | "SPECIALIZED_REFERENCE" | "MISSING_UNIVERSAL_COMPONENT";
export interface RepositoryCapabilityInventoryItem { capability: UniversalCapability; disposition: ReuseDisposition; existingAssets: readonly string[]; universalComponent?: string; constraints: readonly string[]; }

/** Inventario ejecutable: antes de crear un motor se acredita si ya existe infraestructura reutilizable. */
export const REPOSITORY_CAPABILITY_INVENTORY: readonly RepositoryCapabilityInventoryItem[] = [
  { capability: "OBJECT_AND_NEED", disposition: "REUSE", existingAssets: ["src/engines/ObjetoEngine.ts", "knowledge/rules/objeto.rules.json"], universalComponent: "ObjetoEngine", constraints: ["La decisión sobre lotes permanece separada y requiere hechos/motivación del expediente."] },
  { capability: "CPV", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/CPVEngine.ts", "src/domain/cpv/CPVMatcher.ts"], universalComponent: "CPVEngine", constraints: ["Clasificación léxica local; propuesta siempre sujeta a validación humana."] },
  { capability: "LOTS", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalLotsEngine.ts", "src/application/normative/LB4CleaningServiceEngine.ts", "src/domain/expediente/UniversalExpedienteV13.ts"], universalComponent: "UniversalLotsEngine", constraints: ["No fabrica motivación de no división y distingue el subtipo de concesión antes de aplicar reglas."] },
  { capability: "ECONOMICS", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalEconomicEngine.ts", "src/engines/UniversalWorksEconomicEngine.ts", "src/engines/UniversalConcessionEconomicEngine.ts"], universalComponent: "UniversalEconomicEngine + family economic profiles", constraints: ["El núcleo común conserva PBL/VE/componentes; obras incorpora proyecto/suministros puestos a disposición y concesiones cifra neta de negocios sin doble contabilización."] },
  { capability: "PROCEDURE", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/ProcedimientoEngine.ts", "src/engines/UniversalConcessionProcedureEngine.ts", "knowledge/rules/procedimiento.rules.json"], universalComponent: "ProcedimientoEngine + UniversalConcessionProcedureEngine", constraints: ["La ruta concesional excluye el art. 159 y no habilita negociación/diálogo sin supuesto legal y factual documentado."] },
  { capability: "SOLVENCY", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/SolvenciaEngine.ts", "knowledge/rules/solvencia.rules.json", "knowledge/rules/solvencia.rules.yaml"], universalComponent: "SolvenciaEngine", constraints: ["No fabricar medios/umbrales concretos salvo conclusión legal cerrada; la configuración del expediente es humana."] },
  { capability: "PUBLICITY", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/PublicidadEngine.ts", "knowledge/rules/publicidad.rules.json"], universalComponent: "PublicidadEngine", constraints: ["Distinguir obligación jurídica de publicidad de la plataforma institucional concreta."] },
  { capability: "AWARD_CRITERIA", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalAwardCriteriaEngine.ts", "knowledge/rules/criterios.rules.yaml", "src/application/normative/LB4CleaningServiceEngine.ts"], universalComponent: "UniversalAwardCriteriaEngine", constraints: ["Valida criterios aportados por el expediente; no inventa criterios, ponderaciones ni fórmulas."] },
  { capability: "GUARANTEES", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalGuaranteeEngine.ts", "src/application/normative/LB4CleaningServiceEngine.ts"], universalComponent: "UniversalGuaranteeEngine", constraints: ["Distingue Administración Pública, concesiones, ASA, acuerdos marco/SDA y excepciones; validación humana obligatoria."] },
  { capability: "EXECUTION", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalExecutionEngine.ts", "src/engines/UniversalWorksExecutionEngine.ts", "src/engines/UniversalConcessionExecutionEngine.ts", "knowledge/rules/ejecucion.rules.yaml"], universalComponent: "UniversalExecutionEngine + family execution profiles", constraints: ["Obras añade replanteo/certificaciones/recepción; concesiones preservan riesgo, explotación, equilibrio y controles sin fabricar cláusulas materiales."] },
  { capability: "MODIFICATIONS", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalModificationEngine.ts", "src/engines/UniversalEconomicEngine.ts", "src/domain/expediente/UniversalExpedienteV13.ts", "protected supply DA33 pipeline"], universalComponent: "UniversalModificationEngine", constraints: ["El art. 205 nunca se autocierra; la DA33 mantiene sus guardas y no se extrapola a otras familias."] },
  { capability: "PRICE_REVISION", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalPriceRevisionEngine.ts", "src/domain/expediente/UniversalExpedienteV13.ts"], universalComponent: "UniversalPriceRevisionEngine", constraints: ["Evalúa procedencia abstracta y guardas; no fabrica fórmula ni índice oficial."] },
  { capability: "REMEDIES", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalRemediesEngine.ts"], universalComponent: "UniversalRemediesEngine", constraints: ["Cubre ámbito contractual del recurso especial; acto recurrible, legitimación, plazo y órgano quedan fuera hasta su módulo específico."] },
  { capability: "DOCUMENT_MODEL_SELECTION", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/CanonicalDocumentProfileSelector.ts", "src/domain/documentModel/ContractDocumentModelProfile.ts", "src/domain/documentModel/definitions/WorksPcapDefinition.ts"], universalComponent: "CanonicalDocumentProfileSelector", constraints: ["Un perfil real solo puede generar si sus activos/modelos están registrados y aprobados; obras dispone por ahora de estructura, no FULL_MODEL físico."] },
  { capability: "EDITABLE_DOCUMENT_GENERATION", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalDocumentGenerationGate.ts", "src/engines/UniversalPhysicalDocumentGenerationGate.ts", "src/domain/documentModel/EditableTemplateAssetRegistry.ts", "protected supply ODT renderers", "LB5/LB6 document pipeline"], universalComponent: "UniversalPhysicalDocumentGenerationGate", constraints: ["La generación física exige FULL_MODEL, activo ODT/DOCX verificado, SHA y huella de estilo; un PDF o estructura lógica no habilitan generación."] },
  { capability: "CROSS_DOCUMENT_AUDIT", disposition: "REUSE_WITH_BOUNDARY", existingAssets: ["src/engines/UniversalCrossDocumentAudit.ts", "src/engines/UniversalAdministrativePackageAudit.ts", "protected supply package cross audit", "canonical/universal document gates"], universalComponent: "UniversalAdministrativePackageAudit", constraints: ["Exige Memoria-PCAP-PPT y hechos mínimos comunes; añade identidad de proyecto, riesgo/viabilidad o prestación principal según familia."] },
] as const;

export function getCapabilityInventory(capability: UniversalCapability): RepositoryCapabilityInventoryItem {
  const item = REPOSITORY_CAPABILITY_INVENTORY.find(candidate => candidate.capability === capability);
  if (!item) throw new Error(`Capacidad no inventariada: ${capability}`);
  return item;
}

export function getMissingUniversalCapabilities(): readonly RepositoryCapabilityInventoryItem[] {
  return REPOSITORY_CAPABILITY_INVENTORY.filter(item => item.disposition === "MISSING_UNIVERSAL_COMPONENT" || item.disposition === "KNOWLEDGE_ONLY" || item.disposition === "SPECIALIZED_REFERENCE");
}
