import { CanonicalContractType } from "../expediente/CanonicalExpedienteState";
import { DocumentType } from "../documentModel/DocumentType";

/** Matriz conservadora de cobertura universal. */
export type UniversalTargetContractType = Exclude<CanonicalContractType, "OTHER">;
export type UniversalCapability = "OBJECT_AND_NEED"|"CPV"|"LOTS"|"ECONOMICS"|"PROCEDURE"|"SOLVENCY"|"PUBLICITY"|"AWARD_CRITERIA"|"GUARANTEES"|"EXECUTION"|"MODIFICATIONS"|"PRICE_REVISION"|"REMEDIES"|"DOCUMENT_MODEL_SELECTION"|"EDITABLE_DOCUMENT_GENERATION"|"CROSS_DOCUMENT_AUDIT";
export type UniversalCoverageStatus = "VALIDATED_ENGINE"|"AVAILABLE_WITH_HUMAN_VALIDATION"|"PARTIAL_SOURCE_BACKED"|"SOURCE_REFERENCE_ONLY"|"NOT_IMPLEMENTED";
export interface CapabilityCoverage { capability:UniversalCapability;status:UniversalCoverageStatus;criticalForOperationalClaim:boolean;evidence:readonly string[];notes:readonly string[]; }
export interface ContractFamilyCoverage { contractType:UniversalTargetContractType;requiredDocuments:readonly DocumentType[];capabilities:readonly CapabilityCoverage[];realSourceCoverage:"VALIDATED_CASE"|"REAL_SOURCES_AVAILABLE"|"LEGAL_SOURCE_ONLY"|"MISSING"; }
const COMMON_DOCUMENTS=[DocumentType.MEMORY,DocumentType.PCAP,DocumentType.PPT] as const;
const CORE_CAPABILITIES:readonly UniversalCapability[]=["OBJECT_AND_NEED","CPV","LOTS","ECONOMICS","PROCEDURE","SOLVENCY","PUBLICITY","AWARD_CRITERIA","GUARANTEES","EXECUTION","MODIFICATIONS","PRICE_REVISION","REMEDIES","DOCUMENT_MODEL_SELECTION","EDITABLE_DOCUMENT_GENERATION","CROSS_DOCUMENT_AUDIT"];
function capability(name:UniversalCapability,status:UniversalCoverageStatus,evidence:readonly string[],notes:readonly string[]=[]):CapabilityCoverage{return{capability:name,status,criticalForOperationalClaim:CORE_CAPABILITIES.includes(name),evidence,notes};}
const TRANSVERSAL={lots:capability("LOTS","AVAILABLE_WITH_HUMAN_VALIDATION",["UniversalLotsEngine"],["No inventa motivación y exige subtipo cuando la concesión lo requiere."]),award:capability("AWARD_CRITERIA","AVAILABLE_WITH_HUMAN_VALIDATION",["UniversalAwardCriteriaEngine","criterios.rules.yaml"],["Valida criterios aportados; no crea ponderaciones ni fórmulas."]),guarantees:capability("GUARANTEES","AVAILABLE_WITH_HUMAN_VALIDATION",["UniversalGuaranteeEngine"],["Distingue ASA, régimen ordinario, concesiones y otros supuestos especiales."]),modifications:capability("MODIFICATIONS","AVAILABLE_WITH_HUMAN_VALIDATION",["UniversalModificationEngine"],["Art. 205 permanece siempre sujeto a revisión jurídica individual."]),priceRevision:capability("PRICE_REVISION","AVAILABLE_WITH_HUMAN_VALIDATION",["UniversalPriceRevisionEngine"],["No fabrica fórmula ni índices."]),remedies:capability("REMEDIES","AVAILABLE_WITH_HUMAN_VALIDATION",["UniversalRemediesEngine"],["Cubre solo el ámbito contractual del recurso especial; no sustituye el análisis del acto concreto."])} as const;

export const UNIVERSAL_CONTRACT_COVERAGE:readonly ContractFamilyCoverage[]=[
{contractType:"SUPPLY",requiredDocuments:COMMON_DOCUMENTS,realSourceCoverage:"VALIDATED_CASE",capabilities:[capability("OBJECT_AND_NEED","VALIDATED_ENGINE",["ObjetoEngine","golden supply DA33"]),capability("CPV","AVAILABLE_WITH_HUMAN_VALIDATION",["CPVEngine","CPVMatcher"]),TRANSVERSAL.lots,capability("ECONOMICS","VALIDATED_ENGINE",["UniversalEconomicEngine","CONTR/2026/240267"]),capability("PROCEDURE","VALIDATED_ENGINE",["ProcedimientoEngine"]),capability("SOLVENCY","AVAILABLE_WITH_HUMAN_VALIDATION",["SolvenciaEngine"]),capability("PUBLICITY","AVAILABLE_WITH_HUMAN_VALIDATION",["PublicidadEngine"]),TRANSVERSAL.award,TRANSVERSAL.guarantees,capability("EXECUTION","PARTIAL_SOURCE_BACKED",["UniversalExpedienteV13","ejecucion.rules.yaml"]),TRANSVERSAL.modifications,TRANSVERSAL.priceRevision,TRANSVERSAL.remedies,capability("DOCUMENT_MODEL_SELECTION","AVAILABLE_WITH_HUMAN_VALIDATION",["CanonicalDocumentProfileSelector"]),capability("EDITABLE_DOCUMENT_GENERATION","PARTIAL_SOURCE_BACKED",["protected supply pipeline"]),capability("CROSS_DOCUMENT_AUDIT","PARTIAL_SOURCE_BACKED",["protected supply package audit"])]},
{contractType:"SERVICE",requiredDocuments:[DocumentType.MEMORY,DocumentType.PCAP,DocumentType.PPT,DocumentType.MEANS_INSUFFICIENCY_REPORT],realSourceCoverage:"REAL_SOURCES_AVAILABLE",capabilities:[capability("OBJECT_AND_NEED","VALIDATED_ENGINE",["ObjetoEngine"]),capability("CPV","AVAILABLE_WITH_HUMAN_VALIDATION",["CPVEngine","service real sources"]),TRANSVERSAL.lots,capability("ECONOMICS","PARTIAL_SOURCE_BACKED",["UniversalEconomicEngine","service sources"]),capability("PROCEDURE","VALIDATED_ENGINE",["ProcedimientoEngine"]),capability("SOLVENCY","AVAILABLE_WITH_HUMAN_VALIDATION",["SolvenciaEngine"]),capability("PUBLICITY","AVAILABLE_WITH_HUMAN_VALIDATION",["PublicidadEngine"]),TRANSVERSAL.award,TRANSVERSAL.guarantees,capability("EXECUTION","PARTIAL_SOURCE_BACKED",["CARL cleaning case"]),TRANSVERSAL.modifications,TRANSVERSAL.priceRevision,TRANSVERSAL.remedies,capability("DOCUMENT_MODEL_SELECTION","PARTIAL_SOURCE_BACKED",["service physical profile"]),capability("EDITABLE_DOCUMENT_GENERATION","PARTIAL_SOURCE_BACKED",["LB96 package"]),capability("CROSS_DOCUMENT_AUDIT","PARTIAL_SOURCE_BACKED",["LB96 package audit"])]},
{contractType:"WORKS",requiredDocuments:COMMON_DOCUMENTS,realSourceCoverage:"REAL_SOURCES_AVAILABLE",capabilities:[capability("OBJECT_AND_NEED","AVAILABLE_WITH_HUMAN_VALIDATION",["ObjetoEngine","LB97 Works"]),capability("CPV","AVAILABLE_WITH_HUMAN_VALIDATION",["CPVEngine"]),TRANSVERSAL.lots,capability("ECONOMICS","PARTIAL_SOURCE_BACKED",["LB97 Works package"]),capability("PROCEDURE","AVAILABLE_WITH_HUMAN_VALIDATION",["ProcedimientoEngine"]),capability("SOLVENCY","AVAILABLE_WITH_HUMAN_VALIDATION",["SolvenciaEngine"]),capability("PUBLICITY","AVAILABLE_WITH_HUMAN_VALIDATION",["PublicidadEngine"]),TRANSVERSAL.award,TRANSVERSAL.guarantees,capability("EXECUTION","PARTIAL_SOURCE_BACKED",["WorksPreparationGate","WorksProjectContentGate"]),TRANSVERSAL.modifications,TRANSVERSAL.priceRevision,TRANSVERSAL.remedies,capability("DOCUMENT_MODEL_SELECTION","PARTIAL_SOURCE_BACKED",["LB97 Works profiles"]),capability("EDITABLE_DOCUMENT_GENERATION","PARTIAL_SOURCE_BACKED",["LB97 Works package"]),capability("CROSS_DOCUMENT_AUDIT","PARTIAL_SOURCE_BACKED",["LB97 Works package audit"])]},
{contractType:"CONCESSION",requiredDocuments:COMMON_DOCUMENTS,realSourceCoverage:"REAL_SOURCES_AVAILABLE",capabilities:[
capability("OBJECT_AND_NEED","AVAILABLE_WITH_HUMAN_VALIDATION",["ObjetoEngine","Puerto Real service concession","Málaga parking works concession"]),
capability("CPV","AVAILABLE_WITH_HUMAN_VALIDATION",["CPVEngine"]),TRANSVERSAL.lots,
capability("ECONOMICS","PARTIAL_SOURCE_BACKED",["ConcessionRiskOperationalGate","ConcessionViabilityContentGate","LB98 Service Concession E2E"],["SERVICE_CONCESSION dispone de riesgo/viabilidad y paquete físico; WORKS_CONCESSION conserva overlay específico pendiente de paquete físico."]),
capability("PROCEDURE","PARTIAL_SOURCE_BACKED",["ProcedimientoEngine","real concession cases"],["Debe verificarse aplicabilidad según subtipo, valor y características del expediente."]),
capability("SOLVENCY","PARTIAL_SOURCE_BACKED",["SolvenciaEngine","LB98 package"]),capability("PUBLICITY","AVAILABLE_WITH_HUMAN_VALIDATION",["PublicidadEngine"]),TRANSVERSAL.award,TRANSVERSAL.guarantees,
capability("EXECUTION","PARTIAL_SOURCE_BACKED",["ConcessionRiskOperationalGate","ConcessionVerticalFieldManifest","WorksConcessionPreparationGate"],["Tarifas, equilibrio, intervención, rescate y poderes de policía están modelados con validación humana; falta perfil físico Works Concession."]),
capability("MODIFICATIONS","PARTIAL_SOURCE_BACKED",["UniversalModificationEngine","LB98 package"],["No puede neutralizarse el riesgo operacional mediante modificación o reequilibrio automático."]),TRANSVERSAL.priceRevision,TRANSVERSAL.remedies,
capability("DOCUMENT_MODEL_SELECTION","PARTIAL_SOURCE_BACKED",["Puerto Real","Málaga","ConcessionPhysicalBaseline"],["No existe modelo recomendado general de Junta; selección por subtipo y fuente real."]),
capability("EDITABLE_DOCUMENT_GENERATION","PARTIAL_SOURCE_BACKED",["LB98 SERVICE_CONCESSION four-document package"],["Operativo para SERVICE_CONCESSION; WORKS_CONCESSION no se genera con el PCAP de servicios ni con el PCAP Works ordinario."]),
capability("CROSS_DOCUMENT_AUDIT","PARTIAL_SOURCE_BACKED",["LB98 Service Concession E2E"],["Audita objeto, CPV, VE, riesgo y VAN en SERVICE_CONCESSION; overlay Works pendiente de paquete físico."])]},
{contractType:"MIXED",requiredDocuments:COMMON_DOCUMENTS,realSourceCoverage:"REAL_SOURCES_AVAILABLE",capabilities:[capability("OBJECT_AND_NEED","PARTIAL_SOURCE_BACKED",["CARL cleaning mixed service/supply case"]),capability("CPV","AVAILABLE_WITH_HUMAN_VALIDATION",["CPVEngine"]),TRANSVERSAL.lots,capability("ECONOMICS","PARTIAL_SOURCE_BACKED",["CARL cleaning mixed service/supply case","UniversalEconomicEngine"]),capability("PROCEDURE","PARTIAL_SOURCE_BACKED",["ProcedimientoEngine","art. 18 LCSP"]),capability("SOLVENCY","PARTIAL_SOURCE_BACKED",["SolvenciaEngine"]),capability("PUBLICITY","AVAILABLE_WITH_HUMAN_VALIDATION",["PublicidadEngine"]),TRANSVERSAL.award,capability("GUARANTEES","PARTIAL_SOURCE_BACKED",["UniversalGuaranteeEngine"]),capability("EXECUTION","NOT_IMPLEMENTED",[],["Falta orquestación de obligaciones heterogéneas."]),capability("MODIFICATIONS","PARTIAL_SOURCE_BACKED",["UniversalModificationEngine"]),capability("PRICE_REVISION","PARTIAL_SOURCE_BACKED",["UniversalPriceRevisionEngine"]),TRANSVERSAL.remedies,capability("DOCUMENT_MODEL_SELECTION","NOT_IMPLEMENTED",[],["Falta selector mixto formal."]),capability("EDITABLE_DOCUMENT_GENERATION","NOT_IMPLEMENTED",[]),capability("CROSS_DOCUMENT_AUDIT","NOT_IMPLEMENTED",[])]}
] as const;
export interface UniversalCoverageGap{contractType:UniversalTargetContractType;capability:UniversalCapability;status:UniversalCoverageStatus;reason:string;}
export function getContractFamilyCoverage(contractType:UniversalTargetContractType):ContractFamilyCoverage{const coverage=UNIVERSAL_CONTRACT_COVERAGE.find(item=>item.contractType===contractType);if(!coverage)throw new Error(`Cobertura no registrada para ${contractType}`);return coverage;}
export function getOperationalCoverageGaps(contractType?:UniversalTargetContractType):readonly UniversalCoverageGap[]{const families=contractType?[getContractFamilyCoverage(contractType)]:UNIVERSAL_CONTRACT_COVERAGE;return families.flatMap(family=>family.capabilities.filter(item=>item.criticalForOperationalClaim&&item.status!=="VALIDATED_ENGINE"&&item.status!=="AVAILABLE_WITH_HUMAN_VALIDATION").map(item=>({contractType:family.contractType,capability:item.capability,status:item.status,reason:item.notes[0]??`Cobertura ${item.status} todavía insuficiente para una afirmación operativa universal.`})));}
export function canClaimUniversalOperationalCoverage():boolean{return getOperationalCoverageGaps().length===0;}
